### ISSUE TITLE
Error while running CodeQL with Python

### ISSUE THREAD

**Issue by DanOpi** [github/codeql#10037]
Hello all!

Running into some issues trying to get CodeQL working with a sample Python project.

I was hitting a `tkinter` issue prior to this one but installing `python3-tk` seemed to alleviate that.

Using the following action and have it set up like so:

```yaml
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
          ram: 8192

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
```

Versions:

Python: 3.9.13
Python Extractor: 5.26
CodeQL Action: 2.1.18
CodeQL:  2.10.2

Error:

```bash
Error: 8-12 02:15:02] [build-stdout] [ERROR] [4] Exception extracting module /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/asyncio/base_events.py: FlowNode(<class 'semmle.python.ast.Tuple'> at 1279) is not in graph
  [2022-08-12 02:15:02] [build-stdout] [TRACEBACK] [4] "semmle/python/passes/flow.py", line 488, in _walk_scope
  [2022-08-12 02:15:02] [build-stdout] [TRACEBACK] [4] "semmle/python/passes/flow.py", line 292, in unroll
  [2022-08-12 02:15:02] [build-stdout] [TRACEBACK] [4] "semmle/python/passes/unroller.py", line 101, in do_unrolling
  [2022-08-12 02:15:02] [build-stdout] [TRACEBACK] [4] "semmle/graph.py", line 693, in unroll
  [2022-08-12 02:15:02] [build-stdout] [TRACEBACK] [4] "semmle/graph.py", line 576, in dominated_by
```

Failure Error from Action:

> Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220728/x64/codeql/codeql with arguments database,run-queries,--ram=8192,--threads=8,/runner/_work/_temp/codeql_databases/python,--min-disk-free=1024,-v,/runner/_work/_temp/codeql_databases/python-queries-builtin.qls.

I did see #4496 but it sounded like that similar issue was fixed in the Python Extractor Version 5.13 and I'm hitting this issue with version 5.26.

Can certainly move this over to the CodeQL Action Repo if needed but seems like I'm running into an issue with the underlying CodeQL piece itself.  

Thank you and appreciate the help!

**Comment by MathiasVP** [comment]
Hi @DanOpi,

Thank you for raising this issue. I've informed the CodeQL Python team about it, and hopefully, they'll help you resolve it soon 🤞.

**Comment by tausbn** [comment]
I apologise for the (very) late reply. It seems this issue got lost in the cracks somehow. 😞 

As far as I can tell, this has been fixed for a long time now (a fix was merged on August 16th), so I'm going to close this issue. If you're still experiencing this problem, please feel free to reopen the issue.

**Comment by Karthims7** [comment]
Can someone please help me check this issue

```
##[warning] Error running analysis for python: Error: Error running the 'database analyze' CodeQL command (2)
A fatal error occurred: python-security-extended.qls is not a .ql file, .qls file, a directory, or a query pack specification.

##[warning] Error: Error running the 'database analyze' CodeQL command (2)
##[warning] Error: Error running the 'database analyze' CodeQL command (2)
    at g.databaseAnalyze (/home/ubuntu/myagent/_work/_tasks/AdvancedSecurity-Codeql-Analyze_a9efc1ef-3900-494f-a460-963e3f5f6928/1.1.349/index.js:1:83569)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async t.Analyze.runQueries (/home/ubuntu/myagent/_work/_tasks/AdvancedSecurity-Codeql-Analyze_a9efc1ef-3900-494f-a460-963e3f5f6928/1.1.349/index.js:1:64208)
    at async /home/ubuntu/myagent/_work/_tasks/AdvancedSecurity-Codeql-Analyze_a9efc1ef-3900-494f-a460-963e3f5f6928/1.1.349/index.js:1:72572
##[warning] Error running analysis for python: Error: Error running the 'database analyze' CodeQL command (2)
##[error]Error running analysis for python: Error: Error running the 'database analyze' CodeQL command (2)

```
