### ISSUE TITLE
General issue: Excessive Comments (and General Poor Performance)

### ISSUE THREAD

**Issue by muppetjones** [github/codeql#10179]
**Description of the issue**

* After a commit, an excessive number of comments may be added -- each may have a different number of "issues" identified.
* Ignoring an issue _may_ cause another comment to be posted, but sometimes the number of issues increases
* Ignoring an issue (for whatever reason) is tedious and slow: The page may take a moment to register the change, then the page reloads, leaving you to scroll back down to where you were.
* Ignoring an issue keeps the issue in place -- only changing the dropdown option to "reopen", which only makes it harder to cut through the noise and identify actual issues.
* The links to the "files changed" tab are not usable. The "issue" may be reported on code that did not actually change, so the link changes to the tab but not the "alert" comment. On code that _did_ change, the page changes to the tab almost immediately, but can take quite some time to "scroll" down to the issue. Additionally, the "comment" is often absent even on code that did change.

<table><tr><td>
<img width="333" alt="Screen Shot 2022-08-25 at 11 06 44 AM" src="https://user-images.githubusercontent.com/2041619/186721279-f99a89d4-2e2c-4905-a5cd-115de7896493.png">
</td><td>
<img width="327" alt="Screen Shot 2022-08-25 at 11 06 34 AM" src="https://user-images.githubusercontent.com/2041619/186721284-9851170e-2ef2-4602-a3b0-0be0b4c2e72d.png">
</td><td>
<img width="325" alt="Screen Shot 2022-08-25 at 11 06 23 AM" src="https://user-images.githubusercontent.com/2041619/186721285-f390802d-e36d-4905-ac9a-fb685d3df916.png">
</td><td>
<img width="329" alt="Screen Shot 2022-08-25 at 11 06 09 AM" src="https://user-images.githubusercontent.com/2041619/186721286-7312d499-dceb-4266-ba24-da5247ffcfc3.png">
</td></tr></table>

**Comment by sj** [comment]
Thanks for the report! We're aware of this issue and are investigating what might be causing it.

**Comment by sj** [comment]
@muppetjones: could you help us with links to the PRs in which you noticed that behaviour?

**Comment by muppetjones** [comment]
> @muppetjones: could you help us with links to the PRs in which you noticed that behaviour?

Unfortunately, I can't -- it's a private repo.

**Comment by anaarmas** [comment]
Hi @muppetjones! We have now finished deploying some changes that should bring the excessive amount of reviews from code-scanning down to normal. Please do let us know if you continue to experience that particular problem 🙏 🙇

**Comment by sj** [comment]
Closing this — do reopen it if you're still seeing this behaviour!
