### ISSUE TITLE
Useless upcast - false positive

### ISSUE THREAD

**Issue by mikeclayton** [github/codeql#10172]
Code scanning currently gives a "Useless upcast" warning for both ```(Base)``` casts in the following code (see it [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AGQEs8BHAbmuoBuAQyj0AzhBxQwMegF56AUTw4AtjChDgAGxjNFqgA4YAngB4IwAFYwwGAHwAKAJR8qw0ewwxVY+eMlpPQBlGF07R2p6aPF5e1ixAHcvMAALKJiAbwyYmJVtbTj6DFSoCET6PBgKgEk8YW12ABMAeUMNIQx2CDxFBBljbrwXNBzc+gAiAEEJoscAISExGGcqiqmRsdyJ+dm5eIWllbX6ec2qcZiAfSKSsoqTuobmto6unr6B9+HnMYBfaiufg0EinI7UbJUAFUaikehTeggMHLCHUaGw0HzRHImCoqHUIA) in sharplab.io:)

```csharp
using System;
using System.Linq;

var source = Enumerable.Empty<string>();
var items = source.Select(
    s => s switch
    {
        "A" => (Base)new A(),
        "B" => (Base)new B(),
        _ => throw new InvalidOperationException()
    }
);

class Base
{
}

class A : Base
{
}

class B : Base
{
}
```

However, removing both ```(Base)``` casts results in this (see [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AGQEs8BHAbmuoBuAQyj0AzhBxQwMegF56AUTw4AtjChDgAGxjNFqgA4YAngB4IwAFYwwGAHwAKAJR8qw0ewwxVY+eMlpPQBlGF07R2p6aPF5e1ixAHcvMAALKJiAbwyYmJVtbTj6DFSoCET6PBgKgEk8YW12ABMAeUMNIQx2CDxFBBljbrwXNBzc+gAiAEEJoqqKqZGx3ImAIVm5ePn6VaWqcZiAfSKSsortuobmto6unr6Bu+HnMYBfald+GhIdoTEYajZKjvKjUUj0Kb0EC/f6A6ggsE/VZQmEAqhAkFAA==)):

> error CS0411: The type arguments for method 'Enumerable.Select<TSource, TResult>(IEnumerable<TSource>, Func<TSource, int, TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

It's fine to remove *one* of the casts because the return type can be inferred from the remaining cast, but removing both as suggested by Code Scanning will give a compiler error.

**Comment by aibaars** [comment]
You're right that the code does not compile when removing both casts. A cast operation is a runtime check and in this case we know beforehand that the checks will always succeed. However, the cast expression also affect the type inference. It might be better to add a type annotation to `var items` instead of adding two casts. Something like:
```
Base items = source.Select(
    s => s switch
    {
        "A" => (Base)new A(),
        "B" => (Base)new B(),
        _ => throw new InvalidOperationException()
    }
);
```

**Comment by mikeclayton** [comment]
@aibaars - thanks for the quick response.

It'd be nice if the C# compiler could infer the common base class without the casts, but I guess there's good reasons for it not already doing that, so I'll probably go with your first suggestion - in general I'm a bit of a ```var``` junkie and I'm allergic to type annotations, but in this case my ```string``` is actually a more complex generic type so the ```Select<..., Base>``` approach would be a lot longer and uglier :-).

I'm happy for this issue to be closed if there's no value in keeping it open from the Code Scanning perspective.
