### ISSUE TITLE
getIndexOfStmt return None

### ISSUE THREAD

**Issue by icy17** [github/codeql#10287]
I want to get some statements' index, so I use **getIndexOfStmt** like:evil.getEnclosingFunction().getBlock().getIndexOfStmt(rt).
But result is None.Could you tell me where I made a mistake?
PS: Or is there a way to know the index relationship between two statements (expression)? I want to know if one function was called before the other

**Comment by jketema** [comment]
Hi

I'm assuming your question is about C/C++, as that's the only language for which the QL library has a `getIndexOfStmt` predicate.

> But result is None.Could you tell me where I made a mistake?

This is very hard to tell without seeing the code you're trying to reason about. Do note that the statement you're interested in might occur in a block that is not a direct child of the enclosing function (think for example of a block that is the body of a loop and a statement that occurs in that loop body).

> Or is there a way to know the index relationship between two statements (expression)? I want to know if one function was called before the other

There's `ControlFlowNode` and `getASuccessor`. It should be possible to do some `stmt.(ControlFlowNode).getASuccessor()`. Note that the transitive closure of `getASuccessor`, which you might need, might be fairly expensive to compute.

**Comment by icy17** [comment]
> Hi
> 
> I'm assuming your question is about C/C++, as that's the only language for which the QL library has a `getIndexOfStmt` predicate.
> 
> > But result is None.Could you tell me where I made a mistake?
> 
> This is very hard to tell without seeing the code you're trying to reason about. Do note that the statement you're interested in might occur in a block that is not a direct child of the enclosing function (think for example of a block that is the body of a loop and a statement that occurs in that loop body).
> 
> > Or is there a way to know the index relationship between two statements (expression)? I want to know if one function was called before the other
> 
> There's `ControlFlowNode` and `getASuccessor`. It should be possible to do something like `stmt.(ControlFlowNode).getASuccessor()`. Note that the transitive closure of `getASuccessor`, which you might need, might be fairly expensive to compute.

Thanks！I understand！It's very helpful !!!

**Comment by jketema** [comment]
You're welcome.
