### ISSUE TITLE
Java: Query timeout after upgrading from library version 0.3.3 to 0.3.4

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#10303]
**Description of the issue**
After upgrading the CodeQL Git submodule of my project from tag `codeql-cli/v2.10.3` to `codeql-cli/v2.10.4` (therefore from Java library version 0.3.3 to 0.3.4) a certain query is timing out for me.

Previously the execution finished in a few seconds:
```
Compiling queries in <test-dir>/api-visibility-issues.
Executing tests in <test-dir>/api-visibility-issues.
[55/91 eval 2.4s] PASSED <test-dir>/api-visibility-issues.qlref
```
([GitHub Actions log](https://github.com/Marcono1234/codeql-java-queries/runs/8177932199?check_suite_focus=true#step:9:215))

Now it consistently times out after 5 minutes (both for GitHub Actions and locally):
```
 +Timeout (5m0s) in api-visibility-issues#09cf2679::getATypeExposingElement#6#fffffff
[90/91 comp 4.3s eval 5m3s] FAILED(EXECUTION) <test-dir>/api-visibility-issues.qlref
```
([GitHub Actions log](https://github.com/Marcono1234/codeql-java-queries/runs/8189796749?check_suite_focus=true#step:9:395))

It looks like the upgrade from CodeQL CLI version 2.10.3 to 2.10.4 is not responsible for this. Locally when I ran the test with CodeQL CLI 2.10.4 but the Git submodule at tag `codeql-cli/v2.10.3` no timeout occurred. (Though feel free to verify this yourself in case I made a mistake in my setup.)

When I run the query locally against a small test database and cancel it after some time the "CodeQL Query Server" output contains the following summary:
```
Most expensive predicates for unfinished query api-visibility-issues.ql:
        time  | evals |  max @ iter | predicate
        ------|-------|-------------|----------
           1s |       |             | api-visibility-issues#09cf2679::getAnInheritedMethod#1#ff#antijoin_rhs@140f8d4f
        713ms |       |             | api-visibility-issues#09cf2679::getAnInheritedMethod#1#ff#higher_order_body#1@d75caamj
        249ms |       |             | api-visibility-issues#09cf2679::getAnElementExposedByMember#4#fffff@d0afcch6
        140ms |       |             | Visibility#eddc36f2::Visibility::getLower#1#dispred#bff_201#join_rhs@41612dc9
        102ms |       |             | FileSystem#fd75716c::Container::getExtension#0#dispred#ff@3bc1f9t0
        101ms |    19 | 98ms @ 1    | num#Type#6144c3fd::TTypeParam#fff@ad295wg1
         97ms |       |             | num#TopLevelVisibility#60c72f95::TTopLevelPublic#f@5b4a1e7g
         92ms |       |             | FileSystem#fd75716c::Container::getStem#0#dispred#ff@043bb6i1
         82ms |       |             | num#TopLevelVisibility#60c72f95::TTopLevelSelectiveModules#ff@096fe6vh
         81ms |       |             | Element#c53922e0::Element::hasName#ff@8278b78a
         69ms |       |             | Member#9eba3c33::overridesIgnoringAccess#4#ffff_1023#join_rhs@febfc5ok
         68ms |       |             | project#Member#9eba3c33::overridesIgnoringAccess#4@76d81es4
         67ms |       |             | num#Type#6144c3fd::TGenericType#ff@983629gl
         65ms |     5 | 37ms @ 2    | Location#77b33c41::Top::toString#0#dispred#ff@5e6b06lq
         59ms |       |             | api-visibility-issues#09cf2679::getAnElementExposedByMember#4#fffff_10234#join_rhs@3bb580c4
         56ms |       |             | api-visibility-issues#09cf2679::getAnInheritedMethod#1#ff#shared@5a9d27ia
         44ms |       |             | Visibility#eddc36f2::Visibility::getLower#1#dispred#bff@2822cb3r
         39ms |       |             | num#Visibility#eddc36f2::TProtected#ff@19b5e3j5
         39ms |       |             | num#Visibility#eddc36f2::TPublic#f@d5b605cf
         38ms |       |             | num#Visibility#eddc36f2::TPrivate#f@eba7e7jd
         37ms |       |             | num#Visibility#eddc36f2::TPackagePrivate#f@3cb2d8pa
         33ms |       |             | Location#77b33c41::fixedHasLocation#3#fff@c88015of
         28ms |       |             | num#TopLevelVisibility#60c72f95::TTopLevelAllModules#f@42934bgu
         28ms |       |             | api-visibility-issues#09cf2679::getAnInheritedMethod#1#ff@e42860og
         26ms |    21 | 11ms @ 2    | Member#9eba3c33::Callable::paramUpTo#bff@6c5f82at
         24ms |       |             | Location#77b33c41::fixedHasLocation#3#fff#join_rhs@305020ev
         24ms |       |             | Visibility#eddc36f2::getMemberVisibility#1#ff@968039tl
         23ms |       |             | methods_5#join_rhs@ebcc262t
         23ms |    13 | 14ms @ 3    | Type#6144c3fd::hasSubtypeStar1#2#ff#reorder_1_0@8ae3d2wm
         23ms |       |             | Location#77b33c41::hasName#2#ff@04909fnv
         22ms |       |             | api-visibility-issues#09cf2679::getAnInheritedMethod#1#ff#higher_order_body@03dde3ae
         21ms |       |             | Generics#716e7108::ParameterizedType::getTypeArgument#1#dispred#fff@a88b3drc
         21ms |       |             | typeBounds_10#join_rhs@219271f8
         19ms |       |             | Member#9eba3c33::Callable::getStringSignature#0#dispred#ff@6902803k
         19ms |       |             | api-visibility-issues#09cf2679::getATypeExposingCallableElement#3#ffff@ae52cba9
         18ms |       |             | api-visibility-issues#09cf2679::getAnInheritedMethod#1#ff_10#join_rhs@1f688ar1
         16ms |       |             | TopLevelVisibility#60c72f95::getRelevantExportsDirective#2#bff_01#antijoin_rhs@a9cda6pc
         15ms |       |             | Member#9eba3c33::Callable::paramsString#ff@3e905egv
         14ms |       |             | project#Location#77b33c41::fixedHasLocation#3@88765beb
         14ms |       |             | Type#6144c3fd::RefType::getASourceSupertype#ff_10#join_rhs@a7d1e4kt
         14ms |       |             | Location#77b33c41::fixedHasLocation#3#fff#min_term@f22e0f15
         13ms |       |             | Visibility#eddc36f2::Visibility::canSee#1#dispred#ff@264b5ca2
         13ms |       |             | boundedFastTC:Type#6144c3fd::RefType::getASourceSupertype#ff_10#join_rhs:api-visibility-issues#09cf2679::getAnInheritedMethod#1#ff#higher_order_body@83dea407
         12ms |    11 |  5ms @ 3    | Type#6144c3fd::typeArgumentContainsAux1#3#fff@8ae3d3wm
         12ms |    11 |  4ms @ 2    | Type#6144c3fd::typeArgumentContainsAux2#4#ffff@8ae3dx9m
         11ms |       |             | Member#9eba3c33::Method::isPublic#0#dispred#f@f0245epq
         10ms |       |             | num#TopLevelVisibility#60c72f95::TTopLevelPackagePrivate#f@50a581vj
          9ms |       |             | Location#77b33c41::Top::getFile#0#dispred#ff@620c77a7
          9ms |    13 |  4ms @ 1    | Type#6144c3fd::hasSubtype#2#ff@8ae3d0wm
          9ms |       |             | boundedFastTC:Type#6144c3fd::RefType::getASourceSupertype#ff:api-visibility-issues#09cf2679::getAnInheritedMethod#1#ff#higher_order_body#1@3868c05j

[2022-09-05 22:15:27] Total evaluation times for this run:
        * Wall-clock duration of evaluation run: 722.4 seconds
        * Total time spent evaluating predicates: 5.4 seconds
```
Maybe I am reading the summary incorrectly, but the time reported there seems to be pretty off.

The source code of the query can be found [here](https://github.com/Marcono1234/codeql-java-queries/blob/8217e509568bae2f671d3363b42313521d6b3b04/codeql-custom-queries-java/queries/likely-bugs/api-visibility-issues.ql). I am aware that its performance was already quite horrible before, so maybe it was at the mercy of the compiler magic before?

**Comment by aschackmull** [comment]
> I am aware that its performance was already quite horrible before, so maybe it was at the mercy of the compiler magic before?

That seems likely. If you run it locally in VSCode like you did, but set the "Code QL > Running Queries: Debug" setting to true, then the log output should contain a lot more relevant performance debugging information. Right-clicking in the Query History and selecting "Show Evaluator Log (Summary Text)" should then give you the most detailed view of the performance of the individual predicates of your query. In particular, you should see some tuple counts associated with the predicate that was running when you cancel the query, which ought to reveal the source of the problem.

**Comment by Marcono1234** [comment]
Thanks for the hint. Is there some documentation for how to read this output? Should I pay most attention to the absolute value or the percentage after it? For example I see the following lines:
```
        2073  ~207099%    {1} r1 = SCAN TopLevelVisibility#60c72f95::getDeclaringModule#1#ff OUTPUT In.1
```
And for another predicate:
```
        2152690      ~3%    {2} r1 = JOIN api-visibility-issues#09cf2679::getAnInheritedMethod#1#ff#shared WITH Member#9eba3c33::Method::overridesOrInstantiates#1#dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1
        1993967      ~1%    {2} r2 = JOIN r1 WITH Member#9eba3c33::Method::getSourceDeclaration#0#dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1
        1993966  ~85756%    {1} r3 = JOIN r2 WITH Member#9eba3c33::Member::getDeclaringType#0#dispred#ff ON FIRST 1 OUTPUT Lhs.1
```

I have also tried running my test for that query from command line with `--evaluator-log` and (if I read the output correctly), CodeQL is evaluating the predicates in a different order.

It looks like the changes to `Location.qll` done in #10093 seem to be causing this; reverting them brings execution back to < 10 seconds. Though if you have not noticed any similarly servere performance degradations due to this, then maybe I was previously just extremely lucky, or am now extremely unlucky.
(also, please don't try to fix or adjust this if it just affects my query)

**Comment by aschackmull** [comment]
The absolute value is the number of tuples that are computed in that particular line - that's generally the most important number as it directly indicates the amount of work being done. Rough rule-of-thumb: millions are fine, 10s of millions are slow, 100s of millions is a very likely performance problem (unless you're dealing with truly gargantuan codebases). The percentage is a duplication estimate: 0% means a duplicate-free stream of tuples, and 100% means that every tuple is being calculated approximately twice. Duplication is to be somewhat expected after a projection, and doesn't necessarily indicate a problem, but if you're doing lots of subsequent computation on a stream with many duplicates, then that highlights a potential for improvement (e.g. by refactoring you predicates).

> CodeQL is evaluating the predicates in a different order

Predicates can be scheduled by the evaluator as soon as their dependencies are calculated. Usually you would use a number of threads for this, so predicate evaluation order easily becomes non-deterministic. However, that non-determinism shouldn't affect overall performance or whether some particular predicate is slow or not.

> Though if you have not noticed any similarly servere performance degradations due to this

We have not. So there's likely some performance problem inherent in your query, and you might simply have been lucky that the optimiser saved you before.

**Comment by aschackmull** [comment]
Btw., the "Most expensive predicates" table that you posted at the top really ought to include the slow predicate, so something looks broken. And indeed I've just managed to reproduce a case locally where certain predicates are missing from that table, so that issue is being investigated right now.

**Comment by Marcono1234** [comment]
Thanks a lot for the insight and the tips. I have managed to get the query test execution to complete in ~50 seconds now. That is still horrible but at least the test does not time out anymore.

I am closing this issue now because as you mentioned, the problem is most likely with my query.

**Comment by Marcono1234** [comment]
> Btw., the "Most expensive predicates" table that you posted at the top really ought to include the slow predicate, so something looks broken.

In case it is relevant, it looks like this only (?) appeared for cancelled queries for me.
