### ISSUE TITLE
CodeQL "Overly permissive regular expression range" false positive

### ISSUE THREAD

**Issue by Lisenish** [github/codeql#10394]
**Description of the false positive**

I've got the following false positive  `Suspicious character range that is equivalent to [.` for JS codebase for the following RegExps which I think completely fine (I've checked the blocks):
- `/^([ァ-ヾ]|[ｧ-ﾝﾞﾟ])+$/;`
- `/[0-9０-９]/`

Unicode blocks to verify the ranges:
- https://www.compart.com/en/unicode/block/U+FF00 
- https://www.compart.com/en/unicode/block/U+30A0
- https://www.compart.com/en/unicode/block/U+FF00

**Comment by erik-krogh** [comment]
You're right, those are false positives.   
They are from the query being too aggressive at flagging non-ascii character ranges.  

I've fixed it on #10410

**Comment by Lisenish** [comment]
@erik-krogh Thank you!
