### ISSUE TITLE
Query evaluation ran out of Java heap

### ISSUE THREAD

**Issue by philipp-naused** [github/codeql#10432]
We use CodeQL CLI to analyze a very large code base in Azure DevOps.
The repo contains over 11m lines (~400MB) of both C# and C++ code.
Unfortunately, we **cannot** split the build step into smaller parts. The entire database cluster is created using indirect build tracing (which already takes over 5 hours).

But the analysis step always fails with an `OutOfMemoryError`.
The command is:
`codeql/codeql database analyze CodeQL-db/csharp --format=sarifv2.1.0 --output=CodeQL-Results/csharp.sarif --sarif-category=csharp`
Result:
```
[8/53 eval 4m47s] Query failed: codeql\csharp-queries\Security Features\CookieWithOverlyBroadDomain.ql (Query evaluation ran out of Java heap (Java heap (and arrays) maximum: 819 MiB).
(eventual cause: OutOfMemoryError "Java heap space")).
Operation ran out of memory.
```
I have tried increasing the heap size by adding `-J=-Xmx4G` to the command.
The error is now:
```
[11/53 eval 10m21s] Query failed: codeql\csharp-queries\Security Features\CWE-011\ASPNetDebug.ql (Query evaluation ran out of Java heap (Java heap maximum: 1200 MiB, Off-heap arrays maximum: 2000 MiB).
(eventual cause: OutOfMemoryError "Java heap space")).
Operation ran out of memory.
```
Notice that the heap maximum in the log _doesn't match_ the parameter I set.

Is there another way to increase the max heap size? Or can we split the analysis into smaller steps to limit memory consumption?

**Comment by aibaars** [comment]
Have you tried the `--ram` flag? For an 11,000 kLOC code base using 4GB seems pretty low. If you have a lot of ram available I'd suggest using 32GB or more.

**Comment by philipp-naused** [comment]
I will try that. In about 5 hours... 😢

**Comment by philipp-naused** [comment]
Our agents are self-hosted, so I can reuse the database as much as I want.
I didn't set the thread parameter to it should be single threaded.
Not sure how much disk space and RAM our agents can spare but I'll run some tests once the database is finished.

**Comment by philipp-naused** [comment]
Unfortunately, our agents aren't very powerful.
RAM and CPU power are limited. Instead, we have a lot of time and disk space so I'm trying it today with `--ram=16000 --max-disk-cache=100000`. It seems to work so far.

[The documentation](https://codeql.github.com/docs/codeql-cli/manual/database-run-queries/) of `max-disk-cache` says:
`If this size is not configured explicitly, the evaluator will try to use a “reasonable” amount of cache space, based on the size of the dataset and the complexity of the queries.`
Do you know how the “reasonable” amount is calculated?

I also noticed that the RAM usage never goes above 12GB even when I set it to 16GB. Any idea why that is?

**Comment by aibaars** [comment]
> I also noticed that the RAM usage never goes above 12GB even when I set it to 16GB. Any idea why that is?

Did the analysis succeed? If so, then perhaps 12GB is actually enough for the analysis on your code base. I had expected it to need more. You may need to increase the RAM settings when you increase the number of threads to speed things up.

**Comment by philipp-naused** [comment]
12GB RAM seems to be enough for the database. It's even reasonably fast.
I just had to split the `analyze` command into `run-queries --ram=16000` and `interpret-results -J=-Xmx4G`.
`interpret-results` doesn't support `--ram` and without the `-Xmx4G`, it will crash with an out-of-memory error despite only using 1200MB of RAM (both with and without the `Xmx` parameter).

I noticed some other odd things about the database commands:
- `--threads` doesn't do anything on `interpret-results`.
- `--source-root` is optional on `create` but mandatory on `init`.
- `run-queries` and `analyze` are ignoring my `-Xmx4G` parameter.

**Comment by philipp-naused** [comment]
Well, after time trial and error I think I found a combination of `--ram`, `--threads`, `-J=-Xmx4G`, and `--max-disk-cache` that lets the analysis succeed. 
But I may have to increase the 10-hour time-out for the build job...
Thanks for the help!
