### ISSUE TITLE
codeql resolve qlpacks hangs 

### ISSUE THREAD

**Issue by Sim4n6** [github/codeql#10526]
```shell
codeql resolve qlpacks
```
seems to hang on the latest release (for more than 5min). No output for any verbosity.

Any help, please ?

**Comment by edoardopirovano** [comment]
Greetings, thanks for getting in touch with this question! I can't seem to reproduce this by just downloading the latest release, unzipping it and running `codeql resolve qlpacks`. I'll note that this operation does perform a fair bit of IO to look for packs located next to the distribution, so it's possible that if you've unzipped your release somewhere unusual (e.g. a network drive), I could see this command being very slow. Also, do you have any search path configured in your [user config file](https://codeql.github.com/docs/codeql-cli/specifying-command-options-in-a-codeql-configuration-file/)? If you do and that's pointing to a very large folder or network drive, then that could cause the problem you describe as we will scan it for packs.

Would you also be able to share what operating system you're on so I can try to reproduce this on the same OS?

**Comment by Sim4n6** [comment]
Hi,

The directory of the codeql-cli is 
```
/home/sim4n6/codeql-cli
```

 - codeql version yields : **CodeQL command-line toolchain release 2.10.5.**
 - OS : **Linux Mint 21**

I run `codeql resolve qlpacks` without search directories or additional paths from `/home/sim4n6/codeql-cli`.

**Comment by Sim4n6** [comment]
`codeql resolve languages` works like a charm but not qlpacks ... please?

**Comment by edoardopirovano** [comment]
Hmm, interesting. I've passed this along to the team that implemented `codeql resolve qlpacks` so they can look into this for you. We may need to add some more logging to that command in one of our upcoming releases so we can get some logs and better debug what is going on.

**Comment by Sim4n6** [comment]
great, happy to help

**Comment by Sim4n6** [comment]
Is there a workaround ? how should I proceed ? I mean vscode hangs too in resolving the dependencies ...

**Comment by Sim4n6** [comment]
done and it is working like a charm. Thank you very much.

**Comment by aeisenberg** [comment]
Thanks for confirming this is working for you.
