### ISSUE TITLE
LGTM.com - false positive: `js/prototype-polluting-assignment`

### ISSUE THREAD

**Issue by undefined-moe** [github/codeql#10552]
**Description of the false positive**
https://lgtm.com/projects/g/hydro-dev/Hydro/snapshot/bef9a636a2fbf907b17dd9dcb7bf9bdcbc35b940/files/packages/hydrooj/src/loader.ts?sort=name&dir=ASC&mode=heatmap

`Loader.kUpdate` is a symbol defined on L41, which should be impossible to cause a prototype pollution.

**Comment by asgerf** [comment]
The `key` is the untrusted value. If `key` is `__proto__` then `fonts` will refer to `Object.prototype`, and the assignment thus modifies `Object.prototype`.

So it effectively ends up doing,
```js
Object.prototype[Loader.kUpdate] = ...
```

This is what the alert is warning about. If you think the alert message could be improved to make this clearer, I an open to suggestions.
