### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by BillyShaw1210** [github/codeql#10589]
Output of codescan to csv does not work. I specify csv as the format and all that is returned is a blank file. I know this doesn't mean the files is clean because when I run it in with sarif output, it returns the codebases vulnerabilities.

**Comment by alexet** [comment]
Can you show the exact command used to create the csv file?

**Comment by BillyShaw1210** [comment]
codeql database analyze CodeQL_IC/ --format=csv --output="codeQL_analyze.csv"

then it runs 38 queries and shows successful output in the log

**Comment by alexet** [comment]
Does the sarif file actually have any results in it? There is quite a lot of metadata in sarif including diagnostic data that doesn't get written to csv.

**Comment by BillyShaw1210** [comment]
yes it does, it is 1400 lines long

**Comment by alexet** [comment]
That seems possible. Are there any elements in the array called `results` in that file. If you have `jq` installed you can use `jq  '.runs[].results | length'` to get the count easily.

**Comment by BillyShaw1210** [comment]
:-o 

 "results" : [ ],
