### ISSUE TITLE
LGTM.com - false positive: size_t expression has no side effects

### ISSUE THREAD

**Issue by andyhhp** [github/codeql#10601]
I'm transitioning a project from LGTM.com to Github Actions CodeQL.  This particular issue shows up in both cases and is (I think) the root cause of a huge amount of collateral damage.

https://github.com/TrenchBoot/secure-kernel-loader/security/code-scanning/14
https://lgtm.com/projects/g/TrenchBoot/secure-kernel-loader/snapshot/c4099c3177cf609584076395d2679c858e6db396/files/string.c?sort=name&dir=ASC&mode=heatmap#x9221e82d90bfad26:1

This is bizarre.  `size_t` is a type, not an expression, and the line as a whole is very much necessary here.

Trenchbook SKL is a small embedded environment, so defines its own things rather than using the system headers.  In this case, `size_t` is just a typedef for `unsigned long`, and presented in the single header file included by this source.

Is the parser choking on `size_t (strlen)(const char *s)` by any chance?  The extra brackets around the function name is an uncommon construct to find in C, but it is in fact the C spec recommended way of preventing macro expansion happening to the name `strlen`.

This matters for freestanding builds, where builtins aren't available by default and need manually retrofitting with something of the form
```c
size_t strlen(const char *s);         // Real function declaration
#define strlen(s) __builtin_strlen(s) // Try optimisation all calls to strlen()
...
size_t (strlen)(const char *s)        // Prevent the #define from renaming the real function implementation
{
    ....
```

**Comment by jketema** [comment]
Apologies for the slow reply. I see that `include/types.h` contains definitions for both a free standing application and a hosted application? Are you building as free standing? If so, this is not something we properly support at the moment.

**Comment by jketema** [comment]
> The normal build is very much freestanding.

Assuming that this is the build you use in the scan:

> OOI, why does it matter? 

Because we currently do not properly handle `-ffreestanding`. This means on the one side that the typedef of `size_t` is skipped (because `__STDC_HOSTED__` is defined by the CodeQL C/C++ frontend), and this means on the other hand that the standard include paths will not be set by the compiler and, hence, `stdint.h` cannot be found.

The consequence of the above is that the CodeQL C/C++ frontend works with incomplete information (`size_t` will not defined after preprocessing) and it assumes `size_t` is an expression. Hence, the slightly odd error you're seeing.

**Comment by andyhhp** [comment]
Ok.  Is there a reliable way of identifying CodeQL?  I could change that `__STDC_HOSTED__` into `#if __STDC_HOSTED__ && !CODEQL` if there was a suitable macro.  (I've looked a bit, but search seems to focus on the analysis of macros in the subject code.)

**Comment by jketema** [comment]
Thanks again for reporting this problem. The issue should be fixed in the next version of CodeQL which will be released in a few weeks. Closing this issue for now.

**Comment by andyhhp** [comment]
Thanks for fixing it.  Any chance you know which version it will be in, or can you ping back here when it is released, so I can re-test?
