### ISSUE TITLE
How to add a global source in Golang?

### ISSUE THREAD

**Issue by ka1n4t** [github/codeql#10794]
In java, I can extends RemoteFlowSource to add a global source. However, there is no general abstract class to extend in Golang. For example, there is a abstract class "Source" in SqlInjection module in Golang. Every query has its own module.

**Comment by jketema** [comment]
Hi @ka1n4t

Thanks for your question. Is `UntrustedFlowSource` maybe what you're looking for? 
https://github.com/github/codeql/blob/87af5b7d718701e25137e83df14f8dbf6b7e7710/go/ql/lib/semmle/go/security/FlowSources.qll#L8-L29

**Comment by ka1n4t** [comment]
> Hi @ka1n4t
> 
> Thanks for your question. Is `UntrustedFlowSource` maybe what you're looking for?
> 
> https://github.com/github/codeql/blob/87af5b7d718701e25137e83df14f8dbf6b7e7710/go/ql/lib/semmle/go/security/FlowSources.qll#L8-L29

Thanks!
