### ISSUE TITLE
Import cpp Error: Error in transitively-imported module

### ISSUE THREAD

**Issue by icy17** [github/codeql#10898]
Hi! 
When I try to run a very small ql code, I got this error around `import cpp`:
```
Failed to compile query /root/CodeQL/vscode-codeql-starter/codeql-custom-queries-cpp/test.ql against database scheme /root/CodeQL/vscode-codeql-starter/ql/cpp/ql/lib/semmlecode.cpp.dbscheme:
ERROR: Classes may not extend across parameterised module boundaries (/root/CodeQL/vscode-codeql-starter/ql/cpp/ql/lib/semmle/code/cpp/models/implementations/Allocation.qll:336:52:336:56)
ERROR: Classes may not extend across parameterised module boundaries (/root/CodeQL/vscode-codeql-starter/ql/cpp/ql/lib/semmle/code/cpp/models/implementations/Allocation.qll:469:69:469:73)
```
my ql code:
```
import cpp
from FunctionCall fc
select fc.getLocation()
```
and my codeql cli version:
```
CodeQL command-line toolchain release 2.10.2.
Copyright (C) 2019-2022 GitHub, Inc.
Unpacked in: /root/CodeQL/codeql
```
and directory structure:
![image](https://user-images.githubusercontent.com/39425646/196852816-987a02e4-f76a-42e4-bd81-78179e06d427.png)
my ql code is vscode-codeql-starter/codeql-custom-queries-cpp/test.ql
I don't know what the problem is...I use codeql in the same way on another Linux and I didn't meet this error.

**Comment by jketema** [comment]
Hi @icy17.

It seems you're using a clone of the VSCode CodeQL starter workspace that is intended to work with CodeQL CLI 2.11.1. Please update your CLI. 

The current `main` of the VSCode CodeQL starter workspace is only guaranteed to work with the latest version of the CLI.
