### ISSUE TITLE
co​deql database analyze ERROR: Could not resolve predicate ref_returns/1 General issue

### ISSUE THREAD

**Issue by DanSau24** [github/codeql#10944]
ISSUE:

i need to run a report using codeql for our c# code. 

**STEPS:**
--------

https://codeql.github.com/docs/codeql-cli/creating-codeql-databases/ 
https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/configuring-codeql-cli 

1.Set up the CodeQL CLI to run commands locally.
2.Create a CodeQL database for the source code you want to analyze.

codeql database create -l=csharp -s="C:\Users\{myuser}\{project source directory}" C:\Users\{username}\StaticScan\codeql\{outputdirectoryname}

3.export it to zip file

​codeql database bundle -o=C:\Users\{username}\StaticScan\codeql\appOutput.zip C:\Users\{username}\StaticScan\codeql\MVCApp

4.analyze.

//Download queries:( Query pack codeql/csharp-queries )
https://github.com/github/codeql
Downloaded at: C:\Users\{username}\StaticScan\codeql\CODEQUERYdownloaded\codeql-main

co​deql database analyze C:\Users\{username}\StaticScan\codeql\MVCApp C:\Users\{username}\StaticScan\codeql\CODEQUERYdownloaded\codeql-main\csharp --format=csv --output=C:\Users\{username}\StaticScan\codeql\OutputMVResult.csv​

//another attemps :downloaded query pack from here: https://github.com/github/codeql/tree/codeql-cli/v2.11.1

co​deql database analyze C:\Users\{username}\StaticScan\codeql\MVApp C:\Users\{username}\StaticScan\codeql\CODEQUERYdownloaded\codeql-codeql-cli-v2.11.1\csharp\ --format=csv --output=C:\Users\dansau\StaticScan\codeql\OutputMVResult.csv​

ERROR:
--------

first it starts this way..

C:\Users\{username}\StaticScan\codeql>codeql database analyze C:\Users\{username}\StaticScan\codeql\MVConcallApp C:\Users\{username}\StaticScan\codeql\CODEQUERYdownloaded\codeql-codeql-cli-v2.11.1\csharp\ --format=csv --output=C:\Users\dansau\StaticScan\codeql\OutputMVConcallResult.csv
Running queries.
**Did not find any ML models.**
Compiling query plan for C:\Users\dansau\StaticScan\codeql\CODEQUERYdownloaded\codeql-codeql-cli-v2.11.1\csharp\ql\campaigns\Solorigate\src\ModifiedFnvFunctionDetection.ql.
[..]
and then i get below failure and the .csv report is never generated...

![error1](https://user-images.githubusercontent.com/84392794/197360153-22d2e444-f9c7-4575-9625-5333a29382ef.jpg)

any help or directions?

**Comment by hmakholm** [comment]
Hi.

The problem is that the command-line you're using asks CodeQL to run _all_ `*.ql` files found anywhere in the directory tree under `github/codeql/csharp`, and some of those files are special-purpose queries that can't be evaluated against a standard databases.

What you really want is to run a specific query _suite_ rather than everything under the sun. Try giving `..\csharp\ql\src\codeql-suites\csharp-security-and-quality.qls` (or one of the other files in that directory) as the command-line argument rather than just `csharp\`.
