### ISSUE TITLE
How can I query the receiver object of a call in java

### ISSUE THREAD

**Issue by cokeBeer** [github/codeql#10946]
For example I want to access `a` in call `a.equals('y')` here
```java
public void somefunction(){
    String a="x";
    a.equals("y"); // I want to access a in the call expr
}
```
I tried `Call.getCaller`. However, it gives me `somefunction` as the caller.
So how can I get the receiver here?

**Comment by intrigus-lgtm** [comment]
Did you try `Call.getQualifier`?
This should give you `a` in `a.equals("y")`.

**Comment by cokeBeer** [comment]
> Did you try `Call.getQualifier`? This should give you `a` in `a.equals("y")`.

thanks, this does work
