### ISSUE TITLE
False positive from cpp/wrong-number-format-arguments

### ISSUE THREAD

**Issue by ryao** [github/codeql#10941]
**Description of the false positive**

CodeQL reports `Format expects 3 arguments but given 2`, but in reality, the format only expects 1 argument and was given only 1 argument.

**URL to the alert**

https://github.com/ryao/zfs/security/code-scanning/15

https://github.com/github/codeql/issues/10941#tasklist-block-02780934-26aa-4b9c-bf87-aaf7d0586a33

**Comment by hmakholm** [comment]
Thanks for the report. This does indeed look like a false positive. I'll ask our C/C++ analysis experts to take a look at it.

**Comment by geoffw0** [comment]
It looks like the alert isn't about the call to `snprintf` you can see on line 281, instead it is about the code generated by the `VERIFY3U` macro invocation on line 280.  I can find two different definitions of `VERIFY3U`, but assuming we're expanding [this one](https://github.com/ryao/zfs/blob/ab49df487b5dfee8d045195c30d3bf1b00c23910/include/os/linux/spl/sys/debug.h#L98) I think this might be what's going on:
 - `VERIFY3U` contains a call to `spl_panic`.
 - the call has two obvious format specifiers (`%llu`) but also a third hidden in the expansion of #RIGHT (`snprintf(buf, sizeof (buf), "%lld", (longlong_t)lua_tonumber(state, -2)))`).
 - but the call only has two format arguments, hence the alert.

If the above is accurate, this is a true positive result.  `#RIGHT` should be included as an argument (with `%s`) not as part of the format string.

**Comment by ryao** [comment]
@geoffw0 You are right. This is not a false positive. Sorry for the noise.

**Comment by ryao** [comment]
I just want to add, that every other static analyzer that the project has run on the codebase has missed this. That includes:

* Coverity
* Clang's static analyzer
* Clang-tidy
* CPPCheck
* Smatch
* GCC's static analyzer
* -Werror on both Clang and GCC.

CodeQL catching it is amazing.

**Comment by geoffw0** [comment]
😃 

Glad to help - it was a bit of a subtle one.

Closing.
