### ISSUE TITLE
go SqlInjection ... Ellipsis

### ISSUE THREAD

**Issue by yhy0** [github/codeql#10979]
I am a novice, when ... If the data flow is interrupted, how should I add additional steps?
<img width="710" alt="image" src="https://user-images.githubusercontent.com/31311038/197925492-5508234c-5ef8-4bd4-bda1-3c247256a7c4.png">

<img width="471" alt="image" src="https://user-images.githubusercontent.com/31311038/197925477-acfbb7b5-a80a-48d5-91bc-7799e5584cd6.png">
Injection not detected。

If that's all right.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/31311038/197925584-6a2d4a25-8c1e-41ba-bf21-d32015855b7f.png">

How should I add an extra step to connect the data stream

**Comment by smowton** [comment]
This works for me:

```java
public class Test {

  public static ThreadLocal<HasUser> CONTEXT_THREAD_LOCAL;

  public static User getCurrentUser() {
    return CONTEXT_THREAD_LOCAL.get().user;
  }

  public static User getRequiredCurrentUser() {
    User user = getCurrentUser();
    if (user == null) {
        throw new RuntimeException("Need signin first.");
    }
    return user;
  }

}

class HasUser {

  public User user;

}

class User { }
```

```ql
import java
import semmle.code.java.dataflow.TaintTracking
import semmle.code.java.dataflow.ExternalFlow
import semmle.code.java.dataflow.internal.DataFlowPrivate as DFP

class Models extends SummaryModelCsv {
  override predicate row(string r) {
    r = "java.lang;ThreadLocal;true;get;;;Argument[-1];ReturnValue;taint;manual"
  }
}

class Configuration extends TaintTracking::Configuration {
  Configuration() { this = "rfelkgjdfslgkd" }

  override predicate isSource(DataFlow::Node source) {
    exists(FieldRead f | source.asExpr() = f |
      not source.asExpr().getEnclosingStmt() instanceof IfStmt and
      f.getField().isStatic()
    )
  }

  override predicate isSink(DataFlow::Node sink) {
    exists(IfStmt ret | sink.asExpr() = ret.getCondition().getAChildExpr*())
  }

  override predicate isAdditionalTaintStep(DataFlow::Node fromNode, DataFlow::Node toNode) {
    DFP::readStep(fromNode, any(DataFlow::FieldContent f | f.getField().getDeclaringType().hasQualifiedName("", "HasUser")), toNode)
  }
}

from Configuration c, DataFlow::Node src, DataFlow::Node sink
where c.hasFlow(src, sink)
select src, sink
```

I've done two things here:

1. Implement a model for `ThreadLocal.get()` using `SummaryModelCsv` indicating that if the `ThreadLocal` itself is considered tainted, then so is the result of `get()`. I'll suggest to the team whether we might consider including a model like this per default.
2. Used `isAdditionalTaintStep` to indicate that if a `HasUser` instance is tainted, then so is anything read from one of its fields (in this case a `User`). Per default field-reads are not considered taint-propagating like this, so we need to manually opt in to this behaviour.

**Comment by smowton** [comment]
I'm afraid this is a currently-known shortcoming of the Go analysis -- we're working on this at the moment, but for now varargs functions called using a list of implicit array arguments (i.e., not using `...arr` syntax to pass an array explicitly) don't work as expected.

In simple cases using `TaintTracking::Configuration` it may suffices to add code like

```ql
private predicate isVarargsParam(Parameter p) {
  exists(ParameterDecl pd, FuncTypeExpr tp | pd = tp.getAParameterDecl() |
    p.getDeclaration() = pd.getANameExpr() and
    pd.getTypeExpr() instanceof Ellipsis
  )
}

class TaintConfig extends TaintTracking::Configuration {
  TaintConfig() { this = "taint-configuration" }

  override predicate isAdditionalTaintStep(DataFlow::Node source, DataFlow::Node sink) {
    exists(Parameter p, DataFlow::ArgumentNode an, int idx |
      an = source and
      p = an.getCall().getACallee().getAParameter() and
      isVarargsParam(p) and
      not an.getCall().hasEllipsis() and
      an.argumentOf(_, idx) and
      idx >= p.getIndex() and
      sink.asParameter() = p
    )
  }
}
```

This will do what you want so long as `query` itself is tainted on calling `TT` -- it won't work if just the `Sort` field of `TT` is tainted, because additional steps only apply to "top level" taint.

To use this with a `DataFlow::Configuration` instead of a `TaintTracking::Configuration` we'd need to target not the varargs parameter itself, but an array-read from it, like `sink.(Read).readsElement(p.getARead(), _)`. This would also only work if `query` is the value we're tracking, not a value stored in one of its members.

So these workarounds are not great, but perhaps they will help with your case -- otherwise please bear with us while we implement a higher quality solution!

**Comment by yhy0** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github/codeql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 晚上6:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [github/codeql] go SqlInjection ... Ellipsis (Issue #10979)





 
I'm afraid this is a currently-known shortcoming of the Go analysis -- we're working on this at the moment, but for now varargs functions called using a list of implicit array arguments (i.e., not using ...arr syntax to pass an array explicitly) don't work as expected.
 
In simple cases using TaintTracking::Configuration it may suffices to add code like
 private predicate isVarargsParam(Parameter p) {   exists(ParameterDecl pd, FuncTypeExpr tp | pd = tp.getAParameterDecl() |     p.getDeclaration() = pd.getANameExpr() and     pd.getTypeExpr() instanceof Ellipsis   ) } class TaintConfig extends TaintTracking::Configuration {   TaintConfig() { this = "taint-configuration" }   override predicate isAdditionalTaintStep(DataFlow::Node source, DataFlow::Node sink) {     exists(Parameter p, DataFlow::ArgumentNode an, int idx |       an = source and       p = an.getCall().getACallee().getAParameter() and       isVarargsParam(p) and       not an.getCall().hasEllipsis() and       an.argumentOf(_, idx) and       idx &gt;= p.getIndex() and       sink.asParameter() = p     )   } }
 
This will do what you want so long as query itself is tainted on calling TT -- it won't work if just the Sort field of TT is tainted, because additional steps only apply to "top level" taint.
 
To use this with a DataFlow::Configuration instead of a TaintTracking::Configuration we'd need to target not the varargs parameter itself, but an array-read from it, like sink.(Read).readsElement(p.getARead(), _). This would also only work if query is the value we're tracking, not a value stored in one of its members.
 
So these workarounds are not great, but perhaps they will help with your case -- otherwise please bear with us while we implement a higher quality solution!
