### ISSUE TITLE
CPP - fields of classes inside namespaces are not parsed correctly in the AST

### ISSUE THREAD

**Issue by Da5hes** [github/codeql#10972]
During a modeling of an issue I've encountered a bug:

**a.cpp:**
````
#include "b.h"

int gaga_name_map::B::pv(int log, int PCWSTR, int rq)

{
    bool a = mbo;
    return a;
}



int main()
{
    return 0;
}
````

**b.h:**

```
#pragma once

namespace gaga_name_map {
    class B  {
    public:
        static
            int
            g(int log, int PCWSTR, int rq);

    public:
        bool mbo;

    private:
       int pv(int  log, int PCWSTR, int rq);
    };
}
```

expected result:
the bool 'mbo' is parsed as a filed and/or as a definition in the AST

actual result:
the bool 'mbo' definition in b.h is getting parsed as a MoveAssignmentOp in the AST as can be seen in the photo 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/4195138/197818806-02fe040f-3396-49f3-982f-5f9c170d95a0.png">

this reproduces in small and big codebases with both the latest CLI as well as older versions

**Comment by jketema** [comment]
Hi @Da5hes. Thanks for your report. The AST viewer only displays functions and not type definitions such as class definition. In this case the compiler frontend we're using will generate copy and move assignment operators per the rules for implicitly declared ones that can be found, e.g., [here](https://en.cppreference.com/w/cpp/language/copy_assignment) and [here](https://en.cppreference.com/w/cpp/language/move_assignment). And, you will see these in the AST.

Note that these compiler generated operators/functions can be excluded from your queries using `Function::isCompilerGenerated()`:
https://github.com/github/codeql/blob/a520de3986987baf4c5f846bd82bf68536ae042c/cpp/ql/lib/semmle/code/cpp/Function.qll#L79-L80

**Comment by Da5hes** [comment]
Hi @jketema.

Thanks for clarifying on the copy and move operators.
My issue is not solely in the AST viewer per say but with the fact that i am unable to select this boolean definition in any query
for instance, I would expect to be able to catch it with something like:

```
from Field f
where f.hasdefinition() and not f.hasInitializer()
select f
```

or with something like a Declaration,
in any case - it seems impossible to select this boolean thus making it impossible to perform any further analysis i.e flow or taint in such cases - or am I missing something?

**Comment by jketema** [comment]
Running a slight variant of your query:
```codeql
from Field f
where f.hasDefinition() and not f.hasInitializer() and exists(f.getFile().getRelativePath())
select f
```
I get:
\# | f
-- | --
1 | mbo

So this works  for me. Would you be willing to share the database you created and the `build-tracer.log` file? to help diagnose this further?
