### ISSUE TITLE
Java: Cannot find class

### ISSUE THREAD

**Issue by Kaide0521** [github/codeql#11047]
I have defined a basic Springboot Controller class, but the class is not found using the following query language, and also does not appear in the src. zip file in the created database directory. Why? 

### **class define :**
@Api(value = "TestController RESTful", description = "")
@Slf4j
@RestController
@CrossOrigin
@RequestMapping("/test")
public class TestController {
   // do some thing
}

### query :
import java
import libs.SpringMVCMapping

from Class cls
select cls.getQualifiedName(), cls.getASupertype()

**Comment by smowton** [comment]
Could you give the command you're using to build the database, and any build file that it uses?

**Comment by Kaide0521** [comment]
> Could you give the command you're using to build the database, and any build file that it uses?

### **Command:**
codeql database create D:\CodeQL\databases\TestNoClass  --language="java" --command="mvn clean install -DskipTests --file pom.xml" --source-root=D:\CodeQL\sources\TestNoClass

### **Project Demo:**
[](https://github.com/Kaide0521/TestCodeQL.git)

**Comment by Kaide0521** [comment]
Sorry, The issues that have been processed include the answers to this question. Thanks.
https://github.com/github/codeql/issues/4984
