### ISSUE TITLE
Java: xml extractor ... does not provide file-indexing capabilities

### ISSUE THREAD

**Issue by sususukkk** [github/codeql#11115]
Got an issue while creating database from a java project, which showed `[2022-11-04 09:40:51] [build-stderr] A fatal error occurred: xml extractor /opt2/opt/codeql/codeql-cli/xml does not provide file-indexing capabilities.` 

Any clue on solving this?

**Comment by smowton** [comment]
This means we couldn't find `xml/tools/index-files.sh` or similar, or that file was not executable.

You should be able to get more detailed logging using commands like

```
mkdir /tmp/emptydir
cd /tmp/emptydir
codeql database init -l java ../testdb --source-root .
codeql database index-files -l xml ../testdb --log-to-stderr
```

For me that produces a log line `Using index-files script .../codeql/xml/tools/index-files.sh.`, but for you I expect it will show some paths for `index-files.sh` that were rejected and perhaps indicate why.

**Comment by aibaars** [comment]
@woadsl1234 Any update on this? Have you checked the file permissions of the `xml/tools/index-files.sh` script?
