### ISSUE TITLE
[Question] How to override RemoteFlowSource for custom frameworks

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#11186]
Hello, 

I have a use case where I need to add a custom source to the RemoteFlowSource definition in java, however just extending the RemoteFlowSource class and writing my source does not work, Is there anyway I can force the ql queries to load my override before fetching the default definition of semmle.code.java.dataflow.FlowSources. 

Thanks

**Comment by smowton** [comment]
What you describe sounds like it should work -- can you paste example CodeQL? What query are you trying to extend?

**Comment by chmodxxx** [comment]
For context : 
Our framework defines a custom remote flow source, let's name it CustomSource and what I want is when I run a QL query, I want that my CustomSource gets resolved as well. 
this is my custom source .qll definition
```
class CustomSource extends RemoteFlowSource {
  CustomSource(){ doSomething}
}
```
Say I run https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/CWE-023/PartialPathTraversalFromRemote.ql , how can I make sure that remoteflowsource also resolves my customsource without necessarily modifying the [default definition ](https://github.com/github/codeql/blob/56e3334c6db9beed5e6d528f4d82a3495cf9e2ed/java/ql/lib/semmle/code/java/dataflow/FlowSources.qll) , I was thinking that I might need to add a custom qlpack for my library before executing the codeql analysis, but not sure how that looks like in reality. 

Let me know if this makes sense ?

**Comment by smowton** [comment]
Are you running locally or using the CLI? If it's the CLI + a local checkout of `github/codeql` then alter `Customizations.qll` to include your custom source definition. Otherwise if you're running under Code Scanning on Actions or similar, I'll find out the recommended method for that context.

**Comment by chmodxxx** [comment]
Running via both actually, but thanks for the Customizations tip, I'll use that one when I'm testing.

**Comment by smowton** [comment]
There's an official solution for using this on Actions in development, but in the meantime we have a workaround at https://github.com/advanced-security/codeql-bundle-action that can be used to bundle up your Customizations.qll file with the standard Java queries. If you give it a go, please do let us know how you get on, and if there's anything we can improve in the README.

**Comment by chmodxxx** [comment]
Thanks @smowton  appreciate the help. 
Will do
