### ISSUE TITLE
cpp/uncontrolled-allocation-size - false positive

### ISSUE THREAD

**Issue by ryao** [github/codeql#11215]
**Description of the false positive**

CodeQL complains `This allocation size is derived from user-input (a command-line argument) and might overflow.` on a line of code that is basically `calloc(1, size)`. When one of the arguments is 1, an overflow is impossible. Therefore, this is a false positive.

It should be possible to modify the query to stop reporting this issue whenever one of the arguments is 1. That should eliminate the false positive.

**URL to the alert**
https://github.com/ryao/zfs/security/code-scanning/785

**Comment by MathiasVP** [comment]
Hi @ryao,

Thanks for the report!

Indeed, this does look like a false positive. I've created an internal issue for this, and we'll let you know when this has been fixed 🙂.

**Comment by ryao** [comment]
Should this receive the acknowledged label?

**Comment by MathiasVP** [comment]
Yeah, it should. I've added it now.
