### ISSUE TITLE
Autobuild support for .NET 7.0

### ISSUE THREAD

**Issue by uncheckederror** [github/codeql#11224]
The autobuild step of the Analyze (csharp) job in the CodeQL Action fails now that I have upgraded my project to .NET 7.0 from .NET 6.0.xxx.

[You can see a log of this failure here.](https://github.com/AccelerateNetworks/NumberSearch/actions/runs/3442649293/jobs/5743434997)

The CodeQL C# autobuilder is still using the 6.0.402 version of the .NET SDK. You can find the latest version .NET SDK 7.0.100 [here on their website.](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)

.NET 7.0 was released earlier this week so it would be cool if CodeQL added support for it.

**Comment by aibaars** [comment]
@uncheckederror The output of `dotnet info` suggests that `.NET 7.0` is not installed. Could you try installing it first by adding a  [`actions/setup-dotnet`](https://github.com/actions/setup-dotnet) step before `github/codeql-action/init` ?

**Comment by uncheckederror** [comment]
@aibaars thanks for the response.

I was able to get the CodeQL action working by following your advice and commenting out the autobuild step before adding:

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

in between the init and the analyze steps. When I tried adding this build step prior to the init step I got a "no code found" warning.
