### ISSUE TITLE
Migration from LGTM is missing support for .lgtm.yml

### ISSUE THREAD

**Issue by michaelrsweet** [github/codeql#11319]
Hi, since you are migrating everything over from LGTM to Github CodeQL, one of the features of LGTM that I've used across projects is the .lgtm.yml file in the root directory of the repository in order to suppress testing or individual tests that produce too many false positives or are simply not actionable.

I've looked through the current documentation and all I can find is a manual process of dismissing individual claims but no way to do a batch dismissal or disable particular tests for the whole repository or a group of files. When a repository produces many false positives it becomes impossible to see genuine issues in the chaff.

**Comment by aeisenberg** [comment]
Hello, thank you for reporting an issue with migration. I'd like to know a little bit more about your use case.

- Are you looking to disable individual queries or many queries? If so, please read [this bit of documentation](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#excluding-specific-queries-from-analysis). You can specify a query-filter to avoid running one or more queries. 
- Or are you looking to mark multiple alerts as false positives at the same time? If so, please [see this documentation](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository#dismissing-multiple-alerts-at-once). You can dismiss alerts in bulk from the code scanning security tab on the repository in GitHub.
- If neither of these address your problem, please explain in more detail what you are hoping to do.

**Comment by michaelrsweet** [comment]
OK, so it looks like I can assign a configuration file in the Github workflow, and then use that configuration file to disable queries as before - that's good, although I would have never found this information if you hadn't linked directly to it. I recommend making this clearer and/or including this in the default workflow so that it is more accessible.

For marking multiple alerts, it sounds like the documentation says you need to do a search to be able to response to dismiss multiple alerts - if so, there needs to be an easier way to discover what that search needs to be (like links to "show all alerts for a file" and "show all alerts like this one"). That might also be useful when determining what to do with an alert when you aren't sure of the scope/context.

**Comment by aeisenberg** [comment]
Thanks for your feedback. I'll bring this to the appropriate teams. I'm marking this as closed since it sounds like you solved your problem, but feel free to re-open this or raise a new issue if there's anything else.

**Comment by aibaars** [comment]
Another possibility is to filter out alerts using https://github.com/advanced-security/filter-sarif
