### ISSUE TITLE
CodeQL - False positive for uninitialized variable in Python

### ISSUE THREAD

**Issue by pyrito** [github/codeql#11312]
**Description of the false positive**

`modin_res` and `pandas_res` will be defined in the else statement (please see link below for more context)

**Code samples or links to source code**

https://github.com/modin-project/modin/pull/5222/files#file-modin-pandas-test-dataframe-test_binary-py-L283

**Comment by aeisenberg** [comment]
Thank you for your false positive report. It looks like codeql is not able to detect that `op_type` has only a finite set of values and they are all being checked for above. My recommendation would be to add an `else` like this:

```
else
  raise Exception("Invalid op_type " + op_type)
```

This will send a clear signal to codeql (and any people reading the code) that `op_type` is tested for and `modin_res` and `pandas_res` are initialized.

**Comment by pyrito** [comment]
@aeisenberg ah I didn't realize the error was from the other test! Thanks!
