### ISSUE TITLE
go/ql/src/Security/CWE-020/ExternalAPIsUsedWithUntrustedData.ql kind error

### ISSUE THREAD

**Issue by leila97** [github/codeql#11324]
go/ql/src/Security/CWE-020/ExternalAPIsUsedWithUntrustedData.ql 

"@kind table"

should be 

"@kind problem"?

**Comment by smowton** [comment]
No, this really is a tabular report -- the corresponding `@path-problem` alerts are generated by that query's companion https://github.com/github/codeql/blob/main/go/ql/src/Security/CWE-020/UntrustedDataToExternalAPI.ql
