### ISSUE TITLE
False positive for Failure to use HTTPS or SFTP URL in Maven artifact upload/download when repo is disabled

### ISSUE THREAD

**Issue by cdietrich** [github/codeql#11326]
**Description of the false positive**

```
<pluginRepository>
			<id>codehaus-snapshots</id>
			<name>disable dead 'Codehaus Snapshots' repository, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=481478</name>
			<url>http://nexus.codehaus.org/snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
```
having this in maven pom will result in Failure to use HTTPS or SFTP URL in Maven artifact upload/download

https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/pom.xml#L133-L143

**Comment by aeisenberg** [comment]
Thanks for your false positive report. This does indeed seem like a false positive in a security-related query, so this will be of interest to our Java team. I'll ask them to take a look.

**Comment by atorralba** [comment]
Hey @cdietrich, thanks for reporting this to us! I created [a PR](https://github.com/github/codeql/pull/11340) to fix this issue.
