### ISSUE TITLE
Recursive monotonic aggregates related: example provided by official docu is reported as an error "Non-monotonic recursion"

### ISSUE THREAD

**Issue by iiins0mn1a** [github/codeql#11361]
Example I used: https://codeql.github.com/docs/ql-language-reference/expressions/#recursive-monotonic-aggregates
```ql
class Node extends Expr {
    Node() {any()}
}

int depth(Node n) {
    if not exists(n.getAChild())
    then result = 0
    else result = 1 + max(Node child | child = n.getAChild() | depth(child)) // Error is reported at `depth`
  }
```
and VSCode with CLI v2.11.3 reports an error in my `misc.ql` file:
```
Non-monotonic recursion: misc::depth -!-> misc::depth
```
Please help me to understand what's going wrong and how to fix it... If anyone could offer any thoughts, I would be really appreciate...

**Comment by intrigus-lgtm** [comment]
I'd guess that the example is missing a `language[monotonicAggregates]` for `depth`.
With it, it compiles:
https://lgtm.com/query/5829585122479301110/

**Comment by iiins0mn1a** [comment]
@intrigus-lgtm  thanks a lot, it really helps~

**Comment by iiins0mn1a** [comment]
https://github.com/github/codeql/discussions/7263
A related issue I found by searching `language[monotonicAggregates]`.

**Comment by smowton** [comment]
Thanks to @intrigus-lgtm for adding this in #11495 !
