### ISSUE TITLE
/db-python does not exists ?

### ISSUE THREAD

**Issue by Sim4n6** [github/codeql#11412]
Hi,

I am having an unusual error when I try to run a query using codeql version 2.11.3.

```bash
codeql query run --database=./databases/MyDB.db --threads=0 --output=file.bqrs --additional-packs=/root/.codeql/packages/ -- ./myquery.ql
```
Gives this unusual error  
```
A fatal error occurred: /root/MyCodeql/databases/MyDB.db/db-python does not exist.
```

The command used for database creation is:
```bash
codeql database create ./databases/MyDB.db --language=python --source-root=./repos/MyDB/ -v --overwrite
```
strange right ? any help please ?

**Comment by MathiasVP** [comment]
Hi @Sim4n6,

Thanks for raising this issue! A couple of questions to help us debug this:
1. Does `/root/MyCodeql/databases/MyDB.db/db-python` actually exist?
2. Did this work with earlier versions of the CodeQL CLI? (for instance, with [CodeQL version 2.11.2](https://github.com/github/codeql-cli-binaries/releases/tag/v2.11.2)?)

**Comment by Sim4n6** [comment]
1 - no
2- no, new configured instance

**Comment by Sim4n6** [comment]
I mean for 2 did not checked I m working on a new instance

**Comment by Sim4n6** [comment]
```
Writing logs to /root/MyCodeql/databases/MyDB.db/log/database-create-20221124.140745.812.log.
Initializing database at /root/MyCodeql/databases/MyDB.db.
Calculating baseline information in /root/MyCodeql/repos/MyDB
Resolving extractor python.
Successfully loaded extractor Python (python) from /root/codeql/python.
Created skeleton CodeQL database at /root/MyCodeql/databases/MyDB.db. This in-progress database is ready to be populated by an extractor.
Running build command: []
.....
....
 ```
listing files get me :
```
baseline-info.json  codeql-database.yml  log  src  trap  working
```

It is still in progress ... but I think it is working 5min and I will let you the final output of the in-progress database creation process, please.

**Comment by Sim4n6** [comment]
```
A fatal error occurred: Evaluator heap must be at least 384.00 MiB
```

I did not see that error.

**Comment by MathiasVP** [comment]
Ah! In that case, you can try adding an `--ram` argument to your `codeql database create` command to increase the amount of memory available to the CLI.

**Comment by Sim4n6** [comment]
Thanks, I would suggest `--ram=400MB` for instance?

**Comment by Sim4n6** [comment]
Not working with `--ram=400` moving to `500`.

**Comment by Sim4n6** [comment]
It seems that the import is successful but nothing more.

```
Finalizing database at /root/MyCodeql/databases/MyDB.db.
Running TRAP import for CodeQL database at /root/MyCodeql/databases/MyDB.db...
TRAP import complete (21s).
A fatal error occurred: Evaluator heap must be at least 384.00 MiB
```

**Comment by Sim4n6** [comment]
Worked like a charm with a new remote instance `--ram=600` . Thank you very much.
