### ISSUE TITLE
False positive - C# - cs/useless-assignment-to-local with discards

### ISSUE THREAD

**Issue by mikeclayton** [github/codeql#11456]
**Description of the false positive**

The following C# code generates a warning from ```cs/useless-assignment-to-local```:

```csharp
var _ = MyClass.MyMethod();
```

The generated warning is:

> A value is assigned to a local variable, but either that variable is never read later on, or its value is always overwritten before being read. This means that the original assignment has no effect, and could indicate a logic error or incomplete code.

However, the ```_``` "discard" variable is documented as meaning:

> A discard communicates intent to the compiler and others that read your code: *You intended to ignore the result of an expression.*

There are legitimate cases where the side effect of a method needs to be invoked, but we don't care about the return value, and the use of the discard above specifically states this intent.

I think the ```cs/useless-assignment-to-local``` rule needs to check if the variable name is ```_``` before it triggers the warning, and supress it if so.

**Comment by alexet** [comment]
In that case `_` is not the discard variable but an ordinary variable named `_`. If you want to discard a result you must do 

```
_ = MyClass.MyMethod();
```

In fact by having a variable named `_` in scope this can interact with uses of a discard later in the function, see the examples at the bottom of https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/discards#a-standalone-discard for more details.

**Comment by mikeclayton** [comment]
Ah, yeah, I can see that now - oops :-S.

Maybe that could be another CodeQL rule - checking if there's an unused *variable* called ```_``` and suggesting a discard instead :-).
