### ISSUE TITLE
codeql documentation improvement 

### ISSUE THREAD

**Issue by am0o0** [github/codeql#11573]
**I faced some issues when searching for documentation of codeql**

![image](https://user-images.githubusercontent.com/77095239/205714597-c9fc6ef8-533c-41dd-97c9-a255280daaa4.png)
as you can see, there is a lot of `isBarrier`. I want to see their signatures in the same place. I have to click on them one by one to see their differences.
I don't want to use the document search feature as it has such vast results, so it is hard to find sth with it, but if it had advanced filtering options, it would be great.
Finally, I think the documentation should be improved somehow.

**Comment by hvitved** [comment]
Hi

The reason for the duplication is because currently the data flow library exists in multiple copies. This will change soon(ish), once the data flow library is rewritten as a parameterized module. FWIW, there should be no difference in the signatures for the predicates.
