### ISSUE TITLE
Clear unimportant alerts

### ISSUE THREAD

**Issue by LUAgam** [github/codeql#11655]
@p- 
You submitted the codeQL verification in the dble warehouse before
I would like to ask how to clear these unimportant alarms
![image](https://user-images.githubusercontent.com/17228757/206971231-73763025-bf1e-4abc-84c2-00f764948b0d.png)

**Comment by p-** [comment]
>I would like to ask how to clear these unimportant alarms

If you mean by "unimportant alerts" non-security related alerts you can modify what query packs are run in your `codeql.yml`. We set it to `+security-and-quality` to run similar query suites as LGTM did.
If you only want to run the default query suite you can remove the [`queries` line](https://github.com/actiontech/dble/blob/f40048915be091cfaa391dd429523ee17d0d4cb3/.github/workflows/codeql.yml#L45) in your codeql.yml. This should reduce the amounts of alerts in your repository.

See [Using queries in QL packs](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs) for more information.

**Comment by LUAgam** [comment]
> > 请问如何清除这些不重要的告警
> 
> 如果您的意思是“不重要的警报”与安全无关的警报，您可以修改文件中运行的查询包`codeql.yml`。我们将其设置为`+security-and-quality`运行与 LGTM 类似的查询套件。 如果您只想运行默认查询套件，您可以删除codeql.yml 中的[`queries`该行。](https://github.com/actiontech/dble/blob/f40048915be091cfaa391dd429523ee17d0d4cb3/.github/workflows/codeql.yml#L45)这应该会减少存储库中的警报数量。
> 
> 有关详细信息，请参阅[在 QL 包中使用查询。](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs)

Unimportant refers to the note level
I don't want the system to display note-level alerts

**Comment by LUAgam** [comment]
Can remove the queries cancel all previous notes?

**Comment by p-** [comment]
>Unimportant refers to the note level
>I don't want the system to display note-level alerts

Ah, I see, thanks for clarification!
You should be able to filter out queries that are on note level by filtering out the problem severity of `recommendation`. See the snippet in [Example configuration files](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#example-configuration-files):

e.g.

```
name: "CodeQL config"

query-filters:
  - exclude:
      problem.severity:
        - recommendation
```

Note: this needs to be done in a [separate file](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#working-with-custom-configuration-files) e.g. named `codeql-config.yml`. This file can then be referenced in the CodeQL init action by using the `config-file:`key.

>Can remove the queries cancel all previous notes?

Yes, this should be the case as far as I know.

**Comment by LUAgam** [comment]
> > Unimportant refers to the note level
> > I don't want the system to display note-level alerts
> 
> Ah, I see, thanks for clarification! You should be able to filter out queries that are on note level by filtering out the problem severity of `recommendation`. See the snippet in [Example configuration files](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#example-configuration-files):
> 
> e.g.
> 
> ```
> name: "CodeQL config"
> 
> query-filters:
>   - exclude:
>       problem.severity:
>         - recommendation
> ```
> 
> Note: this needs to be done in a [separate file](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#working-with-custom-configuration-files) e.g. named `codeql-config.yml`. This file can then be referenced in the CodeQL init action by using the `config-file:`key.
> 
> > Can remove the queries cancel all previous notes?
> 
> Yes, this should be the case as far as I know.

Thank you for solving my doubts
