### ISSUE TITLE
Javascript: Qhelp for Missing CSRF middleware recommends deprecated package

### ISSUE THREAD

**Issue by chanel-y** [github/codeql#11682]
**Description of the issue**

Hello, the package [csurf](https://www.npmjs.com/package/csurf) recommended by [MissingCsrfMiddleware.qhelp](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-352/MissingCsrfMiddleware.qhelp) is currently deprecated by the author. 

Looking at the query (lines 58-68 [here](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-352/MissingCsrfMiddleware.ql])) the other alternatives are lucsa and "express csrf". How is the latter used? Could be a limitation of my googling but I'm having trouble finding tutorials to implement it

Thanks!

**Comment by MathiasVP** [comment]
Hi @chanel-y,

Thanks for the issue. I'll bring up the fact that https://codeql.github.com/codeql-query-help/javascript/js-missing-token-validation/ is recommending a deprecated deprecated package to the JavaScript team.

**Comment by asgerf** [comment]
Hi @chanel-y,

Thanks for bringing this to our attention. I'll update the query help to suggest the `lusca` package instead.
