### ISSUE TITLE
`concat` does not interleave the second expression if `order by` is used

### ISSUE THREAD

**Issue by AryazE** [github/codeql#11690]
```
import python

string params(Function f) {
    result = concat(int i |  |
        f.getArg(i).getName() order by i, ", ")
}

from Function f
select f.getName(), params(f)
```
this should give me, for each function, the function name and the arguments separated by commas. However, it concatenates all arguments without the comma. If I remove the `order by i`, it works as expected.
Am I missing something?

**Comment by alexet** [comment]
`f.getArg(i).getName() order by i, ", ")`, orders by the tuple `(i,", ")` with the default separator (`""`). I think you want `f.getArg(i).getName() , ", " order by i` instead.
