### ISSUE TITLE
how to do taint tracking when assign to ConstructorFieldInit

### ISSUE THREAD

**Issue by hatface** [github/codeql#11734]
mycode
https://github.com/hatface/codeql_cap_evalution 
someof the code showing below

```cpp student.cpp
#include "Student.h"

int Student::getAge() const {
    return age;
}

void Student::setAge(int age) {
    Student::age = age;
}

const std::string &Student::getName() const {
    return name;
}

void Student::setName(const std::string &name) {
    Student::name = name;
}

Student::Student(int age, const std::string &name) : age(age), name(name) {}

Student::Student() {

}

int Student::studentOperation01() {
    sink(age, name);
    return 0;
}

```

```cpp student.h
#ifndef CPROJECTS_STUDENT_H
#define CPROJECTS_STUDENT_H


#include <string>
#include "common.h"

class Student {
public:


    int getAge() const;

    void setAge(int age);

    const std::string &getName() const;

    void setName(const std::string &name);

    Student(int age, const std::string &name);
    Student();

    int studentOperation01();
private:
    int age;
    std::string name;
};


#endif //CPROJECTS_STUDENT_H

```

```main.cpp
// source 和sink点固定，如果有断链，则sceneTestxx不能出现在codeQL的跟踪路径中


//使用set方式，检查赋值给成员变量，然后在成员函数里面使用污染源
int sceneTest01(int &sourceInt, std::string &sourceStr) {
    Student student;
    student.setAge(sourceInt);
    student.setName(sourceStr);
    student.studentOperation01();
}


//使用初始化列表方式，检查赋值给成员变量，然后在成员函数里面使用污染源
int sceneTest02(int &sourceInt, std::string &sourceStr) {
    Student student(sourceInt, sourceStr);
    student.studentOperation01();
}


int main(int argc, char **argv) {
    int sourceInt = 0;
    std::string sourceStr("");
    source(sourceInt, sourceStr);
    //scene start
    sceneTest01(sourceInt, sourceStr);
    sceneTest02(sourceInt, sourceStr);
    //scene end
    sink(sourceInt, sourceStr);
}
```

the evalution result is shown below

|序号(index)|覆盖内容(testcase )|覆盖函数(test function)|能力说明(say somthing)|结果(result)|
|--|--|--|--|--|
|1|getter setter赋值和污点追踪|sceneTest0001|使用getter setter进行数据赋值，检测这种情况是否存在赋值之后的断链|pass|
|case 1|using getter setter and taint tracking|sceneTest0001|use getter setter to set value，judage is taint tracking work well|pass|
|2|构造函数-初始化列表的检测|sceneTest0002|使用初始化列表进行数据赋值，检测这种情况是否存在赋值之后的断链|fail|
|case 2|constructor-ConstructorFieldInit |sceneTest0002|using ConstructorFieldInit to set value ，judage if taint tracking work well|fail|
|3|构造函数-拷贝构造函数的形式|sceneTest0003|使用拷贝构造函数进行数据赋值，检测这种情况是否存在赋值之后的断链|fail|
|case 3|constructor-Copy constructor  |sceneTest0003|using Copy Constuctor to set value，judage if taint tracking work well|fail|
|4|构造函数-智能指针的形式|sceneTest0004|使用智能指针进行数据赋值，检测这种情况是否存在赋值之后的断链|fail|
|case 4|Construct-Smart Ptr|sceneTest0004|use SMart Ptr to set value ，judage if taint tracking work well|fail|

and my codeql code is shown below
```cpp

/**
 * @name Taint Cap Test
 * @description: Taint Cap Test
 * @problem.severity warning
 * @kind path-problem
 * @id cpp/taint_cap_test/taint_cap_test.ql
 */

// import DataFlow::PartialPathGraph
import DataFlow::PathGraph
import cpp
import semmle.code.cpp.dataflow.TaintTracking
import semmle.code.cpp.controlflow.Guards


class MyTaintTrackingConfiguration extends TaintTracking::Configuration {
    MyTaintTrackingConfiguration() { this = "MyTaintTrackingConfiguration" }
  
    override predicate isSource(DataFlow::Node source) {
        exists(Function fc | 
            fc.getName() = "source" | 
            source.asParameter() = fc.getAParameter())
    }
  
    override predicate isSink(DataFlow::Node sink) {
        exists(FunctionCall fc | fc.getTarget().getName() = "open" | sink.asExpr() = fc.getArgument(0))
        or
        exists(ArrayExpr ae | sink.asExpr() = ae.getArrayOffset())
    }

    override predicate isAdditionalTaintStep(DataFlow::Node node1, DataFlow::Node node2) {
      TaintTracking::localTaintStep(node1, node2)
      or
      node1.asExpr() = node2.asExpr().(FieldAccess).getQualifier()
    }
}

from DataFlow::PathNode sink, DataFlow::PathNode source, MyTaintTrackingConfiguration config
where config.hasFlowPath(source, sink)
select sink.getNode(),source, sink,"This log to file uses data from $@.", source.getNode(), "call to handle.*"

```
QUESTION:
how to fix case 2-4 using ```isAdditionalTaintStep```

**Comment by jketema** [comment]
Hi @hatface. Thanks for your question. I currently do not have enough information to answer your question. Could you share the query you're trying to evaluate, including all imports. Thanks.

**Comment by hatface** [comment]
> 
hi @jketema I have updated my project and question

**Comment by jketema** [comment]
Do note that CodeQL will only display a limited number of paths for each reported location. You probably want to disentangle your test cases.

**Comment by hatface** [comment]
@jketema take a look at my project，and my testcase2，testcase3，testcase4 failed， see the result table。

**Comment by hatface** [comment]
I tried more，by comment my testcase one by one，just like the code shown below
```cpp
    //scene start
    //sceneTest01(sourceInt, sourceStr);
    //sceneTest02(sourceInt, sourceStr);
    //sceneTest03(sourceInt, sourceStr);
    sceneTest04(sourceInt, sourceStr);
```
and I found that CodeQL find the path I want

if I want CodeQL report all the path，what should I do？

**Comment by jketema** [comment]
> take a look at my project，and my testcase2，testcase3，testcase4 failed， see the result table。

They're not failing. CodeQL is just not reporting all the paths. And for every source/sink combination in your code it is finding a path.

> if I want CodeQL report all the path，what should I do？

You can increase the number of paths by specifying the `--max-paths` option when calling `codeql database analyze`, see [here](https://codeql.github.com/docs/codeql-cli/manual/database-analyze/). However, there is no guarantee that you will get all the paths.
