### ISSUE TITLE
[UX] How to run the ql tutorials in VS Code

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/codeql#11746]
**Epilog**
I recently gave a CodeQL workshop and all my workshops include challenges that are based on the "Find the thief" tutorial and the "Catch the firestarter" tutorial.
Now that lgtm.com is gone (:cry:) participants have to use VS Code and the extension.
(I am aware that the current docs are "outdated" and that there are PRs open that address _references_ to lgtm.com but I don't think there is any PR that addresses this issue) 

**Description of the Scene**
- You are attending a workshop and haven't used CodeQL or any of the associated tools before.
- You have just downloaded VS Code, installed the plugin, and cloned the starter workspace.
- You visit https://codeql.github.com/docs/writing-codeql-queries/introduction-to-ql/ and try doing exercise 1
- You try running your query:

**Description of Issue 1**
- The VS Code CodeQL extension will now ask you to select a database.
- You have no idea what the extension wants from you and close the "database selection" window, but now the extension complains with `Can't run query without a selected database (codeQL.runQuery)`.
- The user is confused.

**Description of potential workaround with Issue 2**
- The VS Code CodeQL extension will now ask you to select a database.
- You have no idea what the extension wants from you and **ask** the organizer who suggests just using any database, because the exercises do not have any `import <language>` parts (and so in theory should not care about the db) (This assumption of mine turned out to be false, I know).
- You write the exercise for example in the `codeql-custom-queries-java/` folder.
- You have picked a database that has been created for **Ruby** and so when running the query it fails with `The queries dbscheme did not match the database dbscheme`.
- The user is confused.

**Potential fix(es)**
- Do not require a database when the query does not have any `import <language>` statement. (I guess this might be a risky change, because I'd guess that a lot of code expects a db to be selected)
- Create a special directory in the starter workspace that is just for tutorial queries and include a dummy database for the tutorials.
- Be more clear in the tutorials on how to run them. This means that the tutorial should explicitly state that you have to import a database.

CC: @jf205 maybe?

**Comment by jketema** [comment]
Hi @intrigus-lgtm 

Thanks for your observations. First some good news: Most of the documentation on codeql.github.com has been updated and no longer refers to LGTM.

The only exception to the above is the tutorial. We are aware of the issue you're raising with regard to the tutorial, and we are actively working on a solution.

**Comment by jketema** [comment]
Hi @intrigus-lgtm,

https://codeql.github.com/docs/writing-codeql-queries/introduction-to-ql/ has been updated with the solution I hinted at above. I hope the solution works for you in a workshop setting. We'd of course love to hear your feedback.

I'm closing this for now as resolved. Feel free to re-open, or create new issues.
