### ISSUE TITLE
Placeholders in alerts not evaluated when running in CLI

### ISSUE THREAD

**Issue by Sissel-Wu** [github/codeql#11758]
Hi, I am a novice at CodeQL. I wrote a simple query and found the running results in VSCode and CLI are different.

The query:
```
/**
 * @name Dataflow
 * @problem.severity warning
 * @kind problem
 * @id java/example/dataflow
 */

 import java
 import semmle.code.java.dataflow.DataFlow

 from Expr src1, Expr src2
 where
   DataFlow::localFlow(DataFlow::exprNode(src1), DataFlow::exprNode(src2)) and src1 != src2
 select src1, "flow to $@", src2, src2.toString()
```

The result in VSCode contains 6 rows, as expected
```
  | flow to c | TestDataFlow.java:3:17
  | flow to ...?...:... | TestDataFlow.java:3:25
  | flow to c | TestDataFlow.java:3:25
  | flow to ...?...:... | TestDataFlow.java:3:33
  | flow to c | TestDataFlow.java:3:33
  | flow to a | TestDataFlow.java:3:17
```

However, when I ran the command `codeql database analyze <db> --format=csv --output=qlout.csv codeql/local_dataflow.ql --download`, the result (csv) only has 4 rows
```
"Dataflow",,"warning","flows to ","/src/main/java/org/example/TestDataFlow.java","3","17","3","37"
"Dataflow",,"warning","flows to ","/src/main/java/org/example/TestDataFlow.java","3","25","3","29"
"Dataflow",,"warning","flows to ","/src/main/java/org/example/TestDataFlow.java","3","33","3","37"
"Dataflow",,"warning","flows to ","/src/main/java/org/example/TestDataFlow.java","3","17","3","17"
```

Seems like the cause is that the placeholder in the query is ignored. I don't know if I overlooked anything or if this is an issue in the CLI. My command line tool version is `2.11.6`. Looking forward to your reply.

**Comment by jketema** [comment]
Hi @Sissel-Wu, Thanks for your question. Could you share the Java code you're running this on? It's very difficult to see what is going on without this.

**Comment by jketema** [comment]
Hi @Sissel-Wu, Thanks for your test case. I cannot reproduce what you're seeing unfortunately. When I run your query with your test case, I get:
```
"Dataflow",,"warning","flow to [[""c""|""relative:///TestDataFlow.java:4:16:4:16""]]","/TestDataFlow.java","3","17","3","37"
"Dataflow",,"warning","flow to [[""...?...:...""|""relative:///TestDataFlow.java:3:17:3:37""]]
flow to [[""c""|""relative:///TestDataFlow.java:4:16:4:16""]]","/TestDataFlow.java","3","25","3","29"
"Dataflow",,"warning","flow to [[""...?...:...""|""relative:///TestDataFlow.java:3:17:3:37""]]
flow to [[""c""|""relative:///TestDataFlow.java:4:16:4:16""]]","/TestDataFlow.java","3","33","3","37"
"Dataflow",,"warning","flow to [[""a""|""relative:///TestDataFlow.java:3:25:3:25""]]","/TestDataFlow.java","3","17","3","17"
```

Did you look at the correct csv file? I see that the query mentions `flow` while your csv output mentions `flows`.

**Comment by Sissel-Wu** [comment]
@jketema  Thanks for your information. I should open the correct file because I also tried outputting as `.sarif` file and found that it also only contained 4 items. I rebooted my machine and now everything works well. It outputs the same as yours. I guessed it may be my IDE not flushing my queries correctly. 

Sorry for not checking closely and thanks for your help. Have a good day!
