### ISSUE TITLE
[question] typescript and alias imports 

### ISSUE THREAD

**Issue by Nikoms** [github/codeql#11839]
Hello and happy new year :),

I'm in a typescript codebase with ts with specific `paths` in my `tsconfig` (https://www.typescriptlang.org/tsconfig#paths).

I'd like to know who is using a specific method so I wrote this query:
```
from MethodCallNode myFunction
where myFunction.getMethodName() = "bimbamboum3"
select myFunction, myFunction.getACallee()
```

It's working when I'm importing the file without using the alias (one of `paths`). As soon as I'm using my shortcut, codeQL returns no `callee`.

Is there a way to specify the alias during the extraction or during the evaluation?

Thank you for your help 🙏

**Comment by tausbn** [comment]
Thank you for your question! (And happy new year!)

I don't know the answer to this question off-hand, so I've forwarded it to the JavaScript team. They should hopefully weigh in on it soon. 🙂

**Comment by erik-krogh** [comment]
> Is there a way to specify the alias during the extraction or during the evaluation? 

Unfortunately not. And adding the feature to CodeQL is probably not straight-forward.   

Such an implementation should probably be in `Paths.qll`, and it could be similar to the current support for `outDir` in `tsconfig.json` files: https://github.com/github/codeql/blob/664fdc3b2a95253bae5ce3e00e78857fee7eb1fc/javascript/ql/lib/semmle/javascript/Paths.qll#L210 

There seem to be a decent amount of projects that use the `paths:` feature: https://cs.github.com/?scopeName=All+repos&scope=&q=%2F%22paths%22%3A+%5C%7B%2F+path%3Atsconfig.json. 
So it could be something we should look into.  

Do you have a simple TypeScript example of the code you are trying to analyze (or is you repo open-source, in that case just link to it).

**Comment by Nikoms** [comment]
Thank you for your answer @erik-krogh .

It's indeed a very common used feature. I'm still new in codeQL, do you think there is a way to simulate that with a DataFlow for example?
- Source would be the call of the method
- Sink would be the method code
- Add an "intermediate step" to say => when `@modules/xyz`, check the code in `/modules/xyz.js`

I'll try to provide you a git repo with a simple example this week.

**Comment by erik-krogh** [comment]
> It's indeed a very common used feature. I'm still new in codeQL, do you think there is a way to simulate that with a DataFlow for example?

No, I don't think so.  
This needs to be supported by the import graph, which is quite low-level in the QL code.

**Comment by erik-krogh** [comment]
Looking further into this. 
Turns out we do support `paths` in a `tsconfig.json`, as of [this PR](https://github.com/github/codeql/pull/2712), I had just forgotten about it.  
The implementation works by basically "asking" the TypeScript compiler about what is imported from where. 

So I'm going to need a more complete example before I can tell you why the analysis isn't finding the result you are looking for.

**Comment by Nikoms** [comment]
OK thank you Erik, I'll retry by looking at this MR

Thank you again
