### ISSUE TITLE
"CodeQL library search" language filter does not work for Ruby

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#11840]
### Description of the issue

The language selection on the "CodeQL library search" page (https://codeql.github.com/codeql-standard-libraries/search.html) does not seem to work properly for Ruby. Selecting only Ruby seems to act as if nothing was selected and shows results for all languages.

### Reproduction steps
1. Open https://codeql.github.com/codeql-standard-libraries/search.html?addsearch=test
2. Untick all language checkboxes except for "Ruby"
3. Click the "Search" button
4. Scroll down and look at the results
:x: Bug: You will see non-Ruby results

### Additional comments

The current search feature is also not super user-friendly:
- It is a separate page
- It does not remember the language selection; often you are mostly looking at the documentation for a specific language so you have to uncheck all other languages every single time

If possible it would be great if a search box for a specific language could be added also on the library page for that language (for example similar to the search field in the top right corner of [`javadoc` documentation](https://docs.oracle.com/en/java/javase/17/docs/api/)). That would (1) allow searching without having to open a separate page and (2) not require having to adjust language filtering.

**Comment by aibaars** [comment]
@Marcono1234 Apologies for not responding to this earlier. Thanks for reporting! Things seem to be working now though.  Please re-open if it still doesn't work for you.

**Comment by Marcono1234** [comment]
@aibaars, it seems to be fixed for Ruby, but instead occurs for Swift now. Can / should this be tracked here or should I create a new issue?

> Please re-open if it still doesn't work for you.

I cannot reopen this issue. As far as I know, authors of issues and pull requests can only reopen them if they closed them themselves (or if they are a member of the repository).

**Comment by aibaars** [comment]
Curious, I didn't know that you wouldn't be able to reopen your own issue.

Thanks for letting us know that the same is happening now for Swift. I guess some search index needs updating or so. I'll let the team know.

**Comment by aibaars** [comment]
We were able to reproduce the issue for Swift, and a fix should be available shortly. The cause was a wrongly named variable as shown by the JavaScript console:
```
VM285 search.html:30 Uncaught ReferenceError: swift_filter is not defined
    at applyFilters (VM285 search.html:30:55)
    at HTMLInputElement.onchange (VM294 search.html:1:1)
```

Thanks again for your help!

**Comment by Marcono1234** [comment]
Thanks for fixing this!

> Curious, I didn't know that you wouldn't be able to reopen your own issue.

In case you are interested, here is the corresponding feature request https://github.com/orgs/community/discussions/5084

**Comment by felicitymay** [comment]
@Marcono1234 - many thanks for reporting both of those bugs. You should find that the Swift and Ruby filters both work now.
