### ISSUE TITLE
CodeQL fails to auto-build a Golang project with vendored deps and submodules

### ISSUE THREAD

**Issue by cardil** [github/codeql#12010]
**Description of the issue**

The CodeQL action fails to auto-build a Golang project, that uses both Golang workspace, and who's vendoring the dependencies.

See for failure: https://github.com/knative-sandbox/kn-plugin-event/actions/runs/3926412223/jobs/6712106255

In such project, the build shouldn't include the `-mod=vendor` build flag. From Golang itself:

```
$ go build -race -mod=vendor ./...                                                                                         
go: -mod may only be set to readonly when in workspace mode, but it is set to "vendor"
	Remove the -mod flag to use the default readonly value,
	or set GOWORK=off to disable workspace mode.
```

**Comment by smowton** [comment]
FYI, a short-term workaround is to replace the `autobuild` step with one that runs `go build ./...`. Thanks for your PR -- we'll check that there aren't corner cases around go.work vs. module modes, and tweak or merge as appropriate!

**Comment by cardil** [comment]
BTW. What's the purpose of the build command in terms of Go? The CodeQL analyses the sources, not binaries, right? Maybe the answer to this question should be documented in codeql-action...

**Comment by smowton** [comment]
That's true of other compiled languages too -- they extract code from source, as well as in some cases from compiled dependencies. The build command serves to effectively document the compiler settings required to understand the source, in terms of where to search for dependencies and libraries, compilation options and so on. For Go that means any option you pass to `go build` will be used to call `packages.Load` (https://pkg.go.dev/golang.org/x/tools/go/packages#Load) and so parse and link your code the same way the compiler would do.

**Comment by cardil** [comment]
Right. But that means, for go, instead of adding a build step, I should specify build flags for codeql-analyze step, right? Otherwise, codeql-analyze will not know the build flags the project is using.

As an example, we use `e2e` tag to specify e2e tests, so the build must have `-tags e2e` flags. Then, I should pass those to analyze step. As I understand this...

**Comment by smowton** [comment]
The autobuild step (or replacement manual build step) will be traced to find `go build` invocations and so extract a CodeQL database. The analyze step will then run queries against that database. Therefore anything limiting the `.go` files that should get built should be conveyed in a manual build step, not to the analyze step.

**Comment by cardil** [comment]
In Knative we use the following build command:

```
tags="$(go run knative.dev/test-infra/tools/go-ls-tags@latest --joiner=,)"
echo "Building with tags: ${tags}"
go test -vet=off -tags "${tags}" -exec echo ./...
```

We use `go test` to make sure the test code compiles, not only the production code.

But, that build command fails to find any sources, see: https://github.com/knative-sandbox/kn-plugin-event/actions/runs/4043115700/jobs/6951655266

**Comment by smowton** [comment]
Does a build script like the following do what you want?

```
tags="$(go run knative.dev/test-infra/tools/go-ls-tags@latest --joiner=,)"
  
echo "Building with tags: ${tags}"
go build -tags "${tags}" ./...
```

A `go test` command is assumed per default not to represent code you want in your CodeQL database (unlike `go install` or `go run`), because usually people want to query production but not testing code. If you want to verify that your tests pass or that code you don't want to analyze with CodeQL builds, I suggest doing that either in a separate action to the CodeQL action.

**Comment by cardil** [comment]
Yep, I'm checking that...

Now, I get how it works. You are tracing the `go build` calls with `LD_PRELOAD`.

Maybe it would make sense to add a parameter to the init step, like `tests: true` (default to `false`). If such step is set, then the test calls will be traced as well. That would allow us to analyze the test code too!

**Comment by smowton** [comment]
Pretty much :) Glad you've got it working, and we'll consider if the analyze-test-cases case is common enough that we want to have a dedicated option for it. Thanks for sticking with us and responding quickly!

**Comment by smowton** [comment]
(I'll continue to track the non-workaround case for `go.work` in https://github.com/github/codeql/pull/12012)
