### ISSUE TITLE
Add support for Rust

### ISSUE THREAD

**Issue by atodorov** [github/codeql#12017]
**Description of the issue**

It looks like CodeQL doesn't support the Rust programming language. Please add it.

**Comment by aeisenberg** [comment]
Thank you for your feedback. We will consider this in our future planning.

**Comment by coadaflorin** [comment]
Hey @atodorov, just wanted to let you know that we shipped support for Rust in CodeQL to [public preview](https://github.blog/changelog/2025-06-30-codeql-support-for-rust-now-in-public-preview/). Give it a go and [let us know](https://github.com/orgs/community/discussions/161754#discussioncomment-13627726) how things went for you!

**Comment by lunkhaosei-lgtm** [comment]
wasm-language-server/client/package.json
