### ISSUE TITLE
Feature Request - Arbitrary Redirect (Unsanitized Redirect)

### ISSUE THREAD

**Issue by elliot-huffman** [github/codeql#12035]
Add the ability to detect if a redirect for an Express.JS server is taking user input and if that user input is not sanitized. This could be used to attack end users and redirect them to unauthorized locations.

This is represented as:
https://cwe.mitre.org/data/definitions/601.html

**Comment by aeisenberg** [comment]
Hi there,

We have two javascript queries that address this CWE. See here: https://github.com/github/semmle-code/blob/aeisenberg/database-init-refactor/ql/javascript/ql/src/Security/CWE-601. Please let me know if they are not sufficient for your purposes.

**Comment by elliot-huffman** [comment]
That link didn't work for me.

**Comment by aeisenberg** [comment]
Ah...apologies. Updated the link.

**Comment by elliot-huffman** [comment]
That looks about right to me, thanks!
