### ISSUE TITLE
Uncaught exception - Access to the path is denied - Semmle.Extraction.TrapWriter.ArchiveContents

### ISSUE THREAD

**Issue by cixtor** [github/codeql#12066]
As of **Jan 24th, 2023** w/ [v2.12.1 -- 970025b](https://github.com/github/codeql-cli-binaries/releases/tag/v2.12.1) there is an intermittent error that, in my case, occurs approximately 80% of the time when I try to run one or more tests. This happens both via Visual Studio Code as well as outside the editor (using cmd.exe on Windows).

For example, I could run a test 8 times and see the error, then run the test again for the 9th time to see it succeed with absolutely no changes in the test code or the `.ql` file(s), then succeed again the 10th time, then fail again with the 11th attempt, then if I take a break for 1-2 hours and run the test again, I get the same error a couple of more times until it works, but then fails again seemingly at random.

Some of my co-workers have observed the same error a couple of times, but their suggestion is to either continue clicking the “Run test” button until the error goes away, or restart the code editor, which does not help because, as I explained before, the error also occurs when I execute the codeql binary from a command line interface like `cmd.exe`.

Our theory is that the trigger is a combination of a race condition and file lock.

However, according to the current implementation of [TrapWriter.ArchiveContents](https://github.com/github/codeql/blob/main/csharp/extractor/Semmle.Extraction/TrapWriter.cs#L217-L232), which has not been modified since Mar 2, 2021, there is an `IOException` handler that is supposed to take care of that scenario, unless **“Error: Uncaught exception. Access to the path is denied.” is not an exception but an error, in which case a `try-catch` statement makes no sense.

Could you please double check that code to see if there is a way to solve this problem? Thanks.

---

Below is the error, formatted for readability:

```
C:\...\foo> codeql test run --show-extractor-output .
Executing 1 tests in 1 directories.
Extracting test database in C:\...\foo.
[build-err] Error:   Uncaught exception. Access to the path is denied. at C:\...\foo\TestJohn.cs: (0,0)-(0,0)
[build-err]    at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
[build-err]    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
[build-err]    at Semmle.Util.FileUtils.MoveOrReplace(String src, String dest)
                  in D:\a\semmle-code\semmle-code\ql\csharp\extractor\Semmle.Util\FileUtils.cs:line 36
[build-err]    at Semmle.Extraction.TrapWriter.ArchiveContents(ITransformedPath transformedPath, String contents)
                  in D:\a\semmle-code\semmle-code\ql\csharp\extractor\Semmle.Extraction\TrapWriter.cs:line 224
[build-err]    at Semmle.Extraction.CSharp.Entities.File.Populate(TextWriter trapFile)
                  in D:\a\semmle-code\semmle-code\ql\csharp\extractor\Semmle.Extraction.CSharp\Entities\File.cs:line 20
[build-err]    at Semmle.Extraction.Context.<>c__DisplayClass37_0.<Populate>b__4()
                  in D:\a\semmle-code\semmle-code\ql\csharp\extractor\Semmle.Extraction\Context.cs:line 313
[build-err]    at Semmle.Extraction.Context.Try(SyntaxNode node, ISymbol symbol, Action a)
                  in D:\a\semmle-code\semmle-code\ql\csharp\extractor\Semmle.Extraction\Context.cs:line 459

[ERROR] Spawned process exited abnormally (code 1; tried to run:
  [C:\...\csharp\tools\win64\Semmle.Extraction.CSharp.Driver,
    --qltest,
    -unsafe,
    -target:library,
    /noconfig,
    /r:System.Private.CoreLib.dll,
    /r:System.dll,
    /r:System.Core.dll,
    /r:System.Runtime.dll,
    /r:System.Console.dll,
    --console,
    --verbosity,
    2,
    Program.cs,
    TestAlice.cs,
    TestBob.cs,
    TestJohn.cs,
    TestJane.cs
  ]
)

Could not extract a dataset in C:\...\foo:
Extraction command C:\...\csharp\tools\win64\Semmle.Extraction.CSharp.Driver failed with status 1.
Extraction command C:\...\csharp\tools\win64\Semmle.Extraction.CSharp.Driver failed with status 1.
[1/1] FAILED(EXTRACTION) C:\...\foo\Vulnerability.qlref
Compiling queries in C:\...\foo.
0 tests passed; 1 tests failed:
  FAILED: C:\...\foo\Vulnerability.qlref
```

**Comment by aeisenberg** [comment]
Thank you for your bug report. I've forward this to the relevant team and they should be able to help you.

**Comment by tamasvajk** [comment]
I couldn't reproduce your issue locally, so I investigated it a bit by digging into the code. TLDR: I think you're right, `Access to the path is denied.` is not an `IOException`, we'll need to change the exception handling to be broader.

These are my findings so far: We're [moving a temporary file to a given location](https://github.com/github/codeql/blob/main/csharp/extractor/Semmle.Extraction/TrapWriter.cs#L220-L231). Based on your exception message (`Uncaught exception. Access to the path is denied. at C:\...\foo\TestJohn.cs:`), the target path is not accessible (probably locked by another copy operation). We're using `File.Move` for moving the file, which internally uses `FileSystem.MoveFile()`. This, `MoveFile` is platform specific, [here's the Windows implementation](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs#L204), which doesn't seem to help much. But assuming that the [Unix implementation](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Unix.cs#L181-L228) is close in implementation, I looked at that one. I think this is [where the exception is thrown](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs#L141). Looks like an [`UnauthorizedAccessException`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/UnauthorizedAccessException.cs#L23) is being thrown (with an inner `IOException`, it's also a reasonable assumption based on the exception message that you reported), which is not an `IOException`.
