### ISSUE TITLE
General issue - Broken DataFlow in javascript

### ISSUE THREAD

**Issue by ka1n4t** [github/codeql#12115]
**Description of the issue**

Hi, I got a problem when I try to find possible tainted variable in below source code:
```javascript
//file A.js
let objA = {};
export default objA = {
  getResult: function (data) {
    objB.getInfo({
      success: function (res1) {
        ret = {
          info1: res1.info
        }
        data.success(ret)
      }
    })
  }
}
```

```typescript
//file B.ts
objA.getResult({
  success: async (res2) => {
    const {info2} = res2
  }
})
```

query like this:
```codeql
import javascript

class TrackResVar extends DataFlow::Configuration{
    TrackResVar(){
        this = "TrackResVar"
    }

    override predicate isSource(DataFlow::Node source){
        exists(|
            paramOfTargetMethod(source.asExpr())
            )
    }

    override predicate isSink(DataFlow::Node sink){
        sink.asExpr() instanceof Expr
    }

    predicate paramOfTargetMethod(Parameter p) {
        exists( MethodCallExpr ce, DataFlow::FunctionNode f| 
             ce.getMethodName() = "getInfo"
             and ce.getReceiver().toString() = "objB"
             and f.flowsToExpr(ce.getAChild+())
             and f.getName() = "success" 
             and f.getAParameter().getParameter() = p
             )
    }
}

from TrackResVar trv, DataFlow::Node source, DataFlow::Node sink
where trv.hasFlow(source, sink)
select sink
```

I can only got results including `res1.info` in A.js when I run this query.

**Comment by MathiasVP** [comment]
Hi @ka1n4t,

We have a list of steps you can perform to debug "missing flow" issues like this. See https://codeql.github.com/docs/writing-codeql-queries/debugging-data-flow-queries-using-partial-flow/ for the full list. The most important one (which is probably why it's the first item on the list) is `Checking sources and sinks`. You can do this by using `CodeQL: Quick Evaluation` to find the set of `DataFlow::Node`s satisfying `isSource`, and the set of nodes satisfying `isSink`.

Are these predicates finding all the sources and sinks that you expect? In particular, I'm not sure if `paramOfTargetMethod(source.asExpr())` makes sense when `paramOfTargetMethod`'s first parameter is of type `Parameter` (since I don't think an expression can also be a parameter).

In any case, I'd start by checking the sources and sinks. If those are indeed what you expect we can dig deeper into what's going on.

**Comment by ka1n4t** [comment]
> See https://codeql.github.com/docs/writing-codeql-queries/debugging-data-flow-queries-using-partial-flow/ for the full list.

Javascript lib seems different. It doesn't contains `fieldFlowBranchLimit`, `explorationLimit`...



> Are these predicates finding all the sources and sinks that you expect? In particular, I'm not sure if `paramOfTargetMethod(source.asExpr())` makes sense when `paramOfTargetMethod`'s first parameter is of type `Parameter` (since I don't think an expression can also be a parameter).

Sources and sinks seem to be will defined, I can use this query to find `res1 param` in `success: function (res1) {`.

My goal is find a path from `res1 param` in `success: function (res1) {` to `res2` in `const {info2} = res2`

**Comment by MathiasVP** [comment]
Oh yes you're right. JavaScript doesn't use the same dataflow library. I'll ask the JavaScript team about this and hopefully they'll be able to help you.

**Comment by ka1n4t** [comment]
> Oh yes you're right. JavaScript doesn't use the same dataflow library. I'll ask the JavaScript team about this and hopefully they'll be able to help you.

Thanks!

**Comment by erik-krogh** [comment]
Hi 👋  I'm the JavaScript guy. 

----- 

The partial flow support in the JavaScript dataflow library is quite limited compared to the shared dataflow library.  
But your `isSink()` predicate already highlights everything, so you are essentially already doing partial flow (to the extent that JavaScript supports it). 
So nothing more to do about partial flow.   

----- 

Your example is incomplete (none of the files import the other, and there is no definition of `objB`).  
But I can still see what's happening.  

Callbacks and higher-order-functions are hard, and unfortunately the pattern you write here is not something we currently track flow through, and there is no simple way to add that.   

We might in the future move JavaScript from it's own dataflow library to the shared dataflow library 🤞 
And that might help support use-cases like yours.   

You've given us another piece of motivation for doing the move to the shared dataflow library, so thanks for that.  
But I don't think I can help you more for now.

**Comment by ka1n4t** [comment]
Looking forward to future updates~
