### ISSUE TITLE
JavaExtractorArgs#parse method parameter parsing takes too long

### ISSUE THREAD

**Issue by thanatoskira** [github/codeql#12136]
example:
```
java -cp semmle-extractor-java.jar com.semmle.extractor.java.JavaExtractor --javac-args "@@@/javac.args"
```

If the javac.args file contains a lot of java files to process like the following：

```
-Xprefer:source
a1.java
a2.java
a3.java
....
a50000.java
```

In the processing logic of the com.semmle.extractor.java.args.JavaExtractorArgs#parse() method, for .java files, a large number of unnecessary parameters starting with `-` will be judged, and finally added to `result.otherOptions`

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/8370120/217763411-7736117c-373e-4b3c-ab4a-c27cc93d89ac.png">

<img width="999" alt="image" src="https://user-images.githubusercontent.com/8370120/217764072-b61ae075-21ec-4170-a0d5-021cd1c03a2d.png">

This will consume a lot of time. In fact, it can be solved by first judging whether the current parameter starts with `-` at the beginning of the loop.

**Comment by smowton** [comment]
Fair enough -- made a PR to fix this (against a private repo); I'd expect this performance fix to go into the next-but-one release, ETA early March.
