### ISSUE TITLE
Updated Kotlin version range 1.8.10

### ISSUE THREAD

**Issue by RealYusufIsmail** [github/codeql#12172]
I have an issue where i get an error because I am using kotlin 1.8.10

**Comment by alexet** [comment]
We added support for kotlin 1.8.10 in https://github.com/github/codeql/pull/12090 so the next release of codeql will have support. We expect the next version will be released early next week.

Note that `.X0` releases of kotlinc often change the compiler plugin API which we use so we have to make a new release for even minor versions.

**Comment by igfoo** [comment]
Support for 1.8.10 (and many newer versions) has since been added.
