### ISSUE TITLE
[GO] getCalleeExpr behavior for functions from other packages

### ISSUE THREAD

**Issue by ivan-gavran** [github/codeql#12204]
**Description of the issue**

Consider this code snippet:

```go
import (
	"example/morefunctions"
)

func alternativeIncrement(i int) int {
	return i+1
}

func main() {
	var a int
	for i := 0; i < 10; i++ {
		if i%2 == 0 {
			a = morefunctions.Increment(i)
		} else {
			a = alternativeIncrement(i)
		}
	}
}
```

When calling function `ex.getCalleeName()` (for some `CallExpr ex`), I get an expected value for the function call in the else branch (`alternativeIncrement`), but in the if branch, I get as a result _selection of `Increment`_.

This poses a problem for the function `getTarget`, which is defined by `  Function getTarget() { this.getCalleeExpr() = result.getAReference() }`.

When inspecting the AST, for the else branch, the `CallExpr` node has two children, the first one being a [`FunctionName`, `Ident`] and a second one being  [`Ident`,`VariableName`].
Unlike that, for the if branch, the `CallExpr`'s first child is a `SelectorExpr` and only its children are [`Ident`, `PackageName`] and then [`Ident`], corresponding to the function name.

Is this behavior expected? If so, what would be an alternative to using `getTarget` here?

**Comment by smowton** [comment]
I recommend using `DataFlow::CallNode::getACallee`, or `getACalleeIncludingExternals` if you want to include functions without a definition within the database. The AST classes intentionally expose the distinction between an unqualified name (else branch) and a qualified call (if branch), whereas the data-flow classes provide accessors that operate at a higher level of abstraction.

**Comment by ivan-gavran** [comment]
Thanks for the answer, @smowton ! However, the same problem seems to persist because `getACalleeIncludingExternals`  also uses `getTarget()` in its definition.

As a test case, I considered querying first
`from DataFlow::CallNode c select c`
resulting in both calls to `Increment` and `alternativeIncrement`.

But when querying 
`from DataFlow::CallNode c select c, c.getACalleeIncludingExternals()`,
I only get a call to `alternativeIncrement`.

To narrow down the problem, the same happens when running
`from DataFlow::CallNode c select c, c.getTarget()`

**Comment by smowton** [comment]
Ah sure, sorry this is a different issue to what I thought at first. Generally speaking that use of `getAReference()` to pull the Function relating to a particular static reference (e.g. `morefunctions.Increment`) works as expected -- for example, a call to `fmt.Println` returns the function `Println` and `getCalleeName` similarly returns the string `Println`. Therefore I suspect something has gone wrong at extraction time -- perhaps we couldn't see the package `example/morefunctions`? Could you upload the extraction log, or better yet an example database if the code is a toy sample?

**Comment by ivan-gavran** [comment]
Thanks, that was indeed the problem: in the output of generating a database there was a complaint about being able to import the name.  Concretely, I believe the problem was that when running `codeql create ...`, I gave `--source-root` argument to be a directory above the go project.

Thanks a lot for your help, @smowton!
