### ISSUE TITLE
General issue: codeql cannot find the specified javascript data flow

### ISSUE THREAD

**Issue by ttttmr** [github/codeql#12201]
I use codeql in vscode
Here is the javascript code
```javascript
let s0 = document.createElement("script");
s0.textContent = window.name;
document.head.appendChild(s0);
```
I define `window.name` as source, any appendChild operation as sink, execute this query without any results
I tried to increase isAdditionalTaintStep to let window.name propagate to s0, but I still couldn’t find it

```ql
/**
 * @kind path-problem
 */
import javascript
import DataFlow::PathGraph

class Config extends TaintTracking::Configuration {
  Config() { this = "Config" }

  override predicate isSource(DataFlow::Node source) {
    // window.name
    DataFlow::globalVarRef("window").getAPropertyRead("name") = source
  }

  override predicate isSink(DataFlow::Node sink) {
    // *.appendChild(sink)
    exists(DataFlow::SourceNode s | s.getAMethodCall("appendChild").getArgument(0) = sink)
  }

  override predicate isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ) {
    exists(DataFlow::SourceNode s |
      isDomNode(s) and
      pred = s.getAPropertyWrite().getRhs() and
      succ = s
    )
  }
}

from Config cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where cfg.hasFlowPath(source, sink)
select sink.getNode(), source, sink, "XSS"
```
![image](https://user-images.githubusercontent.com/32825326/219323134-8f4a1f55-0fda-4018-8e1b-bd1a5c9ae940.png)

Using isSource, isSink and isAdditionalTaintStep in Quick Evaluation, it seems that there is no problem

isSource
![image](https://user-images.githubusercontent.com/32825326/219323251-a56858cb-ee7e-4c6d-be63-ac0b04926de4.png)
isSink
![image](https://user-images.githubusercontent.com/32825326/219323333-7935ccfe-f7f0-44c4-92bb-1246110cc56b.png)
isAdditionalTaintStep
![image](https://user-images.githubusercontent.com/32825326/219323504-99885c5c-038c-4ea7-9159-49bbf2eba5aa.png)

**Comment by erik-krogh** [comment]
It's due to `s0` being a global variable in your example.  
We don't have a lot of flow between global variables, because that can cause a lot of imprecise flow.  

You can either change your example to not use global variables: 
```JavaScript
function main() {
  let s0 = document.createElement("script");
  s0.textContent = window.name;
  document.head.appendChild(s0);
}
```

Or add a step between global variables: 
```CodeQL
// A step between two uses of a global variable in the same file.  
exists(string var, File f |
  pred = DataFlow::globalVarRef(var) and
  succ = DataFlow::globalVarRef(var) and
  f = pred.getFile() and
  f = succ.getFile()
)
```
