### ISSUE TITLE
[GO] Precision of mayPanic

### ISSUE THREAD

**Issue by ivan-gavran** [github/codeql#12206]
I was experimenting a bit with the predicate `mayPanic` and it seems to always be `true`. (It is said to be an overapproximation, but I am still unable to find any functions for which it would be `false`.)

For instance, consider the following simple example:

```go
package main

func Constant() int {
	return 1
}

func Identity(x int) int {
	return x
}

func Increment(x int) int {
	return x + 1
}

func main() {
	Constant()
}

```

When running this query:
```codeql
from Function f 
where f.mayPanic()
select f, f.getName()
```
I get all those functions. 

Am I getting something wrong or is `mayPanic` very imprecise? Is there some place to read more details about how it works?

**Comment by smowton** [comment]
It only currently returns false for built-in functions known to never panic. See https://github.com/github/codeql/blob/main/go/ql/lib/semmle/go/Scopes.qll#L661 for the list of functions currently modelled in this way.

**Comment by ivan-gavran** [comment]
Great, thanks for the answer!
