### ISSUE TITLE
False positive: go/incorrect-integer-conversion

### ISSUE THREAD

**Issue by eiffel-fl** [github/codeql#12241]
Hi.

**Description of the false positive**

I think `codeql` does not handle case where the upper-bound check results in code flow break like using `return` or `continue`.
Indeed no example with previous `return` or `continue` are listed on [this page](https://codeql.github.com/codeql-query-help/go/go-incorrect-integer-conversion/).

**Code samples or links to source code**

The following code checks if the value is above upper-bound and `continue` the loop to the next iteration:
https://github.com/inspektor-gadget/inspektor-gadget/blob/53f2a07425b20e007cbc5b2a1942ce238d45f254/pkg/container-collection/k8s.go#L128-L140

Even though a check is done, `codeql` creates an alert:
https://github.com/inspektor-gadget/inspektor-gadget/security/code-scanning/4

Best regards and thank you in advance.

**Comment by smowton** [comment]
It's not a matter of using `continue`; that sort of guard is recognised. It is a shortcoming of the incorrect-integer-conversion query, which doesn't recognise `<= math.MaxUint32` as an adequate check in the case where the source type is signed. https://github.com/github/codeql/pull/12247 should fix the problem.
