### ISSUE TITLE
C/C++: try to trace a function pointer in a big database

### ISSUE THREAD

**Issue by iiins0mn1a** [github/codeql#12256]
I'm trying to trace funciton pointer's dataflow to identify some VariableCall's source funciton. And as I mentioned long time ago, my target is a huge database, which was generated by `allyesconfig` linux kernel with version 6.0. So the performance is critical. 

Besides, I've already tried the `.qll` "PointsTo()", it costs too many memory... and never terminates, or it maybe need a unresonable time to terminate... (already tried for more than 3 days)

Please help me to optimize my query, using dataflow lib for a funciton pointer tracking.

One of my core implementation is a predicate which can trace a funciton pointer's source. And here is my query:
(Order of code is reorganized to be more readable...)
```ql
/**
 * `fp` is the `VariableCall`'s VariableAccess which containes the function pointer.
 */
Function traceFunctionPointer(VariableAccess fp) {
    result = fpFromDataFlowFunctionAccess(fp) or
    result = fpFromOther(fp)
}

Function fpFromDataFlowFunctionAccess(VariableAccess fp) {
    exists(
        DataFlow::Node src, DataFlow::Node sk, FunctionAccess source, FunctionPointerFlow config |
        fp.getType() instanceof FunctionPointerType and
        // sameArea(source.getFile(), fp.getFile()) and
        src.asExpr() = source and sk.asExpr() = fp and
        config.hasFlow(src, sk) and
        result = source.getTarget()
        )
}

Function fpFromOther(VariableAccess fp) {
    result = fpFromGlobal(fp)
}

Function fpFromGlobal(VariableAccess fp) {
    fp.getType() instanceof FunctionPointerType and
    exists(
        DataFlow::Node src, DataFlow::Node sk, Expr source, GlobalVariable gv, FunctionPointerFlow config |
        // sameArea(source.getFile(), fp.getFile()) and
        src.asExpr() = source and sk.asExpr() = fp and
        config.hasFlow(src, sk) and
        getVariableFromExpr(source) = gv and
        result = getFuncFromGlobal(gv)
        )
}

class FunctionPointerFlow extends DataFlow3::Configuration {
    FunctionPointerFlow() { this = "FunctionPointerFlow" }
    
    override predicate isSource(DataFlow::Node node) {
        any()
    }
    
    override predicate isSink(DataFlow::Node node) {
        any()
    }

    override predicate isAdditionalFlowStep(DataFlow::Node node1, DataFlow::Node node2) { 
        doField2StructEdge(node1, node2) or
        doGlobalVariableAccess(node1, node2) or
        doArray2Base(node1, node2)
    }

    override int fieldFlowBranchLimit() { result = 16 }

    override int explorationLimit() { result = 16 }
}

```
Actually, I divided this problem into two parts, due to a bug(maybe?) in standard dataflow analysis. And here follows my comments: 
- The first part is `fpFromDataFlowFunctionAccess`, trying to find a specific `FunctionAccess` in the global area(whole kernel), which will then flow into a `VariableCall`.
    - Theoretically, this predicate should handle all situations. A function can be only used as a `FunctionAccess` to flow into a `VariableCall`. But `FunctionAccess` in a `GlobalVariable`'s `Initializer` just can not flow outside, even with a `isAdditionalFlowStep()` like this:
    ```ql
    /**
    * for handle GlobalVariable's Initializer, but it didn't work...
    */
    predicate doGlobalVariableAccess(DataFlow::Node node1, DataFlow::Node node2) {
        // &drivers_alg[0]
        exists(
            VariableAccess va, GlobalVariable gv, Expr source |
            node1.asExpr() = source and node2.asExpr() = va |
            va.getQualifier*().(VariableAccess).getTarget() = gv and 
            source.getEnclosingVariable() = gv
            )
        or doGlobalVariableAccess(node2, node1)
    }
    ```
- The second part is to handle situations which standard dataflow can not handle, like `GlobalVariable`. 
    - using dataflow to find any global variable access flow to the sink VariableCall and then return any function access in this variable's initializer.
- The commented loc `// sameArea(...)` is a predicate for optimization.
    - I try to constrain the source to the same range with sink, using file path string similaration, but it's still tooooo slow. According to the log, predicate `toString()`... consumed more than 3 hours... And it's still running at this moment.
    - file path string similaration should be make sense in some degree, like a FunctionAccess in `drivers/a/1.c` will not flows to `drivers/b/1.c` in the most cases.
- When I query this `traceFunctionPointer` on an interface of crypto driver `VariableCall`(which means this `VariableCall`'s source can be all crypto drivers, but it's only ONE VariableCall), it costs more than one day and did not stop, I think it's unacceptable...and I terminated it by myself.

here is my question:
- Please help me to optimize my query... And maybe teach me how to optimize query, maybe some tips... plz T-T
- About the general issue, dataflow or pointsTo? If I can not figure out with dataflow, maybe I will try to optimize pointsTo() lib...
- One of my predecessors generated the kernel database with partial kernel, like one subsystem for one database, it's kind of cool and worked fine, maybe I will try it later. What do you think of this solution?

Hi, there, I would thank anyone could offer help or insights from the bottom of my heart. Thank you~

For simplicity, some code is omitted, call me if it's needed.

**Comment by jketema** [comment]
Hi @iiins0mn1a,

Thanks for your question. `pointsTo` is know to have performance problems - as you noticed - so we advice against using it and to use the dataflow library.

The main thing that stands out to me is the following in your dataflow configuration:
```codeql
    override predicate isSource(DataFlow::Node node) {
        any()
    }
    
    override predicate isSink(DataFlow::Node node) {
        any()
    }
```
This will try to find flow between each pair of dataflow nodes, not just ones that represent function pointers, which will be slow even on small databases. Is there any reason these two predicates are not restricted, like:
```codeql
    override predicate isSource(DataFlow::Node node) {
        nodes.asExpr() instanceof FunctionAccess
    }
    
    override predicate isSink(DataFlow::Node node) {
         nodes.asExpr().(VariableAccess).getType() instanceof FunctionPointerType
    }
```
Potentially you might want restrict `isSource` and `isSink` even further to specific function pointers you're interested in to improve performance.

I'm not sure exactly what the problem with global variables is. Could you provide an example of the kind of flow you're missing?

**Comment by iiins0mn1a** [comment]
Hi, @jketema Thanks a lot for your reply~ 

Reason for not restricting `isSource/sink()` are:
- in `fpFromGlobal()`, I want to reuse the config for functionAccess flow in `fpFromDataFlowFunctionAccess`. It's kind of lazy. 
- I will make it a new one, instead of reusing XD

here is my example:
```c
struct a_request{
    unsigned int state;
    unsigned int index;
    char temp;
    void *__ctx[];
};

struct a_ctx{
    unsigned int ctx_state;
    unsigned int ctx_index;
    char buf[0x10];
};

void *get_actx(struct a_request * areq)
{
    return areq->__ctx;
}

void do_digest(struct a_request *areq)
{
    sink();
}

struct crypto_a{
    void (*digest)(struct a_request *req);
    int reqsize;
};

struct a_template{
    char name[0x10];
    struct crypto_a alg;
};

struct a_tfm{
    char name[0x10];
    void (*digest)(struct a_request *req);
    int reqsize;
};

struct a_template drivers_alg[] = {
    {
        .name = "test1",
        .alg = {
            .digest = do_digest, // source()
            .reqsize = 0x10,
        },
    },{
        .name = "test2",
        .alg = {
            .digest = do_digest2,
            .reqsize = 0x8,
        },
    },
};

struct a_tfm *a_get_tfm(struct a_template *t_alg)
{
    struct a_tfm *ret;
    ret = (struct a_tfm *)malloc(sizeof(struct a_tfm));
    strcpy(ret->name, t_alg->name);
    ret->digest = t_alg->alg.digest;
    ret->reqsize = t_alg->alg.reqsize;

    return ret;
}

void a_do_op(struct a_request *req, void (*digest)(struct a_request *))
{
    digest(req);
    return;
}

int test_value = 10;

void test(void)
{
    struct a_tfm *tfm;
    struct a_request *areq;
    
    tfm = a_get_tfm(&drivers_alg[0]); // GlobalVariable access
    areq = (struct a_request *)malloc( sizeof(struct a_request) + sizeof(struct a_ctx) );
    a_do_op(areq, tfm->digest); // sink()

    return;
}
```
This example is extracted from kernel crypto framework, when I debugged this dataflow with partial flow (rev), I found that we can trace function pointer back to `&drivers_alg[0]: access to array`, but can not trace into this GlobalVariable's `Initializer`, resulting to the failure to trace back to source.

To fix this problem, as I mentioned before, `doGlobalVariableAccess()` is used in additional flow step, and the result of quick-evaluation showed that edge from `digest` <--> `drivers_alg` is added, then I added `doField2StructEdge()` for edge from `drivers_alg` <--> `access to array`:
```ql
predicate  doField2StructEdge(DataFlow::Node node1, DataFlow::Node node2) {
    exists(
        FieldAccess access | 
        node2.asExpr()  = access.getQualifier() and
        node1.asExpr() = access
        )
    or
    doField2StructEdge(node2, node1)
}
```
But dataflow (rev) from sink just can not reach the source, I can't understand the reason.

**Comment by jketema** [comment]
> in fpFromGlobal(), I want to reuse the config for functionAccess flow in fpFromDataFlowFunctionAccess. It's kind of lazy.

There is quite some caching going on under the hood, so it should be fine to have two configurations. You do insist of having a single configuration, but then it should still be restricted:
```codeql
 override predicate isSource(DataFlow::Node node) {
        nodes.asExpr() instanceof FunctionAccess
        or
       exists(GlobalVariable gv | gv = getVariableFromExpr(node.asExpr()))
    }
```

With respect you you global variable problem. I'm still somewhat confused, as it does not involve any function pointers at the source. Is that intentional?

**Comment by iiins0mn1a** [comment]
> With respect you you global variable problem. I'm still somewhat confused, as it does not involve any function pointers at the source. Is that intentional?

Let me explain it with more detail. This is a `GlobalVariable` with name "drivers_alg", it's array and has a `Initializer` which is responsible for the initialization of global variable:
```c
struct a_template drivers_alg[] = {
    {
        .name = "test1",
        .alg = {
            .digest = do_digest, // source()
            .reqsize = 0x10,
        },
    },{
        .name = "test2",
        .alg = {
            .digest = do_digest2,
            .reqsize = 0x8,
        },
    },
};
```
And we can see the commented LOC's right side is a `FunctionAccess`. So in another word, there is a `FunctionAccess` to the `Function` with name "do_digest" in this `Initializer`. This is the source.
For the sink, in the function `test`:
```c
void test(void)
{
    struct a_tfm *tfm;
    struct a_request *areq;
    
    tfm = a_get_tfm(&drivers_alg[0]); // GlobalVariable access
    areq = (struct a_request *)malloc( sizeof(struct a_request) + sizeof(struct a_ctx) );
    a_do_op(areq, tfm->digest); // sink()

    return;
}
```
We can see that `tfm->digest` is a VariableAccess whose type is `FunctionPointerType`.So I want to build the flow from `drivers_alg` to  `tfm->digest`.

**Comment by iiins0mn1a** [comment]
Hi, @jketema  Did I misunderstand you? If so, plz offer me a little more description, and I will provide more infomation.

**Comment by iiins0mn1a** [comment]
Hi again, @jketema ~ One more question. 

As you can see in my original query. Instead of restricting `Source/Sink` in the `Configuration`, I chose to restricting them outside(place before using dataflow, like `fpFromDataFlowFunctionAccess`).

Is there any difference?

**Comment by iiins0mn1a** [comment]
Sorry for disturbing, but another question....
```ql
  /**
   * Gets a data flow configuration feature to add restrictions to the set of
   * valid flow paths.
   *
   * - `FeatureHasSourceCallContext`:
   *    Assume that sources have some existing call context to disallow
   *    conflicting return-flow directly following the source.
   * - `FeatureHasSinkCallContext`:
   *    Assume that sinks have some existing call context to disallow
   *    conflicting argument-to-parameter flow directly preceding the sink.
   * - `FeatureEqualSourceSinkCallContext`:
   *    Implies both of the above and additionally ensures that the entire flow
   *    path preserves the call context.
   */
  FlowFeature getAFeature() { none() }
```
It looks like useful for my funciton poineter tracing? While my `sink()`s have a context in most situations.

I can not find any blog or content about `FlowFeature`, and due to my knowledge limitation, I can not understand `FlowFeature` in `.qll` comprehensively. Maybe you guys could offer me some tips?

Again, sorry for disturbing. But I think our conversation is valuable and is technically practical, which can make contributations to the community construction.

Maybe this `FlowFeature getAFeature()` should be documented officially?

**Comment by jketema** [comment]
> Did I misunderstand you? If so, plz offer me a little more description, and I will provide more infomation.

Apologies for not being able to answer earlier. No, you did not misunderstand me, thanks for pointing out where the function pointer is located in the global variable example. I'll try to have a closer look later today.

> As you can see in my original query. Instead of restricting Source/Sink in the Configuration, I chose to restricting them outside(place before using dataflow, like fpFromDataFlowFunctionAccess).

> Is there any difference?

Yes, there's a difference, because CodeQL roughly evaluates queries in a bottom-up fashion, so the way you wrote your query, it will first compute all flow before applying the restrictions.

> It looks like useful for my funciton poineter tracing? While my sink()s have a context in most situations.

This restricts flow in certain cases, and is not related to function pointers. You probably do not want to use this unless you notice unexpected flow due to the situations described in the documentation string of `getAFeature`.

> Maybe this FlowFeature getAFeature() should be documented officially?

I'll pass this along internally. You're not the first person asking.

**Comment by iiins0mn1a** [comment]
@jketema  Sincerely thanks for your kindness. My query runs way more better now~

**Comment by jketema** [comment]
>  I'll try to have a closer look later today.

I'm seeing the same problem with global variables. I will check internally to see if someone knows what is going on here.

**Comment by iiins0mn1a** [comment]
> As a workaround you might try using the IR-based dataflow library by using `import semmle.code.cpp.ir.dataflow.DataFlow` instead of `import semmle.code.cpp.dataflow.DataFlow`. However, that library has its own limitations, and is also going to be replaced by the work I mentioned above.

Thanks for your suggestion. And I'm looking forward to the replacement, best wishes!

**Comment by jketema** [comment]
I'm closing this as completed. Feel free to re-open if there are any remaining issue here, or feel free to open a new issue. The latest dataflow work can be found here: https://github.com/github/codeql/pull/10817 Note that this is not yet quite ready for production.

**Comment by iiins0mn1a** [comment]
Hi there @jketema , I am trying the new dataflow analysis with:
```ql
import semmle.code.cpp.dataflow.new.TaintTracking
```
Again, about the globally tracing of function pointer issue, `FunctionAccess` inside a `Initializer` can not flow outside. I can only launch another dataflow analysis for global variable access as a work around like I did before, which has been showed above in our conversation.

Then, is there any suggestion for my tracing funciton pointer T-T

I noticed that `ResolveCall.qll` in `.../ir/dataflow/` folder may help, but unfortunately it's local...

**Comment by jketema** [comment]
Hi @iiins0mn1a,

I believe this in not an issue with initialisation of global variables as is, but the designated initialisers being used in your example. There's definitely things we're not doing correctly there at the moment. I'll mention your issue in the internal ticket we have for tracking this.

**Comment by iiins0mn1a** [comment]
Thanks for your reply~

> I believe this in not an issue with initialisation of global variables as is, but the designated initialisers being used in your example. 

It's constructive, and I will try other examples about global variable.

**Comment by jketema** [comment]
Hi @iiins0mn1a,

We've fixed some issues related to designated initialisers. This should ship with CodeQL 2.13.0, which will be released in a few weeks time. If you still experience issues with that version of CodeQL, please open a new issue.

**Comment by iiins0mn1a** [comment]
hi @jketema, thanks for your effort, sorry for not checking email in time, i will try it recently. Again, i'm really appreciate.
