### ISSUE TITLE
How to setting the extractor jvm options?

### ISSUE THREAD

**Issue by yinhediyi** [github/codeql#12255]
When I was auditing an internal project(Java), the extractor reported a Java heap space error
![error1](https://user-images.githubusercontent.com/17943388/219956282-771ce3dc-f127-4315-a00c-54e4324a02cc.PNG)
how can i solve this problem
thanks a lot

**Comment by intrigus-lgtm** [comment]
What command did you use for database creation?
Can you try running it with `-J -Xmx4096M`?
If that still doesn't work, have a look at https://github.com/github/codeql/issues/5292#issuecomment-787483542.

Hope this helps.

**Comment by yinhediyi** [comment]
> What command did you use for database creation? Can you try running it with `-J -Xmx4096M`? If that still doesn't work, have a look at [#5292 (comment)](https://github.com/github/codeql/issues/5292#issuecomment-787483542).
> 
> Hope this helps.

export SEMMLE_JAVA_EXTRACTOR_JVM_ARGS='-Xmx4g -Xms512m' is no problem

**Comment by smowton** [comment]
Thanks @intrigus-lgtm for saving our support team some work :D
