### ISSUE TITLE
cs/static-field-written-by-instance false positive

### ISSUE THREAD

**Issue by sungam3r** [github/codeql#12328]
https://github.com/PublicApiGenerator/PublicApiGenerator/security/code-scanning/30
![изображение](https://user-images.githubusercontent.com/21261007/221627282-c4731f3c-4d96-43a3-841f-d7194340c7b2.png)

But this property is static, see https://github.com/PublicApiGenerator/PublicApiGenerator/blob/master/src/PublicApiGenerator/NullableContext.cs

**Comment by michaelnebel** [comment]
This will be fixed here: https://github.com/github/codeql/pull/12334

**Comment by sungam3r** [comment]
Thanks.
