### ISSUE TITLE
How to decode .rel files?

### ISSUE THREAD

**Issue by Sissel-Wu** [github/codeql#12406]
Dear CodeQL maintainers,

I'm researching with CodeQL and want to get the basic relations (extensional tables). After hours of documents reading, I find the [DB schema for Java](https://github.com/github/codeql/blob/main/java/ql/lib/config/semmlecode.dbscheme). Also, I think the .rel files in the compiled database (e.g., `codeql_db/db-java/default/arrays.rel`) are what I need because their names align with the relation names in the schema.

However, the .rel files look file binary files and need some decodings. I spent some more time looking for documents for .rel files, but could hardly find any. Could you hint on how to parse these files, or at least tell me where the codes for handling .rel files locate? I sincerely appreciate your help.

**Comment by tausbn** [comment]
Thank you for your question!

The format of `.rel` files is an internal implementation detail, and is therefore not documented (or intended to be decoded by anything other than the CodeQL binaries).

If you want to extract all of the (extensional) data from a database, I would suggest writing queries to extract all of the relations that are defined in the DB scheme. 

Assuming one such query is `$QUERY.ql`, you can then get a CSV version of the relation using the following CLI commands:
```
codeql query run --output=$QUERY.bqrs --database '/path/to/db' $QUERY.ql

codeql bqrs decode --entities=id --format=csv --no-titles -o $QUERY.csv $QUERY.bqrs

**Comment by Sissel-Wu** [comment]
Thank you for your reply! Following your suggestion, do I need to write a query for each relation defined in the DB schema? I am also not sure whether all the relations/columns can be queried. For example, the id-type values seem unavailable via the CodeQL queries.

Is the implementation of the `.rel` files open-sourced? If so, maybe I can read the codes although they are not documented.

**Comment by Sissel-Wu** [comment]
Thanks a lot for the information! It is really helpful. Have a good day.
