### ISSUE TITLE
Code scanning could use a filter by language option

### ISSUE THREAD

**Issue by ryao** [github/codeql#12411]
It would be useful if code scanning had a filter by language option. I am not sure where would be a better place to file this than here, so I am filing it here.

**Comment by tausbn** [comment]
This is already on the roadmap: https://github.com/github/roadmap/issues/662 🙂

**Comment by ryao** [comment]
@tausbn I see that I was late in filing this. I had meant to file this and other reports months ago, but ENOTIME kept me from filing it until today. Thanks for letting me know that it is already planned. :)
