### ISSUE TITLE
cpp/world-writable-file-creation gives incorrect example code

### ISSUE THREAD

**Issue by ryao** [github/codeql#12414]
**Description of the issue**

https://github.com/ryao/zfs/security/code-scanning/851

We are given this example code:

```
int write_default_config_bad() {
	// BAD - this is world-writable so any user can overwrite the config
	FILE* out = creat(OUTFILE, 0666);
	fprintf(out, DEFAULT_CONFIG);
}

int write_default_config_good() {
	// GOOD - this allows only the current user to modify the file
	FILE* out = creat(OUTFILE, S_IWUSR | S_IRUSR);
	fprintf(out, DEFAULT_CONFIG);
}
```

However, `creat()` returns an int file descriptor, not a `FILE*`:

https://www.man7.org/linux/man-pages/man3/creat.3p.html

That makes the example code wrong.

**Comment by redsun82** [comment]
@ryao thanks for this report! Another problem with the example code snippets was that the functions are marked returning `int` but have no return. All issues should be fixed by https://github.com/github/codeql/pull/12426 :slightly_smiling_face:
