### ISSUE TITLE
js/ false positive command execution when the argument is a template literal

### ISSUE THREAD

**Issue by rb-x** [github/codeql#12502]
When we launch the rule for command injection in a NodeJS project. [CWE-078/CommandInjection.ql](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-078/CommandInjection.ql)
The rule doesn't catch the issue when the argument to the sink is a template literal.

```js
app.get('/test', (req, res) => {
    const { exec } = req.query
    exec(`${exec}`, (err, stdout, stderr) => {
        if (err) {
            console.error(err);
            return;
        }
        return res.send(stdout);
    }
    );
});
```

**Potential fix?**

- option1 : Implement a search when the argument is a template literal referencing a source
- option2 : Search recursively each child node inside a sink to also handle this case, below : 

 ```js
const anothercall = (arg) => {
    return arg;
}

app.get('/test', (req, res) => {
    const { exec } = req.query
    exec(`${anothercall(arg)}`, (err, stdout, stderr) => {
        if (err) {
            console.error(err);
            return;
        }
        return res.send(stdout);
    }
    );
});
```

Thank you

**Comment by asgerf** [comment]
Hi @rb-x, 👋

Thanks for your report.

There's an issue with the example you provided, as the local variable named `exec` shadows any function named `exec` that might be in scope:
```js
    const { exec } = req.query
    exec(`${exec}`, ... // < -- this tries to call req.query.exec as a function, not child_process.exec
```
If that's fixed, and `app` is defined to be an Express router, the analysis should find the vulnerability as expected.

For instance, it works on this example:
```js
const app = require('express')();
const child_process = require('child_process');

app.get('/test', (req, res) => {
    const { exec } = req.query
    child_process.exec(`${exec}`, (err, stdout, stderr) => {
        if (err) {
            console.error(err);
            return;
        }
        return res.send(stdout);
    }
    );
});
```

I understand the example might have been distilled from a larger codebase, and there might still be a false negative in the original codebase. If that's the case, I'd be happy to help resolve the issue if you can provide another example where we can reproduce the error.

**Comment by rb-x** [comment]
Hi @asgerf,

Nice catch, there was indeed a mistake in my code (exec was referring to the imported exec)
After further testing, the query did indeed what was intended.

Thank you very much for your explanation and your time.
