### ISSUE TITLE
Javascript: Support detection of block cipher modes

### ISSUE THREAD

**Issue by natejohnson05** [github/codeql#12545]
**Description of the issue**

As it stands, the JS Cryptography code does not take into account the mode of a block cipher when determining whether it is secure or not. As a result, unsafe modes of secure algorithms can be used, and will not be flagged. For example, AES is a secure algorithm but AES-ECB should not be used. Currently, AES-ECB would not be flagged.

**Proposition**
There should be a change in the underlying code to take into account the mode of a block cipher when determining whether the "algorithm" used is secure.

**Comment by asgerf** [comment]
Thanks for the report @natejohnson05. This was indeed missing from the JS analysis. I've merged a PR that should fix the issue.
