### ISSUE TITLE
C++: BufferAccess shouldn't consider expressions in `sizeof`

### ISSUE THREAD

**Issue by gsingh93** [github/codeql#12576]
I have some code like this:
```c
unsigned long foo() {
  char buf[1];
  return sizeof(buf[0]);
}
```

My understanding is that `buf[0]` is actually not accessing the buffer, `sizeof` will just get the sizeof the type without any memory access. Yet this query still returns it as a result:
```codeql
import cpp
import semmle.code.cpp.security.BufferAccess

from BufferAccess ba
select ba
```

Is this intended? It results in a few false positives in my queries.

**Comment by MathiasVP** [comment]
Hi @gsingh93,

We're still discussing internally whether this is actually intended 😂. But if you want a quick-fix for your own queries you can exclude such cases by adding `not ba.isUnevaluated()` to ensure that the access happens in a context that doesn't cause the expression to remain unevaluated.

**Comment by MathiasVP** [comment]
I've opened a [PR](https://github.com/github/codeql/pull/12611) that excludes these cases from the the `BufferAccess` classes. Thanks for raising this issue!

**Comment by MathiasVP** [comment]
The above PR has been merged. It'll appear in the next CodeQL release which is scheduled to be in about ~2 weeks.
