### ISSUE TITLE
vscode extention javascript/JS "Could not resolve module ..."

### ISSUE THREAD

**Issue by am0o0** [github/codeql#12571]
I'm currently using vscode writing go, python, ruby queries without any problem, but I've faced with the following error message when with JS:
![Screenshot from 2023-03-17 14-36-10](https://user-images.githubusercontent.com/77095239/225922326-421bfb28-5872-43df-b736-2072182ffa3e.png)
I'm using the latest version of codeql on Linux.

**Comment by smowton** [comment]
This happens because the ATM experimental queries use a language model that needs to be installed; without that present, their qlpack resolution fails and so you see resolution failures like this.

To fix, run `codeql pack install` in `ql/javascript/ql/experimental/adaptivethreatmodeling/src`.

**Comment by KingXS** [comment]
How did you solve this problem?

**Comment by smowton** [comment]
@KingXS if your comment relates to https://github.com/github/codeql/issues/13655 then I don't think these are related issues.
