### ISSUE TITLE
[java][Customizations]Question : How to include customizations in codeql bundle

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#12573]
Hello,

As part of making some customizations, we were initially making changes on Customizations.qll and moving it over to java-all, however I noticed recently my customizations aren't getting picked up by java-queries as there is a hidden directory ".codeql" that contains a library folder with old java-all content which is not picking up the Customizations. 

Question : Is there a way to regenerate the .codeql folder safely without copying files manually one by one

**Comment by rvermeulen** [comment]
You indeed need to recreate the CodeQL query pack, because each query pack contains all its dependencies and a compiled version of the query.

Something that can help with that is https://github.com/advanced-security/codeql-bundle-action or https://github.com/rvermeulen/codeql-bundle

**Comment by chmodxxx** [comment]
@rvermeulen  I haven't gotten around using these both tools, something to do with my setup. But essentially I'm trying to recreate the steps manually, after I removed the .codeql folder and all the cached stuff I try to rebundle my custom packs with java-queries but the packing fails . 

I have the following folder structure and when adding the name of my qlpack(1) to qlpack(2) in dependencies block it errors with " pack 'customizations_folder' was not found, version solving failed." , my guess is it requires me to publish the pack before adding it to dependencies however I can't do that because we use an internal GH enterprise and we don't necessarily want to publish the qlpacks. Is there any workaround this ? doing something like **codeql pack create --additional-packs=../customizations_folder** doesn't work , as I don't see the customizations injected in .codeql 

root folder : 
 - customizations_folder 
   - qlpack.yml (1)
 - codeql 
   - qlpacks
     - java-queries
       -  qlpack.yml  (2)
     - java-all

**Comment by rvermeulen** [comment]
To manually perform the steps you have to do the following:

1. Remove the `.cache` and `.codeql` directories in `java-queries`.
2. Remove the precompiled queries in `java-queries` with `find codeql/qlpacks/java-queries -name '*.qlx' --delete`
3. Change the dependency version of the `codeql/java-all` to `*` in `codeql/qlpacks/java-queries/qlpack.yml` to resolve it locally.
4. Add your changes to the `codeql/qlpacks/java-all` `Customizations.qll` module. If this is an import from another CodeQL library pack make sure to add the dependency to `java-all` and read below how to prevent a circular dependency.
5. Create a top-level file called `codeql-workspace.yml` (https://docs.github.com/en/code-security/codeql-cli/codeql-cli-reference/about-codeql-workspaces#the-codeql-workspaceyml-file) with the following contents to ensure you can resolve the local packs, you can test it with `codeql pack ls` that should list all the packs:
  
  ```yml
  provide:
    - codeql/qlpacks/java-all/qlpack.yml
    - codeql/qlpacls/java-queries/qlpack.yml
  ```

If you want to put your customizations into a separate pack, then you have to make sure to remove the circular dependency between that customization pack and `java-all` when you re-create any queries relying on the `java-all` that has a dependency on your customizations pack. This is one of the things the mentioned tools do for you.

**Comment by chmodxxx** [comment]
Thank you @rvermeulen and appreciate your patience here, so far all the steps 1 through 5 are done with no issues. 
running `codeql pack ls` in my workspace returns all the packs (including java-all, java-queries, my-customizations) 

however when I try to create the pack inside java-queries folder by running `codeql pack create` there is a returned error : 
```
A fatal error occurred: Could not create access credentials for custom-org/my-customizations.
(eventual cause: SunCertPathBuilderException "unable to find valid certification path to requested target")
``` 

I tried adding `export _JAVA_OPTIONS="-Dcom.sun.security.enableAIAcaIssuers=true"` to my OS to ignore certificates, but it's still doesn't work , for some reason trying to re-create the java-queries qlpack will make it try to resolve the customizations by checking in registries, we currently don't have that setup and I'd like it so when I make my changes on java-all and add my dependency and after running `codeql pack create` it resolves the pack from local files/directories instead of GHES. 

I tried running your python tool using `codeql-bundle -b ./codeql/ -o test.tar.gz -l debug --workspace=./` but it just hangs,  I think I'm using it incorrectly as I don't see examples of folder structure for customizations repacking

**Comment by rvermeulen** [comment]
Make sure to provide the version `"*"` when adding local packs as dependencies to ensure the CLI first resolves packs using your workspace.

The `codeql-bundle` tools works with an existing bundle that you can download from https://github.com/github/codeql-action/releases

There is some additional structure required on the pack that contains the customizations.
Assuming your pack is called `custom-org/my-customizations`, it must be a library CodeQL pack with a dependency on the `codeql/java-all` pack, and must contain a CodeQL module named `Customizations.qll` in the directory `custom_org/my_customizations`.

```
my_customizations
|
|- custom_org
   |
   |- my_customizations
     |
     |- Customizations.qll
|- qlpack.yml
codeql-workspace.yml
```

With the `qlpack.yml` contents being:

```yaml
---
library: false
name: custom-org/my-customizations
version: 0.0.1
dependencies:
  codeql/java-all: 0.5.4
```

With the `codeql-bundle` tool there is no need for the `java-all` and the `java-query` packs in your workspace. 
The output of the tools is a new bundle with your customizations baked in.

Run it as follows `codeql-bundle --bundle codeql-bundle.tar.gz --output codeql-custom-bundle.tar.gz  --log INFO "custom-org/my-customizations"`

**Comment by chmodxxx** [comment]
I'm getting somewhere with the script codeql-bundle, however I'm hitting the case you mentioned, my customizations qlpack depends on another qlpack that is depending on java-all, and it errors out with cyclic dependency error. Is there a way  I can remove the cyclic dependencies here ? 

This is what I have : 

codeql_home_folder:
  - org
    - java_lib
     - qlpack.yml (1)
   - java_customizations
     - qlpack.yml (2)
  - codeql
  - codeql-workspace.yml



qlpack.yml(2): 
---
library: true
name: org/java-lib
version: 0.0.1
dependencies:
  - codeql/java-all: "*"

---------------------------- 

qlpack.yml(1) : 
---
library: true
name: org/java-customizations
version: 0.0.1
dependencies:
  - codeql/java-all: "*"
  - org/java-lib: "0.0.1"

**Comment by chmodxxx** [comment]
Thanks @rvermeulen  I managed to get it working while avoiding circular dependency error by just copying the lib folder on the customizations folder. 
Let me know if there is a cleaner way to do it.
