### ISSUE TITLE
Correct security-scanning setup for Kotlin/JVM project

### ISSUE THREAD

**Issue by PascalHonegger** [github/codeql#12584]
**Description of the issue**

I'm currently developing a project on GitHub as part of my bachelors thesis (https://github.com/samtkit/core) and noticed, that it was forked by GitHub (https://github.com/octodemo/core, btw. I would rename the fork to samt-core).

I've noticed the two commits made to update the security-scanning.yml by @mcantu, I just wanted to ask if these changes should be integrated into our repository.
The diff can be seen here: https://github.com/samtkit/core/compare/main...octodemo:core:main

We only plan on writing Kotlin Code and no Java, but because of the way Kotlin/JVM is tied to Java, the Java rules might still make sense to include?

We are happy to listen to the official guidelines and follow best practices, thanks in advance for helping us improve our security-scanning setup!

**Comment by aibaars** [comment]
That's a good question. As far as I know CodeQL does not consider Kotlin a separate language and treats Kotlin simply as a dialect of Java. So running `java` and `kotlin` analyses in a job matrix would just analyse the same code twice and report duplicate alerts.

**Comment by aibaars** [comment]
The other change, setting `queries: security-and-quality` is something you could consider. There are three standard sets of queries `code-scanning`, `security-extended` and `security-and-quality`. The `code-scanning` set is the smallest, and only contains queries for the most important security related issues,`security-and-quality` is the largest set and contains "quality" related checks in addition to security related ones. It's up to you to decide which set matches your use-case.

In general I'd recommend turning on the next "level" of queries if you have very few alerts. For example if you have hundreds of security related problems, then it is probably best to address these first, before adding bucket loads of quality related alerts. That makes it easier to focus on the important things first.

**Comment by PascalHonegger** [comment]
Hi @mcantu, don't worry you didn't cause any confusion, we were honored to be forked by a GitHub employee 😉
If you have any new and shiny GitHub / Kotlin integration you want to try out, we're happy to help.

Thanks @aibaars for the explanations, we've switched to `queries: security-and-quality` scanning in https://github.com/samtkit/core/pull/7 and saw no new alerts, thanks for the quick and details response 👍
