### ISSUE TITLE
C++: Add `getSizeExpr` to `BufferAccess`

### ISSUE THREAD

**Issue by gsingh93** [github/codeql#12597]
`BufferAccess` is a useful class to abstract across different types of buffer accesses, i.e. calls to `memcpy`, array indexing, etc. However, there is no generic way to access the expression corresponding to the access size. There is an `int getSize()` predicate, but will only return the access size if it's a constant. For example, here is the implementation for `MemcpyBA`:
```ql
  override int getSize() {
    result =
      this.(FunctionCall).getArgument(2).getValue().toInt() *
        getPointedSize(this.(FunctionCall).getTarget().getParameter(0).getType())
  }
```
Calling `this.(FunctionCall).getArgument(2).getValue().toInt()` will result in any non-constant size argument to `memcpy` being filtered out of the results.

In my case, I'd like to get the `Expr` corresponding to this size, even if the value of this expression  isn't constant. Would it make sense to add an `Expr getSizeExpr()` predicate to the `BufferAccess` class? If so, I'd be happy to make the PR for it.

**Comment by MathiasVP** [comment]
I think that sounds like a great addition 👍. I think the naming is fine as well. I'll be happy to review such a PR 🙇.
