### ISSUE TITLE
JavaScript DataFlow: Unable to trace function calls in objects

### ISSUE THREAD

**Issue by ttttmr** [github/codeql#12627]
```js
function foo() {
  window.Port = {
    send: function (msg) {
      sink(msg);
    },
  };

  Port.send(window.source);
}
foo()
```

```ql
class Config extends DataFlow::Configuration {
    Config() { this = "Config" }

    override predicate isSource(DataFlow::Node source) {
        source = DataFlow::globalVarRef("source")
    }
    
    override predicate isSink(DataFlow::Node sink) {
        exists(DataFlow::CallNode call |
            call.getACallee().getName() = "sink" and
            call.getArgument(0) = sink
        )
    }
}
```

I found something that seems similar to #2567, but not quite the same

**Comment by erik-krogh** [comment]
Could you try `getCalleeName()` instead of `getACallee().getName()`?

**Comment by aibaars** [comment]
If I change the code to
```
function foo() {
  let Port = {
    send: function (msg) {
      sink(msg);
    },
  };

  Port.send(window.source);
}
foo()
```
then the query find a flow path. So it looks like CodeQL is able to trace function calls in objects. I hope that answers your question.

However, for some reason things don't work when adding a field to the `window` object. We'll investigate further.

**Comment by erik-krogh** [comment]
I found a problem in our libraries, and I think I got a fix here: https://github.com/github/codeql/pull/12633 

Our access-path library would find an assignment to `window.Port` but a read from `Port`, and it was therefore unable to match the two.

**Comment by ttttmr** [comment]
@erik-krogh Well done. Is there any way for me to test and verify this fix?

I still have a question, if I change the code like this, will the fix still work?

```js
function foo() {
  Port = {
    send: function (msg) {
      sink(msg);
    },
  };

  Port.send(window.source);
}
foo()
```
Or not encapsulated in a function.
```js
Port = {
  send: function (msg) {
    sink(msg);
  },
};

Port.send(window.source);
```
Even split into two files.
```js
// lib.js
Port = {
  send: function (msg) {
    sink(msg);
  },
};
```
```js
// main.js
Port.send(window.source);
```

**Comment by erik-krogh** [comment]
> I still have a question, if I change the code like this, will the fix still work?

I checked the two files example, and yes that still works.  

That assumes that there isn't another file that also writes to the global variable `Port`.
