### ISSUE TITLE
Could not find qlpack file for dbscheme

### ISSUE THREAD

**Issue by NicolasArmero** [github/codeql#12697]
I am trying to run the examples that can be found on the documentation (for example https://codeql.github.com/docs/codeql-language-guides/basic-query-for-javascript-code/), but when I try to run the basic query command I get the following error:
`Could not find qlpack file for dbscheme C:/Users/nicol/AppData/Roaming/Code/User/workspaceStorage/65ced8da6b900dda4c49f1ae71a1a5e5/GitHub.vscode-codeql/javascript-4/codeql_db/db-javascript/semmlecode.javascript.dbscheme (codeQL.quickQuery)` 

I have tried installing the extension by the three possible ways and in Windows and in Ubuntu, but the result is the same.
I have also tried different databases from different projects and from different languages.

One thing I saw is that after installing the extension it did not automatically installed the Cli, however, after I run the Cli update command it correctly installed.

Here are the URL of the projects I tried:
https://github.com/ajaxorg/ace
https://github.com/protocolbuffers/protobuf
https://github.com/saltstack/salt

I haven't found any solutions on the internet or in other issues, so any help would be appreciated.

Thank you for your time.

**Comment by aeisenberg** [comment]
It's likely that you haven't set up the codeql core libraries properly. The CLI is unable to find the codeql javascript library dependencies. Please read the [setup instructions for vscode](https://codeql.github.com/docs/codeql-for-visual-studio-code/setting-up-codeql-in-visual-studio-code/) and let me know if that helps.

**Comment by WhatTheFuzz** [comment]
@NicolasArmero I'm a fellow CodeQL-er in training. I've found this can happen specifically when you have created your qlpack with `codeql pack init` but not installed it with `codeql pack install`. Make sure to add the Javascript dependency!

**Comment by NicolasArmero** [comment]
Fixed, thank you very much for your help.
