### ISSUE TITLE
False negatives: arithmetic tainted for c++

### ISSUE THREAD

**Issue by LostBenjamin** [github/codeql#12770]
For the following three programs, [This query](https://github.com/github/codeql/blob/b5147bbfb0aa30a5fc6c6ba73eb4927bebd26c63/cpp/ql/src/Security/CWE/CWE-190/ArithmeticTainted.ql) produces alert for `program_1` only. I think the other two cases are false negatives.

`program_1`:
```
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv) {
    char buffer[20];
    fgets(buffer, 20, stdin);

    int num = atoi(buffer);
    num = num + 1000;
}
```

`program_2`:
```
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv) {
    char buffer[20];
    fgets(buffer, 20, stdin);

    int num = atoi(buffer);
    num += 1000;
}
```

`program_3`:
```
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv) {
    char buffer[20];
    fgets(buffer, 20, stdin);

    int num = atoi(buffer);
    int a = 99999999;
    a += num;
}
```

`Makefile`:
```
SRCS=$(wildcard *.c)
OBJS=$(SRCS:.c=.o)

all: $(OBJS)

%.o: %.c
	gcc -c $< -o $@
```

**Comment by MathiasVP** [comment]
Hi @LostBenjamin,

Thanks for raising this issue. I've opened a PR with a fix here: https://github.com/github/codeql/pull/12779

**Comment by LostBenjamin** [comment]
Thank you @MathiasVP !
