### ISSUE TITLE
csharp Attribute.getNamedArgument doesn't work for parameters 

### ISSUE THREAD

**Issue by chanel-y** [github/codeql#12809]
Hi all, 

I've got a query: 

```
from Attribute a
select a.getNamedArgument("bar")
```

that I'm running on: 

```
public class MyAttribute1 : Attribute
{
	public MyAttribute1(bool bar){
		...
	} 
}

[MyAttribute1(bar: someVal)]
public class MyClass1{}

public class MyAttribute2 : Attribute
{
    bool bar; 
	public MyAttribute2(){
		...
	} 
}

[MyAttribute2(bar=someVal)]
public class MyClass2{}

```

CodeQL only recognizes MyAttribute2's bar as a named argument - is this a bug?

**Comment by jketema** [comment]
The `Attribute` QL class recognises both named attributes and constructor attributes. In the case of your `MyAttribute1` attribute, you should use `getConstructorArgument(0)` to get the value of `bar`. Note that the index (`0` here)  will exactly match the index of the relevant argument of the constructor. So, suppose for example we had:
```csharp
public class MyAttribute3 : Attribute
{
	public MyAttribute3(bool foo, int bar) {
		...
	} 
}

[MyAttribute1(bar: 42, foo: true)]
public class MyClass1{}
```
and the query:
```codeql
import csharp

from Attribute a, int i, Expr e
where e = a.getConstructorArgument(i) and exists(e.getFile().getRelativePath())
select i, e.getValue()
```
then is query yields
```
| 0 | test.cs:11:28:11:31 | true |
| 1 | test.cs:11:19:11:20 | 42 |
```
among other values.

**Comment by jketema** [comment]
Confirmed on the GitHub security lab slack that the above indeed solves the problem.
