### ISSUE TITLE
 Missing  code file generated database using codeql

### ISSUE THREAD

**Issue by kingcarzy** [github/codeql#12827]
project language: java springboot
when I use  command： codeql database create D:\--\--\--_db  --language="java"  --command="mvn clean compile --file pom.xml -Dmaven.test.skip=true" --source-root=D:\--\---\--\---web
Command executed successfully with no errors，but when i use vscode to open the database and check the code file , a lot of java controller file missing.

As shown in the following figure:
![image](https://github.com/github/codeql/assets/53007334/d0a1b21c-793b-4ecf-ba51-19e6c9d6c3de)

On the left is the source code directory, and on the right is the code directory in the generated database。In the database，the directory of user only has one file and has no the controller, but in the source project, it has many files . And this is common in another directory.
so this problem is normal? How to solve it?

**Comment by jketema** [comment]
Note that CodeQL only picks up on files that are actually compiled, were the missing files actually compiled while running `mvn clean compile --file pom.xml -Dmaven.test.skip=true`?

**Comment by kingcarzy** [comment]
![image](https://github.com/github/codeql/assets/53007334/d13a86fe-d607-4e65-9bd4-455dc13f55dd)

**Comment by kingcarzy** [comment]
Can I generate a database without compiling it

**Comment by jketema** [comment]
> Can I generate a database without compiling it

No, not for a compiled language like Java.

**Comment by kingcarzy** [comment]
> confirm this directory files are compiled

![image](https://github.com/github/codeql/assets/53007334/62bdf7a5-5293-40df-a5be-c9ca9e4ded46)

**Comment by jketema** [comment]
Does your project happen to use Lombok?

**Comment by smowton** [comment]
Also, are you able to share the logs stored in `----_db/log`?

**Comment by kingcarzy** [comment]
> Does your project happen to use Lombok?

yes, we use @Getter and @Setter  in  the code of java entity, 
<img width="569" alt="image" src="https://github.com/github/codeql/assets/53007334/20a64ffb-d303-41c3-84e6-985f5e8eab11">

**Comment by kingcarzy** [comment]
> Also, are you able to share the logs stored in `----_db/log`?

log of the project database which the codeql creates ?

**Comment by kingcarzy** [comment]
> If you're using Lombok, please try de-lombok'ing your source before extraction, as described at #4984

thanks,Your reply made me aware of the problem,issue closed
