### ISSUE TITLE
Try to replicate the documentation test custom query setup gives several errors

### ISSUE THREAD

**Issue by giper45** [github/codeql#12920]
I am trying to replicate the steps present in the following guide: 
https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/testing-custom-queries

I have uploaded my experiments in the following repo: 
https://github.com/giper45/example-codeql-query

However, I was not able to let the project properly works after several trials. 
* Test 1: run `codeql test run java/tests/EmptyThen` :  
``` 
ERROR: Referenced pack 'giper45/my-custom-queries' was not found locally, and no lock file is present for 'giper45/my-query-tests'. 
Run 'codeql pack install' to create the lock file and download the dependencies. (.../custom-queries/java/tests/qlpack.yml:1,1-1)

```
*    Try to run `codeql pack install` in the `java/queries/qlpack.yml` folder, it returns the same error.  
*  Try to run the ''suggestion'' of the documentation, with the `search-path` flag: 
 
``` 
codeql test run --search-path=java java/tests/EmptyThen
ERROR: Referenced pack 'giper45/my-custom-queries' was not found locally, and no lock file is present for 'giper45/my-query-tests'. Run 'codeql pack install' to create the lock file and download the dependencies. 
(.../example-codeql-query/custom-queries/java/tests/qlpack.yml:1,1-1)
ERROR: The --search-path option was ignored when resolving dependencies for pack 'giper45/my-query-tests'. This option is required only for finding extractors, or legacy pack dependencies specified using the `libraryPathDependencies` property. 
To search for dependencies in additional directories, consider using the --additional-packs option instead. (.../java/tests/qlpack.yml:1,1-1)
```     

* Try to follow the suggestion of the error, the same error occur. 

Operating System: `macOS Ventura ARM`. 
Is it related to my operating system? 
May you kindly help me to make this work? 

I am following the precise information described in the documentation, but I think that several things should be detailed better:  
1. If the `qlpack.yml` of the `queries` folder contains the name `my-custom-queries`, how is it possible that the `qlpack.yml` of the `tests` folders references a `my-github-user/my-custom-queries` name? Should not the first name be `my-github-user/my-custom-queries` ? 
2. If you do not put a `version` tag in the `qlpack.yml` (that I think it should be required), how can the test `qlpack.yml` have a reference with a version that is between `1.2.3` and `2.0.0.`? 
3. If you suggest to follow the `codeql` official repo to follow a template structure of a test, that is composed of `src` and `test` folders, and you state that a `test` folder is required to perform tests, why the proposed structure in the example is completely different (`custom-queries/java/queries` and `custom-queries/java/tests`)?. 

Finally, a `template` repo example could be very useful to create a custom `qlpack` with test, if it does not exist. I think that would fundamental to start writing `codeql` queries, without wasting a lot of time into a first setup configuration. 

Thank you for your attention.

**Comment by hmakholm** [comment]
At https://github.com/giper45/example-codeql-query/blob/9f8b70451f7f3c11052e4d4c95a91fdd4a62b313/custom-queries/java/tests/qlpack.yml#L3 you declare a dependency on a pack called `giper45/my-custom-queries`, but https://github.com/giper45/example-codeql-query/blob/9f8b70451f7f3c11052e4d4c95a91fdd4a62b313/custom-queries/java/queries/qlpack.yml#L1 declares a package named `my-custom-queries`.

The username-slash prefix is part of the pack, name, so it needs to be part of what the target pack self-identifies as.

Once you get past that, though, I suspect `codeql test run` will still not find the queries pack. You'll need _either_ to point `codeql` at the directory containing the query pack using an `--additional-packs` option, _or_ to have a `codeql-workspace.yml` in a common ancestor directory of the test and queries packs. Its content can be as simple as:
```
provide:
  - "**/qlpack.yml"
```
(See https://docs.github.com/en/code-security/codeql-cli/codeql-cli-reference/about-codeql-workspaces)

Packs that are found under the same workspace (or via `--additional-packs`) are not actually checked for a version match. (The rationale for this is an assumption that they are part of the same source-control tree, so the user takes responsibility for having the code you want to run _in_ that tree).

Your points about the documentation being somewhat misleading or at least confusing are well made. I'll start an internal change request to get it made clearer.

**Comment by giper45** [comment]
Hi @hmakholm , thank you for the suggestions.
I fixed the sync through repos, and, with `additional-packs` or with the `codeql-workspace.yml` it gives the following error:
```
ERROR: Referenced pack 'codeql/java-queries' was not found locally, and no lock file is present for 'giper45/my-query-tests'.
```

I have installed the deps with `codeql pack install` in the `queries` folder. 

Any other suggestion? Take a look at the updated code in my repo.

**Comment by aeisenberg** [comment]
Hi, in order to get this running, please do the following:

1. In the `example-codeql-query/custom-queries/java/tests` directory, run `codeql pack install`. This will create a lock file so that the query resolver knows where to find the `codeql/java-all` library. I see you have already done this for the `queries` pack. In general, in order to resolve libraries downloaded to the package cache, you will need a lock file.
2. Change `custom-queries/java/tests/EmptyThen/EmptyThen.qlref` from `EmptyThen` to `EmptyThen.ql`. In order to resolve a qlref, the contents needs to be a path from the root of a resolvable package to the query you are looking for.

Them when you run `gh codeql test run --learn .` in the `example-codeql-query/custom-queries/java/tests`, it will succeed.

After these steps, here are the complete changes:

```
$ git diff HEAD

──────────────────────────────────────────────────────────┐
custom-queries/java/tests/EmptyThen/EmptyThen.expected:1: │
──────────────────────────────────────────────────────────┘
| Test.java:3:6:3:23 | if (...) | This if statement has an empty then. |

───────────────────────────────────────────────────────┐
custom-queries/java/tests/EmptyThen/EmptyThen.qlref:1: │
───────────────────────────────────────────────────────┘
EmptyThen
\ No newline at end of file
EmptyThen.ql

──────────────────────────────────────────────────┐
custom-queries/java/tests/codeql-pack.lock.yml:1: │
──────────────────────────────────────────────────┘
---
lockVersion: 1.0.0
dependencies:
  codeql/java-all:
    version: 0.5.1
  codeql/java-queries:
    version: 0.5.1
  codeql/regex:
    version: 0.0.5
  codeql/suite-helpers:
    version: 0.4.1
  codeql/tutorial:
    version: 0.0.2
  codeql/typetracking:
    version: 0.0.2
  codeql/util:
    version: 0.0.2
compiled: false
```

Hope this helps.

**Comment by giper45** [comment]
Thank you very much @aeisenberg  I have just changed the `qlref`  file and everything works now. 
I suggest to improve the doc in order to fix the misleading information. 
I could send you a `PR` for this.

**Comment by aeisenberg** [comment]
I'll take a look at the docs and see what can be improved. Thanks for raising the issue, @giper45.

**Comment by aeisenberg** [comment]
Closing this issue since we will be handling any docs changes in a separate issue.
