### ISSUE TITLE
Hangs during "Finalizing database"

### ISSUE THREAD

**Issue by sescandor** [github/codeql#12990]
Whenever I build my codeql database, it hangs at "Finalizing database at /project/codeql-database" and never finishes. When I ran: 

```shell
codeql database finalize /project/codeql-database/ -vvv
```

I get the following:

```shell
Writing logs to /project/codeql-database/log/database-finalize-20230502.110357.255.log.
Running TRAP import for CodeQL database at /project/codeql-database...
A fatal error occurred: Error reading array info file: /project/codeql-database/db-cpp/default/idPool/buckets/info
(eventual cause: NoSuchFileException "/project/codeql-database/db-cpp/default/idPool/buckets/info")

``` 

I see that the binary is generated perfectly fine in the _lgtm_build_dir

**Comment by aibaars** [comment]
Could you delete `/project/codeql-database/db-cpp` and try the command again? You can also retry the `codeql database create -vvv` command from scratch (make sure to add `-vvv` for more verbose logging). 

If you can it would be interesting to run `jps` (to get the process IDs) and `jstack` (to get information about what `codeql` process is doing) when the process seems to be "hanging".
