### ISSUE TITLE
Issue with decoding bqrs file to a human readable format

### ISSUE THREAD

**Issue by nikitshahbmc** [github/codeql#13047]
DB is getting created and initialized successfully. I also see .bqrs files getting generated by running queries.
CLI version tried - 2.12.5, 2.13.1
Codeql query package - 0.5.5 0.6.1
Using codeql CLI directly into my build script, instead of Codeql 3000

**Facing Issues with decoding bqrs file to a human readable format**

**Issue 1**: When using 'codeql database analyze' with format=sarif_latest. I see a bunch of metadata from CodeQL at the top of the file, and an empty "results" array at the bottom.
Cmd: codeql database analyze --format=sarif-latest --rerun --output=UninitializedLocal.sarif -- bmc_cpp.db ~/.codeql/packages/codeql/cpp-queries/$QUERY_DIR/Likely\ Bugs/Memory\ Management/UninitializedLocal.ql

**Issue 2**: When using 'codeql database analyze' with format=csv. I see that the bqrs file is generated in the database results folder, but the csv file generated from that .bqrs file is always empty (0KB).
Cmd: codeql database analyze --format=csv --rerun --output=UninitializedLocal.csv -- bmc_cpp.db ~/.codeql/packages/codeql/cpp-queries/$QUERY_DIR/Likely\ Bugs/Memory\ Management/UninitializedLocal.ql

**Issue 3**: When using 'codeql query run' followed by 'codeql bqrs decode' with format=csv. I don't see any filename information in the csv file generated. In this case a csv file is generated with proper data but missing crucial information. Attached csv file for reference.

[UninitializedLocal.csv](https://github.com/github/codeql/files/11402514/UninitializedLocal.csv)

Kindly let me know if any more information is needed.

**Comment by aibaars** [comment]
The `codeql database analyze` command filters out any results that are outside the "source root" folder. Could you check the `sourceLocationPrefix` value in the `bmc_cpp.db/codeql-database.yml` file? Also check the folder hierarchy of  `bmc_cpp.db/src.zip` (or `bmc_cpp.db/src` folder).

Running `codeql bqrs decode --help -vvv` tells me there are some advanced options for the output of the decode command.
```
...
      --entities=<fmt>[,<fmt>...]
                             [Advanced] Control how result columns of entity type are shown. A comma-separated list of the following choices:
                             url: A URL referring to a source location, if the query was compiled to produce such URLs for entitity types.
                             string: A string computed by the toString() method in QL, if the query was compiled to produce such strings for the column.
                             id: The internal ID of the entity, which may not be informative.
                             all: Show columns with all the information the BQRS file provides.
                             All the selected options are shown, if possible.
...
```
The attached CSV file seems to contain only the "toString" values of the selected program elements. Could you try running the `codeql bqrs decode` command with the `--entities=url,string` flag?

**Comment by nikitshahbmc** [comment]
sourceLocationPrefix value points to the correct source i.e. the root location for all the src files (also an argument in 'codeql database init' command). src.zip is under bmc_cp.db

I did try your suggestion for codeql bqrs decode and am able to see the src files and their locations.

Still need support with issue codeql database analyze

**Issue**
Also, I see the issue 1 when running 'codeql database interpret-results' after running 'codeql database run-queries' for .qls file.
This is an alternative to running 'codeql database analyze' but observing same error.

codeql database run-queries -- bmc_cpp.db ~/.codeql/packages/codeql/cpp-queries/0.6.1/codeql-suites/cpp-code-scanning.qls

**Comment by aibaars** [comment]
Could you run `unzip -l` on `bmc_cp.db/src.zip` to print a list of the analysed files. Do any of the file paths in that list start with the sourceLocationPrefix?

Could you post some examples of file paths reported by `codeql bqrs decode`? Do these paths match the sourceLocationPrefix?

**Comment by nikitshahbmc** [comment]
1. Could you run unzip -l on bmc_cp.db/src.zip to print a list of the analysed files. Do any of the file paths in that list start with the sourceLocationPrefix? - Yes
.yml file has sourceLocationPrefix: /C2789/workspace_C2789
Snippet of unzip -l on bmc_cp.db/src.zip: 
52814  2023-05-08 15:22  /Build/kernel/linux/fs/read_write.c


2. Could you post some examples of file paths reported by codeql bqrs decode? Do these paths match the sourceLocationPrefix? - Yes it matches the sourceLocationPrefix
Examples of file paths from the csv file:

/Build/kernel/linux/fs/read_write.c:1060:20:1060:22
/Build/kernel/linux/fs/read_write.c:1036:20:1036:22
/Build/kernel/linux/fs/read_write.c:613:20:613:22
/Build/kernel/linux/fs/read_write.c:589:20:589:22

**Comment by aibaars** [comment]
The path `/Build/kernel/linux/fs/read_write.c` does not start with `/C2789/workspace_C2789` so any results found in that file will be dropped by `codeql database analyze` and `codeql database interpret-results`.

**Comment by nikitshahbmc** [comment]
My bad, I wasn't able to copy full path earlier. Have edited my previous comment with the full path. Kindly check and let me know.

**Comment by aibaars** [comment]
`/home/nikitshah/CodeSpace/Gen9/C2789/workspace_C2789/Build/kernel/linux/fs/read_write.c` contains the sourceLocationPrefix (`/C2789/workspace_C2789`) but does not start with it. As a quick experiment, could you edit `bmc_cpp.db/codeql-database.yml` and set the `sourceLocationPrefix` to `/home/nikitshah/CodeSpace/Gen9/C2789/workspace_C2789` and run `codeql database analyze` again?

**Comment by nikitshahbmc** [comment]
I tried that: sourceLocationPrefix: /home/nikitshah/CodeSpace/Gen9/C2789/workspace_C2789
I see the same result with codeql database analyze

**Comment by aibaars** [comment]
Could you attach the `bqrs` file and the to this issue, so I can have a look?

**Comment by nikitshahbmc** [comment]
Not able to attach bqrs file as the file type is not supported here.

**Comment by aibaars** [comment]
> Not able to attach bqrs file as the file type is not supported here.

Ah sorry about that. Could you try to making a zip file containing the bqrs file and attaching that? Or perhaps `base64` encode (or any other binary to text conversion) the file as text ?

**Comment by nikitshahbmc** [comment]
Attached zip for your reference.
[UninitializedLocal.zip](https://github.com/github/codeql/files/11444317/UninitializedLocal.zip)

**Comment by aibaars** [comment]
Thanks, 

The following command should give you SARIF output (you can also switch to csv format if you like). However, the location URLs are not made relative wrt to the source root, so it is not suitable for upload to GitHub's CodeScanning.
```
codeql bqrs interpret UninitializedLocal.bqrs --format=sarifv2.1.0 --output=/tmp/out.sarif -t=kind=problem -t=id=cpp/uninitialized-local
```

Adding the `--source-location-prefix` and `--source-archive` flags tells `codeql bqrs interpret` to make URLs relative and validate locations. If you add the `-vvv` verbosity flag then the command should inform you if and why locations are skipped. 

```
codeql bqrs interpret UninitializedLocal.bqrs --format=sarifv2.1.0 --output=/tmp/out.sarif -t=kind=problem -t=id=cpp/uninitialized-local  --source-location-prefix=/home/nikitshah/CodeSpace/Gen9/C2789/workspace_C2789  --source-archive=bmc_cpp.db/src.zip -vvv
```

The `bqrs interpret` command is quite low level, but `codeql database analyze` command does something similar under the hood so it is a great way to experiment with different settings for the source location prefix.

**Comment by nikitshahbmc** [comment]
Thank you! This definitely works for query and decoding a .ql file. Was wondering how I can do the same for .qls file, without having to use codeql database analyze.

**Comment by aibaars** [comment]
> Thank you! This definitely works for query and decoding a .ql file. Was wondering how I can do the same for .qls file, without having to use codeql database analyze.

Running `codeql database analyze` would be best. Could you try running with `-vvv` to see why it is skipping results? 

You could try running `codeql resolve queries` to resolve a `.qls` file into a list of `.ql` files, run `codeql resolve metadata` and `codeql bqrs interpret` for each of them and merge the resulting CSV or SARIF files into one. This is quite a hassle though, so better find out why `codeql database analyze` is not giving you the answer you need.

**Comment by nikitshahbmc** [comment]
Tried running query : .codeql/packages/codeql/cpp-queries/$QUERY_DIR/Summary/LinesOfCode.ql with -vvv enabled.
![image](https://github.com/github/codeql/assets/128178643/0dc19608-aef5-4576-a7d6-23938e65239e)

**Comment by nikitshahbmc** [comment]
@aibaars checking-in to see if the above logs attached are expected?
Thank you!

**Comment by aibaars** [comment]
Those look fine to me, however, the `LinesOfCode.ql` query is not very interesting. That query computes lines-of-code numbers and does not produce any alerts. Why not try `UninitializedLocal.ql` instead?

**Comment by nikitshahbmc** [comment]
Here are the logs for UninitializedLocal.ql

![image](https://github.com/github/codeql/assets/128178643/2a790fd5-a894-4d75-94bf-fe776b4b2bef)

**Comment by aibaars** [comment]
That looks good too. I don't see any `Skipping location ...` messages though. Is your SARIF output still empty?

**Comment by nikitshahbmc** [comment]
I think the issue is resolved after changing the path and making sure it is getting reflected at sourceLocationPrefix
Thank you so much for the support!
