### ISSUE TITLE
Performance regression while scanning Ruby code

### ISSUE THREAD

**Issue by deivid-rodriguez** [github/codeql#13103]
I noticed that since (I think) CodeQL 2.13.0, our action to analyze Ruby code is taking much longer.

Here's a 3 minutes run using 2.12.6: https://github.com/dependabot/dependabot-core/actions/runs/4768651225/jobs/8478202528.

Vs a 35 minutes run using 2.13.0: https://github.com/dependabot/dependabot-core/actions/runs/4768852196/jobs/8478637429.

After pinning back to https://github.com/github/codeql-action/releases/download/codeql-bundle-20230418/codeql-bundle.tar.gz (bundling 2.12.7) at https://github.com/dependabot/dependabot-core/pull/7275, it's fast again.

Not sure if this could be related to #12349, but that one seems older, so I went with a separate ticket. I also posted a comment at https://github.com/github/codeql/pull/13028, in case the fix could help here.

Thanks!

**Comment by aibaars** [comment]
Thanks for reporting. We're looking into this!

**Comment by deivid-rodriguez** [comment]
I just verified that this is fast again in the latest version, thanks so much for fixing it!
