### ISSUE TITLE
When running the following command with no query pack specified what is the default query pack that gets used?

### ISSUE THREAD

**Issue by Alberto8657** [github/codeql#13123]
When running the following command with no query pack specified what is the default query pack that gets used?

`codeql database analyze <database> --format=<format> --output=<output>`

_Originally posted by @sam-cha-tfs in https://github.com/github/codeql/discussions/13060_
```[tasklist]
### Tasks
```

**Comment by aibaars** [comment]
This is a duplicate issue. Closing.
