### ISSUE TITLE
Using flow labels JavaScript tutorial example queries don't work

### ISSUE THREAD

**Issue by MaxSchlueter** [github/codeql#13175]
Apart from the first example query in that tutorial, the other examples don't work for me. I copied the code in the tutorial to a new file:

```
var data = JSON.parse(str);
if (data.length > 0) { 
  // problematic: `data` may be `null`
}
if (data && data.length > 0) { 
  // unproblematic: `data` is first checked for nullness
}
```

The query with the additional `TruthinessCheck` class still flags the second property access `data.length > 0` for me. The final path query has the same problem.

**Comment by asgerf** [comment]
Hi @MaxSchlueter 👋 

Thanks for bringing this up. The examples don't work if pasted into the top-level of a JavaScript file. They need to be in a function, or the file needs to be a module, so that `data` isn't seen as a global variable.

I've opened a PR to update the examples.

**Comment by MaxSchlueter** [comment]
Ah, alright, that makes sense. The updated examples work for me now. Thanks!
