### ISSUE TITLE
"Finding definitions" in non-ql files

### ISSUE THREAD

**Issue by amammad** [github/codeql#13254]
in CodeQL VScode extension (linux), when I click or just hold Ctrl key on part of  the source code of imported DB (src.zip), then codeql will try to resolve the definitions of non-ql files. the problem is that, it takes a lot of time and resources to resolve the files that are not codeql query files.
![image](https://github.com/github/codeql/assets/77095239/67990e2e-5e90-4261-8beb-9608d580f127)
for reproducing this, I figured out that if you hold Ctrl and point the mouse cursor on these files then you can see the notification on above screenshot.

**Comment by MathiasVP** [comment]
Hi amammad,
Thanks for raising this issue!

I've responded to the [other version](https://github.com/github/vscode-codeql/issues/2572) in the `vscode-codeql` repo, and I'll close this one to avoid duplication 🙂.
