### ISSUE TITLE
False positive - regex injection in Angular $location.search 

### ISSUE THREAD

**Issue by hiteshb-asurion** [github/codeql#13279]
**Description of the false positive**

CodeQL incorrectly detects AngularJS framework functions to be JavaScript because the naming is same for **location.search**

The data being set by code in the Angular $location.search is identified as "regex injection for regular javascript code".

CQL issue message:

```This regular expression is constructed from a user provided value.```

Ref:
1) https://angular.io/api/common/Location
2) https://developer.mozilla.org/en-US/docs/Web/API/Location/search

**Code samples or links to source code**
```JS
function () {
    //get the search params
    //cql source
    $scope.pageLocation = $location.search();

    //manipulate search params
    $scope.pageLocation.to = $scope.selected_date_before = $scope.selectedRange.to.format('YYYY-MM-DD');
    $scope.pageLocation.from = $scope.selected_date_after = $scope.selectedRange.from.format('YYYY-MM-DD');
    
    //set it back
    //cql sink
    $location.search($scope.pageLocation);
};
```
CodeQL Rule

```js/regex-injection```

App Env: package.json

``` "angular": "~1.8.2" ```

**Comment by jketema** [comment]
Hi @hiteshb-asurion Thanks for your report. I've relayed your report to the responsible team. They should get back to you soon.
