### ISSUE TITLE
Support new React directives

### ISSUE THREAD

**Issue by ntkoopman** [github/codeql#13296]
React server components use the directive `use client` and `use server` to detect if code should run on the server or in the browser. These directives currently produces a warning in CodeQL.

`use client` spec: https://github.com/reactjs/rfcs/blob/main/text/0227-server-module-conventions.md
`use server` is still alpha: https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions

https://github.com/vercel/next.js/blob/cf9591cd2346ca69e96da6e03994573ec9b24050/examples/with-turbopack/app/ssg/random-post-tab.tsx#L1
https://github.com/vercel/next.js/blob/cf9591cd2346ca69e96da6e03994573ec9b24050/test/e2e/app-dir/actions/app/header/actions.ts#L1

**URL to the alert on GitHub code scanning (optional)**

**Comment by jketema** [comment]
Hi @ntkoopman. Thanks for this. I've relayed this to the responsible team.

**Comment by ntkoopman** [comment]
Any update on this?

**Comment by jketema** [comment]
@asgerf ?

**Comment by BasVerlooy** [comment]
any update on this as we're receiving quite a lot of false positives?

**Comment by neo-elgiz-abbasov** [comment]
Any updates 👁️

**Comment by asgerf** [comment]
Sorry for the long delay. The fix PR has been merged. Effects should be visible in code scanning in 2-3 weeks.
