### ISSUE TITLE
Analyzing Java code - getExtension() doesn't work

### ISSUE THREAD

**Issue by yuval-piiano** [github/codeql#13321]
Looking at the definition:

```
string getExtension() {
    result = this.getAbsolutePath().regexpCapture(".*/([^/]*?)(\\.([^.]*))?", 3)
  }
```
seems like the . in [^.] should be escaped: 

```
 import java
 from Method r 
 select r, r.getFile().getAbsolutePath(),
  r.getFile().getAbsolutePath().regexpCapture(".*/([^/]*?)(\\.([^.]*))?", 3)
```
Doesn't return anything while this - 
```

 import java
 from Method r 
 select r, r.getFile().getAbsolutePath(),
  r.getFile().getAbsolutePath().regexpCapture(".*/([^/]*?)(\\.([^\\.]*))?", 3)

```

returns the expected extensions

**Comment by alexet** [comment]
In general you shouldn't need to  escape `.` in a character class. The regexes follow java regex syntax which explicitly notes that `.` loses it special meaning in a character class. Running the above queries gives me identical results.

**Comment by yuval-piiano** [comment]
The issue was a corrupted cache, after clearing the cache both versions worked
