### ISSUE TITLE
Why Class.getAField().getDeclaringType() return the Class

### ISSUE THREAD

**Issue by struce2** [github/codeql#13363]
class define 
```java
package org.example;

public class User {
    public String name;
}

```

query

`from Class c where  c.getName() = "User"  select c.getAField().getDeclaringType()`

the return result is `User`

expect is `java.lang.String`

why return `User`?

and how to get Field declare type ?

when use `from Class c where  c.getName() = "User"  select c.getAField().getType().getName()` , return String, but i expect get `java.lang.String`

**Comment by smowton** [comment]
`Field.getDeclaringType()` means "what type declares this field"? In this case `User` declares a field `public String name;`

If you want the type of the field itself, you want just `c.getAField().getType()`.

**Comment by smowton** [comment]
`Type` as returned from `c.getAField().getType()` can be cast to `RefType`, which has a method `getQualifiedName` -- for example, `c.getAField().getType().(RefType).getQualifiedName()`.

Note this implicitly asserts that `getType()` returned a `RefType`-- if you need to keep non-reftypes (e.g., primitives) then you might want to use a helper like

```ql
string typeToQName(Type t) {
  if t instanceof RefType
  then result = t.(RefType).getQualifiedName()
  else result = t.toString()
}
```

**Comment by struce2** [comment]
Thank you very much
