### ISSUE TITLE
java:Codeql cannot handle Java reference passing

### ISSUE THREAD

**Issue by Sea8ye** [github/codeql#13369]
Codeql defaults to not being able to pass stains from id to req through the convertToOrderListRequest method. I don't know how to write this generic isAdditionalTaintStep to solve similar object reference passing problems. Please help me：

```java
public class DemoApplication {

	@GetMapping("/test")
	public GetOrderPlatformListRequestType test(@RequestParam("id") String id) {
		GetOrderPlatformListRequestType req = new GetOrderPlatformListRequestType();
		convertToOrderListRequest(id,req);
		System.out.println(req);
		return req;
	}

	private void convertToOrderListRequest(String mobile, GetOrderPlatformListRequestType request) {
		request.setMobile(mobile);
	}

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}

public class GetOrderPlatformListRequestType implements Serializable {
    private String mobile;

    public GetOrderPlatformListRequestType(String mobile) {
        this.mobile = mobile;
    }

    public GetOrderPlatformListRequestType() {

    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
}
```

this is my .ql:

```ql
/**
 * @name sectest2
 * @description Writing sectest33
 * @kind path-problem
 * @problem.severity error
 * @precision high
 * @id java/sql-injection
 * @tags security
 */

import java
import semmle.code.java.dataflow.FlowSources
import semmle.code.java.security.QueryInjection
import semmle.code.java.dataflow.TaintTracking
import DataFlow::PathGraph



class MySink extends DataFlow::Node{
    MySink(){
    exists(MethodAccess m |  
        this.asExpr()=m.getArgument(0) and m.getMethod().getName()="println"
        )
    }
}


class MyTaintTrackingConfiguration extends TaintTracking::Configuration {
  MyTaintTrackingConfiguration() { this = "MyTaintTrackingConfiguration" }

  override predicate isSource(DataFlow::Node source) {
   source instanceof RemoteFlowSource 
  }

  override predicate isSink(DataFlow::Node sink) {
     sink instanceof MySink
}

}

from  DataFlow::PathNode source, DataFlow::PathNode sink,MyTaintTrackingConfiguration config
where config.hasFlowPath(source, sink)
select sink.getNode(),source, sink, "sql-injection"
```

**Comment by Sea8ye** [comment]
> Unfortunately we also stumble into a CodeQL bug here: if your toString method really does explicitly expose the mobile field but your code uses the implicit string conversion System.out.println(req), then while we should produce a result without additional help, we still do need the allowImplicitRead override.

Thank you for your answer.
Yes, I think this is a bug.
I hope that codeql can also support spreading stains from the mobile field to the whole GetOrderPlatformListRequestType object by default.
In my other tests, I used both fortify SCA and codeql for testing, and I found that fortify could detect vulnerabilities, but codeql did not, because of this bug. This is regrettable, but I still think Codeql is an excellent static code analysis tool.

**Comment by Sea8ye** [comment]
I got the reason, the stain on the mobile field did not propagate to the request object
By using this isAdditionalTaintStep, this problem can be solved：

`
override predicate isAdditionalTaintStep(DataFlow::Node n1, DataFlow::Node n2) {
  exists(MethodAccess ma |
   n1.asExpr() = ma.getArgument(0) and
     ma.getMethod() instanceof SetterMethod and
   n2.asExpr() = ma.getQualifier() 
 )
}
`

But the best scenario is that stains can be marked on this.mobile instead of the whole request object, which can lead to false positives

**Comment by smowton** [comment]
When we have the source code for the setter, so we know the taint really gets stored in a particular field, and we could use that knowledge to avoid mixing the field up with a different one, we would generally want to keep the taint isolated.

I would recommend using an `allowImplicitRead` predicate to permit the taint to rise from the field to the whole object just at the particular sink you have in mind (here, a call to `println`).

**Comment by Sea8ye** [comment]
If I want to write an allowImplicitRead that takes effect on all rules, what should I do

**Comment by smowton** [comment]
Normally you shouldn't need to -- the taint would be tracked in the `mobile` field until the `GetOrderPlatformListRequestType` reaches the sink, and only then do we need to broaden the taint to the whole object. However sometimes it's also necessary to do this on entry to an external function that has an additional taint step, which is why the usual definition of `isImplicitRead` looks like


```ql
   override predicate allowImplicitRead(DataFlow::Node node, DataFlow::ContentSet c) {
     (isSink(node) or isAdditionalTaintStep(node, _)) and /* specify content -- e.g. c instanceof FieldContent */
     super.allowImplicitRead(node, c)
   }
```
