### ISSUE TITLE
codeql create chromium database failed

### ISSUE THREAD

**Issue by 18Fl** [github/codeql#13531]
## Introduction

Hi, I meet a error when I build chormium. I follow [this](https://github.com/github/securitylab/blob/main/CodeQL_Queries/cpp/Chrome/README.md) to build the codeql database.

1. compile all chrome  by autoninja -C out\codeql chrome
2. delete the folder: out\codeql\obj\content\browser\devtools
3. regenerate related *.ninja file by gn args out\codeql 
4. use this command try to create database :  C:\Users\18f\Desktop\codeql-win64\codeql\codeql.exe  database create D:\code_db\run  --overwrite --language=cpp --command='autoninja -C out\codeql chrome"

I use full path codeql because the original codeql version is `| 2.13.3|`,so I download the newest codeql which version is 2.14.4.

And errors happened:

``` c++
[2023-06-22 01:50:39] [build-stdout] [1401/1406] STAMP obj/content/browser/browser.stamp
[2023-06-22 01:50:57] [build-stdout] [1402/1406] LINK(DLL) chrome.dll chrome.dll.lib chrome.dll.pdb
[2023-06-22 01:50:59] [build-stdout] [1403/1406] LINK initialexe/chrome.exe initialexe/chrome.exe.pdb
[2023-06-22 01:50:59] [build-stdout] [1404/1406] ACTION //chrome:reorder_imports(//build/toolchain/win:win_clang_x64)
[2023-06-22 01:50:59] [build-stdout] [1405/1406] STAMP obj/chrome/reorder_imports.stamp
[2023-06-22 01:50:59] [build-stdout] [1406/1406] STAMP obj/chrome/chrome.stamp   // [+] @a
Finalizing database at D:\code_db\old_bug.
CodeQL detected code written in C/C++ but could not process any of it. This can occur if the specified build commands failed to compile or process any code. // [+] @b
 - Confirm that there is some source code for the specified language in the project.
 - For codebases written in Go, JavaScript, TypeScript, and Python, do not specify
   an explicit --command.
   all the source code files without reusing existing build artefacts.
```

I don't understand why : @a means we build it success, but @b means we failed....

For repro the bug more quickly, I use another method:

1. compile all chrome file by  autoninja -C out\codeql chrome
2. edit code in content\browser\devtools\protocol\input_handler.cc
``` c++
bool StringToGestureSourceType(Maybe<std::string> in, //  [+] I create this commit to make codeql to recompile
                               content::mojom::GestureSourceType& out) {
  if (!in.isJust()) {
    out = content::mojom::GestureSourceType::kDefaultInput;
    return true;
  }
  if (in.fromJust() == Input::GestureSourceTypeEnum::Default) {
    out = content::mojom::GestureSourceType::kDefaultInput;
    return true;
  }
  if (in.fromJust() == Input::GestureSourceTypeEnum::Touch) {
    out = content::mojom::GestureSourceType::kTouchInput;
    return true;
  }
  if (in.fromJust() == Input::GestureSourceTypeEnum::Mouse) {
    out = content::mojom::GestureSourceType::kMouseInput;
    return true;
  }
  return false;
}
```
3.  C:\Users\18f\Desktop\codeql-win64\codeql\codeql.exe  database create D:\code_db\run  --overwrite --language=cpp --command='autoninja -C out\codeql chrome'
Initializing database at D:\code_db\run.

Then I failed again:
``` c++
PS D:\chrome\src> C:\Users\18f\Desktop\codeql-win64\codeql\codeql.exe  database create D:\code_db\run  --overwrite --language=cpp --command='autoninja -C out\codeql chrome'
Initializing database at D:\code_db\run.
Running build command: [autoninja, -C, out\codeql, chrome]
[2023-06-22 10:01:06] [build-stdout] "C:\Users\18f\Desktop\18_floor\source_code\build_chromium_tools\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\python3.exe" C:\Users\18f\Desktop\18_floor\source_code\build_chromium_tools\depo[2023-06-22 10:01:11] [build-stdout] ninja: Entering directory `out\codeql'
[2023-06-22 10:01:22] [build-stdout] [1/7] CXX obj/content/browser/browser/input_handler.obj
[2023-06-22 10:01:22] [build-stdout] [2/7] STAMP obj/content/browser/browser.stamp
[2023-06-22 10:01:42] [build-stdout] [3/7] LINK(DLL) chrome.dll chrome.dll.lib chrome.dll.pdb
[2023-06-22 10:01:43] [build-stdout] [4/7] LINK initialexe/chrome.exe initialexe/chrome.exe.pdb
[2023-06-22 10:01:44] [build-stdout] [5/7] ACTION //chrome:reorder_imports(//build/toolchain/win:win_clang_x64)
[2023-06-22 10:01:44] [build-stdout] [6/7] STAMP obj/chrome/reorder_imports.stamp
[2023-06-22 10:01:44] [build-stdout] [7/7] STAMP obj/chrome/chrome.stamp
CodeQL detected code written in C/C++ but could not process any of it. This can occur if the specified build commands failed to compile or process any code.
 - Confirm that there is some source code for the specified language in the project.
 - For codebases written in Go, JavaScript, TypeScript, and Python, do not specify
   an explicit --command.
 - For other languages, the --command must specify a "clean" build which compiles
   all the source code files without reusing existing build artefacts.
```

Here is my log file:
[build-tracer.log](https://github.com/github/codeql/files/11828080/build-tracer.log)
[database-create-20230622.102645.959.log](https://github.com/github/codeql/files/11828081/database-create-20230622.102645.959.log)

Note: 
>  The chormium which I build is not the newest one. so my window sdk version is 10.0.20348.1, but I don't think this is the reason...

Would u mind give me any tips? thank you very much!

```[tasklist]
### Tasks
```

**Comment by aibaars** [comment]
Thanks for reporting this. I spotted the following error in the build-tracer.log, and this might be an explanation of why things aren't working.
```
Command-line error: the version of Microsoft being emulated must be at least 1920 to use "--ms_c++20"

[E 10:27:06 12676] Warning[extractor-c++]: In construct_message: Command-line error: the version of Microsoft being emulated must be at least 1920 to use "--ms_c++20"


1 catastrophic error detected in this compilation.
Compilation terminated.
```
@jketema or @MathiasVP do you know why this happens? The actual build seems to be fine, but somehow the CodeQL analyser is unhappy about the `--ms_c++20` flag. Is there a way to avoid this?

**Comment by jketema** [comment]
The code is being compiled with clang-cl - which is shipped with Chromium - and the compiler invocation includes `-fmsc-version=1916`. However, that version of the Microsoft compiler did not come with C++20 support as far as I'm aware, and that's what our tooling is complaining about, as we strictly check this. To work around this, you might want to try to set the value of `-fmsc-version` to at least `1920`. I cannot give further guidance on how to do this unfortunately.

We can look into allowing this particular combination of flags, but as we've not seen this issue reported before, this will be a low priority item.

**Comment by 18Fl** [comment]
> The code is being compiled with clang-cl - which is shipped with Chromium - and the compiler invocation includes `-fmsc-version=1916`. However, that version of the Microsoft compiler did not come with C++20 support as far as I'm aware, and that's what our tooling is complaining about, as we strictly check this. To work around this, you might want to try to set the value of `-fmsc-version` to at least `1920`. I cannot give further guidance on how to do this unfortunately.
> 
> We can look into allowing this particular combination of flags, but as we've not seen this issue reported before, this will be a low priority item.

Intersting, is anyway to solve this? should I compile codeql by myself, and remove the stictly check? If I need to do this, which code should I edit.

Maybe another way is try to use old codeql. in old codeql, maybe there are a stictly check like:

``` c++
-fmsc-version>=1916
```

I will try this....

**Comment by jketema** [comment]
> Intersting, is anyway to solve this? should I compile codeql by myself, and remove the stictly check? If I need to do this, which code should I edit.

This is not possible, as the relevant CodeQL component is closed source and not part of this repository.

> Maybe another way is try to use old codeql. in old codeql, maybe there are a stictly check like:
> 
> ```c++
> -fmsc-version>=1916
> ```
> 
> I will try this....

The easiest way is probably to modify the Chromium build system to output something like `-fmsc-version=1920` instead of `-fmsc-version=1916`, which is what I hinted at above.

**Comment by 18Fl** [comment]
> > Intersting, is anyway to solve this? should I compile codeql by myself, and remove the stictly check? If I need to do this, which code should I edit.
> 
> This is not possible, as the relevant CodeQL component is closed source and not part of this repository.
> 
> > Maybe another way is try to use old codeql. in old codeql, maybe there are a stictly check like:
> > ```c++
> > -fmsc-version>=1916
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I will try this....
> 
> The easiest way is probably to modify the Chromium build system to output something like `-fmsc-version=1920` instead of `-fmsc-version=1916`, which is what I hinted at above.

Yes, It is worked. thank u very much.

For another people who want learn codeql query by old chromium bug. I will write this in details.

Just change this file , everything will be ok:

``` c++
PS D:\chrome\src> git diff
diff --git a/build/config/win/BUILD.gn b/build/config/win/BUILD.gn
index a5075393b1231..199021945e488 100644
--- a/build/config/win/BUILD.gn
+++ b/build/config/win/BUILD.gn
@@ -98,7 +98,7 @@ config("compiler") {
     cflags += [ "/D__WRL_ENABLE_FUNCTION_STATICS__" ]

     # Tell clang which version of MSVC to emulate.
-    cflags += [ "-fmsc-version=1916" ]
+    cflags += [ "-fmsc-version=1920" ]

     if (is_component_build) {
       cflags += [
```

Now , it will be ok!
