### ISSUE TITLE
Low speed for database bundle and database finalize command

### ISSUE THREAD

**Issue by CHENXIXIXIXI718** [github/codeql#13570]
Hi,
We used some CodeQL commands  in our CodeQL task, but we found database bundle and database finalize step is very low, each of them may task 5-6 mins. May I ask if there any ways to reduce the time of these two steps, since these two steps take up almost two-thirds of our task?

**Comment by aeisenberg** [comment]
Without knowing much about your specific situation, I can only recommend a few general things:

1. You can pass the `--cleanup-upgrade-backups` option to make the database smaller
2. Run `codeql database finalize --mode brutal` to make the database much smaller (do this before running `bundle`).  See the `--help` for an explanation of exactly what this does
3. Are you running on windows? If possible, try running on ubuntu or another flavour of linux.

**Comment by CHENXIXIXIXI718** [comment]
Thanks @aeisenberg ! I checked our CodeQL task has already used your second recommendation, I guess maybe the first option you provided we can try.

**Comment by aeisenberg** [comment]
Feel free to raise a new issue if you still have a problem. Please run in debug mode and attach your database creation logs.

**Comment by CHENXIXIXIXI718** [comment]
Thanks for your kindness :)
