### ISSUE TITLE
C/C++: about Function's Declaration and Definition

### ISSUE THREAD

**Issue by iiins0mn1a** [github/codeql#13611]
I've read the issue #9337 , and tried the query provided:
```codeql
from Function f, FunctionDeclarationEntry e
where
  not e.isDefinition() and
  f.getADeclarationEntry() = e and
  f.hasEntryPoint()
select f, e
```
This query does find the declaration of a definition function `f`, results are returned in the form of `FunctionDeclarationEntry` class.
Once I want to transform these declaration entities to the class `Function` with method `FunctionDeclarationEntry::getFunction()`, it always returns the orginal function, the definition, rather than declaration.

So I'm curious how can I fetch the declaration in the form of class `Function`.

The ultimate reason for doing so is that, I want to fetch a definition of a declaration, a reverse version of previous one.

This is my version to get the function's definition:
```codeql
Function getFunctionDefinition(Function func) {
    if func.hasEntryPoint() 
    then result = func
    else exists(
        FunctionDeclarationEntry e |
        func.getADeclarationEntry() = e and
        result = e.getFunction() and
        result.hasEntryPoint()
        )
}
```
And it failed, I've found two reasons to explain this after some testing on my database. 

One is that, when I use definition function(def-func) as input to call the method `getADeclarationEntry`, both declarations and definitions would be returned. But with declaration function(dec-func) as input, only declarations would be returned by this method, which means `getADeclarationEntry` failed for resolving the definition.

And second reason is just like I mensioned before, the `e.getFunction()` can only return the declaration itself.

Please help me! I want to build the connection between dec-func and def-func efficiently!

**Comment by iiins0mn1a** [comment]
And this is my work around:
```codeql
Function getFunctionDefinition(Function func) {
    if func.hasEntryPoint() 
    then result = func
    else 
        result.hasEntryPoint() and
        result.getName() = func.getName()
}
```
Actually LGTM... Do you guys have any more to comment?

**Comment by aeisenberg** [comment]
Glad you were able to figure this out on your own. This looks reasonable to me.

In the future, you may want to ask these kinds of questions on the Security Lab Slack. You can find the link on [this page](https://securitylab.github.com/get-involved/). There are many people available who are happy to help with queries like this.

**Comment by iiins0mn1a** [comment]
Hi, @aeisenberg ! Thanks for replying, reason for raising this issue is that, I considered string matching to be a last choice, something we should try to avoid, when there's a better alternative available. 

And thx for the link, it looks better!
