### ISSUE TITLE
CodeQL Python Query Issue: 'INVALID_RESULT_PATTERNS' Error when Retrieving a Specific Argument of a Function Call

### ISSUE THREAD

**Issue by kexinoh** [github/codeql#13646]
I am attempting to write a Python query using CodeQL that retrieves the second argument of calls to a specific function (in this case, the 'chiper' function). Here is the query I have been working with:

ql
```
/**
 * @id python/find-chiper-call
 * @name Find calls to the 'chiper' function
 * @description Finds calls to the 'chiper' function and prints out the location and the second argument.
 * @kind problem
 * @problem.severity recommendation
 */

import python

from Call c
where 
  c.getFunc().(Name).getId() = "chiper" and
  exists(c.getArg(1)) // Here, 1 refers to the second argument as indexing starts from 0.
select c, "This call to the 'chiper' function has the second argument: " + c.getArg(1).toString()
```

Upon running this query, I receive the following error message:

**A fatal error occurred: Could not process query metadata for D:\pycharm\codeqlincrypto\chiper_query.ql. Error was: Expected result pattern(s) are not present for problem query: Expected alternating entity/string and string columns. [INVALID_RESULT_PATTERNS]**

I understand that '@kind problem' queries require me to return a Locatable object and a message string in my select statement. In my query, I have selected a Call object (which is a Locatable object) and a string containing the text representation of the second argument. However, I am still receiving the error message.

I would appreciate any assistance in understanding how to correctly format my query results, so I can retrieve the information I need. Thank you!

**Comment by intrigus-lgtm** [comment]
How are you running your query? Directly using `codeql` on the CLI? Or via VS Code?

**Comment by kexinoh** [comment]
> How are you running your query? Directly using `codeql` on the CLI? Or via VS Code?

i solve it by:https://github.com/github/codeql/issues/6482 .

**Comment by rjt-gupta** [comment]
> How are you running your query? Directly using `codeql` on the CLI? Or via VS Code?

Hello! I'm facing the same issue. How can I rerun the query using VSCode?
