### ISSUE TITLE
How can I resolve the situation where the error "ERROR: Could not resolve module" occurs?

### ISSUE THREAD

**Issue by KingXS** [github/codeql#13655]
When I ran the following command in the macOS terminal: codeql database analyze ./codeqltest --format=csv --output=/tmp/result.csv /Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/src/codeql-suites/java-code-scanning.qls, CodeQL returned an error. The error message is as follows:

Compiling query plan for /Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/src/Likely Bugs/Arithmetic/InformationLoss.ql.
ERROR: Could not resolve module XssVulnerableWriterSourceToWritingMethodFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:47,7-51)
ERROR: Could not resolve module ImplicitStartActivityForResult (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:31,7-37)
ERROR: Could not resolve module TypeLiteralToJacksonDatabindFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:111,3-35)
ERROR: Could not resolve module TypeLiteralToParseAsFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:27,3-27)
ERROR: Could not resolve module RemoteUserInputToArgumentToExecFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:97,3-38)
ERROR: Could not resolve module RemoteUserInputToArgumentToExecFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:98,3-38).

Why did this happen? Is it because I'm missing some dependencies? How should I install these dependencies? Given that the qlpack.yml files are distributed across different directories, how can I install them all at once? Or how should I improve the command I'm running?

**Comment by KingXS** [comment]
Here is the error message

Compiling query plan for /Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/src/Likely Bugs/Arithmetic/InformationLoss.ql.
ERROR: Could not resolve module XssVulnerableWriterSourceToWritingMethodFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:47,7-51)
ERROR: Could not resolve module ImplicitStartActivityForResult (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:31,7-37)
ERROR: Could not resolve module TypeLiteralToJacksonDatabindFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:111,3-35)
ERROR: Could not resolve module TypeLiteralToParseAsFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:27,3-27)
ERROR: Could not resolve module RemoteUserInputToArgumentToExecFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:97,3-38)
ERROR: Could not resolve module RemoteUserInputToArgumentToExecFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:98,3-38)
ERROR: Could not resolve module RemoteUserInputToArgumentToExecFlow (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:100,3-38)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:26,3-30,52)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:32,3-33,54)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:35,3-36,55)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:38,3-41,76)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:43,3-47,74)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:49,3-54,52)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:56,3-74,47)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:76,3-77,79)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:79,3-80,73)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:82,3-88,52)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:107,3-111,52)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:119,3-120,54)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:122,3-123,55)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:125,3-128,76)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:136,3-140,74)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:142,3-147,52)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:149,3-167,47)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:169,3-170,79)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:172,3-173,73)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll:175,3-181,52)
ERROR: Default implementations of module signature predicate members are not yet supported. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/shared/mad/codeql/mad/ModelValidation.qll:16,3-17,56)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare isBarrier/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare isBarrierIn/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare isBarrierOut/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare isAdditionalFlowStep/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare allowImplicitRead/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare fieldFlowBranchLimit/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare getAFeature/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare sourceGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare sinkGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module XssVulnerableWriterSourceToWritingMethodFlowConfig does not declare includeHiddenNodes/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/XSS.qll:64,78-97)
ERROR: Module ImplicitStartActivityForResultConfig does not declare isBarrierIn/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:66,64-83)
ERROR: Module ImplicitStartActivityForResultConfig does not declare isBarrierOut/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:66,64-83)
ERROR: Module ImplicitStartActivityForResultConfig does not declare allowImplicitRead/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:66,64-83)
ERROR: Module ImplicitStartActivityForResultConfig does not declare fieldFlowBranchLimit/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:66,64-83)
ERROR: Module ImplicitStartActivityForResultConfig does not declare getAFeature/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:66,64-83)
ERROR: Module ImplicitStartActivityForResultConfig does not declare sourceGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:66,64-83)
ERROR: Module ImplicitStartActivityForResultConfig does not declare sinkGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:66,64-83)
ERROR: Module ImplicitStartActivityForResultConfig does not declare includeHiddenNodes/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/android/OnActivityResultSource.qll:66,64-83)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare isBarrier/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare isBarrierIn/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare isBarrierOut/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare isAdditionalFlowStep/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare allowImplicitRead/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare fieldFlowBranchLimit/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare getAFeature/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare sourceGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare sinkGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToJacksonDatabindFlowConfig does not declare includeHiddenNodes/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll:90,66-85)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare isBarrier/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare isBarrierIn/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare isBarrierOut/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare isAdditionalFlowStep/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare allowImplicitRead/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare fieldFlowBranchLimit/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare getAFeature/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare sourceGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare sinkGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module TypeLiteralToParseAsFlowConfig does not declare includeHiddenNodes/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/frameworks/google/GoogleHttpClientApi.qll:13,58-77)
ERROR: Module RemoteUserInputToArgumentToExecFlowConfig does not declare isBarrierIn/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:52,61-80)
ERROR: Module RemoteUserInputToArgumentToExecFlowConfig does not declare isBarrierOut/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:52,61-80)
ERROR: Module RemoteUserInputToArgumentToExecFlowConfig does not declare allowImplicitRead/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:52,61-80)
ERROR: Module RemoteUserInputToArgumentToExecFlowConfig does not declare fieldFlowBranchLimit/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:52,61-80)
ERROR: Module RemoteUserInputToArgumentToExecFlowConfig does not declare getAFeature/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:52,61-80)
ERROR: Module RemoteUserInputToArgumentToExecFlowConfig does not declare sourceGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:52,61-80)
ERROR: Module RemoteUserInputToArgumentToExecFlowConfig does not declare sinkGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:52,61-80)
ERROR: Module RemoteUserInputToArgumentToExecFlowConfig does not declare includeHiddenNodes/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:52,61-80)
ERROR: Module LocalUserInputToArgumentToExecFlowConfig does not declare isBarrierIn/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:73,60-79)
ERROR: Module LocalUserInputToArgumentToExecFlowConfig does not declare isBarrierOut/1, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:73,60-79)
ERROR: Module LocalUserInputToArgumentToExecFlowConfig does not declare allowImplicitRead/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:73,60-79)
ERROR: Module LocalUserInputToArgumentToExecFlowConfig does not declare fieldFlowBranchLimit/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:73,60-79)
ERROR: Module LocalUserInputToArgumentToExecFlowConfig does not declare getAFeature/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:73,60-79)
ERROR: Module LocalUserInputToArgumentToExecFlowConfig does not declare sourceGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:73,60-79)
ERROR: Module LocalUserInputToArgumentToExecFlowConfig does not declare sinkGrouping/2, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:73,60-79)
ERROR: Module LocalUserInputToArgumentToExecFlowConfig does not declare includeHiddenNodes/0, required by implemented signature ConfigSig. (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandLineQuery.qll:73,60-79)
ERROR: Non-monotonic recursion: CommandArguments::CommandArgArrayImmutableFirst::getFirstElement -!-> CommandArguments::CommandArgArrayImmutableFirst --> characteristic predicate of CommandArguments::CommandArgArrayImmutableFirst --> CommandArguments::firstElementOf --> CommandArguments::CommandArgArrayImmutableFirst::getFirstElement (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandArguments.qll:158,16-33)
ERROR: Non-monotonic recursion: CommandArguments::CommandArgArrayImmutableFirst --> characteristic predicate of CommandArguments::CommandArgArrayImmutableFirst --> CommandArguments::firstElementOf --> CommandArguments::CommandArgArrayImmutableFirst::getFirstElement -!-> CommandArguments::CommandArgArrayImmutableFirst (/Users/fqy/Desktop/CodeAudit/Tools/codeqls/java/ql/lib/semmle/code/java/security/CommandArguments.qll:148,15-44)

**Comment by smowton** [comment]
The problem is that you're using the latest `codeql` main, but the `codeql` binary you're using is a release that doesn't understand some of the CodeQL features used there.

There is a branch of the github/codeql repo named after each release that is guaranteed to be compatible. For example, if you run `codeql --version` and find you're using the latest release from https://github.com/github/codeql-cli-binaries/releases (v2.13.4) then you should try checking out the corresponding branch https://github.com/github/codeql/tree/codeql-cli-2.13.4

**Comment by KingXS** [comment]
The problem has been solved, thank you very much for your answer!
