### ISSUE TITLE
questioin about variablecall 

### ISSUE THREAD

**Issue by 18Fl** [github/codeql#13766]
# Introduction

Hey, I have try to learn codeql from [this challenge](https://securitylab.github.com/ctf/eko2020/). It's a challenge which find UAF by codeql.  and it is simple.

However, I decide to explore more challenge, I create a little demo:

``` c++
#include <stdio.h>
#include <stdlib.h>

void * mem_freed_by_int = NULL;
void * mem_freed_by_void = NULL;

int (* call_free_ptr_int) ();
void (* call_free_ptr_void) ();

int evil_callback_ret_int(){
    free(mem_freed_by_int);
}

void evil_callback_ret_void(){
    free(mem_freed_by_void);
}

//  [+] The grammer seems strange, I just use it to learn something....
void (*void_callback())(){
    void (* tmp_ptr)();
    tmp_ptr = evil_callback_ret_void;
    return tmp_ptr;
}

int (*int_callback())(){
    int (* tmp_ptr)();
    tmp_ptr = evil_callback_ret_int;
    return tmp_ptr;
}

void set_int_function_ptr(){
    call_free_ptr_int = int_callback();
}

void set_void_function_ptr(){
    call_free_ptr_void = void_callback();
}

int main(){
    //  [+] initiailize memory
    mem_freed_by_int = malloc(0x20);
    mem_freed_by_void = malloc(0x20);

    //  [+] function, think it is a callback...
    set_int_function_ptr();
    set_void_function_ptr();

    call_free_ptr_int();    //  [+] call freed.
    call_free_ptr_void();   //  [+] call freed.

    *(int*)mem_freed_by_int = 0x2121;
    *(int*)mem_freed_by_void = 0x4141;

    return 0;
}
```

This is a various of UAF, we don't use a functioncall to free a memory, now we use a variablecall(function pointer) to free a memory. For now, I use this query to define the source and sink.

``` c++
/**
 * @name just for codeql
 * @kind path-problem
 * @id cpp/workshop/uaf
*/

import cpp
import DataFlow::PathGraph
import semmle.code.cpp.controlflow.Guards
import semmle.code.cpp.dataflow.new.TaintTracking

//  [+] How to archive a a query to query a function pointer case
class FuncPointerUAFConfiguration extends TaintTracking::Configuration{
    FuncPointerUAFConfiguration() {this = "FuncPointerUAFConfiguration"}

    //  [+] how to define source...
    //  [+] make sure it managed by source...
    override predicate isSource(DataFlow::Node source) {
        exists(FunctionCall malloc_call |  
            malloc_call.getTarget().getQualifiedName().matches("%malloc%")
            //  [+] just ensure source is the result of malloc_call
            and source.asExpr() = malloc_call    
        )
    }

    //  [+] give it a santinizer maybe is a good idea...

    //  [+] sink should be simple
    //  [+] *(int*)mem_freed_by_int = 0x2121;
    override predicate isSink(DataFlow::Node sink) {
        dereferenced(sink.asExpr())
    }
}


from DataFlow::PathNode malloc, DataFlow::PathNode access, FuncPointerUAFConfiguration conf
where conf.hasFlow(malloc.getNode(), access.getNode())
select access, malloc, access, "The source $@ , and as a result $@", malloc, 
" function called at here", access, " used at here"
```

The could describe a dataflow from malloc->deference. My basic idea like this, I could add a santinizer , and If the santinizer  doen't pass a variableCall which will freed the memory, It won't cause UAF. So I could get some result which I need.

But If I change the code to this:

``` c++
#include <stdio.h>
#include <stdlib.h>

void * mem_freed_by_int = NULL;
void * mem_freed_by_void = NULL;

int (* call_free_ptr_int) ();
void (* call_free_ptr_void) ();

int evil_callback_ret_int(){
    //  [+] initiailize memory
    mem_freed_by_int = malloc(0x20);
    free(mem_freed_by_int);
}

void evil_callback_ret_void(){
    mem_freed_by_void = malloc(0x20);
    free(mem_freed_by_void);
}

//  [+] The grammer seems strange, I just use it to learn something....
void (*void_callback())(){
    void (* tmp_ptr)();
    tmp_ptr = evil_callback_ret_void;
    return tmp_ptr;
}

int (*int_callback())(){
    int (* tmp_ptr)();
    tmp_ptr = evil_callback_ret_int;
    return tmp_ptr;
}

void set_int_function_ptr(){
    call_free_ptr_int = int_callback();
}

void set_void_function_ptr(){
    call_free_ptr_void = void_callback();
}

int main(){

    //  [+] function, think it is a callback...
    set_int_function_ptr();
    set_void_function_ptr();

    call_free_ptr_int();    //  [+] call freed.
    call_free_ptr_void();   //  [+] call freed.

    *(int*)mem_freed_by_int = 0x2121;
    *(int*)mem_freed_by_void = 0x4141;

    return 0;
}

```

Now for me , It's so hard for me to write this query . I don't know how to archive this. Could u give me any tips or a full example which could archive this work?

I offer the database at here. Thank u so much.

[cool_example.zip](https://github.com/github/codeql/files/12090907/cool_example.zip)

**Comment by jketema** [comment]
Hi @18Fl, thanks for your question. Dataflow does not automatically take into account function pointers. So you will need to write an additional analysis that figures out what each function pointer is, and those should then be used in the source and sink definitions of `FuncPointerUAFConfiguration`.

**Comment by 18Fl** [comment]
> Hi @18Fl, thanks for your question. Dataflow does not automatically take into account function pointers. So you will need to write an additional analysis that figures out what each function pointer is, and those should then be used in the source and sink definitions of `FuncPointerUAFConfiguration`.

Would u mind explain this in more details, espcially with a complete example. Thank u.
=

**Comment by 18Fl** [comment]
> > Hi @18Fl, thanks for your question. Dataflow does not automatically take into account function pointers. So you will need to write an additional analysis that figures out what each function pointer is, and those should then be used in the source and sink definitions of `FuncPointerUAFConfiguration`.
> 
> # Would u mind explain this in more details, espcially with a complete example. Thank u.

And I have no idea to how to think about who is the source or who is the sink in my personal views, That's why I made such a rude request.I want to see how a knowledgeable person sees it. Sorry for this...

**Comment by jketema** [comment]
Writing out a complete example here will be a significant amount of work, so I will not attempt that here.

What you probably want to do is the following:
* Define a dataflow configuration that has its source an assignment of a "malloc"-like function to a function pointer, and as its sink a call of the function pointer.
* Define a similar configuration for the "free"-like function
* In your `FuncPointerUAFConfiguration` restrict the source to any call that we can flow to in the configuration for the "malloc"-like function, and restrict the sink to any call that we can flow to in the configuration for the "free"-like function.

**Comment by 18Fl** [comment]
> Writing out a complete example here will be a significant amount of work, so I will not attempt that here.
> 
> What you probably want to do is the following:
> 
> * Define a dataflow configuration that has its source an assignment of a "malloc"-like function to a function pointer, and as its sink a call of the function pointer.
> * Define a similar configuration for the "free"-like function
> * In your `FuncPointerUAFConfiguration` restrict the source to any call that we can flow to in the configuration for the "malloc"-like function, and restrict the sink to any call that we can flow to in the configuration for the "free"-like function.

Thanks for your reply, I forgot reply this. sorry.... I will close this issue!
