### ISSUE TITLE
False positive: passing context with credentials to logrus

### ISSUE THREAD

**Issue by DavidS-om** [github/codeql#13828]
**Description of the false positive**

When using a context for both log correlation (e.g. with opentelemetry) and holding API Keys (e.g. for use in api clients), the benign use of `logrus.WithContext(ctx)` gets flagged up as "Clear-text logging of sensitive information", when `WithContext` does not do such thing.

**Code samples or links to source code**

https://github.com/overmindtech/ovm-cli/pull/27/commits/05ca8f6deb91a9e50bf462d62ec052e8905a9074#diff-17afbc70fe24dfd24a85d8aa9a3456c9a3b75244d8772d3f83744a51ec511dcbR120

This is the offending code:
```go
import (
	log "github.com/sirupsen/logrus"
)

// ...

func changingItemQueriesFromPlan(ctx context.Context, planJSON []byte, lf log.Fields) ([]*sdp.Query, error) {
  // ...
  log.WithContext(ctx).WithError(err).Infof("could not find scope mapping variables %v, adding them will result in better results. Error: ", mapData.Scope)
  // ...
}
```

Note that CodeQL is correct insofar as `ctx` in our app contains credentials that are passed on to various clients along the way and that `ctx` is passed to a logging method (in the loosest definition) in `WithContext(ctx)`, but `WithContext` does not log the parameters or the credentials in the context, so this is spurious. 

**URL to the alert on GitHub code scanning (optional)**

https://github.com/overmindtech/ovm-cli/security/code-scanning/92

**Comment by smowton** [comment]
Seems reasonable -- amendment posted as https://github.com/github/codeql/pull/13835
