### ISSUE TITLE
Go: support remote package analysis

### ISSUE THREAD

**Issue by am0o0** [github/codeql#13833]
I was trying to analysis [this CVE](https://github.com/advisories/GHSA-m5q5-8mfw-p2hr) which is a JWT related vulnerability, I noticed they are using [this wrapper](https://github.com/IceWhaleTech/CasaOS/blob/705bf1facbffd2ca40b159b0303132b6fdf657ad/route/v1.go#L9C2-L9C51) that is a wrapper of "github.com/golang-jwt/jwt/v4" package [in here](https://github.com/IceWhaleTech/CasaOS-Common/blob/50e132e90de9a5761b971a8115312744ecd82335/utils/jwt/jwt.go#L9).
there is a already modeled CodeQL library and query for "github.com/golang-jwt/jwt/v4" but we don't want to model the wrapper of this library because they are not so popular and usually are like public customized packages for special application.
so we must contain the source code of "ceWhaleTech/CasaOS-Common" repository somehow in "IceWhaleTech/CasaOS"  to be able to run JWT related queries that already contain the modeled library inside.

what I did was simple:
1. inside CasaOS repository clone go.mod packages or the packages you need to contain in CodeQL DB creation
2. checkout the to the required versions of this cloned  repositories(packages)
3. create a go.wok in CasaOS repository and put the cloned repositories(packages) name

I was able to analysis the CasaOS without modeling its JWT wrapper in this way.
I think it can be great to create a script for this, if it is not according to current roadmap of CodeQL, so I can do this as a contributor. 
note that there are many open source applications that are using their own wrapper of popular zipfile/jwt/... libraries in this way.
another idea can be this that somehow we detect there is a already codeql library related to a major package in one of the packages/sub-packages(wrapper packages) and we can just contain these modeled packages source  code in main application source code by go workspaces.

**Comment by smowton** [comment]
Thanks for the suggestion -- this case, of wanting to include one or more libraries within the domain of analysis, does come up from time to time. It isn't on our immediate roadmap because it's a case that usually affects people analysing in depth, whereas our current focus is to improve our breadth and applicability for users with large amounts of code requiring low-effort analysis. However we would certainly welcome a contribution in this direction.
