### ISSUE TITLE
codeql won't work with chromium special file

### ISSUE THREAD

**Issue by 18Fl** [github/codeql#13849]
# Introduction

Hey, I have successful build chromium codeql and run some query on it. they work well. But When I run some special query , I found Iit miss something, Finaly I found seems codeql don't create database with special file(chrome\browser\ui\autofill\chrome_autofill_client.cc).

``` c++
bad@DESKTOP-ETKSDTV:~/chromium_src/src$  codeql database create ../../code_db/best_u/  -J-Xmx40G  --overwrite --language=cpp --command='ninja -j10 -C out/codeql chrome'
Initializing database at /home/bad/code_db/best_u.
Running build command: [ninja, -j10, -C, out/codeql, chrome]
[2023-07-31 15:03:00] [build-stdout] ninja: Entering directory `out/codeql'
[2023-07-31 15:03:19] [build-stdout] [1/3] CXX obj/chrome/browser/ui/ui/chrome_autofill_client.o
[2023-07-31 15:03:19] [build-stdout] [2/3] AR obj/chrome/browser/ui/libui.a
[2023-07-31 15:03:25] [build-stdout] [3/3] LINK ./chrome
Finalizing database at /home/bad/code_db/best_u.
Successfully created database at /home/bad/code_db/best_u.
bad@DESKTOP-ETKSDTV:~/chromium_src/src$ cp -r ../../code_db/best_u/ /mnt/d/code_db/chrome/
```

The log shows that I build the database successfully, But when I run query:

``` c++
import cpp

from BlockStmt bs
select bs, "Just a query"
```

I offer the database zip, u could got src file. but can't see ast . Anything I miss? Thank u.
[Uploading best_u.zip…]()

**Comment by 18Fl** [comment]
[build-tracer.log](https://github.com/github/codeql/files/12212465/build-tracer.log)
update the log file.

**Comment by 18Fl** [comment]
``` c++
"../../components/autofill/core/common/autofill_constants.h", line 75: error: expression must have a constant value
  constexpr base::TimeDelta kLimitBeforeRefill = base::Seconds(1);
                                                 ^
"../../base/numerics/safe_math_clang_gcc_impl.h", line 106: note: cannot call non-constexpr function "__builtin_mul_overflow" (declared implicitly)
                 : !__builtin_mul_overflow(x, y, result);
                    ^
"../../base/numerics/checked_math_impl.h", line 183: note: called from:
        return CheckedMulFastOp<T, U>::Do(x, y, result);
                                         ^
"../../base/numerics/clamped_math_impl.h", line 141: note: called from:
      return BASE_NUMERICS_LIKELY((CheckedMulOp<T, U>::Do(x, y, &result)))
                                                         ^
"../../base/numerics/clamped_math.h", line 157: note: called from:
          Math::template Do<T>(Wrapper<L>::value(lhs), Wrapper<R>::value(rhs)));
                              ^
"../../base/numerics/clamped_math.h", line 224: note: called from:
  BASE_NUMERIC_ARITHMETIC_OPERATORS(Clamped, Clamp, Mul, *, *=)
  ^
"../../base/time/time.h", line 897: note: called from:
    return TimeDelta::FromInternalValue(MakeClampedNum(n) *
```

Some error occurs, But I still could build the database success...

**Comment by 18Fl** [comment]
Hey, I  found this commit will make things happy [commit in 2023-02-17](https://chromium.googlesource.com/chromium/src/+/db8d30126406c71491b7fa5e9a0490f09287d10f). That's means , After the 2023-02-17, [Some commit](https://github.com/chromium/chromium/commits/main?after=766798f003a214ddac3335d2262bcb0f7bb1aa8c+34&branch=main&path%5B%5D=chrome&path%5B%5D=browser&path%5B%5D=ui&path%5B%5D=autofill&path%5B%5D=chrome_autofill_client.cc&qualified_name=refs%2Fheads%2Fmain) introduce new code , which include new grammer make codeql failed.

My basic idea IS use bitsec to find Which commit introduce the code. But it is too hard for me If I archive these by myself....

**Comment by smowton** [comment]
It looks from your logs like you're using CodeQL 2.13.1 -- I know our C++20 support has been improving with each release, so could you see if your problem is reproducible with the latest CLI from https://github.com/github/codeql-cli-binaries/releases ?

**Comment by smowton** [comment]
Aha, I see the crucial error:

```
CodeQL C++ extractor: Current location: ../../chrome/browser/ui/autofill/chrome_autofill_client.cc:643494,36
CodeQL C++ extractor: Current physical location: ../../ui/views/layout/layout_types.h:77,36
"../../ui/views/layout/layout_types.h", line 77: internal error: assertion failed: access check result needed immediately but access check deferral in effect (symbol_tbl.c, line 14002 in record_access_error)

  constexpr SizeBound::SizeBound() = default;
                                     ^

[E 14:56:46 1168] Warning[extractor-c++]: In construct_message: "../../ui/views/layout/layout_types.h", line 77: internal error: assertion failed: access check result needed immediately but access check deferral in effect (symbol_tbl.c, line 14002 in record_access_error)

  constexpr SizeBound::SizeBound() = default;
                                     ^


27 errors and 1 catastrophic error detected in the compilation of "../../chrome/browser/ui/autofill/chrome_autofill_client.cc".
Compilation aborted.
```

I'm afraid this is a known bug in the C/C++ extractor. We're aware of it and intend to fix, but the fix is nontrivial so I can't promise it will be fixed soon.

**Comment by 18Fl** [comment]
Auh, I know what u means, I will wait codeql team to solve it. Maybe I could change some code in chromium to make it works. Thank u!

**Comment by jketema** [comment]
We've fixed the catastrophic error. The fix should appear in CodeQL 2.14.4. We're still looking at the other that you reported here https://github.com/github/codeql/issues/13849#issuecomment-1657815708

**Comment by 18Fl** [comment]
> We've fixed the catastrophic error. The fix should appear in CodeQL 2.14.4. We're still looking at the other error that you reported in [#13849 (comment)](https://github.com/github/codeql/issues/13849#issuecomment-1657815708)

Good luck to see this. I only see codeql 2.14.2(last version), when time 2.14.4 will be public?

**Comment by jketema** [comment]
> when time 2.14.4 will be public?

That should be in about 3 weeks.

**Comment by 18Fl** [comment]
> > when time 2.14.4 will be public?
> 
> That should be in about 3 weeks.

I see 2.14.4 be updated. Unfortunately, It still miss some case (Datflow part) in chromium new database...

**Comment by jketema** [comment]
Hi @18Fl,

Do I understand correctly from your comment that there's code in the database now, and that you're now seeing problems with dataflow? If so, could you please open a new issue for the latter. The issue reported here seems resolved.

**Comment by jketema** [comment]
Closing this as resolved, given no further user feedback.
