### ISSUE TITLE
`codeql query run` and `codeql database analyze` produce different results

### ISSUE THREAD

**Issue by scottconstable** [github/codeql#14002]
Hi,

I have a simple QL query that looks for empty blocks in C/C++ code:
```
/** example.ql
 * @name Empty block
 * @kind problem
 * @problem.severity warning
 * @id cpp/example/empty-block
 */

import cpp

from BlockStmt b
where b.getNumStmt() = 0
select b, "This is an empty block."
```

I also have a simple test program with a single empty block. I'm building the database using:
```
$ codeql database create --language=cpp --threads=12 --command=ninja --source-root=build -- my-codeql-db
```
Then I can do `query run` and CodeQL finds the empty block in my test program:
```
$ codeql query run --database=my-codeql-db --threads=12 -- /home/scott/vscode-codeql-starter/codeql-custom-queries-cpp/example.ql
Compiling query plan for /home/scott/vscode-codeql-starter/codeql-custom-queries-cpp/example.ql.
[1/1] Found in cache: /home/scott/vscode-codeql-starter/codeql-custom-queries-cpp/example.ql.
example.ql: Evaluation completed (83ms).
|    b    |          col1           |
+---------+-------------------------+
| { ... } | This is an empty block. |
```

But when I run `database analyze` it doesn't find the empty block:
```
$ codeql database analyze my-codeql-db --format=csv --output=codeql-db-result.csv --threads=12 /home/scott/vscode-codeql-starter/codeql-custom-queries-cpp/example.ql; cat codeql-db-result.csv
Running queries.
[1/1] No need to rerun /home/scott/vscode-codeql-starter/codeql-custom-queries-cpp/example.ql.
Shutting down query evaluator.
Interpreting results.
```
I have also tried to export the output into other formats such as SARIF, but I still don't see the result that shows the empty block. I wonder if I am using `database analyze` incorrectly, or something else? I am using the CodeQL CLI 2.14.2.

**Update:** Since my original post, I noticed that `codeql database analyze` does write the expected result to the bqrs file, and I can see the result with `codeql bqrs decode`:
```
$ codeql bqrs decode codeql-db/results/getting-started/codeql-extra-queries-cpp/example.bqrs
|    b    |          col1           |
+---------+-------------------------+
| { ... } | This is an empty block. |
```
But I still cannot get this information into SARIF format. I also tried using `codeql database interpret-results`, but the result was the same as `codeql database analyze`.

**Comment by scottconstable** [comment]
Aha! I figured out the problem. My test program uses CMake, and I first configured CMake and then referred CodeQL to the `build` directory, e.g.:
```
$ cd <my-cmake-project>
$ mkdir build
$ cd build
$ cmake ..
$ cd ..
$ codeql database create --language=cpp --threads=12 --command=ninja --source-root=build -- my-codeql-db
```
But... if I instead run `codeql database create` with the autobuild, then `codeql database analyze` produces the expected output:
```
$ cd <my-cmake-project>
$ codeql database create --language=cpp --threads=12 -- my-codeql-db
$ codeql database analyze my-codeql-db --format=csv --output=codeql-db-result.csv --threads=12 /home/scott/vscode-codeql-starter/codeql-custom-queries-cpp/example.ql; cat codeql-db-result.csv
Running queries.
Compiling query plan for /home/scott/vscode-codeql-starter/codeql-custom-queries-cpp/example.ql.
[1/1] Found in cache: /home/scott/vscode-codeql-starter/codeql-custom-queries-cpp/example.ql.
example.ql: [1/1 eval 90ms] Results written to getting-started/codeql-extra-queries-cpp/example.bqrs.
Shutting down query evaluator.
Interpreting results.
"Empty block",,"warning","This is an empty block.","/main.c","47","12","48","5"
```
While I am glad that this is now working as expected, it does feel like a bug that `codeql database analyze` produces correct `.bqrs` output, yet incorrect SARIF/csv output when the database is created using `make` or `ninja` after being configured using `cmake`.

**Comment by aibaars** [comment]
`codeql database analyze` and the lower level `codeql database interpret-results` commands  report paths relative to the 'source root' folder and skip all results that are reported outside this folder. This makes it easier to map alert paths to paths in a repository and avoids reporting alerts in for example system header files located in `/usr/include`. The 'source root' folder is provided using the `--source-root` flag of `codeql database create` and stored in the `codeql-database.yml` file in the database. If you set the `--source-root` to the `build` folder, then the commands will work the way you need. You could also edit the `codeql-database.yml` file manually as a quick workaround. Finally you can use the very low-level `codeql bqrs interpret` with the `--source-location-prefix` flag.

**Comment by scottconstable** [comment]
Thank you @aibaars for the explanation. I do think that it would be helpful for the `codeql database analyze` and `codeql database interpret-results` commands to issue a warning when they cannot resolve *any* source paths and thus cannot generate any output. IMO, this is most likely to happens when someone (like me) is mis-using the CLI. I also think that it is unintuitive to require `--source-root` to point to the `build` folder. Most CMake users create `build` within the source root or as an entirely separate directory.

**Comment by aibaars** [comment]
@scottconstable You're right that it can be confusing. I believe CodeQL,  at a higher logging level, prints messages when it drops results. I think adding one or more `-v` options would work to make them visible. I usually turn up the verbosity level if things aren't working as expected.
