### ISSUE TITLE
Extend Kotlin support to version 1.9.10

### ISSUE THREAD

**Issue by sschuberth** [github/codeql#14046]
Currently, only up to Kotlin 1.9.0 is supported. Please extend support to include the recently released Kotlin 1.9.10.

**Comment by pcolby** [comment]
In particular, Dependabot has begun submitting PR's that fail against CodeQL, with:

```
com.semmle.extractor.java.interceptors.KotlinInterceptor$KotlinVersionTooRecentError:
Kotlin version 1.9.10 is too recent. CodeQL currently supports versions below 1.9.10
```

Thanks.

**Comment by mbg** [comment]
Hi @sschuberth and @pcolby! 

Thanks for raising this and sorry about the inconvenience. I have passed this on to the relevant team internally and they expect this to be resolved early next week.

**Comment by sschuberth** [comment]
Looks like this is [working now](https://github.com/oss-review-toolkit/ort/actions/runs/6016029588/job/16319193935?pr=7426#step:3:19) with [v2.14.3](https://github.com/github/codeql-cli-binaries/releases/tag/v2.14.3) even though not explicitly mentioned in the release notes.

**Comment by igfoo** [comment]
1.9.10 will now work with 2.14.3 for users of the codeql action (i.e. most people). For people using the CLI directly, it will work in the next release (2.14.4).
