### ISSUE TITLE
False positive,  cpp/compare-where-assign-meant

### ISSUE THREAD

**Issue by peternmartin** [github/codeql#14054]
Re: the [cpp/compare-where-assign-meant](https://github.com/github/codeql/blob/main/cpp/ql/src/Likely%20Bugs/Likely%20Typos/CompareWhereAssignMeant.ql) query:

This query highlights cases where the '==' operator may have been used accidentally, where '=' was probably intended.

However, I noticed that it produces quite a few results in test code - specifically, seemingly for code making use of the `gtest` framework, such as:
```cpp
#include <gtest/gtest.h>

// ...
    EXPECT_ANY_THROW(foo1.begin() == foo3.begin());
// or
    EXPECT_NO_THROW(option1 == option2);
```

I suspect the issue here is that (in some build modes at least), the preprocessor expands this macro such that the result of the comparison is never used.

I wondered: in the interest of making this query more precise, could it be changed to only report results where the comparison is not taking place within a macro expansion?

**Comment by MathiasVP** [comment]
Hi @peternmartin,

Thanks for raising this issue! Excluding reporting results when the comparison is not taking place within a macro sounds like a good idea. I've opened a PR that does exactly that: https://github.com/github/codeql/pull/14060 🙂.

Note: I see the title of the PR refers to `cpp/assign-where-compare-meant`, while the description refers to `cpp/compare-where-assign-meant` (which is probably the right one given the context of the issue).

**Comment by MathiasVP** [comment]
https://github.com/github/codeql/pull/14060 has been merged. I expect that it'll reach Code Scanning within ~2 weeks. Please let us know if this didn't fix your issues, and I'd be happy to look at this again!
