### ISSUE TITLE
Question 01: How to identify TempleClass

### ISSUE THREAD

**Issue by 18Fl** [github/codeql#14077]
Hey, I have a question about c++ smart pointer.

c++ often use smart pointer to manage a object life time:

``` c++
    void bad_function(){
        std::unique_ptr<BadBox> badbox = std::move(pass_box);
    }
```

at here, we manage a object lifetime , which  class type is `|BadBox|`. there should be a Destructor at the tail of function `bad_function`.

it should be like:

``` c++
    std::unique_ptr<Badbox, default_delete<Badbox>>::~unique_ptr
```

And I want to know which type has been freed by this destructor(Means `|Badbox|` at here).

I try to use this query:

``` sql
    from DestructorCall dec
    where dec.getEnclosingFunction.getQualifiedName().matches("%bad_function%")
    select dec.getAnExplicitTemplateArgumentKind(), "which class has been freed"
```

But I don't get any result, I also use another API which related about `template` in `|FunctioinCall|`. But I still can't get `|Badbox|`.

I use a very ugly way to archive this:

``` sql
    from Function magic_func, DestructorCall destructor, string destructor_full_name, Class target_class, string target_class_name
    where
    and destructor.getEnclosingFunction().getQualifiedName().matches("%bad_function")
    and destructor_full_name =  destructor.getTarget().getQualifiedName().toString()
    and target_class_name = target_class.getQualifiedName()
    and destructor_full_name.matches("%::unique_ptr<" + target_class_name + "%::~unique_ptr")
    select target_class, "A dangerous call at here $@", target_class, destructor_full_name
```

It works, It could make me know a `|Badbox|` been freed by this `smart pointer`. However, it is so ugly....

So my querstion is simple:

1. Is there another way to make me know `|Badbox|` been managed by this smart pointer?

Thx. :(

**Comment by MathiasVP** [comment]
Hi @18Fl,

I don't think you need to mess around with qualfiied names for this. How about the following:
```ql
import cpp

from DestructorCall call, Destructor d, ClassTemplateInstantiation cti, Class c
where
  d = call.getTarget() and // get the destructor being called (i.e., ~unique_ptr)
  cti = d.getDeclaringType() and // get the class that declares the destructor (i.e., unique_ptr<BadBox, default_delete<BadBox>>)
  c = cti.getTemplateArgument(0) // get the first template argument of unique_ptr (i.e., BadBox)
select call, d, cti, c
```
on your example this gives me:
```
| call to ~unique_ptr | ~unique_ptr | unique_ptr<BadBox, default_delete<BadBox>> | BadBox |
```

**Comment by 18Fl** [comment]
> Hi @18Fl,
> 
> I don't think you need to mess around with qualfiied names for this. How about the following:
> 
> ```ql
> import cpp
> 
> from DestructorCall call, Destructor d, ClassTemplateInstantiation cti, Class c
> where
>   d = call.getTarget() and // get the destructor being called (i.e., ~unique_ptr)
>   cti = d.getDeclaringType() and // get the class that declares the destructor (i.e., unique_ptr<BadBox, default_delete<BadBox>>)
>   c = cti.getTemplateArgument(0) // get the first template argument of unique_ptr (i.e., BadBox)
> select call, d, cti, c
> ```
> 
> on your example this gives me:
> 
> ```
> | call to ~unique_ptr | ~unique_ptr | unique_ptr<BadBox, default_delete<BadBox>> | BadBox |
> ```

Hey, I will check this when I have enough time. thx

**Comment by 18Fl** [comment]
> ```ql
> ClassTemplateInstantiation cti, Class c
> ```

Hey, I ensure this work well. Thx!
