### ISSUE TITLE
Question 00: How to identify a function call path.

### ISSUE THREAD

**Issue by 18Fl** [github/codeql#14076]
Hey, 3 months ago, my friend help me ask a question in github slack. But I don't get a enough answer :( .

If I have a demo code like this:

``` c++
#include <iostream>

int add1(int a, int b){
    free(o);
}
int add0(int a, int b){
    add1(a, b);
}
int add(int a, int b){
    add0(a, b);
}
int main(){
    add(3, 4);
    return 0;
}
```

If we define free a object is dangerous. we could define `add1` is dangerous. Again, we know `add` will call add1 finally, so we could define `add` is dangerous too.

To mark `add` is dangerous is so simple:

``` sql
    from Function from_, Function to_
    from_.getQualifiedName().matches("%add")
    and to_.getQualifiedName().matches("%free")
    and from_.calls+(to_)
    select from_, "u are dangerous"
```

But, think about this, If we prove `add` is dangerous, obviouly, we also want to know why it is dangerous. That meanes, I want to know which call path lead `add` be dangerous.

Here is :

``` c++
    add -> add0 -> add1 -> free
```

With study codeql 3 months, I think this query will work:

``` c++
    from Function from_, Function to_, Function mid
    from_.getQualifiedName().matches("%add")
    and to_.getQualifiedName().matches("%free")
    and from_.calls+(mid)
    and mid.calls+(to_)
    select mid, "u are call path function"
```

And thanks god, This query work well. It could identify function `add0` and `add1`. That means, We could know by this query:

>   we call add, then call add0, then call add1, finally we could call free, free is a dangerous function.

However, This query has a disadvantage, think about we have this call path:

```
    add -> add0 -> add1 -> free
    add -> add2 -> add1 -> free
    add -> add3 -> add1 -> free
    add -> add4 -> add1 -> free
```

The above query will give us these results:

```
    add0, add2, add3, add4, add1
```

We can't identify the path, only with this query, the path maybe is:

``` c++
    add -> add1 -> add2 -> add3 -> free
    etc
```

We just know related function, we still can't got the call path... With more complicated system, the query result will be too much...

So my querstion is simple:

1. Is there are a way to help me prove this query, then I could get the call path from `add` to `free`? 
2. Maybe codeql could offer a official API to archive this, I think it is very useful for bug hunting :( 

Thx!

**Comment by MathiasVP** [comment]
Let me check whether I understand your question. You're saying that the query:
```ql
from Function from_, Function to_, Function mid
where
  from_.getQualifiedName().matches("%add") and
  to_.getQualifiedName().matches("%free") and
  from_.calls+(mid) and
  mid.calls+(to_)
select mid, "u are call path function"
```
will find the results you care about (i.e., all functions that are in a path from a call to `add` to `free`).

And your question is then: How do you know the path that takes you from `add` to `free`?

If that's the case, the answer is pretty easy: You can define your own `path-problem` query to show you this. See https://codeql.github.com/docs/writing-codeql-queries/creating-path-queries/#defining-your-own-edges-predicate for this. In your example you can do something like:

```ql
/**
 * @kind path-problem
 */

import cpp

query predicate edges(Function f, Function g) { f.calls(g) }

from Function from_, Function to_
where
  from_.getQualifiedName().matches("%add") and
  to_.getQualifiedName().matches("%free") and
  from_.calls+(to_)
select to_, from_, to_, "u are call path function"
```
This will generate you a path similar to the paths you get in a dataflow query.

**Comment by 18Fl** [comment]
> Let me check whether I understand your question. You're saying that the query:
> 
> ```ql
> from Function from_, Function to_, Function mid
> where
>   from_.getQualifiedName().matches("%add") and
>   to_.getQualifiedName().matches("%free") and
>   from_.calls+(mid) and
>   mid.calls+(to_)
> select mid, "u are call path function"
> ```
> 
> will find the results you care about (i.e., all functions that are in a path from a call to `add` to `free`).
> 
> And your question is then: How do you know the path that takes you from `add` to `free`?
> 
> If that's the case, the answer is pretty easy: You can define your own `path-problem` query to show you this. See https://codeql.github.com/docs/writing-codeql-queries/creating-path-queries/#defining-your-own-edges-predicate for this. In your example you can do something like:
> 
> ```ql
> /**
>  * @kind path-problem
>  */
> 
> import cpp
> 
> query predicate edges(Function f, Function g) { f.calls(g) }
> 
> from Function from_, Function to_
> where
>   from_.getQualifiedName().matches("%add") and
>   to_.getQualifiedName().matches("%free") and
>   from_.calls+(to_)
> select to_, from_, to_, "u are call path function"
> ```
> 
> This will generate you a path similar to the paths you get in a dataflow query.

Hey, I will check this when I have enough time. Thx!

**Comment by 18Fl** [comment]
> ```ql
> /**
>  * @kind path-problem
>  */
> 
> import cpp
> 
> query predicate edges(Function f, Function g) { f.calls(g) }
> 
> from Function from_, Function to_
> where
>   from_.getQualifiedName().matches("%add") and
>   to_.getQualifiedName().matches("%free") and
>   from_.calls+(to_)
> select to_, from_, to_, "u are call path function"
> ```

Wow! It's so useful for me! Thank u very much!

**Comment by 18Fl** [comment]
Hey, @MathiasVP  Could I filter the call path the call path length. maybe I could get a call path, but if it is so long, like I need call a->b->.... ->d  If "..." including 10 function, which is too long for me, could I filter out this?

**Comment by MathiasVP** [comment]
Then you need to replace `from_.calls+(to_)` with a predicate that counts how many calls it takes to go from `from_` to `to_`.

**Comment by 18Fl** [comment]
Thx!

Mathias Vorreiter Pedersen ***@***.***> 于2023年10月10日周二
20:05写道：
