### ISSUE TITLE
How can I find the concrete implementation of TaintedPath.ql for path-injection vulnerability

### ISSUE THREAD

**Issue by flyboss** [github/codeql#14226]
Hello,

I'm currently trying to learn how to write CodeQL scripts to detect path injection vulnerabilities in Node.js applications. I've come across an example ql file called [TaintedPath.ql](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-022/TaintedPath.ql) provided by CodeQL. This script is used to address a path injection problem illustrated in this [example JavaScript file](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-022/examples/TaintedPath.js).

However, I'm having trouble understanding how this example ql file actually detects the path injection problem. I've inspected the `configuration` of TaintedPath.ql, but the definition I found [here](https://github.com/github/codeql/blob/d8fb875bbb368499f2763feed16b434e87899693/javascript/ql/lib/semmle/javascript/security/dataflow/TaintedPathQuery.qll#L25) doesn't seem to provide information related to the problem. I suspect that the actual detection rules might be defined elsewhere in the script, such as:

```
class MyConfig extends TaintTracking::Configuration {
  MyConfig() { this = "path injection" }
 
  override predicate isSource(DataFlow::Node node) {
      exists(DotExpr dotexpr |
        dotexpr.getBase().toString() = "req"
        and 
        dotexpr.getPropertyName() = "url"
        and 
        dotexpr = node.asExpr())
  }
 
  override predicate isSink(DataFlow::Node node) { 
    exists(CallExpr callexpr |
      callexpr = NodeJSLib::FS::moduleMember("readFileSync").getACall().asExpr()
      and
      node.asExpr() = callexpr.getArgument(0)
    )
  }
}

```

So, my first question is: How can I locate the concrete implementation of TaintedPath.ql to better understand how it works?

Additionally, I'm curious if CodeQL supports an execution mode similar to step-by-step debugging in JavaScript. I'm accustomed to using breakpoints and console.log to explore and understand JavaScript frameworks. If CodeQL doesn't support this kind of debugging, are there any alternative methods for gaining insights into the code analysis process?

**Comment by smowton** [comment]
The file TaintedPathQuery.qll that you linked does define the dataflow configuration you need, but given the definition:

```ql
  override predicate isSource(DataFlow::Node source, DataFlow::FlowLabel label) {
    label = source.(Source).getAFlowLabel()
  }
```

... clearly we need to know what `Source` is to find out what dataflow nodes are being considered sources.

In that file we have the import: `import TaintedPathCustomizations::TaintedPath`

That's where `Source` is coming from (hint: if you use the CodeQL VSCode plugin to browse QL source (https://codeql.github.com/docs/codeql-for-visual-studio-code/setting-up-codeql-in-visual-studio-code/) you could use jump-to-definition for this).

If you look in https://github.com/github/codeql/blob/d8fb875bbb368499f2763feed16b434e87899693/javascript/ql/lib/semmle/javascript/security/dataflow/TaintedPathCustomizations.qll you'll find that the abstract classes `Source`, `Sink`, `Barrier`, and the predicate `isAdditionalTaintedPathFlowStep` that define the meat of the dataflow configuration. The predicate directly states the flow steps involved (except for the default dataflow steps, like a variable definition flowing to a use of that variable). The abstract classes are defined by extending them -- look for `extends Source`, for example, as in:

```ql
  class RemoteFlowSourceAsSource extends Source {
    RemoteFlowSourceAsSource() {
      exists(RemoteFlowSource src |
        this = src and
        not src instanceof ClientSideRemoteFlowSource
      )
    }
  }
```

...which says that `RemoteFlowSource`, a class representing a query-neutral concept of anything controlled by a remote party, is considered a source for this query.

Regarding debugging, the best tool CodeQL has available is called "quick evaluation", which lets you evaluate an individual predicate or a sub-expression highlighted with the mouse -- see https://codeql.github.com/docs/codeql-for-visual-studio-code/analyzing-your-projects/#running-a-specific-part-of-a-query-or-library for more detail.

**Comment by flyboss** [comment]
Thanks a lot!

I have roughly understood how to find  the concrete implementation. Besides,  "quick evaluation"  is really helpful. It saves a lot of my time.
