### ISSUE TITLE
Java: SwitchCase expressions should implicitly break rather than fall through

### ISSUE THREAD

**Issue by wwong** [github/codeql#14332]
Java 14 added support for "arrow labels" on `case` statements, which change the completion behavior from fall-through to implicitly breaking. In some cases, it seems that CodeQL is treating these case statements as if they still implicitly fall through. I think it happens when there's no explicit statement to signal the "completion" of a case expression.

I'm not sure how many of the following conditions are necessary to trigger, but I've been able to reproduce it with this code sample where:
* SwitchStmt that does not return any value
* SwitchCase uses arrow labels (not the older colon labels)
* Normal SwitchCase expressions don't have an explicit completion (e.g. `break`, `return`, `throw`, or `yield`) at the end of their expressions, and therefore rely on the implicit `break`
* A DefaultCase throws and occurs at the end of a switch statement

Here's a code sample that reproduces that behavior:
```java
public class HelloWorld {

    public static void main(String[] args) {
        HelloWorld greeting = new HelloWorld();
        greeting.sayHiFiltered("Semmle");
    }

    void sayHiFiltered(String name) {
        String cmd;
        switch (name) {
            case "Semmle" -> { cmd = "odasa"; }
            case "GitHub" -> { cmd = "codeql"; }
            default -> throw new IllegalArgumentException("nope");
        }
        sayHi(name, cmd);
    }

    void sayHi(String name, String product) {
        System.out.print("Hello " + name + ". ");
        System.out.println("How is " + product + " doing?");
    }
}
```

I pushed a repro repo with a test case containing the results I would have expected if control flow had not fallen through. You can see the output of the test code and the codeql test in the latest Actions run:
https://github.com/wwong/codeql-repro/actions/runs/6334957888/job/17205336346#step:5:42

In cases where the cases fall through to a default case that throws an exception, CodeQL determines that the lines after the switch statement are unreachable, which has been causing some internal dataflow queries to return false positives.
![image](https://github.com/github/codeql/assets/1160302/58087471-1d84-456f-9ecb-7cd9ead74092)

It seems that there's already awareness of "arrow labels" in the libraries (there's even a [test class](https://github.com/github/codeql/blob/main/java/ql/test/library-tests/dataflow/switchexpr/TestSwitchExpr.java)), so I'm thinking the fix is going to be adding cases somewhere in  [ControlFlowGraph.qll](https://github.com/github/codeql/blob/10231e99cedde35590d8ab4722bfb2ade231c457/java/ql/lib/semmle/code/java/ControlFlowGraph.qll) to address the implicit `break` completions.

References:
* [JEP 361: Switch Expressions](https://openjdk.org/jeps/361)

**Comment by aschackmull** [comment]
Good catch! Thank you for this observation. It appears that we've mishandled the case when a case rule is in a switch statement as opposed to a switch expression. Since case rules were introduced in conjunction with switch expressions this combination apparently didn't get enough attention. I'll look into creating a test and a fix. Thanks again.

**Comment by aschackmull** [comment]
PR is up.
