### ISSUE TITLE
False positive: Incomplete multi-character sanitization 

### ISSUE THREAD

**Issue by KuroXI** [github/codeql#14504]
**Description of the false positive**

The system flagged the code for potential HTML injection vulnerabilities because it relies on regular expressions to remove HTML tags and (Source): strings.

**Code samples or links to source code**
```ts
function cleanDescription(description: string) : string {
  return description.replace(/\(Source:[\s\S]*$/g, '').replace(/<[^>]*>/g, '');
}
```

**URL to the alert on GitHub code scanning (optional)**
https://github.com/KuroXI/kurebiverse-fe/security/code-scanning/3

Hi, I'm not actually familiar with those vulnerabilities, and I'm not an expert about them. I just want to ask how this gets flagged to HTML Injection if I'm removing the HTML tag.

**Comment by KuroXI** [comment]
Also, if I dismiss the alert and push a commit again with the same code attached to it, is it still going to flag the dismiss alert or not?

**Comment by jketema** [comment]
Hi @KuroXI,

Thanks for your question.

> I'm not actually familiar with those vulnerabilities, and I'm not an expert about them. I just want to ask how this gets flagged to HTML Injection if I'm removing the HTML tag.

I've asked the relevant engineering team about this.

> Also, if I dismiss the alert and push a commit again with the same code attached to it, is it still going to flag the dismiss alert or not?

I'm not sure what you mean by "with the same code attached". Do you mean that you re-introduce the code in the commit, or that it's still there in unchanged form? If you re-introduce the code, it'll be flagged up again. If the code is still there in unchanged form, code scanning should be smart enough to no re-open the dismissed alert.

**Comment by KuroXI** [comment]
Hi @jketema 

Thank you for responding. I think the code really does have a vulnerability because I also scanned it with SonarCloud and it has the same vulnerability.
