### ISSUE TITLE
java code scanning failed

### ISSUE THREAD

**Issue by yangyepope** [github/codeql#14549]
**Description of the issue**
java code scanning failed

1. [1/122] Found in cache: D:\02-codeQL\CodeQL\ql\codeql\java\ql\src\Security\CWE\CWE-020\ExternalAPIsUsedWithUntrustedData.ql.
Compiling query plan for D:\02-codeQL\CodeQL\ql\codeql\java\ql\src\Security\CWE\CWE-020\OverlyLargeRange.ql.
ERROR: codePointAt(int) cannot be resolved for type string (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:22,34-45)
ERROR: codePointAt(int) cannot be resolved for type string (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:60,16-27)
ERROR: codePointAt(_) cannot be resolved for type string (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:70,45-56)
ERROR: codePointCount(int, int) cannot be resolved for type string (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:76,51-65)
ERROR: 'i' is not bound to a value. (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:21,12-17)
ERROR: 'charIndex' is not bound to a value. (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:59,30-43)
PS D:\02-codeQL\CodeQL>

2.  [1/122] Found in cache: D:\02-codeQL\CodeQL\ql\codeql\java\ql\src\Security\CWE\CWE-020\ExternalAPIsUsedWithUntrustedData.ql.
Compiling query plan for D:\02-codeQL\CodeQL\ql\codeql\java\ql\src\Security\CWE\CWE-020\OverlyLargeRange.ql.
ERROR: codePointAt(int) cannot be resolved for type string (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:22,34-45)
ERROR: codePointAt(int) cannot be resolved for type string (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:60,16-27)
ERROR: codePointAt(_) cannot be resolved for type string (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:70,45-56)
ERROR: codePointCount(int, int) cannot be resolved for type string (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:76,51-65)
ERROR: 'i' is not bound to a value. (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:21,12-17)
ERROR: 'charIndex' is not bound to a value. (D:\02-codeQL\CodeQL\ql\codeql\shared\util\codeql\util\Strings.qll:59,30-43)
PS D:\02-codeQL\CodeQL>

**Comment by aibaars** [comment]
The `codePointAt` method  is a very recent addition to the QL language. It was introduced in version 2.15.0, so you need to upgrade your CodeQL version. See also: https://github.com/github/codeql-cli-binaries/releases/tag/v2.15.0

**Comment by yangyepope** [comment]
Thank you, i'll will try it now.

**Comment by yangyepope** [comment]
> The `codePointAt` method is a very recent addition to the QL language. It was introduced in version 2.15.0, so you need to upgrade your CodeQL version. See also: https://github.com/github/codeql-cli-binaries/releases/tag/v2.15.0

there was a new error,as follow;
A fatal error occurred: Could not process query metadata for D:\02-codeQL\CodeQL\codeql-main\java\ql\src\Security\CWE\CWE-020\ExternalAPIsUsedWithUntrustedData.ql.
Error was: Unknown kind "Table". [UNSUPPORTED_KIND]

**Comment by aibaars** [comment]
You should not run that query with `codeql database analyze` because it cannot render query results of type `table` as alerts in SARIF output. You probably want to skip that query. If you really want to run it consider using [`codeql query run`](https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/query-run)

**Comment by yangyepope** [comment]
copy that
