### ISSUE TITLE
JavaScript: ERROR: No higher-order predicate with name scoreEndpoints

### ISSUE THREAD

**Issue by AnnAngela** [github/codeql#14557]
There is an error when running queries for javascript: https://github.com/MaaAssistantArknights/MaaRelease/actions/runs/6607581545/job/17945160860#step:4:735

```
Error: Error running analysis for javascript: Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.15.1/x64/codeql/codeql database run-queries --ram=5897 --threads=2 /home/runner/work/_temp/codeql_databases/javascript --min-disk-free=1024 -v --expect-discarded-cache --no-intra-layer-parallelism". Exit code was 2 and last log line was: ERROR: No higher-order predicate with name scoreEndpoints (/home/runner/.codeql/packages/codeql/javascript-experimental-atm-queries/0.4.9/.codeql/libraries/codeql/javascript-experimental-atm-lib/0.4.9/experimental/adaptivethreatmodeling/EndpointScoring.qll:39,5-19).
```

If any thing else is needed, please let me know.

**Comment by AnnAngela** [comment]
Same error in another repo: https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/actions/runs/6600247298/job/17930052660#step:4:856

**Comment by jketema** [comment]
You'll need to remove the following line from your CodeQL config: https://github.com/MaaAssistantArknights/MaaRelease/blob/main/.github/codeql-config.yaml#L5

The experimental queries enabled on that line are no longer supported.
