### ISSUE TITLE
Cannot decode bqrs file properly to get functions list

### ISSUE THREAD

**Issue by nagarrianharshit** [github/codeql#14586]
I am trying to run a query on my javascript codebase : 
`import javascript
from Function f where f.getBody().toString().length()>4 select f`
using the VS code it gives me proper results in results window with a list of functions.

But when I am trying to run the commands :

```
codeql query run --database=CalculatorDB  --output=result.bqrs -- query.ql
codeql bqrs decode --output=finalResult  -- result.bqrs
```

I get the output inside finalResult file:
```
|           f            |
+------------------------+
| functio ... \n  }\r\n} |
| () => { ... \r\n    }  |
| functio ... \n  }\r\n} |
| () => { ... ";\r\n  }  |
| functio ... lue;\r\n}  |
| functio ... \n  }\r\n} |
| functio ... his); }    |
| functio ... n ''; }    |
| functio ... null; }    |
| functio ... null; }    |
| functio ... null; }    |
| functio ... rn 0; }    |
| functio ... rn 0; }    |
| functio ... null; }    |
```

I cannot read a single function and also cannot send it to the application I am trying to integrate with codeql

**Comment by smowton** [comment]
In general the CodeQL database does not contain the source of a file, class, function etc. It does however have the file coordinates where they can be found.

For example, try:

```ql
import javascript

from Function f, Location l
where f.getBody().toString().length() > 4 and l = f.getLocation()
select f, l.getFile().getAbsolutePath(), l.getStartLine(), l.getStartColumn(), l.getEndLine(),
  l.getEndColumn()
```

That will give you the file coordinates to retrieve the full function text from the program source.

**Comment by nagarrianharshit** [comment]
Thanks a lot @smowton & @aibaars  for the support!
