### ISSUE TITLE
codeql_cpp QL pack not found

### ISSUE THREAD

**Issue by nssathyan** [github/codeql#14917]
**Description of the issue**
Hello,

I am new to CodeQL and was able to create a database for the windows driver certification project that I am working on.  However,  when I try to analyze the VC project, I get this error:

A fatal error occurred: The QL pack 'codeql-cpp' which is referenced from C:\codeql_home\codeql\Windows-Driver-Developer-Supplemental-Tools\codeql\windows-drivers\suites\windows_driver_mustfix.qls cannot be found.

Please help.

**Comment by jketema** [comment]
Note that driver certification has some very specific requirements with regard to the CodeQL version. So, in addition to the above question. Did you follow the instructions from https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/static-tools-and-codeql, or did you do something else. If you did something else, what did you do?

**Comment by qky7** [comment]
> Thank you for inputs. I installed the right version bundle for the driver certification and was able to run the queries.
> 
> Thanks, Sathya.

Hello, I also get this problem recently.Could you please share the right version detail bundle? I would very appreciate if you could give me some guidance.

**Comment by jketema** [comment]
> > Thank you for inputs. I installed the right version bundle for the driver certification and was able to run the queries.
> > Thanks, Sathya.
> 
> Hello, I also get this problem recently.Could you please share the right version detail bundle? I would very appreciate if you could give me some guidance.

See https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/static-tools-and-codeql

**Comment by jketema** [comment]
Could you please open a new issue for this, then someone will able to help you. Thanks.

**Comment by qky7** [comment]
> Could you please open a new issue for this, then someone will able to help you. Thanks.

Thanks for your advice.It's my first time use github.Thank you very much for taking the time to reply me.
