### ISSUE TITLE
Wrong Pointer Size in Database for Chromium

### ISSUE THREAD

**Issue by creative16** [github/codeql#14914]
**Wrong Pointer Size in CodeQL Database for Chromium on Windows**

Building a CodeQL database on Windows 10 x64 resulted in the database having the wrong size for most of the pointer types (expected size 8, got size 4). This also results in the size of classes and offsets of fields being wrong.

The details of the build are as follows:

OS: Windows 10 Build 19045.3693, x64
Visual Studio: 2022 Version 17.7.5
Chromium commit: 1fdd9778b8eec789b24035f306aca43d5dad90a7

Build setup command:
```
gn gen out\Chrome --args="is_component_build = false is_debug = false enable_nacl = false symbol_level = 0 blink_symbol_level = 0 v8_symbol_level = 0 target_cpu = \"x64\" target_os \"win\""
```

Database build command:
```
codeql database create <database_name> --language=cpp --command="ninja -C out\Chrome chrome -j 6"
```

**Comment by jketema** [comment]
Hi @creative16,

Thanks for your report. We are aware that there are problems with creating databases for Chromium, especially on Windows. I've added this to our internal tracking issue.

**Comment by jketema** [comment]
Hi @creative16,

CodeQL 2.16.3 - to be released in a few weeks - will include some changes that might fix this issue. It would be great if you could try that version once released. Otherwise, please provide a query with which you observed the issue, so we can try to see for ourselves.

**Comment by creative16** [comment]
Hello @jketema,

just tried CodeQL 2.16.3 and verified that the issue was fixed. Thanks so much!

**Comment by jketema** [comment]
Thanks for letting us know. Much appreciated.
