### ISSUE TITLE
Documentation for model YML files

### ISSUE THREAD

**Issue by ebickle** [github/codeql#14920]
**Description of the issue**

Is there any documentation or information on the syntax for CodeQL model yaml files? In particular, I was trying to figure out what the boolean parameter in the third position was:
```
- ["com.google.gson", "JsonElement", True, "getAsByte", "()", "", "Argument[this]", "ReturnValue", "taint", "manual"]
```

It's `True` or `False` in the official CodeQL model files The model editor within the VS Code extension seems to always insert `true` (lowercase).

**Comment by ebickle** [comment]
Found my own answer after posting this - leaving a comment in here in case it's helpful for someone else:
https://github.com/github/codeql/blob/f05c86239f8e50de3ab817b0bea14530266a4412/docs/codeql/codeql-language-guides/customizing-library-models-for-java-and-kotlin.rst

> The third value True is a flag that indicates whether or not the sink also applies to all overrides of the method.

The boolean parameter controls whether the model applies to subclasses as well as the specified type.

**Comment by jketema** [comment]
Hi @ebickle,

We haven't published a full specification yet. You indeed found the current publicly available documentation in your own answer. For a rendered and up-to-date version of the document you link to, see https://codeql.github.com/docs/codeql-language-guides/customizing-library-models-for-java-and-kotlin/#examples-of-custom-model-definitions
