### ISSUE TITLE
Question: False positive in Path traversal - Java

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#14922]
Hello, I'm facing a false positive in path traversal with the following code  : 

```
 public String doSomething(ArgType arg1, SinkType sink1) {
        if (!Util.isValidFilename(sink1.getFilename())) {
            throw new ServiceException();
        }
        Path testPath = Paths.get(sink1.getFilename());
```

isValidFilename definition : 

```
    static boolean isValidFilename(String filename) {
        if (filename.contains("/") || filename.contains("\\")) {
            return false;
        }
        return true;
    }
}
```

basically the isValidFilename method doesn't cut the flow when it reaches `Util.isValidFilename(sink1.getFilename())`. Do you know how I can add some customizations to PathSanitizer so that it takes into consideration this case. 
I have tried things like 
```
class ContainsSanitizer extends PathInjectionSanitizer {
  ContainsSanitizer() {
     exists(MethodCall ma| 
      
      ma.getMethod().getName() = "contains" and ma = this.asExpr() and isDisallowedWord(ma.getArgument(0)) )

  }
}
``` 
this doesn't work as well. 

Appreciate any pointers

**Comment by chmodxxx** [comment]
From my quick understanding looks like this predicate is not working here in this case 
```
private predicate blockListGuard(Guard g, Expr e, boolean branch) {
  branch = false and
  // Local taint-flow is used here to handle cases where the validated expression comes from the
  // expression reaching the sink, but it's not the same one, e.g.:
  //  File file = source();
  //  String strPath = file.getCanonicalPath();
  //  if (!strPath.contains("..") && !strPath.startsWith("/dangerous/dir"))
  //    sink(file);
  g instanceof BlockListGuard and
  localTaintFlowToPathGuard(e, g) and
  exists(Expr previousGuard |
    localTaintFlowToPathGuard(previousGuard.(PathNormalizeSanitizer), g)
    or
    previousGuard
        .(PathTraversalGuard)
        .controls(g.getBasicBlock(), previousGuard.(PathTraversalGuard).getBranch())
  )
}
```
since it's not a localtaintflow, please correct me if i'm wrong

**Comment by jketema** [comment]
Hi @chmodxxx,

Thanks for your question. I've asked someone who is in the known aboyt this to weigh in on your question.

**Comment by atorralba** [comment]
The part about `getFilename()` was my assumption as to how the out-of-the-box path injection query could be finding results in this codebase. Not needed for the sanitization part.

If you don't follow my advice about writing a barrier guard around `isValidFilename`, and decide to go the route of trying to dynamically figure out that it's a validation method by tracking flow into `contains`, you'll run into several problems, as I explained in my comment above. If you do it, let us know how it goes! :)

**Comment by chmodxxx** [comment]
Thanks @atorralba
