### ISSUE TITLE
Missing methods and constructors in Java GSON model 

### ISSUE THREAD

**Issue by ebickle** [github/codeql#14924]
**Description of the issue**

[com.google.gson.model.yml](https://github.com/github/codeql/blob/main/java/ql/lib/ext/com.google.gson.model.yml) is missing some constructors and methods that cause some security vulnerabilities to be missed by CodeQL.

* The [com.google.gson.stream.JsonReader](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/stream/JsonReader.html#%3Cinit%3E(java.io.Reader)) and [com.google.gson.stream.JsonWriter](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/stream/JsonWriter.html#%3Cinit%3E(java.io.Writer)) constructors. CodeQL already supports the `Gson.newJsonReader` and `Gson.newJsonWriter` helper methods, but not the lower level direct instantiation.
* The `getAsJsonArray`, `getAsJsonObject`, and `getAsJsonPrimitive` overloads on [com.google.gson.JsonObject](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonObject.html) that accept a String as argument 0 are missing. These are helper methods that can access a child property directly as a GSON type. CodeQL already supports these methods without arguments on the base `JsonElement` type.
* The `parseReader` and `parseString` methods on [com.google.gson.JsonParser](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonParser.html). These are lower level functions that directly parse JSON and allow it to be traversed.

These were discovered by using the new Visual Studio Code Model Editor plugin and uncovered an issue or two in our code. Shout out to the team for writing that new UI - it's a fantastic tool!

**Comment by jketema** [comment]
Hi @ebickle,

I've forwarded your observation to the relevant engineering team. I was going to suggest that you can can open a PR to add the mentioned methods and constructors, but it seems you already have opened a draft PR.
