### ISSUE TITLE
CodeQL reporting 0 lines of c# code in a simple action

### ISSUE THREAD

**Issue by andrewgbell** [github/codeql#14951]
Hi, we have purchased GHAS and are running it on various actions.  Most appear to run fine, however we're having problems with some of our compiled languages.

We have a fairly simple action to dotnet restore then dotnet build a c# project, but it reports 0 lines of c# code.  The project builds without issue.

I have the debug artifact in case of use (it's a closed source project so not entirely sure what the artifact contains), but is there anything that could be causing this?

An eg. of the yaml is below for the action:

      - uses: actions/checkout@v4
        
      - name: Restore dependencies
        run: dotnet restore blah/blah.sln

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
          debug: true

      - name: Build Scriptdbs
        run: dotnet build blah/blah.sln --configuration release --verbosity normal

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

And returns CodeQL scanned 0 out of 7515 C# files (there are a lot of projects in the repo).  Any ideas?

**Comment by jketema** [comment]
Hi @andrewgbell,

Thanks for your question. It's a bit hard to tell from the information that you provide to diagnose what is happening, and the debug artifacts would be useful. Normally a debug artifact would contain all the source code, which you likely do not want to share. However, in this case I don't expect there to be any.

I see two options:

* Download the artifacts, and only share the logs files with us that are part of each artifact. Before you share them, remove any information they might contain that you don't want to share.
* Go through support by [creating a support ticket](https://docs.github.com/en/support/contacting-github-support/creating-a-support-ticket). The support engineers have tools that allow them to see what is going on in you private repos after you have given them permission to do so.

**Comment by jketema** [comment]
Just to confirm. Our [documentation suggests](https://docs.github.com/en/code-security/codeql-cli/getting-started-with-the-codeql-cli/preparing-your-code-for-codeql-analysis#specifying-build-commands) to build with `/t:rebuild`. Did you try that?

**Comment by andrewgbell** [comment]
> Just to confirm. Our [documentation suggests](https://docs.github.com/en/code-security/codeql-cli/getting-started-with-the-codeql-cli/preparing-your-code-for-codeql-analysis#specifying-build-commands) to build with `/t:rebuild`. Did you try that?

Hi, we run these on github hosted runners so its built from scratch each time.
