### ISSUE TITLE
codeql can't handle chromium dataflow

### ISSUE THREAD

**Issue by 18Fl** [github/codeql#14973]
Hey, sir, sorry for bother u. When I use codeql, I meet a problem.

And I suspect this is a codeql bug... So...

In short to say:

>   1. If I build a database by delete file `[a.cpp, b.cpp]`, run query file `fun.ql`, it will give me a result which I want.
>   2. If I build a database by delete file `[a.cpp, b.cpp, c.cpp, d.cpp]`, run query file `fun.ql`(same query as before), `It won't generate any result...`

##  details

In chromium database, there are this code:

```
//  components\image_fetcher\core\image_fetcher_impl.cc
void ImageFetcherImpl::OnImageURLFetched(const GURL& image_url,
                                         ImageFetcherParams params,
                                         const std::string& image_data,
                                         const RequestMetadata& metadata) {
  [...]
  image_decoder_->DecodeImage(  //  [+] @a
      image_data, params.frame_size(), params.data_decoder(),
      base::BindOnce(&ImageFetcherImpl::OnImageDecoded, 
                     weak_ptr_factory_.GetWeakPtr(), image_url, metadata));
}
```

And at @a, the function will finnaly call this:

```
//  chrome\browser\image_fetcher\image_decoder_impl.cc
void ImageDecoderImpl::DecodeImage(
    const std::string& image_data,
    const gfx::Size& desired_image_frame_size,
    data_decoder::DataDecoder* data_decoder,
    image_fetcher::ImageDecodedCallback callback) {
  std::unique_ptr<DecodeImageRequest> decode_image_request( // [+] @b
      new DecodeImageRequest(this, data_decoder, std::move(callback)));
}

  DecodeImageRequest(ImageDecoderImpl* decoder,
                     data_decoder::DataDecoder* data_decoder,
                     image_fetcher::ImageDecodedCallback callback)
      : ImageRequest(data_decoder),
        decoder_(decoder),
        callback_(std::move(callback)) {}   //  [+] @c
```

And I want to write a query which will finnaly find there are a flow could pass `|base::BindOnce(@a)|` to `|callback_@c|`. 

So I write a query (the attachment my_query).

I delete these files and regenerate chromium to build a database(named less_work_demo). my query will work!

```
rm -rf \
  out/codeql/obj/components/image_fetcher/core/core/image_fetcher_impl.o \
  out/codeql/obj/chrome/browser/image_fetcher/image_fetcher/image_decoder_impl.o
```

However, If I detete more files(the database named more_work_demo), and use same query, and the query will be failed...

```
rm -rf \
  out/codeql/obj/components/image_fetcher/core/core/image_fetcher_impl.o \
  out/codeql/obj/chrome/browser/image_fetcher/image_fetcher/image_decoder_impl.o \
  out/codeql/obj/chrome/browser/ui/ui/account_selection_bubble_view.o \
  out/codeql/obj/chrome/browser/image_decoder/image_decoder/image_decoder.o \
```

It is a strange behaviour... Which I can't solve it by myself... So could u look into it? Thx!

##  additional information

Here is some information which I know.

My build chromium version is :

```
commit e8338962c5e9cf7b12650429997011aa4d8b0b6d (HEAD, origin/main, origin/HEAD)
Author: Mohamed Amir Yosef <mamir@chromium.org>
Date:   Wed Nov 15 14:29:00 2023 +0000

    [Passwords] ProcessIncomingSharingInvitationTask takes PasswordForm

    Before this CL:
    ProcessIncomingSharingInvitationTask processed an incoming password
    sharing invitation to decide with it can be approved.

    After this CL:
    ProcessIncomingSharingInvitationTask processes an incoming password
    form instead of an invitation. The invitation is converted to a
    password form before passing it over to the task.

    This will make follow-up patches that will allow the invitation to
    carry multiple passwords easier to implement by spawning a new task
    per password form.

    This is a mechanical change.

    Bug: 1448235
    Change-Id: Id5710d5172d2fa3418fe462e811f77b63465a6d7
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5032395
    Reviewed-by: Rushan Suleymanov <rushans@google.com>
    Commit-Queue: Mohamed Amir Yosef <mamir@chromium.org>
    Cr-Commit-Position: refs/heads/main@{#1224907}
```

And I attach the related file in [google driver](https://drive.google.com/drive/folders/1qCiNVq-_li1u-oaYoR-kHaMdwoYh_CXv?usp=sharing)... U could download it...

1. less_work_demo, it is a database which my query can work.
2. more_work_demo, it is a database which my query can't work.
3. my_query, it is my query, u could run FunnyExample.ql to run a query.

And I test this in 2.14.4 and 2.15.3, they both will be failed.

and here is my codeql build shell:

```
# build dir
BUILD_DIR="../../code_db/more_work_demo"

# the command
rm -rf \
  out/codeql/obj/components/image_fetcher/core/core/image_fetcher_impl.o \
  out/codeql/obj/chrome/browser/image_fetcher/image_fetcher/image_decoder_impl.o \
  out/codeql/obj/chrome/browser/ui/ui/account_selection_bubble_view.o \
  out/codeql/obj/chrome/browser/image_decoder/image_decoder/image_decoder.o \
&& mkdir $BUILD_DIR \
&& codeql database create $BUILD_DIR \
    -J-Xmx40G --overwrite --language=cpp \
    --command='ninja -j10 -C out/codeql chrome'

```

**Comment by jketema** [comment]
Hi @18Fl ,

Could you share the `build-tracer.log` files for both databases?

**Comment by 18Fl** [comment]
> getALinkTarget

Hey, I try to use this query, but seems it is not right...

``` sql
import cpp

from Function to_func
where 
to_func.getQualifiedName().matches("%ImageDecoderImpl::DecodeImage") 

select to_func, "show me the result. $@", 
to_func.getALinkTarget(), to_func.getALinkTarget().toString()
```
Would u tell me how to use `|getALinkTarget|`? 😢 . Thx!

**Comment by jketema** [comment]
You want to do something like:
```ql
import cpp

from Function f
where f.getQualifiedName().matches("%ImageDecoderImpl::DecodeImage") 
select f, f.getALinkTarget()
```
Note that there many not be any results.

**Comment by jketema** [comment]
Thanks. So what you're observing is expected behaviour. The files you deleted are somehow part of two binary objects (exe or dll) that are being built as part of Chromium, where one is getting linked, but the other is not. In the database we try to partition different binaries, as this avoids many spurious alerts.

**Comment by 18Fl** [comment]
> Thanks. So what you're observing is expected behaviour. The files you deleted are somehow part of two binary objects (exe or dll) that are being built as part of Chromium, where one is getting linked, but the other is not. In the database we try to partition different binaries, as this avoids many spurious alerts.

Thanks for your reply! But I still can't understand this...

> 1. If I build a database by delete file [a.cpp, b.cpp], run query file fun.ql, it will give me a result which I want.
> 2. If I build a database by delete file [a.cpp, b.cpp, c.cpp, d.cpp], run query file fun.ql(same query as before), It won't generate any result...

If there are a way to solve it?

**Comment by 18Fl** [comment]
> > Thanks. So what you're observing is expected behaviour. The files you deleted are somehow part of two binary objects (exe or dll) that are being built as part of Chromium, where one is getting linked, but the other is not. In the database we try to partition different binaries, as this avoids many spurious alerts.
> 
> Thanks for your reply! But I still can't understand this...
> 
> > 1. If I build a database by delete file [a.cpp, b.cpp], run query file fun.ql, it will give me a result which I want.
> > 2. If I build a database by delete file [a.cpp, b.cpp, c.cpp, d.cpp], run query file fun.ql(same query as before), It won't generate any result...
> 
> If there are a way to solve it?

I mean... add file should give me more result, instead of reduce my original result?

**Comment by jketema** [comment]
That will very much depend on your query. If there are there are some conditions in there to exclude results, then those might trigger in the larger database, but not in the smaller one, which could give you less results.

**Comment by 18Fl** [comment]
hey, @jketema , thx for your reply, here is my query:
``` cpp
import cpp

class CustomOverWriteFunction extends Function{
    /**
     * [+] custom_calls will query does this function call |f|. 
     *     I overwrite this because I want it could be :
     *          =>  (*) It could hold virtual function call
     *          =>  (*) It could hold step
     */
    predicate custom_calls(Function f) {
        //  [+] hold custom calls
        this.calls(f)    
        
        //  [+] How to handle virtual calls... and here is my algorithm
        //          =>  (*) find the virtual_base function which point to f
        //          =>  (*) ensure this call |virtual_base|
        or exists(CustomOverWriteFunction virtual_base | 
            this.calls(virtual_base) and
            virtual_base.isVirtual() and
            f.(MemberFunction).overrides(virtual_base)
            //  [+] here should be |calls| or |custom_calls|?
        )
    }
}

from CustomOverWriteFunction custom, Function target
where
custom.getQualifiedName().matches("%ImageFetcherImpl::OnImageURLFetched")
and target.getQualifiedName().matches("%::DecodeImageRequest")
and custom.custom_calls+(target)
select custom,  "here is the target $@", target,target.toString()
```

Here is my thought about this:
1. The code is simple, codeql has calls, but it didn't support virtual call. so I add it by myself.
2. I try to use codeql to prove ImageFetcherImpl::OnImageURLFetched will finally call `|DecodeImageRequest::DecodeImageRequest|`.
3. It works in `|less_work_demo|`, but doesn't work in `|more_work_demo|`. 

Any suggestion, Thx! 😄

**Comment by 18Fl** [comment]
> My suggestion would be to look at some of the intermediate results of this query using the quick evaluation function of the VSCode CodeQL extension. That should give you a better understanding of what is going on.

ok, thank u very much!
