### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by Sim4n6** [github/codeql#15018]
I am getting this exceptio raised while analyzing a database.

This is due to: 

```java
                      com.semmle.inmemory.caching.TuplePool$ComplexNumberer.saveToFile(TuplePool.java:589)
```

and 

```
java.nio.file.FileSystemException: /home/sim4n6/Sec/dbs/py_ai/db-python/default/cache/cached-strings/tuple-pool/tuples#DataFlowImpl#248dabc3--MakeImpl-DataFlowImplSpecific#9c24d182--PythonDataFlow---Impl-TaintTracking#f6f2598d--TaintFlowM-1d70beab#0#tttttt: File name too long
```

It seems that the saving of the cache somehow reached a limit of the filename length.
Any idea how to fix this ?

**Comment by Sim4n6** [comment]
```bash
cat /usr/include/linux/limits.h | grep "PATH_MAX"
#define PATH_MAX        4096	/* # chars in a path name including nul */
```

**Comment by smowton** [comment]
That 143 character file name shouldn't be a problem usually -- are you using an encrypted filesystem, which can increase the actual fillename length on the underlying filesystem, perhaps getting close to the usual 255 character limit? Can you try making your database on an unencrypted volume?

**Comment by Sim4n6** [comment]
Encrypted maybe ... did not check. I can't switch from the actual hd. (The db is the repo apache/airflow)

**Comment by Sim4n6** [comment]
encrypted indeed, can"t switch. any workaround please?

**Comment by smowton** [comment]
I've asked the team to look at reducing the maximum length -- in the meantime your best option if your only filesystem is encrypted would be to create a temporary filesystem to run codeql.

If the database is quite small and main memory is plentiful, this could just be a `tmpfs`:

```
mount -t tmpfs tmpfs -o size=4G /ramdisk
```

(You might already have a tmpfs `/tmp` of course -- run `mount` to check)

Or if you need more space, you could use a loop mount of a file stored in your main filesystem (with a bit of a performance problem due to the layering):

```
dd if=/dev/zero of=~/myfs bs=1M count=4096
mkfs.ext4 ~/myfs
mount ~/myfs /codeql-working-dir
```

**Comment by Sim4n6** [comment]
I see what you did. The first solution consists of creating a temporary file system **in memory** and mounting it at the /ramdisk dir. And then I set up the DB in there to work on from. The second solution would be to create a big file, formatted to ext4 fs, then mount it to a dir for use as an unencrypted storage location on a layer of encrypted fs.

Please confirm that this is what you suggested.

I went a bit of a different road. The"`/home/sim4n6/Sec/dbs/py_ai`" path part was mine-controlled. I reduced it a bit ... and I was running a full .qls from CLI, I switched to VSCode ext use with a more granular query running. 

Thank you man 
@Sim4n6

**Comment by smowton** [comment]
Yes that summary of the suggestions is right. Removing the path prefix won't help -- it's the individual file name that is limited to 143 bytes if we're running on ecryptfs -- but more granular queries likely will by not happening to generate the specific predicate that tipped us over the length limit.
