### ISSUE TITLE
False positive: java/ognl-injection incorrectly treating args parameters as injection sinks

### ISSUE THREAD

**Issue by ebickle** [github/codeql#15053]
**Description of the false positive**

CodeQL may be incorrectly treating the `args` parameter of the overloads for the Apache Struts 2 `com.opensymphony.xwork2.TextProvider` interface as OGNL injection sinks. Although the `key` and `defaultValue` parameters are definitely sinks for OGNL injection (code execution), I don't believe the `args` or `obj` parameters are.

The abstract base class implementation of `TextProvider` in Apache Struts 2 calls `TextParseUtil.translateVariables`, which in turn executes OGNL. If you look at the [implementation](https://github.com/apache/struts/blob/6fcb50122d381b2f2fe5133a95b5898b58614136/core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java#L201C17-L201C17) you can see that `translateVariables` is called on the key (`aTextName`, which `defaultValue` also flows into). The result of that call, which evaluates OGNL, is then used as the format string which `args` flows into. 

In other words, the `args` for the format string are used after the OGNL injection, not before. In other words, `args` is not an OGNL injection sink. In addition, the `String obj` parameter of `TextProvider.getText` flows into `args` [as seen here](https://github.com/apache/struts/blob/6fcb50122d381b2f2fe5133a95b5898b58614136/core/src/main/java/com/opensymphony/xwork2/DefaultTextProvider.java#L128) meaning that isn't an injection sink either.

My local tests and knowledge of Struts 2 is somewhat rudimentary, so please double check all of my work!

**Code samples or links to source code**

The problematic lines in the CodeQL source code are here: 
- [getText(String, String, String)](https://github.com/github/codeql/blob/0618568cdcc01d192628d68e06e049986d613ffe/java/ql/lib/ext/struts2.model.yml#L55C8-L55C8)
- [getText(String, List)](https://github.com/github/codeql/blob/0618568cdcc01d192628d68e06e049986d613ffe/java/ql/lib/ext/struts2.model.yml#L42C13-L42C13)
- [getText(String, String[])](https://github.com/github/codeql/blob/0618568cdcc01d192628d68e06e049986d613ffe/java/ql/lib/ext/struts2.model.yml#L65C6-L65C6)
- [getText(String, String, List)](https://github.com/github/codeql/blob/0618568cdcc01d192628d68e06e049986d613ffe/java/ql/lib/ext/struts2.model.yml#L47C3-L47C3)
- [getText(String, String, String[])](https://github.com/github/codeql/blob/0618568cdcc01d192628d68e06e049986d613ffe/java/ql/lib/ext/struts2.model.yml#L58C16-L58C16)
- [getText(String, String, List, ValueStack)](https://github.com/github/codeql/blob/0618568cdcc01d192628d68e06e049986d613ffe/java/ql/lib/ext/struts2.model.yml#L51C86-L51C90)
- [getText(String, String, String[], ValueStack)](https://github.com/github/codeql/blob/0618568cdcc01d192628d68e06e049986d613ffe/java/ql/lib/ext/struts2.model.yml#L62)

Apache Struts 2 implementation details:
- The implementation of `TextProvider.getText(String key, String defaultValue, String obj)` flows `obj` into `args` [here](https://github.com/apache/struts/blob/6fcb50122d381b2f2fe5133a95b5898b58614136/core/src/main/java/com/opensymphony/xwork2/DefaultTextProvider.java#L128)
- OGNL evaluation for getText occurs [here](https://github.com/apache/struts/blob/6fcb50122d381b2f2fe5133a95b5898b58614136/core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java#L201C17-L201C17), [here](https://github.com/apache/struts/blob/6fcb50122d381b2f2fe5133a95b5898b58614136/core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java#L554), and [here](https://github.com/apache/struts/blob/6fcb50122d381b2f2fe5133a95b5898b58614136/core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java#L614). To a lesser extent, there is also some parsing of OGNL-related syntax [here](https://github.com/apache/struts/blob/6fcb50122d381b2f2fe5133a95b5898b58614136/core/src/main/java/com/opensymphony/xwork2/util/StrutsLocalizedTextProvider.java#L232) as well.

**URL to the alert on GitHub code scanning (optional)**
Reach out to me if you'd like some links to our internal CodeQL false positive alerts caused by this issue.

**Comment by aibaars** [comment]
Thanks for reporting, it looks you are right, but I'm no struts expert either. I'll ask the team to have a closer look!

**Comment by atorralba** [comment]
Hey @ebickle, thank you for your report! I can confirm that your analysis is right and that those sinks were incorrectly added. https://github.com/github/codeql/issues/15053 fixes it.
