### ISSUE TITLE
How do you create COdeQL.exe file?

### ISSUE THREAD

**Issue by pshahid1** [github/codeql#15067]
**Description of the issue**

I downloaded codeql github and placed it in agent _work/_tool folder but my build pipeline fails with an error that it cannot find codeql.exe file. and of course it would not find because there is no exe.

##[warning] Unable to locate executable file: 'F:\AZD\agent01\_work\_tool\CodeQL\0.0.0-v2.15.4\x64\codeql\codeql.exe'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
##[error]Unable to locate executable file: 'F:\AZD\agent01\_work\_tool\CodeQL\0.0.0-v2.15.4\x64\codeql\codeql.exe'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

Learn more about the scan for the CodeQL build tasks:
https://aka.ms/advanced-security/code-scanning/detection

Finishing: AdvancedSecurityCodeqlInit

**Comment by aibaars** [comment]
Could you share the URL you used to download CodeQL? The Windows version or the multi-platform versions should work. Did you download a `tar.gz` file or a `.zip` one. For the `.zip` one make sure there are no warnings about "duplicate" files, some unzip tools on windows consider `codeql` and `codeql.exe` the same file name depending on the order in which they are extracted. The files in the zip file are sorted in a way that  should avoid this problem, but perhaps a mistake was made.

**Comment by pshahid1** [comment]
Hello, thank you for getting back to me, much appreciated.
I have downloaded COdeQL from main branch as Download zip, and also from all tags and picked up latest tag but both download does not contain codeQL.exe
I am not sure if I have to create one. 

this is the link where I downloaded zip file from. it 
https://github.com/github/codeql/tags

![image](https://github.com/github/codeql/assets/98341689/173ab6da-ab8a-4910-8dae-9a000bfc7836)

**Comment by aibaars** [comment]
Ah indeed, that doesn't work. That will download the source code of the CodeQL queries. You can find a ready to use CodeQL bundle at: https://github.com/github/codeql-action/releases or a CodeQL CLI without queries at: https://github.com/github/codeql-cli-binaries/releases

**Comment by pshahid1** [comment]
ahh , yes i got it from Asset tab and found it. thank you so much for your help.
