### ISSUE TITLE
Exit status -1073741515 when doing ruby analysis on Windows 2019

### ISSUE THREAD

**Issue by henti** [github/codeql#15139]
**Description of the issue**

Test ruby extraction from powershell on windows 2019 against [multi-language-repo](https://github.com/github/codeql-action/tree/main/tests/multi-language-repo) in the codeql-actions repo I encountered the following error: 

```
[2023-12-18 10:49:33] [ERROR] Spawned process exited abnormally (code -1073741515; tried to run: [C:\Users\henti\AppData\Local\Temp\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, C:\Users\henti\AppData\Local\Temp\codeql\ruby\tools\autobuild.cmd])
[2023-12-18 10:49:33] Exception caught at top level: Exit status -1073741515 from command: [C:\Users\henti\AppData\Local\Temp\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, C:\Users\henti\AppData\Local\Temp\codeql\ruby\tools\autobuild.cmd]
                      com.semmle.cli2.Commandline.executeAndCheckResult(Commandline.java:170)
                      com.semmle.cli2.Commandline.runWithoutReturn(Commandline.java:123)
                      com.semmle.cli2.database.DatabaseProcessCommandCommon.executeSubcommand(DatabaseProcessCommandCommon.java:226)
                      com.semmle.cli2.database.TraceCommandCommand.executeSubcommand(TraceCommandCommand.java:110)
                      com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:803)
                      com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
                      com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:801)
                      com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:119)
                      com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:199)
                      com.semmle.cli2.database.CreateCommand.executeSubcommand(CreateCommand.java:180)
                      com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:803)
                      com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
                      com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:801)
                      com.semmle.cli2.picocli.SubcommandCommon.toplevelMain(SubcommandCommon.java:685)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:666)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:237)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:247)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:115)
```

Testing via SSH I set the `$env:$CODEQL_EXTRACTOR_RUBY_ROOT` and `$env:$CODEQL_PLATFORM` variables manually and ran `C:\Users\henti\AppData\Local\Temp\codeql\tools\win64\runner.exe cmd.exe /C type NUL && C:\Users\henti\AppData\Local\Temp\codeql\ruby\tools\autobuild.cmd` manually and powershell does not throw and error and just returns to the shell. 

Via RDP I got a pop-up for missing DLL `msvcp140.dll` which is provided by [Microsoft Visual C++ Redistributable Packages for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=53840)

After installing, ruby analysis worked as expected.

**Comment by henti** [comment]
> So, this is perhaps a documentation issue that users need to install `msvcp140.dll` before running a ruby analysis.
> 
> Is this a vm that you created for testing on azure devops?

That is correct. Base windows 2019 install on Azure and then downloading CodeQL and attempt to analyse ruby code.

**Comment by aeisenberg** [comment]
Looks like we should update https://github.com/github/codeql/blob/main/docs/codeql/codeql-overview/system-requirements.rst#L17 to include a mention of `msvcp140.dll`.

**Comment by aeisenberg** [comment]
I put up a docs PR for this. Can you take a look?

**Comment by sidshank** [comment]
With the Docs PR merged, can this issue be closed? Thanks @aeisenberg and @aibaars for getting the docs change in 🚀
