### ISSUE TITLE
Taint Tracking of Function Passed Through JSX Attributes

### ISSUE THREAD

**Issue by gtsp233** [github/codeql#15207]
**Description of the issue**

I'm facing an issue where CodeQL is failing to track data flow correctly when a function is passed through a JSX attribute. For example:

```
import React from "react";
import ReactDOM from "react-dom/client";

function App() {
  <Comp p1={window.location} p2={() => window.location} />;
}
function Comp(props) {
  return (
    <div>
      <p
        dangerouslySetInnerHTML={{
          __html: props.p1,
        }}
      />
      <p
        dangerouslySetInnerHTML={{
          __html: props.p2(),
        }}
      />
    </div>
  );
}
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
export default App;
``` 
I ran the official query [client-side cross-site scripting](https://codeql.github.com/codeql-query-help/javascript/js-xss/) on this example, and it turned out that CodeQl failed to track the data flow through props.p2 when it is a function passed via a JSX attribute, in contrast to its successful detection in the case of props.p1. 

Is this an inherent limitation, a bug, or a case of incorrect usage?

**Comment by jketema** [comment]
Hi @gtsp233,

I've asked the relevant engineering team to take a look. Note that this may take a few days, depending on when people are back from their New Year's holiday.

**Comment by erik-krogh** [comment]
> Is this an inherent limitation, a bug, or a case of incorrect usage?

It's a limitation of our current analysis.  
The relevant code can be found here: https://github.com/github/codeql/blob/19c5d1fd1dfffe2fec9332dbc3405561fc515636/javascript/ql/lib/semmle/javascript/frameworks/React.qll#L860-L870  

On such a React property we're only tracking that the value might be tainted, we're not tracking what the value contains. 
This is to prevent the analysis from blowing up in complexity/runtime, and to prevent possible false positives.  

But, it might be an easy fix to improve the analysis. I'm looking into that.

**Comment by erik-krogh** [comment]
The missing flow you described should be fixed now that https://github.com/github/codeql/pull/15221 has been merged.  

It will take a few weeks for the fix to be released in a CLI release / code-scanning.
