### ISSUE TITLE
Java: Add sinks for `sun.misc.Unsafe`

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#15247]
## Description of the issue
The [`sun.misc.Unsafe`](https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/jdk.unsupported/share/classes/sun/misc/Unsafe.java) class provides methods for directly accessing memory using memory addresses. It is sometimes used in libraries to achieve better performance compared to equivalent Java memory access.

From a security perspective `Unsafe` is interesting because if the memory address is incorrect you can crash the JVM (or possibly worse?). This also makes other bug patterns, such as numeric overflow, interesting in this context.

For example:
```java
var field = sun.misc.Unsafe.class.getDeclaredField("theUnsafe");
field.setAccessible(true);
var unsafe = (sun.misc.Unsafe) field.get(null);

// Crashes the JVM
long badAddress = 1000000000L;
unsafe.getInt(badAddress);
```

What do you think about adding models and a CodeQL class which represents these sinks? Maybe not directly as part of a query (yet) but in a `FlowSinks.qll` library (similar to the existing [`FlowSources.qll`](https://github.com/github/codeql/blob/codeql-cli/v2.15.5/java/ql/lib/semmle/code/java/dataflow/FlowSources.qll)).
There is already [`sun.misc.model.yml`](https://github.com/github/codeql/blob/codeql-cli/v2.15.5/java/ql/lib/ext/sun.misc.model.yml) but it does not cover `Unsafe` yet.

Possibly this could also be combined with (future) sinks for other APIs which take native memory addresses as arguments.

Here is my hacky CodeQL code to match these `sun.misc.Unsafe` sinks:
<details>
<summary><code>UnsafeSink</code></summary>

```codeql
class UnsafeSink extends DataFlow::Node {
  UnsafeSink() {
    exists(MethodAccess c, Method m, int argIndex |
      m = c.getMethod() and
      m.getDeclaringType().hasQualifiedName("sun.misc", "Unsafe") and
      c.getArgument(argIndex) = this.asExpr()
    |
      m.getName().matches(["get%", "put%"]) and
      (
        m.getParameterType(0) instanceof TypeObject and argIndex = 1
        or
        m.getParameterType(0).hasName("long") and argIndex = 0
      )
      or
      m.hasName("allocateMemory") and argIndex = 0
      or
      m.hasName("reallocateMemory") and argIndex = [0, 1]
      or
      m.hasName("setMemory") and
      (
        m.getParameterType(0) instanceof TypeObject and argIndex = [1, 2]
        or
        m.getParameterType(0).hasName("long") and argIndex = [0, 1]
      )
      or
      m.hasName("copyMemory") and
      (
        m.getParameterType(0) instanceof TypeObject and argIndex = [1, 3, 4]
        or
        m.getParameterType(0).hasName("long") and argIndex = [0, 1, 2]
      )
      or
      m.hasName("freeMemory") and argIndex = 0
      or
      m.getName().matches("compareAndSwap%") and argIndex = 1
      or
      m.getName().matches(["get%Volatile", "put%Volatile"]) and argIndex = 1
      or
      m.getName().matches("putOrdered%") and argIndex = 1
      or
      m.getName().matches(["getAndAdd%", "getAndSet%"]) and argIndex = 1
    )
  }
}
```

</details>

### Affected methods (memory address)

<code>get<i>X</i>(Object, ...)</code> / <code>put<i>X</i>(Object, ...)</code>:
| Method | Arg index |
| - | - |
| `getInt(Object, ...)` | 1 |
| `putInt(Object, ...)` | 1 |
| `getObject(Object, ...)` | 1 |
| `putObject(Object, ...)` | 1 |
| `getBoolean(Object, ...)` | 1 |
| `putBoolean(Object, ...)` | 1 |
| `getByte(Object, ...)` | 1 |
| `putByte(Object, ...)` | 1 |
| `getShort(Object, ...)` | 1 |
| `putShort(Object, ...)` | 1 |
| `getChar(Object, ...)` | 1 |
| `putChar(Object, ...)` | 1 |
| `getLong(Object, ...)` | 1 |
| `putLong(Object, ...)` | 1 |
| `getFloat(Object, ...)` | 1 |
| `putFloat(Object, ...)` | 1 |
| `getDouble(Object, ...)` | 1 |
| `putDouble(Object, ...)` | 1 |

<code>get<i>X</i>(long)</code> / <code>put<i>X</i>(long, ...)</code>:
| Method | Arg index |
| - | - |
| `getByte(long)` | 0 |
| `putByte(long, ...)` | 0 |
| `getShort(long)` | 0 |
| `putShort(long, ...)` | 0 |
| `getChar(long)` | 0 |
| `putChar(long, ...)` | 0 |
| `getInt(long)` | 0 |
| `putInt(long, ...)` | 0 |
| `getLong(long)` | 0 |
| `putLong(long, ...)` | 0 |
| `getFloat(long)` | 0 |
| `putFloat(long, ...)` | 0 |
| `getDouble(long)` | 0 |
| `putDouble(long, ...)` | 0 |

<code>get<i>X</i>Volatile</code> / <code>put<i>X</i>Volatile</code>:
| Method | Arg index |
| - | - |
| `getObjectVolatile` | 1 |
| `putObjectVolatile` | 1 |
| `getIntVolatile` | 1 |
| `putIntVolatile` | 1 |
| `getBooleanVolatile` | 1 |
| `putBooleanVolatile` | 1 |
| `getByteVolatile` | 1 |
| `putByteVolatile` | 1 |
| `getShortVolatile` | 1 |
| `putShortVolatile` | 1 |
| `getCharVolatile` | 1 |
| `putCharVolatile` | 1 |
| `getLongVolatile` | 1 |
| `putLongVolatile` | 1 |
| `getFloatVolatile` | 1 |
| `putFloatVolatile` | 1 |
| `getDoubleVolatile` | 1 |
| `putDoubleVolatile` | 1 |

| Method | Arg index |
| - | - |
| `getAddress` | 0 |
| `putAddress` | 0 |
| `reallocateMemory` | 0 |
| `setMemory(Object, ...)` | 1 |
| `setMemory(long, ...)` | 0 |
| `copyMemory(Object, ...)` | 1, 3 |
| `copyMemory(long, ...)` | 0, 1 |
| `freeMemory` | 0 |
| `compareAndSwapObject` | 1 |
| `compareAndSwapInt` | 1 |
| `compareAndSwapLong` | 1 |
| `putOrderedObject` | 1 |
| `putOrderedInt` | 1 |
| `putOrderedLong` | 1 |
| `getAndAddInt` | 1 |
| `getAndAddLong` | 1 |
| `getAndSetInt` | 1 |
| `getAndSetLong` | 1 |
| `getAndSetObject` | 1 |

### Affected methods (memory segment length)
These sinks specify the length of a memory segment to copy or set. Similarly to the memory address sinks above they also allow crashing the JVM, but maybe they cannot be used that easily for other attacks (?).

| Method | Arg index |
| - | - |
| `setMemory(Object, ...)` | 2 |
| `setMemory(long, ...)` | 1 |
| `copyMemory(Object, ...)` | 4 |
| `copyMemory(long, ...)` | 2 |

### Affected methods (memory allocation size)
Maybe this goes more in the direction of #4582[^1], but on the other hand the `Unsafe` documentation says some safety checks might be omitted, so maybe for invalid values these methods can also cause other incorrect behavior?

| Method | Arg index |
| - | - |
| `allocateMemory` | 1 |
| `reallocateMemory` | 1 |

[^1]: I am not completely sure about the status of that PR and whether these sinks have already been covered by the models in the meantime. Sorry if my review comments on that PR back then were too disruptive and prevented that PR from getting merged.

**Comment by MathiasVP** [comment]
Hi @Marcono1234,

I discussed the possibility of a `FlowSinks.qll` library with the Java team, and they said that dumping sinks into a library preemptively doesn't really make much sense, since (contrary to sources) sinks aren't really reusable. Rather, they are query-specific or, at most, shared between very few queries.

Your research about unsafe memory accesses in the JVM is super cool though, and could be a neat idea for a new query in the future!

So we probably won't be adding these sinks without context in a generic library right now, but we encourage you to submit a new query through the bounty program if you can find real-world cases where this pattern becomes a vulnerability (or, even better, if they find new vulnerabilities themselves with the query!)

**Comment by Marcono1234** [comment]
Thanks for the feedback! You are right adding potential sinks preemptively would be a bit weird.

However, I currently find it difficult to write a specific query for this:
- Since `Unsafe` is most often used in libraries, the _source_ would probably be a `byte[]` or `ByteBuffer` rather than remote or local user input
- While range checks might be flow barriers, they might be faulty and be prone to overflow
- While usage of `&` restricts the value and might be a potential flow barrier, the result might be shifted and combined with other read bytes which in the end could still lead to overflow

Maybe it is possible to write a query which considers this, but for now I think it is easier to have a CodeQL query which covers some of this, and then use its results to help with manually reviewing the code. Or only using IDE features to manually browse the dataflow in the Java code (without CodeQL usage).

If someone else wants to write a query based on the information here, feel free to do so, but I will probably not do this for now.

Do you want to close this issue then?

**Comment by smowton** [comment]
Thanks for the writeup; I will as you suggest close this for now.
