### ISSUE TITLE
The QL query should not have multiple results?

### ISSUE THREAD

**Issue by sud0why** [github/codeql#15274]
I tried to use QL statement to query a taint analysis. There should be two results: req->cmdstr and req1->cmdstr1. but four results were returned, like req->cmdstr1. I can't understand why. But when I comment out the statements in the main function, the result is returned correctly, like Figure 2. 
Why does this happen? 
How should I modify the QL statement to query 2 results in the code in Figure 1?

![1704883705339](https://github.com/github/codeql/assets/16025404/ea54b730-7d6a-4967-a8b3-c548a56e16bf)
![17048837755587](https://github.com/github/codeql/assets/16025404/c59e82a5-c293-4e18-87df-b1fa01e04507)

**Comment by MathiasVP** [comment]
Hi @sud0why,

To debug why you're getting these additional results I would advice you to convert this query to a [path-problem query](https://codeql.github.com/docs/writing-codeql-queries/creating-path-queries/). Then you can see the flow path that CodeQL thinks it can take to get from `req` to `cmdstr1`.

To convert your query to a path-problem query you need to do the following:
1. Add the required meta-data to the top of the query (see more information about this [here](https://codeql.github.com/docs/writing-codeql-queries/creating-path-queries/#path-query-metadata)):
    ```ql
    /**
     * @kind path-problem
     */
    ```
2. Import the module that creates the path:
    ```ql
    import UnsafeFlow::PathGraph
    ```
3. Select the right columns in your `select` clause (see more information about this [here](https://codeql.github.com/docs/writing-codeql-queries/creating-path-queries/#select-clause)). That is, replace:
    ```ql
    select source, sink
    ```
    with:
    ```ql
    select sink.getNode(), source, sink, "Flow from source to sink"
    ```

If you then run your query again you should see the path that CodeQL thinks it can take to go from e.g., `req` to `cmdstr1`.

**Comment by sud0why** [comment]
Thx! @MathiasVP 
I found out why this happens, this is very useful help.
But I still have a question, how can I disable the propagation of nodes 2 to 3 in the figure?

![image](https://github.com/github/codeql/assets/16025404/73f9299c-14e7-456a-98d8-1eabaa05c63d)

**Comment by MathiasVP** [comment]
Thanks for that investigation, @sud0why. That reverse propagation certainly looks incorrect. I'll forward your issue to our Go experts.

Would you mind pasting your Go code (and QL code) into this issue in text form so that our Go experts don't have to retype your snippet from your screenshot? ❤

**Comment by sud0why** [comment]
Thanks for your support with this issue! @MathiasVP 

main.go:

`package main

import (
	"context"
	"fmt"
	"os/exec"
)

var actionMap = map[string]Controller{
	"deleteAuditPolicy":  &deleteAuditPolicyController{},
	"deleteAuditPolicy1": &deleteAuditPolicyController1{},
}

type Controller interface {
	Process(context.Context, interface{}) (interface{}, error)
}

type Req struct {
	data string
}

type deleteAuditPolicyController struct {
}

func (this *deleteAuditPolicyController) Process(ctx context.Context, req interface{}) (rsp interface{}, err error) {
	r := req.(*Req)
	myfunc(r.data)
	return nil, nil
}

func myfunc(qwe string) {
	cmdstr := fmt.Sprintf("%s", qwe)
	exec.Command(cmdstr)
}

type deleteAuditPolicyController1 struct {
}

func (this *deleteAuditPolicyController1) Process(ctx context.Context, req1 interface{}) (rsp interface{}, err error) {
	r1 := req1.(*Req)
	myfunc1(r1.data)
	return nil, nil
}

func myfunc1(qwe1 string) {
	cmdstr1 := fmt.Sprintf("%s", qwe1)
	exec.Command(cmdstr1)
}

func main() {
	if controller, ok := actionMap["action"]; ok {
		controller.Process(context.Background(), &Req{data: "hello world"})
	}
}
`

query.ql:

`/**
 * @kind path-problem
 */

import go

class OsExecCommand extends DataFlow::Node {
  OsExecCommand() {
    exists(DataFlow::CallNode call |
      call.getTarget().hasQualifiedName("os/exec", "Command") and
      this = call.getAnArgument()
    )
  }
}

class HttpRequest extends DataFlow::Node {
  HttpRequest() {
    exists(Method m, DataFlow::ParameterNode paramNode |
      this.(DataFlow::ParameterNode) = paramNode and
      paramNode.getPosition() = 1 and
      paramNode.getEnclosingCallable().asFunction().(Method) = m and
      m.getNumParameter() = 2 and
      m.getParameter(1).getType() instanceof InterfaceType and
      m.getName() = "Process"
    )
  }
}

module UnsafeFlowConfig implements DataFlow::ConfigSig {
  predicate isSource(DataFlow::Node source) { source instanceof HttpRequest }

  predicate isSink(DataFlow::Node sink) { sink instanceof OsExecCommand }
}

module UnsafeFlow = TaintTracking::Global<UnsafeFlowConfig>;
import UnsafeFlow::PathGraph

from UnsafeFlow::PathNode source, UnsafeFlow::PathNode sink
where UnsafeFlow::flowPath(source, sink)
select sink.getNode(), source, sink, "Found taint flow"`

**Comment by sud0why** [comment]
Thanks for you replay. @owen-mc 

Now I can understand the reason of propagation in the above example. Also you `isBarrier` solution also works very well.

But considering the following example, should propagation only occur when the type pointed to by the pointer matches? Maybe consider the same type before propagating it in the future?

![image](https://github.com/github/codeql/assets/16025404/33640798-751a-41c4-8800-1b0108305137)

**Comment by owen-mc** [comment]
The data flow library that we use for Go is also used for our analysis of many other languages, including java and C#. I know that they use a feature called type strengthening, which I think keeps track of what type a value can be along a path and use this to exclude impossible paths. We do not currently use this for Go as it is not generally needed, but we will consider this as an example of a case where it would help and reconsider its priority.

**Comment by sud0why** [comment]
Thank you very much for your reply. I have no other questions. 
I will close this issue.
