### ISSUE TITLE
False positive - "zx" npm package usage is mistakenly detected as jQuery usage

### ISSUE THREAD

**Issue by jportner** [github/codeql#15286]
**Background**

I'm using the ["zx" npm package](https://www.npmjs.com/package/zx), which wraps `child_process` and makes it easier to execute shell commands. Example:

```js
await $`cat package.json | grep name`
```

The zx function is named `$`, and it uses a [feature of JavaScript called tagged templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates). Using tagged templates like this is effectively a function call.

The MDN documentation for tagged templates has a good example of this. If you call a function using the tagged template syntax, the first argument is a string array of the template string, and all subsequent arguments are expressions within the template. Example:

```js
const person = "Mike";
const age = 28;

function myTag(strings, personExp, ageExp) {
  const str0 = strings[0]; // "That "
  const str1 = strings[1]; // " is a "
  const str2 = strings[2]; // "."

  const ageStr = ageExp < 100 ? "youngster" : "centenarian";

  // We can even return a string built using a template literal
  return `${str0}${personExp}${str1}${ageStr}${str2}`;
}

const output = myTag`That ${person} is a ${age}.`;

console.log(output);
// That Mike is a youngster.
```

---

**Description of the false positive**

The problem is, it looks like zx usage is getting mistakenly detected as jQuery usage. The only reason I found this out is because if I use a zx function with 3 or more arguments, it gets flagged by the `js/superfluous-trailing-arguments` rule.

**Code samples or links to source code**

Sample:

```js
await $`git clone ${repoUrl} ${directory}`;
```

This results in a CodeQL alert for the `js/superfluous-trailing-arguments` rule for the "directory" argument (that is the 3rd argument in the tagged template):

<img width="451" alt="image" src="https://github.com/github/codeql/assets/5295965/800c19a0-f447-4d17-91a2-b28673a4a9e7">

In this case, the `js/superfluous-trailing-arguments` query seems to be behaving as expected, but the `$` function isn't actually jQuery, it's zx.

jQuery can't be properly used as a tagged template like this, so maybe the appropriate fix here is to update jQuery detection to exclude tagged template usage?

**Comment by erik-krogh** [comment]
You're right, that's a problem.  

We recently added better support for calls to tagged template literals, but that has exposed the problem you see here.  

I think the fix is just to exclude tagged template literals from the `js/superfluous-trailing-arguments` query, which I've done here: https://github.com/github/codeql/pull/15523

**Comment by jportner** [comment]
Thanks, I think completely excluding tagged template literals from this query sounds reasonable!

Maybe I'm overthinking this part. Given that template strings are detected as functions, and apparently any function named `$` is inferred to be jQuery -- I assumed it is possible that there are other query rules which could result in similar false positives that nobody has run into yet. I don't really have a way to validate that assumption though.

Do you think it _also_ makes sense to address that? Perhaps in a separate PR?

I would submit a PR if I knew where to make the change, but I'm not very familiar with the codebase and I couldn't find what I was looking for.

**Comment by erik-krogh** [comment]
> Maybe I'm overthinking this part. Given that template strings are detected as functions, and apparently any function named $ is inferred to be jQuery -- I assumed it is possible that there are other query rules which could result in similar false positives that nobody has run into yet. I don't really have a way to validate that assumption though.

Tagged template literals are detected as function **calls**.  

And I couldn't actually replicate the example you had shown without adding my own definition of `$`, so not every call to `$` is seen as a call to jQuery.  
I suspect you have a copy of jQuery somewhere in your codebase, and that our analysis found that, or maybe I missed something.  
Due to global variables that copy could be anywhere. 

So I don't think there is anything more to do here.

**Comment by jportner** [comment]
Ah, thanks for clarifying. 

We don't have jQuery in our dependencies (at least, not according to our yarn.lock file), I wonder how it was detected then. Strange.
