### ISSUE TITLE
Some CPP source files do not contain headers

### ISSUE THREAD

**Issue by DrAlexD** [github/codeql#15366]
### 1)  Why some CPP source files in the examples do not contain the necessary headers? 
Like https://github.com/github/codeql/blob/main/cpp/ql/src/Security/CWE/CWE-119/OverrunWriteProductFlow.cpp or https://github.com/github/codeql/blob/main/cpp/ql/src/Security/CWE/CWE-295/SSLResultConflationGood.cpp

### 2) Is it necessary to create a CodeQL database to test QL queries on some CPP source files? Using:
```
codeql database create <database> --language=<language-identifier>
``` 

### 3) I was able to test some QL queries without creating a database with command: `codeql test run <dir>`.
Where the `<dir>` contains within it a *.ql file and a *.cpp file.

But I can't run CodeQL queries like this for CPP source files that contain any headers:
```
[date] [build-err] [date] Warning[extractor-c++]: In construct_text_message: "path/to/file.cpp", line 1: catastrophic error: cannot open source file "iostream"
[date] [build-err]   #include <iostream>
[date] [build-err]                      ^
[date] [build-err] 1 catastrophic error detected in the compilation of "path/to/file.cpp".
[date] [build-err] Compilation terminated.
```
Why is this happening?

### 4) At the moment I have the following hierarchy in my project:
```
- dir0
-- dir5
--- dir6
---- dir7
----- file.cpp
----- query.ql
---- dir8
----- file2.cpp
----- query2.ql
---- qlpack.yml
---- codeql-pack.lock.yml
```
Where `qlpack.yml` contain:
```
name: codeql-examples
dependencies:
  codeql/cpp-all: "*"
extractor: cpp
tests: .
```
Where `codeql-pack.lock.yml` contain:
```
---
lockVersion: 1.0.0
dependencies: {}
compiled: false
```
This way I can run a command `codeql test run <dir6>` to execute two tests at once (query.ql and query2.ql).
But I want use *.qlref files to put *.ql files in a different directory like this:
```
- dir0
-- dir1
--- dir2
---- dir3
----- query.ql
---- dir4
----- query2.ql
-- dir5
--- dir6
---- dir7
----- file.cpp
----- query.qlref
---- dir8
----- file2.cpp
----- query2.qlref
---- qlpack.yml
---- codeql-pack.lock.yml
```
I use the same `qlpack.yml` and `codeql-pack.lock.yml` files in `dir6` and dont create any new in `dir2`.
File `query.qlref` looks like:
```
dir1/dir2/dir3/query.ql
```
After executing the same command `codeql test run <dir6>`, I get an error:
```
Cannot resolve QL reference 'dir1/dir2/dir3/query.ql'.
[1/2] FAILED(COMPILATION) path/to/dir5/dir6/dir7/query.qlref
```
What did I do wrong?

**Comment by smowton** [comment]
1. The examples are snippets, not complete runnable programs.
2. Yes, you need to make a database somehow. The simplest way is to write a little Makefile whose `all` / default target compiles the code you're interested in.
3. The tests are supposed to be platform-independent, and of course system headers vary widely. Consequently if you look at the files in `cpp/ql/test/...` you'll find they declare their own types and function signatures that would normally come from system headers.
4. The query files you want to reference aren't in a qlpack, so codeql doesn't know where to look for them. Note for example the shipped qlpack in `cpp/ql/test/qlpack.yml` depends on its companion query qlpack defined in `cpp/ql/src` (in fact we divide our QL into library `ql/lib` and queries under `ql/src`, but you aren't required to do this). You may need the `--additional-packs` option in order to tell codeql where to look for dependency qlpacks.

**Comment by DrAlexD** [comment]
Thanks for your answer! I still don't understand some things a little bit:
1) If creating a database is mandatory, why could I run tests without headers using `codeql test run <dir>`? Or does the lack of database just affect the fact that I can't use this command for CPP files with headers? If possible, I would not like to create database.
2) `Consequently if you look at the files in cpp/ql/test/... you'll find they declare their own types and function signatures that would normally come from system headers.` That is, do I also need to put the necessary header files in certain directories in order to use them? Where in my hierarchy do I need to put them and how do I tell the extractor where to find them?
3) Do I understand correctly that I will not be able to process this code (link below) using CodeQL until I manually put the `cstdio` file in the right place? Or do I need to create a separate file into which the functions I need for the CPP file will be copied?
https://github.com/github/codeql/blob/main/cpp/ql/src/Security/CWE/CWE-020/ExternalAPISinkExample.cpp

**Comment by smowton** [comment]
`codeql test run` will use simple guesses about how it might build some C/C++ files into a database, but this isn't a good tool for creating databases in general. If all you need is to compile some files one time, `database create -c "gcc file1.c file2.c ..."` is likely to be easier and more flexible.

The restrictions about header files are particular to tests, and it sounds like your use case is not for tests but for generally creating a database and querying it. If you create your database using `database create` not `test run`, you will be able to use includes exactly as a normal program.

**Comment by DrAlexD** [comment]
Which is the best way to test one or many QL queries after creating the database with `database create`? 

After creating the database with `database create`, will time and resources be spent on creating database during the `codeql test run`? Or the database created with `database create` will be used?

If I changed one CPP source file after creating the database, do I need to recreate the database by specifying all the files again? Or is there some other way?

**Comment by aibaars** [comment]
> Which is the best way to test one or many QL queries after creating the database with `database create`?

You can run `codeql database analyze`, or `codeql database run-queries` to run queries against a database; the `analyze` command is just a combination of `run-queries` and `interpret-results`. 

If you want to define and run some "unit" tests to verify the behaviour of the queries you wrote then I'd recommend using `codeql test run`. 

> After creating the database with `database create`, will time and resources be spent on creating database during the `codeql test run`? Or the database created with `database create` will be used?

The `codeql test run` command is not meant to run queries against a database built with `codeql database create`.
`codeql test run` is meant for running "unit" tests when developing QL queries and libraries. The "unit" tests consist of some sample source code, a query and a text file with `.expected` extension. The `codeql test run` command will build a database of the sample files, run the query against it, and compare the results to the expected output. 

> If I changed one CPP source file after creating the database, do I need to recreate the database by specifying all the files again? Or is there some other way?

Yes, you'd need to create a new database from scratch.

**Comment by rvermeulen** [comment]
Hi @DrAlexD,

Thanks again for your questions.
I believe @smowton & @aibaars has provided you with answers to all your questions, so I will proceed by closing this issue.

If you have any follow-up questions, feel free to re-open the issue.

Thanks!
