### ISSUE TITLE
Surprising predicate dispatch when extending a class, but not providing a charpred

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/codeql#15374]
**Description of the issue**
(I'm 99 percent sure I've somewhat recently seen a similar issue, but I can't find it. Or it was asked on Slack only)

I have the following codeql query:
```ql
import cpp

class OptionalValue extends Expr {
  override string toString() { result = "Overriden" }
}

from File file, Function func, GlobalVariable var, VariableAccess acc, OptionalValue assigned
where
  file.getRelativePath() = "lib/lz4.c" and
  func.getName() = "LZ4_compress_generic" and
  var.getAnAccess() = acc and
  acc.getEnclosingFunction() = func and
  var.getAnAssignedValue() = assigned
select var, assigned, var.getType()

```

This gives the following results:
![grafik](https://github.com/github/codeql/assets/60750685/d12ac2b8-d0c1-4257-8de7-c798a9448003)

**I would have expected to only see "Overriden" as a result in the `assigned` column.**

If we quick-evaluate the predicate, we get this result which partly shows why we see the duplicate results in the query:
![grafik](https://github.com/github/codeql/assets/60750685/0cad82e1-0085-4346-9f90-b493a1d65a13)

I tried to follow section 2.5 of [this](https://drops.dagstuhl.de/storage/00lipics/lipics-vol056-ecoop2016/LIPIcs.ECOOP.2016.2/LIPIcs.ECOOP.2016.2.pdf) PDF.
```
r' === Expr.toString/1 === C'.p/n
r === OptionalValue.toString/1 === C.p/n
=>
r overrides r' because C is a transitive subtype of C'
=> r is more specific than r'
r' is not a rootdef, because it overrides another predicate
r is not a rootdef, because it overrides another predicate
rootdef is ElementBase.toString/1

static target of assigned.toString() is OptionaValue === C
most specific predicate is OptionalValue.toString/1 because OptionalValue is a _reflexive_, transitive subtype of OptionalValue
dispatch candidates of assigned.toString() are OptionalValue.toString(), Expr.toString() <== ???
applicable targets are ???
```

**I would be very happy if someone could explain why I'm seeing this problem (in as much depth as you need and want to) and how to fix it.**

Database: [13a2d9e34ffc4170720ce417c73e396d0ac1471a.zip](https://github.com/github/codeql/files/13978595/13a2d9e34ffc4170720ce417c73e396d0ac1471a.zip)

**Comment by smowton** [comment]
Your problem is that the other stringification of the instance comes not from a parent of `OptionalValue` but from a sibling, so neither subtype is more specific than the other and both contribute their results.

Normally of course you would define your own `myToString` and stringify how you please, but builtins like `toString` are special in that implicit references to them are generated that you can't override.

One way you can customise stringification is to define a newtype and define stringification for that:

```
newtype TOptionalValue = TOptionalValueExpr(Expr e)

TOptionalValue toOptionalValue(Expr e) {
   result = TOptionalValueExpr(e)
}

class OptionalValue extends TOptionalValueExpr {
  string toString() { result = "Overriden" }
}

...

select var, toOptionalValue(assigned), var.getType()
```

Will that work for the case you're interested in?

**Comment by intrigus-lgtm** [comment]
Ah, so the two siblings are e.g. `BinaryOperation` (which extends `Expr` via `Operator`) and `OptionalValue`(which extends `Expr`) and neither is more specific, makes sense.
I was too fixated on `OptionalValue` extending `Expr` and ignored the sibling.

While not too nice, a newtype does indeed work.
Thank you!

**Comment by smowton** [comment]
(the other thing to bear in mind of course is that in the vast majority of cases you won't be dealing with a stringified object -- you can instead use alert message interpolation, like `select alertLoc, "Trouble relating to $@", problemExpr, "description of problem expr"`, so the "natural" stringification of problemExpr is not considered)
