### ISSUE TITLE
Kotlin Extractor does not respect SEMMLE_PATH_TRANSFORMER for Source Files

### ISSUE THREAD

**Issue by GJL** [github/codeql#15382]
The `SEMMLE_PATH_TRANSFORMER` environment variable configures the [PathTransformer](https://github.com/github/codeql/blob/7e1dd38623f822046bda8e7d7652cb41f638d417/java/kotlin-extractor/src/main/java/com/semmle/util/trap/pathtransformers/PathTransformer.java#L44-L48) which rewrites file paths before the files are stored in the database.

However, the Kotlin extractor does not seem to apply the PathTransformer on the database's source files:

https://github.com/github/codeql/blob/7e1dd38623f822046bda8e7d7652cb41f638d417/java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt#L376-L386

I believe the above code should read something like:
```kt
    val srcFileRelativePath = PathTransformer.std().fileAsDatabaseString(File(srcFilePath))

    val dbSrcFilePath = FileUtil.appendAbsolutePath(dbSrcDir, srcFileRelativePath).toPath()
    val dbSrcDirPath = dbSrcFilePath.parent
    Files.createDirectories(dbSrcDirPath)
    val srcTmpFile = File.createTempFile(dbSrcFilePath.fileName.toString() + ".", ".src.tmp", dbSrcDirPath.toFile())
    srcTmpFile.outputStream().use {
        Files.copy(Paths.get(srcFilePath), it)
    }
    srcTmpFile.renameTo(dbSrcFilePath.toFile())
```

As an example for how the PathTransformer is used elsewhere in the codebase, see:

https://github.com/github/codeql/blob/7e1dd38623f822046bda8e7d7652cb41f638d417/java/kotlin-extractor/src/main/java/com/semmle/extractor/java/OdasaOutput.java#L109-L115

**Comment by aibaars** [comment]
Thanks for reporting this. I think you're right, I'll pass this on to the team.
