### ISSUE TITLE
False positive: cs/web/unvalidated-url-redirection does not recognize sanitization using string interpolation or string.Format

### ISSUE THREAD

**Issue by rpmrmartin** [github/codeql#15383]
**Description of the false positive**

Code using concatenation with a "?" on the left is recognized as sanitized, but the same code using string interpolation or string.Format instead of concatenation generates an alert.

**Code samples or links to source code**

Code with no alerts:
```csharp
var userInput = Request.QueryString["Item"];
Response.Redirect("Home.aspx?Item=" + userInput);
```

Equivalent code that generates alerts:
```csharp
var userInput = Request.QueryString["Item"];
Response.Redirect(string.Format("Home.aspx?Item={0}", userInput));
```

```csharp
var userInput = Request.QueryString["Item"];
Response.Redirect($"Home.aspx?Item={userInput}");
```

**URL to the alert on GitHub code scanning (optional)**

Alert is in a private repository.

**Comment by michaelnebel** [comment]
Thank you for reporting this!
We will add some sanitization logic for string interpolation expressions and `string.Format`: https://github.com/github/codeql/pull/15394
