### ISSUE TITLE
False positive and misleading diagnostic on scanf

### ISSUE THREAD

**Issue by mm2** [github/codeql#15415]
**Description of the false positive**

False positive and misleading explanation on scanf() on code using strict C99 

**Code samples or links to source code**

 ```
 int res; 

  res = scanf("%4095s", Buffer);
  if (res < 0 || toupper(Buffer[0]) == 'Q') { // Quit?

```

> "The result of scanf is only checked against 0, but it can also return EOF."

It is not  obviously "only checked against 0", but it happens that C99 requires EOF to be negative

**URL to the alert on GitHub code scanning (optional)**

https://github.com/mm2/Little-CMS/security/code-scanning/44

**Comment by MathiasVP** [comment]
Hi @mm2,

Thanks for reporting this to us. I've opened a PR with a fix here: https://github.com/github/codeql/pull/15460.

(For what it's worth, the true source of the false positive was actually because of the `while (res == 0);` check further down in the function.)

**Comment by mm2** [comment]
Thanks for fixing!

**Comment by MathiasVP** [comment]
No problem! The fixed has been merged now. I expect that the change will reach Code Scanning in about two weeks 🤞
