### ISSUE TITLE
cpp query does not stop

### ISSUE THREAD

**Issue by zyfeng-go** [github/codeql#15442]
Hi there,

For the following cpp query, when I removed the conditions `and guardCondition.getLocation().isBefore(sink.getLocation())` and `and source.getLocation().isBefore(guardCondition.getLocation())`, the query finished in less than 10 seconds. but when I had the two conditions in place, it took forever and never produced any outputs. I don't know what's wrong here. What I do is to check whether a guard condition exists physically between a source and a sink. Any suggestion would be helpful, thank you!

```
import cpp
import semmle.code.cpp.controlflow.Guards
import semmle.code.cpp.dataflow.new.DataFlow

class PointerArg extends Parameter {
    PointerArg() {
        this.getType() instanceof PointerType
    } 
}

predicate dereference(PointerFieldAccess pfa, PointerArg pa) {
    exists(PointerFieldAccess pointerFieldAccess | 
        pointerFieldAccess = pfa | 
        pfa.getQualifier() = pa.getAnAccess()
    )
}

from
    PointerArg pointerArg,
    DataFlow::Node source,
    DataFlow::Node sink,
    Function function
where
    source = DataFlow::parameterNode(pointerArg)
    and (
        exists (PointerFieldAccess pointerFieldAccess |
            dereference(pointerFieldAccess, pointerArg)
            and sink = DataFlow::exprNode(pointerFieldAccess.getQualifier())
        )
    )
    and DataFlow::localFlow(source, sink)
    and (
        not exists(GuardCondition guardCondition |
            guardCondition.getEnclosingFunction() = pointerArg.getFunction()
            and guardCondition.getLocation().isBefore(sink.getLocation())
            and source.getLocation().isBefore(guardCondition.getLocation())
            and guardCondition.getAChild*() = pointerArg.getAnAccess()
        )
    )
    and function = pointerArg.getFunction()
select
    function, function.getFile()
```

**Comment by ginsbach** [comment]
There are guides on how to troubleshoot query performance in the CodeQL documentation: https://codeql.github.com/docs/writing-codeql-queries/troubleshooting-query-performance/. With the speed of evaluation sufficiently increased, it should become much easier for you to debug your problem by iterating quickly.

I would also recommend constructing a minimal C++ test case that you expect to find a result in (see https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/testing-custom-queries). Such a test case will generate a very small database that can be evaluated quickly even when there are remaining performance problems in the query.

You can then use the Quick Evaluation feature (https://codeql.github.com/docs/codeql-for-visual-studio-code/analyzing-your-projects/#running-a-specific-part-of-a-query-or-library-1) to inspect parts of the query and check that the results match your expectation.

I hope this helps!

**Comment by aibaars** [comment]
Comparing Locations like this often results in performance problems. A predicate like `isBefore` defines a relation between Locations and the table relating each location to the locations that come before them can be really large. The CodeQL compiler is pretty smart at choosing "join" orders that avoid creating large intermediate results, but sometimes it make a wrong choice and things become really inefficient.

In your case it is probably better to avoid comparing locations, because some guard being textually before a sink does not mean it will really be before when running the code. For example in `for(init; condition; update) { body }`, the `update` is textually before the `body` , but it will be run after the `body`.  For the comparison you are trying to make it is best to look at the control flow graph, see also https://codeql.github.com/codeql-standard-libraries/cpp/semmle/code/cpp/controlflow/Dominance.qll/module.Dominance.html

**Comment by zyfeng-go** [comment]
Hello @aibaars ,

Thank you very much for your invaluable suggestion. However, I'm still running into the similar performance issue. Below is the optimized query I wrote based on your suggestion. I've restricted the search space to a specific function with the name _RoofNode_Create_, but the query wasn't able to terminate within hours. I assume that the _functionCall_, the _snk_ and the _function_ being passed to the predicate are constrained by the preceding **"and"** conditions, so I would expect the number of them wouldn't be very large in this case.

Do you happen to have any idea about that? Thank you!

```
import cpp
import semmle.code.cpp.controlflow.Dominance
import semmle.code.cpp.dataflow.new.DataFlow
import semmle.code.cpp.controlflow.Guards
import semmle.code.cpp.controlflow.ControlFlowGraph

 predicate noGuard(FunctionCall fc, Expr sink, Function function) {
    not exists ( GuardCondition g |
        dominates(fc, g)
        and dominates(g, sink)
        and g.getEnclosingFunction() = fc.getEnclosingFunction() |
        g.getAChild*().(VariableAccess).getTarget() = sink.(VariableAccess).getTarget()
    )
}

from 
    DataFlow::Node source,
    DataFlow::Node sink,
    Expr snk,
    FunctionCall functionCall,
    PointerFieldAccess pointerFieldAccess,
    Function function,
    GuardCondition g
where
    // get function return variable
    source = DataFlow::exprNode(functionCall)
    and function = source.getFunction()
    and function.hasName("RoofNode_Create")
    and not function.getFile().getAbsolutePath().matches("%/usr/include%")
    // locate derefs of the function return variables
    and not pointerFieldAccess.getEnclosingStmt() instanceof IfStmt
    and snk = pointerFieldAccess.getQualifier*()
    and sink = DataFlow::exprNode(snk)
    and DataFlow::localFlow(source, sink)
    and noGuard(functionCall, snk, function)
select
    source, sink
```

**Comment by aibaars** [comment]
> assume that the _functionCall_, the _snk_ and the _function_ being passed to the predicate are constrained by the preceding **"and"** conditions, so I wouldn't expect the number of them to be very large in this case.

The "order" of conditions in an `and` expression is not relevant. I'd expect `predicate noGuard` to be really large. It selects all combinations `(FunctionCall fc, Expr sink, Function function)` for which some `GuardCondition` does not exist. It even includes all combinations of `FunctionCall`, `Expr` and `Function` that are totally unrelated.

I think the suggestions in https://github.com/github/codeql/issues/15442#issuecomment-1911912631 can still help you. Especially the one about creating a small test database on which your query does not take too long to run. That allows you to run parts of the query and validate that all pieces of the query work as expected. Once the query is doing the right thing, you can increase the database size to see if there are any performance problems.
