### ISSUE TITLE
Issues Encountered While Analyzing C Control Flow with CodeQL

### ISSUE THREAD

**Issue by Roarcannotprogramming** [github/codeql#15455]
Hello,

I am a newcomer to CodeQL and currently learning how to analyze control flow in C using CodeQL. I wrote a testcase but encountered several peculiar issues. Here are the details of my testcase:

**File: test_issue.c**
```
struct foo {
    int a;
};

struct bar {
    int b;
    struct foo *foo;
};

struct baz {
    int c;
    struct bar *bar;
};

struct qux {
    int d;
    struct baz baz;
};


void test_struct_1() {
    struct qux *q;
    q->baz.bar->foo->a = 0xdeadbeef;
}

void test_struct_2() {
    struct qux q;
    q.baz.bar->foo->a = 0xdeadbeee;
}

void test_struct_3() {
    struct qux q;
    struct baz b;
    q.baz.bar->foo->a = b.c;
}

void test_struct_4() {
    struct qux q;
    struct baz *b;
    q.baz.bar->foo->a = b->c;
}

void test_struct_5(struct qux *q) {
    q->baz.bar->foo->a = q->d;
    q->baz.bar->foo->a = q->baz.c;
}

void test_basic() {
    int a;
    int b;
    int c;

    a = 1;
    b = a;
    c = a + b;
}


int main() {
    return 0;
}
```

**File: dataflow_issue.ql**
```
/**
 * This is an automatically generated file
 *
 * @name Hello world
 * @kind path-problem
 * @problem.severity warning
 * @id cpp/example/hello-world
 */

import cpp
import semmle.code.cpp.dataflow.new.DataFlow
import semmle.code.cpp.dataflow.new.TaintTracking

/**
 * @source is a member of an object
 * @sink is a member of an object
 */
module MyFlowConfiguration implements DataFlow::ConfigSig {
  predicate isSource(DataFlow::Node source) { source.asExpr() instanceof Expr }

  predicate isSink(DataFlow::Node sink) { sink.asExpr() instanceof Expr }
}

module MyFlow = TaintTracking::Global<MyFlowConfiguration>;

import MyFlow::PathGraph

from MyFlow::PathNode source, MyFlow::PathNode sink
where
  MyFlow::flowPath(source, sink) and
  source != sink
select source, source.getNode().asExpr().getPrimaryQlClasses() as sourceQlClass, sink,
  sink.getNode().asExpr().getPrimaryQlClasses() as sinkQlClass,
  source.getNode().getFunction() as sourceFunction, sink.getNode().getFunction() as sinkFunction
```

**File: codeql-pack.yml**
```
---
library: false
warnOnImplicitThis: false
name: getting-started/codeql-extra-queries-cpp
version: 1.0.0
dependencies:
  codeql/cpp-all: ^0.12.3
```

**Result of running `codeql query`:**
```
Result set: edges
| a |     b     |
+---+-----------+
| 1 | a         |
| 1 | b         |
| 1 | a         |
| 1 | a         |
| 1 | b         |
| 1 | a         |
| 1 | ... + ... |
| a | b         |
| a | a         |
| a | b         |
| a | a         |
| a | ... + ... |
| b | ... + ... |
| a | ... + ... |
| q | q         |
| q | q         |
| q | q         |
| q | q         |
| q | q         |
| q | q         |
| q | q         |
| q | q         |
| q | q         |

Result set: nodes
|     n      |     key      |    val     |
+------------+--------------+------------+
| 1          | semmle.label | 1          |
| a          | semmle.label | a          |
| b          | semmle.label | b          |
| a          | semmle.label | a          |
| q          | semmle.label | q          |
| q          | semmle.label | q          |
| q          | semmle.label | q          |
| a          | semmle.label | a          |
| 1          | semmle.label | 1          |
| b          | semmle.label | b          |
| a          | semmle.label | a          |
| b          | semmle.label | b          |
| a          | semmle.label | a          |
| c          | semmle.label | c          |
| ... + ...  | semmle.label | ... + ...  |
| q          | semmle.label | q          |
| baz        | semmle.label | baz        |
| bar        | semmle.label | bar        |
| foo        | semmle.label | foo        |
| q          | semmle.label | q          |
| a          | semmle.label | a          |
| d          | semmle.label | d          |
| q          | semmle.label | q          |
| baz        | semmle.label | baz        |
| bar        | semmle.label | bar        |
| foo        | semmle.label | foo        |
| q          | semmle.label | q          |
| baz        | semmle.label | baz        |
| a          | semmle.label | a          |
| c          | semmle.label | c          |
| q          | semmle.label | q          |
| baz        | semmle.label | baz        |
| bar        | semmle.label | bar        |
| foo        | semmle.label | foo        |
| b          | semmle.label | b          |
| a          | semmle.label | a          |
| c          | semmle.label | c          |
| q          | semmle.label | q          |
| baz        | semmle.label | baz        |
| bar        | semmle.label | bar        |
| foo        | semmle.label | foo        |
| b          | semmle.label | b          |
| a          | semmle.label | a          |
| c          | semmle.label | c          |
| q          | semmle.label | q          |
| baz        | semmle.label | baz        |
| bar        | semmle.label | bar        |
| foo        | semmle.label | foo        |
| a          | semmle.label | a          |
| 3735928558 | semmle.label | 3735928558 |
| q          | semmle.label | q          |
| baz        | semmle.label | baz        |
| bar        | semmle.label | bar        |
| foo        | semmle.label | foo        |
| a          | semmle.label | a          |
| 3735928559 | semmle.label | 3735928559 |
| 0          | semmle.label | 0          |

Result set: subpaths
| arg | par | ret | out |
+-----+-----+-----+-----+

Result set: #select
| source | sourceQlClass  |   sink    |  sinkQlClass   | sourceFunction | sinkFunction  |
+--------+----------------+-----------+----------------+----------------+---------------+
| 1      | Literal        | a         | VariableAccess | test_basic     | test_basic    |
| 1      | Literal        | b         | VariableAccess | test_basic     | test_basic    |
| 1      | Literal        | a         | VariableAccess | test_basic     | test_basic    |
| 1      | Literal        | ... + ... | AddExpr        | test_basic     | test_basic    |
| a      | VariableAccess | b         | VariableAccess | test_basic     | test_basic    |
| a      | VariableAccess | a         | VariableAccess | test_basic     | test_basic    |
| a      | VariableAccess | ... + ... | AddExpr        | test_basic     | test_basic    |
| b      | VariableAccess | ... + ... | AddExpr        | test_basic     | test_basic    |
| a      | VariableAccess | ... + ... | AddExpr        | test_basic     | test_basic    |
| q      | VariableAccess | q         | VariableAccess | test_struct_5  | test_struct_5 |
| q      | VariableAccess | q         | VariableAccess | test_struct_5  | test_struct_5 |
| q      | VariableAccess | q         | VariableAccess | test_struct_5  | test_struct_5 |
| q      | VariableAccess | q         | VariableAccess | test_struct_5  | test_struct_5 |
| q      | VariableAccess | q         | VariableAccess | test_struct_5  | test_struct_5 |
| q      | VariableAccess | q         | VariableAccess | test_struct_5  | test_struct_5 |
Shutting down query evaluator.
```

In short, I am trying to extract all taints from expression to expression within `test_issue.c`.

I have the following questions:

1. **Data Flow Tracking in Functions**: Why is it that the data flow in the functions `test_struct_1` to `test_struct_5` is not being tracked? Is this due to indirect access?

2. **Unexpected Data Flow in `test_struct_5`**: In the function `test_struct_5`, why is there a data flow from variable `q` to variable `q`, instead of from `FieldAccess d` to `FieldAccess a`?

3. **Missing Data Flow in `test_basic`**: Why is there no data flow from any expression to `c` in the function `test_basic`?

4. **Adding `isAdditionalFlowStep()`**: If I need to add `isAdditionalFlowStep()` in my query, how can I obtain the "default flow step"? I apologize as I have not found any documentation related to the default flow step.

I appreciate any guidance or assistance you can provide on these issues.

Thank you for your time and consideration.

**Comment by aibaars** [comment]
> 1\. **Data Flow Tracking in Functions**: Why is it that the data flow in the functions `test_struct_1` to `test_struct_5` is not being tracked? Is this due to indirect access?

I don't think there is any dataflow between `test_struct_1` and `test_struct_5`. The function `test_struct_1` declares a local pointer variable, but it is never passed to `test_struct_5`, is it?

> 2\. **Unexpected Data Flow in `test_struct_5`**: In the function `test_struct_5`, why is there a data flow from variable `q` to variable `q`, instead of from `FieldAccess d` to `FieldAccess a`?

I'm not sure. The dataflow values that are tracked are parts of `q`, so some content inside `q` flows to another part of `q`.  I'm not sure if the lack of detailed steps is a presentation issue or whether it is a simplification to improve analysis performance. 

> 3\. **Missing Data Flow in `test_basic`**: Why is there no data flow from any expression to `c` in the function `test_basic`?

That's a little curious indeed. Could you add a bit of code to the function that uses `c`? Perhaps things got removed because the variable is never used.

> 4\. **Adding `isAdditionalFlowStep()`**: If I need to add `isAdditionalFlowStep()` in my query, how can I obtain the "default flow step"? I apologize as I have not found any documentation related to the default flow step.

I'm not sure I understand the question. Why would you need to obtain the default flow step when defining an additional one? The dataflow library will combine the default and additional steps when building the dataflow graph.

**Comment by Roarcannotprogramming** [comment]
Thank you for your responses. I'd like to provide some clarifications and follow-up questions based on your feedback:

My apologies for the confusion regarding my first point. My question was aimed more at the lack of internal data flow within each function. For example, why is there no data flow from 0xdeadbeef to q->baz.bar->foo->a.
Based on my understanding, there should be a data flow from 0xdeadbeef to a in test_struct_1; from 0xdeadbeee to a in test_struct_2; and from c to a in both test_struct_3 and test_struct_4. Similarly, in test_struct_5, the expected flows are from d to a, c to a, with QlClass being FieldAccess to FieldAccess.
After modifying the test_basic function as follows, I indeed observed a data flow with the sink as c. Does this imply that the CodeQL database collects compiler optimization information during compilation? That's truly fascinating.
```
int test_basic() {
    int a;
    int b;
    int c;

    a = 1;
    b = a;
    c = a + b;
    return c;
}
```
Regarding the "default flow step", I am interested in understanding how CodeQL defines the edges in data flow. This knowledge is essential for me to identify which additional edges need to be defined, to avoid redundantly testing for the existence of certain edges.
Looking forward to your insights. Thank you.

**Comment by MathiasVP** [comment]
> > 3. **Missing Data Flow in `test_basic`**: Why is there no data flow from any expression to c in the function test_basic?
>
> That's a little curious indeed. Could you add a bit of code to the function that uses c? Perhaps things got removed because the variable is never used.

The sink is specified to be an `Expr`, and in your example:
```cpp
void test_basic() {
    int a;
    int b;
    int c;

    a = 1;
    b = a;
    c = a + b;
}
```
there is no use of `c` as an expression: there's an declaration that declares `c` as a local and uninitialized variable (which is not an expression), and then there's a `AssignExpr` that writes the value of `a + b` to `c` - that's the `AddExpr`s you see in your output.

**Comment by Roarcannotprogramming** [comment]
Thank you for your explanation.   @MathiasVP 
I think I've understood it. I rewrote test_struct_1.

```c
void test_struct_1() {
    struct qux *q;
    q->baz.bar->foo->a = 0xdeadbeef;
    if(q) {
        if (q->baz.bar) {
            if (q->baz.bar->foo) {
                q->baz.bar->b = 0xdeadbeef;
            }
        }
    }
}
```
In this way, there is still no data flow from 0xdeadbeef to a.

But

```c
void test_struct_1() {
    struct qux *q;
    q->baz.bar->foo->a = 0xdeadbeef;
    if(q) {
        if (q->baz.bar) {
            if (q->baz.bar->foo) {
                if (q->baz.bar->foo->a == 0xdeadbeef) {
                    q->baz.bar->b = 0xdeadbeea;
                }
            }
        }
    }
}
```
In this version, there is a data flow from 0xdeadbeef to a.

The difference between them is "a new reference".
