### ISSUE TITLE
Failed to load semmle.go.controlflow: "Could not resolve module semmle.go.controlflow" 

### ISSUE THREAD

**Issue by g3rzi** [github/codeql#15469]
I am using the [vscode-codeql-starter](https://github.com/github/vscode-codeql-starter) as workspace.  

I am using Visual Studio Code with CodeQL extension and Golang. I am able to run CodeQL queries from the CodeQL repository.  
I created my own query file inside the [codeql-custom-queries-go](https://github.com/github/vscode-codeql-starter/tree/main/codeql-custom-queries-go) directory.   

This is my file content:  
```ql
import go
import semmle.go.controlflow
```

I am getting error: "Could not resolve module semmle.go.controlflow"  

I tried to run `codeql database analyze` but it didn't help:
```
PS D:\CodeQL\vscode-codeql-starter\codeql-custom-queries-go> codeql database analyze D:\CodeQL\databases\portainer .\MyQuery.ql --format=csv --output=output.cs
Running queries.
Stingpool size measured as 7373194
Compiling query plan for D:\CodeQL\vscode-codeql-starter\codeql-custom-queries-go\MyQuery.ql.
ERROR: Could not resolve module semmle.go.controlflow (D:\CodeQL\vscode-codeql-starter\codeql-custom-queries-go\MyQuery.ql:3,8-29)
ERROR: Query module does not have any queries in scope. (D:\CodeQL\vscode-codeql-starter\codeql-custom-queries-go\MyQuery.ql:1,1-1)
```

My `qlpack.yml`:  
```
# Change 'getting-started' to the name of a user or organization that you have write access to.
name: getting-started/codeql-extra-queries-go
version: 0.0.0
dependencies:
  # This uses the latest version of the codeql/go-all library.
  # You may want to change to a more precise semver string.
  codeql/go-all: "*"
```

**Comment by smowton** [comment]
`semmle.go.controlflow` is a directory but not itself a module. Try for example `import semmle.go.controlflow.ControlFlowGraph`.

**Comment by g3rzi** [comment]
Thank you!
