### ISSUE TITLE
When I run database analyse for cpp, the exported sarif is empty while bqrs contains many warnings

### ISSUE THREAD

**Issue by totocaca123** [github/codeql#15514]
I run codeql database analyse and I run a generic cpp pack (misra or cert). 
My database is ok, and I export to sarif (or csv), there is no warning.
I go to databe/result and I decode all bqrs files into csv, I find many warnings

It semms queries are well performed. But when all bqrs are parsed, merged and converted into sarif, it fails (sarif file is 15Mo but no warning inside). I trued to export into csv, it produces a empty csv.

**Comment by aibaars** [comment]
CodeQL filters out all results that are outside the "source root". Could you check that the paths reported by `codeql decode bqrs` start with the `sourceLocationPrefix` defined in the `codeql-database.yml` file in the database folder?

**Comment by totocaca123** [comment]
I checked the path and as I created my database in subsub folder of my root project, it was filtered. I run the database create command line on root path, and I created my database at leve //codql_prj/mydatabase. Results are not filtered anymore.
Now it works fine, thanks
