### ISSUE TITLE
eliminate GuardConditions that are part of Assertions in cpp

### ISSUE THREAD

**Issue by zyfeng-go** [github/codeql#15512]
Hi there,

I'm wondering is there a good strategy to filter out guard conditions that are actually Assertions in cpp, for example, `assert(image != (Image *) NULL)` is an assertion, and `image != (Image *) NULL` is a guard condition. I've tried using `not assert.getAsserted() = guardcondition` since they're both expressions, but it does not work. Any suggestions would be appreciated. Thank you.

[Edit]: I ended up using `not assert.getAsserted().toString() = guardcondition.toString()`, the results seem okay, but I'm not sure if that's the right way to do that.

**Comment by MathiasVP** [comment]
Hi @zyfeng-go,

I'm glad you found a solution. However, your first solution works fine for me. On this database:
```cpp
#include <assert.h>

int main(int argc, char* argv[]) {
	assert(argc > 1);
	return 0;
}
```
this query returns 0 results:

```ql
import cpp
import semmle.code.cpp.controlflow.Guards
import semmle.code.cpp.commons.Assertions

from GuardCondition gc
where not gc = any(Assertion assert).getAsserted()
select gc
```

A couple of follow-up questions:
1. Which version of CodeQL are you running? We [completely replaced](https://github.com/github/codeql/pull/14992) the `GuardCondition` library in CodeQL version 2.16.1, so if you're running anything lower than that it may be worth checking the behavior on on the latest release.
2. The line `not assert.getAsserted() = guardcondition` makes me think your logic may have been wrong. You need to phrase it as "the guard condition is not equal to _any_ assertion's asserted expression". Note that this is different from the phrase "the guard condition is not equal to this assertion's asserted expression". That is, there's a difference between:
```ql
import cpp
import semmle.code.cpp.controlflow.Guards
import semmle.code.cpp.commons.Assertions

from GuardCondition gc, Assertion assert
where not gc = assert.getAsserted()
select gc
```
and
```ql
import cpp
import semmle.code.cpp.controlflow.Guards
import semmle.code.cpp.commons.Assertions

from GuardCondition gc
where not gc = any(Assertion assert).getAsserted()
select gc
```
the first example says "select a `gc` that is not equal to some assertion's asserted expression", and the second example says "select a `gc` that is not equal to _any_ assertion's asserted expression". The last one is most likely the interpretation that you want.

**Comment by zyfeng-go** [comment]
Hello @MathiasVP,

Thank you very much for your insights and clarifications. Apologies for any confusion caused by my initial explanation.

_Please allow me to describe the situation again._ My objective is to identify if there exists a guard condition that secures the basic block where a pointer parameter is dereferenced in the _WriteBlob_ function.

```
MagickExport ssize_t WriteBlob(Image *image,const size_t length,
  const unsigned char *data)
{
  BlobInfo
    *magick_restrict blob_info;

  int
    c;

  register const unsigned char
    *p;

  ssize_t
    count;
  assert(image != (Image *) NULL);
  assert(image->signature == MagickCoreSignature);
  assert(image->blob != (BlobInfo *) NULL);
  assert(image->blob->type != UndefinedStream);
  if (length == 0)
    return(0);
  assert(data != (const unsigned char *) NULL);
  blob_info=image->blob;
  count=0;
  p=data;
  .......
  .......
  .......
```

In the results of the following query, `image != (Image *) NULL`, `image->signature == MagickCoreSignature`, `image->blob != (BlobInfo *) NULL` and `image->blob->type != UndefinedStream` are recognized as qualified guard conditions. However, they are (part of) assertion statements, and thus do not meet the criteria I'm seeking. Those instances are not excluded even though I explicitly set the restraint `and not g = any(Assertion assert).getAsserted()`.

```
import cpp
import semmle.code.cpp.controlflow.Guards
import semmle.code.cpp.commons.Assertions
import semmle.code.cpp.dataflow.new.DataFlow

 // pointer arg 
 class PointerArg extends Parameter {
    PointerArg() { this.getType() instanceof PointerType } 
}

from
    DataFlow::Node source,
    DataFlow::Node sink, 
    Function function,
    GuardCondition gc,
    PointerArg pointerArg,
    PointerFieldAccess pointerFieldAccess,
    Expr sink_expr
where
    source = DataFlow::parameterNode(pointerArg)
    and function = source.getFunction()
    and function.hasName("WriteBlob")
    and not pointerFieldAccess.getEnclosingStmt() instanceof IfStmt
    and sink_expr = pointerFieldAccess.getQualifier*()
    and sink = DataFlow::exprNode(sink_expr)
    and DataFlow::localFlow(source, sink)
    and exists ( GuardCondition g |
        gc = g
        and not g = any(Assertion assert).getAsserted() |
        g.controls(pointerFieldAccess.getBasicBlock(), _)
    )
select
    source, sink, gc
```

**Version of CodeQL CLI**: v2.15.5
**Compiler**: GCC 11.4.0

I wasn't aware that `GuardCondition` was removed and I checked the [link](https://github.com/github/codeql/pull/14992) you included upon your suggestion. I am curious about the rationale behind this decision. What advantages does `IRGuardCondition` offer over `GuardCondition`, apart from "potentially" enhanced accuracy? Given that my current work is heavily reliant on `GuardCondition`, I'd rather still use `GuardCondition` if I don't have to switch :(

**Comment by MathiasVP** [comment]
> I wasn't aware that `GuardCondition` was removed and I checked the [https://github.com/github/codeql/pull/14992](link) you included upon your suggestion. I am curious about the rationale behind this decision. What advantages does `IRGuardCondition` offer over `GuardCondition`, apart from "potentially" enhanced accuracy? Given that my current work is heavily reliant on `GuardCondition`, I'd rather still use `GuardCondition` if I don't have to switch :(

Indeed, the advantage of the new `GuardCondition` class is that it will catch more guards. It may even be the case that this is why I can't reproduce your problem.

Hopefully you won't notice that we've changed it. There's still a `GuardCondition` class for you to use, but it's now defined as a wrapper around `IRGuardCondition`.

If you find any regressions when using the `GuardCondition` class from 2.16.1 and onwards please do open an issue for it and we'll what we can do to fix it 🙂
