### ISSUE TITLE
cpp - compiler support

### ISSUE THREAD

**Issue by totocaca123** [github/codeql#15530]
**Questions**

- According to https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/, only few compilers are supported. The supported compiler are old versions (clang12 and gcc11). Is there any issue to use latest version og these compilers

- What about other compilers (diab, iar, greenhills, tasking), is there a way to run codeql on these compiled code?

**Comment by jketema** [comment]
> * According to https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/, only few compilers are supported. The supported compiler are old versions (clang12 and gcc11). Is there any issue to use latest version og these compilers

The documentation is somewhat out-of-date, and we'll hopefully fix this soon. Newer versions should generally work. If not, please let us know by opening issues on this.

> * What about other compilers (diab, iar, greenhills, tasking), is there a way to run codeql on these compiled code?

Those compilers are not supported. If your code also compiles with clang or gcc, I'd recommend using those. If the compilers still identify themselves are being based on clang or gcc in their `--version` string, things might still work but we cannot guarantee anything.

**Comment by jketema** [comment]
Closing as answered.
