### ISSUE TITLE
General issue [cpp]  Bug when using Macro  in query

### ISSUE THREAD

**Issue by dragoudin** [github/codeql#15538]
**Description of the issue**

- I have a cpp query very simple

```
import cpp

from Macro m
where
  ( 
```

- I use vscode extension and I have an error

![image](https://github.com/github/codeql/assets/94975153/842c8703-5590-4537-a34c-b8bc11c15d2b)
And error text is 
```
Preprocessor::PreprocessorDirective.extends incompatible with @using \/ @stmt_constexpr_if \/ @stmt_range_based_for \/ @stmt_switch \/ @stmt_for \/ @stmt_end_test_while \/ @stmt_block \/ @stmt_while \/ @stmt_if \/ @isvolatile \/ @isvoid \/ @isunsigned \/ @issigned \/ @isscalar \/ @isrvaluereference \/ @isreference \/ @ispointer \/ @isobject \/ @ismemberpointer \/ @ismemberobjectpointer \/ @ismemberfunctionpointer \/ @islvaluereference \/ @isintegral \/ @isfundamental \/ @isfloatingpoint \/ @isconst \/ @iscompound \/ @iscompletetype \/ @isarithmetic \/ @arrayextent \/ @arrayrank \/ @isarray \/ @ispointerinterconvertiblebaseof \/ @islayoutcompatible \/ @isfunction \/ @issame \/ @blockassignexpr \/ @builtinshuffle \/ @builtinbitcast \/ @hasuniqueobjectrepresentations \/ @isaggregate \/ @isassignable \/ @temp_init \/ @co_yield \/ @co_await \/ @spaceshipexpr \/ @builtincomplex \/ @builtinconvertvector \/ @vec_fill \/ @builtinaddressof \/ @builtinchooseexpr \/ @builtinshufflevector \/ @noexceptexpr \/ @isfinalexpr \/ @isvalueclassexpr \/ @issimplevalueclassexpr \/ ...(227 other disjuncts) in context
```

- When I run the command line, I have the following message
```
Compiling query plan for C:\XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\export_macros.ql.
ERROR: Preprocessor::PreprocessorDirective.extends incompatible with @using \/ @stmt_constexpr_if \/ @stmt_range_based_for \/ @stmt_switch \/ @stmt_for \/ @stmt_end_test_while \/ @stmt_block \/ @stmt_while \/ @stmt_if \/ @isvolatile \/ @isvoid \/ @isunsigned \/ @issigned \/ @isscalar \/ @isrvaluereference \/ @isreference \/ @ispointer \/ @isobject \/ @ismemberpointer \/ @ismemberobjectpointer \/ @ismemberfunctionpointer \/ @islvaluereference \/ @isintegral \/ @isfundamental \/ @isfloatingpoint \/ @isconst \/ @iscompound \/ @iscompletetype \/ @isarithmetic \/ @arrayextent \/ @arrayrank \/ @isarray \/ @ispointerinterconvertiblebaseof \/ @islayoutcompatible \/ @isfunction \/ @issame \/ @blockassignexpr \/ @builtinshuffle \/ @builtinbitcast \/ @hasuniqueobjectrepresentations \/ @isaggregate \/ @isassignable \/ @temp_init \/ @co_yield \/ @co_await \/ @spaceshipexpr \/ @builtincomplex \/ @builtinconvertvector \/ @vec_fill \/ @builtinaddressof \/ @builtinchooseexpr \/ @builtinshufflevector \/ @noexceptexpr \/ @isfinalexpr \/ @isvalueclassexpr \/ @issimplevalueclassexpr \/ ...(219 other disjuncts) in context 
(C:\XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\export_macros.ql:4,6-13)
```
I use latest version of codeql 2.16.1 (this query was working fine few months ago)

**Comment by aeisenberg** [comment]
Can you please share the full query?

**Comment by dragoudin** [comment]
Here is my full query (very simple) and before to run the codeql query on vscode there is a red message. 
`import cpp

from Macro m
where not m.getFile().getAbsolutePath().regexpMatch(".*(START|STOP)_SEC_.*")
select m.getLocation(), m.getName(), m.getBody(), m.getParentScope(), m.getFile().getBaseName()

`

It seems the problem comes from the Macro class as I see bo error.
I use codeql version 2.16.1

I use

**Comment by aeisenberg** [comment]
Thanks for the full query. I can reproduce with a simpler example.

```
import cpp

from Macro m
select m.getParentScope()
```

Let me discuss with the compiler team.

**Comment by aeisenberg** [comment]
Thanks, @intrigus-lgtm. That's exactly correct. I misinterpreted the error message (and was just about to post that). The fact that there is an error is correct. However, it is not particularly user friendly. We are thinking of ways of making this better to use.

In the meantime, simply remove the `m.getParentScope()` clause and your query will compile.

**Comment by dragoudin** [comment]
I removed the call m.getParentScope() and my query works fine

That's a good workaround as this info is useless for my case, but the error message in vscode  indicates the macro class instead of the wrong function m.getParentScope() 
Thanks

**Comment by aeisenberg** [comment]
Thanks for confirming your workaround. We're now tracking internally this via an issue to improve the error message.
