### ISSUE TITLE
[Java][UrlRedirect] False positive when doing string concat

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#15553]
**Description of the false positive**
I have this following code : 
```
@Override 
		public Response redir(String param){

			try {
				URI someUrl = new URI("http://example.org/?query=" + param);
				return Response
						.seeOther(someUrl)
						.build();
			} catch (URISyntaxException e) {
				throw new WebApplicationException("URI Syntax", e);
			}
		}
```

<img width="598" alt="Screenshot 2024-02-08 at 13 29 01" src="https://github.com/github/codeql/assets/20141746/b8b7675b-5dba-4d74-912c-f7805257f871">

As you can see there is not a lot of value of having this alert, because the base URL is not user controlled, so it would make sense to define a sanitizer such as if user input is on the RHS of a concat expression, we should disregard it or at the very least have an interface sanitizer that can be used in customizations

We should probably have a sanitizer interface here (e.g node instanceof UrlRedirectSanitizer)  https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/security/UrlRedirectQuery.qll#L10-L18  so that we can customize it

**Comment by aeisenberg** [comment]
Thanks for this issue. I'm not sure I agree with this being a false positive. The user has control over the search parameters being passed to the redirected URL. In some cases, this may be a false positive, but it seems dangerous enough in the general case that I would still consider this vulnerable. There is some degree of opinion here. I will bring it up with the Java team to see if they have a different understanding.

**Comment by chmodxxx** [comment]
Can we at least have a sanitizer interface like https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/security/JndiInjectionQuery.qll#L24 so that we can customize it ?

**Comment by atorralba** [comment]
Hi @chmodxxx. I think you're right on both counts. The query for SSRF does have sanitization for this kind of thing (prepending a string that prevents the host/IP of the URL to be modified), so I think the logic should apply equally to Open Redirect. _And_ also we should have an extension point for sanitizers in the Open Redirect query, as we have in almost all other dataflow queries. Thanks for the report, we'll handle this.

@aeisenberg has a point about modifying the path or query parameters of the URL being potentially dangerous as well, but in our experience those are FPs most of the time, so if we really want to handle them we should do so in a different, medium-precision query.

**Comment by aeisenberg** [comment]
Thanks for weighing in, @atorralba. This makes sense.
