### ISSUE TITLE
PowerShell keeps open file handle to build-tracer.log when using indirect build tracing

### ISSUE THREAD

**Issue by philipp-naused** [github/codeql#15572]
When I use [indirect build tracing](https://docs.github.com/en/code-security/codeql-cli/getting-started-with-the-codeql-cli/preparing-your-code-for-codeql-analysis#using-indirect-build-tracing) from a PowerShell command line, PowerShell opens a file handle to `\log\build-tracer.log` in the database and never closes it.

Even after running `\temp\tracingEnvironment\end-tracing.ps1` and `codeql database finalize`, the handle stays open, and I cannot delete the db until I close PowerShell.

Example:
1. Extract [codeql-bundle-v2.16.1](https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.16.1/codeql-bundle-win64.tar.gz) to an empty folder.
2. Run `dotnet.exe new console` to generate a basic C# project. (Other languages would probably work too.)
3. Run this script in PowerShell:
```pwsh
.\codeql\codeql database init --language 'csharp' --trace-process-level=0 --begin-tracing --source-root=. 'db'
.\db\temp\tracingEnvironment\start-tracing.ps1
dotnet.exe build -target:Rebuild
.\db\temp\tracingEnvironment\end-tracing.ps1
.\codeql\codeql database finalize 'db'
Remove-Item 'db' -Recurse -Force
```

Result: I cannot delete the folder `db` because `The process cannot access the file '...\db\log\build-tracer.log' because it is being used by another process.`

I used handle.exe from sysinternals to check that it is PowerShell.
Once I close the shell, I can remove the db.

This happens on both Windows PowerShell 5.1 and PowerShell Core 7.4.

I've tested this on both Windows 10 and Windows Server 2022.

I have attached the log file if that helps:
[build-tracer.log](https://github.com/github/codeql/files/14223945/build-tracer.log)

**Comment by aeisenberg** [comment]
Thanks. For reporting and for the clear reproducibility instructions. I can reproduce locally, but I am not familiar with how the tracer works on windows. I'll contact the team to ask.

**Comment by aeisenberg** [comment]
The `--trace-process-level=0` option indicates that the tracer should be injected into the current process (ie- powershell). One way around this is to wrap the calls to build the database into a separate script. After the script exits, then the open `build-tracer.log` file will be closed and can be deleted.

**Comment by philipp-naused** [comment]
PowerShell doesn't start a new process when calling a script. The workaround we're using is to explicitly start a new process:

```pwsh

pwsh.exe -c @"
.\codeql\codeql database init --language 'csharp' --trace-process-level=0 --begin-tracing --source-root=. 'db'
.\db\temp\tracingEnvironment\start-tracing.ps1
dotnet build -target:Rebuild
.\db\temp\tracingEnvironment\end-tracing.ps1 // this line is likely redundant
"@
.\codeql\codeql database finalize 'db'
```

**Comment by aeisenberg** [comment]
That's the approach that I would recommend.

**Comment by philipp-naused** [comment]
@aeisenberg I wasn't trying to ask a question or search for a workaround. I was trying to report a bug.
Why did you close the issue? This bug hasn't been fixed.

Or are you saying that this is working as intended?

**Comment by aeisenberg** [comment]
Yes. This is the intended behaviour. In order to perform tracing, we need to determine which process to hook into to observe build steps. The log file stays open while that process is still running. I understand that this isn't ideal if you're trying to clean up after analyzing in the same process, but there is a workaround.

**Comment by philipp-naused** [comment]
@aeisenberg Understood, thanks for clarifying.
