### ISSUE TITLE
Yaml scripts appear to be non-executable

### ISSUE THREAD

**Issue by s0i37** [github/codeql#15598]
In prebuild codeql (https://github.com/github/codeql-cli-binaries) contains many non executable .sh scripts.

For example:
`codeql database create -v test --language=python`

The error occuried:
`A fatal error occurred: yaml extractor yaml does not provide file-indexing capabilities`

Solve:
```
cd yaml/tools/
chmod +x *.sh
```

**Comment by smowton** [comment]
I double-checked, and the latest release of CodeQL does not seem to have this problem. What platform are you on and what release version did you download?

**Comment by s0i37** [comment]
According to my bash_history - `https://github.com/github/codeql-cli-binaries/releases/download/v2.16.2/codeql-linux64.zip`
My system is `Debian x64`.
Thank you!

**Comment by smowton** [comment]
I downloaded and checked that zip and can confirm the yaml shell scripts unzip with the executable bits set. I can only conclude it must have originally been unzipped to a filesystem that doesn't preserve the executable bit, or in some other way was made non-executable after unzipping.
