### ISSUE TITLE
Global taint tracking time complexity?

### ISSUE THREAD

**Issue by odipar** [github/codeql#15690]
I wonder if it is possible to get a general idea of the time complexity of global traint tracking?
For example, let's say we have the following variables:

#nodes = total number of nodes (linear to the size of the code base) 
#source = number of source nodes
#sink = number of sink nodes
#depth = average depth of path

My assumption is that the total complexity is O(#source * #sink * #depth), indifferent to #nodes?

**Comment by aschackmull** [comment]
If I were to reduce the worst-case complexity to depend on just a single variable `n` being the size of the code base, then the complexity would be `O(n^k)` where `k` is just about 25, as far as I could count.

**Comment by odipar** [comment]
So that means if your code size grows 10 times bigger, there will be 10^25 more work? 
Indeed, the worse case complexity is *much much* worse than I thought.

**Comment by aschackmull** [comment]
> So that means if your code size grows 10 times bigger, there will be 10^25 more work?

Potential work in the worst case, yes, that's right (caveat, 25 might not be exactly right - it's a rough estimate based on a quick count). But again, the average case never really hits the worst case, so the typical experience is more like `O(n)`.

> Indeed, the worse case complexity is _much much_ worse than I thought

Yes.
