### ISSUE TITLE
Ruby ActiveRecord modeling misses multilevel inheriting classes

### ISSUE THREAD

**Issue by MaxSchlueter** [github/codeql#15697]
**Description of the issue**

This piece of code is very common in Ruby on Rails apps:

```rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

class Person < ApplicationRecord
  self.site = "https://api.example.com"
end
```

The following query:

```ql
query predicate modelClassNodes(ActiveResource::ModelClassNode c) { any() }
```

is missing the `Person` class in the results, that transitively inherits from  `ActiveRecord::Base`.

**Comment by alexrford** [comment]
Have you tried using `ActiveRecordModelClass` from `ActiveRecord.qll` in the query rather than `ActiveResouce::ModelClassNode`?

**Comment by MaxSchlueter** [comment]
You are right, I got confused with the similar sounding classes. Sorry for the noise!
