### ISSUE TITLE
Create AOSP C/C++ database in a easy way ?

### ISSUE THREAD

**Issue by SunBK201** [github/codeql#15860]
Is there an easy way to create an AOSP CodeQL database? AOSP contains a large amount of Java and C++ code at the same time, and I only care about C++ code, so whether there is a simple or hacking way to create a CodeQL database only for C++ and skip compiling Java code.

**Comment by jketema** [comment]
Hi @SunBK201. Thanks for your question. Unfortunately, this is ultimately a question about the AOSP build system, and not related to CodeQL. Hence, not something we can help you with.
