### ISSUE TITLE
Mapping CWEs to a Codeql Query

### ISSUE THREAD

**Issue by saikatG** [github/codeql#15892]
Hi,

What is the best way to check if there is an existing query for a particular CWE?

For instance, I was looking for a Java query for [CWE-130](https://cwe.mitre.org/data/definitions/130.html), but I did not find one.

Does that mean existing queries do not cover it?

Secondly, is there a way to run database analyze with some queries just by using their id(s)? Additionally, is there a way to include/exclude some queries when running a query pack? 

I am using codeql-cli btw.

Thanks in advance!

**Comment by jketema** [comment]
Hi @saikatG,

Thanks for your questions.

> What is the best way to check if there is an existing query for a particular CWE?

Probably the easiest is to look at the list here: https://codeql.github.com/codeql-query-help/codeql-cwe-coverage/

> For instance, I was looking for a Java query for [CWE-130](https://cwe.mitre.org/data/definitions/130.html), but I did not find one.
> 
> Does that mean existing queries do not cover it?

Generally, there are two cases. Either it is not covered, or there is child or parent CWE that is covered. In the case of CWE-130, it seems to be the former.

> Secondly, is there a way to run database analyze with some queries just by using their id(s)? Additionally, is there a way to include/exclude some queries when running a query pack?

Probably the easiest way to do this is by defining your own query suite and pass that to the CLI. The defining new query suites is explained here: https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/creating-codeql-query-suites

**Comment by saikatG** [comment]
Thanks @jketema! 

Another question regarding analyzing a javascript project: What is the best way to ensure that codeql can analyze/step into the npm modules that are used? For instance, I have a folder with a js file that calls some third-party libraries. I have installed all the npm modules in the same folder. Is that enough when codeql creates a database? In this case, I know there is a vulnerability in a third-party library that my js file can trigger.

**Comment by jketema** [comment]
You will need to check whether the npm modules are actually included in the database. Possibly the easiest way to do this is to create the database and write a simple query that queries for something that is located in the module, and not used directly by jour js script.
