### ISSUE TITLE
How to pass custom settings.xml for java instead of fetching it from .m2 folder

### ISSUE THREAD

**Issue by AshwinSridharan0410** [github/codeql#15938]
I have some packages/dependencies which needs to be fetched from my private repository. But Codeql , it takes the .m2 folder by default. 
In the codeql database create command , how to pass my settings.xml so that it fetches this and builds it rather than taking settings.xml from .m2 folder.
@jketema  @owen-mc

**Comment by AshwinSridharan0410** [comment]
codeql database create  "javatest " --language "java"  --source-root="."
pom.xml is present at the current working directory

**Comment by jketema** [comment]
Thanks. What you can do is explicitly specify the build command when creating the database. So, something like:
```
codeql database create "javatest " --language "java" --source-root="." --command"mvn --settings YourOwnSettings.xml clean install"
```
where `mvn --settings YourOwnSettings.xml clean install` should be replaced by the usual command you use to build your application.

**Comment by AshwinSridharan0410** [comment]
Thanks @jketema for the help.
