### ISSUE TITLE
Python: clear-text logging of X.509 certificate

### ISSUE THREAD

**Issue by woodruffw** [github/codeql#15942]
**Description of the false positive**

In Python codebases, CodeQL appears to detect `cryptography.x509.Certificates` and treat them as sensitive materials, resulting in an advisory whenever CodeQL is able to observe dataflow from a `Certificate` object to an output or sink (e.g. `print(...)`).

CodeQL treats this as "Clear-text logging of sensitive information," which is incorrect: X.509 certificates are _definitionally_ public materials, as evidenced by the fact that they carry public keys and are typically exported via functions with "public" in their name, like [`cert.public_bytes(...)`](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.public_bytes). 

As such, I believe this is a false positive: CodeQL may choose to flag these for interest, but they are neither sensitive material nor a "High" severity finding.

**Code samples or links to source code**

Here's an example finding, demonstrating the false positive: https://github.com/sigstore/sigstore-python/security/code-scanning/71

**Comment by alex** [comment]
From the perspective of a pyca/cryptography core developer, I absolutely concur. In general, there's no expectation that a certificate be expected to be secret.

**Comment by jketema** [comment]
Hi @woodruffw,

Thank you for this false positive report. Resolving false positives is currently not a priority for us, but we hereby acknowledge the report and will track it internally for future consideration. Note that we also accept external contributions, just in case you want to have a stab at fixing this yourself.

**Comment by woodruffw** [comment]
> @woodruffw 
> 
> Exclude these variables or objects from being considered sensitive in your data flow analysis. You can do this by adding conditions to your queries that exclude these types from being flagged as sensitive.

I understand that I can do this. However, that's not the point: the point is that the entire concept of a "sensitive" certificate is incorrect, and shouldn't have been added in the first place. Regardless of whether I patch this for my own codebases, this still requires upstream addressing.

**Comment by Malikrehman00107** [comment]
I see!

**Comment by sidshank** [comment]
@woodruffw @alex As of CodeQL `2.18.4`, we [no longer X.509 certificates to be sources of sensitive data](https://github.com/github/codeql/pull/17314).

**Comment by woodruffw** [comment]
That's great news, thanks a ton @sidshank!
