### ISSUE TITLE
Is default setup of Codeql blocking the (SARIF file)results from my external CI ?

### ISSUE THREAD

**Issue by AshwinSridharan0410** [github/codeql#15950]
I am trying to push the results from my existing CI to github . I am using **codeql github upload results** command .The API call tells me this :-

```
{
    "message": "Not Found",
    "documentation_url": "https://docs.github.com/rest/code-scanning/code-scanning#get-information-about-a-sarif-upload"
}
```

This is the output when I fetch the SARIF file that is trying to upload to the github

```
{
  "processing_status": "failed",
  "errors": [
    "CodeQL analyses from advanced configurations cannot be processed when the default setup is enabled"
  ]
}
```

Is it due to the default set-up of codeql already enabled ?

**Comment by smowton** [comment]
It seems yes -- can you try disabling CodeQL default setup (which seeks to run CodeQL on Github Actions) and then try again uploading from your own non-Actions CI?

**Comment by AshwinSridharan0410** [comment]
Yes, thanks for your comments. It worked.
