### ISSUE TITLE
JavaScript: (CodeQL Customization) The `Instance` access path component does not match subclasses of the selected class

### ISSUE THREAD

**Issue by mbaluda** [github/codeql#15999]
**Description of the issue**

It should be possible to use the `Instance` access path component to match objects based on their abstract class

For example, it would allow accessing `req` in the following code
```Javascript
import cds from '@sap/cds'
class SampleVulnService extends cds.ApplicationService { init(){
  this.on ('submitOrder', async req => {
    const {book,quantity} = req.data
```
with the path
```
["@sap/cds",
 "Member[ApplicationService].Instance.Member[on].Argument[1].Parameter[0]", 
 "remote"]
```

**Comment by asgerf** [comment]
Draft PR in https://github.com/github/codeql/pull/16136

**Comment by asgerf** [comment]
@mbaluda The above PR has been merged so I'm going to close the issue.

And thanks for the feedback! ✨  It's very valuable to have feedback like this to ensure we're making the right design choices in MaD.
