### ISSUE TITLE
Disable js/unsafe-external-link by default

### ISSUE THREAD

**Issue by nightpool** [github/codeql#15995]
**Description of the false positive**

Modern browsers do not provider the `opener` attribute on `target="_blank"` links. This is the same criteria that js/unsafe-external-link uses to determine whether a link may be vulnerable. From MDN:

> in newer browser versions setting target="_blank" implicitly provides the same protection as setting rel="noopener". See [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#browser_compatibility) for details.

This is true as of Chrome 88 (January 2021), Firefox 79 (July 2020), Opera 74 (February 2021), and Safari 12.1 (March 2019), as per browser-compat-data (https://github.com/mdn/browser-compat-data/blob/main/html/elements/a.json#L330). 

This is a very high-occurrence rule in many repositories, and since 2021 it provides very little security benefit (Especially since many of the occurrences in backend repositories may relate to email templates, which are not affected by the issue since they do not display in same-domain contexts). I would recommend disabling this rule by default for the standard security ruleset, and providing it as an explicit opt-in for 

**Code samples or links to source code**

```html
  <a class="comment-reason" target="_blank" ng-href="{{ comment.reason.context_url }}" ng-if="comment.reason">
```

**URL to the alert on GitHub code scanning (optional)**

I ran codeql on discourse main branch to generate these example alerts:

 * https://github.com/nightpool/discourse/security/code-scanning/1
 * https://github.com/nightpool/discourse/security/code-scanning/2
 * https://github.com/nightpool/discourse/security/code-scanning/3
 * https://github.com/nightpool/discourse/security/code-scanning/4

These show the low specificity of this rule (4/4 are internal links, 0/4 are vulnerable in modern browsers (due to using `_blank`), 2/4 are used in emails). We saw 30 of these alerts on our internal closed-source Ruby codebase, with similar ratios (almost all internal links, all using `_blank`, about 50% used in email)

**Comment by erik-krogh** [comment]
Thanks for the report. It is something that has come up before, and I think now is a good time to actually do the change. 

I've lowered the `@precision` of the query to `low`, such that it doesn't show up in any of the default query suites.  
See this PR: https://github.com/github/codeql/pull/16002

I think the change should land in 2.17.0, which should come out in some weeks time.

**Comment by nightpool** [comment]
Thanks Erik! Great to see this get quickly triaged, and hugely appreciated.
