### ISSUE TITLE
How to create a mapping of key value pairs?

### ISSUE THREAD

**Issue by KylerKatz** [github/codeql#16080]
Hello,

Is there a way to create a mapping in CodeQL

Since codeql doesn't support hashmaps I can't directly do something like this. I am curious if anyone knows of a way to accomplish this? Thank you.

**Comment by intrigus-lgtm** [comment]
How about this?

```ql
string getASuspiciousStringForFile(string filename) {
  filename = "file1" and result = ["password", "password2", "username"]
  or
  filename = "file2" and result = ["something", "anotherthing", "pin"]
}

**Comment by Malikrehman00107** [comment]
import os

# Dictionary to store sensitive variables and their corresponding files
sensitive_variables = {}

# Function to recursively traverse directories
def traverse_directory(directory):
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith(".java"):  # Assuming Java files, adapt for your language
                process_file(os.path.join(root, file))

# Function to process each file
def process_file(file_path):
    with open(file_path, "r") as f:
        lines = f.readlines()
        for line in lines:
            if "password" in line or "username" in line:  # Example criteria for sensitive variables
                # Add sensitive variable to dictionary with file name
                sensitive_variables.setdefault(file_path, []).append(line.strip())

# Example usage
traverse_directory("/path/to/codebase")

# Output sensitive variables with file associations
for file, variables in sensitive_variables.items():
    print(f"{file}: {variables}")

**Comment by adityasharad** [comment]
@KylerKatz I second @intrigus-lgtm's suggestion above. 
An alternative but equivalent way of writing the same logic, that may be slightly easier to generate from your external script, would be to have both the filename and the variable name as predicate parameters:
```ql
predicate suspicious(string fileName, string variableName) {
  // Less verbose but harder to autogenerate
  fileName = "file1" and variableName = ["password", "password2", "username"]
  or
  filename = "file2" and variableName = ["something", "anotherthing", "pin"]
}
```
or
```ql
predicate suspicious(string fileName, string variableName) {
  // More verbose but easier to autogenerate
  fileName = "file1" and variableName = "password"
  or
  fileName = "file1" and variableName = "password2"
  or
  fileName = "file1" and variableName = "username"
  or
  filename = "file2" and variableName = "something"
  or
  filename = "file2" and variableName = "anotherthing"
  or
  filename = "file2" and variableName = "pin"
}
```

Finally, another possible integration point is to use some new CodeQL features, known as "data extensions" and "model packs": see documentation [here](https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/publishing-and-using-codeql-packs#qlpackyml-properties) and [here](https://codeql.github.com/docs/codeql-language-guides/customizing-library-models-for-java-and-kotlin/#about-data-extensions). The docs mostly describe how to use data extensions and model packs to populate sources and sinks for the default analysis, but you can use a similar mechanism to provide any set of data to the analysis.

You can do this by creating a YAML file, say `models/suspicious.model.yml`, within your query or library pack, with the following contents:
```yaml
extensions:
  - addsTo:
      pack: your-user-or-org-name/your-pack-name
      extensible: suspicious
    data:
      - ["file1", "password"]
      - ["file1", "password2"]
      - ["file1",  "username"]
      - ["file2",  "something"]
      - ["file2",  "anotherthing"]
      - ["file2",  "pin"]
```
Here `your-user-or-org-name/your-pack-name` should match the `name` of the query or library pack you are using, defined in `qlpack.yml` or `codeql-pack.yml`.

Then, in the `qlpack.yml` or `codeql-pack.yml` file, add:
```yaml
dataExtensions:
  - model/*.model.yml
```

Finally, define a CodeQL predicate within your code:
```ql
extensible predicate suspicious(string fileName, string variableName);
```
No need to give this predicate a body -- it will be loaded from the YAML. You can use it like a regular predicate in the rest of your query.

**Comment by adityasharad** [comment]
@Malikrehman00107 I'm sorry to say your answer is not relevant -- it provides Python code to look through a set of files, which is not related to CodeQL, and is not what the original question asked. Helping out the community on this repo is very welcome, however please be careful to make sure your suggestion is directly relevant to the question, and do not create further confusion for those who ask a question.

**Comment by KylerKatz** [comment]
Thank you to all of you for your suggestions I appreciate it. I am currently working on a different aspect of the project but will work on implementing these suggestions when I get back to it. Thank you so much for taking the time to help me.

**Comment by KylerKatz** [comment]
I went with this approach since it made the most sense to me given that I don't know `variableName` when I am calling the suspicious predicate.

```
string suspicious(string fileName) {
fileName = "BAD_LoggingSensitiveInformation.java" and result = ["username", "password"] or
fileName = "BAD_UserDetailsExposure.java" and result = ["userId", "userDetails"] 
}
```

However, I am having some trouble using it. I think it's something simple that I am doing wrong with how I am getting the filename. Currently, I am doing this.

```
class SensitiveVariableExpr extends Expr {
  SensitiveVariableExpr() {
    exists(Variable v, File f | this = v.getAnAccess() and
      f = v.getCompilationUnit().getFile() and
      v.getName().matches(suspicious(f.getBaseName())) and
      not this instanceof CompileTimeConstantExpr
    )
  }
}
```

For some reason I am getting this error.  `getBaseName() cannot be resolved for type FileSystem::File` I am not sure why because it looks to be a [valid](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/FileSystem.qll/type.FileSystem$File.html) function. I am hoping by showing this, that it is clear to someone what I am doing wrong. Basically, I just want CodeQL to know the context of the current file so that I only consider the variables associated with it back from `suspicious()` 

Also, this is how I intend to use it in an actual query.  It's the same as how I used to have it without the mapping functionality, and I think it can remain the same since I am doing the file context checking in `SensitiveVariableExpr` but just wanted to point this out in case that seems like it could be an issue in the future.

```
 override predicate isSource(DataFlow::Node source) {
    exists(SensitiveVariableExpr sve |  source.asExpr() = sve)
  }
  ``` 

Thank you for the help. I really appreciate it.

**Comment by mbg** [comment]
Hi @KylerKatz,

Your definition for `SensitiveVariableExpr` looks OK to me. If I paste it into QL source file that has `import java` along with the definition of `suspicious`, then I see no errors. Are you importing the `java` library? Do you get the error when running the query or in your editor? Do you have the latest versions of the CodeQL CLI and the query packs?

**Comment by KylerKatz** [comment]
@mbg 
Thank you for double-checking for me. It seems to be working now without any changes. Sometimes I get errors from the language server which causes the queries not to compile. However, it's all working now.

**Comment by KylerKatz** [comment]
@adityasharad For the approach that uses data extensions is there a way to read the data in from an external file such as a text or CSV file. Or do you have to inject the data into the .yml file? If not, do you know of another way that would allow me to use an external file's data?

**Comment by adityasharad** [comment]
I would recommend using data extensions with YAML, and preprocessing your other data into the above YAML format first.

There is another, older option [--external](https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/database-analyze#--externalpredfilecsv) that lets you pass in a CSV file (you will have to use `external predicate suspicious` rather than `extensible predicate suspicious` in your QL files). This may be enough for your purpose, but generally it is an older feature that is less documented and supported than data extensions. Data extensions can handle a wider range of primitive types, have better error handling, support integration with CodeQL packs, and don't have to specified at the command line with each run.

**Comment by KylerKatz** [comment]
@adityasharad 

I am trying to see if I can convert my current approach to use your data extension recommendation.

My current approach just embeds the data as so,

```
string map(string fileName) {
fileName = "file1.java" and result = ["Hello"] or
fileName = "file2.java" and result = ["Hello", "World"]
}
```

What I would like to know is two things.
1) Is it possible to just define an extensible predicate as so with one parameter that will return a string array?
`extensible predicate suspicious(string fileName);`
2) If so, how would I represent this in the yml file? This is what I have so far
```
extensions:
  - addsTo:
      pack: custom-codeql-queries
      extensible: suspiciousVariables
    data:
    - ["file1", ["var1", "var2"]] 
    - ["file2", ["var3", "var4"]] 
```
Thank you

**Comment by mbg** [comment]
Hi @KylerKatz 

As @adityasharad previously mentioned, a predicate with a return value is equivalent to a predicate with an extra parameter. You can change

```ql
string map(string fileName) {
  fileName = "file1.java" and result = ["Hello"] or
  fileName = "file2.java" and result = ["Hello", "World"]
}
```

to

```ql
predicate map(string fileName, string str) {
  fileName = "file1.java" and str = ["Hello"] or
  fileName = "file2.java" and str = ["Hello", "World"]
}
```

From a usage point of view, where you may have previously had `foo(map(bar))`, you can then use `exists(string x | map(bar, x) and foo(x))`. 

This will allow you to use `map` with data extensions in the way that @adityasharad described.

**Comment by KylerKatz** [comment]
@mbg 

I am currently getting this error. `SEVERE: Internal error: A 'codeql resolve extensions-by-pack' operation failed with error code 2` which looks to be related to CodeQL not being able to find my predicate.

For context, all my files are in the same Directory. 
My `qlpack.yml` looks like this
```
---
library: false
warnOnImplicitThis: false
name: custom-codeql-queries
version: 0.0.1
dependencies:
  codeql/java-queries: ^0.8.9
dataExtensions:
  - SensitiveInfo.yml
```
`SensitiveInfo.yml` defines the extension and looks like this
```
extensions:
  - addsTo:
      pack: custom-codeql-queries
      extensible: thisIsATest
    data:
      - ["file1.java", "DEBUG_MODE"]
      - ["file2.java", "sensitiveInfo"]

```
`SensitiveInfo.qll` defines the predicate and looks like this
```
module SensitiveInfo {
extensible predicate thisIsATest(string fileName, string str);

class SensitiveVariableExpr extends Expr {
  SensitiveVariableExpr() {
    exists(Variable v, File f | this = v.getAnAccess() and
      f = v.getCompilationUnit().getFile() 
      and
      exists(v.getName().matches(thisIsATest(f.getBaseName(), v))) and
      not this instanceof CompileTimeConstantExpr
    )
  }
}
}
```
I am confused why it's not finding it. 

Also, 

Is an extensible function supported like this? 

`extensible string thisIsATest(string fileName);`

I have tried to use an extensible predicate as shown in `SensitiveInfo.qll` however, I am getting this error as well. 
`Expected a predicate with result but found 'thisIsATest', which is a predicate without result.`

I'd like to just use a string function instead since I just want it to return a value, not a bool with how I am checking using the `"matches"` function. I get this error, however, I am trying to narrow down if it's supported or not.

**Comment by mbg** [comment]
> SensitiveInfo.qll defines the predicate and looks like this

I believe the `extensible predicate` must be at the top-level of the file and cannot be contained within a `module`. In other words, changing your definition to the following may work:

```ql
extensible predicate thisIsATest(string fileName, string str);

module SensitiveInfo {
  class SensitiveVariableExpr extends Expr {
    SensitiveVariableExpr() {
      exists(Variable v, File f | this = v.getAnAccess() and
        f = v.getCompilationUnit().getFile() 
        and
        exists(v.getName().matches(thisIsATest(f.getBaseName(), v))) and
        not this instanceof CompileTimeConstantExpr
      )
    }
  }
}
```

Let me know if this resolves the problem. 

> Is an extensible function supported like this?
> 
> ```ql
> extensible string thisIsATest(string fileName);
> ```

No, it must be of the form `extensible predicate thisIsATest(string fileName, string str)`. As we have said previously, this is equivalent. You should think of `string thisIsATest(string fileName)` as syntactic sugar for `thisIsATest(string fileName, string result)`. 

> not a bool with how I am checking using the "matches" function.

I am not sure what you mean by this.

**Comment by KylerKatz** [comment]
@mbg 

Thank you, that was the issue. Everything is working as expected now. I appreciate it.
