### ISSUE TITLE
The Kotlin version installed (2.0.0) is too recent for this version of CodeQL. Install a version lower than 1.9.30.

### ISSUE THREAD

**Issue by zoff99** [github/codeql#16148]
please support newer kotlin versions.

![Screenshot from 2024-04-08 17-12-18](https://github.com/github/codeql/assets/6833516/8d948ccd-f916-4294-82cf-1c8e649a00a5)

https://github.com/Zoxcore/trifa_material/actions/runs/8117069571

**Comment by mbg** [comment]
Hi @zoff99 👋 

Kotlin 2.0 support is something our team is actively working on, but that has turned out to be more challenging to support than anticipated. We are currently targeting the current quarter (April-June) to ship support for this.

As a result of your issue, I noticed that our public roadmap is not up-to-date here and I have passed this on to the relevant people to get updated.

**Comment by abogacz-tl** [comment]
@mbg how is going progress on that one? Do you think it can be done till end of Q2?

**Comment by rotilho** [comment]
Weirdly I'm getting `java.lang.OutOfMemoryError: GC overhead limit exceeded` during compilation time

**Comment by pkruk** [comment]
hi :) What's the status of this one ? 

from what I see it is supported from [2.18.1 ](https://codeql.github.com/docs/codeql-overview/codeql-changelog/codeql-cli-2.18.1/#java-kotlin-4) but on our GHE we run in this error after bumping kotlin up.

**Comment by mbg** [comment]
Hi @pkruk. Going by the release notes, yes it should be supported as of CodeQL 2.18.1. Can you confirm that you are actually using this version of CodeQL? I believe this would only be in GHES 3.15, which I don't think is generally available yet.

**Comment by pkruk** [comment]
we bumped the codeql version on our ghe and that's resolved the issue :)

**Comment by mbg** [comment]
That's great to hear! Thanks for reporting back! 

I will go ahead and close this issue now since Kotlin 2 is supported as of CodeQL 2.18.1.

If anyone has an outstanding or new issue with Kotlin 2, feel free to open a separate issue for that.
