### ISSUE TITLE
False positive - cs/unused-collection - C# projects

### ISSUE THREAD

**Issue by wwwjwww** [github/codeql#16156]
**Description of the false positive**

Hi! There's a false positive example in the following code for cs/unused collection since its description is Container contents are never accessed:

**Code samples or links to source code**

![image](https://github.com/github/codeql/assets/50292531/d5959a0d-6ab6-4202-931e-25bcf6adf4db)

Also, OVRDeviceSelector.isTargetDeviceQuestFamily is not always False, the definition of this could be found in:
https://github.com/heesunc/Prison_VReak/blob/81f3fdd1a8c78b5fdf1d898b4d28ae4d0ae5855c/Assets/Imported/Oculus/VR/Editor/OVRDeviceSelector.cs#L30
![image](https://github.com/github/codeql/assets/50292531/f50b1db2-6f46-4513-9b40-55606d4431a9)

**Comment by wwwjwww** [comment]
Hi @mbg 😊

Thanks for your reply. I've got the idea wrong since I thought adding elements to targetOculusPlatform list is accessing it. Looks like I got it wrong. At first, I thought it might be resulted from the if clause in L246. So, please kindly ignore the second program I posted.

This

**Comment by wwwjwww** [comment]
Hi, I still got some issues here. Could you please tell me the definition of "access"? From what I understand, "write" operation has also accessed the list. So, are "access" and "read" equal to CodeQL queries?

**Comment by mbg** [comment]
The definition of "access" isn't universal for all queries and may vary from query to query. In relation to the `cs/unused-collection` query, "never accessed" means that all operations performed on the collection are write-only, such as `Add`, `Remove`, and `Clear`. The full list of operations can be found in the [definition of `modifyMethodName`](https://github.com/github/codeql/blob/b72f34591d5b682a76b4f3ffedaca23274f98792/csharp/ql/lib/semmle/code/csharp/commons/Collections.qll). In other words, the query is intended to detect collections where the elements are never read from.
