### ISSUE TITLE
Finding comments in Java

### ISSUE THREAD

**Issue by KylerKatz** [github/codeql#16168]
Hello, I am attempting to find comments in Java. It seems like there is not a Comments class like there is for other languages. However, there is a Javadoc class. I would like to point out, however, that I am looking for all comments not just JD ones. If I search for all comments using Javadoc. I do indeed get back all comments in my code (This is good). However, I would like to add a bit more functionality to this.

What I would like to do is a regex match on each of the comments to see if they contain a string. For example 
`where comment.getText().matches(".*Hello.*")` so that I only get back these certain comments. However, when I do either `getText()` or `toString()` I just get an empty comment. I have also tried the JavadocText class as well, but I am getting the same result.  

If someone knows of a way to do this I would appreciate it. 

Thank you.

**Comment by smowton** [comment]
`from Javadoc jd where jd.toString().matches(...) select jd` works as expected for me. Could you give a complete example that isn't working as you'd hope?

One thing to note: `matches` does not take regexes, it takes SQL-style wildcards (using `%` for any string and `_` for any character). There is also `regexpMatch` which does take a regex.

My working example:

```java
/** Javadoc */
public class Test {

  /* Regular comment */
  int x = 1; // EOL comment

}
```

```ql
import java

from Javadoc jd
where jd.toString().matches("%EOL%")
select jd
```

**Comment by KylerKatz** [comment]
Hello @smowton,
Thank you for responding. I am noticing that it seems to be working with some comments but not all of them. For example, if I have something simple such as 

```
public class BAD_ApiKeyInComments {
    /**
     * Initializes the connection to the payment service.
     * Make sure to replace the API key below with a valid one.
     * API Key: ak_test_12345
     */
 String API = "test"; // This is my API key
 
 // Another comment 
}
```
And I do a simple query like
```
from Javadoc comment
select comment
```
To get all of the comments. I get back the comments as expected. However, if I then try to narrow down my results to just those with API in them by doing this where clause. 
```
 where comment.toString().matches("%API%")
```
I end up only getting `// This is my API key` and not the first comment as well. I think it might have something to do with how multiline comments are handled when converting to a string. Do you know of a way to fix this?

Thank you

**Comment by smowton** [comment]
Your problem is that the stringification of a multi-line comment only reports its first line followed by an ellipsis. The individual lines get extracted as JavadocText children. Try instead:

```ql
import java

from Javadoc jd
where any(JavadocText jdt | jd = jdt.getJavadoc()).getText().matches("%API%")
select jd
```

**Comment by KylerKatz** [comment]
Thank you, that worked.
