### ISSUE TITLE
General issue - CSharp Query Metadata

### ISSUE THREAD

**Issue by felickz** [github/codeql#16198]
**Description of the issue**
A few CSharp queries that are missing metadata:

Security Queries without `CWE` or `security-severity`
- [cs/web/ambiguous-client-variable](https://github.com/github/codeql/blob/main/csharp/ql/src/Input%20Validation/ValueShadowing.ql)
- [cs/web/ambiguous-server-variable](https://github.com/github/codeql/blob/main/csharp/ql/src/Input%20Validation/ValueShadowingServerVariable.ql)

Security Query without `precision` (not included in a suite due to the default/exteneded selectors requiring this)
- [cs/web/request-validation-disabled](https://github.com/github/codeql/blob/main/csharp/ql/src/Security%20Features/CWE-016/ASPNetPagesValidateRequest.ql)

**Comment by joefarebrother** [comment]
`cs/web/request-validation` fixed [here](https://github.com/github/codeql/pull/16209) 

For the other queries, I'm unsure what the correct CWE tag should be.

**Comment by sidshank** [comment]
> For the other queries, I'm unsure what the correct CWE tag should be.
@joefarebrother Have you asked anyone, or posted in any of our Slack channels about this?

**Comment by joefarebrother** [comment]
I have asked in #codeql-csharp, but didn't get a response

**Comment by joefarebrother** [comment]
https://github.com/github/codeql/pull/16461 - fixes the missing CWE tags
