### ISSUE TITLE
mac m1 codeql extentions for visual studio always loading

### ISSUE THREAD

**Issue by lianxv-primer** [github/codeql#16224]
when I use codeql extensions in mac, I found the codql view page is always loading, and I can't open CodqlQl databases to analyze .  Here is the picture shows.  How can I solve this. 
My environment:
    * Apple M1 Pro 
    * macOS 14.1.1 
    * codeql extension version: v1.12.5
    *vs code version : 1.88.0

<img width="1717" alt="extentionsloading" src="https://github.com/github/codeql/assets/22149090/93dc0ddc-80fe-43df-93c0-0945ad2129cc">

**Comment by ReDistant** [comment]
你在设置里面指定codeql-cli的位置了吗

**Comment by lianxv-primer** [comment]
> 你在设置里面指定codeql-cli的位置了吗

I think i did
<img width="1212" alt="image" src="https://github.com/github/codeql/assets/22149090/bf92666a-9420-473d-9ef2-ad9e47616301">

**Comment by lianxv-primer** [comment]
> 你在设置里面指定codeql-cli的位置了吗

I Think I did. 
<img width="901" alt="image" src="https://github.com/github/codeql/assets/22149090/39d0e4e0-4af0-4ea0-85dd-9d5f489c49e3">
<img width="934" alt="image" src="https://github.com/github/codeql/assets/22149090/2a161a91-4752-4eb0-9c63-c854d6064241">

**Comment by charisk** [comment]
Thanks for raising this issue. To help us find the problem, can you please share any logs from the CodeQL extension? You can get these from the Output view, by selecting "CodeQL Extension Log" from the drop-down.

Also does this happen on any VS Code workspace you open?

**Comment by lianxv-primer** [comment]
> Thanks for raising this issue. To help us find the problem, can you please share any logs from the CodeQL extension? You can get these from the Output view, by selecting "CodeQL Extension Log" from the drop-down.
> 
> Also does this happen on any VS Code workspace you open?

Here is the output in "CodeQL Extension Log":

Starting GitHub.vscode-codeql extension
Checking CodeQL version using CodeQL CLI: /Users/xxx/codeql/codeql version -v --log-to-stderr --format=json...
[2024-04-16 15:56:47] This is codeql version -v --log-to-stderr --format=json
[2024-04-16 15:56:47] Terminating normally.

CLI command succeeded.
CodeQL CLI is installed externally so could not be updated.
Checking CodeQL version using CodeQL CLI: /Users/xxx/codeql/codeql version -v --log-to-stderr --format=json...
[2024-04-16 15:56:48] This is codeql version -v --log-to-stderr --format=json
[2024-04-16 15:56:48] Terminating normally.

CLI command succeeded.
Found compatible version of CodeQL CLI (version 2.15.5)
Initializing configuration listener...
Initializing CodeQL cli server...
Initializing query server client.
Checking CodeQL version using CodeQL CLI: /Users/xxx/codeql/codeql version -v --log-to-stderr --format=json...
Starting CodeQL CLI Server using CodeQL CLI: /Users/xxx/codeql/codeql execute cli-server -v --log-to-stderr
CodeQL CLI Server started on PID: 49501
Resolving RAM settings using CodeQL CLI: resolve ram -v --log-to-stderr --format json...
[2024-04-16 15:56:48] This is codeql execute cli-server -v --log-to-stderr

CLI command succeeded.
Initializing language context.
Initializing language selector.
Initializing database manager.
Found 0 persisted databases: 
Initializing database panel.
Initializing queries panel.
Initializing evaluator log viewer.
Initializing query history manager.
Initializing results panel interface.
Initializing variant analysis manager.
Initializing database module
[2024-04-16 15:56:48] This is codeql version -v --log-to-stderr --format=json
[2024-04-16 15:56:48] Terminating normally.

CLI command succeeded.
Finished loading persisted databases.
Database config loaded from /Users/xxx/Library/Application Support/Code/User/workspaceStorage/3a381f69beed3282ab05f1cc7b3a27a6/GitHub.vscode-codeql/databases.json
Initializing query history.
Initializing evaluation log scanners.
Initializing compare view.
Initializing source archive filesystem provider.
Initializing CodeQL language server.
Initializing debugger factory.
Initializing debugger UI.
Initializing QLTest interface.
Registering top-level command palette commands.
Starting language server.

**Comment by jketema** [comment]
Hi @lianxv-primer,

It seems it might be hanging while starting the language server. You seems to be running a quite old version of CodeQL. Could you try with a newer version to see if the problem still occurs?

**Comment by lianxv-primer** [comment]
> Hi @lianxv-primer,
> 
> It seems it might be hanging while starting the language server. You seem to be running a quite old version of CodeQL. Could you try with a newer version to see if the problem still occurs?

Unfortunately I upgrade to latest version 2.17.0 but It still hanging.   Here is the log: 
Starting GitHub.vscode-codeql extension
Checking CodeQL version using CodeQL CLI: /Users/xxx/codeql/codeql version -v --log-to-stderr --format=json...
[2024-04-16 17:10:07] This is codeql version -v --log-to-stderr --format=json
[2024-04-16 17:10:07] Terminating normally.

CLI command succeeded.
CodeQL CLI is installed externally so could not be updated.
Checking CodeQL version using CodeQL CLI: /Users/xxx/codeql/codeql version -v --log-to-stderr --format=json...
[2024-04-16 17:10:07] This is codeql version -v --log-to-stderr --format=json
[2024-04-16 17:10:08] Terminating normally.

CLI command succeeded.
Found compatible version of CodeQL CLI (version 2.17.0)
Initializing configuration listener...
Initializing CodeQL cli server...
Initializing query server client.
Checking CodeQL version using CodeQL CLI: /Users/xxx/codeql/codeql version -v --log-to-stderr --format=json...
Starting CodeQL CLI Server using CodeQL CLI: /Users/xxx/codeql/codeql execute cli-server -v --log-to-stderr
CodeQL CLI Server started on PID: 81733
Resolving RAM settings using CodeQL CLI: resolve ram -v --log-to-stderr --format json...
[2024-04-16 17:10:08] This is codeql execute cli-server -v --log-to-stderr

CLI command succeeded.
[2024-04-16 17:10:08] This is codeql version -v --log-to-stderr --format=json
[2024-04-16 17:10:08] Terminating normally.

CLI command succeeded.
Initializing language context.
Initializing language selector.
Initializing database manager.
Found 0 persisted databases: 
Initializing database panel.
Initializing queries panel.
Initializing evaluator log viewer.
Initializing query history manager.
Initializing results panel interface.
Initializing variant analysis manager.
Initializing database module
Finished loading persisted databases.
Database config loaded from /Users/xxx/Library/Application Support/Code/User/workspaceStorage/3a381f69beed3282ab05f1cc7b3a27a6/GitHub.vscode-codeql/databases.json
Initializing query history.
Initializing evaluation log scanners.
Initializing compare view.
Initializing source archive filesystem provider.
Initializing CodeQL language server.
Initializing debugger factory.
Initializing debugger UI.
Initializing QLTest interface.
Registering top-level command palette commands.
Starting language server.

**Comment by jketema** [comment]
Could you also share the logs of the language server. You can get these from the Output view, by selecting "CodeQL Language Server" from the drop-down.

**Comment by lianxv-primer** [comment]
> Could you also share the logs of the language server. You can get these from the Output view, by selecting "CodeQL Language Server" from the drop-down.
Sure.  Here is "CodeQl Language Server" log :
Starting CodeQL language server using CodeQL CLI: /Users/xxx/codeql/codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr
CodeQL language server started on PID: 81754
[2024-04-16 17:10:09] This is codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr

**Comment by lianxv-primer** [comment]
> Could you also share the logs of the language server. You can get these from the Output view, by selecting "CodeQL Language Server" from the drop-down.

Sure. Here is "CodeQl Language Server" log :
Starting CodeQL language server using CodeQL CLI: /Users/doeli/codeql/codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr
CodeQL language server started on PID: 81754
[2024-04-16 17:10:09] This is codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr

**Comment by lianxv-primer** [comment]
> Thanks. Just to confirm, there's no further output after
> 
> ```
> [2024-04-16 17:10:09] This is codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr
> ```
> 
> ?

yes

**Comment by lianxv-primer** [comment]
> Thanks. Just to confirm, there's no further output after
> 
> ```
> [2024-04-16 17:10:09] This is codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr
> ```
> 
> ?

it has more logs after waiting 90 min . it shows here :
`Starting CodeQL language server using CodeQL CLI: /Users/xxx/codeql/codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr
CodeQL language server started on PID: 81754
[2024-04-16 17:10:09] This is codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr
Content-Length: 177

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/xxx/gitfolder/wework-codeql/codeql-custom-queries-cpp/qlpack.yml","diagnostics":[]}}[2024-04-16 18:36:12] Creating pack state at /Users/xxx/gitfolder/wework-codeql/codeql-custom-queries-cpp, with library path [/Users/xxx/gitfolder/wework-codeql/ql/cpp/ql/lib, /Users/xxx/gitfolder/wework-codeql/ql/shared/dataflow, /Users/xxx/gitfolder/wework-codeql/ql/shared/ssa, /Users/xxx/gitfolder/wework-codeql/ql/shared/tutorial, /Users/xxx/gitfolder/wework-codeql/ql/shared/typetracking, /Users/xxx/gitfolder/wework-codeql/ql/shared/util] and dbscheme /Users/xxx/gitfolder/wework-codeql/ql/cpp/ql/lib/semmlecode.cpp.dbscheme
Content-Length: 180

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/xxx/gitfolder/wework-codeql/codeql-custom-queries-csharp/qlpack.yml","diagnostics":[]}}[2024-04-16 18:36:12] Creating pack state at /Users/xxx/gitfolder/wework-codeql/codeql-custom-queries-csharp, with library path [/Users/xxx/gitfolder/wework-codeql/ql/csharp/ql/lib, /Users/xxx/gitfolder/wework-codeql/ql/shared/controlflow, /Users/xxx/gitfolder/wework-codeql/ql/shared/dataflow, /Users/xxx/gitfolder/wework-codeql/ql/shared/mad, /Users/xxx/gitfolder/wework-codeql/ql/shared/ssa, /Users/xxx/gitfolder/wework-codeql/ql/shared/tutorial, /Users/xxx/gitfolder/wework-codeql/ql/shared/typetracking, /Users/xxx/gitfolder/wework-codeql/ql/shared/util] and dbscheme /Users/xxx/gitfolder/wework-codeql/ql/csharp/ql/lib/semmlecode.csharp.dbscheme
Content-Length: 176

...
...
...

{"jsonrpc":"2.0","id":"1","method":"client/registerCapability","params":{"registrations":[{"id":"watcher","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"**/*.{ql,qll,dbscheme}"},{"globPattern":"**/.codeqlmanifest.json"},{"globPattern":"**/codeql-workspace.yml"},{"globPattern":"**/codeql-pack.lock.yml"},{"globPattern":"**/qlpack.lock.yml"},{"globPattern":"**/queries.xml"},{"globPattern":"**/codeql-pack.yml"},{"globPattern":"**/qlpack.yml"}]}}]}}`

**Comment by lianxv-primer** [comment]
> Does the "CodeQL Extension Log" also have more output in it after this point?

yeah , copied here :
Starting GitHub.vscode-codeql extension
Checking CodeQL version using CodeQL CLI: /Users/xxx/codeql/codeql version -v --log-to-stderr --format=json...
[2024-04-16 17:10:07] This is codeql version -v --log-to-stderr --format=json
[2024-04-16 17:10:07] Terminating normally.

CLI command succeeded.
CodeQL CLI is installed externally so could not be updated.
Checking CodeQL version using CodeQL CLI: /Users/xxx/codeql/codeql version -v --log-to-stderr --format=json...
[2024-04-16 17:10:07] This is codeql version -v --log-to-stderr --format=json
[2024-04-16 17:10:08] Terminating normally.

CLI command succeeded.
Found compatible version of CodeQL CLI (version 2.17.0)
Initializing configuration listener...
Initializing CodeQL cli server...
Initializing query server client.
Checking CodeQL version using CodeQL CLI: /Users/xxx/codeql/codeql version -v --log-to-stderr --format=json...
Starting CodeQL CLI Server using CodeQL CLI: /Users/xxx/codeql/codeql execute cli-server -v --log-to-stderr
CodeQL CLI Server started on PID: 81733
Resolving RAM settings using CodeQL CLI: resolve ram -v --log-to-stderr --format json...
[2024-04-16 17:10:08] This is codeql execute cli-server -v --log-to-stderr

CLI command succeeded.
[2024-04-16 17:10:08] This is codeql version -v --log-to-stderr --format=json
[2024-04-16 17:10:08] Terminating normally.

CLI command succeeded.
Initializing language context.
Initializing language selector.
Initializing database manager.
Found 0 persisted databases: 
Initializing database panel.
Initializing queries panel.
Initializing evaluator log viewer.
Initializing query history manager.
Initializing results panel interface.
Initializing variant analysis manager.
Initializing database module
Finished loading persisted databases.
Database config loaded from /Users/xxx/Library/Application Support/Code/User/workspaceStorage/3a381f69beed3282ab05f1cc7b3a27a6/GitHub.vscode-codeql/databases.json
Initializing query history.
Initializing evaluation log scanners.
Initializing compare view.
Initializing source archive filesystem provider.
Initializing CodeQL language server.
Initializing debugger factory.
Initializing debugger UI.
Initializing QLTest interface.
Registering top-level command palette commands.
Starting language server.
Cleaning up query history directories. Removing old entries.
Scrubbed 0 old queries.
Registering jump-to-definition handlers.
Removing orphaned databases from workspace storage.
No orphaned databases found.
Reading query history
Reading cached query history from '/Users/xxx/Library/Application Support/Code/User/workspaceStorage/3a381f69beed3282ab05f1cc7b3a27a6/GitHub.vscode-codeql/workspace-query-history.json'.
Successfully finished extension initialization.
Resolving database using CodeQL CLI: resolve database -v --log-to-stderr --format json /Users/xxx/codeql_database/devops-codeql-database...

CLI command succeeded.

**Comment by jketema** [comment]
I think it might just be very slow. Do you have many databases loaded?

**Comment by lianxv-primer** [comment]
> I think it might just be very slow. Do you have many databases loaded?

No, I hadn't selected any database yet. After loading, the page can be clicked to select the database. You can see my first picture while loading .

**Comment by jketema** [comment]
Yes, what I meant was: do you have a long list of databases?

**Comment by lianxv-primer** [comment]
> Yes, what I meant was: do you have a long list of databases? This is hard to tell from the picture, because I don't know if it has loaded the list yet.
I just have one database that I just loaded.
<img width="370" alt="image" src="https://github.com/github/codeql/assets/22149090/b949a726-5954-4e0a-9376-9dde579b4bde">

**Comment by jketema** [comment]
Is the CodeQL extension the only extension that shows this behaviour of seeming to hang, or do other extensions like search and source control show similar behaviour when you've just started VSCode?

**Comment by lianxv-primer** [comment]
> Is the CodeQL extension the only extension that shows this behaviour of seeming to hang, or do other extensions like search and source control show similar behaviour when you've just started VSCode?
 
So far other extensions works well,  Just codeql extensions loading for long time.  But in my windows machine, codeql extensions looks well

**Comment by jketema** [comment]
We suspect that the behaviour has to do with the place where you put your copy of CodeQL. We recommend you don't point the extension to to a copy of CodeQL that you downloaded yourself, but instead let the extension take care of downloading the latest version of CodeQL.

I you want to keep using the copy of CodeQL you downloaded yourself, we suggest that you move the CodeQL directory slightly. From `/Users/xxx/codeql/` to something like `Users/xxx/new_directory/codeql/` where `new_directory` only contains the `codeql` directory.

**Comment by lianxv-primer** [comment]
> We suspect that the behaviour has to do with the place where you put your copy of CodeQL. We recommend you don't point the extension to to a copy of CodeQL that you downloaded yourself, but instead let the extension take care of downloading the latest version of CodeQL.
> 
> I you want to keep using the copy of CodeQL you downloaded yourself, we suggest that you move the CodeQL directory slightly. From `/Users/xxx/codeql/` to something like `/Users/xxx/new_directory/codeql/` where `new_directory` only contains the `codeql` directory.

Thank you very much. I will try it later. Now I can write the query using the database that was loaded yesterday.

**Comment by lianxv-primer** [comment]
> We suspect that the behaviour has to do with the place where you put your copy of CodeQL. We recommend you don't point the extension to to a copy of CodeQL that you downloaded yourself, but instead let the extension take care of downloading the latest version of CodeQL.
> 
> I you want to keep using the copy of CodeQL you downloaded yourself, we suggest that you move the CodeQL directory slightly. From `/Users/xxx/codeql/` to something like `/Users/xxx/new_directory/codeql/` where `new_directory` only contains the `codeql` directory.

` From /Users/xxx/codeql/ to something like /Users/xxx/new_directory/codeql/ where new_directory only contains the codeql directory.`
It works !!! But I donn't know the reason why should do this.

**Comment by jketema** [comment]
> It works !!! But I donn't know the reason why should do this.

The codeql cli looks for packs in sibling directories of the directory in which the cli is located. In this case that means it'll look in all the directories `/Users/xxx`, of which there are likely many.

**Comment by lianxv-primer** [comment]
> > It works !!! But I donn't know the reason why should do this.
> 
> The codeql cli looks for packs in sibling directories of the directory in which the cli is located. In this case that means it'll look in all the directories `/Users/xxx`, of which there are likely many.

I see . Thanks a lot
