### ISSUE TITLE
[cpp] const qualifiers

### ISSUE THREAD

**Issue by 167rgc911** [github/codeql#16294]
Studying CodeQL at the moment.
Simply trying to find all variables that are ``const`` in this test code:
https://godbolt.org/z/nYT16dYTx

```cpp
  :
  int const aa[] = { 1, 2, f, 3, 4 };
  int const& ref = y;
```

1 LocalVariable.isConst() <b>does not</b> give me an affirmative answer.
```
import cpp
from LocalVariable lv
where
  lv.hasInitializer() and
  lv.isConst() or
  lv.isConstexpr()
select lv, "variable '" + lv.getName() + "' is 'const'/'constexpr'."
```

2 LocalVariable.getType().getName().regexpMatch(".*const.*") <b>does</b> give men an affirmative.
```
import cpp
from LocalVariable lv
where
  lv.hasInitializer() and
  lv.isConst() or
  lv.isConstexpr() or
  lv.getType().isConst() or
  lv.getType().getName().regexpMatch(".*const.*")
select lv, "variable '" + lv.getName() + "' is 'const'/'constexpr'."
```

Am I properly writing the queries?
TIA

**Comment by jketema** [comment]
The reason this fails, is because it's not the type of the local variable itself that is constant, it's the base type that is constant. The following gives the result you're after:
```codeql
import cpp

from LocalVariable lv, Type t, Type b
where
  t = lv.getType() and
  (
    t instanceof ArrayType and b = t.(ArrayType).getBaseType()
    or
    t instanceof ReferenceType and b = t.(ReferenceType).getBaseType()
  ) and
  b.isConst()
select lv, "variable '" + lv.getName() + "' is 'const'/'constexpr'."
```

**Comment by 167rgc911** [comment]
Thanks for the comprehensive reply. I wouldn't have understood that on my own.
