### ISSUE TITLE
Missing option to enable CodeQL at personal org level

### ISSUE THREAD

**Issue by mcandre** [github/codeql#16350]
The "Code security and analysis" personal org settings page lists several options for Dependabot SCA third party security scans, but lists no option for CodeQL SAST first party security scans.

This males it unnecessarily difficult for GitHub users to consistently scan all their repositories. We'd just as well assume that millions of GitHub repos are insecure, rife with SAST violations.

**Comment by sampart** [comment]
Hello from GitHub Code Scanning, and thanks for getting in touch, @mcandre. The behaviour you're describing isn't what I'd expect to see on that page, so I'd like to investigate further. Please could you post a screenshot of what you're seeing on that page, and let us know the organisation name? Many thanks.

**Comment by rvermeulen** [comment]
Hi @mcandre,

It has been a while since our last correspondence.
Is the issue you describe still a problem? If so could you provide a screenshot such that @sampart can further investigate?

Thanks!
