### ISSUE TITLE
Add dummy passwords to documentation for rule 'js/hardcoded-passwords'

### ISSUE THREAD

**Issue by ebickle** [github/codeql#16359]
**Description of the issue**

The rule 'js/hardcoded-passwords' often returns false positives for our developers, often in their test code. This is somewhat expected, since the rule can't be expected to find every possible dummy/stub value added to unit tests. 

Internally the rule depends on [isDummyPassword](https://github.com/github/codeql/blob/607ed2efb4283cf2292444664f89a5b68c3a3f77/javascript/ql/lib/semmle/javascript/security/SensitiveActions.qll#L196) from the `PasswordHeuristics` module to avoid triggering on the most common dummy/stub values.

Would it be possible to add some of these example dummy passwords to the documentation for the rule? That way, when our developers get an alert for 'js/hardcoded-passwords' for unit tests they can immediately see a fix - e.g. using `sample`, `example`, or `fake` as the value to avoid the alert from being detected in the first place.

**Comment by ginsbach** [comment]
Thank you for the suggestion. I have forwarded this to the relevant team and they are working on it!

**Comment by aibaars** [comment]
This should be fixed by https://github.com/github/codeql/pull/16417 once that pull request is merged.

**Comment by erik-krogh** [comment]
Hi Eric (nice name 😉) 

I just un-drafted https://github.com/github/codeql/pull/16417, which should fix this issue, and your related issue (https://github.com/github/codeql/issues/16360).  
I tested the effect of the change, and the change in results look OK.

Your points (in both of these issues) are definitely reasonable, and it seems like the right thing to do.  

Thanks for the reports.

**Comment by erik-krogh** [comment]
Hi 👋 

I just merged https://github.com/github/codeql/pull/16417 which I think should solve your issue. 
If you have feedback and other comments just let me know, nothing is set in stone.  

Thanks for the nice report.
