### ISSUE TITLE
Python - unable to find suitable examples to iterate over objects

### ISSUE THREAD

**Issue by amygbAI** [github/codeql#16532]
Hi folks, i am trying to write queries to identify the connectivity between , lets say, 2 modules linked by a call. Now i am able to get as far as getting the list of all the calls being made across the code base and printing file names, method names but come a cropper while trying to get the method signatures and return values .. i can get them one by one but i would need them all listed in the output csv .. the end goal is to list all the methods, their names, signature (with names and types ) and return signature ..i googled this stuff for almost 3 hours and went through every single example provided on the docs but couldn't find a single example for looping through values ..any pointers are deeply appreciated

```
import python

from Value val, CallNode call, Scope scope, Function func, ParameterList pml
where
  val.getACall() = call and
  (
    scope = val.(CallableValue).getScope()
    or
    scope = val.(ClassValue).getScope()
  ) and
  func.getEvaluatingScope() = scope
  and pml.getParent() = func
  and not call.getEnclosingModule() = scope.getEnclosingModule() and
  exists(scope.getLocation().getFile().getRelativePath()) and
  exists(call.getLocation().getFile().getRelativePath()) and
  not scope.getLocation().getFile().getRelativePath().matches( "codeql%" ) and
  not call.getLocation().getFile().getRelativePath().matches( "codeql%" )

select call, val, scope, scope.getLocation().getFile(), call.getLocation().getFile(), pml.getAnItem().getName()

```

**Comment by amygbAI** [comment]
Thanks so much for your response..for a given codebase in python I would
like
a) to list all the methods / functions
b) capture their input / call signature with names and datatypes of all
input arguments/ parameters
c) capture return signatures with all names and datatypes of objects being
returned

My idea is to create a graph and perform certain analysis (like critical
methods, using page rank etc )..

Appreciate your help

**Comment by jketema** [comment]
Hi. Could you please provide a concrete example.

**Comment by amygbAI** [comment]
Absolutely sir .. 

```
import numpy as np
import scipy as sp

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
    self.capsule_ = dict()
  
  def hobby( self ):
     if self.age < 10: 
       self.capsule['Age'] = "<10"
       self.capsule['Hobby'] = "LEGO"
     else:
       self.capsule['Age'] = ">10"
       self.capsule['Hobby'] = "MMA"
     return ( True, self.capsule )
```
so when i run codeQL on such files i would love to have the output in the following format

ClassOrMethod,	Name,	FileLocation,	InputArgs,	Return
Package	Numpy	numpy_installation		
Package	Scipy	numpy_installation		
Class	Person	xyz/folder	{ 'age': int, 'name': str }	Object
Method	hobby	xyz/folder	{ 'self': object  }	{ 'True': boolean , 'capsule': dict }

**Comment by jketema** [comment]
Thanks.

> Now i am able to get as far as getting the list of all the calls being made across the code base and printing file names, method names but come a cropper while trying to get the method signatures and return values .. i can get them one by one but i would need them all listed in the output csv ..

How are you getting them one-by-one?

**Comment by amygbAI** [comment]
**Function** module's **getArg** where u can get the arguments by passing in indices ..i just dont know how to add for loops ..if i could get some examples on that i could easily iterate over the args / parameter list and put all of them in a csv file

**Comment by jketema** [comment]
What you want to look at is [`concat`](https://codeql.github.com/docs/ql-language-reference/expressions/#aggregations-1):
```codeql
concat(Parameter p | p = func.getArg() | p.toString(), ',')
```

**Comment by amygbAI** [comment]
thanks a ton 👍 .. it worked, with a small tweak .. 
```
concat( Parameter p | p = func.getArgs().getAnItem() | p.getName(), "|")
```
