### ISSUE TITLE
Text format

### ISSUE THREAD

**Issue by mcandre** [github/codeql#16594]
Please implement text format console output, similar to how other linters work.

**Comment by aibaars** [comment]
Thanks for the suggestion. Could you elaborate a bit about the use-case for this feature? Note that CodeQL results are typically some complex than simple linter warning and often refer to multiple source location. Presenting an alert as a line of text on a single source line might not be enough to understand it.

**Comment by mcandre** [comment]
Console output has served as a simple, reliable, effective UX for an incredible number of earlier linters.

**Comment by majority131** [comment]
https://github.com/github/codeql/issues/16594#issue-2318005421

**Comment by mcandre** [comment]
A summary text view in the console provides an efficient way to rapidly improve large, complex repos. Any deep explanations of a rule can be documented elsewhere, such as on a wiki. Take, for example, the report structure of ShellCheck. It balances both needs quite well.

**Comment by rvermeulen** [comment]
Hi @mcandre,

As pointed out by @aibaars, CodeQL alerts are typically more complex than linter errors containing information from various parts of the code base that are not easily summarized to single lines.
However, we support the [SARIF](https://sarifweb.azurewebsites.net) output format that provided all the information you need and you can use this as a basis to output the format you prefer.

I'm closing this issue. If you have any follow-up questions, feel free to re-open this issue.
