### ISSUE TITLE
Recursive type checking in TypeScript

### ISSUE THREAD

**Issue by jpoly1219** [github/codeql#16611]
**Description of the issue**

What would be the best way to check if two types are equal?

For example, if I have:
```ts
type Alpha = number;
type Bravo = string;
type Charlie = boolean[];
type BigType = [Alpha, Bravo, Charlie];
type BigType2 = [number, string, boolean[]];
```
Then I would like to write a checker that `BigType` = `BigType2`. This would involve some recursion. The best way to do this, in my opinion, is to recursively expand both `BigType` and `BigType2` and compare equality between the two. The issue I am running into is that there is no way to guarantee "order" in the structure of these types, but order matters when you want to do structural pattern matching.

Also, I don't see a way to recurse on individual child, then have everything combine together. Normally I would map over each child, then cons them together. But CodeQL is a specific language, so I don't think I can expect that :sweat_smile: 

Is there a good way to do this in CodeQL? I'm looking for ways to map over child nodes and reduce into a single value.

**Comment by aibaars** [comment]
I think you could keep an index/position number so you know whether a child is the 1st, 2nd, 3rd, etc.

**Comment by jpoly1219** [comment]
@aibaars , thank you for the advice! I was unable to find that in the documentation. Where can I find that information?

**Comment by jpoly1219** [comment]
@aibaars bumping, any examples on how to keep an index? Thank you :)

**Comment by aibaars** [comment]
I think something like this would work. It finds the answer for your example. Note, however, that the solution is incomplete and does not handle `any` keyword types correctly. Nevertheless I hope it helps.

```ql
predicate equalsTuple(TupleTypeExpr x, TupleTypeExpr y) {
  forall(int i | i in [0 .. x.getNumChild() - 1] | equals(x.getChild(i), y.getChild(i)))
}

predicate equalsAlias(TypeAliasDeclaration x, TypeAliasDeclaration y) {
  equals(x.getDefinition(), y.getDefinition())
}

predicate equalsArray(ArrayTypeExpr x, ArrayTypeExpr y) {
  equals(x.getElementType(), y.getElementType())
}

TypeExpr resolveTypeAccess(LocalTypeAccess x) {
  x.getLocalTypeName().getADeclaration() =
    any(TypeAliasDeclaration d | result = d.getDefinition() | d).getIdentifier()
}

predicate equalsPrimitive(KeywordTypeExpr x, KeywordTypeExpr y) { x.getName() = y.getName() }

predicate equals(TypeExpr x, TypeExpr y) {
  equalsTuple(x, y) or
  equalsArray(x, y) or
  equalsPrimitive(x, y) or
  equals(resolveTypeAccess(x), y) or
  equals(y, resolveTypeAccess(y))
}
```

**Comment by jpoly1219** [comment]
Thank you!
