### ISSUE TITLE
[Java] SummaryModel compiler issues 

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#16679]
Hello,

I have recently started getting this error 
`A fatal error occurred: A tuple in a data extension for the extensible predicate 'summaryModel' has an incorrect number of columns. Expected 11, but was 10.` was there any recent breaking change that expects the summarymodel column count to be 11 ?

**Comment by chmodxxx** [comment]
I'm on 2.17.3

**Comment by chmodxxx** [comment]
I temporary removed the summaryModel to see what's the issue and I noticed an error with sinks as well : 
`A fatal error occurred: A tuple in a data extension for the extensible predicate 'sinkModel' has an incorrect number of columns. Expected 10, but was 9.`

**Comment by ginsbach** [comment]
Thank you for filing this issue!
You mention that you use CodeQL Bundle v2.17.3, but can you please give us a bit more context about your workflow? What are you doing exactly to trigger this error? Which queries are you running; what code are you analysing; are you evaluating inside VSCode?

**Comment by chmodxxx** [comment]
Hello @ginsbach , 

To clarify this is not a new workflow or anything, we've been using our custom yaml models for a few months now and we are running our internal query packs. 
This has been working flawlessly up to 2.17.0, when we upgraded our codeQL CLI to 2.17.3/2.17.4  things started breaking and the error is `A fatal error occurred: A tuple in a data extension for the extensible predicate 'summaryModel' has an incorrect number of columns. Expected 11, but was 10`

**Comment by chmodxxx** [comment]
Looks like there was some change indeed https://github.com/github/codeql/blob/44a56c420f06a3f87310013754cde73f10e701c9/java/ql/lib/semmle/code/java/dataflow/internal/ExternalFlowExtensions.qll#L8-L26 that adds MadID column, unfortunately looks like this is causing some issues for downstream models. 

@aschackmull  Any help would be appreciated.

**Comment by ginsbach** [comment]
> Hello [@ginsbach](https://github.com/ginsbach) ,
> 
> To clarify this is not a new workflow or anything, we've been using our custom yaml models for a few months now and we are running our internal query packs. This has been working flawlessly up to 2.17.0, when we upgraded our codeQL CLI to 2.17.3/2.17.4 things started breaking and the error is `A fatal error occurred: A tuple in a data extension for the extensible predicate 'summaryModel' has an incorrect number of columns. Expected 11, but was 10`
> 
> This error is happening inside VsCode and with CLI as well. I'm analyzing java code.

Thank you for the additional details @chmodxxx . We have seen a similar problem before internally but thought it to be fixed. I have made the relevant people aware of this.

**Comment by chmodxxx** [comment]
Hey @dbartol / @ginsbach  do you have any ETA or when would this be fixed ? Right now we are using an month old release or so which is not the worst, but still we will probably need to be up to date with the latest releases sometime soon.

**Comment by chmodxxx** [comment]
Hey @smowton  yeah we use the latest bundle including latest cli in our queries 
https://github.com/github/codeql-cli-binaries/releases/tag/v2.17.4
we then use this CLI bundler https://github.com/advanced-security/codeql-bundle to inject our customized models and query packs.

**Comment by chmodxxx** [comment]
Also we're scanning in CI via the scan action 
```

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        id: analysis

```

**Comment by chmodxxx** [comment]
Do I need to be using v3 or ?

**Comment by smowton** [comment]
What CLI version is present where the `codeql-bundle` process is used? Can you make sure the new CLI is being used both in pack / bundle creation and in running the query?

**Comment by chmodxxx** [comment]
Looks like this might not be a problem with 2.17.5, or at least I'm seeing my CI tests not failing. I will give it a try after it's fully rolled out to see if it solves the problem.

**Comment by chmodxxx** [comment]
nope, still not working with 2.17.5

**Comment by chmodxxx** [comment]
Hey folks // @smowton , 

Any updates about this issue, if you can't reproduce I'm happy to share more information to help you get a repro.

**Comment by smowton** [comment]
@chmodxxx that would be very welcome, as yes my local experiments with https://github.com/advanced-security/codeql-bundle seemed to work as expected. The most useful reproducer would be a little qlpack with a yaml model and the CLI commands used to create and then use your custom bundle.

**Comment by chmodxxx** [comment]
okay, it's going to be a bit challenging to get an exact repro, but roughly here is our setup : 

we have this internal QL setup 

two folders : 

 - ql-java-customizations : 
   - contains some QL customizations that we inject into upstream pack 
   - depends on java-all 
   - An example Customizations.qll will have "import lib.frameworks.Foo" 
   
 - ql-java :
   - lib : Folder contains internal libs to be used with our internal queries 
   - models : contains yaml models 
   - queries  : Contains internal queries

A script running in CI that does the following : 
- download the latest codeql cli bundle 
- copy ql-java folder to codeql/codeql/qlpacks/octo-org/
  - the purpose of this is to make import statements work in our customizations since they depend on the ql-java pack
- copy the lib folder from ql-java to ql-java-customizations , same purpose as ^ 
- Run the codeql-bundle cli using `python3.11 codeql_bundle-0.2.0/codeql_bundle/cli.py --bundle ./codeql/  \
    --output mega_ql_rebundled.tar.gz "octo-org/ql-java-customizations"   --log INFO` 


I think if something went wrong is probably around the non-standard copying of our internal qlpack (ql-java) directly to codeql folder. 

This is the output of the bundler CLI : 
```
INFO: Creating custom bundle of codeql using CodeQL pack(s) in workspace /tmp/codeql_bundle_workdir
INFO: Validating the CodeQL CLI version part of the bundle.
INFO: Found CodeQL CLI version 2.17.4.
INFO: Looking for CodeQL packs in workspace /tmp/codeql_bundle_workdir
INFO: Found the CodeQL pack(s): octo-org/go-customizations,octo-org/java-customizations
INFO: Considering the following CodeQL pack(s) for inclusion in the custom bundle: octo-org/java-customizations,octo-org/go-customizations
INFO: Adding the pack(s) octo-org/go-customizations,octo-org/java-customizations and its workspace dependencies to the custom bundle.
INFO: Bundling the customization pack octo-org/go-customizations.
INFO: Bundling the customization pack octo-org/java-customizations.
INFO: Bundling the standard library pack codeql/go-all.
INFO: Bundling the standard library pack codeql/java-all.
INFO: Bundling the standard query pack codeql/go-examples.
INFO: Bundling the standard query pack codeql/go-queries.
INFO: Bundling the query pack octo-org/ql-go.
INFO: Bundling the standard query pack codeql/java-examples.
INFO: Bundling the standard query pack codeql/java-queries.
INFO: Bundling the query pack octo-org/ql-java.
INFO: Bundling custom bundle(s) at mega_ql_rebundled.tar.gz
INFO: Completed building of custom bundle(s).
INFO: Removing temporary directory /tmp/tmp666lpa94 used to build custom bundle.
```

**Comment by chmodxxx** [comment]
fixed offline
