### ISSUE TITLE
Simple queries aren't returning results

### ISSUE THREAD

**Issue by 0ptyx** [github/codeql#16695]
**Description of the issue**

I'm attempting to use CodeQL (VSCode plugin) on the LInux Kernel but it's not returning results for simple queries which should return results.

Command to create the database: `codeql database create cpp-database --language=c-cpp --command="make -j8"`

Query I run that fails to return any results

```codeql

import cpp 


from Type t
where t.getName() = "io_rw"
select t

```

This struct exists in `io_uring/rw.c`.

**Comment by jketema** [comment]
Hi @0ptyx,

Could you share the build-tracer.log from the database directory?

**Comment by 0ptyx** [comment]
hi @jketema ,

I actually figured it out -- compilation failed during the build. It appeared like the build actually succeeded  though when I ran `make` via `codeql create database`. Is that to be expected? I feel that errors should report and kill the process?

**Comment by jketema** [comment]
That will depend on the exit code that `make` returned. If it was non-zero, I would expect `codeql database create` to report something like:
```
[2024-06-07 01:11:30] [ERROR] Spawned process exited abnormally (code 1; tried to run: [...])
A fatal error occurred: Exit status 1 from command: [...]
```

**Comment by 0ptyx** [comment]
Interesting. I don't believe it reporting anything like that. I'm going to close this issue and try building like I was previously.  If doesn't appear clear that it did indeed fail, then I will open an issue for that.
