### ISSUE TITLE
Run Maven autobuild with `--no-transfer-progress` option

### ISSUE THREAD

**Issue by strangelookingnerd** [github/codeql#16793]
This may be an issue for the CodeQL libs, but here goes nothing:

Starting with [Maven 3.6.1](http://maven.apache.org/docs/3.6.1/release-notes.html), users now have an option to suppress the transfer progress when downloading/uploading in interactive mode.

> `mvn --no-transfer-progress` or `mvn -ntp`

In my opionion the Maven autobuild (and others with similar options) would greatly benefit from this. The output generated when downloading dependencies during autobuild provides basically no value but only makes it hard to read and investigate potential errors.

I am aware that I can set up my own build step, however I think making this option a default would be a great addition regardless.

**Comment by smowton** [comment]
Thanks; I've opted for batch mode instead of specifically ntp since that doesn't require Maven >= 3.6.1 and I'm sure there are people with ancient environments out there running CodeQL! This should reduce verbosity as you suggest from CodeQL 2.17.6.

**Comment by smowton** [comment]
Fix will be in 2.18.0 not 2.17.6 sorry as the latter is a stable release.

**Comment by strangelookingnerd** [comment]
> Fix will be in 2.18.0 not 2.17.6 sorry as the latter is a stable release.

Great, thanks for letting me know 👍🏼
