### ISSUE TITLE
QL CVS results is not readable

### ISSUE THREAD

**Issue by ysuLihua** [github/codeql#16820]
For this issue: 
https://github.com/github/codeql/issues/14872
 
I execute cmd as:
codeql query run  too_many_params.ql --database=test_python_database  --output=D:\CWE\output\test.bqrs
codeql bqrs decode D:\CWE\output\test.bqrs --format=csv

results as:
"fcn"
"Function __init__"
"Function makeRecord"

I want contain all properties:
![image](https://github.com/github/codeql/assets/26929409/7b00148a-5908-48e8-8a15-d6ceb715750f)

```[tasklist]
### Tasks
```

**Comment by ysuLihua** [comment]
What can i do for this issue?

**Comment by ysuLihua** [comment]
**Hi @jketema** 
`/**
 * @id py/examples/too-many-params
 * @kind problem
 * @problem.severity warning
 * @name Functions with many parameters
 * @description Finds functions with more than 7 parameters
 * @tags function
 *       parameter
 *       argument
 */

import python
from Function fcn
    where count(fcn.getAnArg()) > 7
select fcn,"params num is "+ fcn.getAnArg()`

**when i execute "codeql  database analyze ", The error is as follows:**
Running queries.
[1/1] No need to rerun D:\code-check\vscode-codeql-starter\ql\python\ql\examples\snippets\too_many_params.ql.
Shutting down query evaluator.
Interpreting results.
A fatal error occurred: Could not process query metadata for D:\code-check\vscode-codeql-starter\ql\python\ql\examples\snippets\too_many_params.ql.
Error was: Expected result pattern(s) are not present for problem query: Expected at least 2 columns. [INVALID_RESULT_PATTERNS]

D:\CWE\Python_Dataflow_Testcases>codeql database analyze test_python_database D:\code-check\vscode-codeql-starter\ql\python\ql\examples\snippets\too_many_params.ql --format=csv --output=D:\CWE\output\python.csv
Running queries.
[1/1] No need to rerun D:\code-check\vscode-codeql-starter\ql\python\ql\examples\snippets\too_many_params.ql.
Shutting down query evaluator.
Interpreting results.
A fatal error occurred: Could not process query metadata for D:\code-check\vscode-codeql-starter\ql\python\ql\examples\snippets\too_many_params.ql.
Error was: Expected result pattern(s) are not present for problem query: Expected at least 2 columns. [INVALID_RESULT_PATTERNS]

**How should I solve this problem?**

**Comment by jketema** [comment]
It seems there's some stale data left in your database cache. Please try re-running the analysis step with the `--rerun` option.

**Comment by ysuLihua** [comment]
@jketema Problem solved. Thank you very much.

**Comment by jketema** [comment]
You're welcome. I'll close this issue now.
