### ISSUE TITLE
[CLI] `query format` should keep set literal elements on separate lines

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#16880]
### Problem
(CodeQL CLI 2.17.6)

When you run `codeql query format`, respectively the "Format Document" action in the VS Code extension, CodeQL [set literal](https://codeql.github.com/docs/ql-language-reference/expressions/#set-literal-expressions) elements are laid out to be as compact as possible.

This is an issue when in the original code the elements were intentionally on separate lines to increase readability.

For example, formatting this code:
```codeql
import java

from Method m, string s
where
  s = m.getDeclaringType().getQualifiedName() + "#" + m.getName() and
  s =
    [
      "com.example.mypackage.subpackage.MyClass#myMethod",
      "com.example.otherpackage.MyClass#myMethod",
      "com.example.MyClass#myMethod",
      "com.example.anotherpackage.AnotherClass#withSomeMethod",
    ]
select m
```
will move `"com.example.MyClass#myMethod"` on the same line as the previous element:
```diff
   s =
     [
       "com.example.mypackage.subpackage.MyClass#myMethod",
-      "com.example.otherpackage.MyClass#myMethod",
-      "com.example.MyClass#myMethod",
+      "com.example.otherpackage.MyClass#myMethod", "com.example.MyClass#myMethod",
       "com.example.anotherpackage.AnotherClass#withSomeMethod",
```

### Suggested solution
If in the original code every set literal element was on a separate line (and maybe the set literal has at least _X_ elements), then the formatted set literal should also have all elements on separate lines.

**Comment by smowton** [comment]
Go on then -- I've made an internal PR to tolerate one-per-line style if already present; it might make it into 2.18.0 or .1

**Comment by Marcono1234** [comment]
Thanks a lot! Could you please close this issue then if / once this is available in a CodeQL release version?

(Also I hope you actually find that feature useful as well)

**Comment by smowton** [comment]
The autoformatter will allow this from 2.18.1 onwards.

In particular, if the array already has max one item per source line, it will regularise to item-per-line style; if there is any existing line with multiple items, it will pack them to lines as it did before 2.18.1.
