### ISSUE TITLE
Java: Run Database analyze and throw the Error of DatabaseQualityDiagnostics.ql

### ISSUE THREAD

**Issue by Yaote** [github/codeql#16944]
When I run database analyze on windows terminal.
And I type this command line:
```
codeql database analyze {database} ${codeql-repo}\java\ql\src\codeql-suites\java-code-scanning.qls --format=sarif-latest --output=xxx.sarif --threads=4
```

It will report this error:
Compiling query plan for D:\codeql-repo\java\ql\src\Telemetry\DatabaseQualityDiagnostics.ql.
ERROR: Expected 'implements' (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:10,21-69)
ERROR: extraneous input ';' expecting one of: Lowerid, Upperid (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:8,7-8)
ERROR: extraneous input 'predicate' expecting one of: '=', '{', Lowerid (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:10,11-20)
ERROR: extraneous input '(' expecting one of: Lowerid, Upperid (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:10,45-46)
ERROR: missing one of: '{' (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:10,70-75)
ERROR: unexpected input ')' expecting one of: '=', '(' (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:10,89-90)
ERROR: missing one of: '}' (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:86,1-2)
ERROR: Could not resolve signature ProvenancePathGraph::PathGraphSig (D:\codeql-repo\shared\dataflow\codeql\dataflow\internal\DataFlowImpl.qll:4215,57-100)
ERROR: Module PathGraph does not declare edges/4, required by implemented signature DataFlow::DataFlowMake<DataFlowImpl::MakeImpl::Location, DataFlowImpl::MakeImpl::Lang>::PathGraphSig<DataFlowImpl::MakeImpl::Impl::PathNode>. (D:\codeql-repo\shared\dataflow\codeql\dataflow\internal\DataFlowImpl.qll:4215,33-55)
ERROR: Module PathGraph does not declare nodes/3, required by implemented signature DataFlow::DataFlowMake<DataFlowImpl::MakeImpl::Location, DataFlowImpl::MakeImpl::Lang>::PathGraphSig<DataFlowImpl::MakeImpl::Impl::PathNode>. (D:\codeql-repo\shared\dataflow\codeql\dataflow\internal\DataFlowImpl.qll:4215,33-55)
ERROR: Module PathGraph does not declare subpaths/4, required by implemented signature DataFlow::DataFlowMake<DataFlowImpl::MakeImpl::Location, DataFlowImpl::MakeImpl::Lang>::PathGraphSig<DataFlowImpl::MakeImpl::Impl::PathNode>. (D:\codeql-repo\shared\dataflow\codeql\dataflow\internal\DataFlowImpl.qll:4215,33-55)
ERROR: Could not resolve signature interpretModelForTestSig/2 (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:33,3-29)
ERROR: This predicate requires a body (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:10,84-89)
WARNING: Unused variable result (D:\codeql-repo\shared\dataflow\codeql\dataflow\test\ProvenancePathGraph.qll:10,77-83)

**Comment by ginsbach** [comment]
Thank you for reaching out with this problem.

You seem to be using a very recent checkout of the _codeql_ repository that uses language features that your version of the cli/compiler is not yet supporting.

Can you try either updating your cli binaries, or otherwise using a checkout of the _codeql_ repo that matches the version of your binaries?

See also https://github.com/github/codeql-cli-binaries/releases, where it will say "This release is compatible with the CodeQL language packs from ..." for each of the cli versions.

**Comment by Yaote** [comment]
Hi @ginsbach,
Thank you for reply.

When I change the version of cli binaries to 2.17.6,
It works.

Thanks a lot.
