### ISSUE TITLE
Running multiple queries concurrently

### ISSUE THREAD

**Issue by aaaayush-n** [github/codeql#16950]
**Description of the issue**

I am running a script in golang that has to run multiple queries concurrently using `codeql query run` command, but I can't because I will get the error :

> Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. 

I can't use `codeql database run-queries ` because I am generating my queries during runtime of the script.
Also does `codeql database run-queries` run the queries aschnchronously?

What are the possible solutions to this problem?

**Comment by ginsbach** [comment]
Thank you for the question!

Our evaluator is set up to run multiple queries in different threads asynchronously (as you suggest, that is what `database run-queries` does). However, if you call `query run` repeatedly, that results in different _processes_, which cannot simultaneously co-operate on the same cache directory.

To help you with finding a solution for this, we will need a bit more context about your use case.
You say that you are "generating my queries during runtime of the script" - can you explain that in more detail?

**Comment by aaaayush-n** [comment]
@ginsbach 

> You say that you are "generating my queries during runtime of the script" - can you explain that in more detail?
Ok. So In my script I am writing new queries based on the result of some previous queries. Say a query1.ql returns me all idents whose `ident.toString()="someString"`, now I am decoding the result of this and reading the json file to get the results into my script. Now for every value I got from query1.ql I am creating copies of a query2.ql modifying the `ident.toString="<to-be-replaced>"` line inside of query2.ql using fileSystem packages in golang and I run the newly generated query2_updated1.ql, query2_updated2.ql, query2_updated3.ql, etc. to get my final results.
Now this repetition happens a lot of times and I want to run my queries parallely to save me time as my script runs for more than a few hours at times.

**Comment by ginsbach** [comment]
> Now for every value I got from query1.ql I am creating copies of a query2.ql modifying the `ident.toString="<to-be-replaced>"` line inside of query2.ql using fileSystem packages in golang and I run the newly generated query2_updated1.ql, query2_updated2.ql, query2_updated3.ql, etc. to get my final results.

It sounds like you have "generations" of queries that are generated at once. You might be able to continue with your basic setup by calling `database run-queries` on all the `query2.ql` copies at once, then generate all the `query3.ql` copies from the results as by your current approach, then call `database run-queries` to parallelise all `query3.ql` copies etc.

That being said, I would explore whether you cannot instead push more of your functionality into the QL query itself. You might be able to implement what you are currently doing via golang inside of QL. That way, you could simply rely on the parallelism of the CodeQL evaluation to do all the work for you.

**Comment by aaaayush-n** [comment]
Thanks
