### ISSUE TITLE
[Java] Question about queries execution order and caching between queries ? 

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#16977]
Hello, 

we execute our queries as an additional pack and we have these following two queries : 

(1) : missing_authn.ql 
(2) : missing_authz.ql 

as the name indicates, these queries are used to find endpoints that are missing either authn/authz.  

The general implementation of missing_authn.ql is : 

```
From Endpoints endpoint 
.. snip .. 

where not hasAuthNCheck(endpoint) and not hasAuthZCheck(endpoint)

select endpoint 
```

and implementation of missing_authz.ql is : 

```
From Endpoints endpoint 
.. snip .. 

where not hasAuthZCheck(endpoint) 

select endpoint 
```

Question : 
-  Is it possible to force the codeql cli (either in actions or direct cli) to execute missing_authn.ql query first, cache the results (between queries) of `hasAuthZCheck` so that it doesn't recompute it when running `missing_authz.ql` since it's the same predicate, same logic (just less restrictions). 

Thank you

**Comment by aibaars** [comment]
CodeQL should already have the desired behaviour when you tell it to run both queries in parallel . I assume you implemented  `hasAuthZCheck` in a separate QLL file that is imported by both queries. You could add a `cached` annotation to the predicate to tell CodeQL that you think it should be cached. Without the annotation CodeQL might still cache the results but it may decide not to, or it may decide to throw cached results away whenever it needs space.

**Comment by chmodxxx** [comment]
Yep, hasAuthZCheck is a shared library between the two files. I'll go ahead and annotate hasAuthZCheck with "cached". 

Thanks
