### ISSUE TITLE
Running "query run" on GPU

### ISSUE THREAD

**Issue by aaaayush-n** [github/codeql#17001]
I want to know if it is possible to run queries using `query run` using gpu along with cpu, right now all my query runs run only on cpu.
My CPU usage is almost 100% for the entire time the queries are being run and I think CPU is the bottleneck here.
I wish to use GPU to reduce the query run time.

**Comment by aibaars** [comment]
The CodeQL evaluator currently does not use the GPU. It's a very interesting idea though.

**Comment by rvermeulen** [comment]
Hi @aaaayush-n,

I'm closing this issue. I hope @aibaars answer was sufficiently helpful.
If you have any further questions on this topic, feel free to re-open this issue.
