### ISSUE TITLE
Including the external files in database create

### ISSUE THREAD

**Issue by aaaayush-n** [github/codeql#17027]
I want to run `codeql database create` for a golang project and I want to also include the vendor file. By default the database create command skips dependencies of a project to be included. I want to include the dependencies in my database.
How do I proceed with this?

**Comment by smowton** [comment]
https://github.com/github/codeql/pull/16925/commits/7ca57e114f0d132c08ffe7369486d094ddf22454 is not in branch `codeql-cli-2.18.0`, so it isn't in the current release, but it will be in CodeQL 2.18.1, expected later this week (Thursday or Friday)

**Comment by aaaayush-n** [comment]
Cool, Thanks!

**Comment by aaaayush-n** [comment]
Hi @smowton @mbg , I wanted to know if this update is live?

**Comment by jketema** [comment]
Yes, CodeQL 2.18.1 has been released: https://github.com/github/codeql-cli-binaries/releases/tag/v2.18.1
