### ISSUE TITLE
Issue while running scan on Java project

### ISSUE THREAD

**Issue by SagarGupta1** [github/codeql#17046]
**Description of the issue**
Hi Team,
I setup the CodeQL locally, and I was able to create the database by following the guidance given in this tutorial: https://www.returngis.net/2022/03/analizar-vulnerabilidades-en-tu-codigo-con-codeql-en-local/

But when I am running the following command:
```shell
codeql database analyze codeqldb $CODEQL_SUITES_PATH/java-code-scanning.qls \
--format=sarifv2.1.0 \
--output=$RESULTS_FOLDER/csharp-code-scanning.sarif
```
I am getting the below error:
```shell
Running queries.
A fatal error occurred: Error reading /Users/sagar.gupta/codeql/codeql-home/codeql-repo/java/ql/src/qlpack.yml: Unexpected '$'.
${workspace}
^ (through reference chain: com.semmle.frontend.packs.QlPack["dependencies"]->java.util.TreeMap["codeql/java-all"])
```
I have also set the workspace variable in my terminal as 
```shell
export workspace=<location to my project I am scanning>
```

**Comment by mbg** [comment]
Hi @SagarGupta1 👋 

It looks like the tutorial you linked to is a couple of years old and mixes a particular (two year old) version of the CodeQL CLI with the most recent version of the `codeql` repository. If you have followed the commands shown in that tutorial precisely, you will probably have ended up with version 2.8.2 of CodeQL. You can verify this by running `codeql version`. If this shows 2.82, then it's likely that there are issues when using such an old version with an up-to-date version of the `codeql` repository. 

I would recommend that you install the latest, non-draft version of the CodeQL CLI, which you can find on https://github.com/github/codeql-cli-binaries/releases/. Once installed and you have verified with `codeql version` that it is the latest version, recreate the database and try running the analyze command again.

**Comment by SagarGupta1** [comment]
Thanks, it resolved the problem
