### ISSUE TITLE
CodeQL on Windows 2022 calling SED on csharp=OK status message

### ISSUE THREAD

**Issue by matross-gh** [github/codeql#17081]
### My Environment

- GHES 3.13.0 in Azure VM
- One (1) dedicated Windows 2022 domain joined runner STIGd to 98% (everything works fine) for CodeQL
    - Using PowerShell 7.4.3
    - using Node 20
- Running: `github/codeql-action/init@v3` with output from action:
    - Found CodeQL tools version 2.16.5 in the toolcache.

### Test Project

- dotnet new webapi -n CustomerAPI  (stands up .net 8.0)

### Setup CodeQL in GHES

- Repo -> Settings -> Code Security and Analysis -> Code Scanning -> CodeQL Analysis
- Choose Default

### Expectation

- Completes setup, however it fails.  Reviewing the workflow there is a CodeQL error.

### Error

``` bash
Run echo "csharp=OK" | sed s/-/_/ >> "$GITHUB_OUTPUT"
sed: D:\actions-runner\_work\_temp\1b526554-1d4a-4117-8b7e-3caadff57d6c.ps1:2
Line |
   2 |  echo "csharp=OK" | sed s/-/_/ >> "$GITHUB_OUTPUT"
     |                     ~~~
     | The term 'sed' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.
Error: Process completed with exit code 1.
```

**Comment by mbg** [comment]
Hi @matross-gh 👋 

Thanks for the issue report. I'm guessing the validation workflow for default setup expects to be run on a linux runner. I will let the relevant team know that this breaks on Windows.

**Comment by matross-gh** [comment]
@mbg Yea I believe so, I updated to 3.13.2.  The management console show that version but when I log in to work with my repos that shows 3.13.0.  I can use Advanced Setup for CodeQL and that works.  So, I have a work-around for now..

**Comment by mbg** [comment]
> I updated my GHES to 3.13.2

Yes, that version of GHES should force Bash to avoid the issue.

> The management console show that version but when I log in to work with my repos that shows 3.13.0.

That's odd, but that has nothing to do with CodeQL or Code Scanning, so I'd advise contacting Enterprise support for this.

> I can use Advanced Setup for CodeQL and that works. So, I have a work-around for now..

Yes, that should be a suitable workaround if you are happy with it! 

I'll close this issue now since we have fixed the issue in GHES 3.13.2 and above and you have a workaround.

**Comment by matross-gh** [comment]
@mbg One last note.. I updated my github/codeql-action (using action-sync) and it runs 2.18.1 and the default still fails looking for sed.  Using advanced setup is ok.  Will watch for update in the next go! thanks!

**Comment by mbg** [comment]
There are three different components at play here:

1. Default setup
2. CodeQL
3. CodeQL Action

All three are essentially independent of each other. You've updated the version of the CodeQL Action to the latest. As a result, it _defaults_ to the latest version of CodeQL (2.18.1). 

The workflow used by Default Setup is independent of both of these. The version of GHES you are using determines which version of the Default Setup workflow you have. 

Consequently, only updating GHES to 3.13.1 or above will give you a Default Setup workflow that doesn't have this problem.
