### ISSUE TITLE
How to build go/extractor

### ISSUE THREAD

**Issue by hac425xxx** [github/codeql#17099]
I want to build go/extractor, but failed.

```
┌──(kali㉿kali)-[~/codeql-main/go/extractor]
└─$ ~/bazel-7.3.0rc1-linux-x86_64 run //go:gen
INFO: Analyzed target //go:gen (43 packages loaded, 4896 targets configured).
ERROR: /home/kali/codeql-main/go/extractor/util/BUILD.bazel:5:11: GoCompilePkg go/extractor/util/util.a failed: (Exit 1): builder failed: error executing GoCompilePkg command (from target //go/extractor/util:util) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/rules_go~~go_sdk~codeql__download_0/builder_reset/builder compilepkg -sdk external/rules_go~~go_sdk~codeql__download_0 -installsuffix linux_amd64 -src ... (remaining 23 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: missing strict dependencies:
	/home/kali/.cache/bazel/_bazel_kali/605d7994aea9d9db10c967d0570949e5/sandbox/linux-sandbox/9/execroot/_main/go/extractor/util/semver.go: import of "golang.org/x/mod/semver"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //go:gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 24.413s, Critical Path: 0.21s
INFO: 13 processes: 13 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target

┌──(kali㉿kali)-[~/codeql-main/go/extractor]
└─$ go build

┌──(kali㉿kali)-[~/codeql-main/go/extractor]
└─$ ls ~/goroot/pkg/mod/golang.org/x/
mod@v0.19.0  sync@v0.7.0  tools@v0.23.0

┌──(kali㉿kali)-[~/codeql-main/go/extractor]
└─$ 

```

**Comment by hac425xxx** [comment]
the package "golang.org/x/mod" is installed.

**Comment by mbg** [comment]
Hi @hac425xxx 👋 

The intended way to build the extractor is to run `make` in the `go` directory. Have you tried that? If so, is it working or do you get the same error as above?

**Comment by criemen** [comment]
Hi @hac425xxx ,
```
bazel build //go
```
should do the job for building, and 
```
bazel run //go:go-installer
```
will install the language pack in-tree in `go/extractor-pack`. Otherwise, if you don't want to use bazel, you can use the `make`-based build as @mbg explained.

**Comment by hac425xxx** [comment]
the same error
```
┌──(kali?kali)-[~/codeql-main/go]
└─$ make
bazel run :gen
Starting local Bazel server and connecting to it...
INFO: Analyzed target //go:gen (176 packages loaded, 16877 targets configured).
ERROR: /home/kali/codeql-main/go/extractor/util/BUILD.bazel:5:11: GoCompilePkg go/extractor/util/util.a failed: (Exit 1): builder failed: error executing GoCompilePkg command (from target //go/extractor/util:util) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/rules_go~~go_sdk~codeql__download_0/builder_reset/builder compilepkg -sdk external/rules_go~~go_sdk~codeql__download_0 -installsuffix linux_amd64 -src ... (remaining 23 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: missing strict dependencies:
	/home/kali/.cache/bazel/_bazel_kali/605d7994aea9d9db10c967d0570949e5/sandbox/linux-sandbox/17/execroot/_main/go/extractor/util/semver.go: import of "golang.org/x/mod/semver"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //go:gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.001s, Critical Path: 1.02s
INFO: 27 processes: 12 internal, 15 linux-sandbox.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
make: *** [Makefile:34: gen] Error 1

```

**Comment by hac425xxx** [comment]
But I have compile the code by import code to goland, I generate some trap file

![image](https://github.com/user-attachments/assets/9bab76cb-1072-4eac-b141-57840dace836)

How can I convert the trap file to codeql db.

I am try to implement a new extractor for another language， and want to refer to go's extrator for development.

And I would like to ask if I want to develop a new extractor, do I only need to implement the process from AST to trap file, and then I can reuse existing tools to generate codeql database?

**Comment by hac425xxx** [comment]
@mbg

**Comment by mbg** [comment]
Hi again @hac425xxx and sorry that `make` still isn't working for you. I have looked into this a bit. Could you try running `bazel run @gazelle//cmd/gazelle -- update-repos -from_file=go/extractor/go.mod` and then `make` again? It seems we may have forgot to update some files when we moved away from vendored dependencies recently. If that works for you, let us know and we will update this in the repository as well.

**Comment by mbg** [comment]
For your other question about TRAP files: the process of converting these to a database is handled by the CodeQL CLI. Extractors output TRAP files and the CLI converts them into a CodeQL database. However, we also have language-specific database schemas that are needed for this. Normally this happens as part of the `codeql database create` process, but you can also run it as a manual step with `codeql dataset import`. Broadly, you will need to implement:

- An extractor for your language that turns code written in it into TRAP files
- A database schema for the entities that your extractor is extracting and that are contained in the TRAP files
- QL libraries for your language to model control flow, data flow, and queries

**Comment by hac425xxx** [comment]
@mbg 

I write a simple extractor and use import command. it seems no error.

```
codeql.exe dataset import --dbscheme=F:\codeql-win64\codeql\go\go.dbscheme -- xxx.dset F:\sca\d1\F_\sca\binary\testbin64_8.3\out\a.so_0.json.trap.gz
Importing TRAP files
Merging relations
Finished writing database (relations: 10.92 KiB; string pool: 3.06 MiB).
```

But I can't open it with vscode codeql plugin, and database finalize also failed.

```
> codeql.exe database finalize .\xxx.dset\
A fatal error occurred: F:\sca\ida2codeql\xxx.dset is not a recognized CodeQL database.
```

error log for vscode.
```
Failed to choose and set database: 'f:\\xxx.dset' does not contain a dataset directory.
Error: 'f:\xxx.dset' does not contain a dataset directory.
    at findDataset (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109703:11)
    at Function.resolveDatabase (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109681:24)
    at Function.resolveDatabaseContents (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109655:22)
    at DatabaseManager.createDatabaseItem (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109923:22)
    at DatabaseManager.openDatabase (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109799:26)
    at DatabaseUI.chooseAndSetDatabase (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:111053:14)
    at DatabaseUI.chooseDatabaseFolder (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:110511:7)
    at withProgress.title (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:110525:9)
Failed to choose and set database: 'f:\\xxx.dset\default' does not contain a dataset directory.
Error: 'f:\xxx.dset\default' does not contain a dataset directory.
    at findDataset (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109703:11)
    at Function.resolveDatabase (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109681:24)
    at Function.resolveDatabaseContents (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109655:22)
    at DatabaseManager.createDatabaseItem (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109923:22)
    at DatabaseManager.openDatabase (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:109799:26)
    at DatabaseUI.chooseAndSetDatabase (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:111053:14)
    at DatabaseUI.chooseDatabaseFolder (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:110511:7)
    at withProgress.title (c:\Users\sta\.vscode\extensions\github.vscode-codeql-1.13.1\out\extension.js:110525:9)
```

**Comment by hac425xxx** [comment]
the compile is still error.

```
┌──(kali㉿kali)-[~/codeql-main/go]
└─$ bazel run @gazelle//cmd/gazelle -- update-repos -from_file=go/extractor/go.mod
INFO: Analyzed target @@gazelle~//cmd/gazelle:gazelle (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @@gazelle~//cmd/gazelle:gazelle up-to-date:
  bazel-bin/external/gazelle~/cmd/gazelle/gazelle_/gazelle
INFO: Elapsed time: 0.274s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/external/gazelle~/cmd/gazelle/gazelle_/gazelle update-repos '-from_file=go/extractor/go.mod'

┌──(kali㉿kali)-[~/codeql-main/go]
└─$ make
bazel run :gen
INFO: Analyzed target //go:gen (0 packages loaded, 0 targets configured).
ERROR: /home/kali/codeql-main/go/extractor/util/BUILD.bazel:5:11: GoCompilePkg go/extractor/util/util.a failed: (Exit 1): builder failed: error executing GoCompilePkg command (from target //go/extractor/util:util) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/rules_go~~go_sdk~codeql__download_0/builder_reset/builder compilepkg -sdk external/rules_go~~go_sdk~codeql__download_0 -installsuffix linux_amd64 -src ... (remaining 23 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: missing strict dependencies:
	/home/kali/.cache/bazel/_bazel_kali/605d7994aea9d9db10c967d0570949e5/sandbox/linux-sandbox/38/execroot/_main/go/extractor/util/semver.go: import of "golang.org/x/mod/semver"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //go:gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.372s, Critical Path: 0.10s
INFO: 4 processes: 4 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
make: *** [Makefile:34: gen] Error 1

┌──(kali㉿kali)-[~/codeql-main/go]

```

**Comment by mbg** [comment]
> I write a simple extractor and use import command. it seems no error.

Good, this has created a _dataset_ from the TRAP files.

> But I can't open it with vscode codeql plugin, and database finalize also failed.

This is not unexpected, because a _dataset_ is not a _database_. You cannot use the dataset you created with `codeql dataset import` instead of a database. A dataset is only part of a database.

If you want a database, then you need to first initialise one with `codeql database init`. You can then populate this with TRAP files, and those will then be imported when you run `codeql database finalize`. There should be no need to run `codeql dataset import` manually, it is part of `codeql database finalize`.

**Comment by hac425xxx** [comment]
Can `codeql database init` specify how to extract the trap files. 

Currently, I can only generate trap files separately and then import them to codeql.

How can use `codeql database init`  import the generated trap files? 

And could you give the complete command line parameters? thanks.

I tried some but it didn't work.

@mbg

**Comment by mbg** [comment]
> Can `codeql database init` specify how to extract the trap files.

No, `codeql database init` has nothing to do with TRAP files. It just initialises an empty database.

TRAP files are expected to be located in `trap/{primary language}` within the database folder. You can see the expected layout of a database by running an ordinary `codeql database create` for e.g. some Go project with the `--keep-trap` flag. In that case the TRAP files will be in `{database root}/trap/go`. 

So what you might be able to do is run `codeql database init`, store your TRAP files in the database in the expected location, and then run `codeql database finalize` which should import them from there. 

That being said, all of that is kind of hacky. We don't have any documentation or guides for how to create custom extractors, but one of my colleagues has a self-contained, open-source extractor for the Kaleidoscope toy language (from the LLVM tutorials) at https://github.com/aibaars/codeql-kaleidoscope -- this may give you an idea of how you can create a complete, custom extractor and how that can be used with the standard CodeQL CLI commands.

**Comment by hac425xxx** [comment]
Thanks a lot, I init the database and copy trap file to trap/go (because I currenty reuse the go extractor codebase), and run finalize

```
PS > codeql.exe database init -l go -s .\awesomeProject\  init8

PS F:\sca\l> F:\sca\codeql-win64\codeql\codeql.exe database finalize  init8
CodeQL detected code written in Go but could not process any of it. For more information, review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build.
```

Is there some method let codeql ignore the source code, because I am try to extract the target without source.

**Comment by hac425xxx** [comment]
thanks a lot again, 
I have another question, how the codeql know the location extractor,how to call the extractor , and  how the codeql pass argument to the extractor
```
codeql database create \
    --language=kaleidoscope --overwrite \
    --search-path $PWD/extractor-pack \
    --source-root ./testing/source \
    ./testing/database
```

**Comment by hac425xxx** [comment]
I can open the database in vscode by copy the result of `codeql.exe dataset import`  to the `{db path}/db-go`.

because I don’t have a deep understanding of trap files at present, the data flow analysis in the output database is  not work properly.

I want to debug this,  is there some useful tool to debug or check the database infomation, such as ast, cfg

because my extract target don't have source, I can't use the vscode to check the ast, can I use command line tool to extract the ast.

I currently review the trap file line by line, It's hard to find the problem.

**Comment by redsun82** [comment]
Hi @hac425xxx: about building the go extractor, could you test whether https://github.com/github/codeql/pull/17145 helps you maybe? We might be merging that soon, so maybe by the time you read this it will already be in `main`.

**Comment by hac425xxx** [comment]
@redsun82 it works, thanks.

**Comment by redsun82** [comment]
Thanks for letting me know @hac425xxx, I just merged that PR now 🎉
