### ISSUE TITLE
C++: Recommended way for adding custom taint sources

### ISSUE THREAD

**Issue by artem-smotrakov** [github/codeql#17106]
Hey team! I have custom remote taint sources for my codebase which I currently enable like this

```MySecurityOptions.qll
import semmle.code.cpp.security.Security

class MySecurityOptions extends SecurityOptions {

  override predicate isUserInput(Expr expr, string cause) {
    SecurityOptions.super.isUserInput(expr, cause)
    or
    exists(MyTaintSource source | source.isUserInput(expr, cause))
  }
}
```
Then, I import it in `cpp.qll` like this

```cpp.qll
[...]
import MySecurityOptions
```

When I upgraded to the latest CodeQL, I see a deprecation warning for `isUserInput()`. If I understand correctly, this API was [deprecated](https://github.com/github/codeql/commit/5165999e9e2d7340c0530d6f5ab08a3e93a6be48) in `2.18.1`. Unfortunately, the [release notes](https://github.com/github/codeql-cli-binaries/releases/tag/v2.18.1) didn't mention this deprecation and what should be used instead.

Going forward, what is the recommended way for adding custom taint sources and other security customizations for C++?

Thank you!

**Comment by jketema** [comment]
This was deprecated in CodeQL 2.16.0. For the change not see: https://github.com/github/codeql/blob/59e22f6cd93968492d15ad5bf6d1a8529cf1015b/cpp/ql/lib/change-notes/released/0.12.3.md?plain=1#L5

**Comment by artem-smotrakov** [comment]
Thanks!

Do I understand correctly, that the extension mechanism does not allow plugging it custom CodeQL code to the standard lib? I guess the only way to do that is to create a model pack with 

```
extensionTargets:
  codeql/cpp-all: ...
```

but model packs are not currently supported by C++. 

https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/creating-and-working-with-codeql-packs#creating-a-codeql-model-pack

Is that correct?

**Comment by jketema** [comment]
That's correct.

**Comment by artem-smotrakov** [comment]
Cool. Hope model packs will be available for C++ soon. This feature looks quite nice. Thanks!
