### ISSUE TITLE
ql language support more arithmetic or bitwise operations? 

### ISSUE THREAD

**Issue by wenta0g** [github/codeql#17133]
Dear codeql team,

I've been trying to customize some queries that involves checking if a literal has its i th bit set as 1. The doc said QL language only supports five binary operators + - x / %. So I'm writing to suggest some new features, if that is possible and beneficial.

Would it be possible for the ql evaluators to recognize more operators like bit-wise operators, square root or exponent? It would be very helpful for some range queries or some dataflow/taint analysis. Thanks in advance.

**Comment by jketema** [comment]
Hi @wenta0g, 

These operations actually exist, but they come in the form of predicates for the primitive types.

For example,
* for int: https://codeql.github.com/codeql-standard-libraries/cpp/type.int.html
* for float: https://codeql.github.com/codeql-standard-libraries/cpp/type.float.html

So if I have a variable `f` of type `float` I can, for example, do: `f.floor()`.

**Comment by wenta0g** [comment]
Thanks @jketema for sharing the docs!
