### ISSUE TITLE
"No space left on device" regression with 2.18.1 

### ISSUE THREAD

**Issue by cary-ilm** [github/codeql#17141]
**Description of the issue**

The CodeQL c-cpp workflow on the [OpenEXR](https://github.com/AcademySoftwareFoundation/openexr) repo began failing on July 27. We use the default [configuration](https://github.com/AcademySoftwareFoundation/openexr/blob/main/.github/workflows/codeql.yml), and runs have traditionally taken 4-12 minutes, but without significant changes to our code, runs began taking 1 hour and failing with the disk filling up. I reverted the repo back to the commit from the last successful run and it failed, indicating it's not likely  something on our end.

I managed to revert the version of CodeQL in the workflow to 2.18.0, and everything is back to working smoothly.

Any clues what might be causing this?

The log from the last successful run is [here](https://github.com/AcademySoftwareFoundation/openexr/actions/runs/10096428315). Log from the first failed run is [here](https://github.com/AcademySoftwareFoundation/openexr/actions/runs/10127674204).

The PR that address the problem for OpenEXR by reverting to 2.18.0 is [here](https://github.com/AcademySoftwareFoundation/openexr/pull/1790).

**Comment by geoffw0** [comment]
Hi @cary-ilm , I have confirmed there is a problem with the performance (both time and space) of alias analysis computations on this database.  We'll let you know here when there's a solution.

**Comment by jketema** [comment]
Hi @cary-ilm,

We merged [a fix](https://github.com/github/codeql/pull/17225). The fix should be part of CodeQL 2.19.3, which will be released in a few weeks.
