### ISSUE TITLE
Need help in implementing a predicate in a query

### ISSUE THREAD

**Issue by aaaayush-n** [github/codeql#17153]
**Description of the issue**
I want to write a predicate similar to getEnclosingFunction() for `TypeDecl`s  and `ParameterOrResultDecl`s.
The problem I am facing is i want to limit my search of certain entities to a particular TypeDecl but there is no convenient predicate like getEnclosingTypeDecl() that I can use. 

Please 
1.share the implementation of `getEnclosingFunction()` predicate  
2. help me write some similar predicate for any type in codeql(but particularly `TypeDecl` and `ParameterOrResultDecl`).

**Comment by smowton** [comment]
`ParameterOrResultDecl` has the required predicate:

```ql
from ParameterOrResultDecl d
select d.getEnclosingFunction()
```

The implementation can be found in AST.qll -- try ctrl/cmd-clicking in VS Code to navigate to the definition.

```ql
  /** Gets the innermost function definition to which this AST node belongs, if any. */
  FuncDef getEnclosingFunction() { result = this.getParent().parentInSameFunction*() }
```

`TypeDecl` similarly inherits `getEnclosingFunction` from `ASTNode`, so the same query will work with `from TypeDecl d`.

**Comment by hac425xxx** [comment]
hello @smowton , can you help for https://github.com/github/codeql/issues/17147#issuecomment-2270174282  , thanks a lot!

**Comment by aaaayush-n** [comment]
@smowton I think I was not able to explain my problem, What I want to do is
```
from TypeVariable tv,ParameterOrResultDecl d
where tv.getEnclosingParameterDecl()=d
select tv
```
I want to make sure that `tv` is a child of `d`. I don't want to know or worry about which child it is... it may be nested inside any amount of selector nodes.
So for all ast node structures like
ParameterDecl>SelectorExpression>SelectorExpression>MapTypeExpression>SelectoExpression>.....>TypeVariable
I only want to worry about `TypeVariable`s  being enclosed in ParameterDecl/ResultDecl

**Comment by smowton** [comment]
We don't have `TypeVariable` in Golang, and I infer from `ParameterOrResultDecl` that we must be talking about QL for Golang? Could you give an example of some Go source code and what you want to identify?
