### ISSUE TITLE
Can CodeQL CLI fire MRVA query ?

### ISSUE THREAD

**Issue by Sim4n6** [github/codeql#17187]
An idea comes to my mind. 

> Can CodeQL CLI fire MRVA query ?   

I mean can I using CodeQL cli programmatically request the running of a query at scale using MRVA? 

Thank you

**Comment by smowton** [comment]
The security lab have an unofficial / unsupported tool for this at https://github.com/GitHubSecurityLab/gh-mrva which might be useful?

**Comment by Sim4n6** [comment]
Sweet 🥇
