### ISSUE TITLE
Are there any keywords that should not be used  in codeql?

### ISSUE THREAD

**Issue by espark0301** [github/codeql#17194]
In a typescript project, if there is a keyword called "Date" in the code comment, it stops at that file during the extracting step. 
 Are there any keywords that should not be used  in codeql?

**Comment by ginsbach** [comment]
Thank you for the question!

Do I understand correctly that CodeQL extraction is failing on one of your projects, and the apparent cause is the use of the word "Date" in a comment in one of the source files?

Would you be able to share the extractor log files? This would help us identify the issue.
