### ISSUE TITLE
How to parse and display SARIF Files?

### ISSUE THREAD

**Issue by KiRito02** [github/codeql#17217]
**Description of the issue**
Whenever I execute code scanning and generate a SARIF file, I always read and parse it in standard JSON format, which makes it difficult to display. Are there any tools or methods to visualize the generated SARIF file without using editors like IDEA or VS Code?

Are there any tools or platforms that can visualize the generated SARIF files?

**Comment by ginsbach** [comment]
Thank you for the question!
Is there a particular reason why you are excluding VS Code as an option? Unfortunately, I am not aware of a standalone viewer, but I would recommend the `SARIF Viewer` extension for Visual Studio Code.

**Comment by aibaars** [comment]
There are some viewers mentioned on https://sarifweb.azurewebsites.net/#Viewers , two of them are IDE extensions, but one of them is a react-component for viewing in the browser (you can try it out via https://microsoft.github.io/sarif-web-component/)

There are also some command line tools for processing SARIF, for example 
* https://github.com/microsoft/sarif-tools?tab=readme-ov-file#sarif-tools (can export to CSV which can be viewed in Excel or similar)
* https://github.com/microsoft/sarif-sdk/blob/main/docs/multitool-usage.md
