### ISSUE TITLE
 Apple Silicon arm64 releases?

### ISSUE THREAD

**Issue by mbuotidem** [github/codeql#17229]
We have a project that is horribly slow when running `xcodebuild` in CodeQL. For context, even with fairly beefy runners, Apple M3 Pro, 36GB, running the CodeQL job takes an hour and 20 minutes on average. The same build without codeql takes 10 minutes.  Based on [this](https://github.com/github/codeql-action/issues/2266#issuecomment-2253032783),  our suspicion is that it has to do with CodeQL's current use of rosetta. 

I see that this issue has been open since 2021, https://github.com/github/codeql-cli-binaries/issues/97 and on there, was a the suggestion to check the roadmap but at the moment, there seems to be no mention of this on it. 

What is the roadmap for when we could see a native arm64 binary? Are there any plans to do this at all?

**Comment by ginsbach** [comment]
Thank you for the question!
Unfortunately, the responses on https://github.com/github/codeql-cli-binaries/issues/97 still apply - arm64 support is not on the public roadmap and we can’t commit to a timeline for Linux/ARM support yet.

**Comment by ginsbach** [comment]
Thank you for the question.

The issue https://github.com/github/codeql-cli-binaries/issues/97 still applies - arm64 support on macOS is in beta (see [system requirements](https://codeql.github.com/docs/codeql-overview/system-requirements/)) and full support is not on our public roadmap.

However, perhaps we can help.
Could you share a bit more about the project that you are trying to build a database for? Could you also share the extractor logs (`database-create-___.log`).

**Comment by mbuotidem** [comment]
Thanks for the response. I'll keep an eye on the roadmap and the other issue to see if it shows up one of these days. 

I'm happy to share logs, but is there a way to do so privately?

**Comment by ginsbach** [comment]
If you want us to have a look at potential problems that might cause your slow build but don't want to share the logs publicly then it might be easiest to open a separate support ticket with the logs attached.

**Comment by mbuotidem** [comment]
Thank you, I've opened one and I linked this issue to it so hopefully it gets routed to you!

**Comment by aibaars** [comment]
> Thank you, I've opened one and I linked this issue to it so hopefully it gets routed to you!

We received your support ticket, let's move the conversation there.
