### ISSUE TITLE
RemoteFlowSource as response body

### ISSUE THREAD

**Issue by Sim4n6** [github/codeql#17231]
I come across [RemoteFlowSource](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/java/dataflow/FlowSources.qll/type.FlowSources$RemoteFlowSource.html) as a response.body , how come a response.body is a source of untrusted input, please ?

**Comment by ginsbach** [comment]
Thank you for the question!
Please, can you share some more context for us to be able to respond?
What query are you trying to write; can you share the code; what do you want to use RemoteControlSource for?

**Comment by Sim4n6** [comment]
>  Please, can you share some more context for us to be able to respond?

I have a query which its Source is a RemoteFlowSource. It caught response.body as a source. 

Well , let me think a bit if I could control the URL or what the body reflect that would work 

Thanks man I figure it out
