### ISSUE TITLE
Error was: Unknown kind "Table". [UNSUPPORTED_KIND]

### ISSUE THREAD

**Issue by Fr1ezy** [github/codeql#17388]
2024-09-05 12:29:29] [DETAILS] database interpret-results> Interpreted definitions query "Jump-to-definition links" (java/jump-to-definition) at path /root/Drone/sast/code/java-database/results/codeql/java-queries/definitions.bqrs.
[2024-09-05 12:29:29] Exception caught at top level: Could not process query metadata for /root/Drone/sast/code/java-database/results/codeql/java-queries/meta/frameworks/Coverage.bqrs.
                      Error was: Unknown kind "Table". [UNSUPPORTED_KIND]
                      com.semmle.analysis.ql.QLToAnalysis.lambda$addQuery$4(QLToAnalysis.java:203)
                      java.base/java.util.Optional.map(Unknown Source)
                      com.semmle.util.data.Result.getOrThrow(Result.java:31)
                      com.semmle.analysis.ql.QLToAnalysis.addQuery(QLToAnalysis.java:197)
                      com.semmle.analysis.ql.QLToAnalysis.addQuery(QLToAnalysis.java:162)
                      com.semmle.cli2.database.InterpretResultsCommand.executeSubcommand(InterpretResultsCommand.java:320)
                      com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:863)
                      com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
                      com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:861)
                      com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:119)
                      com.semmle.cli2.picocli.SubcommandCommon.execPlumbingInProcess(SubcommandCommon.java:227)
                      com.semmle.cli2.database.AnalyzeCommand.continueAfterRunningQueries(AnalyzeCommand.java:198)
                      com.semmle.cli2.execute.ExecuteQueriesCommand.executeSubcommand(ExecuteQueriesCommand.java:757)
                      com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:863)
                      com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
                      com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:861)
                      com.semmle.cli2.picocli.SubcommandCommon.toplevelMain(SubcommandCommon.java:745)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:726)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:237)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:257)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:115)

**Comment by hvitved** [comment]
What is the context here? The query `java/jump-to-definition` will not work with `codeql database interpret-results` because it doesn't have a query kind that is compatible with SARIF (such as `@kind problem` or `@kind path-problem`).

**Comment by Fr1ezy** [comment]
codeql database analyze newbee-database /root/Drone/SAST/codeql-linux64/codeql-codeql-cli-v2.18.3/java/ql/src --format=csv --output=result.csv

**Comment by hvitved** [comment]
The problematic bit here is `/root/Drone/SAST/codeql-linux64/codeql-codeql-cli-v2.18.3/java/ql/src`, which means it will run _any_ `.ql` file, including the one for `java/jump-to-definition`. So you probably want to point it at a relevant query suite (`.qls`) file instead.

**Comment by Fr1ezy** [comment]
> 这里有问题的位是 ，这意味着它将运行_任何_文件，包括 .因此，您可能希望将其指向相关的查询套件 （） 文件。`/root/Drone/SAST/codeql-linux64/codeql-codeql-cli-v2.18.3/java/ql/src``.ql``java/jump-to-definition``.qls`

ok thanks!

**Comment by Fr1ezy** [comment]
> The problematic bit here is , which means it will run _any_ file, including the one for . So you probably want to point it at a relevant query suite () file instead.`/root/Drone/SAST/codeql-linux64/codeql-codeql-cli-v2.18.3/java/ql/src``.ql``java/jump-to-definition``.qls`

ok thanks
