### ISSUE TITLE
Can CodeQL summarize code ?

### ISSUE THREAD

**Issue by Chakit22** [github/codeql#17428]
Can CodeQL help me to summarize a piece of code ? if so then what kind of query should be written for a javascript database.
Can CodeQL help me find the necessary files based on an issue ? Let' say I am giving it an issue, then can CodeQL help me find the relevant files to fix that issue ?

**Comment by mbg** [comment]
Hi @Chakit22 👋🏻 

Thanks for the questions. You can read about what CodeQL is and can do for you in [our documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/). If that does not answer your questions, could you be more specific about: what sort of summaries of the code you are hoping for? E.g. CodeQL could get you a list of all functions in the code. What representation would your issues be in?

**Comment by mbg** [comment]
Hi @Chakit22,

I don't think CodeQL is what you are looking for. CodeQL is a static analysis tool and uses queries written in a programming language called QL. [Copilot](https://github.com/features/copilot) may be more suited to what you are looking to do, I think.

**Comment by Chakit22** [comment]
Okay @mbg , so could you describe in detail as to what did you mentioned it is a static analysis tool ? Can it perform semantic search ? I know about Copilot, but wanted to know if CodeQL does that.

**Comment by mbg** [comment]
I hope that's answered your questions, so I will go ahead and close this issue for now. Do feel free to follow-up if you have any further questions though.
