### ISSUE TITLE
Add Dart language

### ISSUE THREAD

**Issue by lsaudon** [github/codeql#17447]
**Description of the issue**

It would be good if CodeQL supported [Dart](https://dart.dev/).

**Comment by mbg** [comment]
Hi @lsaudon 👋🏻 

Noted, thanks for the suggestion! We do not currently have any plans to add support for Dart. You can keep an eye on our [public roadmap](https://github.com/orgs/github/projects/4247) for updates if that changes and on our plans to support additional languages generally.

**Comment by fguisso** [comment]
There is any advice if a community member wants to start this feature?

**Comment by rvermeulen** [comment]
Hi @fguisso,

There is no official support for third-party extractors at this point in time. That doesn't mean you cannot implement one. The following repo provides a starting point https://github.com/aibaars/codeql-kaleidoscope.

**Comment by guissow** [comment]
Any updates here? @mbg @rvermeulen
