### ISSUE TITLE
CodeQL returns invalid types for almost all DataFlow::Nodes

### ISSUE THREAD

**Issue by tylergu** [github/codeql#17452]
**Description of the issue**

We are trying to analyze the mariadb-operator at https://github.com/mariadb-operator/mariadb-operator
by directly importing the database from the GitHub link.

We wrote a simple query like following:
```ql
/**
 * @name MariaDB
 * @kind problem
 * @problem.severity warning
 * @id go/example/mariadb
 */

import go

from DataFlow::Node src
where src.getFile().getBaseName() = "switchover.go"
select src, src.getType().toString()
```

The results returned by this query are mostly `invalid types`, except six `int` types for four slice items.
```
"MariaDB",,"warning","int","/pkg/controller/replication/switchover.go","58","3","58","3"
"MariaDB",,"warning","int","/pkg/controller/replication/switchover.go","62","3","62","3"
"MariaDB",,"warning","int","/pkg/controller/replication/switchover.go","66","3","66","3"
"MariaDB",,"warning","int","/pkg/controller/replication/switchover.go","70","3","70","3"
"MariaDB",,"warning","int","/pkg/controller/replication/switchover.go","74","3","74","3"
"MariaDB",,"warning","int","/pkg/controller/replication/switchover.go","78","3","78","3"
"MariaDB",,"warning","invalid type","/pkg/controller/replication/switchover.go","174","46","174","48"
"MariaDB",,"warning","invalid type","/pkg/controller/replication/switchover.go","264","46","264","48"
"MariaDB",,"warning","invalid type","/pkg/controller/replication/switchover.go","22","6","22","20"
"MariaDB",,"warning","invalid type","/pkg/controller/replication/switchover.go","28","5","28","27"
"MariaDB",,"warning","invalid type","/pkg/controller/replication/switchover.go","28","5","28","25"
"MariaDB",,"warning","invalid type","/pkg/controller/replication/switchover.go","28","5","28","7"
...
```

We are expecting the types for the dataflow nodes to be the actual types of the values.

Are we writing the wrong query? Or is this caused by how the database is created?
---

If we try to create the database manually, using the command:
```
codeql database create codeql/mariadb-operator --language=go --source-root ~/repos/mariadb-operator/  --command "go1.23.1 build cmd/controller/main.go cmd/controller/cert_controller.go cmd/controller/webhook.go"
```
The command fails with 32 error code with error message: `CodeQL detected code written in Go but could not process any of it.`
Although we are able to build the project using the command specified in the `--command` argument.

Any insight would be helpful, thanks!

**Comment by mbg** [comment]
Hi @tylergu 👋🏻 

Thanks for reporting this! 

Let me start with your problem creating the database. I think the problem here is that you are specifying individual Go source files as arguments to `go build`. I was able to successfully generate a database with e.g. `--command "go build ./..."`. 

It seems that when just the Go source files are given to `go build`, we end up with the following error: "internal error: package "github.com/mariadb-operator/mariadb-operator/api/v1alpha1" without types was imported from "command-line-arguments"". I will investigate further whether this is down to something we are doing or expected in this case.

Seeing "invalid types" in your query results usually indicates that there is a mismatch between the version of CodeQL that the database was created with and the version of CodeQL that you are using. I can see that the current database for `mariadb-operator/mariadb-operator` was generated with CodeQL 2.18.3 so you should make sure that you have the same version (or newer). Could you check which version of CodeQL you are using?

**Comment by tylergu** [comment]
@mbg Thanks for the response. I ran `codeql version` and see that it is `CodeQL command-line toolchain release 2.18.3.`
Previously I was using the vscode plugin to run queries. To make sure that I am using the installed codeql CLI, I ran the query with the CLI but still got the invalid types from the results.
```
codeql query run ...
>

Compiling query plan for /Users/tylergu/repos/codeql/codeql-custom-queries-go/mariadb.ql.
[1/1] Found in cache: /Users/tylergu/repos/codeql/codeql-custom-queries-go/mariadb.ql.
mariadb.ql: Evaluation completed (2.4s).
|                                       src                                        |     col1     |
+----------------------------------------------------------------------------------+--------------+
| element index                                                                    | int          |
| element index                                                                    | int          |
| element index                                                                    | int          |
| element index                                                                    | int          |
| element index                                                                    | int          |
| element index                                                                    | int          |
| 1                                                                                | invalid type |
| 1                                                                                | invalid type |
| rhs of increment statement                                                       | invalid type |
| rhs of increment statement                                                       | invalid type |
| switchoverPhase                                                                  | invalid type |
| call to IsMaxScaleEnabled                                                        | invalid type |
| selection of IsMaxScaleEnabled                                                   | invalid type |
| mdb                                                                              | invalid type |
| call to IsRestoringBackup                                                        | invalid type |
| selection of IsRestoringBackup                                                   | invalid type |
| mdb                                                                              | invalid type |
| call to IsUpdating                                                               | invalid type |
| selection of IsUpdating                                                          | invalid type |
| mdb                                                                              | invalid type |

```

**Comment by mbg** [comment]
The output suggests that the results are cached (`[1/1] Found in cache:`). You could try running `codeql database cleanup` to clean up the cache first and then re-run the query. Also make sure that your CLI isn't just the right version, but is also using an up-to-date version of the query libraries or, if you are using a clone of the `codeql` repo, make sure it's up-to-date.

**Comment by tylergu** [comment]
I used codeql from source and got it working.

I think the problem was that I upgrade the version of codeql through homebrew recently, and somehow the versions are messed up.

Thanks! @mbg
