### ISSUE TITLE
Java: data-flow / via-point query

### ISSUE THREAD

**Issue by whyaicn** [github/codeql#17544]
In a Java program, I want to know if CodeQL can find a specific call path, where the source is a remote or external input data source (I feel that RemoteFlowSource can meet this requirement), and then pass through a specific method (for example, the method's name is validate, and its package name is org.example.openadmin.server, class name is AdminUser), with an unknown sink point. And  CodeQL needs to save the call path in the form of a string

**Comment by smowton** [comment]
Can you elaborate on the sink? Constructing a data-flow path from source to validate is easy using the CodeQL dataflow library, but simply declaring any point in the whole program an interesting sink node would likely lead to many thousands of paths. Perhaps you could restrict the sinks to arguments to method calls, or to particular method calls?

The path you get out won't directly be a single string, but by exporting the result as SARIF you'll get a JSON description of the steps along the path. I would recommend then using a post-processing script to summarise that path as suits your needs.

**Comment by whyaicn** [comment]
Thank you very much for your help. In my task, I don't have any specified sinks. I plan to obtain a data flow path from the source points described above and pass through the method I used to mention, and the more paths obtained, the better. Thank you again for your response

**Comment by smowton** [comment]
I would strongly recommend at least restricting sinks to e.g. arguments to other (non-validate) methods, otherwise you'll get a path returned for every single local variable that ever holds something that has been validated.

With that caveat, you might use a stateful-data-flow configuration like:

```ql
private module ExampleConfig implements DataFlow::StateConfigSig {
  private newtype TValidationState =
    MkNotValidated() or
    MkValidated()

  private class ValidationState extends TValidationState {
    string toString() {
      this = MkNotValidated() and result = "not validated"
      or
      this = MkValidated() and result = "validated"
    }
  }

  class FlowState = ValidationState;

  predicate isSource(DataFlow::Node source, FlowState state) {
    source.asExpr() =
      any(MethodCall c | c.getCallee().hasQualifiedName("mypkg", "SomeClass", "source")) and
    state = MkNotValidated()
  }

  predicate isAdditionalFlowStep(
    DataFlow::Node node1, FlowState state1, DataFlow::Node node2, FlowState state2
  ) {
    state1 = MkNotValidated() and
    state2 = MkValidated() and
    node2.asExpr() =
      any(MethodCall c |
        c.getCallee().hasQualifiedName("mypkg", "ValidatorClass", "validate") and
        node1.asExpr() = c.getArgument(0)
      )
  }

  predicate isSink(DataFlow::Node node, FlowState state) {
    state = MkValidated() and node.asExpr() = any(MethodCall c).getAnArgument()
  }
}
```

**Comment by whyaicn** [comment]
Thank you a lot for solving this problem which is helpful to me.  I really appreciate you.And I still have a problem with exporting results to a JSON file.  Many blogs on the internet just explain how to export some methods such as source and sink. But it's not enough to me. I hope I can get all methods along a call path and export them to a JSON file. I'm very sorry to take up your valuable time once again.

**Comment by smowton** [comment]
Are you using the CodeQL CLI? If so, the command `codeql database analyze` with the option `--format=sarif-latest` is probably the best way to get the path information exported in a machine-readable form.

**Comment by whyaicn** [comment]
Yes, I use the CodeQL CLI. It's my fault. I didn't describe my problem clearly. I mean how to write a query to get all the methods along a call path. For example, I used to use this query to generate the result: 
```
from Flow::PathNode source, Flow::PathNode sink
 where Flow::flowPath(source, sink)
 select sink.getNode(), source, sink, "<message>"
```
But this query just returns me the source and the sink. And I want to get all the methods between them. How should I write a query?

**Comment by smowton** [comment]
Use `codeql database analyze --format=sarif-latest` to export the results of a `@kind path-problem` query such as that shown above and you should find that the sarif file contains not just the start and end points, but also the path between the two.

**Comment by whyaicn** [comment]
Thank you so much, my friend. This is my first time trying to ask a question on GitHub, and you have accurately solved my problem. Once again, I would like to express my gratitude to you
