### ISSUE TITLE
Java: control-flow dependency query

### ISSUE THREAD

**Issue by whyaicn** [github/codeql#17572]
I used a query in this [issue](https://github.com/github/codeql/issues/17544) with some adjustments in isSource and isSink. The following query is mine:
```
/**
 * This is an automatically generated file
 * @name Hello world
 * @kind path-problem
 * @problem.severity warning
 * @id java/example/hello-world
 */

 import java
 import semmle.code.java.dataflow.DataFlow
 import semmle.code.java.dataflow.FlowSources
 import codeql.dataflow.DataFlow

 // For some languages (Java/C++/Python/Swift) you need to explicitly import the data flow library, such as
 // import semmle.code.java.dataflow.DataFlow or import codeql.swift.dataflow.DataFlow
 private module MyConfig implements DataFlow::StateConfigSig {
    private newtype TValidationState =
      MkNotValidated() or
      MkValidated()
  
    private class ValidationState extends TValidationState {
      string toString() {
        this = MkNotValidated() and result = "not validated"
        or
        this = MkValidated() and result = "validated"
      }
    }
  
    class FlowState = ValidationState;
  
    predicate isSource(DataFlow::Node source, FlowState state) {
      exists(source) and
      state = MkNotValidated()
    }
  
    predicate isAdditionalFlowStep(
      DataFlow::Node node1, FlowState state1, DataFlow::Node node2, FlowState state2
    ) {
      state1 = MkNotValidated() and
      state2 = MkValidated() and
      node2.asExpr() =
        any(MethodCall c |
          c.getCallee().hasQualifiedName("com.example.app", "UserAuthentication", "authenticateUser") 
        and node1.asExpr() = c.getArgument(0)) 
    }

    predicate isSink(DataFlow::Node sink, FlowState state) {
      exists(sink) and state = MkValidated()
    } 
  }

 private module Flow = DataFlow::GlobalWithState<MyConfig>;
 import Flow::PathGraph

 from Flow::PathNode source, Flow::PathNode sink
 where Flow::flowPath(source, sink)
 select sink.getNode(), source, sink, "<message>"
```
I tried obtaining a call path that includes my project's "authenticateUser" method. There is a call path satisfies my goal which is Main.main()->UserRegistration.getEmail()->UserAuthentication.authenticateUser(). But there is no result returned from my query. Is this a logical issue with the query, or other reasons?
The code snippets in my project are the following:
```
package com.example.app;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        UserRegistration registration = new UserRegistration();
        registration.registerUser();
        
        String registeredEmail = registration.getEmail();
        
        if (registeredEmail != null) {
            UserAuthentication authentication = new UserAuthentication();
            authentication.authenticateUser(registeredEmail);
            
            OrderCalculator calculator = new OrderCalculator();
            calculator.calculateOrder();
        } else {
            System.out.println("Registration failed. Exiting program.");
        }
    }
}
```
```
package com.example.app;

import java.util.Scanner;

public class OrderCalculator {
    public void calculateOrder() {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("==== Order Calculation ====");
        System.out.println("Enter the price of the item: ");
        double price = Double.parseDouble(getUserInput(scanner));
        
        System.out.println("Enter the quantity: ");
        int quantity = Integer.parseInt(getUserInput(scanner));
        
        double totalCost = calculateTotalCost(price, quantity);
        displayOrderSummary(price, quantity, totalCost);
    }

    private String getUserInput(Scanner scanner) {
        return scanner.nextLine();
    }

    private double calculateTotalCost(double price, int quantity) {
        return price * quantity;
    }

    private void displayOrderSummary(double price, int quantity, double totalCost) {
        System.out.println("Order Summary:");
        System.out.println("Price per item: $" + price);
        System.out.println("Quantity: " + quantity);
        System.out.println("Total Cost: $" + totalCost);
    }
}
```
```
package com.example.app;

import java.util.Scanner;

public class UserAuthentication {
    public void authenticateUser(String email) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("==== User Login ====");
        System.out.println("Enter your username: ");
        String username = getUserInput(scanner);

        System.out.println("Enter your password: ");
        String password = getUserInput(scanner);

        if (validateInput(username) && validateInput(password)) {
            if (email != null && email.equals(username)) {
                System.out.println("User authenticated successfully with email: " + email);
            } else {
                System.out.println("Authentication failed. Incorrect email.");
            }
        } else {
            System.out.println("Invalid input detected!");
        }
    }

    private String getUserInput(Scanner scanner) {
        return scanner.nextLine();
    }

    private boolean validateInput(String input) {
        return input != null && !input.isEmpty();
    }
}
```
```
package com.example.app;

import java.util.Scanner;

public class UserRegistration {
    private String firstName;
    private String lastName;
    private String email;

    public void registerUser() {
        Scanner scanner = new Scanner(System.in);

        System.out.println("==== User Registration ====");
        System.out.println("Enter your first name: ");
        firstName = getUserInput(scanner);
        
        System.out.println("Enter your last name: ");
        lastName = getUserInput(scanner);
        
        System.out.println("Enter your email: ");
        email = getUserInput(scanner);

        if (validateEmail(email)) {
            System.out.println("User registered successfully:");
            System.out.println("Name: " + firstName + " " + lastName);
            System.out.println("Email: " + email);
        } else {
            System.out.println("Invalid email format. Registration failed.");
        }
    }

    public String getEmail() {
        return email;
    }

    private String getUserInput(Scanner scanner) {
        return scanner.nextLine();
    }

    private boolean validateEmail(String email) {
        return email.contains("@") && email.contains(".");
    }
}
```

**Comment by smowton** [comment]
I think now I've seen the code, this is probably not a data-flow question. The data-flow configuration specified says, "track flow from anything at all, via the argument -> return value of an `authenticateUser` call, to anything at all". However since `authenticateUser` is void typed, that argument -> return value step cannot happen.

That suggests any logic relating to when `authenticateUser` is called is going to be a control-flow problem, not a data-flow problem. It'll look something like, `authenticateUser` should always be called before XYZ operation is performed.

Could you say what property of the source program given here you want to identify, then I could probably give some more specific advice?

**Comment by whyaicn** [comment]
Thank you for your help. Well, I'd like to find a call path that includes a specified method related to validation in order to figure out if there is a logical vulnerability in this path. For example, the authenticateUser is a method to validate the user's authentication. And I hope to get a complete path from source to sink which passes authenticateUser to figure out whether there is a logical vulnerability in this path.

**Comment by smowton** [comment]
Could you give a code example, say an example of a problem, vs. a corresponding example when the problem is fixed, and say what's right or wrong about them?

**Comment by whyaicn** [comment]
Of course. This is a vulnerability of authentication bypass caused by the modified UserAuthentication method. The source code is the UserAuthentication method mentioned earlier. And the modified code is following:
```
package com.example.app;

import java.util.Scanner;

public class UserAuthentication {
    public void authenticateUser(String email) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("==== User Login ====");
        System.out.println("Enter your username: ");
        String username = getUserInput(scanner);

        System.out.println("Enter your password: ");
        String password = getUserInput(scanner);

        if (validateInput(username) && validateInput(password)) {
            // **Vulnerability: Directly allowing the use of specific usernames to bypass authentication**
            if (username.equals("admin") && password.equals("password123")) {
                System.out.println("Admin access granted without email verification!");
                return; 
            }

            if (email != null && email.equals(username)) {
                System.out.println("User authenticated successfully with email: " + email);
            } else {
                System.out.println("Authentication failed. Incorrect email.");
            }
        } else {
            System.out.println("Invalid input detected!");
        }
    }

    private String getUserInput(Scanner scanner) {
        return scanner.nextLine();
    }

    private boolean validateInput(String input) {
        return input != null && !input.isEmpty();
    }
}
```

And the other type of vulnerability is authentication missing which is caused by modified OrderCalculator. The source code is the OrderCalculator method mentioned earlier. And the modified code is following:
package com.example.app;

import java.util.Scanner;

public class OrderCalculator {
    private boolean isAuthenticated = false; // **New field added to indicate whether the user has been authenticated**

    public void calculateOrder() {
        // **There is no authentication check here, allowing all users to access the order calculation function**
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("==== Order Calculation ====");
        System.out.println("Enter the price of the item: ");
        double price = Double.parseDouble(getUserInput(scanner));
        
        System.out.println("Enter the quantity: ");
        int quantity = Integer.parseInt(getUserInput(scanner));
        
        double totalCost = calculateTotalCost(price, quantity);
        displayOrderSummary(price, quantity, totalCost);
    }

    private String getUserInput(Scanner scanner) {
        return scanner.nextLine();
    }

    private double calculateTotalCost(double price, int quantity) {
        return price * quantity;
    }

    private void displayOrderSummary(double price, int quantity, double totalCost) {
        System.out.println("Order Summary:");
        System.out.println("Price per item: $" + price);
        System.out.println("Quantity: " + quantity);
        System.out.println("Total Cost: $" + totalCost);
    }

    // **New method for setting user authentication status**
    public void setAuthenticated(boolean authenticated) {
        isAuthenticated = authenticated;
    }
}

**Comment by whyaicn** [comment]
**Since I am testing a tool's performance detecting logical vulnerabilities, I want to obtain many context-aware call paths. Can a CodeQL query framework be adapted to scan different projects by modifying a few parameters to retrieve these call paths? Or does CodeQL require writing project-specific queries each time? Thank you for your help**

**Comment by smowton** [comment]
Both of these cases would be quite custom queries, since they embody rules that are particular to your project.

In both cases this is not a data-flow but a control-flow question -- we're looking for execution paths, not data-flow paths, that break certain rules.

Case 1: the broken `authenticateUser` method. It seems your rule is that any successful return path should check the `email` parameter. This could be checked by looking for a condition like

```ql
from Method m, Parameter p, ReturnStmt rs
where m.hasQualifiedName("com.example.app", "UserAuthentication", "authenticateUser")
and rs.getEnclosingCallable() = m
and p = m.getAParameter()
and p.getName() = "email"
and not p.getAnAccess().getControlFlowNode().getBasicBlock().bbDominates(rs.getControlFlowNode())
select "Suspect return statement $@", rs, rs.toString()
```

Note that the check for "is the return statement dominated by a variable access?" could be improved:

* we might consider the case where there's more than one use of `email` that covers a return statement, so neither case dominates it (e.g., `checkStrict ? checkEmailStrict(email) : checkEmailLax(email)`)
* we should consider the case where the use is in the same basic block as the return statement (see https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/security/Validation.qll for example which considers such a case)
* for a void-typed method, we should also consider an implicit return -- that is, a control-flow node with no successor which isn't a throw statement or a non-exiting method like `System.exit`

However I hope this gives a useful starting point.

Case 2: the `calculateOrder` method that lacks an authenticate call. Presumably you have some idea what the entry-points are for request control flow, that should be able to reach a call to `authenticateUser`. For the simple missing-call case it's enough to use

```ql
from Method entryPoint
// Replace me with a better way to identify entry points
where
  entryPoint.hasQualifiedName("com.example.app", "OrderCalculator", "calculateOrder") and
  not entryPoint
      .polyCalls+(any(Method m |
          m.hasQualifiedName("com.example.app", "UserAuthentication", "authenticateUser")
        ))
select entryPoint, "Suspicious entry point"
```

However I expect in practice you would look for patterns where an auth call is present, but similar to case 1 does not dominate something that it ought to -- probably another method call that does something privileged, that ought to have a preceding auth check.

**Comment by whyaicn** [comment]
Thank you for your help.  You help me a lot at this time. Maybe I need to learn more things about codeql.
