### ISSUE TITLE
CodeQL Documentation index.html: CodeQL coverage of CWEs link pointing to wrong link

### ISSUE THREAD

**Issue by aikenka** [github/codeql#17723]
**CodeQL Documentation index.html has incorrect link for "CodeQL coverage of CWEs"**

- https://codeql.github.com/docs/
- https://github.com/github/codeql/blob/main/docs/codeql/index.html - line 104 - link for CodeQL coverage of CWEs is pointing to Supported Languages and Frameworks page, rather than one detailing CWE coverage.

```
                        <a href="codeql-overview/supported-languages-and-frameworks/">
                            <div class="Subhead-heading f4 text-center">CodeQL coverage of CWEs</div>
                        </a>

```

![image](https://github.com/user-attachments/assets/fe913a9c-3a8a-44e0-996b-c094b3a1cf30)

Take care,
Karen

**Comment by redsun82** [comment]
👋 @aikenka thank you so much for spotting this and letting us know! https://github.com/github/codeql/pull/17725 should take care of this.
