### ISSUE TITLE
Please clarify Use Rights in license

### ISSUE THREAD

**Issue by jkugler** [github/codeql#17721]
In this file: https://github.com/github/codeql-cli-binaries/blob/main/LICENSE.md it says:

> Use Rights; Scope of License
> The Software is licensed on a per user basis. Here's what you may do with the Software, but subject to License Restrictions provisions below:
> * Use the Software to perform academic research.
> * Use the Software to demonstrate the Software.
> * Test CodeQL queries that are released under an OSI-approved Licence to confirm that new versions of those queries continue to find the right vulnerabilities.

What qualifies as demonstration? Is a company allowed to run CodeQL against their non-opensource software to determine if this will be a useful tool? Or must they purchase licenses before they know whether or not the tool will provide them any value?

**Comment by redsun82** [comment]
:wave: @jkugler: apologies for the late reply, it took some time for me to circle back on this one.

CodeQL can be trialed directly on public repositories. For private repositories we recommend reaching out to the GitHub [sales team](https://github.com/enterprise/advanced-security) and they can guide you through the trial process.

**Comment by rvermeulen** [comment]
Hi @jkugler,

Does @redsun82's answer provide you with enough information on how to use CodeQL to demonstrate its capabilities?

**Comment by jkugler** [comment]
@rvermeulen Mostly. It just seems very high friction for a developer who wants to try it out and see if it would provide any value.
