### ISSUE TITLE
The attribute name of the vue file contains dots. As a result, the attribute cannot be parsed

### ISSUE THREAD

**Issue by keysenYang** [github/codeql#17834]
In the vue file, if the attribute name of a component contains dots, all attributes of the component cannot be parsed. For example, in the following code, the component cannot parse HTML::Attribute because the sendBoxVisibility.sync attribute contains dots.

<SendDialog
v-if="sendBoxVisibility"
:sendBoxVisibility.sync="sendBoxVisibility"
:checkedCount="fullCheckedCount"
:isEmail="isEmail"
:isFeedback="isFeedback"
@sendNotification="sendNotification"
/ >

**Comment by hvitved** [comment]
@github/codeql-javascript : I think this one is for you?

**Comment by keysenYang** [comment]
> @github/codeql-javascript : I think this one is for you?

Yes, it's a problem of codeql for javascrpt

**Comment by asgerf** [comment]
Opened a PR that should fix the issue https://github.com/github/codeql/pull/17864

**Comment by asgerf** [comment]
@keysenYang Thanks for reporting this. I'm closing the issue as the fix has been merged, but feel free to re-open if you notice further issues.

Note that it will take some time to for the fix to make it into a release. The next release is estimated to be out November 8.
