### ISSUE TITLE
GitHub CodeQL extractor seems incompatible with hosted runner

### ISSUE THREAD

**Issue by jsoref** [github/codeql#17945]
**Description of the issue**

I just pushed a random commit to my codeql-action fork, and the https://github.com/check-spelling-sandbox/github-codeql-action/actions/runs/11748775946/workflow failed https://github.com/check-spelling-sandbox/github-codeql-action/actions/runs/11748775946/job/32733592636

Current runner version: '2.320.0'
Operating System
*  Ubuntu
*  22.04.5
*  LTS

Runner Image
*  Image: ubuntu-22.04
*  Version: 20241103.1.0
*  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20241103.1/images/ubuntu/Ubuntu2204-Readme.md
   *  CodeQL Action Bundle 2.19.2 #17808
*  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20241103.1

```
/opt/hostedtoolcache/CodeQL/0.0.0-20241108/x64/codeql/swift/tools/linux64/extractor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /opt/hostedtoolcache/CodeQL/0.0.0-20241108/x64/codeql/swift/tools/linux64/extractor)
/opt/hostedtoolcache/CodeQL/0.0.0-20241108/x64/codeql/swift/tools/linux64/extractor: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /opt/hostedtoolcache/CodeQL/0.0.0-20241108/x64/codeql/swift/tools/linux64/extractor)
/opt/hostedtoolcache/CodeQL/0.0.0-20241108/x64/codeql/swift/tools/linux64/extractor: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /opt/hostedtoolcache/CodeQL/0.0.0-20241108/x64/codeql/swift/tools/linux64/extractor)
```

**Comment by jsoref** [comment]
A previous build succeeded: https://github.com/check-spelling-sandbox/github-codeql-action/actions/runs/11697919997/job/32577384551
It was using CodeQL Action Bundle 2.19.1

So this _feels_ like a regression from the release...

**Comment by jketema** [comment]
We no longer support Swift on Linux. https://github.com/github/codeql-action/pull/2588 is probably relevant here.

**Comment by jsoref** [comment]
If it isn't supported, the binaries should be removed instead of leaving things that will just crash when run. Slightly preferably would be something which just does the equivalent of:

```sh
echo 'codeql no longer supports Swift on Linux see ...' >&2
exit 1
```

**Comment by jketema** [comment]
Thanks for the suggestion. We'll take this in consideration. Closing this as completed, as the situation seems to have been clarified.
