### ISSUE TITLE
Unable to process Kotlin code after switching to Gradle 8.11 with `org.gradle.configuration-cache.parallel = true`

### ISSUE THREAD

**Issue by sschuberth** [github/codeql#17962]
It seems that after upgrading our Kotlin/JVM project to Gradle 8.11 and enabling the new `org.gradle.configuration-cache.parallel = true`, we [getting](https://github.com/oss-review-toolkit/ort/actions/runs/11786246853/job/32829225271#step:6:62)

```
/opt/hostedtoolcache/CodeQL/2.19.3/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=14576 /home/runner/work/_temp/codeql_databases/java
  CodeQL detected code written in Java/Kotlin but could not process any of it. For more information, review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build .
  Error: Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.19.3/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=14576 /home/runner/work/_temp/codeql_databases/java". Exit code was 32 and last log line was: CodeQL detected code written in Java/Kotlin but could not process any of it. For more information, review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build . See the logs for more details.
```

Can it be that parallelizing configuration cache access has an impact on CodeQL analysis?

**Comment by sschuberth** [comment]
> use `--no-daemon` to disable the Gradle daemon

We're already [doing that](https://github.com/oss-review-toolkit/ort/actions/runs/11786246853/workflow#L12), but I'll give the `--no-build-cache` a try on top.

> CodeQL extraction works by observing `kotlinc` invocations

As a side note, isn't that approach a bit fragile? Should maybe the Gradle tooling API be used instead?

**Comment by smowton** [comment]
I should clarify, we can also see in-process invocations of the Kotlin compiler, not just literal usage of the `kotlinc` binary, if that's what you mean?

**Comment by sschuberth** [comment]
> not just literal usage of the `kotlinc` binary

That makes things better, I guess, but I'm still wondering whether CodeQL shouldn't rather hook into Gradle, so that it somehow could also get compiled code from caches instead of always requiring full builds (that's my understanding now how it works).

**Comment by smowton** [comment]
I note the linked commit seems to feature a successful CodeQL analysis, so I'll close this.

**Comment by sschuberth** [comment]
> I note the linked commit seems to feature a successful CodeQL analysis, so I'll close this.

Yes, sorry for forgetting to report back.
