### ISSUE TITLE
False positive - Websites must specify the HttpOnly attribute on sensitive cookies

### ISSUE THREAD

**Issue by markwallace-microsoft** [github/codeql#18119]
**Description of the false positive**

We got 5000 "Websites must specify the HttpOnly attribute on sensitive cookies" errors reported in our repo against C# code.

Here is an example:

[dotnet/samples/Concepts/Agents/ChatCompletion_FunctionTermination.dotnet/samplescs:135
](https://github.com/microsoft/semantic-kernel/blob/370c89a836145fbee6c239179f8d22471b71339f/dotnet/samples/Concepts/Agents/ChatCompletion_FunctionTermination.cs#L135-L135)

```csharp
        // Local function to invoke agent and display the conversation messages.
        async Task InvokeAgentAsync(string input)
        {
            ChatMessageContent message = new(AuthorRole.User, input);
HttpOnly attribute is missing or not set to true on the Http Cookie
CodeQL
            chat.Add(message);
            this.WriteAgentChatMessage(message);
```

https://github.com/microsoft/semantic-kernel/security/code-scanning/195

**Comment by LittleLittleCloud** [comment]
We also got 3000+  "Websites must specify the HttpOnly attribute on sensitive cookies" errors reported in our repo against C# code

- https://github.com/microsoft/autogen/security/code-scanning/5423

**Comment by redsun82** [comment]
:wave: @markwallace-microsoft, @LittleLittleCloud 

I can't find traces of such queries in the standard CodeQL bundle. Aren't these queries maybe part of a Microsoft-only query pack?

**Comment by Evangelink** [comment]
+1 on testfx, it's being raised on `StringBuilder`, `List` creation and much more but none of the isntances are web related.

**Comment by markwallace-microsoft** [comment]
Hi @redsun82 thank you fr the response. The problem is resolved now, I'll follow up internally. @LittleLittleCloud @Evangelink I'll let you know what I find out.
