### ISSUE TITLE
Kotlin version 2.0.20 is too recent. CodeQL currently supports versions below 2.0.10

### ISSUE THREAD

**Issue by rseeton** [github/codeql#18381]
CodeQL running in a Enterprise installation is reporting a Kotlin version issue.  

During the CodeQL Init action:

> Successfully loaded extractor Java/Kotlin (java) from /__w/_tool/CodeQL/2.17.6/x64/codeql/java.
> Created skeleton CodeQL database at /__w/_temp/codeql_databases/java. This in-progress database is ready to be populated by an extractor.

During the Gradle Build execution:

> Task :build-settings-logic:processResources
> e: com.semmle.extractor.java.interceptors.KotlinInterceptor$KotlinVersionTooRecentError: Kotlin version 2.0.20 is too recent. CodeQL currently supports versions below 2.0.10
> 	at com.semmle.extractor.java.interceptors.KotlinInterceptor.getExtractorJarPath(KotlinInterceptor.java:213)
> 
> 	at com.semmle.extractor.java.interceptors.KotlinInterceptor.beforeKotlinExecute(KotlinInterceptor.java:539)
> Task :build-settings-logic:compileKotlin FAILED

This leads to a workflow failure.

**Comment by smowton** [comment]
You will need to update your CodeQL version to at least 2.19.1 to gain Kotlin 2.1.0+ support. Are you familiar with how to update CodeQL for GHES?

**Comment by rseeton** [comment]
@smowton - Thanks for the follow-up. 

Our admins follow-edu p and established that this occurred because during Github upgrade to 3.14 ,it set the default codeql bundle version to 2.17.6 https://docs.github.com/en/enterprise-server@3.14/admin/release-notes#code-scanning

They have manually synced the codeql-action now & performed a test .It is updated to codeql bundle version "2.20.0" and our issue has been resolved.
