### ISSUE TITLE
POM XML Files not included in java db dump

### ISSUE THREAD

**Issue by JLLeitschuh** [github/codeql#2377]
**Description of the issue**

I just pulled the database for a project that should have `pom.xml` files included in the dump but when you look at the files that LGMT has collected, it doesn't include the `pom.xml` files.

https://lgtm.com/projects/g/apache/isis/latest/files

The following query returns nothing:
```ql
import java
import semmle.code.xml.MavenPom

from XMLElement xml
select xml
```

**Comment by JLLeitschuh** [comment]
Hey, @aschackmull that's unfortunate.

I was hoping to write a query for the security BB that involved the XML files.
Would an XML query still be eligible for the BB even though those files aren't pulled in by default?

**Comment by yo-h** [comment]
We're considering enabling extraction of `pom.xml` files by default in the near future (likely next month).

**Comment by JLLeitschuh** [comment]
Is there a way that I can create a DB using the `codeql` CLI that will have it create a DB with an XML file inside it?

**Comment by hmakholm** [comment]
Unfortunately the new CodeQL CLI cannot extract _any_ XML to the databases it creates yet. We really wanted to have that feature in last week's version, but it got sacrificed to the gods of release-on-time. If everything goes well, an updated release that can do it ought to arrive within a few weeks.

**Comment by JLLeitschuh** [comment]
@hmakholm I managed to get a DB with my XML just using the LGTM site. See #2413

**Comment by yo-h** [comment]
LGTM Java analysis now extracts `pom.xml` files by default. See for example: https://lgtm.com/projects/g/apache/isis/latest/files/pom.xml?sort=name&dir=ASC&mode=heatmap
