### ISSUE TITLE
LGTM.com - false positive for default __bool__ behaviour

### ISSUE THREAD

**Issue by maxfischer2781** [github/codeql#2388]
**Description of the false positive**

LGTM reports a method ``__bool__(self) -> raise TypeError`` as unneeded, and claims this is the default behaviour. However, by default all objects inherit ``object.__bool__(self) -> return True``.

```python3
>>> bool(object())
True
>>> class Foo: ...
...
>>> bool(Foo())
True
```

Unlike for example ``__hash__``, ``__bool__`` cannot be disabled by setting it to ``None``. Types with ambiguous boolean meaning *must* override ``__bool__`` and raise an error. Examples include [``numpy`` series](https://stackoverflow.com/a/44345755/5349916).

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/MaineKuehn/classad/snapshot/9014ed88450a1241c1aee0f8f2f675140904a84e/files/classad/_primitives.py?sort=name&dir=ASC&mode=heatmap#x464e562b08f7ae5a:1

**Comment by yoff** [comment]
This has been fixed in https://github.com/github/codeql/pull/3460. The fix will be live on [LGTM.com](https://LGTM.com) within a few weeks.
