### ISSUE TITLE
Fancy scroll to anchor feature doesn't scroll to correct place.

### ISSUE THREAD

**Issue by greggman** [github/codeql#2424]
**Description of the issue**

Fancy "scroll to anchor" feature doesn't take you to the correct place in neither Chrome nor Safari. (and is off in Firefox)

![ScreenFlow](https://user-images.githubusercontent.com/234804/69477085-54f2d280-0e25-11ea-9841-54c7f12b3022.gif)

https://lgtm.com/help/lgtm/exploring-project-alerts#what-if-i-see-a-false-positive

**Comment by jbj** [comment]
@alexrford, are you the right person to address this? I have similar issues in Firefox when clicking links that take me into a source file, with "scroll to anchor" either not working at all or scrolling just past the intended location. But sometimes it works.

**Comment by jketema** [comment]
Hi @greggman. Thanks for your interest in LGTM.  I'm closing this issue, as LGTM has been shutdown. Please see the [blog post on LGTM's deprecation](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) for further details. More details on LGTM's replacement - Code Scanning - can be found in the [GitHub Docs for this feature](https://docs.github.com/en/code-security/code-scanning).
