### ISSUE TITLE
LGTM.com - false positive (Java, Generics)

### ISSUE THREAD

**Issue by HenryLoenwind** [github/codeql#2441]
I'm not quite sure how one would formulate an exception to this rule (the rule itself is sound), but anyway:

Java is quite restrictive when casting with generics, especially when they are not at the top level. Here my return type is fixed to `List<List<ItemStack>>` by a third-party API that value is fed to eventually. I can declare my method and variable as `NNList<List<ItemStack>>` instead and implicitly cast. I cannot use `NNList<NNList<ItemStack>>` nor explicitly cast that.

Or in other words: When building nested data structures you instantly lose access to the real types because you must create them using the abstract types of the declaration. If you don't assemble them using preexisting parts, but have to fill them, that's an issue.

Maybe limiting the check to values that come from parameters and fields would be a solution?

https://lgtm.com/projects/g/SleepyTrousers/EnderIO/snapshot/e76a8b98d9f06521ed4b6712e66e5c82c7b6ce01/files/enderio-base/build/sources/main/java/crazypants/enderio/base/recipe/Recipe.java?sort=name&dir=ASC&mode=heatmap#xfcd935276dab086:1 (ignore the second one, that's an unnecessary cast)

PS: No, that code isn't pretty. I know. Volunteer to rewrite the underlying data structures? Those []s should have been evicted years ago... ;) ;)

**Comment by hmakholm** [comment]
[I won't express any opinion on the alert at this time, but I think the code could become _slightly_ prettier if you work on a `NNList<NNList<ItemStack>>` while constructing the structure and then unsafe-cast it to `List<List<ItemStack>>` when you're ready to return it. To keep the Java type checker from rioting, that final cast would have to go through an intermediate variable with an even-less-precise type such as `Object` or a raw `List`, so it would probably end up _more verbose_ -- but isolating it to a single step in the algorithm would still arguably make it a _conceptual_ win.]

**Comment by hmakholm** [comment]
[Or alternatively use `Collections.unmodifiableList()` to convert from `NNList<NNList<ItemStack>>` to `List<List<ItemStack>>` when returning it, at a tiny performance cost.]

**Comment by HenryLoenwind** [comment]
Ideally the recipe and inputs would use Lists instead of Arrays, then I wouldn't need to cast at all and could use List.addAll(Collection). This code is in the user-interactive path, so trying to avoid extra time spent on copying stuff ... actually isn't needed when compared to the rest of the code that is fps-bound. ;)

**Comment by aschackmull** [comment]
Maybe I'm missing something here, but why can't you just remove those casts?  I.e. `addAll` also exists on `List`, so changing `((NNList<ItemStack>) res.get(slotNumber)).addAll(equivelentInputs);` to `res.get(slotNumber).addAll(equivelentInputs);` ought to work just fine, right?

**Comment by HenryLoenwind** [comment]
That's not List.addAll(Collection<X>), that's NNList.addAll(X[]).

**Comment by aschackmull** [comment]
Ah, right, my mistake.  In that case I'll just echo the suggestions by hmakholm.
