### ISSUE TITLE
LGTM.com - false positive - py/import-own-module

### ISSUE THREAD

**Issue by mjpieters** [github/codeql#2475]
**Description of the false positive**

I see a lot of `py/import-own-module` false positives, where the analyzer is equating top-level imports with local (package-namespaced) modules, which simply are not the same, or confuses nested packages with the top-level name or misses that the module could have been running as the `__main__` script module.

E.g. in the [`sphinxcontrib.asyncio` module](https://github.com/aio-libs/sphinxcontrib-asyncio/blob/1e0e9139b6dda8036f223fd0ddd358a76de4be7a/sphinxcontrib/asyncio.py#L6) there is an import from the top-level `asyncio` standard library module:

    from asyncio import iscoroutinefunction

This is a false positive because in Python 3, `import asyncio` will only consider top-level names, not namespaced modules. To import itself you'd have to use `from . import asyncio` or `from sphinxcontrib import asyncio` or import `sphinxcontrib.asyncio`

* [LGTM project page for the alert](https://lgtm.com/projects/g/aio-libs/sphinxcontrib-asyncio/snapshot/fcae58065e8b4c05a9997e7eea6c766468f445f7/files/sphinxcontrib/asyncio.py?sort=name&dir=ASC&mode=heatmap#xd4200df71b7ae4fc:1)

The alert also triggers if a module doubles as a `__main__` script. When run from the command line, *any module* can be used as a script instead, at which point they are imported as the `__main__` module. You then *may* have to import the module itself, so `import own_name`, but from within a `if __name__ == '__main__':` guard.

## further examples

In the Flask project:

* [namespaced module `cliapp.inner1.inner2.flask` imports the top-level name `flask`](https://lgtm.com/projects/g/pallets/flask/snapshot/32689db6cd01618eb8451d2c230ff312465b0317/files/tests/test_apps/cliapp/inner1/inner2/flask.py?sort=name&dir=ASC&mode=heatmap#xbdbcb88cebc8a8b:1)

In the Python project itself:

* [`os` imports `os.path`, a nested module](https://lgtm.com/projects/g/python/cpython/snapshot/2ae31865f3e941aa2eab21073325f03c95cacd8c/files/Lib/os.py?sort=name&dir=ASC&mode=heatmap#xb948f3670cfc2295:1) (note the `sys.modules['os.path'] = path` on the preceding line)
* [`difflib` run as `__main__` imports `difflib`](https://lgtm.com/projects/g/python/cpython/snapshot/2ae31865f3e941aa2eab21073325f03c95cacd8c/files/Lib/difflib.py?sort=name&dir=ASC&mode=heatmap#x355db4b73d50b1ac:1), an example of the file-run-as-script.
* [`pdb` run as `__main__` imports `pdb`](https://lgtm.com/projects/g/python/cpython/snapshot/2ae31865f3e941aa2eab21073325f03c95cacd8c/files/Lib/pdb.py?sort=name&dir=ASC&mode=heatmap#x121b1e8b27c122ca:1), another `__main__` case.

**Comment by bryevdv** [comment]
Just noting we see these here as well:

https://lgtm.com/projects/g/bokeh/bokeh/snapshot/5499c7eade1b24444ba733e82d0d2779687252cd/files/bokeh/_testing/plugins/bokeh.py?sort=name&dir=ASC&mode=heatmap#xaffd1881854d7600:1

Going to rename the module to work around but agree with @mjpieters that that should not be necessary

**Comment by bryevdv** [comment]
~60 of these suggestions just appeared overnight, and they are completely spurious. Unlike the previous one, the new ones are just completely, flat-out wrong. There is not even a plausible explanation I can think of for a mixup. Here is one example:

https://lgtm.com/projects/g/bokeh/bokeh/snapshot/30a8133c235cf21466d479996a88c4c9324b5b2c/files/bokeh/core/validation/__init__.py?sort=name&dir=ASC&mode=heatmap

The imported submodule only imports standard library, literally nothing else. No sibling or parent modules. Nothing anywhere there is "importing itself"

**Comment by tausbn** [comment]
The ones that appeared overnight were due to a bug we introduced recently (see issue #2771). This should hopefully be fixed, and the alerts should disappear within the next few weeks.
