### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by paul-ion** [github/codeql#2476]
**Description of the false positive**

The application has its own CSRF protection method. No need to use CSURF. In fact the existing protection is more reliable by automatically enforcing CSRF based on request path rather than order of routes definition (the existing CSURF method, which is error prone).

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/trendmicro/SecureCodingDojo/snapshot/4e37dfd83ddbd42a31e607d17c7d82d4bea8c29d/files/trainingportal/server.js#x81c9ebfede9f9abc:1

**Comment by max-schaefer** [comment]
Thank you for your report, @paul-ion, we very much appreciate it!

Could you tell us a bit more about how your application protects against CSRF? That way we may be able to improve our analysis to avoid falsely flagging it in future.

**Comment by paul-ion** [comment]
Sure thing. Right here you can see the CSRF protection being enforced on relevant pages:  https://github.com/trendmicro/SecureCodingDojo/blob/04375cc5bc34d75c73d1b43e27758cb1335f99b4/trainingportal/auth.js#L525

**Comment by max-schaefer** [comment]
Excellent, thanks! We'll look into teaching our analysis to take this into account.

**Comment by erik-krogh** [comment]
I fixed this issue in https://github.com/github/codeql/pull/4521. 

It will take a few weeks for the fix to appear on LGTM.com.
