### ISSUE TITLE
LGTM.com - false positive if custom printf-specifiers are used

### ISSUE THREAD

**Issue by tobiasbrunner** [github/codeql#2502]
**Description of the false positive**

If custom printf-specifiers are defined  (e.g. via [glibc's `register_printf_function`](https://www.gnu.org/software/libc/manual/html_node/Customizing-Printf.html)) that take multiple arguments, there could be type mismatches reported for arguments that are seemingly out of place. If only custom specifiers are used in a format string, nothing is reported, though, even if the number of arguments doesn't match the number of specifiers.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/strongswan/strongswan/snapshot/6bb67f7bc86440200fc4e847843b200f8fa8f714/files/src/libstrongswan/plugins/plugin_feature.c?sort=name&dir=ASC&mode=heatmap#x2cf8e992bcef6932:1

Note that nothing is reported for the statements between lines 303 and 415.

Another example (again, note that nothing is reported for the line right above this):

https://lgtm.com/projects/g/strongswan/strongswan/snapshot/6bb67f7bc86440200fc4e847843b200f8fa8f714/files/src/libstrongswan/credentials/certificates/certificate_printer.c?sort=name&dir=ASC&mode=heatmap#x735d254442893b94:1

**Comment by geoffw0** [comment]
Hi @tobiasbrunner,

Custom specifiers are beyond the scope of our `printf` format string analysis at present.  I'll look into putting in some kind of exception so that you don't get these incorrect alerts.

**Comment by tobiasbrunner** [comment]
> Custom specifiers are beyond the scope of our `printf` format string analysis at present.

Yeah, I figure it could be tricky to provide a fix for this.

> I'll look into putting in some kind of exception so that you don't get these incorrect alerts.

Thanks.

**Comment by geoffw0** [comment]
Its been a long time coming, but this issue should be fixed once a recent change (https://github.com/github/codeql/pull/4831) reaches LGTM.  Please allow a few weeks.

**Comment by tobiasbrunner** [comment]
Thanks. I think there might still be problematic cases e.g. when a custom printf-specifier requires two arguments (such as our `%N` specifier) and a known specifier follows it.
