### ISSUE TITLE
Error `NO_KIND_SPECIFIED`

### ISSUE THREAD

**Issue by prashast** [github/codeql#2508]
If I follow through with running analyses using codeql cli as given here:https://help.semmle.com/codeql/codeql-cli/procedures/analyze-codeql-database.html 

I end up with a similar error as reported here: https://github.com/Semmle/ql/issues/2486 if I run any of the queries located here https://github.com/Semmle/ql/tree/master/cpp/ql/examples/snippets The reason for this is a missing `@kind` parameter which is necessary when using `database analyze` subcommands. 

I can make a PR fixing this in the snippets if you let me know what is the appropriate @kind parameter to add to these snippets. Unless of course these snippets are not intended to be used with `database analyze`

**Comment by jbj** [comment]
https://github.com/github/codeql/issues/2486#issuecomment-564014596 and the discussion around it can hopefully answer your question about whether `database analyze` is the right subcommand for your use case. If it is, you likely want `@kind problem`, where your `select` satisfies its column format requirements: a source-code element in the first column and a string in the second. See https://codeql.github.com/docs/writing-codeql-queries/metadata-for-codeql-queries/ for more details on query metadata.
