### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by amarkevich** [github/codeql#2559]
**Description of the false positive**

Raw usage of HttpServletRequest.getRequestURL() reported as 

> Cross-site scripting vulnerability due to user-provided value.

HTTP Parameter Pollution occurs for query parameters according to [1].
[2] mentioned about this:

> it does not include query string parameters

1. https://www.owasp.org/index.php/Testing_for_Reflected_Cross_site_scripting_(OTG-INPVAL-001)#Example_7:_HTTP_Parameter_Pollution_.28HPP.29
2. https://jakarta.ee/specifications/servlet/4.0/apidocs/javax/servlet/http/HttpServletRequest.html#getRequestURL--

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/apache/cxf-fediz/snapshot/2876fbb262c5e60fcbd38d72bf4a59e504fab8d8/files/systests/webapps/springWebapp/src/main/java/org/apache/cxf/fediz/example/FederationServlet.java?sort=name&dir=ASC&mode=heatmap#x9fd8b03bf2c1a5a5:1

**Comment by aschackmull** [comment]
Although query parameters are not included in getRequestURL, user controlled parameters can still be included via the path parameters (see, for example, this for some of the subtleties involved: https://www.jtmelton.com/2011/02/02/beware-the-http-path-parameter/ ). So for example, a request url for `http://localhost:8080/index.html;<script>alert()</script>` will include the path parameter `<script>alert()</script>` which can still lead to XSS.
