### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by niuzhi** [github/codeql#2633]
Hello, may I ask if there is a person in charge of semmle in China? Our company is planning to purchase CodeQL and we cannot contact your after-sales.

**Comment by niroshan** [comment]
Hello @niuzhi I look after the codeQL go to market team. I will be happy to help you and connect you with the sales team in china.

my email address is niroshan@github.com if you can email me, I will be happy to help you.

**Comment by niuzhi** [comment]
Thank you very much for your help,my WeChat is cq123456lang，please contact me ,thinks 

发自我的iPhone

**Comment by niroshan** [comment]
@niuzhi I am on the wechat group now, so we can close this ticket.
