### ISSUE TITLE
LGTM.com - false positive - unused python locals with typehints incorrectly

### ISSUE THREAD

**Issue by ghost** [github/codeql#2652]
**Description of the false positive**

Adding a descriptive type-hint to an existing variable is treated as if it is redefining the variable, when it is not.

![image](https://user-images.githubusercontent.com/52883826/72685554-3df9f500-3ae3-11ea-9c6b-2d43cf0ca3db.png)

https://lgtm.com/projects/gl/nekokatt/hikari/snapshot/1a1a0346e6e0529199a5dd80a9bb8e42a761926f/files/hikari/orm/state/state_registry_impl.py#x4d28be86792861e0:1

Example:
```py
def do_something_with(foo: Eggs):
    ...

def do_something_else_with(foo: Spam):
    ...

foo = bar()  # `Value assigned to "foo" is never used' (yes it is!!!)

if baz:
    foo: Eggs
    do_something_with(foo)
else:
    foo: Spam
    do_something_else_with(foo)
```

**Comment by tausbn** [comment]
Thank you for the report!

I agree with your assessment that it looks like type annotations are treated as redefinitions, which is of course incorrect. I expect this may also affect our taint tracking and dataflow analyses, so this should definitely be addressed (though I can't give a time frame for this just now).
