### ISSUE TITLE
Unable to control which repos I see alerts for

### ISSUE THREAD

**Issue by ljharb** [github/codeql#2714]
My "My Alerts" page, for example, shows Microsoft/Typescript alerts, even though:
1. i don't maintain it or have write access
1. i don't have it starred on github
1. i don't have it followed on lgtm.com

How can I make sure I only see alerts for repos I have write access on (and ideally, be able to manually filter the list down from that)?

**Comment by jketema** [comment]
Hi @ljharb . Thanks for your interest in LGTM.  I'm closing this issue, as LGTM has been shutdown. Please see the [blog post on LGTM's deprecation](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) for further details. More details on LGTM's replacement - Code Scanning - can be found in the [GitHub Docs for this feature](https://docs.github.com/en/code-security/code-scanning).

**Comment by ljharb** [comment]
@jketema thanks. in the future, when i find similar false positives with CodeQL, where do i report them?

**Comment by jketema** [comment]
This repo is fine. We can always relay the issue if this in not quite the right place for it.

For specific problems with the CodeQL CLI or the CodeQL action, there's also https://github.com/github/codeql-cli-binaries and https://github.com/github/codeql-action.
