### ISSUE TITLE
LGTM.com - false positive - cpp/uncontrolled-allocation-size

### ISSUE THREAD

**Issue by tobiasbrunner** [github/codeql#2762]
**Description of the false positive**

The _cpp/uncontrolled-allocation-size_ query looks for upper-bound checks for values passed to an allocation function. Unfortunately, only very specific checks are considered, that is, the value must be on the left of a relational operator. So checks for an exact length have to be rewritten.

Consider the first example below. It has the "wrong" form to begin with. But if we rewrite the check so that the variable is on the left, it looked like this:

```c
if (read(fd, &name_len, 4) != 4 ||
    name_len != eventdata_len - 4 - algo_digest_len - 4)
{
    error = "invalid filename field length";
    break;
}
```
This should be fine (no danger of an overflow, in particular because the value is passed directly to `malloc()`, no computation involved).  However, the query doesn't accept it. Instead, we'd have to write it like this:

```c
if (read(fd, &name_len, 4) != 4 ||
    name_len < eventdata_len - 4 - algo_digest_len - 4 ||
    name_len > eventdata_len - 4 - algo_digest_len - 4)
{
    error = "invalid filename field length";
    break;
}
```

The second example linked below is similar. Instead of checking for the problematic value directly (1 is added to the length later and the check prevents an overflow):

```c
if (read(fd, &name_len, 4) != 4 || name_len == UINT32_MAX)
{
    error = "invalid filename field length";
    break;
}
```
We'd have to rewrite it to something like this to avoid the alert:

```c
if (read(fd, &name_len, 4) != 4 || name_len > UINT32_MAX-1)
{
    error = "invalid filename field length";
    break;
}
```

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/strongswan/strongswan/snapshot/850c8726e8059c7f6fb8cff5ab5ecc3949aa8499/files/src/libimcv/pts/pts_ima_event_list.c?sort=name&dir=ASC&mode=heatmap#x6adbe6b6984a6f4a:1

https://lgtm.com/projects/g/strongswan/strongswan/snapshot/850c8726e8059c7f6fb8cff5ab5ecc3949aa8499/files/src/libimcv/pts/pts_ima_event_list.c#x17a431613ac65d43:1

**Comment by jbj** [comment]
Thank you for the report. The problematic check is this one: https://github.com/Semmle/ql/blob/90f94e2e5404b0e578ac8735645c5b28e546379f/cpp/ql/src/semmle/code/cpp/security/TaintTrackingImpl.qll#L330-L340

I don't have any ideas that would remove these false positives without potentially creating many false negatives. @geoffw0 and @MathiasVP, do you have ideas for a fix we could apply in the near term?

**Comment by geoffw0** [comment]
We shouldn't be using `getLeftOperand()` here, `RelationalOperation` has a `getLesserOperand()` and `getGreaterOperand()` for this kind of thing.

That said, I don't think the above addresses the issue here.  I think we should consider excluding allocations that don't contain a multiply (whether explicitly, as in `malloc(size * 4)`, or implicitly, as in `new int[size]`, or indirectly, as in `size = size * 4; malloc(size)`).  This should solve the above issue and bring the query into line with how it's described in it's `qhelp` file.

**Comment by jbj** [comment]
I agree with your analysis, except that I don't expect there's a problem in `new int[size]` -- I expect the implicit multiplication to have an implicit overflow check on it. But I haven't actually checked what the standard says.

Making the query agree with its qhelp solves the first reported problem. I think we can solve the second reported problem with a simple syntactic match for now, expanding the check for `RelationalOperation` to include all `ComparisonOperation`s.

**Comment by geoffw0** [comment]
Note to self: there are currently two copies of `hasUpperBoundsCheck`, one in TaintTrackingImpl and one in DefaultTaintTracking.  We should probably apply any fixes to both.

**Comment by geoffw0** [comment]
I believe https://github.com/github/codeql/pull/3479 will finally resolve this issue.

**Comment by geoffw0** [comment]
Fixed by https://github.com/github/codeql/pull/3479.  Please allow a couple of weeks for the fix to reach LGTM.
