### ISSUE TITLE
LGTM.com - false positive - Python - unused variable in nested F string 

### ISSUE THREAD

**Issue by johnashu** [github/codeql#2885]
**Description of the false positive**

When using a variable that has been assigned inside an F-string nested inside another F-String, LGTM marks this as never used.

The specification states that they [support full Python *expressions*][1]* inside brackets. It's also stated that a formatted string literal *is really just an expression* that is evaluated at run-time (See [here][2], and [here][3]). As a result, it only makes sense to allow a formatted string literal as the expression inside another formatted string literal, forbidding it would negate the full support for Python expressions.

  [1]: https://www.python.org/dev/peps/pep-0498/#supporting-full-python-expressions
  [2]: https://www.python.org/dev/peps/pep-0498/#abstract
  [3]: https://docs.python.org/3.6/reference/lexical_analysis.html#formatted-string-literals

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/mjmikulski/horology/snapshot/44de1b55be5524696fa054ea5e972ae53d094ea1/files/horology/timed_decorator.py?sort=name&dir=ASC&mode=heatmap#xbec2752d5d5d648b:1

![lgtm](https://user-images.githubusercontent.com/26277199/74928100-1e533680-53d9-11ea-8c35-314febecab21.png)

**Comment by tausbn** [comment]
Thank you for your report. I think what's happening here is that our handling of format specifiers is somewhat incomplete. It _should_ work if `dp` was referenced at the "top level" of the format string (like `name` and `t`). This is definitely a bug.

Unfortunately, I can't give you a timeline for when we'll get round to fixing it. If its presence bothers you, my best suggestion would be to disable the alert in question, either locally with an `lgtm` comment, or globally in an `.lgtm.yml` configuration file. You can find the documentation for these things on LGTM.com.

**Comment by johnashu** [comment]
> 
> 
> Thank you for your report. I think what's happening here is that our handling of format specifiers is somewhat incomplete. It _should_ work if `dp` was referenced at the "top level" of the format string (like `name` and `t`). This is definitely a bug.
> 
> Unfortunately, I can't give you a timeline for when we'll get round to fixing it. If its presence bothers you, my best suggestion would be to disable the alert in question, either locally with an `lgtm` comment, or globally in an `.lgtm.yml` configuration file. You can find the documentation for these things on LGTM.com.

Thanks for the quick reply.

I will look at other options and hopefully a solution can be found soon.

**Comment by tausbn** [comment]
I believe this should now be resolved in our parser and have gone live on LGTM.com. Feel free to reopen this issue if this is not the case. :slightly_smiling_face:
