### ISSUE TITLE
LGTM.com - false positive - Overflow in uncontrolled allocation size

### ISSUE THREAD

**Issue by mmatuska** [github/codeql#2953]
**Description of the false positive**

The value passed to block_size comes from  bsdtar->bytes_per_block and can be only between 0 and 4194304:
https://lgtm.com/projects/g/libarchive/libarchive/snapshot/bc41ff0bf39759e9221545882226301d418cc550/files/tar/bsdtar.c#L299

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/libarchive/libarchive/snapshot/bc41ff0bf39759e9221545882226301d418cc550/files/libarchive/archive_read_open_fd.c?sort=name&dir=ASC&mode=heatmap#x4d1a678af15934e3:1

**Comment by geoffw0** [comment]
Possibly related to https://github.com/Semmle/ql/issues/2762.

**Comment by jbj** [comment]
Thank you for your patience with this issue. We won't get to the bottom of this in the near future, so we've now [lowered the precision of the query](https://github.com/github/codeql/pull/4068) so it's not displayed by default on LGTM. The change will take effect on the next deployment to LGTM, which should happen in 2-4 weeks from now.
