### ISSUE TITLE
Python: Add support for sqlite3

### ISSUE THREAD

**Issue by imanoracle** [github/codeql#2961]
This is the [file](https://github.com/imanoracle/vulnerable/blob/master/ansible/roles/api/files/vAPI.py) that I fed to LGTM. It has multiple issues (12 different unique issues). For example, there is an SQL injection bug in function `def get_user(user):`, even though it has SQL injection query (default for Python), still it cannot detect it. Could you please help me to resolve the issue?

**Comment by RasmusWL** [comment]
Thanks for bringing this up. I can see that you are using `sqlite3` in your example vulnerable code, and that our current CodeQL libraries does not have any support for `sqlite3`. I have updated this ticket to become a feature request for this.

If you have other problem, please open a new issue for them :blush:

**Comment by imanoracle** [comment]
Thank you very much.

**Comment by RasmusWL** [comment]
Support for sqlite3 was added in https://github.com/github/codeql/pull/4801, so closing this feature request now
