### ISSUE TITLE
LGTM.com - false positive on Python f-string with Unicode named entities

### ISSUE THREAD

**Issue by QuLogic** [github/codeql#3044]
**Description of the false positive**

LGTM states that `f"{degrees:0.0f}\N{DEGREE SIGN}"` is a `SyntaxError` on Python 3.7. However, it is not; the beginning is a regular f-string, and the `\N{}` is a Unicode character name. This syntax has worked since long before f-strings were introduced.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/matplotlib/matplotlib/snapshot/4815f4c68d7b205467cb7d5546aafe7cae9a3632/files/lib/matplotlib/projections/geo.py?sort=name&dir=ASC&mode=heatmap#x45394d1ecac47e47:1

**Comment by tausbn** [comment]
Thank you for your report. It looks like our parser is getting confused by the fact that curly braces can be used both to indicate f-string expressions, and also Unicode name aliases.

@BekaValentine This may be suitable for you to look at, since it'll most likely require a change to the tokenizer.

**Comment by tausbn** [comment]
This has been fixed. You should expect to see this change take effect in a couple of weeks.
