### ISSUE TITLE
LGTM.com - false positive python local imports flagged duplicate imports.

### ISSUE THREAD

**Issue by Anutrix** [github/codeql#3068]
**Description of the false positive**
Removing the import fails(reported by Travis).

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/godotengine/godot/snapshot/5417b13a54cecf94cfe456f9fb8a5badbbe14591/files/methods.py?sort=name&dir=ASC&mode=heatmap#x27aa2a1de55baf77:1

**Comment by tausbn** [comment]
Thank you for your report. Do you know how the `win32_spawn` function is called? I couldn't find any indication of how this happens in the repo you linked.

I'm wondering if this has something to do with how the function is invoked, and in particular if it's in a `spawn`ed subprocess. I could imagine that in that case the outer import of `subprocess` is no longer visible (though this is just a hunch).

**Comment by Anutrix** [comment]
I am not sure it's probably called by Scons.
