### ISSUE TITLE
LGTM.com - false positive - Python: six.assertRaisesRegex

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [github/codeql#3207]
**Description of the false positive**

When having a test that is expected to raise an exception using 

```python
with six.assertRaisesRegex(self, ValueError, emsg):
    OptionsValues("a=2\nconfig\nb=3")
```

LGTM.com analysis reports that an iteration could happen over a string (instead of a collection of items). I am not sure whether this is at all supported or it's too difficult to implement, but reporting here just in case. 

I guess that an expectation from the end user would be that calls that are supposed to raise an exception happening within a context manager that suppress the exception (as `six.assertRaisesRegex` does or with `unittest` e.g. with `self.assertRaises(TypeError)`) shouldn't trigger an alert on LGTM.com.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/conan-io/conan/snapshot/b4ebb2ce8abbd5585832d3d6f6175d4f56233557/files/conans/model/options.py#L184 where the error is reported

https://lgtm.com/projects/g/conan-io/conan/snapshot/b4ebb2ce8abbd5585832d3d6f6175d4f56233557/files/conans/test/unittests/model/options_test.py#x392febecfb386487:1 test where the call happens

**Comment by RasmusWL** [comment]
Thanks Alexey :+1: I agree that this alert is not useful. PR that fixes this is on it's way :rocket:
