### ISSUE TITLE
LGTM.com - false positive: Contradictory type checks not instanceof

### ISSUE THREAD

**Issue by suneet-s** [github/codeql#3249]
**Description of the false positive**

The failure indicates that the instance of expression can never be true. However the assert statement in the code is checking the inverse of the assert statement.

```
assert !(current instanceof QueryDataSource);
```

This flags that `current instanceof QueryDataSource` is always false, which is what is expected based on the not ahead of the instanceof check.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/apache/druid/snapshot/490d344f16a9321ad617e5a1daac0c489b967be1/files/server/src/main/java/org/apache/druid/server/ClientQuerySegmentWalker.java#x604538127fba3c48:1

**Comment by aschackmull** [comment]
Yes, indeed the alert is correctly telling you that the assertion is always true, so this is not a false positive.
In this case this can be seen with very simple local reasoning, so I would say that the `assert` statement is superfluous - it's not really checking anything that isn't already checked just a few lines above.  I'd suggest deleting the `assert`, or perhaps replace it with a comment.
