### ISSUE TITLE
Java false positive during the instantiation of a singleton

### ISSUE THREAD

**Issue by nblxa** [github/codeql#3253]
The condition `INSTANCE != null` is falsely considered to be always `true`. This is a corner case since typically a `static final` field is always initialized, however in this case the condition is the code that does the initialization in the first place.

```java
    static final Nil<?> INSTANCE = new Nil<>();

    private Nil() {
        if (INSTANCE != null) {
            throw new UnsupportedOperationException();
        }
    }
```

Link to source:

https://lgtm.com/projects/g/nblxa/cons-list/snapshot/7e701271e9f42a4e87e854fdf6a1444878a0d168/files/cons-list/src/main/java/io/github/nblxa/cons/Nil.java?sort=name&dir=ASC&mode=heatmap#xb068fdc3eccdc3a6:1

Screenshot of the alert:
![image](https://user-images.githubusercontent.com/195997/79130891-f9ab8780-7da7-11ea-80ab-04dec957c694.png)

Screenshot of the debugger stating that the value is in fact false when running the test `io.github.nblxa.cons.ConsListTest#spliterator_characteristicsAndData` in debug mode.
![image](https://user-images.githubusercontent.com/195997/79131008-2f507080-7da8-11ea-88b4-8f08db0990a2.png)

**Comment by aschackmull** [comment]
You are correct that this is a false positive, and as you also say, this is somewhat of a corner-case, so I think an alert suppression comment is the most appropriate fix.
