### ISSUE TITLE
LGTM.com - false positive - regular expressions with high Unicode codepoints

### ISSUE THREAD

**Issue by jbarlow83** [github/codeql#3281]
**Description of the false positive**

LGTM attempts to parse this regular expression but misunderstands it for some reason.

https://lgtm.com/projects/g/pikepdf/pikepdf/snapshot/cd5e853439a4c324c788dbf6a5eb234575cc37fd/files/src/pikepdf/models/metadata.py?sort=name&dir=ASC&mode=heatmap#xd0c9ca18fb0d3f1d:1

**Comment by RasmusWL** [comment]
There is one problem with your code that might be causing it.

Unicode escape sequences with `\u` in Python strings only work with 16-bit hex values (as described [here](https://docs.python.org/3/howto/unicode.html#the-string-type)). So for the range U+10000–U+10FFFF, you should be using `\U`.

For example, the unicode character for the grinning face 😀 is `1F600` : http://www.fileformat.info/info/unicode/char/1F600/index.htm

```py
>>> print('\u1F600', '\U0001F600')
... ὠ0 😀
```


I'm not sure if all errors will go away once this is fixed, but it's a good first step :)

**Comment by jbarlow83** [comment]
I changed to \U and LGTM still parses it incorrectly.

https://lgtm.com/projects/g/pikepdf/pikepdf/snapshot/6745fa83fc21ebc4312c62ae3fc8a526f9757940/files/src/pikepdf/models/metadata.py?sort=name&dir=ASC&mode=heatmap#x88a58cd2b59a7044:1

The expression works as it should
https://regex101.com/r/oK0kLl/1

**Comment by RasmusWL** [comment]
Yep that does look like we're not handling the unicode escapes properly.

Thanks for taking the time to report this and updating your code :+1: I'm not sure when we will have time to fix this, but it has been added to our backlog :heavy_check_mark:

**Comment by RasmusWL** [comment]
This was fixed in https://github.com/github/codeql/pull/3464
