### ISSUE TITLE
Minor typo in comment

### ISSUE THREAD

**Issue by hohn** [github/codeql#3356]
**Description of the issue**

Minor typo: in Access.qll, [L341](https://github.com/Semmle/ql/blob/4eea62cbde459b054126d9e78ccbeb79e15d3743/cpp/ql/src/semmle/code/cpp/exprs/Access.qll#L341) should be `myFunctionTarget`

**Comment by geoffw0** [comment]
Thanks for spotting this.  I've made a pull request to fix it.

**Comment by MathiasVP** [comment]
Fixed by https://github.com/github/codeql/pull/3414.
