### ISSUE TITLE
Minor issue in Python docs: "Tutorial: Statements and Expressions"

### ISSUE THREAD

**Issue by lgolding** [github/codeql#3360]
On https://help.semmle.com/QL/learn-ql/python/statements-expressions.html, in the section “Example: Finding comparisons to integer or string literals using ‘is’”, the Tip says:

> … the expression `3 < x < 7` has two operators and two comparators. You use `cmp.getComparator(0)` to get the first comparator (in this example the `3`) and `cmp.getComparator(1)` to get the second comparator (in this example the `7`).

But `getComparator(0)` returns the `x`, not the `3`. To get the `3`, you'd call `getLeft()`.

@lcartey FYI

**Comment by RasmusWL** [comment]
Thanks for point this out @lgolding :+1: I'll make a fix for this soon.

I'll update this issue once the fix has gone live :blush:

**Comment by lgolding** [comment]
Thanks. Sorry for the duplication.

**Comment by RasmusWL** [comment]
No worries :)

**Comment by RasmusWL** [comment]
Hi @felicitymay, the fix for this problem was merged into master 7 days ago. When should we expect that it goes live on help.semmle.com ? :blush:

**Comment by felicitymay** [comment]
Hi @RasmusWL, we'll be updating all the help for the release of 1.24 at the end of this week/start of next week. This correction is included in that update so will be live by the middle of next week, at the latest. 

Hi @lgolding 👋
Thanks for reporting the error 🙇‍♀️

**Comment by shati-patel** [comment]
This has now been published 🎉 😄 
https://help.semmle.com/QL/learn-ql/python/statements-expressions.html
