### ISSUE TITLE
LGTM.com - false positive [py/modification-of-default-value]

### ISSUE THREAD

**Issue by adrianinsaval** [github/codeql#3397]
`.__contains__()` doesn't modify the default value AFAIK, please correct me if I'm wrong.

https://lgtm.com/projects/g/FredsFactory/FreeCAD_AirPlaneDesign/snapshot/a5329a06a35e8bb8b1d06be41b2591f4c2662658/files/airPlaneAirFoil.py?sort=name&dir=ASC&mode=heatmap#x5046bdac50e4dafa:1

**Comment by RasmusWL** [comment]
Thanks for this report @adrianinsaval! I agree, `foo.__contains__(x)` does not modify `foo`.

I'll update the query in a PR :+1:

ref: https://docs.python.org/3.8/library/operator.html#operator.__contains__

**Comment by adrianinsaval** [comment]
Thanks!

**Comment by RasmusWL** [comment]
Should go live on lgtm.com within the next few weeks.
