### ISSUE TITLE
Java: Private interface methods are considered public

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#3416]
Since Java 9 interface methods can be `private`:
> A method in the body of an interface may be declared `public` or `private`

[JLS §9.4](https://docs.oracle.com/javase/specs/jls/se9/html/jls-9.html#jls-9.4)

However, CodeQL currently considers them public:
https://github.com/github/codeql/blob/11ffcc43782e9ae07f0ff40afe40ff65ca3e3604/java/ql/src/semmle/code/java/Member.qll#L365-L366

Example query (finds methods in the example projects on https://lgtm.com/query):
```
import java

from Method m
where
 m.isPrivate() and m.isPublic()
select m
```

**Comment by aschackmull** [comment]
Thank you for bringing this to our attention. I've put up a PR to fix this.
