### ISSUE TITLE
odasa analyzeSnapshot --sarif-add-snippets option is not documented

### ISSUE THREAD

**Issue by lgolding** [github/codeql#3428]
Proposed description:

> Optional, supported for SARIF output only (version 2.0 and above). Use to include in each result the textual contents ("snippet") of the region where the result was detected.
>
> Default: The results do not include snippets

**Comment by jketema** [comment]
Hi @lgolding. Thanks for your suggestion. Since Odasa is no longer supported. I'm closing this issue. Note that Odasa's replacement - the CodeQL CLI - does document this option. See, e.g., here: https://codeql.github.com/docs/codeql-cli/manual/database-analyze/
