### ISSUE TITLE
JS: Add support for Fastify

### ISSUE THREAD

**Issue by subesokun** [github/codeql#3435]
This is a feature request for adding support for [Fastify](https://github.com/fastify/fastify). Various [HTTP Frameworks](https://github.com/github/codeql/blob/master/javascript/ql/src/semmle/javascript/frameworks/HttpFrameworks.qll) are already supported but unfortunately, Fastify is missing. The Fastify team signaled that they'd help review/identify common problems but they don't have the bandwidth to provide the GraphQL queries on their own, see https://github.com/fastify/help/issues/187.

**Comment by mcollina** [comment]
Thanks!
