### ISSUE TITLE
LGTM.com - false positive in leptonica

### ISSUE THREAD

**Issue by DanBloomberg** [github/codeql#3437]
lgtm static analyzer claims that a variable read by fscanf is not checked and could lead to overflow

In fact the variables depth and ncolors are both checked immediately after reading in
     colormap.c: pixcmapReadStream()
If they are out of bounds, they are not used any further.

Then in pixcmapCreate(), which is called by pixcmapReadStream(), the depth is checked again and if not one of the 4 allowed values, it returns NULL.  I have just added another check and if cmap is not made, pixcmapReadStream() returns NULL, although I expect the false positive to be unaffected by this.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/DanBloomberg/leptonica/snapshot/a0146dcfc73f1f44967afd4195507b20fdbede77/files/src/colormap.c?sort=name&dir=ASC&mode=heatmap#x2cdb45b7161e593:1

**Comment by jbj** [comment]
Thank you for the report. I think this issue has the same root cause as https://github.com/github/codeql/issues/2762, which is for a query we're actively working to improve. @geoffw0, do you agree?

**Comment by geoffw0** [comment]
Yes it looks related, I'm not sure whether the existing fix is going to catch this case yet.

**Comment by geoffw0** [comment]
Test added in https://github.com/github/codeql/pull/3479, but the fix there doesn't cover this case.

**Comment by jbj** [comment]
Thank you for your patience with this issue. We won't get to the bottom of this in the near future, so we've now [lowered the precision of the query](https://github.com/github/codeql/pull/4068) so it's not displayed by default on LGTM. The change will take effect on the next deployment to LGTM, which should happen in 2-4 weeks from now.
