### ISSUE TITLE
LGTM.com - false positive -- Modification of parameter with default flowing through `copy`

### ISSUE THREAD

**Issue by richterdavid** [github/codeql#3462]
**Description of the false positive**

facets is copied before being mutated, so it's not the default parameter that is modified.

**URL to the alert on the project page on LGTM.com**

Line 144 of

https://lgtm.com/projects/g/kubernetes/community/snapshot/5223f7caca528791cd581566604bc1190576cc88/files/sig-contributor-experience/surveys/k8s_survey_analysis/plot_utils.py?sort=name&dir=ASC&mode=heatmap#xbfe835a53e86836d:1

**Comment by max-schaefer** [comment]
It looks like this is actually a Python issue.

**Comment by tausbn** [comment]
Thank you @max-schaefer. I agree this is Python-related.

As for the FP itself, I agree with the report. Ironically, having `copy` preserve taintedness is a fairly low-level assumption in our taint-tracking libraries, but in this case it should actually sanitise away the taint.
