### ISSUE TITLE
LGTM.com - false positive XSS detection in Python Django HttpResponseRedirect(url)

### ISSUE THREAD

**Issue by ajinabraham** [github/codeql#3466]
**Description of the false positive**

The string is appended to the end of a URL. There is no XSS here.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/MobSF/Mobile-Security-Framework-MobSF/snapshot/8fae9352bd3cb15fc7016a0ad9dbbd400bfa5e98/files/DynamicAnalyzer/views/android/dynamic_analyzer.py?sort=name&dir=ASC&mode=heatmap#x2313d0a373a97168:1

**Comment by RasmusWL** [comment]
Hi @ajinabraham, thanks for your report :+1:

I agree that this is a false positive, and will see if I can get it fixed fairly soon :blush: :crossed_fingers:
