### ISSUE TITLE
LGTM is too Chatty

### ISSUE THREAD

**Issue by gfs** [github/codeql#3493]
For an example of how being too chatty distracts from usefulness: https://github.com/microsoft/AttackSurfaceAnalyzer/pull/398

## Actual Behavior: 
LGTM Spams my PRs with Comments for every subsequent commit if any commit previous to it in the branch fixes an LGTM issue.

## Expected Behavior: 
LGTM comments only on the commit that fixes the issue.

## Explanation: 
LGTM should comment if the new commit changes something from the previous commit (i.e. new warnings).  Getting repeated information, particularly that you've fixed something, is not useful.

**Comment by jketema** [comment]
Hi @ljharb . Apologies for not getting back to you and thanks for your interest in LGTM.  I'm closing this issue, as LGTM has been shutdown. Please see the [blog post on LGTM's deprecation](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) for further details. More details on LGTM's replacement - Code Scanning - can be found in the [GitHub Docs for this feature](https://docs.github.com/en/code-security/code-scanning). If you feel that Code Scanning exhibits the same kind of behaviour please open a new issue.
