### ISSUE TITLE
LGTM.com - false positive: Syntax Error (in Python 3).

### ISSUE THREAD

**Issue by MrCreosote** [github/codeql#3588]
**Description of the false positive**

The false positive is for a syntax error in py3. A syntax error should prevent compilation, however the code compiles and tests successfully in TravisCI. Moreover, examination of the highlighted code reveals that it is legal syntax.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/kbase/sample_service/snapshot/3fce2a4d46033a8c596bfb9e9c58e72eb9706bda/files/lib/SampleService/core/storage/arango_sample_storage.py?sort=name&dir=ASC&mode=heatmap#x8fba044a7b4c5e0b:1

**Comment by tausbn** [comment]
Thank you for this report. It seems our latest update to LGTM.com managed to introduce a bug in how we parse `{{` appearing inside a triple-quoted string. I am working on a fix now. The syntax error should go away once that fix goes live, though this may take a few weeks.
