### ISSUE TITLE
Problem with "import cpp" using CODEQL

### ISSUE THREAD

**Issue by PhPires13** [github/codeql#3614]
Hi,

I'm starting to study CODEQL from the GitHub Learning Lab(  _https://lab.github.com/githubtraining/codeql-u-boot-challenge-(cc++)_  ). I did the first two steps correctly(I think), but when I try to run the first code of the third step, that error appear:

![Capturar](https://user-images.githubusercontent.com/65675322/83653223-dfb14880-a591-11ea-8bcc-1c4c7ee763ad.PNG)

Is there something that I have to add for this to work ?

**Comment by p0** [comment]
I think this would happen if you cloned the `vscode-codeql-starter` repo without submodules. See [here](https://github.com/github/vscode-codeql-starter/#instructions) for full instructions; could you try running `git submodule update --init` in your checkout root to see whether that will fix the problem?

Context: You need a clone of the github/codeql repo to be able to `import cpp`; the starter workspace achieves this through a submodule reference.

**Comment by PhPires13** [comment]
So, this is the first time I'm working with GitHub Projects.

If you could teach me where I have to use the commands `git`, like `git clone --recursive` or `git submodule update --init`. It would help a lot, because I really think the problem exits because I didn't add the submodules.

**Comment by p0** [comment]
Sure, I can help out.

If you look to Visual Studio Code window from your screenshot, I think the easiest thing to do is open the integrated terminal (Ctrl+Shift+P `Terminal: Create New Integrated Terminal (In Active Workspace)`, or click the 'Terminal' tab in the bottom pane). That should give you a prompt in which you can run `git submodule update --init`, which should be all you need.

If you're interested in the full details about submodules, [the Pro Git book](https://git-scm.com/book/en/v2/Git-Tools-Submodules) has a good reference.

Hopefully this helps you get further!

**Comment by PhPires13** [comment]
I created the terminal with the folowing address(and other addresses to), but when I try to execute any `git` command, the following message appear.

![image](https://user-images.githubusercontent.com/65675322/83777572-f6be6c00-a65f-11ea-9533-5ef7e38a2984.png)

Do I need an specific address ?

**Comment by p0** [comment]
Hmm, that's odd -- it indicates `git` isn't globally installed for you. How did you get a copy of the starter workspace? Perhaps it's not set up system-wide, and you need to open a 'Git bash' from the start menu, run `cd /c/Users/Pedro/Documents/CodeQL/vscode-codeql-starter-master` and try `git submodule update --init` there?

**Comment by PhPires13** [comment]
Do you think it will be easier if restart the installation ?

Btw, do I need this ?
![image](https://user-images.githubusercontent.com/65675322/83780548-b19c3900-a663-11ea-9216-50d2af70269f.png)

**Comment by p0** [comment]
Yes, to get the workspace easily and completely I'd highly recommend installing `git`.

Am I right in thinking that you got the starter workspace by downloading a `.zip` file from GitHub? If so, I'm afraid the easiest thing will indeed be to start over. I'd suggest the following steps:

1. Install `git` for windows from the page you shared above.
2. Open "Git bash", `cd` to the folder where you want to store the workspace, and follow the [starter workspace instructions](https://github.com/github/vscode-codeql-starter/#instructions) by running `git clone --recursive https://github.com/github/vscode-codeql-starter`.
3. Open the VS Code workspace file within this new directory, and proceed with the learning lab.

**Comment by PhPires13** [comment]
I'm starting to follow this steps right now and thanks for your  help, but I have just one doubt:

I read about that **_"Git bash"_**, and its like a **Linux prompt for Windows**. So, if I use an Unix based OS, like MacOS, I would not have to download the `git`, just use the **basic Command Prompt**, right ?

**Comment by p0** [comment]
"Git bash" is installed by Git for Windows when you install it. On platforms like MacOS or Linux, `bash` would typically be one of the pre-installed shells, and you would still have to install `git`, whether by `apt`, `yum`, `brew` or another package manager.

**Comment by PhPires13** [comment]
Finally its ready, thanks man.

So, the problem really was because I was trying to do without the submodules, and when I tried to to add, it went wrong beacuse I was using Windows.

So I literally followed the steps you enumerated above.
