### ISSUE TITLE
Python: see false positive "too many arguments"

### ISSUE THREAD

**Issue by Junchao-Mellanox** [github/codeql#3617]
I have a Fan class which takes 2 mandatory args and 3 optional args, but LGTM report 3 errors for oneline:
Call to 2 Values with too many arguments; should be no more than 2.
Call to 4 Values with too many arguments; should be no more than 3.
Call to 3 Values with too many arguments; should be no more than 4.

https://lgtm.com/projects/g/Azure/sonic-buildimage/snapshot/e5fa9e1f0332301bd2543f9cda87c0f676acab6d/files/platform/mellanox/mlnx-platform-api/sonic_platform/chassis.py?sort=name&dir=ASC&mode=heatmap#xd37274ac53a618c6:1

**Comment by RasmusWL** [comment]
Agreed that this looks odd, thanks for reporting :+1:

There seems to be a _lot_ of definitions of `class Fan` residing in the file `sonic_platform/fan.py` in different subfolders. For example:

- [device/accton/x86_64-accton_as7116_54x-r0/sonic_platform/fan.py](https://lgtm.com/projects/g/Azure/sonic-buildimage/snapshot/e5fa9e1f0332301bd2543f9cda87c0f676acab6d/files/device/accton/x86_64-accton_as7116_54x-r0/sonic_platform/fan.py?sort=name&dir=ASC&mode=heatmap#xbd23450813edcc0c:1) -- takes up to 3 args
- [platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/fan.py](https://lgtm.com/projects/g/Azure/sonic-buildimage/snapshot/e5fa9e1f0332301bd2543f9cda87c0f676acab6d/files/platform/broadcom/sonic-platform-modules-dell/s6000/sonic_platform/fan.py?sort=name&dir=ASC&mode=heatmap#x3f9726b5556283c5:1) -- takes up to 4 args
- [device/celestica/x86_64-cel_e1031-r0/sonic_platform/fan.py](https://lgtm.com/projects/g/Azure/sonic-buildimage/snapshot/e5fa9e1f0332301bd2543f9cda87c0f676acab6d/files/device/celestica/x86_64-cel_e1031-r0/sonic_platform/fan.py?sort=name&dir=ASC&mode=heatmap#xd63f4a8ad762095c:1) -- takes up to 5 args

@tausbn, think it makes most sense that you look at this in regard to the work you're doing on the module resolution? :blush:

**Comment by tausbn** [comment]
Yeah, this looks like a bug in the module resolution. I will investigate.
