### ISSUE TITLE
Java: Assignment / LValue getControlFlowNode().getASuccessor() holds for RHS

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#3688]
**Description of the issue**
It appears that both `Assignment` and `LValue` `getControlFlowNode().getASuccessor+()` holds for expressions which are part of the right-hand side of the assignment, even though they are evaluated before the assignment and are therefore not actually a successor:
```java
String s = "abc";
// QL claims that `substring` call is a successor of assignment
s = s.substring(1);
```

Example query:
```ql
import java

from MethodAccess call, Assignment assign, Variable var
where
  assign.getControlFlowNode().getASuccessor+() = call
  and call.getQualifier() = var.getAnAccess()
  and call.getParent+() = assign
  and assign.getDest() = var.getAnAccess()
select assign, call

```
Or is there something wrong with the query?

**Comment by aschackmull** [comment]
I'd guess that your Java code snippet is contained in a loop.  If I run your query on
```
  void foo() {
    String s = "abc";
    s = s.substring(1);
  }
```
then I get zero results.

**Comment by Marcono1234** [comment]
Good point, it appears that was indeed the case for the results it found, adding
```
and not call.getEnclosingStmt().getEnclosingStmt*() instanceof LoopStmt
```
causes it to not find anything anymore.
Sorry for the trouble. QL's control flow classes and predicates are pretty useful!
