### ISSUE TITLE
Consider supporting distinct SARIF `id` vs `name` properties  in CodeQL SARIF (to support MS-style opaque identifiers)

### ISSUE THREAD

**Issue by michaelcfanning** [github/codeql#3699]
CodeQL emits an identical value for its [id](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317839) and [name](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317843) properties. The 

In SARIF, this value looks more like the readable `name` property. CodeQL emits this in both places, I assume, because `id` is the more required value to persist and because CodeQL does not have a convention for defining opaque ids (such as is very typical in Microsoft compilers, where there is a short prefix, typically designation a language or tool, and a 4 digit numeric code, e.g., CS1001).

        "rules" : [ {
          "id" : "cpp/lossy-pointer-cast",
          "name" : "cpp/lossy-pointer-cast",

Since CodeQL has this duplication, it raises the possibility of allowing users to add an explicit new  `id` passthrough property. MS would use this to allocate opaque rule identifiers that make CodeQL analysis results fold more seamlessly into existing systems (built around tools such as PREfast /analyze that emit compiler-style identifiers).

I observed and commented on this issue a few years ago. :) I noticed this comment in a spec I was just reviewing on a Windows CodeQL integration effort and so am raising the issue again. This convention of requiring opaque all or mostly-numeric ids also exists in the Office team's historical analysis infrastructure (OACR). The danger for MS is that each distinct infrastructure allocates its own ids. Better (for us here internally anyway) would be if we could bake this rule id directly into CodeQL, so that the rule sets we share would be connected in this way.

    Windows static analysis fabricates a numeric rule Id for Semmle rules.  They take the the form 99XXXX.  Ex: 990001

Btw - I am aware that we can use the @tag mechanism to assign/flow a rule id to SARIF in the property bag. We can consider this as a workaround.

**Comment by lcartey** [comment]
Hi @michaelcfanning!

The good news is that we do already have a facility for this, through a query metadata property called `@opaqueid`. If present, this is surfaced in the SARIF output in the rule `id` properties in preference to the `@id`. We actually add this in response to your observation/comments from a few years ago, and the feature is actually used within Microsoft (give me a shout directly if you want to discuss that).
