### ISSUE TITLE
LGTM.com - false positive: unexcaped URL regex with re.escape

### ISSUE THREAD

**Issue by UncleGoogle** [github/codeql#3712]
The parser says 

> This regular expression has an unescaped '.' 

despite `re.escape` is used.

https://lgtm.com/projects/g/UncleGoogle/galaxy-integration-humblebundle/snapshot/db6cdbd82cfd52c312bbdab1a04b62332686fa1c/files/src/plugin.py?sort=name&dir=ASC&mode=heatmap#xeffd31b6e2e973f8:1

**Comment by RasmusWL** [comment]
Hi @UncleGoogle, thanks for reporting this :+1:

I'll have a fix ready soon. Once that is merged, the fix will go live on LGTM.com within a few weeks.
