### ISSUE TITLE
false positive with `<script lang="ts">` in `*vue`

### ISSUE THREAD

**Issue by Mister-Hope** [github/codeql#3730]
**Description of the false positive**

vue files with `<script lang="ts">` should be treated as typscript files

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/Mister-Hope/vuepress-theme-hope/snapshot/790b5ca7cd47066c2af5e23bc0c9171da8e6e608/files/packages/components/src/MyBadge.vue?sort=name&dir=ASC&mode=heatmap#x11336253b9b90367:1

https://lgtm.com/projects/g/Mister-Hope/vuepress-theme-hope/snapshot/790b5ca7cd47066c2af5e23bc0c9171da8e6e608/files/packages/theme/components/Anchor.vue?sort=name&dir=ASC&mode=heatmap#x8bdfaec729b3e527:1

https://lgtm.com/projects/g/Mister-Hope/vuepress-theme-hope/snapshot/790b5ca7cd47066c2af5e23bc0c9171da8e6e608/files/packages/theme/components/SidebarLink.vue?sort=name&dir=ASC&mode=heatmap#x9436911ffb661355:1

The issue is asked in https://discuss.lgtm.com/t/support-for-vue-single-file-components-with-class-decorators/2518 Dec 2019, but still unsupported after half year time.

**Comment by asgerf** [comment]
Hi @Mister-Hope. Thanks for bringing it up again. I've put it on the agenda for our next team meeting. I'll get back to you next week.

**Comment by asgerf** [comment]
It should be fixed as of https://github.com/github/codeql/pull/3832. The syntax errors should go away next time LGTM.com is updated.
