### ISSUE TITLE
[js/xss] JavaScript: Rule misses nearly all location.hash vectors

### ISSUE THREAD

**Issue by Raz0r** [github/codeql#3828]
Hi!

While testing `js/xss` rule, I've got a bunch of false negatives on `location.hash`. Some of the test cases:

```js
var payload = window.location.hash.substr(1);document.write(payload);
```

```js
var payload = window.location.hash.substr(1);document.writeln(payload);
```
```js
var payload = document.location.hash.substr(1);
var iframe = document.createElement("iframe");
iframe.src = payload;
document.body.appendChild(iframe);
```
```js
var payload = window.location.hash.substr(1);var div = document.createElement('div');
div.innerHTML = '<div onclick=\'' + payload.replace(/'/g, '"') + '\'>div</div>';
document.documentElement.appendChild(div);
```
```js
var payload = window.location.hash.substr(1);var div = document.createElement('div');
div.setAttribute('onclick', payload);
document.documentElement.appendChild(div);
```
```js
var payload = document.location.hash.substr(1);
var scriptElement = document.createElement("script");
scriptElement.src = payload;
document.body.appendChild(scriptElement);
```

This happens because of 
1) a [sanitizer](https://github.com/github/codeql/blob/master/javascript/ql/src/semmle/javascript/security/dataflow/Xss.qll#L357) on `hash` property;
2) custom [load/store steps](https://github.com/github/codeql/blob/master/javascript/ql/src/semmle/javascript/security/dataflow/DomBasedXss.qll#L31) `isAdditionalLoadStep`/`isAdditionaLoadStoreStep` not working properly. 

Although a comment in `SafePropertyReadSanitizer ` makes sense for jQuery sinks, it does not take into account other sinks like `document.write()`.

**Comment by asgerf** [comment]
Hi @Raz0r,

Thanks for reporting this. I'm not sure how this happened, but will get it fixed ASAP.

**Comment by Raz0r** [comment]
Can confirm that the test cases are now detected, thank you!
