### ISSUE TITLE
LGTM.com - false positive C#

### ISSUE THREAD

**Issue by tznind** [github/codeql#3868]
https://lgtm.com/projects/g/HicServices/RDMP/snapshot/6d305579cf2e95d876f63c52769d56f77259813a/files/Rdmp.Core/DataExport/Data/ProjectCohortIdentificationConfigurationAssociation.cs?sort=name&dir=ASC&mode=heatmap#xcdc480d705fa1806:1

Line is flagged 'always null'.  Property `CohortIdentificationConfiguration` returns the value of a `Lazy<CohortIdentificationConfiguration>` (called `_knownCic`) so I'm not sure why it thinks it would always be null... possibly because of the `reason = null` line? That is required in case the property returns null so assignment of the out variable is satisfied in the `?? false` condition.

```csharp
public bool ShouldBeReadOnly(out string reason)
{
	reason = null;
	return CohortIdentificationConfiguration?.ShouldBeReadOnly(out reason) ?? false;
}
```

**Comment by hvitved** [comment]
Hi 👋 

It appears that this false-positive has already been fixed; the alert is no longer there in the most recent version: https://lgtm.com/projects/g/HicServices/RDMP/alerts/?mode=list&id=cs%2Fdereferenced-value-is-always-null.

Best regards,

Tom

**Comment by tznind** [comment]
Hi, thanks for looking into this? wouldn't the filter be 'Expression is always 'null'' not 'dereferenced value is always null'?

**Comment by hvitved** [comment]
Ah, sorry, you are absolutely right; I was looking at the wrong query. Here is the right query: https://lgtm.com/projects/g/HicServices/RDMP/alerts/?mode=list&id=cs%2Fconstant-condition. I'll look into why this false positive is reported.

**Comment by hvitved** [comment]
Here is the fix: https://github.com/github/codeql/pull/3870.

Thanks again for reporting this @tznind.
