### ISSUE TITLE
I can not get any result under cli mode

### ISSUE THREAD

**Issue by xsser** [github/codeql#3872]
**Description of the issue**
result codez:

`from DataFlow::PathNode source, DataFlow::PathNode sink, RemoteInputToURLOpenMethodFlowConfig c
where c.hasFlowPath(source, sink)
select "query", source, sink, "ssrf occurred $@.", source.getNode(), "user input"
`

I got the result  in Codeql vscode .

But  i can not get anything  under cli 

cmd i ran :
`codeql database create codeqltest --language=java && codeql  database analyze --format=sarif-latest --output=./codeql_db.json --threads 4  codeqltest /Users/xxxx/Downloads/codeql-plugin/codeql/java/ql/src/Security/CWE/yyy/ssrf.ql
`

my output json:
```

{
  "$schema" : "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version" : "2.1.0",
  "runs" : [ {
    "tool" : {
      "driver" : {
        "name" : "CodeQL command-line toolchain",
        "organization" : "GitHub",
        "semanticVersion" : "2.1.2",
        "rules" : [ {
          "id" : "java/ssrf-injection",
          "name" : "java/ssrf-injection",
          "shortDescription" : {
            "text" : "ssrf"
          },
          "fullDescription" : {
            "text" : "ssrf"
          },
          "defaultConfiguration" : {
            "level" : "error"
          },
          "properties" : {
            "tags" : [ "security" ],
            "kind" : "path-problem",
            "precision" : "high",
            "name" : "ssrf",
            "description" : "ssrf",
            "id" : "java/ssrf-injection",
            "problem.severity" : "error"
          }
        } ]
      }
    },
    "results" : [ ],
    "columnKind" : "utf16CodeUnits",
    "properties" : {
      "semmle.formatSpecifier" : "sarif-latest"
    }
  } ]
```

**Comment by aschackmull** [comment]
Try replacing `select "query", ...` with `select sink.getNode(), ...`.  The very first item in the `select` should be an entity, which will define the source location for the alert, so I'm guessing that as soon as the raw result is interpreted it disappears since the string `"query"` does not have a location.  Running the query in VSCode will, however, be able to show you the raw result without the alert interpretation.

**Comment by xsser** [comment]
> Try replacing `select "query", ...` with `select sink.getNode(), ...`. The very first item in the `select` should be an entity, which will define the source location for the alert, so I'm guessing that as soon as the raw result is interpreted it disappears since the string `"query"` does not have a location. Running the query in VSCode will, however, be able to show you the raw result without the alert interpretation.

Thanks in advance, I have solved the problem.
I changed the first column  using
`select source.getNode(), source, sink, "input comes $@.", source.getNode(), "output"`
instead.

May it help anyone needs
