### ISSUE TITLE
LGTM.com - false positive [CWE 457] CPP

### ISSUE THREAD

**Issue by klebertarcisio** [github/codeql#3904]
**Description of the false positive**

Hi, I am using CodeQL offline and would like to share a case with you.

I am analyzing CWE 457. [The CWE 457](https://github.com/github/codeql/blob/794a3deba9af7983a14c8a7a8ba3ec0cff3b3e75/cpp/ql/src/Security/CWE/CWE-457/ConditionallyUninitializedVariable.ql) query reports that there is a weakness in my code below

Ok, I understand that having a function with a return and not using that return is not a good practice, it looks like a smell. However, my point is this: The query does not report the weakness when I **change the call functionB (p1) to functionC (p1)**. However, as we can see, the **two functions change p1**. I believe this is a false positive. Perhaps the **memset** function is not being evaluated.

```c
#include <stdio.h> 
#include <stdlib.h> 
#include <string.h> 

typedef struct
{ 
   int x, y; 
} Point;

void functionC(Point *p1){
	p1->x = 30;
	p1->y = 40;	
}

void functionB(Point *p1){
	memset(p1, 0, sizeof(*p1));
}

int functionA(Point *p1, int flag){
	if(flag){
		p1->x = 30;
		p1->y = 40;
		return 1;
	}else{
		functionB(p1); // functionC(p1);
		return 0;
	}
}

int main(){
	Point p1;	
	functionA(&p1, 0);
	int var = p1.x;
	printf ("var = %d \n", var);
	return 0;
}

**Comment by jbj** [comment]
Thanks for taking the time to describe your use case and problem.

We've used the `ConditionallyUninitializedVariable.ql` query successfully on the few specific codebases it's been developed and tuned for. We haven't yet turned it into a general-purpose query that's expected to give good results on arbitrary codebases. As you observe, the query doesn't have built-in knowledge about `memset`. The query can be told about `memset`-like functions [via a CSV file that can be baked into the database at creation time](https://github.com/github/codeql/blob/794a3deba9af7983a14c8a7a8ba3ec0cff3b3e75/cpp/ql/src/Security/CWE/CWE-457/InitializationFunctions.qll#L126-L132), but that feature is not part of our free-to-use tooling.

In the long term I'd like to develop this query into a general-purpose query, but it hasn't become a priority yet. Our general-purpose queries have a `@precision` annotation in the header, and the queries displayed by default on LGTM and GitHub Code Scanning have `high` or `very-high` precision.

Cc @lcartey -- FYI.

**Comment by klebertarcisio** [comment]
Hi @jbj, thanks for the answer.
