### ISSUE TITLE
LGTM.com - false positive for super.printStackTrace()

### ISSUE THREAD

**Issue by agoncharuk** [github/codeql#3941]
**super.printStackTrace() in an overridden method is treated as an information exposure**

When an exception logic is extended to include additional information, we override `Exception#printStackTrace(...)` methods to amend their output and calling `super.printStackTrace()`. This call is treated as an information exposure, even though it does not actually initiate stacktrace output.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/gridgain/gridgain/snapshot/08ae5858eba2e92a2931e6d2a58470b7ac226d7c/files/modules/h2/src/main/java/org/h2/jdbc/JdbcSQLTimeoutException.java?sort=name&dir=ASC&mode=heatmap#xc131fbdd935d6c31:1

**Comment by aibaars** [comment]
Thanks for the report. This should be addressed by #3948 .
