### ISSUE TITLE
Implement PrintAST for Python

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql#3956]
This issue is about adding support to the CodeQL VS Code extension for viewing ASTs of Python files. See the parent issue github/vscode-codeql#492.

**Comment by RasmusWL** [comment]
Hi @aeisenberg, as you might know, we're currently busy reworking large parts of the Python QL libraries. So we're not going to prioritize implementing the PrintAST functionality mentioned in https://github.com/github/vscode-codeql/issues/505 before we're done with the rewrite.

**Comment by erik-krogh** [comment]
https://github.com/github/codeql/pull/4461 has been merged.
