### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by drazisil** [github/codeql#3958]
**Description of the false positive**

The current source code no longer contains this issue, but lgtm.com does not want to update. It seems to have the code cached in some way.

This was corrected as of this commit https://github.com/drazisil/Craftbox/commit/fd1c436a599d3a21e278e9cc5020d62aa66bf384#diff-d0c380c7035ec382ab6ed06963637b59 14 hours ago ago of this report.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/drazisil/Craftbox/snapshot/d72389c6067feab56c928e1dd02fb4fd3dbdd3a6/files/server/src/app.js?sort=name&dir=ASC&mode=heatmap#x4e87dfed95fe8c1d:1

**Comment by intrigus-lgtm** [comment]
If I were to guess, I would say this is your problem:
So you just have to give it a bit more time.

https://lgtm.com/help/lgtm/analysis-faqs#how-often-does-lgtm-check-for-new-commits

> LGTM checks the external repository host for new commits roughly once a day. When a new commit is found, LGTM analyzes it and updates the latest alerts view. This explains why you won't immediately see analysis results or alerts on LGTM for that commit. If you want a more rapid response, you should enable automated code review for pull requests. That way you’ll get results on proposed changes straight away, even before they are merged into your codebase.

**Comment by drazisil** [comment]
I have automated code review enabled.

**Comment by intrigus-lgtm** [comment]
Yeah, but you did not add this commit via a pull request, did you?
So your commit will only be analysed after the daily update has occured.

**Comment by drazisil** [comment]
I did try a new PR with a readme change, as well as kicking off a new analyze job. I will wait though.

**Comment by drazisil** [comment]
It has cleared. Closing.
