### ISSUE TITLE
Database Files

### ISSUE THREAD

**Issue by RickGY** [github/codeql#3964]
Hi,

I've been exploring CodeQL and noticed something weird with the database generated:

In the folder db-cpp/default (which I believe stores the tables for the code database), a folder idPool takes up a very large amount of space. I wonder what does it store and is it safe to remove it so as to save space?

Thanks

**Comment by p0** [comment]
The `idPool` folder makes it possible, hypothetically, to import further data into the database in a consistent way. Admittedly this is an advanced operation, which will not occur for the vast majority of databases. `codeql database create` takes a [`--finalize-dataset` flag](https://help.semmle.com/codeql/codeql-cli/commands/database-create.html#cmdoption-codeql-database-create-no-finalize-dataset) which will clean up this folder, and which we are considering making the default.

For existing databases, you can delete the unnecessary data safely by using [`codeql database cleanup --finalize-dataset](https://help.semmle.com/codeql/codeql-cli/commands/database-cleanup.html).

**Comment by RickGY** [comment]
thanks for the info
