### ISSUE TITLE
LGTM.com - No matching copy assignement operator false positive

### ISSUE THREAD

**Issue by Madour** [github/codeql#3966]
**Description of the false positive**

I have a class template that defines both copy constructor and copy assignement operator, but lgtm warns me about :
```
No matching copy assignment operator in class Rect<T>. It is good practice to match a copy constructor with a copy assignment operator.
```
I am also getting this warning *twice* on the same line.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/Madour/NasNas/snapshot/fa03251c2260ed1324cd5f0afb5bb19b9d336444/files/include/NasNas/data/Rect.hpp?sort=name&dir=ASC&mode=heatmap#xc4def4e2466c09d5:1

**Comment by MathiasVP** [comment]
Thanks for reporting this! I _think_ the problem is that the query is not excluding uninstantiated templates (which doesn't always have the same amount of information in the database compared to other elements). In that case, it can be weeded out with an extra condition like:
```codeql
not f.isFromUninstantiatedTemplate(_)
```

I'll create a ticket for it, but I don't know exactly when we will have a fix.

**Comment by jbj** [comment]
I just took a look at the code, and I'm inclined to say the alert is a true positive: the class doesn't have a copy assignment operator. According to https://en.cppreference.com/w/cpp/language/copy_assignment, a copy assignment operator for class `T` must take exactly one parameter of type `T` or `[const] [volatile] T&`. [The `operator=` of Rect](https://lgtm.com/projects/g/Madour/NasNas/snapshot/fa03251c2260ed1324cd5f0afb5bb19b9d336444/files/include/NasNas/data/Rect.hpp#L41) does not take such a parameter, and therefore it's technically not a copy assignment operator. It's just an overload of `operator=` that accepts the same types of argument that a copy constructor would, and more.

I'd like to hear your thoughts on this, @Madour.

**Comment by Madour** [comment]
You are totally right @jbj , it looks like I mixed the namespaces.
Thank you very much for noticing this ! and sorry for wasting your time, I should had triple checked before posting the issue.

**Comment by jbj** [comment]
No worries.
