### ISSUE TITLE
LGTM.com - false positive (C# null coalescing assignment ignored)

### ISSUE THREAD

**Issue by Trojaner** [github/codeql#3982]
**Description of the false positive**
[Null coalescing assignments](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/null-coalescing-assignment) (nullable ??= value) are not considered when analyzing nullable type usage

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/openmod/openmod/snapshot/4f9a8c1dc1a81e629a2b91675ae51094e46acd1f/files/framework/OpenMod.EntityFrameworkCore/Extensions/EntityFrameworkCoreContainerBuilderExtensions.cs?sort=name&dir=ASC&mode=heatmap#xe44d19e967183ef7:1

Example code:
```cs
private static ContainerBuilder AddDbContextInternal(this ContainerBuilder containerBuilder,
    Type dbContextType,
    Action<DbContextOptionsBuilder> optionsBuilderAction,
    ServiceLifetime? serviceLifetime)
{
   serviceLifetime ??= ServiceLifetime.Scoped;
   (...)
   something(serviceLifetime.Value); // "Variable serviceLifetime may be null here because it has a nullable type"
}
```

**Comment by hvitved** [comment]
Thanks a lot for reporting this. A fix is underway at https://github.com/github/codeql/pull/3986.
