### ISSUE TITLE
LGTM - C++ Files not appearing/importing

### ISSUE THREAD

**Issue by Dekken** [github/codeql#3997]
Hi there,

I’m having a hard time getting the files I would like to have analyzed actually be imported and/or appear. I would say the build isn’t all that trivial so there’s a chance it’s messing something up I suppose. Some files are appearing, just not all are.

No matter what I seem to do with path_classifiers it doesn't seem to change the files found in the import step.

Any help would be appreciated, it's quite probable I'm doing something silly.

Thanks

Relevant Project: https://lgtm.com/projects/g/Dekken/FUR/

**Comment by Dekken** [comment]
I should not that our C++ sources that are not appearing are also not in the set of "excluded files", they just seem to be ignored entirely.

**Comment by geoffw0** [comment]
Without having looked at your particular project, here are a few reasons files may not be included:
 - the particular build that's being used for LGTM does not include those files because of preprocessor directives (`#ifdef` etc).
 - the source file in question is part of a library that isn't compiled as part of the build; usually the library header files will be seen but not the sources.

**Comment by Dekken** [comment]
I don't think either of these are applicable to our case.
The import shows our library pyphare_cxx.cpython-37m-x86_64-linux-gnu.so, but has no reference of the source file "pyphare_cxx.cpp" which it comes from

Extraction
```
[2020-07-30 21:09:00] [build] [ 99%] Building CXX object src/python3/CMakeFiles/pyphare_cxx.dir/pyphare_cxx.cpp.o
[2020-07-30 21:10:40] [build] [100%] Linking CXX shared module ../../pybindlibs/pyphare_cxx.cpython-37m-x86_64-linux-gnu.so
```

Import
```
[2020-07-30 21:12:52] Importing pyphare_cxx.cpython-37m-x86_64-linux-gnu.so.trap.br for pyphare_cxx.cpython-37m-x86_64-linux-gnu.so.link (68597 of 68638)
```

This can be seen here: https://lgtm.com/projects/g/Dekken/FUR/logs/languages/lang:cpp

**Comment by geoffw0** [comment]
Hi, we've done a bit more investigation and are fairly sure this is caused by an issue in the extractor, not something you are doing wrong.  The extractor team is investigating.

**Comment by banagiri** [comment]
@geoffw0 same issue is observed, though extract section has content for cpp & python, no c++ files are extracted but python. is this issue resolved?

**Comment by nickrolfe** [comment]
Hi @banagiri - we're still working on the above problem. On what project are you seeing this issue?

**Comment by banagiri** [comment]
> Hi @banagiri - we're still working on the above problem. On what project are you seeing this issue?

Hi nickrolfe, now the cpp are appearing. i should have missed something

**Comment by Dekken** [comment]
Any chance of an update on this?

**Comment by nickrolfe** [comment]
Hi @Dekken - we've identified the problem as a segfault caused by the third-party library we use for parsing C++. We've reported the problem to the vendor and we're waiting for an update from them.

**Comment by Dekken** [comment]
Cheers @nickrolfe 
please let me know if there's something I can do to help

**Comment by igfoo** [comment]
Hi @Dekken,

Sorry for the wait; we've just pushed an update with some fixes for this, so it should work for you now. Please let us know if you still see problems.

**Comment by Dekken** [comment]
looks good!
