### ISSUE TITLE
LGTM.com - false positive for Python star imports

### ISSUE THREAD

**Issue by domdfcoding** [github/codeql#4003]
LGTM warns that `from __pkginfo__ import *` pollutes the namespace because \_\_pkginfo\_\_ does not define '\_\_all\_\_'.
However, \_\_pkginfo\_\_.py does define \_\_all\_\_, starting on line 17:

https://lgtm.com/projects/g/domdfcoding/cawdrey/latest/files/__pkginfo__.py#L17

I don't know if LGTM is thinking that `from __pkginfo__ import *` imports from a different file? If so it would be helpful if that was indicated in the warning.

The link to the alert is:
https://lgtm.com/projects/g/domdfcoding/cawdrey/snapshot/615f5f499a29690afff51e994fdeb93b09e4fee7/files/setup.py?sort=name&dir=ASC&mode=heatmap#xe0a8551b1fac31ab:1

**Comment by tausbn** [comment]
Thank you for your report. The alert will go away once the fix linked above has been merged, and the changes have gone live. This may take a few weeks.
