### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by TaaviE** [github/codeql#4006]
**Description of the false positive**

Because the case is only always false if the function is never called again. 

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/Freeyourgadget/Gadgetbridge/snapshot/bc3926285bd4e8cb49d0e8d7b0aa445fc76560e1/files/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusHandlerThread.java?sort=name&dir=ASC&mode=heatmap#xa8ea6623b879ff17:1

**Comment by aschackmull** [comment]
The code above the condition (lines 580-594) has 3 cases with two of these cases ending in `return;`. So in order for the check in line 596 to be reached we must have passed through the false-edge of line 581. So unless `mGetDaySlotsTime.add(Calendar.SECOND, CURRENT_DAY_SYNC_RETRY_PERIOD);` in line 588 can somehow change the value of `mLastSlotReceived` then this is a true positive.

**Comment by TaaviE** [comment]
You seem to be correct.
