### ISSUE TITLE
LGTM.com - false positive at "Inconsistent direction of for loop" when exit by underflow is used

### ISSUE THREAD

**Issue by v1993** [github/codeql#4018]
Unsigned integer correctly underflows to huge value, causing loop to exit as expected. I think that such exceptional case can be detected by exit condition being exactly one unit higher that initial value assigned to counter.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/citra-emu/citra/snapshot/f34cdc8c3b555bcd234728259e0969e688f21940/files/externals/libressl/crypto/curve25519/curve25519.c?sort=name&dir=ASC&mode=heatmap#x64f22fca99b3ca7d:1

**Comment by geoffw0** [comment]
Hi, thanks for raising this.

The query as written does not account for `unsigned` integers having defined wrapping behaviour.  We plan to update it with an appropriate exception.

**Comment by geoffw0** [comment]
I've created a fix for this (https://github.com/github/codeql/pull/4023).  Once the fix is merged, please allow a further two weeks (ish) before changes are reflected on LGTM.

**Comment by geoffw0** [comment]
Fixed by https://github.com/github/codeql/pull/4023.  Please allow a further two weeks (ish) for the changes to be reflected on LGTM.
