### ISSUE TITLE
LGTM.com - false positive "Declaration hides variable" for structured bindings

### ISSUE THREAD

**Issue by zhaowenlan1779** [github/codeql#4026]
**Description of the false positive**

When C++17 structured bindings are used, LGTM seems to interpret them as declarations of variables named `null`. When there are multiple structured bindings declaration, there can be false positives about variables being shadowed.

The `[` symbol (part of the syntax) is highlighted for the alert.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/zhaowenlan1779/threeSD/snapshot/e2ebd2c632f6f0ee6d309aec1290f7f188bf8f57/files/src/frontend/utilities.cpp#xb3c9c8b347f92558:1

**Comment by jbj** [comment]
Thank you for the report. I agree it's a false positive.

@igfoo Before we start working around this problem at the QL level, I want to check with you whether `(null)` is the intended name for these variables. It looks to me like the name could be an artifact of `printf("%s", s)` on a string `s` that was unintentionally null. I went looking for other variables with that name in a random snapshot and found [this use of `union`](https://github.com/mysql/mysql-server/blob/f8cdce86448a211511e8a039c62580ae16cb96f5/extra/protobuf/protobuf-3.11.4/src/google/protobuf/wire_format_lite.h#L808-L815) in MySQL that I didn't even know was possible.

I'm not sure what's the ideal name of unnamed variables, but at least for parameters we synthesize names like `p#0`, `p#1`, etc.

**Comment by igfoo** [comment]
I agree we should use a better name for this. We'll take a look, although I fear we won't get to it until closer to the end of the year.

**Comment by igfoo** [comment]
We now get the better `Variable (unnamed local variable) hides another variable of the same name (on line 179).` text for the alert.

**Comment by jbj** [comment]
Thanks for the update. I've put this issue off to the side for now as the affected query is not displayed by default and is not a security query. Pull requests will be gratefully considered, but GitHub will likely not fix this issue on our own initiative.

**Comment by MathiasVP** [comment]
Hi @zhaowenlan1779,

We have just merged a PR that improves our support for structured bindings. The change should reach LGTM.com within the next couple of weeks and the false positives _should_ be gone then then :)
