### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by rube200** [github/codeql#4033]
**In a method, the value of a variable is checked if the value is null but the warning says otherwise.**

**https://lgtm.com/projects/g/openmod/openmod/snapshot/98fe15364887559177b06cd3233bb20e8a00ce43/files/unturned/OpenMod.Unturned/Users/UnturnedUserProvider.cs?sort=name&dir=ASC&mode=heatmap#xaeea251722dc42e9:1**

**Comment by hvitved** [comment]
Thank you for reporting this. I believe this issues has already been addressed (see https://github.com/github/codeql/pull/3986 and https://github.com/github/codeql/issues/3982), but sadly the fix has not yet been deployed to LGTM.com.

**Comment by hvitved** [comment]
Fix has now been deployed.
