### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by TheRealNate** [github/codeql#4036]
**Description of the false positive**

React must always be imported into scope when using JSX, even if it isn't explicitly used

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/TheRealNate/meteor-react-native/snapshot/2a27ad9ad7c765a1b6a900fea507c9fa5d2f9e1f/files/src/components/useTracker.js?sort=name&dir=ASC&mode=heatmap#x5fbff141c2646292:1

**Comment by erik-krogh** [comment]
To expand on this:  
The identifiers specified by the `@jsx`/`@jsxFrag` pragma from [TypeScript](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-rc/#custom-jsx-factories) and [Babel](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx) are implicitly used when writing JSX.

**Comment by erik-krogh** [comment]
> React must always be imported into scope when using JSX, even if it isn't explicitly used

That is true. However, the file you are linking to does not use JSX.  

The query does check for the existence of JSX elements to see if `React` could possibly be used.  
So if you add some JSX to the file, then the alert should go away.

**Comment by TheRealNate** [comment]
I see, my mistake. Thanks for the information!
