### ISSUE TITLE
LGTM.com - false positive - Unused container - AppInspector

### ISSUE THREAD

**Issue by guyacosta** [github/codeql#4047]
**Description of the false positive**

Message: The contents of this container are never accessed.

**https://lgtm.com/projects/g/microsoft/ApplicationInspector/?mode=list**

The container is used as shown here and in the code file:
  List<string> rulePaths = new List<string>();
  if (!_options.IgnoreDefaultRules)
            {
                rulePaths.Add(Utils.GetPath(Utils.AppPath.defaultRulesPackedFile));
                rulesSet = Utils.GetDefaultRuleSet(_options.Log);
            }

            if (!string.IsNullOrEmpty(_options.CustomRulesPath))
            {
                if (rulesSet == null)
                {
                    rulesSet = new RuleSet(_options.Log);
                }

                rulePaths.Add(_options.CustomRulesPath);

**Comment by hvitved** [comment]
Hi 👋 

As far as I can see, elements are only added to `rulePaths`, and never read. This is why the query triggers an alert.

**Comment by guyacosta** [comment]
The container is passed into another object that expects is and therefore is read elsewhere.

**Comment by guyacosta** [comment]
oh wait...maybe not.  I'll review again.
