### ISSUE TITLE
LGTM.com - false positive - Unused var - AppInspector

### ISSUE THREAD

**Issue by guyacosta** [github/codeql#4048]
**Description of the false positive**

Message: string commandCompletedMsg = "Unknown";  This assignment to commandCompletedMsg is useless, since its value is never read.

This is incorrect.  See actual code file. 

**https://lgtm.com/projects/g/microsoft/ApplicationInspector/?mode=list**

**Comment by hvitved** [comment]
I don't think that is correct; as far as I can tell, all reads of `commandCompletedMsg` will read one of the other assigned values, which is why you get an alert.

**Comment by guyacosta** [comment]
yeah so the learning is don't initialize a var in c# if it's going to be overwritten in each if/else case and makes sense for performance.  old habits i.e. initialize everything to a starting state.
