### ISSUE TITLE
LGTM.com - false positive - Unused var - AppInspector

### ISSUE THREAD

**Issue by guyacosta** [github/codeql#4049]
Message: int result = 2;
This assignment to result is useless, since its value is never read.

This is incorrect.  See code file.

**https://lgtm.com/projects/g/microsoft/ApplicationInspector/?mode=list**

**Comment by hvitved** [comment]
The value is always assigned `process.ExitCode` before being read, so this is not a false positive.

**Comment by guyacosta** [comment]
got it
