### ISSUE TITLE
LGTM.com - false positive - Unused vars - AppInspector

### ISSUE THREAD

**Issue by guyacosta** [github/codeql#4050]
Message: 
bool equalTagsCompare1 = true;
--
  | This assignment to equalTagsCompare1 is useless, since its value is never read.
204 | bool equalTagsCompare2 = true;
  | This assignment to equalTagsCompare2 is useless, since its value is never read.

Both are used for conditional actions.  See code file.

**https://lgtm.com/projects/g/microsoft/ApplicationInspector/?mode=list**

**Comment by guyacosta** [comment]
There are a couple others similarly wrong...maybe my submissions could be consolidated into one issue -I leave it to you.

**Comment by hvitved** [comment]
The assignments are indeed useless, as the read of `equalTagsCompare1` is dominated by [this](https://lgtm.com/projects/g/microsoft/ApplicationInspector/snapshot/76713fbc68eaa7ef340bad44c2d4b64009bd4572/files/AppInspector/Commands/TagDiffCommand.cs?sort=name&dir=ASC&mode=heatmap#L240) other assignment, and similar the read of `equalTagsCompare2` is dominated by [this](https://lgtm.com/projects/g/microsoft/ApplicationInspector/snapshot/76713fbc68eaa7ef340bad44c2d4b64009bd4572/files/AppInspector/Commands/TagDiffCommand.cs?sort=name&dir=ASC&mode=heatmap#L243) assignment.

**Comment by guyacosta** [comment]
makes sense I wasn't understanding that it is complaining about the initial assignment -np.
