### ISSUE TITLE
cpp：Does anyone know how to write rules  to find this fault case of `malloc without null check`?

### ISSUE THREAD

**Issue by lietdai** [github/codeql#4084]
Hello, I want to find "malloc  without null check" by  Rule `cpp/ql/src/JPL_C/LOC-3/Rule 14/CheckingReturnValues.ql`

```
void  heap_mem = malloc(20);
//right case
if (heap_mem != NULL){
   use heap_mem 
}

//fault case
use heap_mem without null check

```

The CheckingReturnValues.ql cannot find  this fault `malloc` code case,
Does anyone know how to write rules  to find this fault case of `malloc without null check`?

**Comment by geoffw0** [comment]
That query (`cpp/jpl-c/checking-return-values`) is a very simple query, it just looks for function calls to a function with a return value, where the return value isn't captured by the surrounding syntax.  For example it would catch:
```
malloc(20);
```
but not
```
heap_mem = malloc(20);
```
regardless of how `heap_mem` is used afterwards.

I think you might have more luck beginning with a different query such as `cpp/inconsistent-null-check`.  You could perhaps specialize it by restricting it to `f.getName() = "malloc"` or `f instanceof AllocationFunction` and remove the statistical check (`percent >= 70`).  I haven't tried this though, let me know how you do!

**Comment by lietdai** [comment]
Amazing, it works. 
Thank you @geoffw0
