### ISSUE TITLE
Fatal error "conflicting definitions"

### ISSUE THREAD

**Issue by vsec2022** [github/codeql#4086]
Got this error when running queries suite on apache_kafka

codeql database analyze /root/Desktop/apache_kafka_5645d90/ /root/codeql-home/vscode-codeql-starter/ql/java/ql/src/codeql-suites/java-lgtm-full.qls --format=csv --output=out.csv

Running queries.
A fatal error occurred: The QL pack 'codeql-suite-helpers' which is referenced from /root/codeql-home/vscode-codeql-starter/ql/java/ql/src/codeql-suites/java-lgtm-full.qls has conflicting definitions.

**Comment by mrthankyou** [comment]
@vsec2022, Any reason why you closed this? I'm experiencing the same issue.

**Comment by hmakholm** [comment]
@mrthankyou
This problem typically arises when the CodeQL CLI cannot find your checkout of the github/codeql repo. Even if you're naming a file _within_ that repo on the command line, there are still other parts of it that need to be found by name.

The repo should be found automatically if either github/codeql or github/vscode-codeql-starter is a _sibling directory_ of the directory  you have unpacked the CLI in. It it's located somewhere else you'll need to give a `--search-path` argument either on the command line or in a `~/.config/codeql/config` file.

See https://codeql.github.com/docs/codeql-cli/getting-started-with-the-codeql-cli/ for recommendations about directory structure when unpacking `codeql`, and https://codeql.github.com/docs/codeql-cli/specifying-command-options-in-a-codeql-configuration-file/  for information about the config file.

**Comment by aibaars** [comment]
@hmakholm I think your answer is about the case where the QL pack is not on the search path. The error message (`... has conflicting definitions ...`) suggests that the QL pack `codeql-suite-helpers` was found multiple times. Or am I missing something here?

**Comment by hmakholm** [comment]
@aibaars No, you're completely right, and I didn't read the error message closely enough.

So scratch my earlier comment. The correct troubleshooting step here is to run `codeql resolve qlpacks` to find out _what_ the conflicting definitions of `codeql-suite-helpers` are. Most likely it will be because there are checkouts of both github/codeql and github/vscode-codeql-starter on the search path.
