### ISSUE TITLE
java: false positive with insecure cookie

### ISSUE THREAD

**Issue by MAHDTech** [github/codeql#4103]
***Logged on behalf of a GitHub customer.***

Hi 👋 ,

@github/advanced-security-support received the following request to review a potential false positive from the [CWE-614](https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/CWE-614/InsecureCookie.ql) query.

I am seeing this finding:

Cookie is added to response without the 'secure' flag being set.

```java
response.addCookie(createCookie(PM_COMPANY, "0", age));
```

Which is IMHO false positive because function createCookie sets flag secure

```java
private static Cookie createCookie(String name, String value, int expiry) {
    Cookie c = new Cookie(name, value);
    c.setMaxAge(expiry);
    c.setHttpOnly(true);
    c.setSecure(true);
    return c;
}
```

- [Alert as shown on LGTM.com](https://lgtm.com/projects/g/svjis/svjis/snapshot/59954bcb0cd418f46be84f56449e1d442d173fee/files/src/main/java/cz/svjis/common/PermanentLoginUtils.java?sort=name&dir=ASC&mode=heatmap#x16392eae1c2dadd9:1)
- [createCookie](https://lgtm.com/projects/g/svjis/svjis/snapshot/59954bcb0cd418f46be84f56449e1d442d173fee/files/src/main/java/cz/svjis/common/PermanentLoginUtils.java?sort=name&dir=ASC&mode=heatmap#L126)

**Comment by exceptionfactory** [comment]
This false positive issue also impacts Apache NiFi:

https://lgtm.com/projects/g/apache/nifi/snapshot/a34c3926d0615ee8d485b4d80667147d25cff612/files/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/csrf/StandardCookieCsrfTokenRepository.java?sort=name&dir=ASC&mode=heatmap#x86b98739d92b3261:1

The `StandardCookieCsrfTokenRepository.saveToken()` method calls `Cookie.setSecure()` using a static constant value named `SECURE_ENABLED` with a value of `true`, so this should not be flagged as an error.

**Comment by smowton** [comment]
That's a different and more-easily resolved FP: https://github.com/github/codeql/pull/8874
