### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by ronys** [github/codeql#4117]
**Test setup fails due to missing libcurl4-openssl-dev**

See https://github.com/pwsafe/pwsafe/runs/1015706686

- This is reap[eatable
- Build on the same environment succeeds
- Same scripts worked a few days ago.

**Comment by RasmusWL** [comment]
Hi @ronys, this doesn't seem to be a problem with CodeQL. 

It seems like the script is trying to install an older version that is not available anymore. Could you try running `apt-get update` before [`apt-get install`](https://github.com/pwsafe/pwsafe/blob/dd88342b189224caa1c5166811aa305a87127427/Misc/setup-linux-dev-env.sh#L72)?

**Comment by ronys** [comment]
Hi @RasmusWL, thanks for getting back to me.

apt-get update indeed fixed the problem. As this may be something the user in general may not be interested in doing, I've put it in as a step in the \.github\workflows\codeql-analysis.yml file. This fixed the problem.
