### ISSUE TITLE
what does fastTC predicate means?

### ISSUE THREAD

**Issue by xsser** [github/codeql#4121]
**Description of the issue**

What does fastTC predicate means?
Thanks!

**Comment by aschackmull** [comment]
It means "fast transitive closure". It is the same as writing the `+` in `someBinaryPredicate+(x, y)` to get the transitive closure of `someBinaryPredicate`. (For the sake of completeness, note that there's also `*`, which gives the reflexive, transitive closure). Explicit calls to `fastTC` is usually never necessary unless you're working on performance tuning of highly complex library code.

**Comment by xsser** [comment]
> It means "fast transitive closure". It is the same as writing the `+` in `someBinaryPredicate+(x, y)` to get the transitive closure of `someBinaryPredicate`. (For the sake of completeness, note that there's also `*`, which gives the reflexive, transitive closure). Explicit calls to `fastTC` are usually never necessary unless you're working on performance tuning of Thanks

**Comment by cL0und** [comment]
> It means "fast transitive closure". It is the same as writing the `+` in `someBinaryPredicate+(x, y)` to get the transitive closure of `someBinaryPredicate`. (For the sake of completeness, note that there's also `*`, which gives the reflexive, transitive closure). Explicit calls to `fastTC` are usually never necessary unless you're working on performance tuning of highly complex library code.

Hi, Can you tell me, what does codeql do internally when it executes the statement [fastTC(localFileValueStep/2)(n1, n2)](https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/CWE-022/ZipSlip.ql#L104)? What are the details of it? I can understand the recursive summation in the [tutorial documentation](https://help.semmle.com/QL/ql-handbook/recursion.html), but I don't quite understand what it means to recursively sum two nodes.

**Comment by aschackmull** [comment]
It's not about summation - it's about applying the predicate an arbitrary number of times (until a fixpoint is reached), it's covered in this section: https://help.semmle.com/QL/ql-handbook/recursion.html#transitive-closures.

**Comment by cL0und** [comment]
> It's not about summation - it's about applying the predicate an arbitrary number of times (until a fixpoint is reached), it's covered in this section: https://help.semmle.com/QL/ql-handbook/recursion.html#transitive-closures.

In this section we can see that it calls itself inside the code, e.g. it calls `this.getAParent().getAnAncestor()` in the predicate `getAnAncestor`. So how does `fastTC(localFileValueStep/2)(n1, n2)` work, and call `localFileValueStep` recursively in `localFileValueStep`?

**Comment by aschackmull** [comment]
The code
```
predicate localFileValueStepPlus(Node n1, Node n2) = fastTC(localFileValueStep/2)(n1, n2)
```
is equivalent to
```
predicate localFileValueStepPlus(Node n1, Node n2) { localFileValueStep+(n1, n2) }
```
which in turn is equivalent to
```
predicate localFileValueStepPlus(Node n1, Node n2) {
  localFileValueStep(n1, n2)
  or
  exists(Node mid |
    localFileValueStepPlus(n1, mid) and
    localFileValueStep(mid, n2)
  )
}
```
Note that by equivalent I mean that these 3 predicates calculate the exact same set of pairs - they may have different performance.  In general one should prefer the `localFileValueStep+(n1, n2)` version.

**Comment by cL0und** [comment]
> The code
> 
> ```
> predicate localFileValueStepPlus(Node n1, Node n2) = fastTC(localFileValueStep/2)(n1, n2)
> ```
> 
> is equivalent to
> 
> ```
> predicate localFileValueStepPlus(Node n1, Node n2) { localFileValueStep+(n1, n2) }
> ```
> 
> which in turn is equivalent to
> 
> ```
> predicate localFileValueStepPlus(Node n1, Node n2) {
>   localFileValueStep(n1, n2)
>   or
>   exists(Node mid |
>     localFileValueStepPlus(n1, mid) and
>     localFileValueStep(mid, n2)
>   )
> }
> ```
> 
> Note that by equivalent I mean that these 3 predicates calculate the exact same set of pairs - they may have different performance. In general one should prefer the `localFileValueStep+(n1, n2)` version.

Thank you for your answer.

**Comment by 18Fl** [comment]
> It's not about summation - it's about applying the predicate an arbitrary number of times (until a fixpoint is reached), it's covered in this section: https://help.semmle.com/QL/ql-handbook/recursion.html#transitive-closures.

Uhhhh! This is very useful. I could understand this fully. By the way,  When I use vscode, I can't click to FastTC implmentation. Where is it? Thank u.

**Comment by aschackmull** [comment]
> I can't click to FastTC implmentation. Where is it?

It is not open source, it's a builtin in the QL language.

**Comment by 18Fl** [comment]
Oh, Thank u very much!


Anders Schack-Mulligen ***@***.***> 于2023年8月3日周四 14:46写道：
