### ISSUE TITLE
CodeQL can't find the C++ API xmlFree from libxml2

### ISSUE THREAD

**Issue by lvtao-sec** [github/codeql#4128]
**I'm running CodeQL on libxml2, but it returns nothing when execute `from FunctionCall fc   fc.getTarget().hasName("xmlFree")`. Acctually it really has this API.**

**Comment by geoffw0** [comment]
Hi, do you know where `xmlFree` is defined or declared?

**Comment by jbj** [comment]
Is it possible that `xmlFree` is a macro rather than a function?
