### ISSUE TITLE
LGTM.com - false positive, local variable hides parameter, but only the name in declaration, not definition

### ISSUE THREAD

**Issue by zayenz** [github/codeql#4166]
In the following case, LGTM signals that a local variable hides a parameter of the same name, but there is no such parameter hidden. The declaration of the method has different names for the parameters, where the name occurs, which seems to be the reason for the false positive.

https://lgtm.com/projects/g/Gecode/gecode/snapshot/5363d23b2de103d98b33aecca7bc30f757140065/files/gecode/kernel/trace/recorder.hpp#xa27c4b3149b4d871:1

**Comment by geoffw0** [comment]
Hi, thanks for raising this.  I believe https://github.com/github/codeql/pull/4202 will fix the issue.

**Comment by geoffw0** [comment]
https://github.com/github/codeql/pull/4202 has been merged and I've confirmed that the change fixes this issue.  It may take a few weeks to reach LGTM.

**Comment by zayenz** [comment]
Thanks!
