### ISSUE TITLE
[Java] Reconsider "InefficientToArray"

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#4167]
The query [InefficientToArray](https://github.com/github/codeql/blob/main/java/ql/src/Performance/InefficientToArray.qhelp) suggests (though only with `@precision low`) that using `Collection.toArray(new T[0])` can be inefficient because it
>can cause considerable garbage collector churn

However it appears that pre-sizing the array has other disadvantages:
- In case of concurrent use the pre-sized array could be too small
- The JVM might perform the the zero length array copy more efficiently, see [Arrays of Wisdom of the Ancients](https://shipilev.net/blog/2016/arrays-wisdom-ancients/).
While that blog post is from 2016, it at least shows that there is no universal truth that one variant is more efficient than another without also considering the JVM version running it.

So is this QL query really that useful?

**Comment by aibaars** [comment]
@Marcono1234 You are right, that query makes little sense these days. The blog post you linked above is the reason why we stopped running that query by default and marked it as [`@deprecated`](https://github.com/github/codeql/blob/main/java/ql/src/Performance/InefficientToArray.ql#L8) . The query wasn't deleted at the time to avoid query configurations at customers that may refer to the query from failing. I suppose we should be able to delete the query by now.
