### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by ehuelsmann** [github/codeql#4169]
The error reported is a false positive, because the error says it's an external link. This is not the case: it's a relative link into our own project which we need to open in a new window (hence the _blank target). The scan can't see this, but the document in which this link is embedded is itself (just as the link URL) the 'erp.pl' document.

https://lgtm.com/projects/g/ledgersmb/LedgerSMB/snapshot/7a56308e925b0ac604f5da25f6f84854d7188bba/files/UI/payments/payment2.html?sort=name&dir=ASC&mode=heatmap#x6f9d0e417596aa3c:1

**Comment by erik-krogh** [comment]
Yes, you are right, that is a false positive, and I'm doing something about that.  

The part of the URL that our query notices was the `[% row.invoice.href %]` part of the URL. 
That looks like a dynamically constructed URL using some template system, and the query therefore concluded that the URL was dynamically constructed. 
However, in this case the template element of the URL was prefixed with a `?` and a `#`, both of which make it safe.
The query didn't look for that, so we got the false positive. 

Thanks for the report.

**Comment by erik-krogh** [comment]
Fixed in https://github.com/github/codeql/pull/4173. 

It can take a few weeks before the fix goes live on LGTM.
