### ISSUE TITLE
LGTM.com - false positive for assignment operator not returning *this involving comma operator

### ISSUE THREAD

**Issue by oknenavin** [github/codeql#4215]
LGTM.com issues "_Assignment operator in class range_output_iterator<char *> does not return a reference to *this._" 
for assignment operator, which in fact returns *this for all control paths.

https://lgtm.com/projects/g/oknenavin/cxon/snapshot/95a86a87dc32d08464cdb304df280116780a63ed/files/src/cxon/utility.hxx?sort=name&dir=ASC&mode=heatmap#x3d1f698895f95647:1

Edit: I found no way to add a label after I opened it (firefox), so I add it here - it's C++.

**Comment by MathiasVP** [comment]
Thanks for the report! This does indeed look like a false positive.
I've opened a fix for this in https://github.com/github/codeql/pull/4218.

**Comment by oknenavin** [comment]
thanks. when it's expected to be in effect, I still have the same alert (build from an hour ago)?

**Comment by MathiasVP** [comment]
> thanks. when it's expected to be in effect, I still have the same alert (build from an hour ago)?

It can take a few weeks before the fix goes live on LGTM.
