### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by Trott** [github/codeql#4239]
**Description of the false positive**

> Left hand side of assignment contains 4 variables, but right hand side is a tuple of length 0.

The tuple is not of length 0. It is of length 4. It is constructed dynamically with `+=` and I'm guessing codeql is missing that.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/nodejs/node/snapshot/e10efc51c683c1778e22d0f79be18071773803b1/files/configure.py#xf4643e1de1c2c4fc:1

**Comment by RasmusWL** [comment]
Hi @Trott, thanks for reporting this :+1: I agree that this is clearly a false positive. 

We're currently busy reworking large parts of the Python QL libraries, so I can't make any promises on when we'll be able to look into solving this one, but we'll keep it in our backlog :blush:
