### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by dmiller-nmap** [github/codeql#4240]
**Description of the false positive**

Rule 900075 is being detected in our Python 2 project with the message, "Keyword argument 'unicode' is not a supported parameter name of method NullTranslations.install." The keyword argument `unicode` is valid in the Python 2 version of the `gettext` library, but not in Python 3.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/nmap/nmap/snapshot/1a66fc9a8a84317ff0ddf38770fbc6789e31f621/files/zenmap/zenmapCore/I18N.py#x8d52157be3bd129e:1

**Comment by RasmusWL** [comment]
Hi @dmiller-nmap :wave: problem is that we need to pick either Python 2 or Python 3 for analysis, and in this case we `Could not guess Python version, will use default: Python 3` (from the extractor logs).

If you alter your `lgtm.yml` file to contain the following, we should analyse as Python 2 (as described [here](https://lgtm.com/help/lgtm/python-extraction#customizing-python-setup))

```yaml
extraction:
  python:
    python_setup: 
      version: 2
```

**Comment by dmiller-nmap** [comment]
@RasmusWL Thanks for the tip. We'll give that a try. If we migrate some, but not all of our code to Python 3, is there a way to specify different versions for different paths in the project?

**Comment by RasmusWL** [comment]
@dmiller-nmap we only support either Python 2 or Python 3 for a single project, so you would need to make a choice.

**Comment by dmiller-nmap** [comment]
This config worked to remove the finding. Thanks!
