### ISSUE TITLE
LGTM.com - false positive (integer negative 0)

### ISSUE THREAD

**Issue by arvidn** [github/codeql#4243]
**Description of the false positive**

negating integer 0 results in integer 0.

The analyzer seems to consider the integer val in expression `val = -val` to result in `-0`. This negative integer 0 is then considered *smaller* than 0, resulting in treating the condition `val == 0` as always false, because `val` is `-0` or smaller.

https://lgtm.com/projects/g/arvidn/libtorrent/snapshot/b9e5def6fe4855f710787c74e19123037fa5c5c3/files/src/entry.cpp?sort=name&dir=ASC&mode=heatmap#x468910299c931467:1

**Comment by geoffw0** [comment]
I believe this is a side-effect of the `float` type being used to model values in the range analysis library, resulting in [particular behaviours](https://lgtm.com/query/4062099718571698102/) being inherited.

@jbj is there somewhere we can insert a 'normalization' step that turns `-0` into `0` to prevent results like this?

**Comment by jbj** [comment]
That should be doable. We already have such a normalization predicate: https://github.com/github/codeql/blob/d60b7c729740b358e66fe4f2a2eecad9e38c107c/cpp/ql/src/semmle/code/cpp/rangeanalysis/SimpleRangeAnalysis.qll#L497-L504

I'll take a look today to see if it's easy to find the right place to call this predicate.

**Comment by jbj** [comment]
Thanks for the report, @arvidn. A fix is under way: #4252.

**Comment by jbj** [comment]
The fix has been merged and will be included in an lgtm.com deployment 1-4 weeks from now.
