### ISSUE TITLE
LGTM.com - false positive in [cpp/constant-comparison]

### ISSUE THREAD

**Issue by dmiller-nmap** [github/codeql#4249]
**Description of the false positive**

Description states "Comparison is always false because n >= 0" but `n` is returned from `Snprintf`, which gets it from `Vsnprintf()`, which gets it from `vsnprintf()` which may return a negative number in the case of an error (C++ stdio, GlibC, and MSDN docs confirm). Why does LGTM think `n` must be positive?

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/nmap/nmap/snapshot/e608b14363bf4270b11a15f043b553f1599ea5e1/files/ncat/ncat_listen.c?sort=name&dir=ASC&mode=heatmap#xe60cc1a8fde0e6f6:1

**Comment by jbj** [comment]
Thanks for the report. I believe the alert is correct even if it's rather confusing.

When `n` is a signed `int` and you check `n >= sizeof(buf)`, you're comparing a signed left-hand side to an unsigned right-hand side of a wider type. In this case, the compiler inserts a cast to make the left-hand side unsigned before comparing. If `n` is negative, it becomes a very large positive number, and so `n >= sizeof(buf)` is true and the `n < 0` check is skipped.

It would be safe to remove the `n < 0` check, but I definitely understand if you want to keep it for the sake of readers and future maintainers. As a workaround, you can make the alert go away by swapping the order of the operands to `||`.
