### ISSUE TITLE
General issue - Information regarding extracting location from external libraries in Java build

### ISSUE THREAD

**Issue by SaumoPal97** [github/codeql#4257]
I have been analyzing a Java project for which I first created a codeql database and then ran queries to find all classes and get their methods and corresponding location. However, on trying to find their location, the classes which belong to external libraries show the location as 0 for the starting line, starting column, ending line, and ending column. I wanted to know if the actual location can be derived for classes in external libraries.

**Comment by aschackmull** [comment]
To get source locations we would need to see the actual source during the build. For external libraries all we see are the `.class` files from which we extract information about types and methods, but we don't get any location information, which is why those locations show up with zeroes.

**Comment by SaumoPal97** [comment]
Thanks for the clarification.
