### ISSUE TITLE
LGTM.com - false positive in "Potentially uninitialized local variable"

### ISSUE THREAD

**Issue by olehermanse** [github/codeql#4259]
**Description of the false positive**

I think this kind of pattern is not so unusual:

```C
int res;
bool was_attempted = false;

if (...)
{
    res = SomeOperation();
    was_attempted = true;
}

if (...)
{
    res = SomeOperation();
    was_attempted = true;
}

if (was_attempted && res != 0)
{
    printf("Some error: %d\n", res);
}
```

This causes the LGTM to give a false positive alert - for all cases were `was_attempted` is true, `res` is initialized.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/cfengine/core/snapshot/1e3d1567db2ff8d470d3473ba68d27e933c1a7ae/files/libpromises/cf3parse_logic.h?sort=name&dir=ASC&mode=heatmap#x26838ee62fa30f43:1

**Comment by geoffw0** [comment]
Hi @olehermanse,

The query in question (`cpp/uninitialized-local`) has a precision of 'medium' (severity 'warning'), so a certain level of false positives are to be expected if you choose to use it.  The reason for this precision is in fact exactly the pattern you've described, which occurs quite widely - but unfortunately appears to be difficult to fix [with accuracy and sufficient generality].

I'll poke a few people to try and [re-]start a discussion about this subject.  I don't think we should expect a quick solution.

**Comment by jbj** [comment]
The cfengine project has opted in to imprecise queries by [putting `include: "*"` in their `lgtm.yml`](https://github.com/cfengine/core/blob/782c013a0b30eb84ce3cd092055200be35db691f/lgtm.yml#L14). I'm afraid that false positives are to be expected from this query, which is why it's not shown by default.
