### ISSUE TITLE
General issue - [Java] How to get MethodAccess's caller

### ISSUE THREAD

**Issue by tutorial0** [github/codeql#4274]
```java
pattern.matcher("some text").maches();
```
As the code above here, how can i get the `pattern`? I can't find any api to get the `MethodAccess`'s caller.
`getCaller` function  return the function/method that called this method/function, so doesn't fit my requirement.

**Comment by aibaars** [comment]
I think you are looking for [`MethodAccess::getQualifier`](https://help.semmle.com/qldoc/java/semmle/code/java/Expr.qll/predicate.Expr$MethodAccess$getQualifier.0.html)

In your example the qualifier of `matches()` is `pattern.matcher("some text")` and the qualifier of `matcher("some text")` is `pattern`

**Comment by tutorial0** [comment]
Yes, thanks.
