### ISSUE TITLE
LGTM doesn't remove language checks when all items have been removed

### ISSUE THREAD

**Issue by keithrfung** [github/codeql#4284]
**Description of the issue**

This is a similar issue to #3175 . The language was shifted from `C#` to `python` now the C# check runs consistently with absolutely no C# code present. 

This is in regards to this project:
https://lgtm.com/projects/g/microsoft/electionguard-web-api

**Comment by jketema** [comment]
Hi @keithrfung. Apologies for not getting back to you and thanks for your interest in LGTM.  I'm closing this issue, as LGTM has been shutdown. Please see the [blog post on LGTM's deprecation](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) for further details. More details on LGTM's replacement - Code Scanning - can be found in the [GitHub Docs for this feature](https://docs.github.com/en/code-security/code-scanning).
