### ISSUE TITLE
Java: Add TypeAccess as a child of LocalVariableDeclExpr in Print AST Query

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql#4286]
In the print AST query for Java, in `LocalVariableDeclExpr`s, the TypeAccess is being printed as a sibling node, but I believe it should be a child node since it is available from the getTypeAccess() predicate on LocalVariableDeclExpr.

<img width="1107" alt="_Extension_Development_Host__-_AbstractBag_java__read-only___read-only__—_vscode-codeql-starter__Workspace_" src="https://user-images.githubusercontent.com/363559/93488490-46494080-f8bb-11ea-90b0-2fb82a00b25e.png">

**Comment by joefarebrother** [comment]
I've found out that the reason the AST is set up the way it is, with the `TypeAccess` being a sibling node of the its `LocalVariableDeclExpr`, is because multiple `LocalVariableDeclExpr`s can share the same `TypeAccess`, such is in the following:

```java
int i = 0, j = 1;
```

**Comment by aeisenberg** [comment]
So, in this case the first `LocalVariableDeclExpr`'s type access is the same instance as that of of the second?

One of the main benefits of using the AST viewer is that you get a chance to see what the tree looks like from the perspective of the compiler and evaluator. If the `TypeAccess` is available from the `LocalVariableDeclExpr`,  but not from the `ForStmt` (or whatever the containing node is), then it seems more appropriate that the AST viewer should mimic that (even if that means the node is the same across the `LocalVariableDeclExpr`s.

**Comment by joefarebrother** [comment]
The issue is that having one `TypeAccess` be the child of two different `LocalVariableDeclExpr`s makes the AST a DAG, which the AST viewer doesn't support - it gives an error on tryng to expand one of the nodes with a duplicate child

Would a good solution be to make the `TypeAccess` a child of only the first `LocalVariableDeclExpr` in such a group?

**Comment by aeisenberg** [comment]
Ah...right. I see. We are assuming that ids are unique. So, if we duplicate a node in multiple places, we will get conflicting ids.

I don't think making the `TypeAccess` a child of only the first decl is great either. Though, it's perhaps better than the current situation. So, I would have a slight preference for trying this, but could also be convinced otherwise. 

Maybe we should hold off on making this change until we get some more experience with how the viewer is used and what people expect from it.

**Comment by joefarebrother** [comment]
Another potential option could be to add a synthetic node for the initialisers of for statements

**Comment by aeisenberg** [comment]
That sounds reasonable to me.

**Comment by joefarebrother** [comment]
There are 5 possible parents to a `LocalVariableDeclExpr`:
- `LocalVariableDeclStmt`: can have multiple `LocalVariableDeclExpr`s - makes most sense to leave it as it is, with the `TypeAccess` being a sibling to the `LocalVariablDeclExpr`s.
- `ForStmt`: can have multiple `LocalVariableDeclExpr`s - makes most sense to use a synthetic node to hold them along with their `TypeAccess`
- The others - `EnhancedForStmt`, `CatchClause`, and `InstanceOfExpr` (as part of a new JDK14 feature) - can only have one `LocalVariableDeclExpr` each. Would it be best to use keep it how it is (with the `TypeAccess` as a sibling), make the `TypeAccess` a child of the `LocalVariableDeclExpr`, or use more synthetic nodes? 

I believe the most sensible option is to leave these cases how they are.

**Comment by aeisenberg** [comment]
I think the first two bullet points make sense. 

In your last poiint, I think there's value in keeping consistency in how we display `LocalVariableDeclExpr`. If `TypeAccess` is a sibling in other cases, then it should be a sibling here as well. So, I'd lean towards having a synthetic node for the initializer here as well. It would contain the `LocalVariableDeclExpr` and `TypeAccess` as siblings.
