### ISSUE TITLE
LGTM.com - false positive: Promise returned in async function with null coalescing triggers correctness alert

### ISSUE THREAD

**Issue by d-fischer** [github/codeql#4326]
**Description of the false positive**

This shouldn't be a problem since the promise is returned further immediately.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/d-fischer/twitch/snapshot/5249a6f49264f6678324dcf6e5ad37dd95b49935/files/packages/twitch/src/ApiClient.ts?sort=name&dir=ASC&mode=heatmap#x15c45d7e044b2c9b:1

**Comment by erik-krogh** [comment]
> This shouldn't be a problem since the promise is returned further immediately.

Yes... But that is not why this is a false positive.  

The query only looked at (simplified): `provider.refresh?.() ?? null`. 
It assumed that a call to an `async` function will always return a promise, and thus the `??` would be useless (as the left hand side would always be a promise).   
What the query didn't realize was that the call was an [optional chaining with function calls](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Optional_chaining_with_function_calls), and thus the result from the call is either a promise or `null`. 

I've opened a PR to fix this.  

It will take a few weeks after the PR has been merged before the fix lands on LGTM.com
