### ISSUE TITLE
C# contextual queries (find definitions and references) are not working

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql#4351]
I'm using this project in the VS Code extension: https://lgtm.com/projects/g/JetBrains/resharper-cyclomatic-complexity

To reproduce:

1. Download the database above into VS Code
2. Open this file: `src/opt/src/src/dotnet/ReSharperPlugin.CyclomaticComplexity/ComplexityAnalysisElementProblemAnalyzer.cs`
3. Select the definition `_provider`, right click -> Go To References
4. BUG

Expected: references are found on lines 48 and 98.
Actual: no references found

Similarly, find Definition is not working:

1. Select either of the references of `_provider`
2. Right click -> Go To Definition
3. BUG

Expected: Caret is navigated to the definition
Actual: no definition found

**Comment by aeisenberg** [comment]
To be clear, I have tried multiple other locations, and I could not get find defs/refs to work for any of them in C#.

**Comment by hvitved** [comment]
This must be a bug in the VSCode specific query, as it works fine on LGTM: If I click on `_provider` [here](https://lgtm.com/projects/g/JetBrains/resharper-cyclomatic-complexity/latest/files/src/dotnet/ReSharperPlugin.CyclomaticComplexity/ComplexityAnalysisElementProblemAnalyzer.cs?sort=name&dir=ASC&mode=heatmap#L48) it works fine.

**Comment by aeisenberg** [comment]
Thanks for looking at this. Let me see what's happening.

**Comment by aeisenberg** [comment]
Ah...yes. This is an error on the VSCode end. It looks like it is not properly handling LGTM databases whose sources are unzipped. The fully qualified name it is retrieving is incorrect. Thanks for investigating. I'll close this issue.
