### ISSUE TITLE
LGTM.com - false positive: Java variable cant be null after !Strings.isNullOrEmpty check

### ISSUE THREAD

**Issue by XN137** [github/codeql#4355]
**Description of the false positive**

```
if (!Strings.isNullOrEmpty(ks) && !Strings.isNullOrEmpty(cf))
{
    String type = cf.contains(".") ? "IndexTable" : "Table";
    ...
}
````
inside the block `cf` can not be null, due to the if condition above.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/apache/cassandra/snapshot/432180c435acbf284b835addb738df1510da5909/files/src/java/org/apache/cassandra/tools/NodeProbe.java#xa4c110c51a74e3d8:1

**Comment by aschackmull** [comment]
Indeed, and thank you for the report. We currently don't model `com.google.common.base.Strings.isNullOrEmpty`, so that is why this guard currently isn't recognised.
