### ISSUE TITLE
Running CodeQL create database command on Java Repos give IOException

### ISSUE THREAD

**Issue by SaumoPal97** [github/codeql#4360]
I have been trying to run codeql create database command on a java repository using the command - codeql database create jv-db --language=java --command='mvn clean install -DskipTests'. After running for a while, it is giving the following error-

Failed to execute ODASA javac builder: java.lang.RuntimeException: IOException while executing process with args: [/Users/<user_name>/codeql-home/codeql/java/tools/macos/jdk-extractor-java/bin/java, -Dfile.encoding=UTF-8, -Xmx1024M, -Xms256M, -classpath, /Users/<user_name>/codeql-home/codeql/java/tools/semmle-extractor-java.jar, com.semmle.extractor.java.JavaExtractor, --jdk-version, -1, --javac-args, @@@/Users/<user_name>/Desktop/Experiments/<repo_name>/jv-db/log/ext/javac.args]

Since my current Mac OSX is Catalina, I followed the specific instructions given here (https://help.semmle.com/codeql/codeql-cli/procedures/get-started.html) before running the codeql create database command. My java version "1.8.0_251" and maven version Apache Maven 3.6.3. Thanks

**Comment by aibaars** [comment]
Thanks for the report. The error message doesn't provide enough information to debug this. Could you have look in the jv-db/log folder expecially the javac and extractor logs. I see you redacted the repo name. It would be great if you could provide the url if it's an open source project to help us reproduce the error locally.
