### ISSUE TITLE
The pointsTo can not find some Value in Call, such as Pool.

### ISSUE THREAD

**Issue by ZanderChang** [github/codeql#4368]
I want to use the query to find the `Value` of every arg when calling the function `tt` in `test.py`, however I can get the results of all the args without `Pool(5)`.
```
from Module m, Call c, int i, Value v
where m.getLocation().toString().matches("test%")
    and m.containsInScope(c)
    and c.getFunc().toString().matches("%tt%")
    and c.getArg(i).pointsTo(v)
select m, c.getArg(i), v, count(c.getAnArg()), v.getClass()
```
The result:
```
1	Script test.py	IntegerLiteral	int 25	5	builtin-class int
2	Script test.py	List	List	5	builtin-class list
3	Script test.py	c	c1()	5	class c1
4	Script test.py	q	deque()	5	builtin-class collections.deque
```
```py
# just for testing
import time
from multiprocessing import Pool
from collections import deque

class c1:
  def __init__(self,a,b):
    self.a = b
    self.b = b

  def sum(self):
    return self.a+self.b

  def get(self):
    return time.time()

def tt(a,b,c,d,e):
  print(c)
  print(d)

q = deque()
c = c1(1,2)
tt(25, [1,2,3], c, Pool(5), q)
```
What shuold I do to get all the args? Thx.

**Comment by tausbn** [comment]
Thank you for raising this issue.

I think the most likely culprit in this case is that the way `multiprocessing` defines its attributes is [complicated enough](https://github.com/python/cpython/blob/master/Lib/multiprocessing/__init__.py#L22) that our analysis is not able enough to determine these attributes statically.

A similar thing happens with flags for regular expressions (see [here](https://github.com/python/cpython/blob/master/Lib/re.py#L180)), and the way we addressed it in this case was to define an extension to the points-to analysis to catch exactly these flags (see [here](https://github.com/github/codeql/blob/main/python/ql/src/semmle/python/types/Extensions.qll#L130)). I imagine a similar approach would be needed in this case.

Unfortunately, we're currently doing a large rewrite of the Python QL libraries, and so it may be a while before we address this issue. In the mean time, my best suggestion would be to see if you could work around this problem by approaching it more syntactically. This may be less precise, depending on the names of the classes involved, but it might be good enough for your purposes.

**Comment by ZanderChang** [comment]
Thx a lot for replying !
