### ISSUE TITLE
LGTM.com - false positive: js/unsafe-external-link for Flask url_for

### ISSUE THREAD

**Issue by ThiefMaster** [github/codeql#4387]
**Description of the false positive**

Flask applications use `{{ url_for(...) }}` to build internal URLs. These URLs always point to the application itself, so the `js/unsafe-external-link`

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/indico/indico/snapshot/6644fcefc7e4f3246091ae037234b15b7c281f31/files/indico/modules/events/abstracts/templates/reviewing/public.html?sort=name&dir=ASC&mode=heatmap#x615eaec2d2786aa5:1

**Comment by erik-krogh** [comment]
Yep, that is a false positive. 

I just merged a pull request that should fix the issue.  
The fix should appear on LGTM.com within a few weeks.

**Comment by ThiefMaster** [comment]
Thanks! I had initially tested it on the new GitHub/codeql integration - will the fix arrive there at the same time?

**Comment by erik-krogh** [comment]
The fix should arrive there at about the same time. Not necessarily the exact same time.
