### ISSUE TITLE
LGTM.com - false positive | Unused import

### ISSUE THREAD

**Issue by Gusted** [github/codeql#4409]
**Description of the false positive**

The alert states it says `import {m} from 'malevic';` is a unused import, 
however this is our jsxFactory, stated in the [tsconfig.json](https://github.com/darkreader/darkreader/blob/master/src/tsconfig.json#L19) So the code wouldn't add `m([HTML tags])` to the code, however LGTM states it's a unused import(which seems to be) but it's importing it so Typescript recognize the HTML tags and don't need to wrap it into `m()` function.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/darkreader/darkreader/snapshot/a04705a3fa8ffb401ca7921ca202c1f0b52b18ba/files/src/ui/popup/settings-page/change-browser-theme.tsx#xfdd22f26d8b2a52:1

**Comment by erik-krogh** [comment]
Yep, you're right, that is a false positive. 

I recently added support for TypeScript 4.0, and in doing that I apparently overlooked that I needed to support the new `jsxFactory` option in the unused-import query.      

I just opened a pull request that should fix this issue.   
The fix should appear on LGTM.com within a few weeks of merging the pull request.
