### ISSUE TITLE
How to show additionalTaintStep in PathGraph

### ISSUE THREAD

**Issue by kingkaki** [github/codeql#4410]
Hi buddy:

I have encountered some problems in using codeql.
java vulnerability code(spring boot application)
```codeql
    @GetMapping("/codeinject/test")
    public String test(String filepath) throws IOException {
        StringBuilder sb  = new StringBuilder();
        sb.append(filepath);
        sb.append("Test");
        String filterFilePath = sb.toString();
        String[] cmdList = new String[]{"sh", "-c", "ls -la " + filterFilePath};
        ProcessBuilder builder = new ProcessBuilder(cmdList);
        builder.redirectErrorStream(true);
        Process process = builder.start();
        return WebUtils.convertStreamToString(process.getInputStream());
    }
```
codeql taint analyze
```codeql
/**
 * @kind path-problem
 */

import java
import semmle.code.java.dataflow.TaintTracking
import DataFlow::PathGraph
import semmle.code.java.frameworks.spring.SpringController

class RequestMapping extends Callable {
  RequestMapping() { this instanceof SpringRequestMappingMethod }
}

class ProcessBuilderCommandMethod extends Constructor {
  ProcessBuilderCommandMethod() {
    this.getDeclaringType().hasQualifiedName("java.lang", "ProcessBuilder")
  }
}

class SpringTaintAnalyzer extends TaintTracking::Configuration {
  SpringTaintAnalyzer() { this = "spring taint analyzer" }

  override predicate isSource(DataFlow::Node node) {
    exists(RequestMapping source | source.getAParameter() = node.asParameter())
  }

  override predicate isSink(DataFlow::Node node) {
    exists(ProcessBuilderCommandMethod sink, Call call |
      call.getCallee() = sink and
      call.getAnArgument() = node.asExpr()
    )
  }
}

from DataFlow::PathNode source, DataFlow::PathNode sink, SpringTaintAnalyzer config
where
  config.hasFlowPath(source, sink) and
  source.getNode().asParameter().getCallable().getName() = "test"
select source.getNode(), source, sink, sink.getNode()
```
It can work and run well,and PathGraph will output the following path.
![image](https://user-images.githubusercontent.com/30930379/95167949-17036080-07e3-11eb-9864-ab22c5b77db8.png)
but here seems to only show the pathnode of sink and source(also some function jump nodes)
In my opinion, there should be the following five nodes
- test(String filepath)
- sb.append(filepath);
- String filterFilePath = sb.toString();
- String[] cmdList = new String[]{"sh", "-c", "ls -la " + filterFilePath};
- new ProcessBuilder(cmdList);
like StringBuilder.append() StringBuilder.toString() and String array initialization these operations are all defined in the defaultAdditionalTaintStep of TaintTrackingImpl.
Is there any way to display these additionalTaintStep nodes in PathGraph?

Thank you!

**Comment by aschackmull** [comment]
This is intentional. The generated paths compress some local steps, so you only see some of the nodes along the paths. There are two main reasons for this choice: The analysis can be calculated faster and we avoid overwhelming the viewer with a huge number of in-between steps. We try to choose the nodes to show such that the path is still clear and the important nodes still are included. Indeed, you also excluded some steps that you found to be irrelevant when you listed the steps you expected to see, as the actual full path contains 11(!) nodes.

**Comment by intrigus-lgtm** [comment]
Is there any way to view the actual full path?

**Comment by kingkaki** [comment]
Is there any way to see the complete path, to display the node of isAdditionalFlowStep?
Otherwise, when there are too many additionalTaintSteps in one function, it will be inconvenient to view.

**Comment by aschackmull** [comment]
In debug mode when viewing partial paths then you'll see everything. You can enable flow exploration by overriding `int explorationLimit()` on the `Configuration` and using the predicate `Configuration::hasPartialFlow`. Be sure to read the qldoc on `hasPartialFlow`:
```
  /**
   * Holds if there is a partial data flow path from `source` to `node`. The
   * approximate distance between `node` and the closest source is `dist` and
   * is restricted to be less than or equal to `explorationLimit()`. This
   * predicate completely disregards sink definitions.
   *
   * This predicate is intended for dataflow exploration and debugging and may
   * perform poorly if the number of sources is too big and/or the exploration
   * limit is set too high without using barriers.
   *
   * This predicate is disabled (has no results) by default. Override
   * `explorationLimit()` with a suitable number to enable this predicate.
   *
   * To use this in a `path-problem` query, import the module `PartialPathGraph`.
   */
  final predicate hasPartialFlow(PartialPathNode source, PartialPathNode node, int dist) {
```

**Comment by kingkaki** [comment]
Thanks!This is exactly what i want.
