### ISSUE TITLE
How to distinguish unique Node

### ISSUE THREAD

**Issue by kingkaki** [github/codeql#4491]
Take StoredXss.js in CWE-079 as an example.
```js
var express = require('express'),
    fs = require('fs');

express().get('/list-directory', function(req, res) {
    fs.readdir('/public', function (error, fileNames) {
        var list = '<ul>';
        fileNames.forEach(fileName => {
            // BAD: `fileName` can contain HTML elements
            list += '<li>' + fileName + '</li>';
        });
        list += '</ul>'
        res.send(list);
    });
});
```
I tried to select all nodes named `fileNames`, 
and formed a unique id based on the file path, line number, column number and variable name.
```codeql
import javascript

string getIdentity(DataFlow::Node node) {
  result =
    node.getFile().getRelativePath() + ":" + node.getStartLine() + ":" + node.getStartColumn() + "-"
      + node.getEndColumn() + ":" + node.toString() 
}

from DataFlow::Node node
where
  node.getFile().getRelativePath() = "examples/StoredXss.js" and
  node.toString() = "fileNames" 
select node, getIdentity(node)
```
The results of its selection are as follows. 
![image](https://user-images.githubusercontent.com/30930379/96243931-feabf680-0fd7-11eb-9c24-2eb7ae03f3e6.png)
Although I know that the first two nodes are two different objects in memory, 
the Identity results are the same, which makes me unable to distinguish the two nodes.
How do I distinguish between these two nodes?

Or not limited to javascript, is there a general way to distinguish these nodes(similar to Object.hashCode of Java)?

**Comment by intrigus-lgtm** [comment]
What are actually trying to do?
I.e. why do you want to distinguish nodes?

**Comment by erik-krogh** [comment]
There is no general way to distinguish such nodes.  

However, in this case you can distinguish the two.  
One node is a `DataFlow::ParameterNode`, and the other node is a `DataFlow::SsaDefinitionNode`.   
So you can use an `instanceof` check to see which is which (e.g. `node instanceof DataFlow::SsaDefinitionNode`).

**Comment by kingkaki** [comment]
Okay, thanks.
First of all, I am curious, I want to know the difference between these nodes.
Secondly, I am trying to construct a path graph by myself through the results of edges, nodes and select query (not through vscode), but the results of cli output are all presented in the form of strings, so I want to distinguish the unique node through some information.
