### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by don-tay** [github/codeql#4504]
The alert is triggered when a non-template literal is passed as a string type argument as a database query argument. This is an expected feature of a database connection instance initialised by the library `pg-promise`, as they have an underlying query formatting engine that resolves these string literals for the purpose of preventing SQL injection attacks. 

The `pg-promise` query formatting documentation can be found here: https://lgtm.com/projects/g/Project-Kampong/kampong-backend/snapshot/567a204a23ed3addba2d1062cd9b1993091a9011/files/src/controllers/listingSkills.ts?sort=name&dir=ASC&mode=heatmap#x229cde5c5dd061ae:1

Alert link:
https://lgtm.com/projects/g/Project-Kampong/kampong-backend/snapshot/567a204a23ed3addba2d1062cd9b1993091a9011/files/src/controllers/listingSkills.ts?sort=name&dir=ASC&mode=heatmap#x229cde5c5dd061ae:1

**Comment by erik-krogh** [comment]
Yep, that is a false positive. 

We try to recognize when there exists an object supplying the variables used in a "template-like" string.  
In your case that would be the [`data`](https://lgtm.com/projects/g/Project-Kampong/kampong-backend/snapshot/567a204a23ed3addba2d1062cd9b1993091a9011/files/src/controllers/listingSkills.ts?sort=name&dir=ASC&mode=heatmap#L55) object.    
However, the query doesn't currently recognize that `data` supplies the variables for the "template-like" string. 

I'll generalize the query a bit such that it will be better at recognizing these object, which will fix this false positive.

**Comment by erik-krogh** [comment]
The PR fixing this issue has been merged.  

It might still take a few weeks for the fix to appear on LGTM.com
