### ISSUE TITLE
LGTM.com - false positive (logical assignment)

### ISSUE THREAD

**Issue by DuncanMacWeb** [github/codeql#4510]
**Description of the false positive**

The expression `identified.type ||= "unknown";` causes the alert `This expression will be implicitly converted from string to number.` to be raised.

This alert shouldn’t be included as both operands are strings, so there is no implicit conversion to number. (If this is not correct, then perhaps an additional text could be helpful to explain how this could result in implicit type coercion.)

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/ClaudiuCeia/detect-translation/rev/pr-253511d59258a56ef045753f2141eb8d17f7ffcb

**Comment by erik-krogh** [comment]
Thanks for the report.  

Yep that is a false positive.   
The query was unaware of how the new ES2021 operators `||=`/`&&=`/`??=` behaved.   

I've opened https://github.com/github/codeql/pull/4517 which will fix the false positive. 
It will take a few weeks after the pull request has been fixed for the change to appear on LGTM.com.

**Comment by DuncanMacWeb** [comment]
Thanks @erik-krogh, appreciate that!
