### ISSUE TITLE
LGTM.com - suppression comment not working

### ISSUE THREAD

**Issue by DuncanMacWeb** [github/codeql#4511]
**Description of the issue**

The alert described in #4510 is not suppressed, even though the line ends with `// lgtm [js/implicit-operand-conversion]`:
<img width="1215" alt="lgtm  js implicit-operand-conversion  not working" src="https://user-images.githubusercontent.com/593122/96478488-a4a56e00-122f-11eb-927a-ccbee854b7d5.png">

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/ClaudiuCeia/detect-translation/rev/pr-253511d59258a56ef045753f2141eb8d17f7ffcb

**Comment by intrigus-lgtm** [comment]
"If you make changes to the suppression of alerts in a pull request, please note that these changes will only be effective once that pull request is merged."

**Comment by DuncanMacWeb** [comment]
Ah, thank you @intrigus-lgtm. Closing.

**Comment by Sv443** [comment]
> "If you make changes to the suppression of alerts in a pull request, please note that these changes will only be effective once that pull request is merged."

I'm sorry but that's just stupid behavior. If LGTM checks a pull request it shouldn't throw alerts based on the master branch. My PRs are getting spammed by the LGTM bot and it's getting extremely annoying.
