### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by DanBloomberg** [github/codeql#4547]
There are 4 lgtm parser errors in the url below, which is from the attached file.

I have simplified the logic to demonstrate the error:

   f1(char *str) {
        int a, b, c;
        b = f2(str);  // some function that returns an int
        a = 0;
        if (b == 1)
            a = f3(str);  // another function that returns an int
        if (b != 1 || a == 5)  // complains that (a == 5) is known to be false
            c = 0;
    }

    This is incorrect.  The parser is apparently interpreting the last if statement as:
        if (b != 1 && a == 5)

The actual code is in the function l_generateFlateDataPdf() in the attached file, pdfio2.c, 

I have modified the code in the file pdfio2.c so that the parser should no longer fail,
but I figure you would like to know about it  :-)

https://lgtm.com/projects/g/DanBloomberg/leptonica/snapshot/92a0dce6c3a8b826653dff735a48319888461c17/files/src/pdfio2.c?sort=name&dir=ASC&mode=heatmap#xcd7eda16a957c9b8:1
 
[pdfio2.c.gz](https://github.com/github/codeql/files/5434231/pdfio2.c.gz)

Regards,

Dan

**Comment by geoffw0** [comment]
Hi,

It looks `bps` and `spp` are always zero at the line you link to, so it's correct that the comparisons `bps == 1` etc are always false.  Note that none of the results refer to the entire condition `(format != IFF_PNG || interlaced || bps == 1 || spp == 4 || spp == 2)`, which could indeed be true if `format != IFF_PNG`.

Nevertheless thank you for raising this, I'm considering changing the phrasing of the message to be clearer about this.  And please let us know if you have any further concerns.

**Comment by DanBloomberg** [comment]
They're not always zero.  They're initialized to zero, and if the format is PNG they can be changed.

Here's the conditional as it was:
   if (format != IFF_PNG || interlaced || bps == 1 || spp == 4 || spp == 2) 

It's admittedly a little confusing, so I rewrote it with identical logic but in a redundant form that is
more like how one would describe it verbally:
   if (format != IFF_PNG ||
       (format == IFF_PNG && (interlaced || bps == 1 || spp == 4 || spp == 2)))

Does your parser still have trouble with the new version?

Dan

**Comment by geoffw0** [comment]
Where can they be given a non-zero value?  The implementation of `readHeaderPng` appears to be roughly equivalent of `return 1` ("function not present"), and doesn't write to it's input parameters.  Is there a different body for that function in a different build configuration perhaps?

**Comment by DanBloomberg** [comment]
Yes, there are two source files:
     pngio.c    (if the png library is available for linking)
     pngiostub.c    (if it is not)

When linking the stub library, as you said, readHeaderPng() does nothing.

Virtually all uses of leptonica have libpng, libjpeg and libtiff linked, because these are the major image compression formats in use.  The lgtm parser is apparently running in a non-standard configuration that assumes the external libraries are not linked.

**Comment by geoffw0** [comment]
Hi,

We recommend setting up an lgtm.yml file to configure your build for LGTM to more typical settings.  See https://lgtm.com/help/lgtm/configuring-lgtm-analysis-project, and in particular https://lgtm.com/help/lgtm/cpp-extraction.  This will require good understanding of the leptonica build process.  Doing so should allow QL to see (amongst other things) that `readHeaderPng` does not simply `return 1`, which I believe will improve the quality of your results.

The lgtm.yml file also allows you to control other behaviours of LGTM, such as which queries are displayed in the interface.

Happy to answer any further questions.

**Comment by DanBloomberg** [comment]
Unfortunately, I'm not familiar with the yml configuration files.
From what we've discussed, it seems that we only need to add these 3 external libraries
   libtiff
   libpng
   libjpeg
to the runtime environment that lgtm expects for leptonica.   (Also libz, but that's likely already included).

The only yml file in leptonica is for appveyor on github (building in windows).  It appears to use curl to
bring in the needed libraries.  I have attached it.
[appveyor.yml.gz](https://github.com/github/codeql/files/5454263/appveyor.yml.gz)

Dan

**Comment by jbj** [comment]
From the build logs, https://lgtm.com/projects/g/DanBloomberg/leptonica/logs/languages/lang:cpp, it looks to me like it's finding all the libraries it needs. LGTM will auto-install packages during the build, and this seems to work:

```
[2020-11-04 09:57:32] [build] -- Found GIF: /usr/lib/x86_64-linux-gnu/libgif.so (found version "5.1.4") 
[2020-11-04 09:57:32] [build] -- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
[2020-11-04 09:57:32] [build] -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
[2020-11-04 09:57:32] [build] -- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
[2020-11-04 09:57:32] [build] -- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.10") 
```

Even though the build system is finding these libraries, it's still building and linking the `pngiostub.c` file. From the logs, further down:

```
[2020-11-04 09:58:54] [build] [ 67%] Building C object src/CMakeFiles/leptonica.dir/pngiostub.c.o
...
/usr/bin/ar qc libleptonica.a  ... CMakeFiles/leptonica.dir/pngio.c.o CMakeFiles/leptonica.dir/pngiostub.c.o ...
```

Does something happen at link time or run time to make the final binary use the non-stub PNG library even though the stub is compiled in?

**Comment by DanBloomberg** [comment]
No, it all happens in the library at compile time.
For example, look at pngio.c and pngiostub.c.
The code in pngio.c is included if the variable HAVE_LIBPNG is defined:
```
/* --------------------------------------------*/
#if  HAVE_LIBPNG   /* defined in environ.h */
/* --------------------------------------------*/
```
whereas if it is not defined, the code in pngiostub.c is included:
```
/* --------------------------------------------*/
#if  !HAVE_LIBPNG   /* defined in environ.h */
/* --------------------------------------------*/
```
So you need to make sure that these are defined.
Looking at CMakeLists.txt in the root directory of leptonica on github, there is a section SW_BUILD=ON where these variables are defined:
```
add_definitions(
        -DHAVE_LIBGIF=1
        -DHAVE_LIBJPEG=1
        -DHAVE_LIBPNG=1
        -DHAVE_LIBTIFF=1
        -DHAVE_LIBWEBP=1
        -DHAVE_LIBWEBP_ANIM=1
        -DHAVE_LIBZ=1

        -DHAVE_LIBJP2K=1
        -DLIBJP2K_HEADER="openjpeg.h"
    )
```
Does that help?

Dan

**Comment by jbj** [comment]
I tried to debug this, but I found that the problem was no longer there in the latest version. I'd missed your remark on the original bug report:
> I have modified the code in the file pdfio2.c so that the parser should no longer fail

But that's not all. Something has clearly changed around the conditional compilation in the stub file between the problematic version and the current version. Compare LGTM's view of `pngiostub.c` [in the problematic version](https://lgtm.com/projects/g/DanBloomberg/leptonica/snapshot/92a0dce6c3a8b826653dff735a48319888461c17/files/src/pngiostub.c) and [in the latest version](https://lgtm.com/projects/g/DanBloomberg/leptonica/snapshot/a0f52837e5cec7d107e5965907e72297ffa43ac6/files/src/pngiostub.c). The problematic version has clickable links inside the `#if` block because that code path was taken during compilation, while the latest version doesn't. That means when building the latest version of leptonica we're not seeing the stub code at all, which is what we want.

My guess is that you can remove [the workaround](https://github.com/DanBloomberg/leptonica/commit/091ee190146b8caf5112165add220b7e7ee80311), and the false positive will not come back.

**Comment by DanBloomberg** [comment]
Excellent.  Thank you for the investigation and resolution.

I like the workaround, but will remove the comment about your parser, which is no longer valid.
