### ISSUE TITLE
General issue - Files excluded from codeql database if lombok java library is used for getters and setters functionality

### ISSUE THREAD

**Issue by SaumoPal97** [github/codeql#4555]
I have been building codeql databases for multiple projects and in some of them I found that the src.zip file inside codeql database doesn't contain files that utilize lombok library for getters and setters. On further checking, I realised that while the files are missing from codeql database, their classes and methods can be fetched, but on doing so, their start line, start column, end line and end column all have value 0, so they are getting treated as external libraries, with no AST or DFG created for them. Just to help understand the issue, please build the codeql database for this - https://github.com/ayonious/lombok-examples, and you can check inside src.zip of the created codeql database that the representation doesn't contain `lombok-examples/src/main/java/com/ayon/lombok`. But if you try running a query to find all classes and their locations, the excluded files inside `lombok-examples/src/main/java/com/ayon/lombok`will be shown with their start and end locations as 0.

**Comment by aschackmull** [comment]
This is intentional. Lombok isn't currently supported. I know that others have had success with using delombok to work around this.

**Comment by SaumoPal97** [comment]
Thank you, will be checking out delombok. Closing the issue

**Comment by XuCcc** [comment]
fix it now?

**Comment by Marcono1234** [comment]
For any future readers, the delombok workaround is described in https://github.com/github/codeql/issues/4984#issuecomment-763440211.
