### ISSUE TITLE
LGTM.com - false positive unused-local-variable with lambda captures

### ISSUE THREAD

**Issue by DanySpin97** [github/codeql#4569]
**Description of the false positive**

When a local variable is only used in a lambda capture list, LGTM reports it as unused.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/DanySpin97/tt/snapshot/651a6ea6b29491f05ac2aba61bbc42ef99af5780/files/src/cli/command/service_control_command.cpp?sort=name&dir=ASC&mode=heatmap#x75cc5370152ac03e:1

**Comment by geoffw0** [comment]
Thanks for this report - a workaround (https://github.com/github/codeql/pull/4592) is on the way and there may be a more accurate fix later on.

**Comment by geoffw0** [comment]
The above fix has been merged and should get rid of this false positive (may take a few weeks to reach LGTM).
