### ISSUE TITLE
LGTM.com - false positive variable used in if condition results in unused-local-variable

### ISSUE THREAD

**Issue by DanySpin97** [github/codeql#4570]
**Description of the false positive**

When a local variable in only used inside an if condition, it is reported as unused. Might be related to the if statement with initializer.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/DanySpin97/tt/snapshot/651a6ea6b29491f05ac2aba61bbc42ef99af5780/files/src/cli/command/parse_command.cpp?sort=name&dir=ASC&mode=heatmap#x563d5b8a06b14665:1

**Comment by geoffw0** [comment]
Thanks for this report - a workaround (https://github.com/github/codeql/pull/4592) is on the way and there may be a more accurate fix later on.

**Comment by geoffw0** [comment]
The above fix has been merged and should get rid of this false positive (may take a few weeks to reach LGTM).
