### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by flanglet** [github/codeql#4587]
**Description of the false positive**
'This definition of v3 is never used' when v3 is used on the next line.
2 matches in the same file.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/flanglet/kanzi-go/snapshot/accab25ea15c3ec306e9e71ff9ffbbd156a220fc/files/transform/DivSufSort.go?sort=name&dir=ASC&mode=heatmap#x527a316ebc009b12:1

**Comment by smowton** [comment]
Thanks for the report -- this is fixed by https://github.com/github/codeql-go/pull/393

**Comment by smowton** [comment]
Fix merged into codeql-go/main.
