### ISSUE TITLE
PrintAST and contextual queries use incorrect getEncodedFile for windows paths

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql#4621]
In all of the `external string selectedSourceFile();` for contextual queries, references for windows paths are not created properly. All paths must begin with a `/`. The reason is that this path represents a piece of a uri (even though special characters like spaces are _not_ encoded) and must always have a slash at the front.

Currently, paths inside of a database's `src.zip` file for dbs created on windows look like this:

```/C_/databases/my-database/my-file.cpp```

and the original path looks like this:

```C:\databases\my-database\my-file.cpp```

The problem is that inside of the extension, there is no way to determine if `C_` is an encoded drive name on windows, or a directory name from a linux-like system.

The extension, therefore passes the path with the leading `/` to the contextual query and the contextual query does not recognize it as a path to any file in the database.

One example is here: https://github.com/github/codeql/blob/89a808cafeb86459bf6de32c0fae168d7de30b65/cpp/ql/src/definitions.qll#L217

One proposed solution is to move `getEncodedFile` to a shared location and fix it once. All language libraries would use the same implementation. Though, this would not work for `go` or `ruby`.

Originally reported by @nickrolfe

**Comment by aeisenberg** [comment]
To be clear, this is an issue for all supported languages. This _used_ to work because we were being sloppy with our URI handling in the extension. Once we fixed that in v1.3.6 of the extension, the resulting print ast queries have broken for windows-created databases.

**Comment by nickrolfe** [comment]
- [ ] C++, C#, JS, Java, Python: https://github.com/github/codeql/pull/4643
- [ ] Ruby - TODO once above has been agreed on and merged
- [ ] Go - TODO once above has been agreed on and merged

**Comment by aeisenberg** [comment]
Thanks guys Jing this on!

**Comment by aeisenberg** [comment]
Thanks for taking this on!

**Comment by nickrolfe** [comment]
All languages have fixes merged.
