### ISSUE TITLE
Will a JavaScript method that is never called analyzed?

### ISSUE THREAD

**Issue by izgzhen** [github/codeql#4635]
Specifically, I wrote an example and wrapped all code inside a function that is never used: https://github.com/izgzhen/CodeQL-Labs/blob/dead/tutorials/js_dataflow/src/main.js

However, when I executed [the query](https://github.com/izgzhen/CodeQL-Labs/blob/dead/tutorials/js_dataflow/example_local.ql), I can still see the outputs:

```
Evaluation completed (3.4s).
|       readFile       |       source        |
+----------------------+---------------------+
| readFil ... b.js"))  | require("./lib.js") |
| fs.read ... );\n  }) | p                   |
| fs.read ... );\n  }) | path.resolve(p)     |
| fs.read ... );\n  }) | p                   |
```

**Comment by erik-krogh** [comment]
Yes. Code that is never executed is still analyzed. 

This is a deliberate choice for multiple reasons, some of which include. 
- It is not possible in general to determine what code is and is not used (although in your exact case it would be easy). 
- Code like that is sometimes used by a preprocessor that modifies the code in some way such that the code is executed. 
- Even if the code is never executed: If the code contains some bug, then that code buggy code is just waiting to be used, and it is better to fix the bug early.

**Comment by izgzhen** [comment]
I see. That makes sense! Thanks!
