### ISSUE TITLE
General issue: Create a function to return dataflow source

### ISSUE THREAD

**Issue by SaumoPal97** [github/codeql#4636]
I want to create a function that takes in a sink and returns a source, so that I can recursively fetch all sources for sinks and their child expressions. Most of the example implementations I found on Github declared classes and predicates which finally returns source and sink via select statement but I couldn't find one that implements the above logic. The barebones code looks something like this
`Expr getAllSources(DataFlow::Node sink) {
        result = sink.asExpr().getParent*().(Expr).getAChildExpr*()
        or
        result = getAllSources(getSingleSource(
            DataFlow::exprNode(sink.asExpr().getParent*().(Expr).getAChildExpr*())
        ))
    }`
I would like to create a function `getSingleSource()` which takes in a sink node and returns a source node 
`DataFlow::Node getSingleSource(DataFlow::Node sink) { ...need help here....}`
I would be glad if someone could point out resources or suggest some help with this.

**Comment by SaumoPal97** [comment]
So I worked on it for a bit and came up with this implementation of `getSingleSource` :
`DataFlow::Node getSingleSource(DataFlow::Node sink, DataFlow::Node source, UrlFetcher config) {
        config.hasFlow(source, sink) and result = source
    }`
such that the final code is:


    Expr getAllSources(DataFlow::Node sink) {
        result = sink.asExpr().getParent*().(Expr).getAChildExpr*()
        or
        result = getAllSources(getSingleSource(
            DataFlow::exprNode(sink.asExpr().getParent*().(Expr).getAChildExpr*()), _, _
        ))
    }

    from UrlInitializer config, DataFlow::Node source, DataFlow::Node sink, Expr E
    where config.hasFlow(source, sink)
    and E = getAllSources(sink)
    select E, E.getLocation(), E.getCompilationUnit()

where UrlInitializer is another dataflow from where I get the sink, and recursively find all sources for such sinks and their child expressions which inturn is passed on as new sinks. The code is syntactically correct, but on running the last 3 lines, that is, fetching the results from the recursion, I do not get any results for #select in vscode, but I do get nodes and edges. That leads me to think the above definition is incorrect. Please let me know if the above seems correct/any help is appreciated.

**Comment by smowton** [comment]
```codeql
DataFlow::Node getSingleSource(DataFlow::Node sink, DataFlow::Node source, UrlFetcher config) { config.hasFlow(source, sink) and result = source }
``` 

can become

```codeql
DataFlow::Node getASource(DataFlow::Node sink, UrlFetcher config) { config.hasFlow(result, sink) }
```

Note the name `getASource` because there can be more than one path that leads to the same `DataFlow::Sink`, so there may be more than one match even if all parameters are single-valued.

`getAllSources` could usefully be split into two pieces. `sink.asExpr().getParent*().(Expr).getAChildExpr*()` could probably be expressed better but I'm not completely clear what you're looking for there, so for now I'll just call that `getARelatedExpr(Expr e)`, then we can define

```codeql
DataFlow::Node getASourceRelative(DataFlow::Node sink) {
  result.asExpr() = getARelatedExpr(getASource(sink).asExpr())
```

Then finally following this chain of source -> sink -> related -> source -> sink -> related ... can be done using the `*` operator:

```codeql
DataFlow::Node getAConnectedSource(DataFlow::Node sink) {
  result = getASourceRelative*(sink)
```

That means calling `getARelatedSource` zero or more times until there are no more sources to discover.

At this point the question of why some particular expression doesn't match when you expect it to can be investigated using Quick Evaluate: start by checking if plain old `getASource` does what you expect? If not, the problem lies with your dataflow config. Otherwise, does `getARelatedSource` do what you'd expect? And so on, up the function tree.

Could you say what `sink.asExpr().getParent*().(Expr).getAChildExpr*()` is supposed to achieve, with some examples? That will enable further clarification -- we might be able to write a dataflow config that gets all the way from start to finish, without having to post-hoc stitch them together using `getARelatedExpr`.

(Admin note: other maintainers might come by shortly to suggest a better forum for this sort of query, in which case I'll follow up there)

**Comment by SaumoPal97** [comment]
@smowton thanks for the improvements, the recursion is working now. As for why I used something like `sink.asExpr().getParent*().(Expr).getAChildExpr*()`, I do need some insights from your part which can help me improve my dataflow config as well. 

I want to find the dataflow from a restTemplate function `exchange()` which is used to call an external api to a variable containing the url string for the api call. So the `exchange()` function takes the first argument as the api url. So for the following code snippet, 

        UriComponentsBuilder builder = UriComponentsBuilder.fromUriString(prop.getCrmLeadsUrl());
        UriComponents components = builder.buildAndExpand(uriParams);
        ResponseEntity<Void> responseEntity = restTemplate.exchange(components.toUriString(), HttpMethod.POST, request, Void.class);

if I use a dataflow config(TaintTracking) where source is any `Expr` and sink is the first argument of the `exchange()` function, then I am only able to get `.toUriString()` as source. So instead of just taking the first argument of the `exchange()` function, if I take the first argument and its child expressions as well, I am able to reach `.buildAndExpand(...)` through `components` as sink but I am unable to reach `builder`. Therefore for every new source, I apply `sink.asExpr().getParent*().(Expr).getAChildExpr*()` where the new sink = the previous source for the recursive dataflow and then for each child expression, I apply the dataflow config. The pros are definitely not missing out any result but the cons are getting too many results. 
(The reason I would like to reach `builder` is because using that as sink, I would be able to reach `fromUriString()` whose child expressions can then be reached and hence `getCrmLeadsUrl()` can be reached which returns the variable containing the api url string, which is what I want to achieve)
 
Similar example can also be found here (https://help.semmle.com/QL/ql-training/java/global-data-flow-java.html#8), where dataflow can help reach` .getNamespace() `but not `ai`. So any recommendation on how I can define my dataflow config to achieve the same will be beneficial.

My current definitions of the two dataflow configs are:
1. To fetch source where sink is first argument of `exchange()`:
```
class UrlSourceInitializer extends TaintTracking::Configuration {
    UrlSourceInitializer() { this = "UrlSourceInitializer" }
      override predicate isSource(DataFlow::Node source) {
        exists(Expr E |
          source.asExpr() = E
        )
      }
      override predicate isSink(DataFlow::Node sink) {
        exists(MethodAccess call |
          call.getMethod() instanceof RestTemplateMethod and
          (not call.getLocation().getFile() instanceof TestFile) and
          sink.asExpr() = call.getArgument(0)
        )
      } 
    }
```
2. To get source for any sink:
```
class UrlSourceFetcher extends TaintTracking::Configuration {
      UrlSourceFetcher() { this = "UrlSourceFetcher" }
      override predicate isSource(DataFlow::Node source) {
        exists(Expr E |
          source.asExpr() = E
        )
      }
      override predicate isSink(DataFlow::Node source) {
        exists(Expr E |
            source.asExpr() = E
          )
      }
    }
```
These two dataflows are used in conjuction to get the final set of sources, the conjunction being:
```
from UrlSourceInitializer config, DataFlow::Node source, DataFlow::Node sink, Expr E
    where config.hasFlow(source, sink)
    and E = getAConnectedSource(source).asExpr()
    select sink, E, E.getLocation(), E.getCompilationUnit()
```
keeping all other definitions same as you mentioned in your comment above, and `getARelatedExpr()` being
```
Expr getARelatedExpr(Expr E) {
      result = E.getParent*().(Expr).getAChildExpr*()
    }
```

Let me know if I have been able to clarify my issue properly. Also I understand that this is a bit different from the original issue I posted which is actually solved following your recursive function definitions, so do let me know if I need to open a new issue for this doubt. Thanks!

**Comment by smowton** [comment]
Do I understand right that `UriComponentsBuilder` instances are your ultimately interesting sources? If so, what you want is a single Dataflow config with the properties:
* A `UriComponentsBuilder` constructor (or constructing static method call in your illustration) is the source
* An argument to `RestTemplateMethod` is the sink (already done)
* The `builder.buildAndExpand` method conveys taint from its argument to its return value -- if its argument is tainted, so is its return value. This can also be done for any other method call you're interested in following taint across.

This allows you to avoid building a taint-flow config like "any expression to any expression", which as you might imagine will have a bajillion results and run out of either time or memory on any substantial project.

A taint configuration that includes an additional step like "if argument 0 to method F is tainted, then so is its return value" is said to **model** the function F. Here's an example of modelling the `JSON.parse` function in MongoDB: https://github.com/github/codeql/blob/main/java/ql/src/semmle/code/java/security/QueryInjection.qll#L85 -- that says taint flows from argument 0 to the return value, just as you need for `builder.buildAndExpand`.

In that particular model they've done it by extending an abstract Step class (https://github.com/github/codeql/blob/main/java/ql/src/semmle/code/java/security/QueryInjection.qll#L22) and then including it in their query here: https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/CWE-089/SqlInjectionLib.qll#L21

However you can also simply directly define modelling steps like these in your dataflow config's `isAdditionalTaintStep` predicate.

At that point you can throw away the recursion sewing together multiple taint flow paths and simply draw a single path from your interesting `UriComponentsBuilder.fromUriString` call to the sink you already have defined.

**Comment by SaumoPal97** [comment]
Thanks @smowton , isAdditionalTaintStep actually is better than the recursive method I had in mind. Closing this issue.
