### ISSUE TITLE
LGTM.com - false positive (C#)

### ISSUE THREAD

**Issue by tznind** [github/codeql#4652]
**Description of the false positive**

Error is 'pointless assignment to local variable'.  But variable is used in `Func` which is later called.

```csharp
// lgtm complains about this line
IDecideTypesForStrings decider = deciderFactory.Create(_keyType);

//this is a Func local variable that is used later on in the method
typeConversion = (a)=>decider.Parse(a.ToString());
```

https://lgtm.com/projects/g/HicServices/RDMP/snapshot/3a699967f0f79c59a390715ba648de56e00bef22/files/Rdmp.Core/DataLoad/Modules/DataFlowOperations/Swapping/ColumnSwapper.cs#x39472e7c382cc792:1

**Comment by hvitved** [comment]
Indeed, this looks like a false positive. Thank you for reporting it!
