### ISSUE TITLE
select "4294967295".toInt()  returns nothing

### ISSUE THREAD

**Issue by sad-dev** [github/codeql#4691]
**Description of the issue**

As mentioned in the title. toInt appears to be the only api to return integers (other than toFloat) from a string, and does not return a value for anything above 0x80000000. 

for example (using toHex from my previous issue https://github.com/github/codeql/issues/4145)

```
enum Magic {
...
magicWoops = 0xDEADBEEF,
...
}
```

trying to enumerate the Magic enum and apply toHex on the values will result in all values above 0x80000000 not appearing.

**Comment by sad-dev** [comment]
Also, the query "select 4294967295" fails outright

**Comment by aschackmull** [comment]
The `int` type in QL is a 32-bit signed integer, so 4294967295 is too large to be represented.

**Comment by sad-dev** [comment]
Yes, I realized from the qldocs. Raised this issue because I can't convert "3735928559" to "0xDEADBEEF" in a select without jumping through hoops to reimplement toHex, especially since integers are bounded by 32bit-signed.

**Comment by aschackmull** [comment]
> or whatever getValue() returns

For which language?

**Comment by sad-dev** [comment]
This would be cpp, but I would presume any API that returns a string representation of an integer would cause similar problems.

**Comment by aschackmull** [comment]
Right, makes sense. (I was asking because in Java the `getValue()` of the integer "0xDEADBEEF" would have been a negative number within the 32-bit signed range)

**Comment by aschackmull** [comment]
If your numbers are all unsigned 32-bit then you can get them converted to signed 32-bit like this (and convert to hex with your `toHex` predicate aftwerwards):
```
bindingset[s]
int toSignedInt(string s) {
    result = s.toInt()
    or
    not exists(s.toInt()) and
    exists(float f | f = s.toFloat() |
        f > 2147483647.0 and
        result = (f - 2147483648.0).(int) + (-2147483648)
    )
}

select toSignedInt("4294967295")
```

**Comment by aschackmull** [comment]
(The QL type `float` is 64 bit, so it should be precise enough to do the conversion correctly for all unsigned 32-bit integers)

**Comment by sad-dev** [comment]
Thanks, this worked out for me. As enums (and maybe Macros?) in cpp are the only things I can think of where I would want bigger integer types by default, I am closing the issue for now.
