### ISSUE TITLE
LGTM.com - false positive in Python script: assignment to '...' is unnecessary as it is redefined here before value is used.

### ISSUE THREAD

**Issue by kfriedberger** [github/codeql#4698]
**Description of the false positive**

The code under review can throw an exception and thus not initialize the corresponding variable.
In case of an exception, the assigned value is used as return value of the function.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/sosy-lab/cpachecker/snapshot/600369b90877446fdb27ab169736c5c2ad7b7e84/files/scripts/post_processing/coverage/generate_coverage.py?sort=name&dir=ASC&mode=heatmap#x2f378ace7fe16437:1

**Comment by RasmusWL** [comment]
Hi @kfriedberger,

I don't agree about this report. If an exception is raised inside the try-block, the code in `finally` will be executed, but afterwards the exception processing continues. See code below as an example.

```py
def foo()
    res = "default result"
    try:
        0/0
        res = "after exception"
    finally:
        print("in finally")
    return res

foo()
```

If you want to ignore any exceptions, you should use an `except` block :wink:

**Comment by kfriedberger** [comment]
Oh, you are right. Thanks for the hint.
