### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by jaxley** [github/codeql#4699]
Is support for Kotlin on the CodeQL roadmap? I don't see it listed as a supported language currently.

**Comment by jaxley** [comment]
BTW, it looks like someone has been working on Kotlin support in tree-sitter:  https://github.com/fwcd/tree-sitter-kotlin

Not sure what parser/generator CodeQL uses to know if that might be a quick path to kotlin support...

**Comment by sj** [comment]
Thanks for the suggestion, @jaxley! And great to know that someone's been working on a Tree-Sitter grammar for Kotlin :smile:.

Indeed, CodeQL currently doesn't support Kotlin ([list of supported languages](https://codeql.github.com/docs/codeql-language-guides/)). Support for new languages is typically announced on our [public roadmap](https://github.com/github/roadmap/projects/1) a few quarters before a planned release. At this stage, we don't have plans for adding Kotlin support to CodeQL, but there will be likely be an update to our roadmap later this month (relating to a different language).

Having said that, we always keep a very close eye on the [popularity of programming languages](https://octoverse.github.com/). So if Kotlin continues to grow like it has in the past few years, I'm sure it'll make its way to our roadmap soon!

**Comment by laukvik** [comment]
Kotlin support would be greatly appreciated!

**Comment by ThibaudLopez** [comment]
Kotlin is now on the [roadmap](https://github.com/orgs/github/projects/4247/views/1?filterQuery=Kotlin) for Q3 2022: https://github.com/github/roadmap/issues/207

**Comment by turbo** [comment]
Kotlin is now available in beta: https://github.blog/changelog/2022-11-28-codeql-code-scanning-launches-kotlin-analysis-support-beta/
