### ISSUE TITLE
LGTM.com - false positive - Message: Comparison is always true because k <= 2.

### ISSUE THREAD

**Issue by Bandie** [github/codeql#4791]
**Description of the false positive**

`Message: Comparison is always true because k <= 2.`

```
for(int k=0; k<3; k++){
  // k is never modified in this loop
}
```

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/pampanic/pam_panic/snapshot/ec43a67fe29287e8e65cab2f068f056e25ad8237/files/src/pam_panic_pw/pam_panic_pw.c?sort=name&dir=ASC&mode=heatmap#x4863e1685c0c23aa:1

**Comment by intrigus-lgtm** [comment]
I don't think this is a false positive:
Suppose `ok` is `true`, then we will exit the loop [here](https://lgtm.com/projects/g/pampanic/pam_panic/snapshot/ec43a67fe29287e8e65cab2f068f056e25ad8237/files/src/pam_panic_pw/pam_panic_pw.c?sort=name&dir=ASC&mode=heatmap#L120).
Suppose `ok` is `false` instead, then we will hit at same point the [k==2](https://lgtm.com/projects/g/pampanic/pam_panic/snapshot/ec43a67fe29287e8e65cab2f068f056e25ad8237/files/src/pam_panic_pw/pam_panic_pw.c?sort=name&dir=ASC&mode=heatmap#L114) condition and return.
Therefore `k <= 2` always holds.

**Comment by Bandie** [comment]
So returning something means that it holds the int? I mean .. that's not what is happening in real.

**Comment by geoffw0** [comment]
I agree with @intrigus-lgtm, as far as I can tell there is no situation where `k` is incremented from `2` to `3` so the comparison `k < 3` is always true.  Sometimes these kinds of comparisons indicate that something is wrong with the code nearby but in this case it doesn't appear to be doing any harm.
