### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by garethhurley** [github/codeql#4792]
**Description of the false positive**

LGTM reports a java/xxe issue which should be disabled by the line commented `// should fix the issue?`
However:
- LGTM failed to close the issue and it had to be manually suppressed via a comment `//lgtm [java/xxe]`
- The developer who made the fix followed the recommendation to disallow-doctype-decl

See the code snippet below (from a private instance not on lgtm.com)

```
...
...
public static ParsedObject someParsingMethod(InputStream inputStream, int iLength) throws ParserConfigurationException, SAXException, IOException {
        SAXParserFactory saxParserFactory = SAXParserFactory.newInstance();
        saxParserFactory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
        saxParserFactory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);  // should fix the issue?
        SAXParser saxParser = saxParserFactory.newSAXParser();
        try {
            if (iLength > 0) {
                saxParser.setProperty("http://apache.org/xml/properties/input-buffer-size", 2 * iLength);
            }
        } catch (Exception e) {
            //Ignored
        }
        SAXHandler saxHandler = new SAXHandler();  // extends org.xml.sax.helpers.DefaultHandler to manage the parsing
        saxParser.parse(inputStream, saxHandler); //lgtm [java/xxe]
        return saxHandler.getParsedObject();
}
...
...
```

It appears from the [query implementation](https://github.com/github/codeql/blob/8d4f7e2db7ec3b7559a3e358fd1b8a7203ce7474/java/ql/src/semmle/code/java/security/XmlParsers.qll#L481-L505) that this fix is not taken into account. 

Is this an omission?

**Comment by yo-h** [comment]
Thank you for your report. We agree this looks like an omission and the team is looking into it.
