### ISSUE TITLE
Failed with bad exit code during 'Checkout'

### ISSUE THREAD

**Issue by olehermanse** [github/codeql#4809]
We don't understand this error:

```
Failed with bad exit code during 'Checkout'
```

https://lgtm.com/projects/g/cfengine/core/logs/rev/pr-71279a53946a93a614029a0f8b3ef7f3e1b958ea/lang:cpp/stage:Build%20merge_97b2e35e947678dd248112a6cc02a36db7c10453

The PR doesn't do anything weird:

https://github.com/cfengine/core/pull/4422

We retriggered the build and it didn't work. Any idea what's happening?

**Comment by aibaars** [comment]
Thanks for the report. The error isn't related to the checkout phase, but instead happens between the checkout and build phases. It looks like the Ubuntu eoan packages have been removed Today from http://security.ubuntu.com/ubuntu causing errors like below.  Eoan's official support ended last July and we should have upgraded earlier. Apologies for the inconvenience.

```
Ign:1 http://archive.ubuntu.com/ubuntu eoan InRelease
Ign:2 http://security.ubuntu.com/ubuntu eoan-security InRelease
Err:3 http://security.ubuntu.com/ubuntu eoan-security Release
  404  Not Found [IP: 91.189.88.152 80]
Ign:4 http://archive.ubuntu.com/ubuntu eoan-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu eoan-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu eoan Release
  404  Not Found [IP: 91.189.88.142 80]
Err:7 http://archive.ubuntu.com/ubuntu eoan-updates Release
  404  Not Found [IP: 91.189.88.142 80]
Err:8 http://archive.ubuntu.com/ubuntu eoan-backports Release
  404  Not Found [IP: 91.189.88.142 80]
Reading package lists...
```

**Comment by olehermanse** [comment]
@aibaars Thank you for the explanation, any update on when it will be resolved?

**Comment by jwhui** [comment]
We are experiencing a similar issue:

https://lgtm.com/projects/g/openthread/openthread/logs/rev/pr-9e63ed864c762c839b7529394ad03ae0ba1c1d28/lang:cpp/stage:Build%20merge_fefface59c04c231c97491b2e0621e2c64adc7fc

Any suggestions on how to resolve?

**Comment by dreamer** [comment]
We had this issue as well. We suspended lgtm.com bot for now, as it's extremely inconvenient when it's failing the review.

**Comment by chrisgavin** [comment]
Hi. We've rolled out a temporary fix by switching to a custom mirror of the Ubuntu Eoan repository while we migrate to a newer version of Ubuntu as part of our default build images.

If you retry any failed builds they should now succeed. Apologies again for the inconvenience here, we should have migrated to a newer Ubuntu release sooner.
