### ISSUE TITLE
Getting the string with ... in the middle instead of whole string

### ISSUE THREAD

**Issue by SandeepKallepalli** [github/codeql#4811]
when i am trying to get a long output(string,expr name etc) from a javascript database , I am getting "..." in the middle of the string instead of the total output(.toString() ) . What should i do to get the total string without ... in the middle.

Example: 
I am trying to get the first argument of a http call :
    http.get('/application/appID/blahblah') when i want the url i am getting "/appli...hblah"
I want the whole '/application/appID/blahblah'.

**Comment by geoffw0** [comment]
Which tool are you using to view your query results?  It sounds like the "..." might be something that the interface is doing, rather than an issue with the database or query.

**Comment by SandeepKallepalli** [comment]
I tried both vscode and cli . In both i am getting ...

**Comment by erik-krogh** [comment]
The default `toString()` is short on purpose, to make sure alert messages don't grow too large.   

But we do have methods to get the full string. 

You can use `Literal::getValue()` If you are working on AST nodes: 
```CodeQL
from Literal lit
where lit.getValue().length() > 20 and lit.getRawValue().length() < 100
select lit, lit.getValue()
```

Or you can use `DataFlow::Node::getStringValue()` if you are working with dataflow nodes: 
```CodeQL
from DataFlow::Node node
where node.getStringValue().length() > 20 and node.getStringValue().length() < 100
select node, node.getStringValue()
```

**Comment by SandeepKallepalli** [comment]
Ok thanks
