### ISSUE TITLE
Got error while analyzing a Go db

### ISSUE THREAD

**Issue by adilrookout** [github/codeql#4815]
**Description of the issue**
Created a go database via `codeql database create` command

Then ran `codeql database analyze` and got the following error :
`Unknown kind "Table" when converting to analysis model.(UNSUPPORTED_KIND).`

**Comment by aibaars** [comment]
I think the annotation `@kind table` should be with lower case t .

**Comment by adilrookout** [comment]
where should i change it ?

**Comment by adilrookout** [comment]
Here is the problematic query :
```
/**
 * @name Frequency counts for external APIs that are used with untrusted data
 * @description This reports the external APIs that are used with untrusted data, along with how
 *              frequently the API is called, and how many unique sources of untrusted data flow
 *              to it.
 * @id go/count-untrusted-data-external-api
 * @kind table
 * @tags security external/cwe/cwe-20
 */

import go
import semmle.go.security.ExternalAPIs

from ExternalAPIUsedWithUntrustedData externalAPI
select externalAPI, count(externalAPI.getUntrustedDataNode()) as numberOfUses,
  externalAPI.getNumberOfUntrustedSources() as numberOfUntrustedSources order by
    numberOfUntrustedSources desc
```

**Comment by adilrookout** [comment]
taken from here :
https://github.com/github/codeql-go/blob/main/ql/src/Security/CWE-020/ExternalAPIsUsedWithUntrustedData.ql

**Comment by smowton** [comment]
Looks like that really is a bug: obviously the intent is for lgtm.com to display the results in tabular form not as inline alerts, but https://help.semmle.com/QL/learn-ql/writing-queries/query-metadata.html says `@kind` must be either `problem` or `path-problem`.

**Comment by smowton** [comment]
With that being said, that kind does seem to be used quite a lot, mostly but not exclusively in tests (e.g. https://github.com/github/codeql/blob/8d4f7e2db7ec3b7559a3e358fd1b8a7203ce7474/cpp/ql/src/Architecture/General%20Class-Level%20Information/HubClasses.ql) -- anyone know why that `@kind` isn't documented, and where it is or isn't supported? 

@adilrookout, what query-set were you running that included this one? It shouldn't be part of any standard query set; what was your full `analyze` command?

**Comment by adilrookout** [comment]
`codeql database analyze <db path> codeql-go/ql/src/Security --format=csv --output=results.csv`

**Comment by smowton** [comment]
I recommend running https://github.com/github/codeql-go/blob/main/ql/src/codeql-suites/go-code-scanning.qls instead, which references https://github.com/github/codeql/blob/main/misc/suite-helpers/code-scanning-selectors.yml, which in turn will pick security queries of appropriate types / warning severities. You can copy and customise either one of those files to vary the query selection.

**Comment by adilrookout** [comment]
Tried and i get the following error :
`A fatal error occurred: The QL pack 'codeql-suite-helpers' which is referenced from /Users/adil/work/codeql-home/codeql-go/ql/src/codeql-suites/go-code-scanning.qls cannot be found.
`

**Comment by aibaars** [comment]
The suite helpers can be found in https://github.com/github/codeql/tree/main/misc/suite-helpers . If I am not mistaken things should work if you `git clone https://github.com/github/codeql` as a sibling folder of your `codeql-go` folder :
```
git clone https://github.com/github/codeql /Users/adil/work/codeql-home/codeql
```

**Comment by jalseth** [comment]
@aibaars I'm running into the same issue, and that doesn't seem to work. I have both `codeql` and `codeql-go` checked out in my `$HOME/Code` directory and am running into the following error.

```
$ codeql database analyze my-db $HOME/Code/codeql-go/ql/src/codeql-suites/go-code-scanning.qls --format=csv --output=test01.csv
Running queries.
A fatal error occurred: The QL pack 'codeql-suite-helpers' which is referenced from /Users/james/Code/codeql-go/ql/src/codeql-suites/go-code-scanning.qls cannot be found.
```

I've tried patching the `from:` field in the YAML using a relative path, but it results in the same error
```
$ odeql database analyze my-db $HOME/Code/codeql-go/ql/src/codeql-suites/go-security-extended.qls --format=CSV --output=test01.csv
Running queries.
A fatal error occurred: The QL pack '../../../codeql/misc/suite-helpers' which is referenced from /Users/james/Code/codeql-go/ql/src/codeql-suites/go-security-extended.qls cannot be found.
```

**Comment by aibaars** [comment]
> @aibaars I'm running into the same issue, and that doesn't seem to work. I have both `codeql` and `codeql-go` checked out in my `$HOME/Code` directory and am running into the following error.

@jalseth 
Did you also unzip the CodeQL CLI in the  `$HOME/Code` folder? If not you should either add a flag `--search-path `$HOME/Code/codeql` to the `codeql database analyze` command, or unzip the CodeQL CLI into  `$HOME/Code`. I normally have the following folder structure:

* `$HOME/Code/codeql` : A CLI from https://github.com/github/codeql-cli-binaries/releases
* `$HOME/Code/ql` : A checkout of https://github.com/github/codeql
* `$HOME/Code/codeql-go` : A checkout of https://github.com/github/codeql-go
```

**Comment by jalseth** [comment]
@aibaars Thanks! That was it.

That said, it's quite abnormal for the relative paths to be based on the tool's location, since it can be placed anywhere on disk as long as it's in $PATH. I would expect the relative search path to be based on the current directory, or relative to the configuration files I point it at.

**Comment by xanderdunn** [comment]
I am seeing the same error:
```
$ ./codeql/codeql database analyze my-proj-database --format=csv --output=./my-proj-output.csv
Running queries.
ERROR: Referenced pack 'codeql/suite-helpers' not found. (/home/xander/codeql-home/codeql-go/ql/src/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /home/xander/codeql-home/codeql-go/ql/src
```

I have the three sibling directories as described above:
<img width="284" alt="Screen Shot 2022-02-06 at 19 35 23" src="https://user-images.githubusercontent.com/1313618/152708647-346b1c95-2864-4a86-8e2a-420c139cfba8.png">
- `codeql` is an unzip of a 2.8.0 binary from https://github.com/github/codeql-cli-binaries/releases
- `ql` is a clone of https://github.com/github/codeql
- `codeql-go` is a clone of https://github.com/github/codeql-go

When I run `./codeql/codeql resolve qlpacks` it does find the suite-helpers:
```
codeql/suite-helpers (/home/xander/codeql-home/ql/misc/suite-helpers)
```

Specifying the `--search-path` doesn't help either:
```
$ ./codeql/codeql database analyze my-proj-database --format=csv --output=./my-proj-output.csv --search-path=/home/xander/codeql-home/ql
Running queries.
ERROR: Referenced pack 'codeql/suite-helpers' not found. (/home/xander/codeql-home/codeql-go/ql/src/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /home/xander/codeql-home/codeql-go/ql/src
```

**Comment by xanderdunn** [comment]
@smowton That did it, thank you! I was following [this]() guide, which didn't mention it
