### ISSUE TITLE
Create CodeQL DB for compiled files

### ISSUE THREAD

**Issue by SaumoPal97** [github/codeql#4816]
So I have a Java project with a lot of external dependencies, and when I want to find some information like say a `MethodAccess` for a method defined inside an external library, I am able to get the class information and file's absolute location in `.m2` folder of maven. Given I know the file location, can I build a CodeQL DB from the external library jar file? Or can compiled `.class` files be used to create CodeQL DB. Any alternatives can also be appreciated. Thanks!

**Comment by chriskaliX** [comment]
same
