### ISSUE TITLE
Python: Formatted string literals are not supported

### ISSUE THREAD

**Issue by kingkaki** [github/codeql#4834]
It seems can't propagate taint with formatted string literals, like `f"hello {name}"`
Following SQL injection can't be detected
```python
class SqlInject1View(View):
    def get(self, request):
        name = request.GET.get("name")
        with connection.cursor() as cursor:
            cursor.execute(f"SELECT * FROM user where username='{name}'")
            user = cursor.fetchone()
        return HttpResponse("sql inject")
```

**Comment by RasmusWL** [comment]
Hi @kingkaki, do you have a complete code example you can share?

This seems to be using Django class-based views, which we currently don't support (but there a [PR](https://github.com/github/codeql/pull/4779) open to add that). So the problem isn't that taint isn't propagated through f-strings, but that the source (`request.GET`) isn't currently recognized.

**Comment by kingkaki** [comment]
After reading the source code, I found that I used the v1.25.0 release.Formatted string literals has been supported in the latest version of the code.
So, no problem, thank you for your answer.
