### ISSUE TITLE
is the hasValue method deprecated of Expr

### ISSUE THREAD

**Issue by madneal** [github/codeql#4848]
**Description of the issue**

I am learning the codeql queries of csharp. For the [exercise 2 of csharp](https://codeql.github.com/docs/codeql-language-guides/analyzing-data-flow-in-csharp/#exercise-2), the `hasValue` method cannot be resolved for type Expr.

![image](https://user-images.githubusercontent.com/12164075/102702958-bd6be780-42a3-11eb-8c25-ba0cf223ebc5.png)

```
import csharp

class Configuration extends DataFlow::Configuration {
  Configuration() {
    this = "String to System.Uri"
  }
  
  override predicate isSource(DataFlow::Node src) {
    src.asExpr().hasValue()
  }
  
  override predicate isSink(DataFlow::Node sink) {
    exists(Call c | c.getTarget().(Constructor).getDeclaringType().hasQualifiedName("System.Uri")
      and sink.asExpr() = c.getArgument(0))
  }
}

from DataFlow::Node src, DataFlow::Node sink, Configuration config
where config.hasFlow(src, sink)
```

Here is the corresponding [project link](https://lgtm.com/query/project:1506137406248/lang:csharp/) of lgtm. I have searched for the method `hasValue`. It does exists. But why it cannot be resolved here.

https://codeql.github.com/codeql-standard-libraries/csharp/semmle/code/csharp/exprs/Expr.qll/predicate.Expr$Expr$hasValue.0.html

![image](https://user-images.githubusercontent.com/12164075/102702983-20f61500-42a4-11eb-99b4-1cbf23bdcb01.png)

**Comment by intrigus-lgtm** [comment]
`DataFlow::Node.asExpr` returns a `DotNet::Expr` which is not the same as `Expr`.
So to fix your problem you should change the line to this:
```ql
src.asExpr().(Expr).hasValue()
```
Maybe @hvitved can shed some light onto the difference between `DotNet::Expr` and `Expr`.

**Comment by hvitved** [comment]
Thanks a lot for reporting this; I have created https://github.com/github/codeql/issues/4848 which should address it.
