### ISSUE TITLE
csharp DataFlow EnvironmentVariableFlowSource is compatiable

### ISSUE THREAD

**Issue by madneal** [github/codeql#4849]
**Description of the issue**

For the [exercise 4](https://codeql.github.com/docs/codeql-language-guides/analyzing-data-flow-in-csharp/#exercise-4) of analyzing data flow in C#. It always indicates as the following:

![image](https://user-images.githubusercontent.com/12164075/102703647-85b56d80-42ac-11eb-803c-4965d1bbaf08.png)

```
import csharp

class EnvironmentVariableFlowSource extends DataFlow::ExprNode {
  EnvironmentVariableFlowSource() {
    this.getExpr().(MethodCall).getTarget().hasQualifiedName("System.Environment.GetEnvironmentVariable")
  }
}

class Configuration extends DataFlow::Configuration {
  Configuration() { this="Environment to System.Uri" }

  override predicate isSource(DataFlow::Node src) {
    src.asExpr() instanceof EnvironmentVariableFlowSource
  }

  override predicate isSink(DataFlow::Node sink) {
    exists(Call c | c.getTarget().(Constructor).getDeclaringType().hasQualifiedName("System.Uri")
    and sink.asExpr()=c.getArgument(0))
  }
}

from DataFlow::Node src, DataFlow::Node sink, Configuration config
where config.hasFlow(src, sink)
select src, "This environment variable constructs a 'System.Uri' $@.", sink, "here"
```

However, the class `EnvironmentVariableFlowSource` is already defined. And it extends from ExprNode. So it should be compattiable with Expr.

**Comment by intrigus-lgtm** [comment]
> However, the class EnvironmentVariableFlowSource is already defined. And it extends from ExprNode. So it should be compattiable with Expr.

No, `EnvironmentVariableFlowSource` should not be compatible with `Expr`.
`src.asExpr()` gives us an `Expr`.
Asking whether this `Expr` is an instance of `EnvironmentVariableFlowSource` would be like asking whether a `Picture` is `Loud` - they are incompatible and so the answer is always `false`.

In CodeQL there are "two types" for describing stuff:
First, types like `Expr`, `Call`, `Method`, and `MethodCall` to name a few.
The other types for describing stuff are based  on `DataFlow::Node`.
Like `DataFlow::ExprNode` or `DataFlow::ParameterNode`.

You can not compare one of the first types with one of the second types.
Instead, you can use `DataFlow::Node.asExpr` to get an `Expr` and vice versa.

So what is the problem with the code?
`src.asExpr() instanceof EnvironmentVariableFlowSource`
`src.asExpr()` returns the `Expr` for a `Node`.
But `EnvironmentVariableFlowSource` is defined in terms of `Node`s, making the comparison invalid.
So `src` **is** already a type of `Node` and we don't have to convert it.
Just remove `.asExpr()`, leaving `src instanceof EnvironmentVariableFlowSource` which should now compile :tada:

**Comment by madneal** [comment]
@intrigus-lgtm Thanks for your reply. I'd like to pr for the two problems of the code of codeql docs.

**Comment by hvitved** [comment]
Thanks for fixing the documentation.
