### ISSUE TITLE
Python: track variables across files

### ISSUE THREAD

**Issue by kingkaki** [github/codeql#4884]
Hey, I have a problem.
When I import app from app.py, it doesn’t seem to be detected correctly, like this
```python
# app.py
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello World!'
```
```python
# run.py
from app import app

if __name__ == '__main__':
    app.run(debug=True)
```
When I use CWE-215 to detect flask debug, the result is empty.
```
/**
 * @name Flask app is run in debug mode
 * @description Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.
 * @kind problem
 * @problem.severity error
 * @precision high
 * @id py/flask-debug
 * @tags security
 *       external/cwe/cwe-215
 *       external/cwe/cwe-489
 */

import python
import semmle.python.web.flask.General

from CallNode call, Value isTrue
where
  call = theFlaskClass().declaredAttribute("run").(FunctionValue).getACall() and
  call.getArgByName("debug").pointsTo(isTrue) and
  isTrue.getDefiniteBooleanValue() = true
select call,
  "A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger."
```
![image](https://user-images.githubusercontent.com/30930379/103169826-38239c80-487a-11eb-8cee-c62ce90fcea4.png)
It doesn't seem to recognize the app variable in run.py as an instance of Flask

**Comment by kingkaki** [comment]
Is this a bug? Or is there any way to track it? @geoffw0

**Comment by RasmusWL** [comment]
Hi @kingkaki, thanks for raising this issue.

We're currently reworking how to track such instances in the Python analysis, so stay tuned (we still need to iron out some things before we're ready to share with outside contributors).

We have a known problem if your python code doesn't belong to a package, so as a temporary workaround, could you try to structure you code such as:

```
mypkg/
├── __init__.py
├── app.py
└── run.py
```

and change `run.py` as

```diff
-from app import app
+from mypkg.app import app
```

If you're creating databases locally, it's also important that flask is available in the active python environment. If it isn't already, you need to create a new virtual environment and do `pip install flask`.

Let me know if you run into more problems :blush:

**Comment by kingkaki** [comment]
Okay, if I analyze other people's code, this way of modifying the code will be more troublesome.

Hope the new tracking way can solve this problem.

Anyway, thanks a lot.

**Comment by FelipeF1198** [comment]
> Hey, I have a problem.
> When I import app from app.py, it doesn’t seem to be detected correctly, like this
> 
> ```python
> # app.py
> from flask import Flask
> 
> app = Flask(__name__)
> 
> @app.route('/')
> def hello_world():
>     return 'Hello World!'
> ```
> 
> ```python
> # run.py
> from app import app
> 
> if __name__ == '__main__':
>     app.run(debug=True)
> ```
> 
> When I use CWE-215 to detect flask debug, the result is empty.
> 
> ```
> /**
>  * @name Flask app is run in debug mode
>  * @description Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.
>  * @kind problem
>  * @problem.severity error
>  * @precision high
>  * @id py/flask-debug
>  * @tags security
>  *       external/cwe/cwe-215
>  *       external/cwe/cwe-489
>  */
> 
> import python
> import semmle.python.web.flask.General
> 
> from CallNode call, Value isTrue
> where
>   call = theFlaskClass().declaredAttribute("run").(FunctionValue).getACall() and
>   call.getArgByName("debug").pointsTo(isTrue) and
>   isTrue.getDefiniteBooleanValue() = true
> select call,
>   "A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger."
> ```
> 
> ![image](https://user-images.githubusercontent.com/30930379/103169826-38239c80-487a-11eb-8cee-c62ce90fcea4.png)
> It doesn't seem to recognize the app variable in run.py as an instance of Flask

**Comment by RasmusWL** [comment]
Hi @FelipeF1198 . I've removed your comment since it was just a copy of the original issue description. If you have a problem yourself, please create a new issue :blush:
