### ISSUE TITLE
cannot resolve qlpacks of codeql-repo

### ISSUE THREAD

**Issue by madneal** [github/codeql#4887]
**Description of the issue**

As stated from [this](https://codeql.github.com/docs/codeql-cli/getting-started-with-the-codeql-cli/), I have unextracted the code-cli to the directy of `codeql-home`:

![image](https://user-images.githubusercontent.com/12164075/103192172-b3d12800-4912-11eb-876d-97d10b3d9761.png)

And clone the repository of [codeql](https://github.com/github/codeql) with the name of `codeql-repo` inside `codeql-home`.

![image](https://user-images.githubusercontent.com/12164075/103192290-1c200980-4913-11eb-8104-70b29204e40c.png)

The `codeql-home` has been added to `$PATH`.

![image](https://user-images.githubusercontent.com/12164075/103192366-61443b80-4913-11eb-9188-94ec42a8d20b.png)

But for `codeql resolve qlpacks`, there is only one result. But no qlpacks of codeql-repo.

The system of mine is MacOS 10.14.6

**Comment by aibaars** [comment]
If I am not mistaken all folders should be siblings of each other (the CLI , codeql-repo and codeql-go).

**Comment by madneal** [comment]
@aibaars  Sorry, I don't understand what do you mean? Is there any problem of the folder replationship?

**Comment by aibaars** [comment]
I think the folder structure should be
- `codeql_home`
  - `codeql` 
  - `codeql-go`
  - `codeql-repo`

**Comment by aibaars** [comment]
You could use the starter work space too: https://github.com/github/vscode-codeql-starter This has a similar layout and can be opened directly with VSCode .

**Comment by madneal** [comment]
@aibaars does `codeql` means the extracted folder of codeql-cli. I have organized like this. But still does not work.

![image](https://user-images.githubusercontent.com/12164075/103203889-f73a8f00-4930-11eb-9fdd-a0f3d8110ddf.png)

**Comment by madneal** [comment]
But stated in 

```
4. Extract the zip archive
For Linux, Windows, and macOS users (version 10.14 “Mojave”, and earlier) simply extract the zip archive into the directory you created in step 2.

For example, if the path to your copy of the CodeQL repository is $HOME/codeql-home/codeql-repo, then extract the CLI into $HOME/codeql-home/.
```

The codeql is extracted to `codeql-home`.

**Comment by aibaars** [comment]
> @aibaars does `codeql` means the extracted folder of codeql-cli. I have organized like this. But still does not work.
> 
Yes that should work. Also put the `codeql-go` repo in `codeql-home`. 

Just checking: the file `codeql-home/codeql/codeql` should be the codeql command.

**Comment by aibaars** [comment]
I see you still have a `.codeqlmanifest.json` file in `codeql-home`. Is that a left-over from the earlier attempt? That file describes where QL packs can be found and may interfere with the default QL pack lookup.

**Comment by madneal** [comment]
@aibaars Thanks. It's the reason. But the file of `.codeqlmanifest.json` is generated by which. Should there a policy to update this file when add `codeql-repo` to `codeql-home`.

**Comment by aibaars** [comment]
That file is part of the codeql cli. I suspect it was a leftover from when you extracted the cli without the codeql subfolder

**Comment by madneal** [comment]
@aibaars It comes from the [release page](https://github.com/github/codeql-cli-binaries/releases) of codeql. I just verified.  I download [codeql-osx64.zip](https://github.com/github/codeql-cli-binaries/releases/download/v2.4.1/codeql-osx64.zip) which contains the `.codeqlmanifest.json` file.
