### ISSUE TITLE
False positive : SQL injection

### ISSUE THREAD

**Issue by timsgit** [github/codeql#4888]
Hi,
I think these 3 issues are false positives:

https://lgtm.com/projects/g/timsgit/ipscan/snapshot/a0d6e6d783fc0fb608d4a8170a27fb40930383ef/files/ipscan_db.c?sort=name&dir=ASC&mode=heatmap#xd463e94fe928c142:1

The external source in this case is actually /dev/urandom and the information which is embedded into the SQL query
is a number (no chance of a SQL injection in the usual sense).

**Comment by geoffw0** [comment]
The relevant code here seems to be:
```
uint64_t fetchedsession = 0;
FILE *fp;
fp = fopen("/dev/urandom", "r");

size_t numitems = fread( &fetchedsession, sizeof(fetchedsession), 1, fp); // fetchedsession becomes tainted

fclose(fp);
```
As you say two things stand out - that the source is `"/dev/urandom"` (which is easy to tell in this case but more difficult to determine in general), and that the tainted value has an integer type.  I will try a fix...

**Comment by geoffw0** [comment]
Thanks for this report, it appears this issue was affecting at least a handful of projects.  It will be fixed by https://github.com/github/codeql/pull/4915.

**Comment by timsgit** [comment]
You're welcome - thanks for identifying a fix.

**Comment by geoffw0** [comment]
The fix is merged so I'm closing this issue.  It will take up to 2 weeks for the changes to reach LGTM.  Please let me know if there are any remaining problems.
