### ISSUE TITLE
C++ query involving getAnOverload() does not seem to finish

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [github/codeql#4889]
I need to write a simple C++ query that returns all overloads of a function. I came up with this:

```
import cpp

from Function f, Function g
where f.getQualifiedName() = "foo::bar" and f.getAnOverload() = g
select g.getQualifiedName()
```

I saved it as query.ql (with `foo::bar` being a specific name, of course) and ran it with the following command line:

```codeql query run --database=cpp-database C:\codeql-home\codeql-repo\cpp\ql\src\q\query.ql```

It compiled successfully, and codeql started evaluation. However, I had to kill it after 25 hours because it generated over 300 GB of cache and I started to run out of available disk space.

Is it expected that a simple query like that should take so much time and disk space? Is it a bug, or is there something wrong with the query itself?

**Comment by MathiasVP** [comment]
Hi automatedbugreportingfacility,

Thanks for reporting this. There was a performance-problem in `Function::getAnOverload`. I've created a PR with a fix here: https://github.com/github/codeql/pull/4891. I expect it'll take a couple of days before it's merged due to the holidays.

I hope the PR fixes the performance-problems you observed. If not, feel free to reach out again and I'm sure we'll figure it out!

**Comment by automatedbugreportingfacility** [comment]
Thank you for a very fast response, this is much appreciated! I'll test the fix as soon as possible.

By the way, is it correct that `getAnOverload()` returns a single function? For example, if there's class A with function f(), and 2 directly derived classes, B and C, that both override A::f(), would getAnOverload() return B::f(), C::f(), or both? What I'm trying to achieve is: given a function call to A::f(), return all possible functions that might be called in the invocation. Something that would include B::f(), C::f(), and possibly also indirect overrides if there was E::f(), where class E derives from class D, which derives from class C. Spending my holidays on exploring options for the most performant way to complete this task :)

**Comment by MathiasVP** [comment]
> By the way, is it correct that getAnOverload() returns a single function? For example, if there's class A with function f(), and 2 directly derived classes, B and C, that both override A::f(), would getAnOverload() return B::f(), C::f(), or both? What I'm trying to achieve is: given a function call to A::f(), return all possible functions that might be called in the invocation. Something that would include B::f(), C::f(), and possibly also indirect overrides if there was E::f(), where class E derives from class D, which derives from class C. Spending my holidays on exploring options for the most performant way to complete this task :)

It sounds like what you really want is to figure out which functions _overrides_ a given function. The result of `f.getAnOverload()` is all the function that _overloads_ f. That is, given the following of function definitions:

```cpp
void f() { /* ... */ }
void f(int) { /* ... */ }
void f(int, char) { /* ... */ }
```

the query:
```codeql
import cpp

from Function f
where f.getNumberOfParameters() = 0 // only consider the f that has 0 parameters.
select f.getAnOverload()
```

would give you back the two functions `f(int)` and `f(int, char)`.

In contrast, given the situation you describe:

```cpp
struct A {
  virtual void f() {}
};

struct B : public A {
  virtual void f() override {}
};

struct C : public A {
  virtual void f() override {}
};

struct D : public A {};

struct E : public D {
  virtual void f() override {}
};
```

You can use `MemberFunction::getAnOverridingFunction` to figure out which functions overrides a given member function:
```codeql
import cpp

from MemberFunction f
select f.getAnOverridingFunction()
```

Does that help?

**Comment by automatedbugreportingfacility** [comment]
Ah! Thanks for clearing up my overload/override mix-up, things make much more sense now :) Happy New Year!
