### ISSUE TITLE
The improvement of ResponseSplitting.qll

### ISSUE THREAD

**Issue by madneal** [github/codeql#4899]
**Description of the issue**

The [`getArgument`](https://github.com/github/codeql/blob/8d4f7e2db7ec3b7559a3e358fd1b8a7203ce7474/java/ql/src/semmle/code/java/security/ResponseSplitting.qll#L22) should be covered by method of `getAnArgument`. So it's better to remove `getArgument`.

**Comment by intrigus-lgtm** [comment]
Huh?
The one clause (`getArgument(0)`) is for `ResponseAddCookieMethod` while the other clause (`getAnArgument()`) is for `ResponseAddHeaderMethod`.
Therefore `getArgument` is not covered by `getAnArgument`.

Or did I misunderstand your issue?

**Comment by madneal** [comment]
@intrigus-lgtm Sorry for my missing. I'll close the issue and pr.
