### ISSUE TITLE
LGTM.com - false positive: This replaces with itself.

### ISSUE THREAD

**Issue by dzikoysk** [github/codeql#4916]
**Description of the false positive**

Unicode based character representations are not the same as its standard form and the recognition of such a character is processed differently. 

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/dzikoysk/reposilite/snapshot/9ca6be1fa05b2063f36aebf4a77ddece3a1c69da/files/reposilite-frontend/src/views/dashboard/Cli.vue?sort=name&dir=ASC&mode=heatmap#x93f9411fae7a7047:1

![image](https://user-images.githubusercontent.com/4235722/103682742-8e36c500-4f89-11eb-9ae8-56aabc1afdb4.png)

**Comment by erik-krogh** [comment]
I don't get it.  
If I try to execute: `console.log('\u003C' === '<')`, then I get `true`.    
I can't find a function where '\u003C' is treated differently from  '<'. 

Do you have some example where the two are processed differently?

**Comment by dzikoysk** [comment]
I was also wondering, but I've found that it was happening only on my Firefox dev-edition. I've just upgraded it to the latest version, and it works as expected 😳 I couldn't figure it out how Vue.js processed the source, because there is a couple of similar responses on their forum where such an approach works well. It also explains my issue with emoji lately in other project 
Sorry for taking your time 😅
