### ISSUE TITLE
the dead link of built-in predicates

### ISSUE THREAD

**Issue by madneal** [github/codeql#4931]
**Description of the issue**

The built-in predicates in page [Predicates](https://codeql.github.com/docs/ql-language-reference/predicates/) is 404. The link  is https://codeql.github.com/docs/ql-language-reference/predicates/ql-language-specification#built-ins.

But it should be https://codeql.github.com/docs/ql-language-reference/predicates/ql-language-specification/#built-ins

The source code of `predicates.rst` is right. But the page is not correct.

![image](https://user-images.githubusercontent.com/12164075/104092343-56e45300-52be-11eb-907b-3d66a10daba5.png)

**Comment by criemen** [comment]
@github/docs-content-dsp can you have a look?

**Comment by shati-patel** [comment]
Hi @madneal! Thank you for the issue. Unfortunately, we've had a few problems with links since moving to the new site 😬 Sorry for the difficulty these have caused! 

I've fixed them in https://github.com/github/codeql/pull/4925, and these changes will be published within the next few weeks.

**Comment by shati-patel** [comment]
The update is live! 

The links on https://codeql.github.com/docs/ql-language-reference/predicates/ (and other pages) should be fixed now 🔗
