### ISSUE TITLE
errors of Binding behaviro

### ISSUE THREAD

**Issue by madneal** [github/codeql#4932]
**Description of the issue**

For [Binding behavior](https://codeql.github.com/docs/ql-language-reference/predicates/#binding-behavior), there should be another error except the two errors.

![image](https://user-images.githubusercontent.com/12164075/104093012-ac226380-52c2-11eb-884c-751566a18bce.png)

There should be another error for `i * 4 ` of `expression is not bound to a value.`

![image](https://user-images.githubusercontent.com/12164075/104093030-d7a54e00-52c2-11eb-80ef-a24f0dad7fcd.png)

**Comment by smowton** [comment]
You can make a PR to edit this at https://github.com/github/codeql/blob/main/docs/codeql/ql-language-reference/predicates.rst

**Comment by madneal** [comment]
@smowton I have created the pr after the issue. #4933
