### ISSUE TITLE
 the format of note in types

### ISSUE THREAD

**Issue by madneal** [github/codeql#4934]
**Description of the issue**

The format of Note in [Types](https://codeql.github.com/docs/ql-language-reference/types/) isn't correct.

![image](https://user-images.githubusercontent.com/12164075/104094942-f9a4cd80-52ce-11eb-8bcd-aac6022f88e3.png)

**Comment by criemen** [comment]
@github/docs-content-dsp can you have a look?

**Comment by shati-patel** [comment]
Thank you for taking the time to report the issue @madneal! This was a bug with the syntax highlighting on the site :bug: 
https://github.com/github/codeql/pull/4874 (specifically [this line](https://github.com/github/codeql/pull/4874/files#diff-adcb95d4c4e211d071e120ece2ef78157198516571433900f3ed97798367ce1aR177)) contains a fix, and will be included in the next publishing cycle.

**Comment by shati-patel** [comment]
Just published an update with the fix: 

![image](https://user-images.githubusercontent.com/42641846/104173610-f6f4c600-53fd-11eb-9029-7795e0952ac1.png)


Let us know if you find more bugs!
