### ISSUE TITLE
the format in expressions

### ISSUE THREAD

**Issue by madneal** [github/codeql#4936]
**Description of the issue**

The format of code blocks isn't correct.

https://codeql.github.com/docs/ql-language-reference/expressions/

![image](https://user-images.githubusercontent.com/12164075/104114288-a9188900-533d-11eb-9d6b-73a5e28c7c93.png)

**Comment by criemen** [comment]
@github/docs-content-dsp can you have a look?

**Comment by shati-patel** [comment]
Thank you again for reporting the bug @madneal! The indentation had caused some weird syntax highlighting, and I've fixed this in https://github.com/github/codeql/pull/4874.

The update should be published in the next few weeks!

**Comment by shati-patel** [comment]
@madneal: I've just published an update to the docs. The page now looks like this:

![image](https://user-images.githubusercontent.com/42641846/104173373-95ccf280-53fd-11eb-8895-ddbbf27fef40.png)


I'll close this issue, but let us know if you spot more bugs! 👀
