### ISSUE TITLE
Close/delete more than 25 alerts at a time ?

### ISSUE THREAD

**Issue by AleksIvanovSinglet** [github/codeql#4961]
In a project I am currently working on, there are 1000+ code scanning alerts (coming from the security-and-quality query) we've investigated, are not a problem for us, so we'd like to close all of them together.

Through the platform interface, on the Code Scanning Alerts page, I see that only one page of 25 entries can be selected at a time. 

Is there a way to selected all of the alerts, so that we may apply some action on all of them at the same time ?

**Comment by marcogario** [comment]
:wave: There is currently no way to do this bulk operation in the UI. 

You could automate this from the API. See https://docs.github.com/en/free-pro-team@latest/rest/reference/code-scanning#update-a-code-scanning-alert to see how to dismiss an alert.

Out of curiousity, are all these results from the same rule? If so, this might be a good example to extend https://github.com/github/codeql-action to support disabling a single rule.

**Comment by AleksIvanovSinglet** [comment]
> Out of curiosity, are all these results from the same rule? If so, this might be a good example to extend https://github.com/github/codeql-action to support disabling a single rule.

All of the alerts are generated from code added by a dependency and our goal is for CodeQL to scan only project owner-created code.
Through paths-ignore, it can be done easily, but unfortunately only for Py and JS, so there is no out-of-the-box way to paths-ignore dirs and files, generated by a build process.

Simultaneously, we are implementing the SonarCloud tool on the same build process and it seems to bypass that.

**Comment by ChrisCarini** [comment]
In case others find this issue in the future, I wrote a small script to bulk-dismiss code scanning alerts; see my comment here for the script: https://github.com/github/codeql/issues/8250#issuecomment-2571393199
