### ISSUE TITLE
Java: Add ArrayInit.getSize()

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#4964]
**Description of the issue**
It would be useful to add a predicate `ArrayInit.getSize()` to allow determining the size of an array initializer (e.g. size of `{'a', 'b', 'c'}` = 3)
For example:
```ql
class ArrayInit extends Expr, @arrayinit {
  ...

  /**
   * Gets the number of expressions in this initializer.
   */
  int getSize() {
    result = count(getAnInit())
  }
}
```

This could then also be used by `ArrayCreationExpr.getFirstDimensionSize()` [here](https://github.com/github/codeql/blob/8d4f7e2db7ec3b7559a3e358fd1b8a7203ce7474/java/ql/src/semmle/code/java/Expr.qll#L449).

**Comment by aschackmull** [comment]
Yes, that sounds like a reasonable addition. Feel free to open a PR with this change.
