### ISSUE TITLE
Angular2 doesn't take into account all possible DomSanitizer instances

### ISSUE THREAD

**Issue by mrthankyou** [github/codeql#4967]
**Description of the issue**

The Angular2 module has a [`domSanitizer` predicate](https://github.com/github/codeql/blob/5ead4244fe9a32e59b250a89b3aaab723ec3627f/javascript/ql/src/semmle/javascript/frameworks/Angular2.qll#L122). This predicate's logic relies on determining if the node has an underlying type from the module `@angular/platform-browse`. However, when viewing different Angular 2 examples across the internet, I see that DomSanitizer object can come from `@angular/core` as well. 

Shouldn't this predicate take into account that DomSanitizer can come from `@angular/core`?

Thanks for all the hard work guys!

**Comment by asgerf** [comment]
Thank you @mrthankyou, that's great feedback! I've opened a PR to address the issue: https://github.com/github/codeql/pull/4969

**Comment by mrthankyou** [comment]
Quick turnaround! Thanks guys!
