### ISSUE TITLE
General issue - Can‘t find the path between multi Python modules when use Taint tracking script provide by LGTM.com

### ISSUE THREAD

**Issue by yikesoftware** [github/codeql#5034]
I found this template script on [https://codeql.github.com/codeql-query-help/python/py-code-injection/](url) which is used to interpret unsanitized user input as code allows a malicious user arbitrary code execution：

```codeql
/**
 * @name Code injection
 * @description Interpreting unsanitized user input as code allows a malicious user to perform arbitrary
 *              code execution.
 * @kind path-problem
 * @problem.severity error
 * @sub-severity high
 * @precision high
 * @id py/code-injection
 * @tags security
 *       external/owasp/owasp-a1
 *       external/cwe/cwe-094
 *       external/cwe/cwe-095
 *       external/cwe/cwe-116
 */

import python
import semmle.python.security.dataflow.CodeInjection
import DataFlow::PathGraph

from CodeInjectionConfiguration config, DataFlow::PathNode source, DataFlow::PathNode sink
where config.hasFlowPath(source, sink)
select sink.getNode(), source, sink, "$@ flows to here and is interpreted as code.",
  source.getNode(), "A user-provided value"
```

Although this script is very effective when Sink and Source In the same module , it can not analyze the propagation path from Sink and Source when they are in different modules.

This is a sample：

Module 1 **vuln.py**

```python
from flask import Flask, request
import vuln_module
 
app = Flask(__name__)

@app.route('/multi_module')
def get_multi_module():
    code = request.args.get("code")
    vuln_module.exec_python_code(code)
    return "multi_module"
 
app.run(debug=True)
```

Module 2 **vuln_module.py**

```python
def exec_python_code(code):
    return eval(code)
```

I want to know if it's my reason or CodeQL is not perfect in this respect.

**Comment by yikesoftware** [comment]
Does anyone have such a problem?

**Comment by tausbn** [comment]
Hi! Thank you for your report!

I think this is the same issue as in https://github.com/github/codeql/issues/4884, where we fail to show any results when the given source code is _not_ inside a package. Could you try putting it in a package (as mentioned in the linked issue) and see if that makes the problem go away?
