### ISSUE TITLE
Only run the language that had changes on PRs

### ISSUE THREAD

**Issue by ocket8888** [github/codeql#5048]
I'm working on a CodeQL workflow for the Apache Traffic Control project and I'm having trouble understanding from documentation what exactly the CodeQL Action does and how it behaves.

I took the generated workflow and split it into four - one for each of the three languages in the project that will run on Pull Requests that modify files in those languages, and one that runs all languages on pushes to the master branch as well as on a weekly cron schedule.

However, the three separate language actions have the following warning:

> 1 issue was detected with this workflow: Please specify an on.push hook so that Code Scanning can compare pull requests against the state of the base branch.

Because our concurrent Actions quota is shared across the Apache organization on GitHub, we didn't want to run matrix tests for Go, Python, and Javascript on PRs that may only modify one language. But this seems to indicate that

1. The scans cannot operate as intended without on.push hooks and
2. That the actions when run on PRs are comparing the branch's changes to the state of 'master' and only running the necessary tests - which would cut down concurrent jobs by just making some of them extremely short-lived if not needed.

Is that accurate? If not, do you have any suggestions on how to minimize concurrent jobs while allowing the CodeQL Action to function properly?

**Comment by rneatherway** [comment]
Hi @ocket8888,

Your observations are correct. When a workflow analyses the head or merge commit of a PR (normally triggered by `on: pull_request`) Code Scanning compares the uploaded results against those for the base branch's HEAD at that time. We select the correct base results by looking for those for the same tool, workflow and matrix variables.

This means that results for a particular language need to be generated by a single workflow file. One approach that you could use would be to have three workflow files, one per language. In each of those files you can then specify the correct `on.pull_request.paths` pattern(s) for that language (Docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths).

I think that this will give you the minimum number of concurrent jobs while Code Scanning will still function as intended.

A more compact definition in a single workflow file may well be possible by using something like https://github.com/dorny/paths-filter to build a dynamic `matrix` only in the `pull_request` case, or by aborting certain matrix jobs early. However, for simplicity I'd recommend one workflow file per language.

**Comment by ocket8888** [comment]
Thanks, that answers my question.
