### ISSUE TITLE
General issue on building the codeql databse

### ISSUE THREAD

**Issue by valour01** [github/codeql#5054]
Hi, I am now using codeql to analyze a large C project (i.e., Linux kernel).

It takes a rather long time to build the codeql database as I need to compile the Linux kernel. My question is whether I need to rebuild the whole database if the Linux kernel receives several new PRs. 

I guess that there should be some cache or optimization so that I do not need to rebuild the whole database if only several lines of code are updated in such a big project. 

However, I didn't find the answer. Any suggestions or comments are welcome. Many thanks.

**Comment by aibaars** [comment]
There is no way to incrementally update a CodeQL database, so you'd have to rebuild the whole database from scratch each time. You might want to grab a copy of the Linux database from https://lgtm.com/projects/g/torvalds/linux/ci/#ql .  LGTM.com regularly builds new databases.

**Comment by intrigus-lgtm** [comment]
@aibaars 
This is only building a part of the Linux Kernel isn't it?

**Comment by valour01** [comment]
Is building a part of the Linux kernel enough (i.e., the changed files) to generate a new database? I was wondering whether I can just build the changed part and combine them with the unchanged part. Not sure whether Codeql support this.

**Comment by aibaars** [comment]
> Is building a part of the Linux kernel enough (i.e., the changed files) to generate a new database? I was wondering whether I can just build the changed part and combine them with the unchanged part. Not sure whether Codeql support this.

CodeQL does not support that unfortunately.

**Comment by aibaars** [comment]
> @aibaars
> This is only building a part of the Linux Kernel isn't it?

You're right. I think LGTM runs `make depconfig; make` so whatever is compiled by that by default is included in the database.

**Comment by intrigus-lgtm** [comment]
@aibaars I think this issue can be closed :)
