### ISSUE TITLE
Unclear QL Language specification for `forex(| formula)`

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/codeql#5060]
**Description of the issue**
While looking at [this code](https://github.com/github/codeql/pull/4214/files/22fbf90a4e5557b7186fac9159b9c7d331c297be#diff-5b22c5f8bdcd2d5c5263013ef6e6d195fe9051f6777ee83827d237ebffb01640R17-R22) I was wondering how a `forex(| formula)` works. Per the [QL language specification](https://codeql.github.com/docs/ql-language-reference/ql-language-specification/) this should not even be a valid QL program I think (If I understood the spec right).
The spec says:
```ql
quantified ::= "exists" "(" expr ")"
           |   "exists" "(" var_decls ("|" formula)? ("|" formula)? ")"
           |   "forall" "(" var_decls ("|" formula)? "|" formula ")"
           |   "forex"  "(" var_decls ("|" formula)? "|" formula ")"
```
So a `forex` should always have a `var_decls`, right?
And a `var_decls` is defined as:
```ql
var_decls ::= var_decl ("," var_decl)*
var_decl ::= type simpleId
```
so it needs at least one `var_decl`. And a `var_decl` has to contain a `type` and an identifier `simpleId`.
This `simpleId` can then either be a `lowerId | upperId`, so either an identifier that starts with a lower-case char or an identifier that starts with an upper-case char.

So how does `forex(| formula)` work?
The part before the `|` and after the `(` can not be a `var_decl` as it doesn't even contain a `simpleId`...

Did I miss something obvious? 
Pinging @alexet as they recently worked on #4914 which was also spec related.

**Comment by alexet** [comment]
Thanks for the report

The forms are pretty useless but simply follow the existing rules to extremes where they are empty. So `forex(| formula)` basically takes the tuple we are testing, extends it with no values (which always succeeds) and then tests that with `forumla`. This is equivalent to `formula`. The other forms of `exists`, `forall` and `forex` behave similarly. They can ocassionally be useful for code-generation tools to avoid having to special case degenerate cases there but are mostly useless for hand-written code.

The `var_decl` rule probably should have an empty case in the spec to match the implementation.

**Comment by intrigus-lgtm** [comment]
> Thanks for the report
> 
> The forms are pretty useless but simply follow the existing rules to extremes where they are empty. So `forex(| formula)` basically takes the tuple we are testing, extends it with no values (which always succeeds) and then tests that with `forumla`. This is equivalent to `formula`. The other forms of `exists`, `forall` and `forex` behave similarly. They can ocassionally be useful for code-generation tools to avoid having to special case degenerate cases there but are mostly useless for hand-written code.
> 
> The `var_decl` rule probably should have an empty case in the spec to match the implementation.

Thanks for the explanation!
