### ISSUE TITLE
False positive during a 6-fold loop

### ISSUE THREAD

**Issue by SteffenSeckler** [github/codeql#5073]
**Description of the false positive**

False positive during a 6-fold loop. For details, see URL.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/AutoPas/AutoPas/snapshot/7ffb8dcb79b2cc9074455a1765ce718364266644/files/examples/md-flexible/src/Objects/Sphere.h#x741c22af364e960e:1

**Comment by jbj** [comment]
Thank you for reporting this problem. I can see the false positive clearly in the URL you're providing, but I can't reproduce it. In the latest version of the same file, https://lgtm.com/projects/g/AutoPas/AutoPas/latest/files/examples/md-flexible/src/Objects/Sphere.h?sort=name&dir=ASC&mode=heatmap, the alert isn't there. Have you done something to suppress the alert?

**Comment by SteffenSeckler** [comment]
somehow this alert was always going on and off lately.
Here, it vanished:

**Comment by jbj** [comment]
I can see it's an alert that comes and goes, making it hard for us to debug. Next time the alert appears on your default branch, meaning it shows up on [the Alerts tab](https://lgtm.com/projects/g/AutoPas/AutoPas/alerts/), please download [the corresponding CodeQL database](https://lgtm.com/projects/g/AutoPas/AutoPas/ci/#ql) and let us know. Then we'll try to debug what went wrong.

**Comment by jbj** [comment]
This issue is likely caused by the extractor crashing while building the database. That's something we'll have to investigate separately. As a workaround, there's a good chance that https://github.com/github/codeql/pull/5696 will make the false positive alert go away.

**Comment by jbj** [comment]
I note that the issue hasn't manifested since #5696 was deployed on lgtm.com on April 28. If it happens again, please reopen this issue.
