### ISSUE TITLE
Error: init action failed: HttpError: API rate limit exceeded for installation ID 7125406

### ISSUE THREAD

**Issue by woody-apple** [github/codeql#5106]
**Description of the issue**

For the last few days we've been seeing lots of intermittent failures like this one:
https://github.com/project-chip/connectedhomeip/runs/1841598839

Is this a configuration issue on our side, or any ideas about how to resolve this?

**Comment by criemen** [comment]
Hi,

it seems that the token that actions uses to talk to github got rate-limited.
The token is allowed to issue 1000 commands per hour and repository.
This is not a CodeQL issue per se, but more a general artifact of how you use actions.

In short, re-trying the build should work.
If the problem persists, you're probably running too many jobs that have, in some sense, too much interaction with the GitHub API.

**Comment by adityasharad** [comment]
We'll close this for now, but please feel free to reopen it if you're seeing it more frequently on CodeQL workflow runs.
