### ISSUE TITLE
LGTM can't build projects which use NDK

### ISSUE THREAD

**Issue by porcupineyhairs** [github/codeql#5109]
I was trying to build [reyhoo/collection](https://github.com/reyhoo/collection/). There were a few build errors so I removed a few files and created a new project with the same code [here](https://github.com/porcupineyhairs/collection/). Unfortunately, LGTM can't seem to find the `NDK` libraries in the build path. See the LGTM build log [here](https://lgtm.com/projects/g/porcupineyhairs/collection/logs/languages/lang:java).

There are other projects similar to this one which fail due to the `NDK` issue too. Can someone help me figure out how to fix this?

**Comment by criemen** [comment]
Thank you for your message.
I reached out to the responsible engineering team about the issue, and will get back to you once I hear from them.

**Comment by criemen** [comment]
Hi,

the SDK version 30 is live now.
You also might need to update your gradle plugin - see this stackoverflow post for more information: https://stackoverflow.com/questions/52193274/no-toolchains-found-in-the-ndk-toolchains-folder-for-abi-with-prefix-mips64el-l/52402004#52402004

Please reopen the issue if you need more help.
