### ISSUE TITLE
CodeQL CLI Extractor Backtraces, Missing Files

### ISSUE THREAD

**Issue by kmh11** [github/codeql#5115]
I've gotten lots of backtraces and missing files with https://github.com/litecoin-project/litecoin, https://github.com/Bitcoin-ABC/bitcoin-abc, and https://github.com/tensorflow/tensorflow. All builds were done in WSL 2 (Hyper-V VM) on Arch Linux with CodeQL CLI v2.4.3 or v2.4.2.

Here's the litecoin build, which uses C++11. If you can't reproduce or otherwise need the others I can send the details/logs for those too.

```
$ ./autogen.sh
$ ./configure --with-gui=no --disable-wallet
$ ~/codeql/codeql database create db --language=cpp -c "make -j8"
```

Here are the backtraces:

```
grep "^CodeQL C++ extractor: Backtrace:$" -A 20 db/log/build-tracer.log > /mnt/c/Users/kmh11/Documents/build-tracer.log
```

[build-tracer.log](https://github.com/github/codeql/files/5946897/build-tracer.log)

I can send you the full log privately if necessary. The database is still "created successfully" and querying the files that are in the database works, but there are many files missing from the source archive:

```
$ unzip -l db/src.zip | grep txmempool
$ ls src | grep txmempool
libbitcoin_server_a-txmempool.o
txmempool.cpp
txmempool.h
$ unzip -l db/src.zip | grep net
    19923  2021-02-08 15:45   home/kmh/codeql-builds/litecoin/src/netaddress.cpp
     6313  2021-02-08 15:45   home/kmh/codeql-builds/litecoin/src/netaddress.h
    28100  2021-02-08 15:45   usr/include/netdb.h
     4277  2021-02-08 15:45   usr/include/arpa/inet.h
     1264  2021-02-08 15:45   usr/include/bits/netdb.h
     6982  2021-02-08 15:45   usr/include/net/if.h
    21912  2021-02-08 15:45   usr/include/netinet/in.h
    10490  2021-02-08 15:45   usr/include/netinet/tcp.h
     2897  2021-02-08 15:45   usr/include/rpc/netdb.h
$ ls src | grep net
libbitcoin_common_a-netaddress.o
libbitcoin_common_a-netbase.o
libbitcoin_server_a-net.o
libbitcoin_server_a-net_processing.o
netaddress.cpp
netaddress.h
netbase.cpp
netbase.h
net.cpp
net.h
netmessagemaker.h
net_processing.cpp
net_processing.h
```

Thank you for looking into this!

**Comment by criemen** [comment]
Hi,
this issue has been fixed in the not-yet-released CLI version 2.4.4.

I believe that a suitable workaround is to use clang/clang++ as compiler instead of gcc, if you don't want to wait for our next release.
