### ISSUE TITLE
C++: DataFlow/TaintFlow Modelling Question

### ISSUE THREAD

**Issue by creative16** [github/codeql#5116]
Hello,

I'm trying to use `DataFlowFunction` and `TaintFunction` to model some functions in a similar manner to how `memcpy()` and `StdContainer::data()` is modelled in the libraries.

As a minimum example, I have the following source code:
```cpp
class WrapperClass {
  public:
    WrapperClass() { ptr = new char[100]; }
    ~WrapperClass() { delete[] ptr; }
    char * data() const { return ptr; }

  private:
    char * ptr;
};

void my_memcpy(char * dst, char * src, size_t len) {
  for(size_t i = 0; i < len; i++) {
    dst[i] = src[i];
  }
}

int main(void) {
  WrapperClass w;
  char hello[] = "HelloWorld";

  hello[0] = 'A';
  my_memcpy(w.data(), hello, 10);

  return (int)(w.data()[0]);
}
```

In the following query, I am trying to detect a taint from `'A'` to the use of `w` in the return statement:
```ql
class WrapperClass extends Class {
  WrapperClass() { this.hasName("WrapperClass") }
}

class WrapperDataFunction extends MemberFunction, TaintFunction {
  WrapperDataFunction() {
    this.hasName("data") and 
    this.getDeclaringType() instanceof WrapperClass
  }

  // From a write to data() to the qualifier object
  override predicate hasTaintFlow(FunctionInput input, FunctionOutput output) {
    input.isReturnValueDeref() and 
    output.isQualifierObject()
  }
}

class MyMemcpyFunction extends DataFlowFunction {
  MyMemcpyFunction() { this.hasName("my_memcpy") }

  override predicate hasDataFlow(FunctionInput input, FunctionOutput output) {
    input.isParameterDeref(1) and 
    output.isParameterDeref(0)
  }
}

from FunctionCall memcpy, FunctionCall data, DataFlow::Node src, DataFlow::Node sink, Assignment assign
where
  memcpy.getTarget() instanceof MyMemcpyFunction and 
  data.getTarget() instanceof WrapperDataFunction and 
  data.getEnclosingStmt() instanceof ReturnStmt and 
  src.asExpr() = assign.getRValue() and 
  sink.asExpr() = data.getQualifier() and 
  TaintTracking::localTaint(src, sink)
select sink, "Flow from $@", src, "source"
```

However, the query above is not returning any results. The issue seems to be the `hasTaintFlow()` predicate for `WrapperDataFunction` (which I modelled similarly to how the `data()` function for containers are modelled), as setting `sink.asDefiningArgument() = memcpy.getArgument(0)` does return a result as expected.

As I'm not sure if this is a misunderstanding on my part or not, I would really appreciate some insight into this. Thanks!

**Comment by geoffw0** [comment]
Hi creative16,
```
override predicate hasTaintFlow(FunctionInput input, FunctionOutput output) {
  input.isReturnValueDeref() and 
  output.isQualifierObject()
}
```
This models taint flow in through the reference returned by `data`, as in:
```
my_memcpy(w.data(), hello, 10);
```
but it doesn't model flow out through the reference returned by `data`, as in:
```
return (int)(w.data()[0]);
```
I believe you want something like:
```
override predicate hasTaintFlow(FunctionInput input, FunctionOutput output) {
  // flow from data inside the class (qualifier) to returned reference
  input.isQualifierObject() and
  output.isReturnValueDeref()
  or
  // reverse flow from writes to the returned reference to the class (qualifier)
  input.isReturnValueDeref() and
  output.isQualifierObject()
}
```
Does that change get you the full flow you want?

**Comment by creative16** [comment]
Hello @geoffw0 , thanks for your reply.

Not quite. My sink is actually `data.getQualifier()`, and not the value returned by `data`. So wouldn't the original version of `hasTaintflow` be sufficient to capture the flow into the qualifier?

**Comment by geoffw0** [comment]
Hmm, I'm not sure I'd expect taint to reach the qualifier of the call to `data`.  The qualifier is a reference to an object `w` (that is tainted), but the reference itself isn't tainted and the tainted data within `w` it isn't being extracted by the qualifier - the call to `data` does that.  So I would expect to find taint in the return value of the call.

What is the wider context here?  I had assumed what you're really interested in is taint reaching the `return` expression.

**Comment by creative16** [comment]
Hello @geoffw0,

so following your reply, I tried a couple of things.

First, I modified `hasTaintFlow` as you suggested, and modified the query as follows such that the sink is the expression of the `ReturnStmt`:
```ql
from FunctionCall memcpy, FunctionCall data, DataFlow::Node src, DataFlow::Node sink, Assignment assign,
  ReturnStmt ret
where
  memcpy.getTarget() instanceof MyMemcpyFunction and 
  data.getTarget() instanceof WrapperDataFunction and 
  data.getEnclosingStmt() = ret and
  src.asExpr() = assign.getRValue() and 
  sink.asExpr() = ret.getExpr() and
  TaintTracking::localTaint(src, sink)
select sink, "Flow from $@", src, "source"
```
From what I gather, I should expect a result. However, the query did not produce any results.

Regarding what you wrote about not expecting the taint to reach the qualifier of the call to `data`, I wrote a simpler example as follows:
```cpp
class TestClass {
  public:
    void setValue(int n) { x = n; }
    int getValue() { return x; }
  
  private: 
    int x;
};

int main(void) {
  TestClass t;

  t.setValue(42);

  return t.getValue();
}
```
In the following query, I attempt to find a taint from the argument to `setValue` to the **qualifier** of the call to `getValue`:
```ql
class TestClass extends Class {
  TestClass() { this.hasName("TestClass") }
}
  
class SetValueFunction extends MemberFunction, TaintFunction {
  SetValueFunction() {
    this.hasName("setValue") and 
    this.getDeclaringType() instanceof TestClass
  }
  
  override predicate hasTaintFlow(FunctionInput input, FunctionOutput output) {
    input.isParameter(0) and 
    output.isQualifierObject()
  }
}
  
class GetValueFunction extends MemberFunction {
  GetValueFunction() {
    this.hasName("getValue") and 
    this.getDeclaringType() instanceof TestClass
  }
}

from FunctionCall setValue, FunctionCall getValue, DataFlow::Node src, 
  DataFlow::Node sink
where
  setValue.getTarget() instanceof SetValueFunction and 
  getValue.getTarget() instanceof GetValueFunction and 
  src.asExpr() = setValue.getArgument(0) and 
  sink.asExpr() = getValue.getQualifier() and 
  TaintTracking::localTaint(src, sink)
select sink, "Flow from $@", src, "source"
```
If I understood your reply correctly, I should not expect this query to produce any results. However, running this query found the taint from `42` to the qualifier of the call to `getValue`.

As for the wider context, I am not only interested in finding the reaching the `return` expression, but I would also be interested to find accesses to `WrapperClass` objects that are tainted. The examples I have given are really just minimal examples to illustrate the problem I'm facing.

**Comment by geoffw0** [comment]
I've done a bit of my own investigation - as best I can tell the flow from argument 1 to 0 of `my_memcpy` works but the 'reverse flow' into `w` through the return value of `w.data()` does not:
```
my_memcpy(w.data(), hello, 10);
```
@mathiasvp do you have any ideas?

**Comment by MathiasVP** [comment]
I think this is a problem on our side. We're misinterpreting the constness annotation on the `data` member function in `lvalueToUpdate` in `AddressFlow.qll`:

```codeql
private predicate lvalueToUpdate(Expr lvalue, Expr outer, ControlFlowNode node) {
  (
    exists(Call call | node = call |
      outer = call.getQualifier().getFullyConverted() and
      outer.getUnspecifiedType() instanceof Class and
      not call.getTarget().hasSpecifier("const")
    )
    or
    // ...
  )
  or
  // ...
}
```
I think the intuition of that constness conjunction above is to remove flow when it shouldn't be possible to update the qualifier, but (as you've shown in your example), that isn't always guaranteed :) I'll file an issue for this!

**Comment by creative16** [comment]
Hello @MathiasVP , yup I can confirm that the taint is found when the `const` specifier is removed from the `data` member function. 

Thanks so much for looking into this!
