### ISSUE TITLE
LGTM.com - false positive on ReDoS

### ISSUE THREAD

**Issue by tshino** [github/codeql#5145]
**Description of the false positive**

It is reported that a regular expression `/(a|b)+/` may cause exponential backtracking.
https://github.com/tshino/vscode-vz-like-keymap/pull/7/commits/720e020e0f2d47e8c5b8f717be4990faf2d40176

I think it is a false positive.

**URL to the alert on the project page on LGTM.com**

**Comment by erik-krogh** [comment]
Yes. That is a false positive.   

The ReDoS query has been updated a lot recently, and it seems that the FP you reported here has already been fixed.   
So the alert should go away on it's own with the next update of CodeQL on Code scanning.   

I've added your regular expressions to our ReDoS test suite: #5146

**Comment by tshino** [comment]
Thank you!
