### ISSUE TITLE
General issue - JavaScript data flow analysis

### ISSUE THREAD

**Issue by gdemarcsek** [github/codeql#5177]
**Description of the issue**
The following DOM XSS vector is recognized nicely (CWE-079):

```javascript
function test() {
    let x = new URLSearchParams(location.search).get('x');
    document.getElementById("sink").innerHTML = x;
}
```

But this one is not recognized:

```javascript
function test() {
    [document.getElementById("sink")][0].innerHTML = new URLSearchParams(location.search).get('x');
}
```

Is this a limitation of the JS data flow analysis library, generic limitation of the methodology or just an uncovered scenario (e.g. not propagating taint through array literals to their elements?)

My original test case was more complicated and a bit more realistic (like I could imagine _similar_ code to be written IRL):

```javascript
function f(e) {
    e.innerHTML = new URLSearchParams(location.search).get('x');
}
[document.getElementById("sink")].map(f);
````

But this didn't work so I started to simplify. Same for a forEach + arrow function.

**Comment by hmakholm** [comment]
@github/codeql-javascript might have some input here.

**Comment by erik-krogh** [comment]
I would say it's an uncovered scenario. 

In [`DOM.qll`](https://github.com/github/codeql/blob/main/javascript/ql/src/semmle/javascript/security/dataflow/DOM.qll) we track which values are DOM nodes.   
We don't use the full featured data flow analysis to track these DOM nodes, we instead use a more lightweight approach we call type tracking.   
Getting type-tracking to support your original test case would only require a small change to the [`ArrayCreationStep` class](https://github.com/github/codeql/blob/main/javascript/ql/src/semmle/javascript/Arrays.qll#L242).  
Specifically, changing `ArrayCreationStep` to the below would support your original test case. 

```CodeQL
private class ArrayCreationStep extends PreCallGraphStep {
  override predicate storeStep(DataFlow::Node element, DataFlow::SourceNode obj, string prop) {
    exists(DataFlow::ArrayCreationNode arr, int i |
      element = arr.getElement(i) and
      obj = arr and
      if arr = any(PromiseAllCreation c).getArrayNode()
      then prop = arrayElement(i)
      else prop = arrayElement()
    )
  }
}
```

However, this might introduce false positives if an array contain elements of different types. 

But it's something I think is worth investigating.

**Comment by erik-krogh** [comment]
> But it's something I think is worth investigating.

I've now merged the above suggestion as part of [another PR](https://github.com/github/codeql/pull/10126).  
So the scenario you describe is now supported.
