### ISSUE TITLE
Getting Dataflow graph for method

### ISSUE THREAD

**Issue by navyasri1** [github/codeql#5213]
I want to get a dataflow graph from a method to all the methods it has called till it ends at `.class` file in a springboot repo. Could you help me how to proceed on this as methods cannot be added to dataflow as source or sink.

**Comment by intrigus-lgtm** [comment]
I did not fully understand your question, but this part ...
> a (...) graph from a method to all methods it has called

... suggests that you may want a [control flow graph](https://en.wikipedia.org/wiki/Control-flow_graph) ([Code QL ControlFlowGraph class](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/java/ControlFlowGraph.qll/module.ControlFlowGraph.html))?

If you indeed want a dataflow graph, then someone else has to answer your question.

**Comment by smowton** [comment]
if I understand, you actually want the call graph? So f() calls g() calls h() and h()  is somewhere in the spring-boot package?

If so I suggest looking at Callable.calls(Callable), a method that represents one edge of the call graph, and `getDeclaringType().hasQualifiedName` which can be used to check the package and class name of the class declaring a Callable (constructor or method)
