### ISSUE TITLE
Primitive predicate string::matches behaves incorrectly for some patterns

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#5230]
The primitive predicate [`string::matches(string pattern)`](https://codeql.github.com/codeql-standard-libraries/java/predicate.string$matches.1.html) should only consider unescaped `_` and `%` as placeholder, every other character should be matched literally.
However, it appears for certain patterns it is not matching other characters literally. So far I have only noticed this for patterns similar to `[%|%]`:
```ql
from string s, string p
where
  s = [
    "[0-9]",
    "0-9",
    "[]",
    "[0-9",
    "0-9]",
    "[0]",
    "0",
    ""
  ]
  and p = [
    "%[%|%]%",
    "[%|%]",
    "%[|]%",
    "%|%]%",
    "%[%|%",
    "%|%",
    "%[]%"
  ]
  and s.matches(p)
select s, p
```
[Query console link](https://lgtm.com/query/2136406237046830260/)

This yields a lot results which are not correct, e.g.:
- `"".matches("%[%|%")`
- `"0-9".matches("%|%]%")`

**Comment by alexet** [comment]
Thanks for the bug report. 

I can confirm this is a bug. It looks like the issue is with patterns containing `|` where it is incorrectly treated as alternation.

**Comment by alexet** [comment]
This should be fixed in the next release of codeql.

**Comment by Marcono1234** [comment]
Thank you very much for this fast response and fix!
