### ISSUE TITLE
CPP: underlying type of FullyConverted 1D ArrayExpr in AssignAndExpr gets matched but not sanitized?

### ISSUE THREAD

**Issue by adriaanjacobs** [github/codeql#5234]
**Description of the issue**

In reviewing the following C code:
```
unsigned long int accepts[SOME_NUMBER];
unsigned long int second_array[SOME_NUMBER];

unsigned long int any_set |= (accepts[j] &= second_array[j]);
```

the following AST is generated:
![image](https://user-images.githubusercontent.com/48367267/108634693-0b0af900-747b-11eb-9ddd-d2357653d231.png)
(This is all AST nodes on the `any_set` assignment line of code).

I can successfully match this kind of thing using the following quick and dirty query, which quite literally corresponds to the AST View:
```
from AssignOrExpr e, ArrayExpr ae
where e.getLValue() instanceof VariableAccess 
        and e.getRValue() instanceof AssignAndExpr
        and e.getRValue().(AssignAndExpr).getLValue() = ae
        and ae.getArrayBase().getFullyConverted() instanceof ArrayToPointerConversion
        and not hasAddressType(ae)
select ae
```

However, when I use this exact predicate to sanitize flow in a taint tracking configuration it does not sanitize taint from `accepts` to `any_set`. I originally used the following predicate to do this (as I want to disallow flow from the base of an array to an element looked up in that array):
```
override predicate isSanitizer(DataFlow::Node intermediate) {
        exists(ArrayExpr arrayaccess | intermediate.asExpr() = arrayaccess
            and not hasAddressType(arrayaccess)
        )
}
```
But this failed as well, which is why I started investigating it. 

Here is the definition of the `hasAddressType` predicate, nothing fancy:
```
predicate hasAddressType(Expr e) {
    isAddressType(e.getFullyConverted().getUnderlyingType())
}

predicate isAddressType(Type type) {
    type instanceof PointerType 
    or type instanceof ArrayType 
    or type instanceof FunctionPointerType
}
```

Am I missing something obvious here? When I use both at the same time in the sanitizer (OR) like so:
```
override predicate isSanitizer(DataFlow::Node intermediate) {
      exists(ArrayExpr arrayaccess | intermediate.asExpr() = arrayaccess
          and not hasAddressType(arrayaccess)
      )
      or exists(AssignOrExpr e, ArrayExpr ae | intermediate.asExpr() = ae
          and e.getLValue() instanceof VariableAccess 
          and e.getRValue() instanceof AssignAndExpr
          and e.getRValue().(AssignAndExpr).getLValue() = ae
          and ae.getArrayBase().getFullyConverted() instanceof ArrayToPointerConversion
          and not hasAddressType(ae)
      )
}
```
the ArrayExpr still gets through. 

It is quite remarkable that at every place this happens (is reported on at least 2 other places as well), there is some kind of bit manipulation / value of assignment expressions used thing going on, so I can only think it has something to do with that?

What could I be doing wrong?

**Comment by MathiasVP** [comment]
Hi @adriaanjacobs,

I think the problem is that your sanitizer is choosing a _slightly_ different expression than the expression that's actually part of the dataflow path. I think it'll work if you change your `isSanitizer` to be something like:

```codeql
override predicate isSanitizer(Node intermediate) {
  exists(AssignOrExpr e, ArrayExpr ae |
    intermediate.asExpr() = ae.getArrayBase() and // <--- Note the difference between this line and your version.
    e.getLValue() instanceof VariableAccess and
    e.getRValue() instanceof AssignAndExpr and
    e.getRValue().(AssignAndExpr).getLValue() = ae and
    ae.getArrayBase().getFullyConverted() instanceof ArrayToPointerConversion and
    not hasAddressType(ae)
  )
}
```

**Comment by adriaanjacobs** [comment]
Thank you @MathiasVP, using your suggestion I updated the santization from 
```
exists(ArrayExpr arrayaccess | intermediate.asExpr() = arrayaccess
    and not hasAddressType(arrayaccess)
)
```
to
```
or exists(ArrayExpr ae | intermediate.asExpr() = ae.getArrayBase()
    and ae.getFullyConverted().getUnderlyingType().getPointerIndirectionLevel() <= 1
)
```
to match all array subscript operations such that the resulting element is not tainted simply because the base address is tainted.

I tried this before however, only using `= 1` instead of `<= 1` (which I tried for the first time just now), and only the `<= 1` works. Does this mean for array bases that are of ArrayType, the pointerIndirectionLevel() is 0? As far as I could follow it, ArrayType inherits that predicate from DerivedType, which calls it on getBaseType() which is just Type I believe (where the implementation simply returns 0). Is this to explicitly make a difference between an array that has not implicitly been converted to a pointer yet, and one that did? Intuitively I though arrays would have a pointerIndirectionLevel of at least 1.

**Comment by MathiasVP** [comment]
> I tried this before however, only using `= 1` instead of `<= 1` (which I tried for the first time just now), and only the `<= 1` works. Does this mean for array bases that are of ArrayType, the pointerIndirectionLevel() is 0?

Indeed, it looks like the `pointerIndirectionLevel` predicate on `ArrayType`s evaluates to 0. Most expressions of array types will decay to pointer types as soon as you do anything to them, though. So in practice, when you look at the fully converted expression, the type will have a `pointerIndirectionLevel()` result that is at least 1.

Note that, in your example:
```codeql
or exists(ArrayExpr ae | intermediate.asExpr() = ae.getArrayBase()
   and ae.getFullyConverted().getUnderlyingType().getPointerIndirectionLevel() <= 1
)
```
you're looking at the result type of the array expression (i.e., the type of `accepts[j]`). That type will be an `unsigned long int`, which has a `pointerIndirectionLevel()` of 0.

**Comment by adriaanjacobs** [comment]
Thank you, now it makes sense to me.
