### ISSUE TITLE
General issue - Default Maven compile command should be changed

### ISSUE THREAD

**Issue by tutorial0** [github/codeql#5235]
This problem happend when i want to scan all my old codes. I did write a lot of shit code, especially the unit-test code.

CodeQL's maven compile command now is:
`mvn clean package -f "pom.xml" -B -V -e -Dfindbugs.skip -Dcheckstyle.skip -Dpmd.skip=true -Denforcer.skip -Dmaven.javadoc.skip -DskipTests -Dmaven.test.skip.exec -Dlicense.skip=true -Drat.skip=true`

Unit test code won't execute but still be compiled, and unit test code usually have a lot of errors. 

And i can't change the command with `codeql --command` because i don't know if i should use 'mvn' or 'gradle' or something else.

**Comment by alexet** [comment]
We always compile test code so that we find as much code as possible. 

The command that you pass to `codeql --command` should just be the command you normally use to do a clean compile compile. If you want to skip tests then you can skip them in your compile command.

**Comment by tutorial0** [comment]
> We always compile test code so that we find as much code as possible.
> 
> The command that you pass to `codeql --command` should just be the command you normally use to do a clean compile compile. If you want to skip tests then you can skip them in your compile command.

But i don't known what's my compile command when i scan a bunch of projects. Maybe it's a build with gradle or ant.

**Comment by alexet** [comment]
You could try creating you own script that guesses which command to run that is more suited to your specific problems.
