### ISSUE TITLE
How to include swagger generated classes in code ql db in Java

### ISSUE THREAD

**Issue by manikanta689** [github/codeql#5241]
The swagger(open API) generates the source code while running the mvn clean command and those files are placed in generated-sources folder.Is there any way these source code can be included in code ql db when i try to create db for the source repo.I need this files also available to analyse the code properly.

**Comment by alexet** [comment]
As long as the generated classes are compiled during extraction then they should be included in the database. Is your build a clean build? If it isn't then maven may be reusing the compilation and hence we could miss them.

**Comment by aeisenberg** [comment]
If you're still having a problem, feel free to re-open this issue.
