### ISSUE TITLE
General issue - We need integration for one dashboard for security vulnerabilities reporting to github issues.

### ISSUE THREAD

**Issue by csayler** [github/codeql#5261]
**Description of the issue**
We currently have multiple venerability tools in our CICD for SSDLC. We are currently using Github Issues for reporting vulnerabilities automatically with GitHub actions. 

1. We need codeql to report each vulnerability for a repository to create a GitHub issues for the developer to set a priority in their sprints. 
2. OneDashboard effect for all GitHub repository issues.
3. Two tabs just seems a lot of jumping back and forth.

We need a method through API/CLI to report vulnerability from codeql to generate a GitHub issue for the one dashboard effect on repository issues. 

All repos are internal to company or I would share.

**Comment by sj** [comment]
Thanks for your suggestions, @csayler! I've asked my colleagues to contact you directly to follow up on this. They should be able to help you further.

**Comment by csayler** [comment]
Sounds good. 

-
Craig
