### ISSUE TITLE
Java Find all the string constants hard-coded and export in CSV. Is this correct?

### ISSUE THREAD

**Issue by sbilello** [github/codeql#5312]
Do you have any suggestions for the query below? Does it cover my goal?
```
/**
 * @name Constant Recommendation
 * @kind problem
 * @problem.severity recommendation
 * @id java/example/constants/evaluation
 */
import java
where f.getType().hasName("String") and f.getAnAssignedValue().toString().indexOf("\"") != -1
select f.getLocation(), f.getAnAssignedValue().toString() 
```

Execution:
```
codeql database analyze java-database test.ql --format=csv --output=out.csv
```

I tried to improve it via

```
/**
 * @name Constant Recommendation
 * @kind problem
 * @problem.severity recommendation
 * @id java/example/constants/evaluation
 */
import java
// Try to exclude empty values  but it does not work. 
from Field f
where f.getType().hasName("String") and f.getAnAssignedValue().toString().length() > 2 and f.getAnAssignedValue().toString().indexOf("\"") != -1 
select f.getAnAssignedValue(), f.getLocation()
```

How can I have the filter to exclude all the variables with an empty String initialized?

Thanks

**Comment by Marcono1234** [comment]
> `f.getType().hasName("String")`

You can use <code>f.getType() instanceof [TypeString](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/java/JDK.qll/type.JDK$TypeString.html)</code>.

> `f.getAnAssignedValue().toString()`

This gives you the QL string representation of the expression, which is not necessarily a string constant; it could also be for example a method call: `doSomething()`

> `indexOf("\"") != -1`

This won't work. When a substring is not contained there is no result, you would have to check for `not exists(... indexOf("\""))`.

Additionally, when you are looking for string constants, I assume you are looking for [`StringLiteral`](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/java/Expr.qll/type.Expr$StringLiteral.html) (and maybe [`CompileTimeConstantExpr`](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/java/Expr.qll/type.Expr$CompileTimeConstantExpr.html) as well).

Maybe the following would work for you:
```ql
import java

from Field f, StringLiteral stringLiteral, string s
where
  f.getAnAssignedValue() = stringLiteral
  and s = stringLiteral.getRepresentedString()
  and s.length() > 2
  and not exists(s.indexOf("\""))
select s, stringLiteral.getLocation()
```

**Comment by sbilello** [comment]
Thanks for your reply. I don't need ```and not exists(s.indexOf("\""))``` because I want to get all the constants even the ones with the quote character included. I was trying to figure out that there was a constant in the previous query by checking existence of the quote character for this reason I did that statement.

How can I extend with CompileTimeConstantExpr?
I was trying to do this https://lgtm.com/query/7702411338860866318/
```
import java

from Field f, StringLiteral stringLiteral, string s, CompileTimeConstantExpr ctce
where
  f.getAnAssignedValue() = stringLiteral
  and s = stringLiteral.getRepresentedString()
  or exists(ctce.getStringValue())
select s, stringLiteral.getLocation()
```
but now it is not working and it is complaining about the s local variable?

**Comment by Marcono1234** [comment]
The reason for this is that the second operand of the disjunction (`or`) does not bind `s`. The following uses parentheses to show more clearly the disjunction:
```ql
(
  f.getAnAssignedValue() = stringLiteral
  and s = stringLiteral.getRepresentedString()
)
or (
  exists(ctce.getStringValue())
  // Here you do not bind `s`, so it could have any value
)
```
To solve this you could replace `exists(ctce.getStringValue())` with `s = ctce.getStringValue()`, and then even simplify it because `CompileTimeConstantExpr` includes `StringLiteral`:
```ql
import java

from CompileTimeConstantExpr ctce, string s
where s = ctce.getStringValue()
select s, ctce.getLocation()
```

Originally I did not include `CompileTimeConstantExpr` in the suggested code because compile time expressions are more than just hardcoded strings (see also [Java Language Specification](https://docs.oracle.com/javase/specs/jls/se15/html/jls-15.html#jls-15.29)), e.g.:
```java
class MyClass {
  private static final String CONSTANT = "test";

  public static void main(String[] args) {
    System.out.println(CONSTANT); // Read of field CONSTANT is a CompileTimeConstantExpr
    int length = (CONSTANT + "suffix").length(); // Here even the complete `CONSTANT + "suffix"` is a CompileTimeConstantExpr
  }
}
```

**Comment by sbilello** [comment]
Thanks for your reply! I am learning a lot from this thread. Is there a way to get the absolute path as result? I tried with f.getLocation() but it does not display the fullPath. I am googling about it ....

**Comment by Marcono1234** [comment]
`Location` defines the location within a file. The documentation page you have found already points in the right direction, but it appears to be written for a language other than Java, or for an older version. The CodeQL classes (except the primitive CodeQL ones, such as `string`) differ between languages; for Java the predicate is called [`File::getAbsolutePath`](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/FileSystem.qll/predicate.FileSystem$File$getAbsolutePath.0.html).

**Comment by sbilello** [comment]
I am trying to include the properties file
```
export LGTM_INDEX_PROPERTIES_FILES=true
codeql database create propdb --language=java --command='mvn -DskipTests clean install'

/**
 * @name Constant Recommendation
 * @kind problem
 * @problem.severity recommendation
 * @id java/example/constants/evaluation
 */
import java

from Field f, StringLiteral stringLiteral, string s
where
  f.getAnAssignedValue() = stringLiteral
  and s = stringLiteral.getRepresentedString()
  and s.length() > 0
select s,  "https://github.com/sbilello/asset-service/" + f.getLocation().getFile().getRelativePath() + "#L" + f.getLocation().getStartLine()

```
I might need to extract all the properties value from a file with their location 
Dirty solution export this via bash script or I was trying via the codeql query but I am not sure if I can make the union of the results like SQL of two queries or I need to run 2 separate queries and merge the results later on?

**Comment by Marcono1234** [comment]
> or I was trying via a codeql query but I am not sure if I can make the union of the results like SQL of two queries or I need to run 2 separate queries and merge the results later on?

I think you have to declare all expected columns in the `select` clause, so having a union of unrelated tables is probably not possible (though I might be wrong here, maybe a maintainer can clarify this). Could you please describe a little bit more in detail what you are trying to find, or how your Java Properties query looks like?

----

Also next time [GitHub Discussions](https://github.com/github/codeql/discussions) might be better suited, though I am not completely sure what the maintainers prefer for usage discussions such as this.

**Comment by sbilello** [comment]
I don't know how to make the Java properties query. I am going to close this conversation and thank you very much for your help! https://github.com/github/codeql/discussions/5321
