### ISSUE TITLE
Feature request: generate AST for code snippet on LGTM.com

### ISSUE THREAD

**Issue by adriaanjacobs** [github/codeql#5314]
Sometimes I want to see how CodeQL's AST would represent a certain syntactical construct. I was wondering if it was on the roadmap for LGTM.com to have a feature where you could paste a small code snippet and the site would show you the AST for that snippet right now?

To experiment with this kind of thing, I have a small VSCode CodeQL workspace set up now with a Makefile that can generate CodeQL databases using the CLI. I noticed it causes problems though if I regenerate the database while it is still selected as the active database in the CodeQL extension. So I deselect the database in the extension, remove the database, then reroll the database (using the brutal mode), then select it again in the extension and then I can view the AST/run queries on files again. Even then (but that might be because I left some files open from the zipped source archive, not sure) it (rarely, yet sometimes) still won't run/cause issues (due to missing cached files etc).

If, on the other hand, I could just put some code snippets on LGTM.com and generate the AST from that, that would be such a useful way of checking how CodeQL represents a certain code pattern and improve my queries accordingly.

Is something like that in the works or is there any way I could contribute to such a feature?

**Comment by adityasharad** [comment]
@adriaanjacobs thanks for the suggestion, and apologies that this question slipped through the cracks for so long.

We're not planning such a feature to process code snippets on LGTM.com. However, I think the AST viewer in the CodeQL extension for VS Code continues to be your best bet here.
It sounds like you've got a decent workflow to create databases. An alternative way to quickly create databases from snippets of source code is to use the CodeQL test functionality: see https://codeql.github.com/docs/codeql-for-visual-studio-code/testing-codeql-queries-in-visual-studio-code and https://codeql.github.com/docs/codeql-cli/testing-custom-queries, and the test cases in this repository (under `<language>/test`) that you can copy and modify. When a test fails, it leaves behind a `.testproj` folder, which is a valid CodeQL database you can import into the extension and run the AST viewer on.
We also fixed some bugs recently with the VS Code extension's handling of removed databases, so hopefully your workflow of removing and re-adding a database when modified will work better.

Let us know if you have further questions, or continue to have trouble getting this to work.
