### ISSUE TITLE
Same path reported twice for path queries

### ISSUE THREAD

**Issue by adriaanjacobs** [github/codeql#5315]
A lot of times when running path queries the exact same path is reported twice, as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/48367267/109812725-b3b01a00-7c2c-11eb-878e-455f171de0c6.png)

I have a lot more examples of this, but since it is so common I think I just don't understand what's going on here or why it happens.
Why does this occur? 

A variant of this is where only a part of the path is reported again, which I can kind of comprehend for specific queries. But why would the tool report the exact same path result twice?

**Comment by intrigus-lgtm** [comment]
Looking at your screenshot, the paths are not the same.
The description of the nodes may make it seem as if they are the same, but for example node 1.2 and 2.2 have different locations (xyz.c:327:16 vs xyz.c:453:16)

**Comment by adriaanjacobs** [comment]
Oh, you are right indeed, my bad. Looking back on other examples, they are similar cases. Thank you.
