### ISSUE TITLE
LGTM doesn't remove checks for JavaScript in a Python project

### ISSUE THREAD

**Issue by lucasgcb** [github/codeql#5351]
**Description of the issue**

Our open source Python project utilizes LGTM for analyzing our Python code.

However, we have documentation bundled and some of it has a couple JavaScript snippets. This wasn't a problem before, but now we are working on a new version and LGTM keeps giving us false checks because it fails to find this previous JavaScript code. This is a problem for Pull Requests because it classifies the PRs as a failed integration.

I got here by finding #3175 and was wondering if there is now a way we can fix this ourselves, or if it should be cleared up manually for us.

Our repository: https://github.com/magpylib/magpylib
Our LGTM page: https://lgtm.com/projects/g/magpylib/magpylib/
Our latest JavaScript check fail on LGTM: https://lgtm.com/projects/g/magpylib/magpylib/rev/pr-20ab46641b1b976106773e2fda8209c536a625a3

Thank you.

**Comment by yoff** [comment]
Hi, I have turned off javascript analysis for your project. I do not think that you can do this yourself.

**Comment by lucasgcb** [comment]
> Hi, I have turned off javascript analysis for your project. I do not think that you can do this yourself.

Thank you, it's no longer triggering these checks.
It would be nice to let users do this themselves in the future.

**Comment by yoff** [comment]
> It would be nice to let users do this themselves in the future.

Since your repository is on GitHub, the future is here! As an alternative to using LGTM, you can do code scanning via actions. With that setup, everything is user configurable. See [docs for code scanning](https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning).
