### ISSUE TITLE
LGTM.com - false positive (regular expression always matches)

### ISSUE THREAD

**Issue by thorn0** [github/codeql#5352]
**Description of the false positive**

`IS_POSSIBLY_SCSS = /(\w\s*:\s*[^:}]+|#){|@import[^\n]+(?:url|,)/;`

It says "This regular expression always matches when used in a test here, as it can match an empty substring.", but it's easy to find counterexamples.

```js
IS_POSSIBLY_SCSS.test('')
false
IS_POSSIBLY_SCSS.test('foo')
false
```

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/prettier/prettier/snapshot/e8a2bd733d824198f14326c9c4a96ec4f2a5452b/files/src/language-css/utils.js?sort=name&dir=ASC&mode=heatmap#xbdbfbea60ccad92:1

**Comment by erik-krogh** [comment]
Thanks for the report. 
This is definitely a false positive, and I will try to fix it.    

It looks like our parser is having trouble with the unescaped `{` (right next to `|@import`). 
As I read [the spec](https://tc39.es/ecma262/#prod-Atom) an unescaped `{` is technically a syntax error, and our parser treats it as such. 

However, every other Javascript parser doesn't think it's a syntax error.  
So we should also handle it that way.

**Comment by thorn0** [comment]
> So we should also handle it that way.

Warning that this syntax isn't really valid might make sense too.

**Comment by erik-krogh** [comment]
I've fixed our parser such that it parses your regular expression the same way as other JavaScript parsers.   
It might take a few weeks for the fix to land on LGTM.com.   

Thanks again for the report.
