### ISSUE TITLE
Track flow through multi files

### ISSUE THREAD

**Issue by Ovi3** [github/codeql#5362]
index.html:
```
<script src="./index.js"></script>
<script>
 eval(foo());
</script>
```
index.js:
```
function foo(){
    return location.hash.substr(1);
}
```
codeql query:
```
import javascript

class Cfg extends TaintTracking::Configuration {
    Cfg() { this = "Cfg" }
  override predicate isSource(DataFlow::Node node) { 
      node = DataFlow::globalVarRef("location")

  }

  override predicate isSink(DataFlow::Node node) {
      node = DataFlow::globalVarRef("eval").getACall().getArgument(0)
  }
}

from Cfg cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where cfg.hasFlowPath(source, sink)
select sink.getNode(), source, sink, "taint from", source.getNode(), "here"

```
The query can not found the flow from `location` to `eval()`. Seem like codeql is not seeing the association between `index.html` and `index.js`(`index.html` include `index.js` using script tag).

Why codeql doesn't found the flow? It there any solution to solve this problem?

**Comment by asgerf** [comment]
Hi @Ovi3 👋 

The example you provided works for me, so we'll need to find out why it's not working for you.

But first, please add the following at the top of the query:
```codeql
/** @kind path-problem */
import javascript
import DataFlow::PathGraph
```

Also, you should use `$@` in the alert message to indicate where the source link should appear, otherwise the message will just say `taint from`.
```codeql
select sink.getNode(), source, sink, "taint from $@", source.getNode(), "here"
```

Even without the above changes, the query _should_ work from vscode (except the results won't be presented in a nice way) but the query won't work at all in code scanning.

If you're using code scanning to run the query, please try again with the above changes. If you're using vscode, please make sure you're using the latest version of the vscode extension and the query libraries. If that didn't work, please double-check that you're running on the exact code you posted here.

**Comment by Ovi3** [comment]
I figured out why it't not working for me. It's because I have other test file containing a function that has the same name `foo`.
Code below doesn't work:
index.html: (I remove `<script src="./index.js"></script>` since codeql doesn't care)
```
<script>
 eval(foo());
</script>
```
index.js:
```
function foo(){
    return location.hash.substr(1);
}
```
index2.js:
```
function foo(){
    console.log("foo from index2.js")
    return location.hash.substr(1);
}
```
So, should be careful about the function name when there are lots of test files.

But this occasion happen easily when I download all the js and html file from a website to analyse:
1. different html files have same code that contains same global variable name (but include different extern js file, so I need to analyse all of them)
2. js file is minified and the same global variable name exists in different js file
3. different html files include different version of js files and these js files can easily has the same global variable name
And so on.

How can I deal with this, any suggestion?

**Comment by asgerf** [comment]
Yes, you've hit a limitation of the CodeQL JavaScript analysis, namely that we don't analyze flow to global functions whose name is not unique within the database.

As a workaround, you can include this in your query, although it may give some false flow paths:
```codeql
class ExtraCallEdge extends DataFlow::InvokeNode {
  string accessPath;

  ExtraCallEdge() {
    getCalleeNode() = AccessPath::getAReferenceTo(accessPath)
  }

  override Function getACallee(int imprecision) {
    result = super.getACallee(imprecision)
    or
    result.flow() = AccessPath::getAnAssignmentTo(accessPath).getALocalSource() and
    imprecision = 0
  }
}
```

Also, I'd suggest you update `isSource` like this to be forward compatible with some changes we're currently making to `location`-based taint sources. In particular, the step `location -> location.hash` will be removed, and instead `location.hash` will be a source of its own, but only if you include `RemoteFlowSource` as a source:
```codeql
  override predicate isSource(DataFlow::Node node) { 
    node = DataFlow::globalVarRef("location")
    or
    node instanceof RemoteFlowSource
  }
```

**Comment by Ovi3** [comment]
Got it. Thanks for your help.
