### ISSUE TITLE
Queries fail to compile due to recent change: use pragma[only_bind_into] to prevent bad join in Ssa::hasLocationInfo

### ISSUE THREAD

**Issue by andrew-barnett** [github/codeql#5365]
- Using [v2.4.4 of codeql-cli-binaries](https://github.com/github/codeql-cli-binaries/releases/tag/v2.4.4) for MacOSX
   - Same problem when using the Linux binaries
- Run `codeql query compile --threads=0 --ram=4096 --search-path=${PWD} ./javascript/ql/src/codeql-suites/*.qls` against a checkout of this repo.
   - Output:
      ```sh
      Compiling query plan for /Users/abarnett/src/codeql/javascript/ql/src/AngularJS/DisablingSce.ql.
      ERROR: Expected a term but found an expression instead (/Users/abarnett/src/codeql/javascript/ql/src/semmle/javascript/SSA.qll:524,7-13)
      ERROR: unexpected input '[' expecting one of: 'and', 'implies', 'in', 'instanceof', 'or', '<', '<=', '=', '>', '>=', '-', '!=', '/', '.', ')', '*', '%', '+', '|' (/Users/abarnett/src/codeql/javascript/ql/src/semmle/javascript/SSA.qll:524,13-14)
      ERROR: extraneous input '(' expecting one of: 'boolean', 'date', 'float', 'int', 'predicate', 'string', Lowerid, Upperid, Atlowerid (/Users/abarnett/src/codeql/javascript/ql/src/semmle/javascript/SSA.qll:524,59-60)
      . . .
      Failed [1/182 comp 4.1s] /Users/abarnett/src/codeql/javascript/ql/src/AngularJS/DisablingSce.ql.
      ```
      [Full output](https://github.com/github/codeql/files/6103690/error.txt)
   - Commit [be26a48a168187f65c048caa3d4f8a139d2b7c85](https://github.com/github/codeql/commit/be26a48a168187f65c048caa3d4f8a139d2b7c85) is the first instance where there is a problem
   - Prior to commit [ccd706ea10c98ad18e17919ad321524d11cbcd55](https://github.com/github/codeql/commit/ccd706ea10c98ad18e17919ad321524d11cbcd55) (inclusive) does not exhibit the problem

**Comment by intrigus-lgtm** [comment]
I guess you have to update to [version 2.4.5](https://github.com/github/codeql-cli-binaries/releases/tag/v2.4.5) of the codeql cli.

**Comment by andrew-barnett** [comment]
> I guess you have to update to [version 2.4.5](https://github.com/github/codeql-cli-binaries/releases/tag/v2.4.5) of the codeql cli.

lol... should have waited a couple minutes, I guess.

**Comment by hmakholm** [comment]
Well, the PR that inserted `pragma[only_bind_into]` really shouldn't have been merged until the public release of a QL compiler that understands it, but I think it's as close to fixed as it'll ever be now.

**Comment by andrew-barnett** [comment]
Confirm that 2.4.5 fixes things... thanks!
