### ISSUE TITLE
Unable to scan C++ built with setup.py [Error: No code found during the build]

### ISSUE THREAD

**Issue by colindembovsky** [github/codeql#5370]
Hi team

We are trying to build a Python module which wraps C++ code. The build process involves calling `setup.py` to build the code. When we configure CodeQL scanning, autobuild does not work, so we inject our own build steps. The build completes successfully on a hosted runner so there is no caching from previous builds. However, CodeQL scanning does not execute and the logs show this error: `Error: No code found during the build`.

The run can be found [here](https://github.com/colindembovsky/python_cpp_example/actions/runs/636662336).

Is there a way to help CodeQL intercept compilation using `setup.py` or similar?

**Comment by cmboling** [comment]
Here's an OSS example of where the build is successful: https://github.com/cmboling/python-c-extension/actions

**Comment by aibaars** [comment]
It looks like your build command is `sudo python3 ./setup.py install` . I suspect CodeQL can't trace the build through `sudo` .

**Comment by aibaars** [comment]
@cmboling You could try putting the following lines in a file named `script.sh`
```
source /home/runner/work/python_cpp_example/python_cpp_example/codeql-runner/codeql-env.sh           
python3 ./setup.py install
```
and run `sudo bash script.sh` as build command. That way the `sudo` does not interfere with the environment variable settings from `codeql-env.sh`.

**Comment by aibaars** [comment]
Alternatively you could drop all the `sudo`s and run `python3 ./setup.py build` or specify the `--prefix` flag , for example `python3 ./setup.py install --prefix /tmp/out`

**Comment by colindembovsky** [comment]
Thanks @aibaars - looks like the `--prefix` flag and dropping `sudo` worked!
