### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by HansEJC** [github/codeql#5387]
I believe it thinks that the return is an object literal, but it's a Boolean.

**https://lgtm.com/projects/g/HansEJC/hansejc.github.io/snapshot/3886325e6f5a37f719ec3736149777d8cb8fc4c5/files/js/index.js?sort=name&dir=ASC&mode=heatmap#x339586aeab1ad253:1**

**Comment by hvitved** [comment]
Hi

Could you elaborate on why you think this is a false positive? As far as I can see it simply suggests that you put a `;` after the `}` on line 31, because almost all other statements inside `initiate` have a semi colon, which seems sensible?

**Comment by HansEJC** [comment]
Hi

Thank you for the quick reply. I think realised why it was suggesting I put the `;`. It was probably because I was assigning the function to `document.onkeydown`. I'm not used to putting a `;` at the end of a function, so I declared the function separately instead. That should make the warning go away.
