### ISSUE TITLE
javascript: How to add flow label in the middle of taint tracking

### ISSUE THREAD

**Issue by Ovi3** [github/codeql#5402]
I'm taint-traking `location.hash` , and wanna know if it would be URL decoded.
In my though, I wanna add a flow label when the flow hit `unescape` function (or other similar functions). But I couldn't find a way to do this.

In this doc [Using flow labels for precise data flow analysis](https://codeql.github.com/docs/codeql-language-guides/using-flow-labels-for-precise-data-flow-analysis/#api) say:
> Each of the three member predicates isSource, isSink and isAdditionalFlowStep/isAdditionalTaintStep has one version that uses the default flow labels, and one version that allows specifying custom flow labels through additional arguments.

But the `isAdditionalTaintStep` predicate that allows specifying custom flow labels doesn't exists.

**Comment by intrigus-lgtm** [comment]
The `isAdditionalTaintStep` predicate is defined here:
https://github.com/github/codeql/blob/ad665b765faa93108d2cd820a59ad937f4e4a278/javascript/ql/src/semmle/javascript/dataflow/Configuration.qll#L152-L156
And here is an example use:
https://github.com/github/codeql/blob/5ead4244fe9a32e59b250a89b3aaab723ec3627f/javascript/ql/src/semmle/javascript/security/dataflow/TaintedPath.qll#L47-L52

Did you maybe miss a required parameter when overriding your `TaintTracking::Configuration`'s `isAdditionalTaintStep` predicate?

**Comment by Ovi3** [comment]
Oh yeah. My mistake, Thanks for the help.

**Comment by Ovi3** [comment]
BTW, In this page https://codeql.github.com/codeql-standard-libraries/javascript/semmle/javascript/dataflow/TaintTracking.qll/type.TaintTracking$TaintTracking$Configuration.html , there's only one `isAdditionalTaintStep` predicate.

**Comment by asgerf** [comment]
Sorry, that's a bug in the tutorial, thanks for pointing that out. You have to override the 4-argument version of `isAdditionalFlowStep`, even if you're using a taint-tracking configuration.

**Comment by Ovi3** [comment]
Got it
