### ISSUE TITLE
Java: CodeQL database issue: extract Ant build.xml files

### ISSUE THREAD

**Issue by haby0** [github/codeql#5409]
Use `Ant` to generate database, no `build.xml` file is found in `src.zip`

**Comment by aibaars** [comment]
@haby0 You're right that `build.xml` files are not included in the database by default. Only a handful of XML files are included by default (currently `AndroidManifest.xml`, `pom.xml`, `struts.xml` and `web.xml` ). There are no queries that rely on `build.xml` files, although it looks like you are working on one that would https://github.com/github/codeql/pull/5359 .

You can configure the XML extraction for Java with the `LGTM_INDEX_XML_MODE` environment variables (values `smart, all, no, default`). The `smart` and `all` modes would include ant build files.

Perhaps CodeQL should just include `build.xml` by default. 
@yo-h ^

**Comment by haby0** [comment]
@aibaars @yo-h 

Yes, the name of the `Ant` build file is not necessarily `build.xml`

In addition, I think `yml` and `properties` related files should also be considered to be included.Hope to think about it.

**Comment by aibaars** [comment]
> In addition, I think `yml` and `properties` related files should also be considered to be included.Hope to think about it.

`properties` can be included by setting `LGTM_INDEX_PROPERTIES_FILES=true`, unfortunately the default value is `false`. I don't think Java databases currently support yaml content.

**Comment by haby0** [comment]
> > In addition, I think `yml` and `properties` related files should also be considered to be included.Hope to think about it.
> 
> `properties` can be included by setting `LGTM_INDEX_PROPERTIES_FILES=true`, unfortunately the default value is `false`. I don't think Java databases currently support yaml content.

Thanks for the answer, I hope I can participate in more CodeQL construction.

**Comment by haby0** [comment]
@aibaars @yo-h I will close this question and hope that the `build.xml` file will be added to the `CodeQL` database build by default.
