### ISSUE TITLE
LGTM.com - false positive Resource not released in destructor

### ISSUE THREAD

**Issue by VolkerEnderlein** [github/codeql#5412]
**Description of the false positive**

The objects in question are reference counted. After allocating the component with

     thisp->pvcache = new SoPrimitiveVertexCache(action->getState());

its refcount is increased by a call to `thisp->pvcache->ref();`

When decreasing the refcount by calling `thisp->pvcache->unref();` and the refcount goes to zero the object is deleted.

Interestingly lots of other allocations following the same pattern are not reported.

Thanks for this wonderful tool! Keep up the good work.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/coin3d/coin/snapshot/7b2bacce908ee22d80d641938ec9b9ff3c77616c/files/src/actions/SoReorganizeAction.cpp?sort=name&dir=ASC&mode=heatmap#x14018e37bb35dc4:1

**Comment by MathiasVP** [comment]
Hi @VolkerEnderlein,

Thanks for reporting this.

It looks like the reference count on `thisp->pvcache` is incremented whenever a new `SoPrimitiveVertexCache` is allocated, and decremented when `replaceNode` is called. Is that right?

Shouldn't the reference count also be decremented in the destructor somewhere?

> Thanks for this wonderful tool! Keep up the good work.

Thanks for the support. It is very appreciated! :)

**Comment by VolkerEnderlein** [comment]
Thanks for looking into the issue. I agree with you that a non paired call of the functions creating and releasing the memory may leak the memory. I will examine more deeply and apply your suggestion to dereference the nodes in the destructor. So it seems I have picked the wrong alert and the issue is valid.

More alerts are in  the [SoShadowLightCache class](https://lgtm.com/projects/g/coin3d/coin/snapshot/f91ad7f35d0a659a39e5a1d30309b2db7ac0517a/files/src/shadows/SoShadowGroup.cpp?sort=name&dir=ASC&mode=heatmap#x58843c314e4ef140:1) where nodes are properly dereferenced in the destructor, but were also marked as "Resource not released in destructor". Can you please have a look into this cases? It is highly appreciated.

**Comment by MathiasVP** [comment]
> More alerts are in the [SoShadowLightCache class](https://lgtm.com/projects/g/coin3d/coin/snapshot/f91ad7f35d0a659a39e5a1d30309b2db7ac0517a/files/src/shadows/SoShadowGroup.cpp?sort=name&dir=ASC&mode=heatmap#x58843c314e4ef140:1) where nodes are properly dereferenced in the destructor, but were also marked as "Resource not released in destructor". Can you please have a look into this cases? It is highly appreciated.

Indeed, they look like false positives. The analysis was not spotting that `this` was being released in this piece of code in `SoBase::unref(void)`:
```cpp
if (refcount == 0) {
  SoBase * base = const_cast<SoBase *>(this);
  base->destroy();
}
```

I've opened up a PR with a fix: https://github.com/github/codeql/pull/5431. With the changes in that PR I see four alerts on your project:

![Screenshot 2021-03-17 at 16 21 13](https://user-images.githubusercontent.com/4527323/111492267-d23e0700-873c-11eb-84be-5d4f239ce5ac.png)

**Comment by VolkerEnderlein** [comment]
Cool. Thanks so much for your support. I really appreciate it.
