### ISSUE TITLE
Java: Query Console omits some Exception elements

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#5465]
It appears the LGTM Query Console omits some `Exception` elements from the results. However, the affected elements have a `toString()` result, so this is not the cause (see also #5290).
These `Exception` elements are probably also bogus, see #5464.

To reproduce, compare:
```ql
import java

from Exception e
where not e.fromSource()
select e
```
[Query Console link](https://lgtm.com/query/7336685919389070531/)

With the following:
```ql
import java

from Exception e
where not e.fromSource()
select e.toString()
```
[Query Console link](https://lgtm.com/query/4208038394044451036/)

The first one has no results at all, not even 'non-source' results.
The second one has results even though the only difference is that its `select` clause uses `e.toString()` instead of `e`.

Note that the VSCode extension is not affected, it has results for both queries.

**Comment by dbartol** [comment]
Thanks for the report. The reason that the query console is omitting those results is that the objects being selected have no `getLocation()` result. For non-primitive types, the query console requires both `toString()` and `getLocation()` to have a result. When we created the VS Code extension, we decided it was more useful to include results that lack a location, but it's unlikely that we'll go back and change the query console to match that behavior.

**Comment by Marcono1234** [comment]
Thanks for the explanation!

> but it's unlikely that we'll go back and change the query console to match that behavior

I guess you have your reasons, though similar to #5290 this can make 'debugging' unexpected or missing query results pretty confusing. E.g. in this case you trace it down to bogus `Exception` elements being reported and then try to emit these elements with the `select` clause and suddenly have no results at all.

**Comment by aibaars** [comment]
The LGTM query console used the wrong CodeQL compilation setting so results without a location URL were omitted. Thanks for reporting the issue.

**Comment by aibaars** [comment]
@Marcono1234 This should be resolved now, please re-open this issue if things still don't work for you. Note that you need to "re-run" existing queries to get the missing data. LGTM caches the results for a query. You can force a "re-run" by modifying a query a little (adding a space or a comment is enough).

**Comment by Marcono1234** [comment]
Thanks a lot! Yes it looks like this is resolved now.
