### ISSUE TITLE
Java: `Modifiable.hasModifier(string)` reports implicit modifiers

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#5472]
### Description
The [documentation for `Modifiable.hasModifier(string)`](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/java/Modifier.qll/predicate.Modifier$Modifiable$hasModifier.1.html) says:
> For most purposes, the more specialized predicates `isAbstract`, `isPublic`, etc. should be used, which also take implicit modifiers into account.

This suggests that it should only hold if an explicit modifier is used. However, this does not seem to be the case.
This makes it difficult to write any queries taking explicit modifier usage into account (e.g. checking for redundant modifiers), and also renders some special casing code in the CodeQL classes pointless.

The current behavior is therefore probably incorrect, only the respective predicates, such as `isFinal()` or `isStatic()`, which explicitly mention that they also hold for implicit modifiers should hold. Predicates reporting explicit modifiers such as `hasModifier`, and probably also `getAModifier` and `hasNoModifier`, should not hold. Their documentation should also more clearly mention that they only are supposed to only match explicit modifiers.

### Affected cases
(List is likely incomplete)

- Records: Are always reported as `final` and, for nested records, `static`
[Query Console link](https://lgtm.com/query/6284304620801545884/)
- Enums are always reported as `final` and, for nested enums, `static`
- Nested interfaces are always reported as `static`
- Interface methods are always reported as `public` (unless explicitly `private`) and `abstract` (unless `default` or `static`)
- Interface fields are always reported as `static`

**Comment by dbartol** [comment]
Thanks for the report. At the very least, the documentation is incorrect, but I've forwarded the issue to our Java team to determine if the implementation should be changed instead.

**Comment by smowton** [comment]
https://github.com/github/codeql/pull/5682

**Comment by smowton** [comment]
Documented current behaviour in #5682. Could consider exposing only explicit modifiers if there's a pressing need, though this would be low priority.
