### ISSUE TITLE
Add Tomcat's server.xml to the list of indexed files

### ISSUE THREAD

**Issue by agustingianni** [github/codeql#5497]
One of our bug bounty submissions deals with misconfiguration of server.xml. Unfortunately LGTM does not index it by default therefore I cannot rate the submission properly.

The file is popular enough and has impact in the security of projects so I think adding it to the index would be a good idea.

CC: @yo-h

**Comment by haby0** [comment]
I submitted an issue:#5482. I think that only `server.xml` is not enough, and configuration files such as `application.properties`/`config.ini` should also be included in the build database by default.

**Comment by agustingianni** [comment]
I'm closing this issue because server.xml is a file that belongs to the configuration of the tomcat server itself and has no relationship with a particular codebase.
