### ISSUE TITLE
LGTM doesn't remove alerts for a language when all items have been removed 

### ISSUE THREAD

**Issue by leonard84** [github/codeql#5501]
**Description of the issue**
This is related to #4284 and #3175.

In an older version we had some javascript code for a now removed reporting module.
The alerts for those since removed libraries still show up in the report.

https://lgtm.com/projects/g/spockframework/spock/?mode=list

It even shows a warning, that the javascript error message are based on a different commit.
![grafik](https://user-images.githubusercontent.com/1151511/112159516-8af6c100-8be9-11eb-91cd-431cf481e84f.png)

It also lists a low code quality for the hence removed javascript.
![grafik](https://user-images.githubusercontent.com/1151511/112158839-d9579000-8be8-11eb-9473-611e935480e7.png)

A possible workaround could be to include a dummy javascript file, just so that the javascript check doesn't fail and recognizes that there are no issues left. However, that should not be necessary IMO.

**Comment by leonard84** [comment]
@aeisenberg please remove the `stale` and `question` label, as this is a bug report.

**Comment by jketema** [comment]
Hi @leonard84. Apologies for not getting back to you and thanks for your interest in LGTM.  I'm closing this issue, as LGTM has been shutdown. Please see the [blog post on LGTM's deprecation](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) for further details. More details on LGTM's replacement - Code Scanning - can be found in the [GitHub Docs for this feature](https://docs.github.com/en/code-security/code-scanning).
