### ISSUE TITLE
Java: JUnit annotations affect Dataflow analysis results

### ISSUE THREAD

**Issue by uxhg** [github/codeql#5511]
## Description
JUnit annotations such as `@Test` prevent some Java dataflow anlaysis results from appearing in the query results. 

## MWE
The MWE can be seen at https://github.com/uxhg/mwe-codeql-2021-03-24
Basically it contains the following testcase.
```java
import org.junit.Test;
import ch.qos.logback.classic.Logger;
import org.slf4j.LoggerFactory;

public class AppTest
{
    protected static Logger logger;
    @Test
    public void testLogging() {
        logger = (Logger) LoggerFactory.getLogger(App.class);
        logger.info("test");
    }
}         
```

The query used is pasted here. I left out the metadata part.
```codeql
import java
import semmle.code.java.dataflow.TaintTracking

class DataDepLibCalls extends TaintTracking::Configuration {
  DataDepLibCalls() {
    this = "DataDepLibCalls"
  }

  override predicate isSource(DataFlow::Node nd) {
    exists(Call libCall | nd.asExpr() = libCall)
  }

  override predicate isSink(DataFlow::Node nd) {
      exists(Call libCall | nd.asExpr() = libCall.getAnArgument() or nd.asExpr() = libCall.getQualifier())
     }
}

from DataDepLibCalls pt, Call source, Call sink, string lib1, string lib2, Expr e
where
  lib1 = source.getCallee().getDeclaringType().getQualifiedName() and
  lib2 = sink.getCallee().getDeclaringType().getQualifiedName() and
   (e = sink.getAnArgument() or e = sink.getQualifier()) and
  pt.hasFlow(DataFlow::exprNode(source), DataFlow::exprNode(e))
select source, lib1, sink, lib2, source.getLocation(), e.getLocation()
```

I run the following codeql-cli commands to generate db and run the query.
```sh
codeql database create project.db --language=java --command "mvn clean package"
codeql query run --database=project.db --output=mwe.bqrs /path/to/codeql-repo/java/ql/src/mwe.ql
codeql bqrs decode --format=csv -o mwe.csv mwe.bqrs 
```

### What is the expected output?
If `@Test` is commented out, there would be one row of result in `mwe.csv` as below.
```
"source","lib1","sink","lib2","col4","col5"
"getLogger(...)","org.slf4j.LoggerFactory","info(...)","ch.qos.logback.classic.Logger","AppTest:16[21-54]","AppTest:17[3-8]"
```
 ### What is the output?
When `@Test` is used, `mwe.csv` contains no result (just one line of header).
This also happens in real projects using other JUnit annotations such as `@Before`.

### What others have I tried?
To verify test cases code are processed and anlyzed by codeql, I also run the following query using the same cli commands above.
```codeql
import java
from Call a, Expr s, Location sl
where s = a.getQualifier() and sl = s.getLocation()
select a.getCallee().getDeclaringType().getQualifiedName(), s, sl
```
No matter whether `@Test` is commented or not, the output stays the same and obviously related code entities are included.
```
"col0","s","sl"
"ch.qos.logback.classic.Logger","logger","AppTest:13[3-8]"
"java.io.PrintStream","System.out","App:11[9-18]"
"org.slf4j.LoggerFactory","LoggerFactory","AppTest:12[21-33]"
```

**My Question**: Why JUnit annotations affect the dataflow analysis results?

**Comment by aschackmull** [comment]
This is intentional. A `TaintTracking::Configuration` is a specific kind of `DataFlow::Configuration`, which comes with a bunch of default settings. Removing flow through unit test code makes sense as taint-tracking is mostly used to find security problems and for that unit tests are typically irrelevant. If you don't want this behaviour, you can simply use a `DataFlow::Configuration` instead and add the additional steps and other configuration you want.

**Comment by uxhg** [comment]
Thanks for your information. I can confirm `DataFlow::Configuration` will reveal the dataflow in test cases.
And for others who may need it,  following predicates seem to be reponsible for filtering out `NonSecurityTestClass`.
```java
// ql/src/semmle/code/java/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
final override predicate isBarrier(DataFlow::Node node) {
  isSanitizer(node) or 
  defaultTaintSanitizer(node)
}
```

```java
// ql/src/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll
predicate defaultTaintSanitizer(DataFlow::Node node) {
  // Ignore paths through test code.
  node.getEnclosingCallable().getDeclaringType() instanceof NonSecurityTestClass or
  node.asExpr() instanceof ValidatedVariableAccess
}
```
