### ISSUE TITLE
codeQL missed files

### ISSUE THREAD

**Issue by NitroCao** [github/codeql#5523]
Our company has a Java project that used the Spring framework. I created a database by using the command:
```
codeql database create ~/codeql-home/samples/codeql-rma --language=java --threads 4 --source-root ~/rma --search-path ~/codeql-home/codeql-repo
```
Then I wrote a QL file to get all package names:
```
import java

from Package p
where
    p.toString().regexpMatch("^com.example.rma.web.*")
select p
```
Here is the result:
```
Evaluation completed (280ms).
|                          p                          |
+-----------------------------------------------------+
| com.example.rma.web                                  |
| com.example.rma.web.api.factory                      |
| com.example.rma.web.api.vo                           |
| com.example.rma.web.controller.common.publicapi      |
| com.example.rma.web.controller.incident.publicapi.vm |
| com.example.rma.web.controller.request.publicapi.vm  |
| com.example.rma.web.controller.rma.publicapi.vm      |
| com.example.rma.web.interceptor                      |
```
But actually there is another package called `com.example.rma.web.api`:
```
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /home/example/rma/web/src/main/java/com/example/rma/web/api/RmaServiceRest.java
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ package com.synnex.rma.web.api;

......
```
I then use the following code to query this class and it also has no output.
```
import java

from Package p, Class c
where
        c.getName().regexpMatch("^RmaServiceRest$")
select c
```

This project doesn't use Lombok.
This project belongs to our company, so I cannot provide the source code.
Is there any suggestion on how to solve this kind of problem? Thanks

**Comment by rdmarsh2** [comment]
>  This project belongs to our company, so I cannot provide the source code.

Can you reproduce this with an open-source project? If not, please go through your enterprise support channel rather than filing a public issue.

**Comment by aeisenberg** [comment]
Enterprise support will be happy to help you. Please file an [issue on zendesk](https://enterprise.githubsupport.com/hc/en-us). Closing this issue, and feel free to re-open if you are able to provide the source code.
