### ISSUE TITLE
Question about the conflict of predicate declarations

### ISSUE THREAD

**Issue by f52985** [github/codeql#5539]
Consider this QL code snippet

```
predicate p(int i) { i = 1 }

module M {
  predicate p(int i) { i = 2 }
}

from int i
where p(i) or M::p(i)
select i
```

My expectation is that, there should be no conflict between those two predicate declarations, since the first one is accessible by <code>p</code> and the second one accessible by <code>M::p</code>. (And I did not import the module)
Yet, the CodeQL compiler told me that those two declarations conflict.

The questions are,
1) Is this an intended behavior?
2) If this is an intended behavior, why is it prohibited to declare predicates in such a way?

**Comment by aschackmull** [comment]
Yes, this is intended.

The conflict does not exist outside `M` - indeed it is perfectly possible to have both a `p` and an `M::p` in scope at the same time. The conflict is within `M` where `p` refers to two different predicates.  If `M` was defined in a separate file so it didn't have the top-level `p` in scope then the conflict goes away.
