### ISSUE TITLE
JaxRsResponseBuilder definition error

### ISSUE THREAD

**Issue by zzzzfeng** [github/codeql#5576]
in file semmle/code/java/frameworks/JaxWS.qll
instead of
`class JaxRsResponseBuilder extends Class {
  JaxRsResponseBuilder() { this.hasQualifiedName("javax.ws.rs.core", "ResponseBuilder") }
}`
it should be
`class JaxRsResponseBuilder extends Class {
  JaxRsResponseBuilder() { this.hasQualifiedName("javax.ws.rs.core", "Response$ResponseBuilder") }
}`

**Comment by smowton** [comment]
Agreed. https://github.com/github/codeql/pull/5491 will fix this.
