### ISSUE TITLE
LGTM.com - false positive - Uncontrolled data used in path expression

### ISSUE THREAD

**Issue by alanmehio** [github/codeql#5598]
**Description of the false positive**

Please take a look at [this ](https://github.com/apache/cxf/pull/768/files#annotation_1255142036)
as in line 187 it gets the directory as a String from a  message contextual property 

```java
Object directory = message.getContextualProperty(AttachmentDeserializer.ATTACHMENT_DIRECTORY);
```

the Directory can be any path . If we can say it is a tmp directory on the linux which will end up like "/tmp"
If we follow the [recommendation ](https://codeql.github.com/codeql-query-help/java/java-path-injection/) it is not applicable since the class [AttachmentUtil](https://github.com/apache/cxf/tree/master/core/src/main/java/org/apache/cxf/attachment/AttachmentUtil.java) has no idea what is being stored in the message contextual property ATTACHMENT_DIRECTORY)

**URL to the alert on the project page on LGTM.com**
https://github.com/apache/cxf/pull/768/files#annotation_1255142036

https://lgtm.com/projects/g/apache/cxf/snapshot/018c47bd2be8213910b34d1cfb2aabf796c40b7e/files/core/src/main/java/org/apache/cxf/attachment/AttachmentUtil.java?sort=name&dir=ASC&mode=heatmap#x5d0eff0d14e724ce:1

**Comment by aeisenberg** [comment]
This doesn't seem like a false positive to me. Because any value can be stored in the message contextual property `ATTACHMENT_DIRECTORY`, this data is potentially tainted and should not be used without sanitizing. Before using the directory string, you will need to sanitize and remove any potentially dangerous components (eg- `..`).

Or, are you saying that the output directory can be _any_ location on the file system and so there is no security issue here? I am not familiar with this code. In general, this is bad practice, though in this specific case, it might be warranted.

**Comment by alanmehio** [comment]
@aeisenberg  thanks for commenting on the issue.   Please look at the report bug also at [CXF project](https://issues.apache.org/jira/browse/CXF-8448)
Actually  from the test cases the directory is a full path directory on the file system such as /tmp or  /dev/null  
I will discuss the issue with the  other contributors of the CXF and see what we can do for sanitization action to be done on this directory name which is converted to a java.io.File object .  
I will try to different naming implementations for this directory names in relation to the security check rules from codeQL.

**Comment by alanmehio** [comment]
The issue is sorted now by following the recommendation from @aeisenberg  to remove dangerous component such as ".." from the directory name. There are still a list of 38 errors for the[ CXF project](https://lgtm.com/projects/g/apache/cxf/alerts/?mode=list&result_filter=0e00f5fa7b93849767c1677dc71d9400f85c6a54) . I am going to create a separate issue for  addressing this list on CXF Jira system . Many thanks for Andrew Eisenberg  for his valuable feedback

**Comment by aeisenberg** [comment]
Happy to help. 🎉
