### ISSUE TITLE
Scanning randomly fails with exit code 2

### ISSUE THREAD

**Issue by soumyamahunt** [github/codeql#5599]
**Description of the issue**

I have implemented CodeQL scanning in [this](https://github.com/soumyamahunt/Notepads) project and it [works](https://github.com/soumyamahunt/Notepads/runs/2268330838?check_suite_focus=true) most of the time but some times it randomly fails like for [this](https://github.com/soumyamahunt/Notepads/pull/18/checks?check_run_id=2268746178) instance. Log:
```
Finalizing database creation
Finalizing csharp
  C:\hostedtoolcache\windows\CodeQL\0.0.0-20210326\x64\codeql\codeql.exe database finalize --threads=2 D:\a\_temp\codeql_databases\csharp
  Running pre-finalize script C:\hostedtoolcache\windows\CodeQL\0.0.0-20210326\x64\codeql\csharp\tools\pre-finalize.cmd in D:\a\Notepads\Notepads.
  Running pre-finalize script C:\hostedtoolcache\windows\CodeQL\0.0.0-20210326\x64\codeql\csharp\tools\pre-finalize.cmd in D:\a\Notepads\Notepads.
  [2021-04-05 09:43:17] [build-stderr] Scanning for files in D:\a\Notepads\Notepads...
  [2021-04-05 09:43:17] [build-stderr] Scanning for files in D:\a\Notepads\Notepads...
  [2021-04-05 09:43:18] [build-stderr] D:\a\_temp\codeql_databases\csharp: Indexing files in in D:\a\Notepads\Notepads...
  [2021-04-05 09:43:18] [build-stderr] D:\a\_temp\codeql_databases\csharp: Indexing files in in D:\a\Notepads\Notepads...
  [2021-04-05 09:43:18] [build-stderr] D:\a\_temp\codeql_databases\csharp: Running in D:\a\Notepads\Notepads: [C:\hostedtoolcache\windows\CodeQL\0.0.0-20210326\x64\codeql\xml\tools\index-files.cmd, D:\a\_temp\codeql_databases\csharp\working\files-to-index6385052761477996838.list]
  [2021-04-05 09:43:18] [build-stderr] D:\a\_temp\codeql_databases\csharp: Running in D:\a\Notepads\Notepads: [C:\hostedtoolcache\windows\CodeQL\0.0.0-20210326\x64\codeql\xml\tools\index-files.cmd, D:\a\_temp\codeql_databases\csharp\working\files-to-index6385052761477996838.list]
  Running TRAP import for CodeQL database at D:\a\_temp\codeql_databases\csharp...
  Running TRAP import for CodeQL database at D:\a\_temp\codeql_databases\csharp...
  A fatal error occurred: Error saving relations while importing TRAP files for locations_default
  A fatal error occurred: Error saving relations while importing TRAP files for locations_default
  (eventual cause: IOException "There is not enough space on the disk")
  (eventual cause: IOException "There is not enough space on the disk")
  Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20210326\x64\codeql\codeql.exe' failed with exit code 2
  Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20210326\x64\codeql\codeql.exe' failed with exit code 2
      at Object.toolrunnerErrorCatcher (D:\a\_actions\github\codeql-action\v1\lib\toolrunner-error-catcher.js:79:19)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Object.finalizeDatabase (D:\a\_actions\github\codeql-action\v1\lib\codeql.js:401:13)
      at async finalizeDatabaseCreation (D:\a\_actions\github\codeql-action\v1\lib\analyze.js:72:9)
      at async Object.runAnalyze (D:\a\_actions\github\codeql-action\v1\lib\analyze.js:124:5)
      at async run (D:\a\_actions\github\codeql-action\v1\lib\analyze-action.js:50:30)
      at async runWrapper (D:\a\_actions\github\codeql-action\v1\lib\analyze-action.js:96:9)
```

**Comment by aeisenberg** [comment]
The error that you are getting is that there is not enough disk space available to create the database (TRAP) files. The standard windows actions runners have [14GB of SSD space available](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) and somehow all of this space is being used. 

I am not able to tell exactly what is going on, but I wonder if it has something to do with [al-cheb/configure-pagefile-action](https://github.com/al-cheb/configure-pagefile-action). Take a look at what you can do to reliably reduce the amount of disk usage for these builds.

In theory, you could also use [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) that have a larger disk size, but we only recommend these for private repos in order to avoid security concerns.

**Comment by soumyamahunt** [comment]
> The error that you are getting is that there is not enough disk space available to create the database (TRAP) files. The standard windows actions runners have [14GB of SSD space available](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) and somehow all of this space is being used.
> 
> I am not able to tell exactly what is going on, but I wonder if it has something to do with [al-cheb/configure-pagefile-action](https://github.com/al-cheb/configure-pagefile-action). Take a look at what you can do to reliably reduce the amount of disk usage for these builds.
> 
> In theory, you could also use [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) that have a larger disk size, but we only recommend these for private repos in order to avoid security concerns.

The `configure-pagefile-action` was suggested to avoid [out of memory error](https://github.com/github/codeql-action/issues/245). I think this issue is better suited for the [action](https://github.com/github/codeql-action) repo.

**Comment by aeisenberg** [comment]
Ah...that makes sense. Because you are paging out memory to disk, the disk is running out of space.

I see that you set the max size of the page file to 32GB, but there is only 14GB of hard disk available. That in itself is a problem. You also need to ensure there is enough disk space for all the other parts of the OS, applications, database, etc. So, try setting the max page file size to something smaller, like 8GB and the min size to 4GB. If that still doesn't work, you'll need to go smaller.

**Comment by soumyamahunt** [comment]
> Ah...that makes sense. Because you are paging out memory to disk, the disk is running out of space.
> 
> I see that you set the max size of the page file to 32GB, but there is only 14GB of hard disk available. That in itself is a problem. You also need to ensure there is enough disk space for all the other parts of the OS, applications, database, etc. So, try setting the max page file size to something smaller, like 8GB and the min size to 4GB. If that still doesn't work, you'll need to go smaller.

Even if I reduce the maximum size of the page file doesn't that mean I will just get `Out of memory error` instead of this error??

**Comment by aeisenberg** [comment]
At this point, this is your best option. Try reducing the max page file size and see if you can avoid OOMEs. There might be a sweet spot in there where you have enough RAM and enough hard disk. You may need tweak the settings a bit until you find the right value.

Also, you could try cleaning up build artifacts before building the database. Delete anything that isn't required for building and analyzing the database, including the pieces generated during the msbuild step.

**Comment by aeisenberg** [comment]
Another suggestion is to move codeql analysis to a separate workflow and _only_ do codeql analysis in that workflow. Because you are both building and analyzing the project in the same workflow, there will be extra build artifacts created that are not necessary for the entire process.

**Comment by aeisenberg** [comment]
@VoVanHaiQS, can you please create a new issue for this? You need to run `codeql-action/init` in the same job as you are running the build and `codeql-action/analyze`.

**Comment by VoVanHaiQS** [comment]
@aeisenberg , I have opened new issue for this https://github.com/github/codeql/issues/13571, thank you
