### ISSUE TITLE
Retrieving MemberDeclaration for Function in JavaScript

### ISSUE THREAD

**Issue by lcwj3** [github/codeql#5602]
**Description of the issue**

To retrieve the members of a class or interface, I found there is a `ClassOrInterface`, and I can retrieve the members by `getAMember()`, but it doesn't work for Function object. For example the [Yallist](https://github.com/isaacs/yallist/blob/master/yallist.js#L7), here is my code:
```
from ClassOrInterface c, MemberDeclaration f
where f = c.getAMember()
select 
c, c.getName(), c.getFile().getRelativePath(), f, f.getName()
```

Another solution I found is the `getAnInstanceMember()` of  `DataFlow::ClassNode`, but it seems it will retrieve all functions from the file instead of the single Class object, for example the `naiveLength` in [lru-cache](https://github.com/isaacs/node-lru-cache/blob/master/index.js#L17) will be given. Besides, this method can not retrieve constructors.
```
import javascript
import DataFlow
from ClassNode f
select f, f.getName(), f.getFile().getRelativePath(), f.getAnInstanceMember()
```

I am not sure whether this could be false positives or true negatives, but is there any solution to handle both of these cases?

My env is codeql cli v2.4.4, ubuntu 18.04

Thanks!

**Comment by aeisenberg** [comment]
The issue you are seeing is that constructs like `function foo() { ... }` are not `MemberDeclaration`s. There is no `ClassOrInterface` that they are a part of. I know it's confusing since the function you are pointing to defines a traditional javascript object constructor using prototypal inheritance. `MemberDeclaration` is only for property members of actual `class`es.

My first suggestion is that you try using the AST Viewer in vscode. It will show you exactly the AST type at any given location in the code.

In this case, you will see that the AST type is `FunctionDeclStmt`. There is also `FunctionExpr` that covers constructs like `let x = function () { ... }`. Both of which are subtypes of `Function`.

**Comment by lcwj3** [comment]
> The issue you are seeing is that constructs like `function foo() { ... }` are not `MemberDeclaration`s. There is no `ClassOrInterface` that they are a part of. I know it's confusing since the function you are pointing to defines a traditional javascript object constructor using prototypal inheritance. `MemberDeclaration` is only for property members of actual `class`es.
> 
> My first suggestion is that you try using the AST Viewer in vscode. It will show you exactly the AST type at any given location in the code.
> 
> In this case, you will see that the AST type is `FunctionDeclStmt`. There is also `FunctionExpr` that covers constructs like `let x = function () { ... }`. Both of which are subtypes of `Function`.

Thanks for your kind explanation, what about the result of `ClassNode`? The `getAnInstanceMember()` returns a function that is not a member of that class, and it ignores the constructor.

**Comment by aeisenberg** [comment]
`ClassNode` and `getAnInstanceMember()` are not JavaScript types. Which language are you using here? I'd thought it was JavaScript because the two files you linked to are js. Are you also looking at a different language?

**Comment by lcwj3** [comment]
> ~`ClassNode` and `getAnInstanceMember()` are not JavaScript types. Which language are you using here? I'd thought it was JavaScript because the two files you linked to are js. Are you also looking at a different language?~
> 
> My mistake, you are talking about `DataFlow`.
> 
> [`getAnInstanceMethod()`](https://codeql.github.com/codeql-standard-libraries/javascript/semmle/javascript/dataflow/Nodes.qll/predicate.Nodes$ClassNode$getAnInstanceMethod.0.html) does not return constructors. You will need to call [`getConstructor()`](https://codeql.github.com/codeql-standard-libraries/javascript/semmle/javascript/dataflow/Nodes.qll/predicate.Nodes$ClassNode$getConstructor.0.html).
> 
> Can you give me an example of a function that gets returned by `getAnInstanceMember()` that is not a class member?

Sorry for the late reply. The `naiveLength` in [lru-cache](https://github.com/isaacs/node-lru-cache/blob/master/index.js#L17) will be returned if you run the second part of code in my question. However, `nativeLength` is a function defined outside the class.

**Comment by aeisenberg** [comment]
In this case the function body of `naiveLength` is being assigned to a member in the constructor at line 40 https://github.com/isaacs/node-lru-cache/blob/master/index.js#L40. This means that this function eventually does become a member of this class according to some dataflows.

**Comment by lcwj3** [comment]
> In this case the function body of `naiveLength` is being assigned to a member in the constructor at line 40 https://github.com/isaacs/node-lru-cache/blob/master/index.js#L40. This means that this function eventually does become a member of this class according to some dataflows.

Okay I see, thanks for your explanation!
