### ISSUE TITLE
Dealing with inconsistent hashcode and equals alerts

### ISSUE THREAD

**Issue by eevanwong** [github/codeql#5615]
This alert appears multiple times in Apache Drill. 

https://lgtm.com/projects/g/apache/drill/snapshot/e2a0925dd18aacf3a5657acd738f89a63a3b8576/files/contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/json/JsonTableRangePartitionFunction.java?sort=name&dir=ASC&mode=heatmap 

For this issue (but not exclusively), there is an overridden method called equals, but it is supposedly used in tandem with another method called hashcode. 

For many of the instances this alert shows up, there is one method but not the other. I believe this is because only one of the methods are required for functionality, but LGTM still throws an alert. Furthermore, there are some cases where there is a hashcode method and an equals method, but the equals method is named something else. Regardless, it still makes an alert.

I would like some input in how to deal with these particular issues, is it required to have it? Or can I find some sort of workaround without suppressing it?

**Comment by aeisenberg** [comment]
Yes, this is a legitimate concern. The contract between `hashCode` and `equals` is that equal instances must have the same hashCode. The reverse is not necessary, but high quality hashCode algorithms should avoid this as much as possible.

According to javadoc for the equals method:

> Note that it is generally necessary to override the hashCode method whenever this method is overridden, so as to maintain the general contract for the hashCode method, which states that equal objects must have equal hash codes.

Full javadoc is here: [equals](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)) and [hashCode](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#hashCode()).
