### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by styfle** [github/codeql#5651]
**Description of the false positive**

The error message says "The initial value of sourceSegments is unused, since it is always overwritten", but that's not true.

Consider the case when `sourceToRegex()` throws an error and the Set will not be overwritten. So it is important to initialize it to the empty Set so we can later call `.has()`.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/vercel/vercel/snapshot/0b2704395dd99a3f439761ce08e4b4fd4513e3b0/files/packages/routing-utils/src/index.ts?sort=name&dir=ASC&mode=heatmap#x7a0121e9c632e29:1

**Comment by intrigus-lgtm** [comment]
If sourceToRegex fails it will return from the function, won't it?
So there are two cases, sourceToRegex fails or it doesn't.
If it doesn't fail you overwrite the initial set.
It it does fail you return.
So I'd say that the query is correct and this is a true-positive.

**Comment by styfle** [comment]
Yep, you're right there's an early return in the catch() 🤦‍♂️
