### ISSUE TITLE
Java: Control flow does not work well for `LValue`

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#5652]
Control flow does not work well for `LValue`, the main reason is that `LValue` matches the var access. This causes (at least) two issues:
1. For `LValue` as destination of an `AssignExpr` the control flow node has neither any predecessors nor successors. While this might be technically correct because the var access does not evaluate anything (only the qualifier, if any, does; for which control flow works), this makes usage of it error-prone.
2. For `LValue` representing a compound assignment the right-hand side is considered a successor, e.g. `i += i = 1`. This is incorrect, `i = 1` should be considered a predecessor.

Maybe the following control flow model for `LValue` would be correct (though it might not be possible to implement):
- `AssignExpr`: `qualifier` (if any) → `RHS` → [`AssignExpr`, `LValue`] → ...
- `AssignOp`: `qualifier` (if any) → _var-read_ → `RHS` → [`AssignOp`, `LValue`] → ...
- `UnaryAssignExpr`:  `qualifier` (if any) → _var-read_ → [`UnaryAssignExpr`, `LValue`] → ...

Overriding `getControlFlowNode()` for `LValue` might cause issues when it is used for a `VarAccess`  representing both an `LValue` and `RValue` (i.e. for compound assignment), then the RHS would be considered both a predecessor and a successor (though this might actually be correct?).

**Comment by aschackmull** [comment]
The `LValue` in the control-flow graph is the _var-read_, so it is placed correctly in the `AssignOp` and `UnaryAssignExpr` cases. And for the `AssignExpr` case, as you note yourself "this might be technically correct", indeed I believe that's what it is.
The "does not work well" complaint is quite vague compared to this. The placement/exclusion of `LValue` in the CFG has been carefully considered, and I don't currently see any reason to change this.

**Comment by Marcono1234** [comment]
> The `LValue` in the control-flow graph is the _var-read_

That is the main issue; when you are writing a query which explicitly uses the control flow node of `LValue`, then the query is very likely not interested in the _var-read_ (it would use `RValue` then).

> The "does not work well" complaint is quite vague compared to this.

I tried choosing a title which covers both issues outlined in the description. As you can see originally this GitHub issue had a different title when I did not notice that `LValue` as child of `AssignOp` was reporting the flow in the wrong order.

> I don't currently see any reason to change this.

The main issue is that trying to determine any control flow for an `LValue` is impossible / error-prone and requires manual workarounds. Especially due to the nature of CodeQL debugging is rather time consuming (or I don't know all the tricks yet).

---

I am currently thinking of two possible solutions for this:
- Override `LValue.getControlFlowNode()` and get the parent (assignment) as result. In my opinion this would be the more 'correct' solution. However, there would then not be a 1:1 mapping between AST element and control flow node anymore. This is an issue because `ControlFlowNode` extends `Top` and there is a lot of code which directly compares nodes with AST elements instead of using `getControlFlowNode()`. For sanity `ControlFlowNode` could be changed to only extend an algebraic type; though I guess you would refuse any such changes.
- The other more feasible solution would be to override `LValue.getControlFlowNode()` and deprecate it. The QLDoc could then explain that `getParent().getControlFlowNode()` should be used. This would at least prevent 'surprises' for users.
