### ISSUE TITLE
Java: Call does not extend ExprParent

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#5657]
**Description of the issue**
The CodeQL class `Call` does not extends `ExprParent`.
It looks like `forall(Call c | c instanceof ExprParent)` always holds, and I cannot currently think of any call type which does not permit any expression children. Therefore `Call` should probably extend `ExprParent`.

**Comment by smowton** [comment]
Looks like it could be: https://github.com/github/codeql/pull/5661

**Comment by smowton** [comment]
Done
