### ISSUE TITLE
LGTM.com - false positive - Variable is modified on runtime in Java

### ISSUE THREAD

**Issue by Lauriichan** [github/codeql#5693]
**Description of the false positive**

The project doesn't include all code as it is an addon for a Server software called "Spigot" for Minecraft
In this project, there are multiple things handled in this way that we're accessing variables directly of specific objects and those variables are changed on runtime.

Related to the Player1_8_R2 class:
Every accessed variable of the variable called "handle" is modified on runtime by the code used in this project
For example handle.locX; handle.locY; handle.locZ; handle.yaw and handle.pitch are the position and rotation of the entity object that we're accessing in this class.

Related to the Entity1_12_R1 class:
The here accessed player is a variable in a for loop and the "playerConnection" variable is different for every player in the collection of players.

**URL to the alert on the project page on LGTM.com**

Player1_8_R2 class:
https://lgtm.com/projects/g/SourceWriters/vCompat/snapshot/3010f54ce1afa1bb11d8fbfd370650cf05712963/files/src/main/java/net/sourcewriters/minecraft/vcompat/reflection/provider/v1_8_R2/entity/Player1_8_R2.java?sort=name&dir=ASC&mode=list

Entity1_12_R1 class:
https://lgtm.com/projects/g/SourceWriters/vCompat/snapshot/3010f54ce1afa1bb11d8fbfd370650cf05712963/files/src/main/java/net/sourcewriters/minecraft/vcompat/reflection/provider/v1_12_R1/entity/Entity1_12_R1.java?sort=name&dir=ASC&mode=list#x5e9306f63165b1:1

**Comment by smowton** [comment]
Looks like all those "Expression always evaluates to the same value." warnings stem from the access `.locX` and similar actually being a `TypeAccess` to a class named `sendPacket` (which is actually a method defined on a connection; unsure why this is mistaken for a class). Looks like extraction trouble rather than the query being oversensitive, in any case.

**Comment by smowton** [comment]
Try

```
from TypeAccess ta
where ta.getType().(Class).getName() = "sendPacket"
select ta
```

for example to see this odd class.

**Comment by Lauriichan** [comment]
I think the problem could be that lgtm has no access to the classes that we're using there, as they're not included in the projects code and are downloaded when being build, but I've no idea how lgtm actually does analyze the code so I could be very wrong here

**Comment by yo-h** [comment]
These false positives were due to extraction issues, which have now been fixed and deployed.

There are now [zero alerts](https://lgtm.com/projects/g/SourceWriters/vCompat/alerts/?mode=tree) for this project on lgtm.com.
