### ISSUE TITLE
Add stub structure files in Javascript experimental folder

### ISSUE THREAD

**Issue by mrthankyou** [github/codeql#5713]
# Description

There should be several stub structure files for Javascript external contributions in the `experimental/semmle/javascript` folder. #5493 resolved this issue in the python folder and I assume that this is how the CodeQL team would want this done for Javascript. I'm hoping this can be done for Javascript as well since I plan on submitting Javascript security queries in the next week or two.

**Comment by mrthankyou** [comment]
If it's easier/faster for me to create this PR than having it go to the CodeQL team queue please let me know. I'm more than happy to create a PR for this 😄. Thank you.

**Comment by yoff** [comment]
The various language teams organise their code slightly differently, I think javascript does not have a `concepts.qll`. You certainly want to put everything inside experimental, and probably in a self-contained way. You can still put parts in `.qll`-files where it makes sense. I would advice just submitting your contributions and let the language team guide you regarding structure.

**Comment by mrthankyou** [comment]
Thanks @yoff. I'm going to close this since I think you've answered my concern.
