### ISSUE TITLE
General issue:how to build a database from Multiple bundel

### ISSUE THREAD

**Issue by JiangLi23** [github/codeql#5720]
**Description of the issue**

I have an app compiled by multiple bundles. Each bundle has a code git. How do I deal with the entire APK as an analysis object?

Now I do it by analyzing a single code, but there's no way to correlate it.

**Comment by hmakholm** [comment]
The analysis CodeQL does is fundamentally a _whole-program analysis_, so it needs to see the entire system at once if you want to catch problems that depend on interactions between different parts of your system. Unfortunately that requirement doesn't play very smoothly with the tooling we've built _around_ the analysis in a case such as yours.

If you're managing the analysis yourself using the CodeQL CLI, you can just clone all of your repositories as children of a common parent directory, and run `codeql database create` on that common directory. If your project is in a compiled language where CodeQL depends on observing a build process, you'll need a script that involves the build system of each component in turn. However, we don't provide much tooling for exploring the analysis _results_ in those cases; you'd have to do something interesting yourself with the `csv` or `sarif` output from `codeql database analyze`.

It's worse if you hope to use the Code Scanning infrastructure that integrates the analysis with the GitHub experience, pull requests and so forth.

You can get the analysis to _run_ by amending the CodeQL workflow file such that it clones the subsidiary repositories before it starts using the `github/codeql-action` to bracket a build process. (This assumes that you know how to write workflow files for GitHub Actions, of course -- it that's not that hard). However, that way you will only get pull request integration with the "main" repository that you instrument that way, and alerts that CodeQL flags up in the other repositories might not show up in the UI.

**Comment by RasmusWL** [comment]
@JiangLi23 just wanted to check in whether this has helped resolve your problem? :blush:
