### ISSUE TITLE
LGTM.com - false positive: Python __init__ called twice alert ignores python's MRO

### ISSUE THREAD

**Issue by nritsche** [github/codeql#5760]
Class [..] may not be initialized properly as method [..].__init__ may be called multiple times during initialization.

This alert went off for a class D inheriting from B and C. B and C both inherit from A.
Python's super is smarter than that and doesn't call the diamond-shape-multiple-inheritance base class' `super` twice:
https://docs.python.org/3/library/functions.html#super

https://lgtm.com/projects/g/radiocosmology/draco/snapshot/ec02af52448cfb4d42cfae6f5a1f58051cc4ee87/files/draco/core/task.py?sort=name&dir=ASC&mode=heatmap#xab53fce3168d97bf:1

**Comment by tausbn** [comment]
You are correct that in general `super` does something clever, but in this case the cleverness is being counteracted by calling `LoggedTask.__init__` directly. Consider the following condensed example, based on the code you link to:
```python
 class Reader:
    def __init__(self):
        print("Reader init")

class TaskBase(Reader):
    def __init__(self):
        print("TaskBase init")

class LoggedTask(TaskBase):
    def __init__(self):
        print("LoggedTask init")
        super().__init__()

class MPITask(TaskBase):
    def __init__(self):
        print("MPITask init")
        super().__init__()

class MPILoggedTask(MPITask, LoggedTask):
    def __init__(self):
        print("MPILoggedTask init")
        MPITask.__init__(self)
        LoggedTask.__init__(self)

class MPILoggedTaskCorrect(MPITask, LoggedTask):
    def __init__(self):
        print("MPILoggedTaskCorrect init")
        super().__init__()

MPILoggedTask()
print()
MPILoggedTaskCorrect()
```
When run with Python 3, this produces the following output
```
MPILoggedTask init
MPITask init
LoggedTask init
TaskBase init
LoggedTask init
TaskBase init

MPILoggedTaskCorrect init
MPITask init
LoggedTask init
TaskBase init
```
Observe the duplicate entries in the first section above -- we are calling `TaskBase.__init__` and `LoggedTask.__init__` twice each, exactly as the alert states.

**Comment by nritsche** [comment]
Thanks, @tausbn. I must have missed that.
