### ISSUE TITLE
[C/C++] LGTM.com - false positive

### ISSUE THREAD

**Issue by LekKit** [github/codeql#5771]
**Description of the false positive**

Passing unsigned int multiplication result to malloc() results in
"Multiplication result may overflow 'unsigned int' before it is converted to 'size_t'."
In our case, this is just a 2D frame allocation, so >4 Gb is an overkill, and the passed values are limited anyways before they are passed to the function, so overflow is not possible.
It may be better to suppress such warnings for library functions (since user may never intended to use size_t in the first place) unless there is really a reason the value would overflow, but i might be wrong after all, thanks for any clarification in advance

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/LekKit/RVVM/snapshot/81b23c887710da3dba082ef1db707e850285a23d/files/src/devices/fb_window.c?sort=name&dir=ASC&mode=heatmap#x71ff5c73cf1ac7b1:1

**Comment by RasmusWL** [comment]
Hi @LekKit, thanks for your report :+1:

I discussed this with the C++ team, and the `malloc` call in question is exactly the pattern we want to flag with this query (that has caused real vulnerabilities in the past).

However, from looking at the code, it seems like `init_fb` is only used [here](https://lgtm.com/projects/g/LekKit/RVVM/snapshot/81b23c887710da3dba082ef1db707e850285a23d/files/src/riscv32.c?sort=name&dir=ASC&mode=heatmap#L170), and is used with small constant values, which matches with what you say yourself:

> and the passed values are limited anyways before they are passed to the function

So we get your point, and agree that this specific instance is an FP. 

We're going to keep this in our backlog for considering query improvements, but I can't make any promises on when/if we're going to look into improving this query to handle your case better.

**Comment by intrigus-lgtm** [comment]
> Just FYI, both GitHub Code Scanning and LGTM.com have facilities for suppressing individual alerts or disabling a query.

**Comment by LekKit** [comment]
> We're going to keep this in our backlog for considering query improvements

Thanks for your attention, that's exactly what i wanted to hear - maybe it should analyze the calls to the function in question, but as i think about it, it is possible that codeql thinks this function is linked externally (it isn't as of now), and so that it should be protected from arbitary values. I just think it might be a useful example. 

We fixed the alarm anyways soon after discovering it, by simply using a temporary variable to store multiplication result - and that by the way, in other circumstances (that codeql may already assumed) could be a vulnerability... so there isn't a certain answer unless codeql could read programmers minds :D 

Anyways, good luck 👍
