### ISSUE TITLE
Python query for index out of bounds?

### ISSUE THREAD

**Issue by pettershao-ragilenetworks** [github/codeql#5778]
**Description of the issue**

Hi  ql team,  I just simply create an issue about visit a list out of bounds, but seems no ql can detect  it, can you help figure out witch ql case can work for me, thanks!

**Comment by RasmusWL** [comment]
Hi @pettershao-ragilenetworks, can you give me a few more details as to what you're looking for?

- What language are you trying to analyze? 
- Can you provide a small snippet of code with the behavior you're trying to flag? (or a link to some code)

**Comment by pettershao-ragilenetworks** [comment]
hi @RasmusWl, thanks for replying, please check below information:
language: Python
code:
```
# -*- coding: utf-8 -*-

if __name__ == "__main__":
    l = list(range(4))
    print(l[5])
```

**Comment by RasmusWL** [comment]
Hi @pettershao-ragilenetworks, we do not have any Python queries for detecting index out of bounds currently. Since we are currently focused on security queries, I do not expect us to write any such queries in the near future either.

**Comment by pettershao-ragilenetworks** [comment]
Thanks! @RasmusWL but still sounds a little strange since c++ , java support index out of bounds query.

**Comment by RasmusWL** [comment]
Since our queries are developer _per_ language there can be differences in what queries are supported for which languages. Hopefully this solves your question :blush:

**Comment by RasmusWL** [comment]
Closing this issue off since it is stale :blush:
