### ISSUE TITLE
Docs: Metadata guides do not mention new `@kind` and `@tag` values

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#5827]
CodeQL CLI  version 2.5.3 added support for new values for the `@kind` and `@tag` metadata properties, see [release notes](https://github.com/github/codeql-cli-binaries/blob/main/CHANGELOG.md#release-253-2021-04-30).
However these new values are not documented in the respective guides:
- [Query file metadata and alert message style guide](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md)
- [Metadata for CodeQL queries](https://github.com/github/codeql/blob/main/docs/codeql/writing-codeql-queries/metadata-for-codeql-queries.rst)

Or is that intended because they are only supposed to be used by built-in CodeQL queries?

**Comment by dbartol** [comment]
Thanks for the report. We're still working on features that actually use those metadata properties, and will likely be adding more such properties in the near future. We expect to update the metadata docs once we've got the full set of new properties implemented.

**Comment by smowton** [comment]
Closing since both of these docs now mention these tags
