### ISSUE TITLE
Improve warning message:  Warning: Did not find any lines of code in database

### ISSUE THREAD

**Issue by mariusingjer** [github/codeql#5838]
**Description of the issue**

I am getting a warning in my codeql build which I have no idea what means, and google is not helping either.

![image](https://user-images.githubusercontent.com/65291983/117144693-84479600-adb2-11eb-8c24-ee295f364451.png)

Suggestion: give some more context to this warning, what does it mean?

**Comment by mariusingjer** [comment]
The error message stems from this file:
https://github.com/github/codeql-action/blob/1585462c63bbf1fe66558b776baebdf15cea0f3a/src/count-loc.ts

..still gets me wondering though

**Comment by aeisenberg** [comment]
We have recently introduced a baseline lines of code counter for the source code in your scan. We're using this as part of a larger feature to gather metrics about the repository being scanned.

In your case, for some reason, code scanning did not find any lines of code (it doesn't mean that your repository wasn't scanned, just that our LoC counter found nothing). It could be a bug. Though, it's hard to track this down without knowing a bit more about your repository. Is it public? If not, can you share a (sanitized) version of your code scanning workflow?

**Comment by mariusingjer** [comment]
`jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        language: [ 'csharp', 'javascript' ]
        include:
          - language: 'csharp'
            config: './.github/workflows/codeql-config-dotnet.yaml'
          - language: 'javascript'
            config: './.github/workflows/codeql-config-javascript.yaml'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        config-file: ${{ matrix.config }}
    - if: matrix.language == 'csharp'
      name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
`

config
`
name: "dotnet codeql config"

paths:
  - src
  - database
`

and

`
name: "javascript codeql config"

paths:
  - pipeline
  - pipeline-lambdas
`

**Comment by aeisenberg** [comment]
Thanks. This is useful. I'll see if I can get some way to reproduce.

**Comment by mariusingjer** [comment]
I just very quickly looked at the code, and I guess it can't be this simple, but I noticed that the values (which are the keys in the reversemap) doesn't match the languages. Could this be a bug?

analyze.ts:
```
  const locPromise = countLoc(
    path.resolve(),
    // config.paths specifies external directories. the current
    // directory is included in the analysis by default. Replicate
    // that here.
    config.paths,
    config.pathsIgnore,
    config.languages,
    logger
  );
```
count-loc.ts
````
const supportedLanguages = {
  c: "cpp",
  "c++": "cpp",
  "c#": "cs",
  go: "go",
  java: "java",
  javascript: "js",
  python: "py",
  ruby: "rb",
  typescript: "js",
};

const supportedLanguagesReversed = Object.entries(supportedLanguages).reduce(
  (obj, [key, value]) => {
    if (!obj[value]) {
      obj[value] = [];
    }
    obj[value].push(key);
    return obj;
  },
  {}
);

analysisLanguages: dbLanguages.flatMap(
  (lang) => supportedLanguagesReversed[lang]
),
```
languages.ts
```
// All the languages supported by CodeQL
export enum Language {
  csharp = "csharp",
  cpp = "cpp",
  go = "go",
  java = "java",
  javascript = "javascript",
  python = "python",
}
```

**Comment by aeisenberg** [comment]
Thanks for taking a deeper look into this. I'm not able to verify at this moment, but it's possible you've found the problem.

**Comment by tschaub** [comment]
Perhaps this is a totally unrelated project, but Googling for this "Did not find any lines of code in database" turns up examples like this: https://github.com/github/codeql-action/actions/runs/797613079

**Comment by RA80533** [comment]
`countLoc` ([definition](https://github.com/github/codeql-action/blob/35a83b92cafebd4eab6b6b459ab9dc1997f6bc04/src/count-loc.ts#L39)) appears to be typed incorrectly based on how it is used in [analyze.ts](https://github.com/github/codeql-action/blob/35a83b92cafebd4eab6b6b459ab9dc1997f6bc04/src/analyze.ts#L149); specifically, `dbLanguages` is widened from `Language[]` to `string[]`.

**Comment by aeisenberg** [comment]
Thanks all for pointing this out. This will be fixed next time we release.
