### ISSUE TITLE
CONTRIBUTING.md should mention change note creation

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#5904]
#5214 added a GitHub workflow for checking whether a pull request adds a change note. However there are currently two flaws:
- It looks like it is nowhere explained what a change note is. It would be good to add a section to [`CONTRIBUTING.md`](https://github.com/github/codeql/blob/main/CONTRIBUTING.md) explaining:
  - When a change note is needed
  - Where the change note should be placed (i.e. <code><var>language</var>/changes-notes</code>)
  - Which format change notes should have (maybe tell the user to have a look at existing ones)
  - What date should be used as part of the change note file name
- The workflow job name seems to be directed at maintainers instead of at the contributors:
  https://github.com/github/codeql/blob/17b74319faf7c7af7d2d7b8c3a45777ccae018aa/.github/workflows/check-change-note.yml#L15

  Maybe the following would be more useful:
  > Fail if no change note found. To fix, see CONTRIBUTING.md, or wait for a maintainer to review the pull request.

**Comment by intrigus-lgtm** [comment]
Wouldn't it be better to expand https://github.com/github/codeql/blob/main/docs/supported-queries.md instead?
Step 7 c) already talks about release notes.
Note that it refers to the **old** way (someone should fix this) of organizing change notes, when change notes were added [here](https://github.com/github/codeql/tree/main/change-notes) and not [here](https://github.com/github/codeql/tree/main/csharp/change-notes) (the new way).
Section "Supported CodeQL queries and libraries bullet point 2" also refers to the **old** way:
https://github.com/github/codeql/blob/ab90fe18fd3b1957ad26d9d18b2fa2d29cfe2bb5/docs/supported-queries.md#supported-codeql-queries-and-libraries

So maybe keep all the information related to supported queries (only supported queries should get a change-note afaik) in `supported-queries.md` and link to that from `CONTRIBUTING.md` (with an explanation along the lines of "only skip the 'contribute to experimental move to supported later' process if you know what you're doing^^") ?

**Comment by adityasharad** [comment]
Thanks for raising this.
The change note check workflow only runs on non-experimental contributions, so that instruction is indeed written with maintainers in mind, as we frequently make changes requiring change notes, or will be reviewing all such contributions.

Both of you raise good suggestions -- we may not get to them right away, but I'll leave this issue open to track them:
- Update `supported-queries.md` to refer to the new change note format and location
- Update `CONTRIBUTING.md` to mention when a change note is needed, and link to `supported-queries.md` for details

**Comment by AlexDenisov** [comment]
It should also mention the date format, so far we have yyyy-mm-dd and yyyy-dd-mm :)

**Comment by MathiasVP** [comment]
> It should also mention the date format, so far we have yyyy-mm-dd and yyyy-dd-mm :)

Thanks for spotting these! I've fixed the C++ ones here: https://github.com/github/codeql/pull/5942

**Comment by Marcono1234** [comment]
This has been addressed by #7400 now, correct? Can I close this issue now?

**Comment by smowton** [comment]
Closing in view of https://github.com/github/codeql/blob/main/docs/change-notes.md
