### ISSUE TITLE
How to determine if the type of a variable is a struct or not?

### ISSUE THREAD

**Issue by powerthe900** [github/codeql#5905]
Currently my codeql query gets the unspecified type of the variable lemon and this returns in foo *. I want my query to see if the type is a struct. How would I do this?
```c
struct foo2 {
int data;
int length;
}
typedef struct foo2 foo;
foo* lemon;
```

**Comment by powerthe900** [comment]
To provide further context, my work is on a C++ project.

**Comment by selim** [comment]
https://en.wikipedia.org/wiki/Run-time_type_information?wprov=sfti1

**Comment by intrigus-lgtm** [comment]
Something like [this](https://lgtm.com/query/5258820927240341325/)?
```ql
from Variable var
where 
var.getUnspecifiedType() instanceof Struct
or
var.getUnspecifiedType().(PointerType).getBaseType+().getUnspecifiedType() instanceof Struct 
select var
```
This should find all variables in the program that are a `struct` or which are a pointer to a `struct`.

**Comment by MathiasVP** [comment]
You can also use `stripType` like so:
```codeql
from Variable var
select var, var.getUnspecifiedType().stripType()
```

For your example that should give you: `lemon, foo2`.

**Comment by powerthe900** [comment]
thank you so much this works

**Comment by MathiasVP** [comment]
> thank you so much this works

Happy that it worked :)
