### ISSUE TITLE
Repeated spamming of the same issue

### ISSUE THREAD

**Issue by schmidtw** [github/codeql#5915]
**LGTM Spams Issues**

The agent constantly spams new entries with no new information.  This has forced the issue to the point that we're going to turn of LGTM and look elsewhere.

https://github.com/xmidt-org/bascule/pull/104#issuecomment-840214211

**Comment by schmidtw** [comment]
![image](https://user-images.githubusercontent.com/698825/118587899-3e93b180-b752-11eb-8698-5e01e728be1c.png)

**Comment by smowton** [comment]
Does this happen for all your PRs, or all that generate any alert, or just some? Were the deleted comments absolutely identical, or just very similar?

**Comment by schmidtw** [comment]
This isn't an isolated incident, but I don't have any other examples.  We also weren't able to find any reasonable way to shut off the issues.

I happened to have a tab open & took a screenshot.  It looks like every change of a file, LGTM felt compelled to repeat itself.
![image](https://user-images.githubusercontent.com/698825/118608567-afe15d80-b76e-11eb-83e6-22404c2b954e.png)

**Comment by smowton** [comment]
Note you can specifically disable just the comments rather than the whole integration: by clicking the gear wheel to the right of "Automated Code Review" you can choose "Deactivate comments" while leaving the status badge enabled.

**Comment by schmidtw** [comment]
Here is another example:
https://github.com/xmidt-org/ears/pull/111

**Comment by smowton** [comment]
The intent is to note that while the PR branch tip has moved, the new problem remains (compared to the branch the PR is targeting). In this particular use case where you are frequently pushing new commits this can produce too much noise however. In such a case disabling bot comments and only using a CI status badge to monitor whether your PR introduces new alerts is probably the right course of action.
