### ISSUE TITLE
when i use codeql CLI，it report java.lang.ClassNotFoundException: com.semmle.cli2.CodeQL

### ISSUE THREAD

**Issue by B0sS-Tang** [github/codeql#6005]
when i try to analyse the database，terminal show:
```
PS D:\chrome\cef_binary_90.6.6+g3c44b04+chromium-90.0.4430.93_windows64\build\tests\cefclient\Debug\ql\1622735574> ..\codeql\codeql.exe database analyze .\demo ..\vscode-codeql-starter\ql\javascript\ql\src\code_test.ql --format=csv --output=out.csv
Running queries.
错误: 找不到或无法加载主类 com.semmle.cli2.CodeQL//“错误: 找不到或无法加载主类” means error: Cannot find or load the main class
原因: java.lang.ClassNotFoundException: com.semmle.cli2.CodeQL//"原因" means reason
```
can anybody help me，oh....
thanks a lot

**Comment by RasmusWL** [comment]
Hi @B0sS-Tang, that does sound like a strange problem. Can you tell us a few more details, so we can figure out what is going on here?

- What version of the CLI did you download?
- How did you unpack it?
- Have you tried downloading the CLI again?
- Have you set the `CODEQL_DIST` environment variable? (probably not, but that could be a cause)
