### ISSUE TITLE
how can i build extractor java source to jar

### ISSUE THREAD

**Issue by jax777** [github/codeql#6022]
i want to build extractor to jar；
https://github.com/github/codeql/blob/main/javascript/extractor/src/com/semmle/js/extractor/FileExtractor.java

but i can import com.semmle.util；so i cant build success

**Comment by rdmarsh2** [comment]
Unfortunately, it's not yet possible to build the JavaScript extractor from just github/codeql. Those files are shared with another codebase, and are currently in its closed-source repository.

If you're just trying to get a copy of the current extractor, it's included in our binary releases here: https://github.com/github/codeql-cli-binaries/
