### ISSUE TITLE
How to choose unique expressions in the select statement?

### ISSUE THREAD

**Issue by powerthe900** [github/codeql#6054]
I currently have a query that returns the values of three expressions like this.
```import cpp

from Function f, Variable v, string s, string l
where 
foo
select f, s, l
```
The problem that I come across is that for each function f there are multiple values of l.  For example, the output would be
printf, foo, lemon
printf, foo, straw

How could I write the query in such a way that it only chooses the first value of l. In this case, it would be lemon.

**Comment by rdmarsh2** [comment]
Assuming you're looking for the lexicographically first, you'd want to use the [`min` aggregate](https://codeql.github.com/docs/ql-language-reference/expressions/#aggregations) to find the lowest value of `l` for each set of values of the other variables. That would look something like this:

```codeql
from Function f, Variable v, string s, string l_min
where 
l_min = min(string l | foo(f,v,s,l))
select f, s, l_min
```

If you're wanting the value of `l` that appears earliest in a source file, you'd probably want to use an `order by` clause, something like this:

```codeql
from Function f, Variable v, string s, string l_min
where 
l_min = min(
  string l, Expr e, Location eLoc
  |
  foo(f,v,s,l) and
  bar(v, e, l) and // connect e to the other QL variables
  eLoc = e.getLocation()
  |
  l order by eLoc.getStartLine(), eLoc.getStartColumn(), eLoc.getEndLine(), eLoc.getEndColumn()
  )
select f, s, l_min
```

**Comment by powerthe900** [comment]
This did not work. Foo in my example just represents whatever I wrote in my where statement.

**Comment by rdmarsh2** [comment]
Oh, you don't need to copy the parenthesized stuff there. I just realized you have a variable in the `from` that isn't used in the `select` - you might need to move that declaration into the `min`, since it could have multiple values for a given `f` and `s`.

**Comment by powerthe900** [comment]
this did not work.
Are there any ideas to remove the duplicates from the l variable?

**Comment by powerthe900** [comment]
I messed up my query. Your solution works. Thank you so much!
