### ISSUE TITLE
General issue  Anything to main method don't exist in database

### ISSUE THREAD

**Issue by Sharyie** [github/codeql#6057]
hello, I used CodeQL to scan my springboot project, found that CodeQL did not generate AST of main method of project or something about main method, I can't search anything from database that method name is "main" and method invoked in main method body. I want learn is this a feature or CodeQL could't do it ?

my SpringbootApplication class:

`
@SpringBootApplication
public class Application {

    public static void main(String[] args) throws Exception {
        ParserConfig.getGlobalInstance().setSafeMode(true);

        // some code start the application

    }
}
`

i want to detect whether my project enable fastjson.safeMode feature, so I wrote ql:
`
import java
import semmle.code.java.dataflow.FlowSources
import semmle.code.java.frameworks.FastJson

class FastJsonSink extends MethodAccess {
    FastJsonSink() {
      exists(Method m |
        this.getMethod() = m and 
        not fastJsonLooksSafe() and
        m.hasName(["parse", "parseObject"])
        and m.getDeclaringType().hasQualifiedName("com.alibaba.fastjson", "JSON") 
      )
    }
}

from FastJsonSink m
select m.toString() as method,m.getLocation().getFile().getRelativePath()+":"+m.getLocation().getStartLine()+":"+m.getLocation().getStartColumn() as location
`

I invoked JSON.parse in some business code, the result of this ql is not emtpy, of course that was a worry output, unless I wrote 'ParserConfig.getGlobalInstance().setSafeMode(true);' in some business code and got right result that is empty.
I wrote main method and sink method(JSON.parse) invoked process in body to business code(eg: XxxServiceImpl.java), the result of this ql is also not empty and did not contain FastjsonSink in new main method.

**Comment by smowton** [comment]
I've confirmed in a trivial test project a `main` method like that **does** make `fastJsonLooksSafe()` satisfiable, so the problem must be particular to your project setup.

Note for Java if you do a `codeql database create` then the default build command will be `mvn clean package -f "pom.xml" -B -V -e -Dfindbugs.skip -Dcheckstyle.skip -Dpmd.skip=true -Denforcer.skip -Dmaven.javadoc.skip -DskipTests -Dmaven.test.skip.exec -Dlicense.skip=true -Drat.skip=true`, **and only `.java` files touched while running that command will be indexed**. Do you expect `Application.java` to be caught in a build launched that way? Are there `.java` file inclusion / exclusion sets defined that might leave that file out?

To check if the file was indexed at all, you could try a quick query `from Method m where m.hasName("main") and m.isStatic() select m` and see whether that `main` method was included in the build. You could also use the `--command` flag to `codeql database create` to try different build commands that should touch `Application.java`.

**Comment by Sharyie** [comment]
thx,I verified in a new demo.
