### ISSUE TITLE
HTMLExtractor.java can support <script lang="tsx">

### ISSUE THREAD

**Issue by jax777** [github/codeql#6066]
https://github.com/github/codeql/blob/ef0ea247c40da805efa427a37f5213457d18f714/javascript/extractor/src/com/semmle/js/extractor/HTMLExtractor.java#L274

<script lang="tsx"> value <script>,this kind of code cant be recoginzed as typescript；
i think code in  HTMLExtractor can add 
`if ("tsx".equals(language) ||"ts".equals(language) || "typescript".equals(language)) return true;`

**Comment by asgerf** [comment]
Thanks for the suggestion @jax777, this seems like a good idea.

Do you have a link to some code that uses `<script lang="tsx">`?

**Comment by jax777** [comment]
https://github.com/search?l=Vue&q=%3Cscript+lang%3D%22tsx%22%3E&type=Code
i searched like this 

such as https://github.com/pkej/vue-cli-3-nuxt-typescript/blob/61a12831e2ae7192f3a3dfa15f8f6fd702c1fa32/src/pages/lang-tsx.vue
https://github.com/LiuJiangshan/ele-tree-table/blob/e9322a7371ff3eea2eb8a7e374098971b7d2c24b/example/app.vue
