### ISSUE TITLE
False positive - caches.match

### ISSUE THREAD

**Issue by iam-py-test** [github/codeql#6067]
**Description of the false positive**
CodeQL flags caches.match (Client side JS) as an insecure RegExp match when it is used to retrieve a url.<br>
This is not an issue because:
- No user-supplied data is used
- It is not an RegExp
- It is not being used to test urls - all of that is done internally (probably) without RegExps

**URL to the alert on the project page on LGTM.com**
Screenshot: 
![image](https://user-images.githubusercontent.com/84232764/121815292-b4047c00-cc43-11eb-8595-3b948265f343.png)

Repo: https://github.com/iam-py-test/check-site
URL to GitHub security alert: https://github.com/iam-py-test/check-site/security/code-scanning/2?query=ref%3Arefs%2Fheads%2Fmain

**Comment by tausbn** [comment]
Thanks for bringing this to our attention! To my untrained (in JavaScript) eyes, this _does_ look like a false positive, as I assume `caches` is intended to be an instance of something like `Cache` (and not `String`, where the `match` method would indeed be using its argument as a regular expression).

I have relayed this report to the JavaScript team for further comment.

**Comment by iam-py-test** [comment]
> Thanks for bringing this to our attention! To my untrained (in JavaScript) eyes, this _does_ look like a false positive, as I assume `caches` is intended to be an instance of something like `Cache` (and not `String`, where the `match` method would indeed be using its argument as a regular expression).
> 
> I have relayed this report to the JavaScript team for further comment.

Thanks for your prompt reply.
`caches` is the interface for storing parts of websites for offline use, and is an instance of CacheStorage.
I am not familiar with how CodeQL works, so I am not sure how (or if) that can be implemented.

**Comment by asgerf** [comment]
@iam-py-test Thanks again for your report. We've merged https://github.com/github/codeql/pull/6117, which should fix the FP you reported.
