### ISSUE TITLE
LGTM.com - false positive -  py/insecure-protocol

### ISSUE THREAD

**Issue by huornlmj** [github/codeql#6074]
**Description of the false positive**

py/insecure-protocol reports "Insecure SSL/TLS protocol version TLSv1 allowed by" in the following chunk, where you can see that TLS 1.2 is enabled and TLS 1.0, 1.1 is disabled:

```
ssl_context.options |= ssl.PROTOCOL_TLS
ssl_context.options |= ssl.OP_NO_SSLv2
ssl_context.options |= ssl.OP_NO_SSLv3
ssl_context.options |= ssl.OP_NO_TLSv1
ssl_context.options |= ssl.OP_NO_TLSv1_1
ssl_context.set_ciphers(CIPHERS)
self.socket = ssl_context.wrap_socket(self.socket, server_side=True)
```

Detected with codeql CLI and codeql-repo/python/ql/src/codeql-suites/python-lgtm-full.qls

**Comment by tausbn** [comment]
Can you supply us with some more context, or a link to the code in question?

I just tried adding the following test example to [the test files for this query](https://github.com/github/codeql/blob/main/python/ql/test/query-tests/Security/CWE-327/ssl_fluent.py) and it does _not_ result in an additional alert being raised by our analysis. If I comment out either the `TLSv1` or `TLSv1_1` line, an alert is raised, as expected.
```python
def test_reported_fp():
    hostname = 'www.python.org'
    ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS)
    ssl_context.options |= ssl.OP_NO_SSLv2
    ssl_context.options |= ssl.OP_NO_SSLv3
    ssl_context.options |= ssl.OP_NO_TLSv1
    ssl_context.options |= ssl.OP_NO_TLSv1_1
    ssl_context.set_ciphers(CIPHERS)
    with socket.create_connection((hostname, 443)) as sock:
        with ssl_context.wrap_socket(sock, server_hostname=hostname) as ssock:
            print(ssock.version())
```
