### ISSUE TITLE
Add me to the organisation

### ISSUE THREAD

**Issue by vedantmgoyal2009** [github/codeql#6104]
Hi there, 
My GitHub Username - @vedantmgoyal2009
Please add me to the organisation.

**Comment by tausbn** [comment]
Why do you wish to be added to the organisation?

If you want to contribute, you can just open a PR.

**Comment by vedantmgoyal2009** [comment]
I wish to be added because a badge appears on the profile that "You are a member of :this: organisation"

**Comment by vedantmgoyal2009** [comment]
Waiting to be added

**Comment by tausbn** [comment]
That does not appear to be a valid reason.

**Comment by vedantmgoyal2009** [comment]
Actually, I want to be added so that I can contribute to private repos
