### ISSUE TITLE
Non-monotonic recursion, false positive?

### ISSUE THREAD

**Issue by bocherry** [github/codeql#6118]
Hello, 

I am trying to write a predicate to give a textual representation of an Expr in javascript without the "..." given by the toString predicate.
It is structured as such : 

`    
(...)
(node instanceof BinaryExpr) and
        result = textualRepresentation(node.(BinaryExpr).getLeftOperand()) + node.(BinaryExpr).getOperator() + textualRepresentation(node.(BinaryExpr).getRightOperand()) 
or
(node instanceof UnaryExpr) and
        result = node.(UnaryExpr).getOperator() + textualRepresentation(node.(UnaryExpr).getOperand())
(...)        
`

It goes recursively through Expr, with a custom behaviour for each Expr subtype. 

I am facing a problem when I treat Expr having an unknown number of elements (element of ArrayExpr, arguments of a CallExpr, etc. ) : because I use an aggregation to retrieve each of them and then treat them recursively, the compiler won't let it happens as it considers it being a non-monotonic recursion. 
As an example, how I would like to treat ArrayExpr : 

`
    (node instanceof ArrayExpr) and
        result = "[" + concat( textualRepresentation( node.(ArrayExpr).getAnElement() ), ", " ) + "]"
`
In this case, the compiler says it is a non-monotonic recursion. However, as I always go deeper into the tree, isn't the recursion supposed to always end? 

Alternatively, is there another method to get a complete string representation (without "...") of the ArrayExpr elements ?

Thank in advance

**Comment by criemen** [comment]
Hey,

I think you'd want to check out the PrintAST library - it already provides a graph representation of the whole AST, which can also be turned into a text output by our tooling. The AST printing is also integrated into the VSCode extension.
However, it doesn't seem to fit your wish of enumerating all the elements in an `ArrayExpr` (etc.). For that, it might make sense to modify in `PrintAST.qll` `PrettyPrinting:repr` and add some more cases.

For your other question: QL does not support [recursion through regular aggregates](https://codeql.github.com/docs/ql-language-reference/recursion/), as alluded to in the documentation.
However, we do have monotonic aggregates, which _are_ allowed in recursions:
- https://codeql.github.com/docs/ql-language-reference/expressions/#monotonic-aggregates
- There is also a PR that adds more documentation on them that's not yet on the docs webpage that might help you https://github.com/github/codeql/pull/5934

**Comment by bocherry** [comment]
Hello,

Thank you for your kind and clear answer :) . 
Simple question, do you have in plan to add a generic predicate like toString but without the "..." ?

**Comment by criemen** [comment]
Hey,

the short answer is no.
There are some technical problems if you want to compute the full `toString` predicate in QL that make this infeasible in the general case.

Usually in QL, if we want to work with the information you're asking for, we'd do a recursion through the AST classes, instead of constructing a string that contains all the data.

**Comment by bocherry** [comment]
Ok thank you!
