### ISSUE TITLE
How to use "@deprecated" queries?

### ISSUE THREAD

**Issue by xiaoxinz-cisco** [github/codeql#6124]
**Description of the issue**

Hi,

In external queries: https://github.com/github/codeql/blob/main/cpp/ql/src/external/ , all are marked as `@deprecated`, I removed this line in the query and wanted to run it, but the output is empty, seems it doesn't run properly.

This is the only description I found about `@deprecated`: https://github.com/github/codeql/blob/main/docs/supported-queries.md

Could you let me know how to use these external queries?

Thanks

**Comment by criemen** [comment]
Hi,

if you tried to run the queries about code duplication, these unfortunately do not work any longer.
These queries rely on information in the CodeQL database that is no longer written into the database, hence the empty results from the query. There is nothing you can do about that :(

**Comment by xiaoxinz-cisco** [comment]
Hi @criemen ,

Thanks for the explanation. Is there any way to identify code duplication? 
I found this doc https://codeql.github.com/codeql-standard-libraries/cpp/external/CodeDuplication.qll/module.CodeDuplication.html but as you mentioned, it may be unavailable now?

If it's still available to use, is there any usage example?

Thanks

**Comment by criemen** [comment]
HI @xiaoxinz-cisco,
that library is unfortunately also unavailable. I will file an issue internally to get it removed, because it is very confusing.

CodeQL is a tool mainly aimed at security research, and finding duplicate code is outside the scope of the product.
