### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by corinwagen** [github/codeql#6176]
**Description of the false positive**

The error states that normal methods ought to have ``self`` as the first parameter, but this is an abstract method (as evidenced by the `` @abstractmethod`` decorator) - so the error doesn't apply. I'm not sure how hard it would be to recognize this decorator, or how common abstract methods are practically speaking, so feel free to disregard this issue if it's mostly irrelevant. 

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/ekwan/cctk/snapshot/42efb4de45fa18425b432164c597227e78832d82/files/cctk/group.py?sort=name&dir=ASC&mode=heatmap#x7853d470c6bdb605:1

**Comment by tausbn** [comment]
Thank you for your report!

I would like to understand why you think this is a false positive. Unless I've misunderstood the official documentation, the presence of an `@abstractmethod` annotation does _not_ change the nature of the underlying method. If you call it (which you can using `super()`), then the first argument _will_ be a reference to the instance on which this method is invoked. And going by the documentation again, it seems that `self` is the preferred name for this argument [even for abstract methods](https://docs.python.org/3/library/abc.html#abc.abstractmethod).

Judging by how this function is actually invoked, it seems that you're using it as a static method of the `Group` class, in which case you might want to add the `@staticmethod` decorator as well?

**Comment by corinwagen** [comment]
Hm, you may be right - I wasn't familiar with instances of calling it with
self as the first argument, but you're right that this appears to be
normal, and that my usage might be better suited for @staticmethod.

Thanks for teaching me something new, and score 1 for lgtm!
