### ISSUE TITLE
LGTM.com - Python: Call to next() in a generator - false positive

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [github/codeql#6227]
**Description of the false positive**

`Call to next() in a generator` is reported for a block of code with `next()` call that is wrapped in `try-except` catching the `StopIteration`.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/pantsbuild/pants/snapshot/66951bf70ab4c9d9461bcb453c7fc125f27e6cdc/files/build-support/bin/release_helper.py?sort=name&dir=ASC&mode=heatmap#xf7fe7e231aad14fd:1

**Comment by hvitved** [comment]
@github/codeql-python could you take a look please?

**Comment by tausbn** [comment]
Thank you for the report! I have created a fix for it which should land at some point (though with this being high season for holidays, I can't exactly say when this will be).
