### ISSUE TITLE
General issueMy blog has a security issue. Chrome Browser has blocked it

### ISSUE THREAD

**Issue by 78434309** [github/codeql#6245]
![Screenshot_20210710-132320_Chrome](https://user-images.githubusercontent.com/85474664/125157053-23598700-e182-11eb-9e50-2262a72207d9.jpg)

My blog has a security issue. Chrome Browser has blocked it

**Comment by ngoclong19121990** [comment]
Ok

0921757857

Vào 03:26 PM, T.7, 10 Th7, 2021 78434309 ***@***.***> đã viết:
