### ISSUE TITLE
bqrs interpret `-t` usage

### ISSUE THREAD

**Issue by xiaoxinz-cisco** [github/codeql#6307]
**Description of the issue**
Hi, in https://codeql.github.com/docs/codeql-cli/manual/bqrs-interpret/#cmdoption-codeql-bqrs-interpret-t , can you give an example that explains the use of `-t` in CLI? I've tried `-t=<kind="problem", id="cpp/...">` and others, all didn't work.
Thanks.

**Comment by smowton** [comment]
Did you try `-t=key=value`?
