### ISSUE TITLE
CodeQL Go support does not work with repository for multiple targets

### ISSUE THREAD

**Issue by rhysd** [github/codeql#6321]
**Description of the issue**

I tried CodeQL with the following project and faced an issue.

https://github.com/rhysd/actionlint

Package layout of this project is as follows:

- `/`: Package `actionlint` for library
- `/cmd/actionlint/`: Package `main` for CLI
- `/playground/`: Package `main` for browser (compiled with `GOARCH=wasm`)

This project cannot be built with `go build ./...` because multiple packages target different platforms. `/cmd/actionlint` targets current platform and `/playground` targets `js/wasm`.

To build this project, building each binaries respectively is necessary:

```
go build ./cmd/actionlint
GOOS=js GOARCH=wasm go build -v -o ./playground/main.wasm ./playground/
```

However, CodeQL tries to compile Go project with pattern `./...`. The workflow steps I tried on GitHub Actions is as follows:

```yaml
- uses: actions/checkout@v2
- uses: github/codeql-action/init@v1
  with:
    languages: go
- uses: github/codeql-action/autobuild@v1
- uses: github/codeql-action/analyze@v1
```

And here is an example of job failure at `uses: github/codeql-action/analyze@v1`:

https://github.com/rhysd/actionlint/runs/3100854367?check_suite_focus=true

```
[2021-07-19 05:54:24] [build-stderr] 2021/07/19 05:54:24 Running /opt/hostedtoolcache/go/1.16.5/x64/bin/go failed, continuing anyway: exit status 1
[2021-07-19 05:54:24] [build-stderr] 2021/07/19 05:54:24 Running extractor command '/opt/hostedtoolcache/CodeQL/0.0.0-20210702/x64/codeql/go/tools/linux64/go-extractor [./...]' from directory '/home/runner/work/actionlint/actionlint'.
[2021-07-19 05:54:25] [build-stderr] 2021/07/19 05:54:25 Build flags: ''; patterns: './...'
[2021-07-19 05:54:25] [build-stderr] 2021/07/19 05:54:25 Running packages.Load.
[2021-07-19 05:54:25] [build-stderr] 2021/07/19 05:54:25 Error running go tooling: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -- ./...]: exit status 1: go build syscall/js: build constraints exclude all Go files in /opt/hostedtoolcache/go/1.16.5/x64/src/syscall/js
[2021-07-19 05:54:25] [build-stderr] 2021/07/19 05:54:25 Extraction failed: exit status 1
Error: 7-19 05:54:25] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20210702/x64/codeql/tools/linux64/preload_tracer, /opt/hostedtoolcache/CodeQL/0.0.0-20210702/x64/codeql/go/tools/autobuild.sh])
```

From the log, the `go-extractor` tool tried to run the following command and it failed:

```
go -e -json -compiled=true -test=false -export=false -deps=true -find=false -- ./...
```

As I described above, this command fails because one of packages in my project needs to be built with `GOOS=js GOARCH=wasm`.

I looked into the codebase to configure the `./...` pattern, but it was hard-coded here. So I could not change it.

https://github.com/github/codeql-go/blob/b03513bcd209c957ffe2bffecf52766c0f4e3901/codeql-tools/index.sh#L10

My suggestion is allowing to specify the pattern by input of `github/codeql-action/analyze` action or by the configuration file (meant specifying packages which are analyzed) so that I can specify only the packages which target the current platform.

**Comment by sauyon** [comment]
Hiya! Have you tried adding run steps as described [here](https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-the-codeql-workflow-for-compiled-languages#adding-build-steps-for-a-compiled-language)?

**Comment by rhysd** [comment]
Yes, I also tried steps like below. But it did not help to solve this issue. The same error occurred at the same place.

```yaml
- uses: actions/checkout@v2
- uses: github/codeql-action/init@v1
  with:
    languages: go
- uses: actions/setup-go@v2
  with:
    go-version: '1.16'
- name: Build Go sources
  run: |
    go build ./cmd/actionlint
    GOOS=js GOARCH=wasm go build -o ./playground/main.wasm ./playground
- uses: github/codeql-action/analyze@v1
```

Here is the example of job failure when I tried above:

https://github.com/rhysd/actionlint/runs/3101003621?check_suite_focus=true

**Comment by sauyon** [comment]
Could you try adding `CODEQL_EXTRACTOR_GO_BUILD_TRACING=on` in the `env`?

**Comment by rhysd** [comment]
Sure. Let me try it.

**Comment by rhysd** [comment]
@sauyon I'm sorry this seems my fault.

I re-created the workflow from scratch again to ensure everything is clean:

https://github.com/rhysd/actionlint/blob/cbeea14667a574941a4bc1be886528a016576332/.github/workflows/codeql.yaml

And this time, workflow ran successfully:

https://github.com/rhysd/actionlint/runs/3103985348?check_suite_focus=true

I have no idea why previously the workflow did not work. But it seems to work now.

**Comment by sauyon** [comment]
That's weird, but I'm glad that worked :)

**Comment by rhysd** [comment]
Thank you for looking into this issue. I'll continue to use CodeQL and check if this issue does not reproduce again.

**Comment by rhysd** [comment]
@sauyon I found the condition to reproduce this issue.

After [removing the `CODEQL_EXTRACTOR_GO_BUILD_TRACING` env var](https://github.com/rhysd/actionlint/commit/bf2ae2c9e75e786be3f2953e1f07f6b6ac176dee), the job failed again with this issue.

https://github.com/rhysd/actionlint/runs/3105133513?check_suite_focus=true

I don't know what the environment variable does, but it seems to trigger this issue.

**Comment by sauyon** [comment]
Ok, that makes sense and would be what I'd expect. I'll raise this so that we can correct our documentation.

**Comment by rhysd** [comment]
Thanks. I'll wait for the update.
