### ISSUE TITLE
Nunjucks: external link

### ISSUE THREAD

**Issue by undefined-moe** [github/codeql#6359]
It's [nunjucks](https://mozilla.github.io/nunjucks/) grammar

https://lgtm.com/projects/g/hydro-dev/Hydro/snapshot/dbb77fe0cecb3c4b51a1c8d399f6e1a4978ad6d3/files/packages/ui-default/templates/user_detail.html#x807f5a3f495e67a2:1

**Comment by erik-krogh** [comment]
Thanks for the report, that was a false positive. 

It should be fixed with #6399 

It might take a few weeks for the fix to appear on LGTM.com

**Comment by undefined-moe** [comment]
I don't think the fix is correct.

In nunjucks, `url` isn't a builtin function, and user should pass them into the rendering context manually,
which means user might use something like `link` `get_url` instead of `url`.

I think maybe we can simply check if the url starts with `{{` ?

**Comment by erik-krogh** [comment]
> I don't think the fix is correct.
> 
> In nunjucks, `url` isn't a builtin function, and user should pass them into the rendering context manually,
> which means user might use something like `link` `get_url` instead of `url`.
> 
> I think maybe we can simply check if the url starts with `{{` ?

Hmm.. 

I did consider simply checking if the url starts and ends with a templating marker (like `{{`).   
But we do have desirable TPs of that form, like `<a href="{{some_templating_variable}}">foo</a>`.  
So I'm not sure what we can do about it.

**Comment by undefined-moe** [comment]
I think a url started matches `\{\{.+?\}\}.*` can't be a external link.  
I'm using the code below in `lostpass.html` , variables are nearly impossible to handle.

```
<p><a href="{{ url_prefix }}{{ url }}">{{ url_prefix }}{{ url }}</a></p>
```

**Comment by erik-krogh** [comment]
> I think a url matches `\{\{.+?\}\}.*` can't be a external link.

Unfortunately, such a url can be an external link (at least that is the case for other template engines).  
So I'm still not sure what a good solution could be.

**Comment by undefined-moe** [comment]
https://lgtm.com/projects/g/vijos/vj4/snapshot/bf5bb5c1f9131429308a733b8882564dcbc9fd66/files/vj4/ui/templates/partials/header_mobile.html#xdcf30e06f4d6f773:1
