### ISSUE TITLE
false positive for java/non-static-nested-class

### ISSUE THREAD

**Issue by arburk** [github/codeql#6361]
Today I added a **Junit5** nested test class to a unit test. 
```java
 @Nested
  class SrcDirectoryFromPom  {
     ...
  }
```

As consequence codeQL now alerts the class to be made static which is not possible for nested test classes. I assume the responsible query does not distinguish between test and productive classes.

Details can be found in the Git repo: https://github.com/baloise-incubator/codeql2sonar-maven-plugin/security/code-scanning/3?query=ref%3Arefs%2Fheads%2Fmain

**Comment by smowton** [comment]
Suggested fix: https://github.com/github/codeql/pull/6366

**Comment by smowton** [comment]
Fix merged
