### ISSUE TITLE
Can anyone tell how primaryLocationLineHash be generated?

### ISSUE THREAD

**Issue by Sharyie** [github/codeql#6367]
### Discussed in https://github.com/github/codeql/discussions/5982

<div type='discussions-op-text'>

<sup>Originally posted by **ZH3FENG** June  1, 2021</sup>
I have read part of _SARIF_ https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/sarif-v2.1.0-cs01.html, particularly  _partialFingerprints property_.
Also, _SARIF results file_ from https://lgtm.com/help/lgtm/sarif-results-file.

> This will contain, at a minimum, a value for the primaryLocationLineHash, which provides a fingerprint based on the context of the primary location.

Can anyone tell me how _primaryLocationLineHash_ be generated. What algorithm ？
I have noticed the result contains _codeflow_ property. Does  _codeflow_ affect generation of _primaryLocationLineHash_ ?
</div>

I got the same confusion,could anyone tell some rough factors during primaryLocationLineHash been generated.

**Comment by aeisenberg** [comment]
Is this on LGTM or in code scanning using the GitHub CodeQL Action?

For LGTM, this value is generated based on the line and column offsets for each source element. So, the hashes are sensitive to the amount of text present in the different parts of the file.

For the CodeQL Action, the hashes are a bit more stable when changes happen in the file. The hashes are based on the contents of the line and some relative location in the file.
