### ISSUE TITLE
LGTM.com - false positive Sensitive data (id, password)

### ISSUE THREAD

**Issue by BoYanZh** [github/codeql#6380]
**Description of the false positive**

It will only log the engine, not the id and password.

**URL to the alert on the project page on LGTM.com**

<https://lgtm.com/projects/g/joint-online-judge/horse/snapshot/556f8f0d38df6e88a1eac9dccde5d9c9daf85825/files/joj/horse/utils/db.py?sort=name&dir=ASC&mode=heatmap#xc52233c733123edc:1>

**Comment by aeisenberg** [comment]
Thanks. That does look suspicious. I am forwarding this to our Python team.
