### ISSUE TITLE
LGTM.com - cpp/incorrect-allocation-error-handling false positive with std::nothrow

### ISSUE THREAD

**Issue by Joshua-Anderson** [github/codeql#6435]
**Description of the false positive**

Fprime is a C++ project targeting embedded systems and is explicitly calling the `new(std::nothrow)` variant of new.
Because of this, it must check that the return value of `new(std::nothrow)` is null. The cpp/incorrect-allocation-error-handling incorrectly suggests that the allocation cannot return null, despite the fact that it can. Suggesting the incorrect error handling of memory allocation is dangerous and can lead to serious bugs.

It looks like cpp/incorrect-allocation-error-handling query has logic for handling std::nothrow but isn't successfully matching these calls to `new(std::nothrow)`.

https://lgtm.com/projects/g/nasa/fprime/rev/pr-47d3627dbb3106f32896b17edc48b8829d494566

**Comment by MathiasVP** [comment]
Hi @Joshua-Anderson,

Thanks for the report. Indeed, there was a problem in our detection of `std::nothrow` on some platforms.

I've opened up a PR with a fix [here](https://github.com/github/codeql/pull/6471). It should be on LGTM within a couple of weeks.
