### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by xiaoxinz-cisco** [github/codeql#6438]
**Description of the issue**

Hi, if we only install Codeql CLI and do not clone this repo, can we write queries and use them?

For example, `import semmle.code.cpp.commons.Printf` in query calls the library in `semmle`, which is defined in this repo, but now we want to write queries in our own repo, and use those libraries, like we use in python, e.g. `import pandas as pd`, where pandas is maintained by pandas team. 

Thanks in advance.

**Comment by alexet** [comment]
With the current release you can write your queries in a separate repository and have the libraries in this repository on the search path but you do need to download the content of this repository and add it to the codeql search path. [This repository](https://github.com/github/vscode-codeql-starter) conatins a submodule based setup for doing this.

With the beta release of packaging you can depend on the packs without cloning the repository if you use the beta version of codeql. See [here](https://codeql.github.com/docs/codeql-cli/creating-and-working-with-codeql-packs/) for the docuemntation.
