### ISSUE TITLE
Unexpected C# extractor error: Uncaught exception. The method or operation is not implemented

### ISSUE THREAD

**Issue by lovettchris** [github/codeql#6439]
**Description of the issue**

Trying to analyze a C# solution.  See https://github.com/microsoft/XmlNotepad/pull/122/checks?check_run_id=3265484537 

I get this output but no other explanation or details on how to fix it?

| Severity |                                                  Message                                                   |
|----------|------------------------------------------------------------------------------------------------------------|
| error    | Unexpected C# extractor error: Uncaught exception. The method or operation is not implemented.             |
| error    | Unexpected C# extractor error: Uncaught exception. Signature type sequence must have at least one element. |

**Comment by RasmusWL** [comment]
Thanks for reporting this @lovettchris :+1:

That output is some diagnostics information that shows that our extractor encountered a problem on the code-base. The C# team is looking into it.

**Comment by tamasvajk** [comment]
@lovettchris Thank you again for reporting this. I've merged the two linked PRs to fix the unexpected C# extractor errors.
