### ISSUE TITLE
LGTM.com - false positive - BufferedInputStream is not always closed on method exit

### ISSUE THREAD

**Issue by derklaro** [github/codeql#6445]
**Description of the false positive**

LGTM warns that an Output stream is not always closed on method exit when using:
```java
try (JarInputStream inputStream = new JarInputStream(new BufferedInputStream(moduleFile.openStream()))) {
```

I walked through the whole method refernces how the inherited AutoCloseable method is implemented on JarInputStream and can safely say, that the buffered inputstream is always closed after the method finished (I did also test it using a debugger).

[Alert URL](https://lgtm.com/projects/g/CloudNetService/CloudNet-v3/snapshot/a377b5c0ef8097d74460ef99dd1b8e5502b3f7bc/files/cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/module/DefaultModuleProvider.java#xab95e2c7da9da82a:1)

**Comment by aibaars** [comment]
I believe the JarInputStream constructor may throw an IOException in which case the object instantiation fails and the close method will not be called.
