### ISSUE TITLE
Expected alternating entity/string and string columns. [INVALID_RESULT_PATTERNS]

### ISSUE THREAD

**Issue by migraine-sudo** [github/codeql#6482]
**Description of the issue**

Hello, this problem occurs every time I use `codeql database analyze`, no matter how I modify the format of select, it will not help. I referred to this [tutorial]( https://codeql.github.com/docs/writing-codeql-queries/defining-the-results-of-a-query/ ), but it still did not solve the problem.

ERROR:
>A fatal error occurred: Could not process query metadata for ../example.ql.
Error was: Expected result pattern(s) are not present for problem query: Expected alternating entity/string and string columns. [INVALID_RESULT_PATTERNS]

my ql :

```
/**
 * @name Empty block
 * @kind problem
 * @problem.severity error
 * @precision high
 * @id cpp/example/empty-block
 */

import cpp

class MallocCall extends FunctionCall{
    MallocCall(){
        this.getTarget().hasName("malloc") and
        this.getArgument(0) instanceof AddExpr
    } 
}

from MallocCall mc
select mc.getTarget().getQualifiedName(),mc
```

` % codeql database analyze demo_database example.ql --format=csv --output=codeql.csv  --search-path=codeql-repo`

**Comment by aibaars** [comment]
Have you tried? 

```
from MallocCall mc select mc, mc.getTarget().getQualifiedName()
```

**Comment by migraine-sudo** [comment]
> Have you tried?
> 
> ```
> from MallocCall mc select mc, mc.getTarget().getQualifiedName()
> ```

Thanks for your reply, I found that my problem lies in the cache after codeql analyse. After I added --rerun, my modification finally took effect.
