### ISSUE TITLE
General issue: Overriding the isSource method does not behave as expected

### ISSUE THREAD

**Issue by bananabr** [github/codeql#6497]
**Description of the issue**

While trying to create a new DomBasedXss Javascript query, I overrode the _isSource_ method of both **DomBasedXss::HtmlInjectionConfiguration** and **DomBasedXss::JQueryHtmlOrSelectorInjectionConfiguration**. However, when the query is run, I still get results whose sources match the original source definitions.

The following query should return no results according to the new _isSource_ definition, nonetheless it still does.

```js
import javascript
import DataFlow
import semmle.javascript.security.dataflow.DomBasedXss
import DataFlow::PathGraph

SourceNode fooSource(TypeTracker t) {
  t.start() and
    exists(DataFlow::PropRead pr | pr.getPropertyName() = "foo" and pr.flowsTo(result))
  or
  exists(TypeTracker t2 |
    result = fooSource(t2).track(t2, t)
  )
}

SourceNode fooSource() {
  result = fooSource(TypeTracker::end())
}


SourceNode barSource(TypeTracker t) {
  t.start() and
    fooSource().getAMethodCall("bar").flowsTo(result)
  or
  exists(TypeTracker t2 |
    result = barSource(t2).track(t2, t)
  )
}

SourceNode barSource() {
  result = barSource(TypeTracker::end())
}

class FooBarSource extends DataFlow::Node {
  FooBarSource() {
    this = barSource()
  }
}

class FooBarHtmlInjectionConfiguration extends DomBasedXss::HtmlInjectionConfiguration{
  override predicate isSource(DataFlow::Node source) { source instanceof FooBarSource }
}

class FooBarJQueryHtmlOrSelectorInjectionConfiguration extends DomBasedXss::JQueryHtmlOrSelectorInjectionConfiguration {
  override predicate isSource(DataFlow::Node source) { source instanceof FooBarSource }
}


from DataFlow::Configuration cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where
  (
    cfg instanceof FooBarHtmlInjectionConfiguration or
    cfg instanceof FooBarJQueryHtmlOrSelectorInjectionConfiguration
  ) and
  cfg.hasFlowPath(source, sink)
select sink.getNode(), source, sink,
  sink.getNode().(DomBasedXss::Sink).getVulnerabilityKind() + " vulnerability due to $@.", source.getNode(),
  "user-provided value"
```

The query is also available at https://lgtm.com/query/8290858812151649752/ for testing.

**Comment by alexet** [comment]
`JQueryHtmlOrSelectorInjectionConfiguration` uses the two argument `isSource(DataFlow::Node source, DataFlow::FlowLabel label)` predicate that takes a label. So your override would not have overridden that case and only have overridden the base `isSource(DataFlow::Node source)` (which was already empty).

**Comment by bananabr** [comment]
Thanks!

I only looked into HtmlInjectionConfiguration and assumed JQueryHtmlOrSelectorInjectionConfiguration was the same!
