### ISSUE TITLE
Extractor does not detect compiler

### ISSUE THREAD

**Issue by CarloMara** [github/codeql#6506]
Hello Everyone,

I was trying to build a CodeQL for an embedded C codebase using `codeql database create codeql_db --language=cpp --command='bash ./build.sh'”` and soon realized that the built database contains only a small portion of the codebase.

I looked in build-tracker.log to check that all the compilers used are detected correctly and it seems that this is not the case for a one of the build steps that is using a custom built clang. I get this error message for several hundreds c file:
```
[E 12:25:02 36628] CodeQL C/C++ Extractor 1.28.0-SNAPSHOT
[E 12:25:02 36628] Current directory: REDACTED
[E 12:25:02 36628] Command: /opt/codeql/cpp/tools/linux64/extractor --mimic REDACTED/clang-9 --target=aarch64-linux-gnu -std=gnu99 -Werror -fdiagnostics-show-option -Wall -Wcast-align -Werror-implicit-function-declaration -Wextra -Wfloat-equal -Wformat-nonliteral -Wformat-security -Wformat=2 -Winit-self -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wshadow -Wstrict-prototypes -Wswitch-default -Wwrite-strings -Wno-missing-field-initializers -Wno-format-zero-length -Waggregate-return -Wredundant-decls -Wold-style-definition -Wstrict-aliasing=2 -Wundef -Wno-language-extension-token -Wno-gnu-zero-variadic-macro-arguments -O0 -ffunction-sections -fdata-sections -pipe -gdwarf-2 -mcpu=cortex-a76 -mstrict-align -mgeneral-regs-only -mcmodel=large -MD -MF REDACTED/.FILENAME.o.d -MT REDACTED/FILENAME.o -nostdinc REDACTED_INCLUDES -c REDACTED/FILENAME.c -o REDACTED/FILENAME.o
[E 12:25:02 36628] Not a compiler; exiting. Reason: did not produce a meaningful object file
[T 12:25:02 36561] Extractor terminated with exit code 0.
```
Reading https://github.com/github/codeql-cli-binaries/issues/70#issuecomment-882891679 I'm left wondering if this could be the issue I'm facing?

Any ideas on how to move forward?

Thanks again,
Carlo

**Comment by RasmusWL** [comment]
Hi @CarloMara, I'll ping the C++ team to take a look :+1:

**Comment by jbj** [comment]
To determine whether an executable is a compiler, we compile a special test program. You'll see "did not produce a meaningful object file" when a magic string from the test program doesn't seem to appear in the output file. We run your compiler with (roughly) the command line you put in the log, but instead of compiling your source file we'll compile this program:

```
extern const volatile char* marker(void) { return "\x01S\x23" "E\x45M\x67M\x89L\xab" "E\xcd!\xef"; }
```

In the resulting object file, we search for this binary string (C++ syntax):

```
"\x01S\x23""E\x45M\x67M\x89L\xab""E\xcd!\xef"
```

Can you check whether your custom cross-compiler produces an object file that contains the magic string when it compiles our test program with the command-line flags you've provided?

**Comment by CarloMara** [comment]
Hi @jbj, I saw that while analyzing the problem. The compiler does not produce an object file, because the extractor does not pass the right flags to it. 

I could easily generate a list with all the project c files (something similar to Clang `compile_commands.json`). Are you aware if there is a way of building the database without wrapping the project build system?

Thanks again,
Carlo

**Comment by jbj** [comment]
> The compiler does not produce an object file, because the extractor does not pass the right flags to it.

Can you describe what's wrong with the flags? I'd expect the extractor to pass the same flags as in the original compiler invocation it intercepted, possibly with the addition of `-fintegrated_cc1`, `-nostdinc`, and/or `-nostdsysteminc`.

> Are you aware if there is a way of building the database without wrapping the project build system?

We don't have a supported way of doing this.

**Comment by CarloMara** [comment]
Hi @jbj,

sorry for the late reply. The issues ended up begin a very complex build system that relied on a custom llvm. Adding `-nostdinc` would break the build in subtle ways, resulting in no object file begin produced. I can't go into much details, but I had to fix the build system itself and refactor some code.

Clear for the second point, I can sort of see that it would be very hard to do properly.

Thanks again for the support. Feel free to close this issue.
Carlo
