### ISSUE TITLE
cpp: improvement: Add `VariableUpdate`/`VariableAssignment `class like in java library and improve documentation for `Assignment`/`Initializer`

### ISSUE THREAD

**Issue by matan7890** [github/codeql#6510]
It seems that an `Assignment` of a `Variable` and an `Initializer` of a `Variable`  are not the same in the world of CodeQL. This was already discussed in the of the Java library in this issue [#3266](https://github.com/github/codeql/issues/3266).

Although I believe this distinction might be useful in some cases (SSA i guess?), I believe it is not a trivial idea for the common query writer, and will probably lead to bugs in the queries. When a query writer searches for a variable assignment, he probably searches for the assignments and initialization using the '=' operation (which for primitives in c/cpp is actually the same).
I believe that a clarification should be added to the documentation of `Variable.getAnAssignment`, `Assignment` and all its sub-classes or related classes. The clarification should mention that `Initializer` is not an `Assignment` with an example, and if someone also searchs for one he should probably want to add it his query.

I also understand that the Java library has the VariableUpdate/VariableAssignment classes that should behave as query-writer would believe they would. I suggest to also add these kind of classes to cpp library.
Thanks very much!

PS. this is my first issue in the project, I'm sorry if I'm missing something and would be glad to share more.

**Comment by RasmusWL** [comment]
Thanks for your input. I've forwarded this to the C++ team who will take a look soon :+1:

**Comment by MathiasVP** [comment]
Hi @matan7890,

I've opened a [PR](https://github.com/github/codeql/pull/6515) with some clarifying documentation to the classes you mentioned.

I like the idea of a common class that captures both assignments and initializers. I'll discuss this with the rest of the team soon and hear what they think of it.

**Comment by matan7890** [comment]
Thanks for the fast reply! I really appreciate how you take suggestions so seriously!
The PR looks good, I'm looking forward for the common class!!

**Comment by geoffw0** [comment]
Note the existence of `Variable.getAnAssignedValue()` for exactly this purpose - but it isn't particularly visible and I'm inclined to agree we need a better solution.

**Comment by matan7890** [comment]
Thanks for the hint! The name of the function is really confusing as "AssignedValue" indicates the returned value is an `Assignment`...

**Comment by geoffw0** [comment]
After some discussion we think that in most cases, modern users of `Variable.getAnAssignedValue()` or the hypothetical `VariableUpdate` / `VariableAssignment` classes would be better served by SSA, data flow, or other libraries that are more semantic.  We're reluctant to add library classes that might not see much use (and might even lead users astray?), though we'll be happy to reconsider this position if significant use cases arise.  We also remain keen to improve our documentation where it will help users to write CodeQL more effectively.
