### ISSUE TITLE
LGTM.com - false positive - LGTM asks for useless Base.__init__ call

### ISSUE THREAD

**Issue by howetuft** [github/codeql#6530]
When no `__init__` method is provided in a derived class, LGTM complains:
"Class `<Subclass>` may not be initialized properly as method `<Base>.__init__` is not called from its `__init__` method."

However, if `<Subclass>` has no initialization code to add to `<Base>`, explicit instantiation of `__init__`, limited to call to `super().__init__`, is redundant and discouraged. See for instance pylint warning: https://vald-phoenix.github.io/pylint-errors/plerr/errors/classes/W0235.html

Here is a practical example:
https://lgtm.com/projects/g/FreeCAD/FreeCAD-render/snapshot/dcdb4aa2b4ad3b78167cf99b3fa037c1653a5e49/files/Render/camera.py?sort=name&dir=ASC&mode=heatmap#x3dd72d0c483debb:1

**Comment by tausbn** [comment]
Thank you for your report! My best guess is that our analysis is _a bit_ too strict in what it considers to be enough to merit an `__init__` method on the subclass. In this case, the only change is that some of the attributes of the class are given different values, and it's likely that it's this discrepancy that we're picking up on (even though it shouldn't matter in this case).

As this is not related to our security queries, and as we're currently focused on improving our security analysis, we'll add this to our backlog and revisit it at a future point. If you find the alert bothersome, you can suppress it as described in the LGTM.com help.

**Comment by howetuft** [comment]
Hello,
Thank you for your answer! I agree with your analysis. I will silence the warning until you have addressed the point.
