### ISSUE TITLE
database analyze  error .  " db-cpp does not exist" 

### ISSUE THREAD

**Issue by xiaobo93** [github/codeql#6590]
For Win11 driver, we have a error about CodeQL when we Output "SARIF" file. 
Here' s what we do with this link : 
https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/static-tools-and-codeql
![image](https://user-images.githubusercontent.com/24961290/131816526-05100902-5279-405c-be88-aad3141ea0fb.png)

**Comment by criemen** [comment]
Hi,

can you upload the zipped contents of `C:\codeql-home\databases\Mydriver1\log`? That will help us debugging this issue.

**Comment by xiaobo93** [comment]
[log.zip](https://github.com/github/codeql/files/7102985/log.zip)

this log gives the same error .

**Comment by xiaobo93** [comment]
hi  : 

i use the os of en  and the problem is solved .

**Comment by criemen** [comment]
Great you figured out a workaround! You are not the only one hitting this issue, and I've raised this internally.

**Comment by ogamespec** [comment]
In the name of fuck, can you please remove language support from MSVC compiler and leave English only?

**Comment by criemen** [comment]
Your complaint notwithstanding, we've been supporting non-English locales for MSVC and gcc since 2022, so I'm gonna close this issue.
