### ISSUE TITLE
LGTM.com - false positive - This statement is unreachable

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [github/codeql#6609]
**Description of the false positive**

```go
                        err = singularity.LibraryPush(ctx, pushSpec, lc, co)
                        if err == singularity.ErrLibraryUnsigned {
                                fmt.Printf("TIP: You can push unsigned images with 'singularity push -U %s'.\n", file)
                                fmt.Printf("TIP: Learn how to sign your own containers by using 'singularity help sign'\n\n")
                                sylog.Fatalf("Unable to upload container: unable to verify signature")
                                os.Exit(3)
                        } else if err != nil {
```
I may be missing something here, but I don't see how the statement `os.Exit(3)` could be unreachable, while the rest would be reachable.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/hpcng/singularity/snapshot/de471cf6a3ba24098a4cfe759dfa959f1ee3fe58/files/cmd/internal/cli/push.go?sort=name&dir=ASC&mode=heatmap#x133b9ad5a6cec035:1

**Comment by sauyon** [comment]
It seems to me like the `Fatalf` function called above the exit is a dummy function that also calls `os.Exit`, so that like is indeed unreachable.

**Comment by DimitriPapadopoulos** [comment]
Ah, right:
> Fatalf is equivalent to Printf() followed by a call to os.Exit(1).

https://pkg.go.dev/log#Fatalf
