### ISSUE TITLE
Java: Add CodeQL class (or predicate) for Text Blocks

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#6619]
In some cases it might be useful to differentiate between regular string literals and Text Blocks (`""" ... """`).

CodeQL already seems to support Text Blocks and models them as `StringLiteral`.
Based on the [JLS](https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-3.10.6) Text Blocks are not string literals (e.g. it says "Unlike in a string literal ..."), however for simplicity it probably makes sense to keep modelling them as `StringLiteral` anyways. But it would be good to adjust the `StringLiteral` documentation then.

It would therefore be useful to either have a predicate (e.g. `StringLiteral.isTextBlock()`) or a separate class `TextBlock` which extends `StringLiteral`.
Detection is already possible by checking if `StringLiteral.getLiteral()` starts with (or ends with) `"""` (or checking if the literal contains line breaks, which is not possible for regular string literals). However, that is slightly error-prone because (despite being unlikely) the Java source code could use Unicode escapes (which are replaced during pre-processing) for the `"` and then the `getLiteral()` check would fail:
```java
// Unicode escapes for """
String s = \u0022\uuuu0022\u0022
    test
    """;
```
So the sanest solution might be to introduce a database type or predicate eventually.

What do you think?

**Comment by RasmusWL** [comment]
Thanks. This has been noted in the backlog for the Java team :+1:

**Comment by aschackmull** [comment]
I like the simplicity of a predicate on `StringLiteral` and the simple QL-level detection you mention. And even though it might not cover the unicode escape sequence version, I would like to see this matter "in the wild" before making a more complicated solution.
