### ISSUE TITLE
Question about `bqrs interpret` command

### ISSUE THREAD

**Issue by ananya-cisco** [github/codeql#6644]
**Unable to filter output using bqrs interpret**

I am running the  following command to filter out the deviations present within the sub-directory specified with `source-location-prefix` option. Can you please point out any issues with this command and achieve the intended output? 

`codeql bqrs interpret --output=ananya.sarif.json --format=sarifv1 -t=kind=problem -t=id=cpp/dead-code-function --source-archive=<absolute path of the source code git repo>  --source-location-prefix=<relative path of a sub-directory within source code git repo> DeadCodeFunction.bqrs`

Note: bqrs file contains deviations for  DeadCodeFunction.ql for the entire database/git repo.

**Comment by hmakholm** [comment]
Do you have concrete observations that your command gives you wrong/unexpected results in practice, or are you just looking for reassurance that it looks right at first sight?

In the former case, please describe what it is you expect, and how your actual output differs from your expectations.

**Comment by ananya-cisco** [comment]
I observed that the command gives me wrong results.  It doesn't filter out the deviations for the particular sub-directory and returns an almost empty json file. Output json file contains only the following, but not the expected deviations - 
```
{
  "$schema" : "http://json.schemastore.org/sarif-1.0.0",
  "version" : "1.0.0",
  "runs" : [ {
    "tool" : {
      "name" : "Semmle",
      "version" : "2.0.0"
    },
    "rules" : {
      "cpp/dead-code-function" : {
        "id" : "cpp/dead-code-function",
        "name" : "cpp/dead-code-function",
        "defaultLevel" : "warning",
        "properties" : {
          "id" : "cpp/dead-code-function",
          "kind" : "problem"
        }
      }
    }
  } ]
```

**Comment by alexet** [comment]
The source archive is specified incorrectly. You should specify the source archive from the database rather than the root of the git repo. We filter out files that don't exist in the source archive as we can't convert between location types.

**Comment by ananya-cisco** [comment]
Can you expand on `source archive from the database rather than the git repo` ? Do you mean the absolute path of the git repo from where database was generated? If you can provide an example command with path specifications, that would be very helpful.

**Comment by hmakholm** [comment]
What `bqrs analyze` wants is the source _archive_ that's a subdirectory of the _CodeQL database_, not the original file locations.

`bqrs interpret` is a very low-level command. Usually the functionality it exposes is accessed through `codeql database interpret results`, which knows how to pick the various bits of metadata out of the database and the query, instead of needing them on the command line. But that might not support your filtering needs out of the box.

**Comment by ananya-cisco** [comment]
Thank you for the detailed explanation.
I was able to generate an output file using the tip you provided above - `source archive that's a subdirectory of the CodeQL database`.
