### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by MarcDirven** [github/codeql#6669]
To reduce compile times in C++, I've (authors of Clang or GCC did) created an `EnableIf` implementation which looks as follows:

```cpp
template<bool B>
struct EnableIfImpl {};

template<>
struct EnableIfImpl<true> {
    template <class T>
    using type = T;
};

template<bool B, class T = void>
using EnableIf = typename EnableIfImpl<B>::template type<T>;
```

When you use this implementation, and use it as a return value:
```cpp
EnableIf<Condition> func() {}
```
lgtm will not recognize this return value `void` (or any return value at all), and will give the alert: 
`Function func should return a value of type EnableIf but does not return a value here`.

### Please explain briefly why you think it shouldn't be included?
Well it shouldn't because it's wrong, the return type is `void` or `T`, not `EnableIf`.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/MarcDirven/cpp-lazy/rev/pr-41b78e4b123d0ca2505b678174f1545443101d75

**Comment by RasmusWL** [comment]
Thank you, I'll get someone with more C++ expertise to take a look at this:+1:

**Comment by MathiasVP** [comment]
Hi @MarcDirven,

Thanks for the report. I've opened a PR with a fix: https://github.com/github/codeql/pull/6687. Once that is merged, it should reach LGTM within a couple of weeks.
