### ISSUE TITLE
LGTM.com - false positive - Modification of dictionary returned by locals()

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [github/codeql#6674]
**Description of the false positive**

In the [following snippet](https://github.com/nilearn/nilearn/blob/ac1a934/nilearn/plotting/cm.py#L221-L222), `locals()` operates at the module level, therefore `locals()` is identical to `globals()`:
```python
# Save colormaps in the scope of the module
locals().update(_cmap_d)
```
Therefore, the above code does work.

That said, I will change `locals()` → `globals()` since they are identical here, to make the intent clear (nilearn/nilearn#2958).

See also [`locals()`](https://docs.python.org/3/library/functions.html#locals) documentation:
>Update and return a dictionary representing the current local symbol table. Free variables are returned by [`locals()`](https://docs.python.org/3/library/functions.html#locals) when it is called in function blocks, but not in class blocks. Note that at the module level, [`locals()`](https://docs.python.org/3/library/functions.html#locals) and [`globals()`](https://docs.python.org/3/library/functions.html#globals) are the same dictionary.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/nilearn/nilearn/snapshot/d520eb8468e57b591fe97798f038a56ab134679b/files/nilearn/plotting/cm.py?sort=name&dir=ASC&mode=heatmap#x63244eecb7d9ea77:1

**Comment by RasmusWL** [comment]
Thanks. This is not security related, so doesn't really fit our current focus. However, it was very easy to fix, so I've done so in https://github.com/github/codeql/pull/6688
