### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [github/codeql#6750]
After fixing a typo in https://github.com/github/codeql/blob/main/docs/codeql/ql-language-reference/ql-language-specification.rst#summary-of-syntax from `alias := qldoc?` to `alias ::= qldoc?` we can copy and paste the complete grammar on  https://www.bottlecaps.de/rr/ui in the tab Edit Grammar then switching to the tab View Diagram.

**Comment by aibaars** [comment]
Thanks for reporting the typo! The rail-road diagram looks really useful, thanks for sharing.
