### ISSUE TITLE
LGTM.com - false positive - Comparison is always false because denom >= 1.

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [github/codeql#6752]
**Description of the false positive**

It's true that denom is initialized to 1:
```c
    npy_uint64 num = 1, denom = 1, tmp, gcd;
```
and subsequently multiplied by positive integers::
```c
                denom *= 400*7;
```
```c
                denom *= 400*12*7;
```
```c
                denom *= 400*12*7;
```
```c
                denom *= 400*12;
```
I can see why LGTM reports that `demon` cannot be but larger than 1. However, what happens in case of an **overflow**? That's precisely what the code tries to detect here:
```c
    /* If something overflowed, make both num and denom 0 */
    if (denom == 0 || num == 0) {
```

Here is a simple example:
```c
#include <stdio.h>
#include <inttypes.h>

int main() {
	uint64_t denom = UINT64_MAX/2+1;
	printf("denom = %"PRIu64"\n", denom);
	denom *= 2;
	printf("denom = %"PRIu64"\n", denom);
}
```
which outputs:
```
denom = 9223372036854775808
denom = 0
```

Perhaps LGTM is smarter than that and know this cannot happen in this case, for example for a reason involving considerations such as 18446744073709551616 cannot be divided by 400, 12 or 7. However, I suspect that's not the case.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/numpy/numpy/snapshot/6fd377657ac7fcc9d244e2d1ebae26e70f60db51/files/numpy/core/src/multiarray/datetime.c?sort=name&dir=ASC&mode=heatmap#x2f5c881720f6cdf2:1

**Comment by aeisenberg** [comment]
Thanks for reporting this false positive. Like #6746, this report does not relate to a security query, we will put this on our backlog and prioritize it if we get enough reports of the same underlying issue in other projects. If you think that your report is related to our security analysis, please clarify that in a comment. Either way, we'll let you know here as soon as it's fixed!

**Comment by testt11114** [comment]
> **وصف الإيجابي الكاذب**
> 
> صحيح أن الفئة تمت تهيئتها إلى 1:
> 
> ```c
>     npy_uint64 num = 1 ، denom = 1 ، tmp ، gcd ؛
> ```
> 
> وبعد ذلك مضروبة في أعداد صحيحة موجبة:
> 
> ```c
>                 المذهب * = 400 * 7 ؛
> ```
> 
>  ```c
>                 المذهب * = 400 * 12 * 7 ؛
> ```
> 
>  ```c
>                 المذهب * = 400 * 12 * 7 ؛
> ```
> 
>  ```c
>                 المذهب * = 400 * 12 ؛
> ```
> 
> يمكنني معرفة سبب تقارير LGTM التي `demon`لا يمكن إلا أن تكون أكبر من 1. ومع ذلك ، ماذا يحدث في حالة حدوث **فائض** ؟ هذا هو بالضبط ما يحاول الكود اكتشافه هنا:
> 
> ```c
>     / * إذا فاض شيء ما ، اجعل كلاً من num والمسمى 0 * /
>      if (المسمى == 0 || num == 0 ) {
> ```
> 
> اليك مثال بسيط:
> 
> ```c
> # include  < stdio.h > 
> # include  < inttypes.h >
> 
> int  main () {
> 	 uint64_t denom = UINT64_MAX / 2 + 1 ؛
> 	printf ( " denom =٪ " PRIu64 " \ n " ، denom) ؛
> 	المذهب * = 2 ؛
> 	printf ( " denom =٪ " PRIu64 " \ n " ، denom) ؛
> }
> ```
> 
> أي مخرجات:
> 
> ```
> denom = 9223372036854775808
> denom = 0
> ```
> 
> ربما تكون LGTM أذكى من ذلك وتعرف أن هذا لا يمكن أن يحدث في هذه الحالة ، على سبيل المثال لسبب يتضمن اعتبارات مثل 18446744073709551616 لا يمكن تقسيمه على 400 أو 12 أو 7. ومع ذلك ، أظن أن الأمر ليس كذلك.
> 
> **عنوان URL للتنبيه على صفحة المشروع على LGTM.com**
> 
> https://lgtm.com/projects/g/numpy/numpy/snapshot/6fd377657ac7fcc9d244e2d1ebae26e70f60db51/files/numpy/core/src/multiarray/datetime.c?sort=name&dir=ASC&mode=heatmap#x2f5c881720f6cdf2:1

ok

**Comment by DimitriPapadopoulos** [comment]
I agree `denom == 0` is **not** a general check for overflow. The comment is wrong. From what I gather, the intent is to silently overlook overflows. However, in the case of an overflow, there is a very small chance `denom == 0`, and the intent is to ensure that `denom` (actually `*out_denom`) and `num` (actually `*out_num`) are both `0` if either of them is `0`.

**Comment by DimitriPapadopoulos** [comment]
Indeed `npy_uint64` is a 64-bit integer. I might not be an [`unsigned long`](https://github.com/numpy/numpy/blob/02f18a88c15f98c5879bb90e5a29463f08d262ec/numpy/core/include/numpy/npy_common.h#L549), but an [`unsigned long long`](https://github.com/numpy/numpy/blob/02f18a88c15f98c5879bb90e5a29463f08d262ec/numpy/core/include/numpy/npy_common.h#L625) or an [`unsigned int`](https://github.com/numpy/numpy/blob/02f18a88c15f98c5879bb90e5a29463f08d262ec/numpy/core/include/numpy/npy_common.h#L715) depending on the platform, but it is supposed to be a 64-bit integer and should therefore be large enough to to hold `1 * 400*12*7`.

My wrong. I don't know why, but I was under the impression that the whole multiplication was happening in a loop, which is certainly not the case.

That said, I'm still curious whether my snippet would still raise the LGTM.com warning - one could argue it shouldn't:
```c
#include <stdio.h>
#include <inttypes.h>

int main() {
	uint64_t denom = UINT64_MAX/2+1;
	printf("denom = %"PRIu64"\n", denom);
	denom *= 2;
	printf("denom = %"PRIu64"\n", denom);
	if (denom == 0)
		printf("WHAT?!?");
}
```
I'll test this (or a more complicated one) in a dedicated repo.

**Comment by MathiasVP** [comment]
Thanks for digging into this. As the alert turned out to be a true positive I'll close this issue, and we'll keep an eye out for similar issues related to your latest snippet.

**Comment by DimitriPapadopoulos** [comment]
I've created a small example:
https://lgtm.com/projects/g/DimitriPapadopoulos/codeql-tests/snapshot/bd5805ded4c7da0fa4d9d19b2a52d3665946aaef/files/src/wrapping.c#x37756bc502b4933f:1

**Comment by MathiasVP** [comment]
Thanks for testing this. I'll create an internal issue for it. :)
