### ISSUE TITLE
could not resolve XXX

### ISSUE THREAD

**Issue by xsser** [github/codeql#6768]
![图片](https://user-images.githubusercontent.com/1850771/135091495-e8bd5d73-b60d-4334-84cf-df363b312edf.png)

I met this problem ,and tried what i could .
But i still cannot fix it.
Why would it happen??

It works fine in MacOS but not windows.
So, how to make it  under windows?
Thanks

**Comment by MathiasVP** [comment]
Hi @xsser,

Did this suddenly start happening, or is this the first time you run it under Windows?

Can you try setting up the CodeQL extension using the [vscode-codeql-starter](https://github.com/github/vscode-codeql-starter) repo?

**Comment by xsser** [comment]
> Hi @xsser,
> 
> Did this suddenly start happening, or is this the first time you run it under Windows?
> 
> Can you try setting up the CodeQL extension using the [vscode-codeql-starter](https://github.com/github/vscode-codeql-starter) repo?

This happened in my first time using codeql under windows.
And i have used the vscode-codeql-starter , but did not work 


![图片](https://user-images.githubusercontent.com/1850771/135095922-46fd4798-9dde-4191-80dc-1b73203e8fa8.png)

**Comment by xsser** [comment]
> Does the CodeQL Extension Log report any details on what goes wrong? I'm not exactly sure how to find it on Windows, but on a Mac, you can find it on by clicking on "View" -> "Output" and selecting the "CodeQL Extension Log" in the dropdown menu: <img alt="Screenshot 2021-09-28 at 15 36 11" width="1146" src="https://user-images.githubusercontent.com/4527323/135097502-ef063a38-7406-4dd1-9c1c-95428561cd4e.png">



A fatal error occurred: Error reading D:\Users\xxxx\Desktop\codeql-starter\vscode-codeql-starter\codeql-custom-queries-cpp\qlpack.yml: Unrecognized field "dependencies" (class com.semmle.frontend.packs.QlPack), not marked as ignorable (8 known properties: "tests", "dbscheme", "extractor", "upgrades", "version", "libraryPathDependencies", "name", "suites"])
 at [Source: (StringReader); line: 7, column: 3] (through reference chain: com.semmle.frontend.packs.QlPack["dependencies"])
[2021-09-28 21:21:25] Exception caught at top level: Error reading D:\Users\xxxx\Desktop\codeql-starter\vscode-codeql-starter\codeql-custom-queries-cpp\qlpack.yml: Unrecognized field "dependencies" (class com.semmle.frontend.packs.QlPack), not marked as ignorable (8 known properties: "tests", "dbscheme", "extractor", "upgrades", "version", "libraryPathDependencies", "name", "suites"])
                       at [Source: (StringReader); line: 7, column: 3] (through reference chain: com.semmle.frontend.packs.QlPack["dependencies"])
                      com.semmle.frontend.packs.QlPackResolver.lambda$readQlpackJson$2(QlPackResolver.java:183)
                      java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
                      com.semmle.frontend.packs.QlPackResolver.readQlpackJson(QlPackResolver.java:176)
                      com.semmle.frontend.packs.QlPackResolver.findContainingPack(QlPackResolver.java:128)
                      com.semmle.frontend.packs.QlPackResolver.findContainingPackWithExtractor(QlPackResolver.java:150)
                      com.semmle.cli2.resolve.ResolveTestsCommand.definitelyATest(ResolveTestsCommand.java:114)
                      com.semmle.cli2.resolve.ResolveTestsCommand.foundTestFile(ResolveTestsCommand.java:125)
                      com.semmle.cli2.resolve.ResolveTestsCommand.access$200(ResolveTestsCommand.java:40)
                      com.semmle.cli2.resolve.ResolveTestsCommand$1.visitFile(ResolveTestsCommand.java:71)
                      com.semmle.cli2.resolve.ResolveTestsCommand$1.visitFile(ResolveTestsCommand.java:59)
                      java.base/java.nio.file.Files.walkFileTree(Unknown Source)
                      java.base/java.nio.file.Files.walkFileTree(Unknown Source)
                      com.semmle.cli2.resolve.ResolveTestsCommand.executeJSON(ResolveTestsCommand.java:59)
                      com.semmle.cli2.resolve.ResolveTestsCommand.executeJSON(ResolveTestsCommand.java:33)
                      com.semmle.cli2.picocli.SimpleJsonSubcommand.executeInsistingOnJSON(SimpleJsonSubcommand.java:101)
                      com.semmle.cli2.picocli.SimpleJsonSubcommand.executeSubcommand(SimpleJsonSubcommand.java:77)
                      com.semmle.cli2.picocli.SubcommandCommon.executeWithParent(SubcommandCommon.java:414)
                      com.semmle.cli2.execute.CliServerCommand.lambda$executeSubcommand$0(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:201)
                      com.semmle.cli2.execute.CliServerCommand.executeSubcommand(CliServerCommand.java:67)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:430)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:201)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:209)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:91)

**Comment by xsser** [comment]
Done!
The reason why it would happen:
1.Incompatible version codeql-cli and codeql-vscode and codeql-rules

**Comment by MathiasVP** [comment]
Great! I'm happy you got it working :)

**Comment by h0ld1rs** [comment]
Sorry, I wonder which version will fix this bug
