### ISSUE TITLE
LGTM.com - false positive Pattern always matches.

### ISSUE THREAD

**Issue by jmarolf** [github/codeql#6786]
**Description of the false positive**

It appears the default case for pattern matches are not considered in this rule.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/dotnet/roslyn/snapshot/c9e0dd1ec0e440897388bbd55184fb53a555e3a4/files/src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs?sort=name&dir=ASC&mode=heatmap#x7bf442d9c11933e9:1

**Comment by MathiasVP** [comment]
Hi @jmarolf,

Thanks for posting this issue as well. I'll forward it to the C# team. Like https://github.com/github/codeql/issues/6785, since this isn't a security query it'll be put on our backlog and prioritized when we get similar issues.

We'll let you know as soon as it's fixed!

**Comment by hvitved** [comment]
Thanks for the report. Will be fixed by https://github.com/github/codeql/pull/6800.
