### ISSUE TITLE
LGTM.com - false positive This assignment to _ is useless, since its value is never read.

### ISSUE THREAD

**Issue by jmarolf** [github/codeql#6788]
**Description of the false positive**

It appears that values which are read as part of participating in a using statement are not considered by this rule today.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/dotnet/roslyn/snapshot/c9e0dd1ec0e440897388bbd55184fb53a555e3a4/files/src/Workspaces/Core/Portable/FindSymbols/FindReferences/FindReferencesSearchEngine.UnidirectionalSymbolSet.cs?sort=name&dir=ASC&mode=heatmap#x3fd4a3ae68c51e00:1

**Comment by MathiasVP** [comment]
Hi @jmarolf,

Thanks for opening another issue. Please see my response to the other [false positive](https://github.com/github/codeql/issues/6785) you submitted on this query.

**Comment by hvitved** [comment]
I agree that this is a false positive. Here is a fix: https://github.com/github/codeql/pull/6799.
