### ISSUE TITLE
is not compatible with the QL library (General issue)

### ISSUE THREAD

**Issue by a-elk** [github/codeql#6798]
can't successfully launch database analyse command.
i tried to launch it like this : 

 codeql database analyze test $HOME/codeql-home/codeql-repo/cpp/ql/examples/snippets/function_call.ql  --format=csv --output=c_test.csv

i got this error : is not compatible with the QL library ../codeql-home/codeql-repo/cpp/ql/examples/snippets/function_call.ql uses.
The database may be too new for the QL libraries the query is using; try upgrading them.

**Comment by hvitved** [comment]
Hi

I suggest making sure that you are using the [latest CodeQL CLI](https://github.com/github/codeql-cli-binaries), and if you are running queries from a checkout of https://github.com/github/codeql, then make sure to have checked out a version that compatible (e.g. https://github.com/github/codeql/tree/codeql-cli/v2.6.2).

**Comment by a-elk** [comment]
hi, thank you were right, but now i have this error : 

Error was: No query kind specified [NO_KIND_SPECIFIED]

**Comment by hvitved** [comment]
Great. I'll close this issue then.
