### ISSUE TITLE
Error when trying to analyze Go db

### ISSUE THREAD

**Issue by jshuping-ns1** [github/codeql#6956]
I can analyze a CPP db just fine, but when I try to analyze a Go db, I get this error:
```
+ codeql database analyze /codeql-results --output=/tmp/codeql.sarif --format=sarif-latest --sarif-category=unknown -j0
Running queries.
ERROR: Referenced pack 'codeql/suite-helpers' not found. (/codeql/codeql-go/ql/src/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /codeql/codeql-go/ql/src
```

It is similar but not identical to this issue: https://github.com/github/codeql/issues/4815#issuecomment-781179069
I'm new to this tool so maybe something simple. Here is how I installed codeql:
```
wget -q -O/tmp/codeql.zip https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip \
    && mkdir /codeql \
    && cd /codeql \
    && unzip /tmp/codeql.zip \
    && git clone https://github.com/github/codeql.git codeql-repo \
    && git clone https://github.com/github/codeql-go.git codeql-go
```

And here is how I'm running it:
```
# codeql database create /codeql-results --language=go --command="go build -v ."
Initializing database at /codeql-results.
Running build command: [go, build, -v, .]
Finalizing database at /codeql-results.
[2021-10-22 20:46:55] [build-stderr] Scanning for files in /platform/golang/xfrgenerate...
Successfully created database at /codeql-results.

# time codeql database analyze /codeql-results --output=/tmp/codeql.sarif --format=sarif-latest -j0
Running queries.
ERROR: Referenced pack 'codeql/suite-helpers' not found. (/codeql/codeql-go/ql/src/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /codeql/codeql-go/ql/src
```

Any ideas?

**Comment by disconnect3d** [comment]
The 2.7.1 version still has this problem (cc: @hmakholm)

**Comment by disconnect3d** [comment]
To elaborate, I have `~/.codeql/{codeql,codeql-repo,codeql-go}` directories and I always had the `/home/dc/.codeql/codeql` path in `PATH`. However, since some time I need to add a `--additional-packs /home/dc/.codeql/codeql-repo/` to all `codqel analyze ...` invocations with Go.

**Comment by aeisenberg** [comment]
Can you display the contents of the qlpack.yml where your queries are located?

If you are using packages, please make sure to add a `dependencies` block and remove any `libraryPathDependencies` block.

Should look something like this:

```
dependencies:
  codeql/go-all: ^0.0.2
```

**Comment by disconnect3d** [comment]
@aeisenberg this also applies to the `go-lgtm-full.qls` query pack that is within the `codeql-go` repo and it indeed has the `dependencies` block and does not have `libraryPathDependencies` blocks. Its full content:
```
name: codeql/go-queries
version: 0.0.2
suites: codeql-suites
extractor: go
defaultSuiteFile: codeql-suites/go-code-scanning.qls
dependencies:
  codeql/go-all: "*"
  codeql/suite-helpers: "*"
```
