### ISSUE TITLE
False Positive in Javascript ZipSlip 

### ISSUE THREAD

**Issue by Naman-ntc** [github/codeql#6990]
I believe the following code is not vulnerable to zip slip vulnerability since instead of detecting whether `..` is present is using `indexOf` method, the code uses regex matches. I suspect the presence of regex makes dataflow analysis not possible causing the false positive?
(I have been using the command-line tool with security suite and not the lgtm databases)

``` 
const fs = require('fs');
const unzip = require('unzip');

fs.createReadStream('archive.zip')
  .pipe(unzip.Parse())
  .on('entry', entry => {
    const fileName = entry.path;
    // GOOD: ensures the path is safe to write to.
    //if (fileName.indexOf('..') == -1) {
    if (fileName.match(/\.\./)) {
        entry.pipe(fs.createWriteStream(fileName));
    }
    else {
      console.log('skipping bad path', fileName);
    }
  });
```

**Comment by asgerf** [comment]
@Naman-ntc Thanks for the follow-up, that regexp was in fact not covered by the original PR, but should be covered by the second PR (linked above).
