### ISSUE TITLE
Incorrect message when using `\G` in CodeQL beta support for Ruby

### ISSUE THREAD

**Issue by nobu** [github/codeql#7001]
Thank you for the support for Ruby!

https://github.com/ruby/ruby/security/code-scanning/40?query=ref%3Arefs%2Fheads%2Fmaster
> This part of the regular expression may cause exponential backtracking on strings starting with 'G/' and containing many repetitions of '\\.'.

The line is:
```ruby
        val.scan(%r[\G[\s;]*(/(?:\\.|[^/])*/)?([sy])(\\?\W)((?:(?!\3)(?:\\.|.))*)\3((?:(?!\3)(?:\\.|.))*)\3([gi]*)]) do
```

Here, we use `\G` which anchors the beginning of the string or the end of the previous matching, but not a bare `G`.

**Comment by sj** [comment]
Looks like this was fixed in https://github.com/ruby/ruby/pull/5056. Nice spot :slightly_smiling_face:

**Comment by nickrolfe** [comment]
https://github.com/github/codeql/pull/7120 fixed the issue with mis-parsing `\G`.
