### ISSUE TITLE
CodeQL Language Feature: Trailing comma at end of List

### ISSUE THREAD

**Issue by JLLeitschuh** [github/codeql#7006]
This is a quality of life/syntactic sugar feature request:

It would be awesome if CodeQL, similar to Python, Java and C supported creating lists where the last element can have a trailing comma. For example:
```ql
fruit = [
  "apple",
  "kiwi",
  "grape",
]
```

Rationale is basically the same as in other languages: The main advantages are that it makes multi-line lists easier to edit and that it reduces clutter in diffs.
This is especially helpful when writing `SummaryModelCsv` by hand and you need to copy/paste then modify a previously written line, then run unit tests. It gets annoying have to constantly remove, then add a new , at the end of the last line you add.

**Comment by adityasharad** [comment]
See also: https://github.com/github/codeql-cli-binaries/issues/76.

**Comment by hmakholm** [comment]
Release 2.7.1 of the CLI, which contains this language extension, is now out.
