### ISSUE TITLE
CodeQL C/C++: Perform taint analysis on pointers to structure

### ISSUE THREAD

**Issue by BATTZION** [github/codeql#7053]
I am using codeql to perform taint analysis on the following code. A risky execution path is as follows: read data from the network, and then use the read data as a parameter of the system function. My purpose is to find all such paths, but i can only find the level1 path.

``` c
// buffer is tainted
// after copy, cli_msg->msg is tainted too
strncpy(cli_msg->msg, buffer, sizeof(cli_msg->msg) - 1);
// but when transferring structure pointers across functions
// cli_msg->msg taint disappeared
system_msg(cli_msg);
```
Detail: 
``` c
struct CliMsg {
    int fd;
    char msg[64];
};

void system_msg(struct CliMsg *cli_msg) {
    system(cli_msg->msg);
}

// level1
void handle_msg_level1(int client, char *buffer) {
    char msg[256];
    strncpy(msg, buffer, sizeof(msg));
    system(msg);
}

// level2
void handle_msg_level3(int client, char *buffer) {
    struct CliMsg *cli_msg = (struct CliMsg*)malloc(sizeof(struct CliMsg));
    cli_msg->fd = client;
    memset(cli_msg, 0, sizeof(cli_msg));
    strncpy(cli_msg->msg, buffer, sizeof(cli_msg->msg) - 1);
    system_msg(cli_msg);
    free(cli_msg);
}
// level3
void handle_msg_level2(int client, char *buffer) {
    struct CliMsg *cli_msg = (struct CliMsg*)malloc(sizeof(struct CliMsg));
    cli_msg->fd = client;
    memset(cli_msg, 0, sizeof(cli_msg));
    strncpy(cli_msg->msg, buffer, sizeof(cli_msg->msg) - 1);
    pthread_t handle_client_t;
    pthread_create(&handle_client_t, NULL, (void *)system_msg, cli_msg);
    pthread_join(handle_client_t, NULL);
    free(cli_msg);
}

void handle_client(int client) {
    char buffer[256];
    memset(buffer, 0, sizeof(buffer));
    recv(client, buffer, sizeof(buffer), 0);
    int level = buffer[0] - '1';
    switch (level) {
        case 1:
            handle_msg_level1(client, buffer + 1);
            break;
        case 2:
            handle_msg_level2(client, buffer + 1);
            break;
        case 3:
            break;
            handle_msg_level3(client, buffer + 1);
    }
}
```
my CodeQL query statement is as follows:

``` 
import cpp
import semmle.code.cpp.dataflow.TaintTracking
import DataFlow::PathGraph

class ReceivedBuffer extends Expr {
    ReceivedBuffer() { exists(FunctionCall caller | caller.getTarget().getName() = "recv" | caller.getArgument(1) = this)}
}

class SystemCmd extends Expr {
    SystemCmd() { exists(FunctionCall caller | caller.getTarget().getName() = "system" | caller.getArgument(0) = this)}
}

class Config extends TaintTracking::Configuration {
    Config() { this = "NetworkToSystem" }
  
    override predicate isSource(DataFlow::Node source) {
        source.asDefiningArgument() instanceof ReceivedBuffer
    }

    override predicate isSink(DataFlow::Node sink) {
        sink.asExpr() instanceof SystemCmd
    }
}

from Config cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where cfg.hasFlowPath(source, sink)
select source, sink, "recv flows to system" 
```
how can i improve the query statement so that I can find the path of level2 and level3 ？

**Comment by tausbn** [comment]
Thank you for your question!

This _looks_ like something the analysis should be able to handle (though I'm not terribly familiar with how things work for C/C++), so I'm going to forward it to the CodeQL C/C++ team.

Incidentally, your `level2/3` comments seems to be out of sync with the function names. Judging by the structure of the code, I assume that `handle_msg_level3` should really be called `handle_msg_level2` and vice versa.

**Comment by MathiasVP** [comment]
Hi @BATTZION,

I think we're not finding the flow in the level3 case is because of a mistake in your switch case:
```cpp
switch (level) {
        case 1:
            handle_msg_level1(client, buffer + 1);
            break;
        case 2:
            handle_msg_level2(client, buffer + 1);
            break;
        case 3:
            break;
            handle_msg_level3(client, buffer + 1);
    }
```

notice the break _before_ the call to `handle_msg_level3`: that call is actually dead code.

Now, the reason we're not finding the flow to `handle_msg_level2` is more complicated. Basically, we haven't yet modeled flow through `pthread_create` calls, so it's currently difficult to make this work exactly as one might hope. You can _almost_ do it yourself by adding an additional taint step to your configuration like this:
```codeql
class Config extends TaintTracking::Configuration {
  // ...

  override predicate isAdditionalTaintStep(DataFlow::Node node1, DataFlow::Node node2) {
    exists(Call call, FunctionAccess facc |
      call.getTarget().hasName("pthread_create") and
      node1.asExpr() = call.getArgument(3) and
      facc = call.getArgument(2) and
      node2.asParameter() = facc.getTarget().getParameter(0)
    )
  }
}
```
which says: "there is a step from the argument of `pthread_create` to the parameter of the callback function".

However, that doesn't actually work in this case because we want to transfer flow that's currently inside a field, and when that is the case you cannot provide a step using `isAdditionalTaintStep`. So, to side-step this issue we provide a couple more `isAdditinoalTaintStep` cases that allow us to track the flow without taking fields into account:

```codeql
class Config extends TaintTracking::Configuration {
  // ...

  override predicate isAdditionalTaintStep(DataFlow::Node node1, DataFlow::Node node2) {
    // as before
    exists(Call call, FunctionAccess facc |
      call.getTarget().hasName("pthread_create") and
      node1.asExpr() = call.getArgument(3) and
      facc = call.getArgument(2) and
      node2.asParameter() = facc.getTarget().getParameter(0)
    )
    or
    // flow `b` to `a` in `strncpy(a.f, b, n)`
    exists(Call call |
      call.getTarget().hasName("strncpy") and
      node1.asExpr() = call.getArgument(1) and
      node2.asPartialDefinition() = call.getArgument(0).(FieldAccess).getQualifier()
    )
    or
    // flow from `a` to the argument of `system` in `system(a.f)`
    exists(Call call, FieldAccess fa |
      call.getTarget().hasName("system") and
      fa = call.getArgument(0) and
      node1.asExpr() = fa.getQualifier() and
      node2.asExpr() = fa
    )
  }
}
```
This will give you flow in all the cases. However, the last two cases are horrible to include in general as it allows flow between unrelated fields of a struct. So I would not add such a flow step in general.

It's a bit unfortunate that this is necessary. Hopefully, once we model `pthread_create` properly you can just delete all these cases and everything should be handled automatically.

**Comment by BATTZION** [comment]
> Thank you for your question!
> 
> This _looks_ like something the analysis should be able to handle (though I'm not terribly familiar with how things work for C/C++), so I'm going to forward it to the CodeQL C/C++ team.
> 
> Incidentally, your `level2/3` comments seems to be out of sync with the function names. Judging by the structure of the code, I assume that `handle_msg_level3` should really be called `handle_msg_level2` and vice versa.

Hi @tausbn,

Thank you for your correction and help. In order for others to see MathiasVP’s answer not to be confused, let’s not correct this error. Thanks Again!

**Comment by BATTZION** [comment]
> Hi @BATTZION,
> 
> I think we're not finding the flow in the level3 case is because of a mistake in your switch case:
> 
> ```c++
> switch (level) {
>         case 1:
>             handle_msg_level1(client, buffer + 1);
>             break;
>         case 2:
>             handle_msg_level2(client, buffer + 1);
>             break;
>         case 3:
>             break;
>             handle_msg_level3(client, buffer + 1);
>     }
> ```
> 
> notice the break _before_ the call to `handle_msg_level3`: that call is actually dead code.
> 
> Now, the reason we're not finding the flow to `handle_msg_level2` is more complicated. Basically, we haven't yet modeled flow through `pthread_create` calls, so it's currently difficult to make this work exactly as one might hope. You can _almost_ do it yourself by adding an additional taint step to your configuration like this:
> 
> ```ql
> class Config extends TaintTracking::Configuration {
>   // ...
> 
>   override predicate isAdditionalTaintStep(DataFlow::Node node1, DataFlow::Node node2) {
>     exists(Call call, FunctionAccess facc |
>       call.getTarget().hasName("pthread_create") and
>       node1.asExpr() = call.getArgument(3) and
>       facc = call.getArgument(2) and
>       node2.asParameter() = facc.getTarget().getParameter(0)
>     )
>   }
> }
> ```
> 
> which says: "there is a step from the argument of `pthread_create` to the parameter of the callback function".
> 
> However, that doesn't actually work in this case because we want to transfer flow that's currently inside a field, and when that is the case you cannot provide a step using `isAdditionalTaintStep`. So, to side-step this issue we provide a couple more `isAdditinoalTaintStep` cases that allow us to track the flow without taking fields into account:
> 
> ```ql
> class Config extends TaintTracking::Configuration {
>   // ...
> 
>   override predicate isAdditionalTaintStep(DataFlow::Node node1, DataFlow::Node node2) {
>     // as before
>     exists(Call call, FunctionAccess facc |
>       call.getTarget().hasName("pthread_create") and
>       node1.asExpr() = call.getArgument(3) and
>       facc = call.getArgument(2) and
>       node2.asParameter() = facc.getTarget().getParameter(0)
>     )
>     or
>     // flow `b` to `a` in `strncpy(a.f, b, n)`
>     exists(Call call |
>       call.getTarget().hasName("strncpy") and
>       node1.asExpr() = call.getArgument(1) and
>       node2.asPartialDefinition() = call.getArgument(0).(FieldAccess).getQualifier()
>     )
>     or
>     // flow from `a` to the argument of `system` in `system(a.f)`
>     exists(Call call, FieldAccess fa |
>       call.getTarget().hasName("system") and
>       fa = call.getArgument(0) and
>       node1.asExpr() = fa.getQualifier() and
>       node2.asExpr() = fa
>     )
>   }
> }
> ```
> 
> This will give you flow in all the cases. However, the last two cases are horrible to include in general as it allows flow between unrelated fields of a struct. So I would not add such a flow step in general.
> 
> It's a bit unfortunate that this is necessary. Hopefully, once we model `pthread_create` properly you can just delete all these cases and everything should be handled automatically.

Hi @MathiasVP,

Thank you for your answer, and sorry for my mistake. 

This code is a demo I extracted from a real project. Levels 1-3 represent the three difficulties I think I will encounter when using CodeQL for taint analysis:

1. The taint flows directly through the pointer;
2. The taint flows into the field of the structure, and then flows with the pointer to the structure；
3. There are implicit function calls in the path of taint flow, such as pthread_create;

Through your answer, I learned how to use the isAdditionalTaintStep function to handle these cases.

Thanks again for your detailed explanation！
