### ISSUE TITLE
[Update Request] support `dotnet 6` for C#

### ISSUE THREAD

**Issue by taha-ghadirian** [github/codeql#7086]
Hello, Microsoft released new `Dotnet 6` version last night, and it is now LTS version of dotnet. 
Can you upgrade CodeQl to last dotnet version for C# programmers?

https://github.com/github/codeql/issues/7086#tasklist-block-e512d681-976f-4ba1-8fa9-cc04baacb709

**Comment by hvitved** [comment]
Hi

Until [Roslyn](https://www.nuget.org/packages/Microsoft.CodeAnalysis) supports C# 10, we will not be able to support C# 10. Once it is released, we will work on supporting C# 10, but in the meantime it should still mostly work.

**Comment by taha-ghadirian** [comment]
> Hi
> 
> Until [Roslyn](https://www.nuget.org/packages/Microsoft.CodeAnalysis) supports C# 10, we will not be able to support C# 10. Once it is released, we will work on supporting C# 10, but in the meantime it should still mostly work.

Hello dear @hvitved, Roslyn version `4.0` supports `C# 10`, `Dotnet 6` and included in `Visual Studio 2022 version 17.0` by default. 

![image](https://user-images.githubusercontent.com/36773254/141053936-177b0161-7641-4750-b06e-ceb108a97587.png)
![image](https://user-images.githubusercontent.com/36773254/141053959-5593565d-9f3a-4bf0-bc97-aabe72d9e582.png)

**Comment by hvitved** [comment]
When I checked yesterday, the [Roslyn nuget package](https://www.nuget.org/packages/Microsoft.CodeAnalysis) was still at version 3.10.0, but it appears to have been upgraded to version 4.0.1 overnight. We will look into upgrading to the latest version soon.

**Comment by taha-ghadirian** [comment]
Thanks for your answer 😀❤️
We're waiting for update 😃✌️

**Comment by tenhobi** [comment]
Hello, after 80 days from confirmation that `Roslyn` supports `C# 10`, can we get some idea when this feature is available? Thanks a lot for your work! 🙏

**Comment by hvitved** [comment]
Hi @tenhobi . We are actively working on C# 10 support right now (see some of @michaelnebel's [PRs](https://github.com/github/codeql/pulls?q=is%3Apr+author%3Amichaelnebel+) for progress). We are hoping to have full C# 10 support within a couple of months.

**Comment by SupinePandora43** [comment]
https://github.com/SupinePandora43/UltralightNet/runs/5068194629?check_suite_focus=true

**Comment by taha-ghadirian** [comment]
CodeQl is now supporting `.Net6`. Closed as completed.
