### ISSUE TITLE
Javascript: Size of generated databases - only YAML files, no code

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/codeql#7093]
**Description of the issue**
I have a massive source directory that consists **only** of YAML files.
The YAML files are Github Actions workflow files.
I want to analyze the YAML files using codeql-javascript in combination with [the existing library](https://github.com/github/codeql/blob/main/javascript/ql/src/experimental/semmle/javascript/Actions.qll) for Github Actions.
The source directory is 246 MB big, the resulting database 719 MB.
The file sizes of the biggest relations:
```
245565792 locations_default.rel
238375968 yaml.rel
93369240 yaml_scalars.rel
79458848 yaml_locations.rel
39965040 extraction_time.rel
```

I can understand that storage is cheap these days, but **if there is maybe an easy way to reduce the size a little bit, I would appreciate that.**
The YAML files are Github Actions so I guess there are many duplicate strings or string fragments. Maybe it would be possible to deduplicate or share some parts?

**Comment by tausbn** [comment]
Could you perhaps exclude that directory from extraction? (Or are you querying the contents of these YAML files somehow?)

Also, what language are you extracting?

**Comment by intrigus-lgtm** [comment]
Sorry, my description has been unclear.

I have downloaded many Github Actions workflows from different repositories.
These workflows are YAML files which I'm extracting using the javascript extractor.
Instead of creating a seperate database for each and every repository I just created a database from the folder that contains all the repositories.

The source directory is 246 MB big, but the database is **three** times as big.

My question is:
Is there maybe a simple change for you that would reduce the size of the database?

**Comment by esbena** [comment]
Our best advice is to try and zip the database. That would reduce the size on disk, but it would obviously need to be unzipped before you could run any queries on it.

The database size increase is expected, and is generally not considered a problem. At the database level, there is a a rather small conceptual difference between "yaml" and "code", so I expect that you would see a similar kind of increase for a 246MB JavaScript "code" database.

**Comment by intrigus-lgtm** [comment]
Thanks for taking the time to answer my question!

I've now written a program to deduplicate the workflows from the different repositories.
This helps with my problem.
While I've hoped that there would be a way to reduce the overhead, I consider this issue closed.

**Comment by ardnitsuy** [comment]
Hi @intrigus-lgtm @intrigus, 
I have the same use case with you. I want to scan only YAML files. But the default configuration of CodeQL and just setting the language as `javascript` apparently didn't work.

Would you help me understanding how to configure the workflow YAML such that it can scan YAML files?

**Comment by intrigus-lgtm** [comment]
Hi @ardnitsuy 
just adding a file with the name `nano.js` (or any other name)
and the content `true` should make CodeQL recognize the files as Javascript and begin extracting YAML files.

If CodeQL only sees YAML files, it will (rightfully) not detect them as Javascript and stop the extraction.
So to make this work, we have to create a dummy Javascript file. Only then will CodeQL also extract YAML files.

How this helps.
