### ISSUE TITLE
possible incompleteness in Dataflow Analysis 

### ISSUE THREAD

**Issue by fdujwc** [github/codeql#7128]
I tested the following code using CodeQL Java v2.5.7, and it is reported as Positive(FP) of Reflected XSS.
```java
    @ResponseBody
    @GetMapping(value = "/callback", consumes = MediaType.ALL_VALUE, produces = MediaType.TEXT_PLAIN_VALUE)
    public String checkSignature(WxMiniProgramCheckSignRequest signParam) {
        return wxMiniProgramOpenService.checkSignature(signParam);
    }
```
I tried to debug using PartialPathGraph, and the dataflow analysis did step into the function **checkSignature** , which does not contain a dataflow from the tainted param to return-value.
Using frameworks like springboot, the word "return" is more like a function call(dataflow node). But in CodeQL it is considered as a statement, which are not included in dataflow analysis for dataflow nodes.
In the case above, my guess is that the dataflow analysis only checked the possible flow from source to **the node after return statement**, but ignored the possibility that the taint cannot propagate from **the node after return statement** to **return** (in which case **the node after return statement** does not contain a dataflow from the tainted param to return-value).
Am I misunderstanding something here?

**Comment by MathiasVP** [comment]
Hi @fdujwc,

Thanks for the issue. I'm not quite sure what you mean by:
> In the case above, my guess is that the dataflow analysis only checked the possible flow from source to the node after return statement, but ignored the possibility that the taint cannot propagate from the node after return statement to return (in which case the node after return statement does not contain a dataflow from the tainted param to return-value).
Am I misunderstanding something here?

Can you add an example piece of code that illustrates what you mean?
