### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by neptunao** [github/codeql#7167]
Hello! 

Want to ask if there is any plans to support F# language. I use it on my work and pet projects, and I'm interested mostly in security scanning, the same way as CodeQL and Coverity do for C#. 

Thanks!

**Comment by hvitved** [comment]
Hi

F# is unfortunately not on [the roadmap](https://github.com/orgs/github/projects/4247).

**Comment by neptunao** [comment]
Is there any plans to consider it in future roadmap revisions?

**Comment by hvitved** [comment]
Not to my knowledge.

**Comment by krzysztof-madej** [comment]
Where can I make feature request for this?

**Comment by hvitved** [comment]
@coadaflorin can you help answer this request?

**Comment by coadaflorin** [comment]
@krzysztof-madej the best place to make a request is on the [Code Scanning community](https://github.com/orgs/community/discussions/categories/code-security?discussions_q=is%3Aopen+category%3A%22Code+Security%22) if one doesn't exist.
