### ISSUE TITLE
`scanning results / CodeQL` check hanging on PRs in transferred repo

### ISSUE THREAD

**Issue by ldennington** [github/codeql#7176]
My team just [transferred one of our repositories](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) into a new org. While our [CodeQL workflow](https://github.com/GitCredentialManager/git-credential-manager/actions/workflows/codeql-analysis.yml) seems to be working as expected, the `scanning results / CodeQL` PR check has been hanging indefinitely (see [this PR](https://github.com/GitCredentialManager/git-credential-manager/pull/541) for an example). Do y'all have any suggestions on how to get this check running again to unblock our PRs?

**Comment by hvitved** [comment]
Hi

I have forwarded this issue internally, and the team will get back to you.

**Comment by hvitved** [comment]
This should now be resolved.
