### ISSUE TITLE
Codeql not running on all PRs

### ISSUE THREAD

**Issue by amanagr** [github/codeql#7190]
On the PRs of https://github.com/zulip/zulip, codeql tests are in a hanging state. No error message, it just shows `Started 8h 33m 23s ago`.

See https://github.com/zulip/zulip/pull/20278/checks?check_run_id=4261083837 for example. Any idea what maybe causing them? Tips to debug? or Is this an error from codeql side?

**Comment by simon-engledew** [comment]
👋 Sorry about this! This is caused by a bad deploy we are currently reverting. (Incident here: https://github.com/github/code-scanning/issues/4760).

**Comment by intrigus-lgtm** [comment]
> :wave:  Sorry about this! This is caused by a bad deploy we are currently reverting. (See also https://github.com/github/code-scanning/issues/4757)

The link is private unless it is meant for other Github staff.

**Comment by amanagr** [comment]
I figured.

**Comment by simon-engledew** [comment]
Whoops! 😊 Yes, quite right! Too many tabs open. 🙇

**Comment by simon-engledew** [comment]
Everything should be back to normal now. 🙇‍♂️

**Comment by amanagr** [comment]
Thanks!
