### ISSUE TITLE
Query compilation fails for ruby and go with error  'codeql/suite-helpers' not found.

### ISSUE THREAD

**Issue by jacobmsft** [github/codeql#7193]
**I follow the codeql getting started guide to clone the repos locally, and then I try to compile the queries. For ruby and go, it gives me error below. For the rest of the languages, the compilation works fine.**

/usr/local/codeql-home#> codeql query compile --threads=0  /usr/local/codeql-home/codeql-go-repo/ql/src/codeql-suites/*.qls
ERROR: Referenced pack 'codeql/suite-helpers' not found. (/usr/local/codeql-home/codeql-go-repo/ql/src/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /usr/local/codeql-home/codeql-go-repo/ql/src

/usr/local/codeql-home#> codeql query compile --threads=0 /usr/local/codeql-home/codeql-repo/ruby/ql/src/codeql-suites/*.qls
ERROR: Referenced pack 'codeql/suite-helpers' not found. (/usr/local/codeql-home/codeql-repo/ruby/ql/src/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /usr/local/codeql-home/codeql-repo/ruby/ql/src

the paths are set properly and qlpack resolution works just fine:

/usr/local/codeql-home#> codeql resolve qlpacks 
codeql-csharp-tests (/usr/local/codeql-home/codeql-repo/csharp/ql/test)
codeql/cpp-all (/usr/local/codeql-home/codeql-repo/cpp/ql/lib)
codeql/cpp-examples (/usr/local/codeql-home/codeql-repo/cpp/ql/examples)
codeql/cpp-queries (/usr/local/codeql-home/codeql-repo/cpp/ql/src)
codeql/cpp-tests (/usr/local/codeql-home/codeql-repo/cpp/ql/test)
codeql/cpp-tests-cwe-190-tainted (/usr/local/codeql-home/codeql-repo/cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted)
codeql/cpp-upgrades (/usr/local/codeql-home/codeql-repo/cpp/upgrades)
codeql/csharp-all (/usr/local/codeql-home/codeql-repo/csharp/ql/lib)
codeql/csharp-examples (/usr/local/codeql-home/codeql-repo/csharp/ql/examples)
codeql/csharp-queries (/usr/local/codeql-home/codeql-repo/csharp/ql/src)
codeql/csharp-upgrades (/usr/local/codeql-home/codeql-repo/csharp/upgrades)
codeql/go-all (/usr/local/codeql-home/codeql-go-repo/ql/lib)
codeql/go-examples (/usr/local/codeql-home/codeql-go-repo/ql/examples)
codeql/go-queries (/usr/local/codeql-home/codeql-go-repo/ql/src)
codeql/go-tests (/usr/local/codeql-home/codeql-go-repo/ql/test)
codeql/go-upgrades (/usr/local/codeql-home/codeql-go-repo/upgrades)
codeql/java-all (/usr/local/codeql-home/codeql-repo/java/ql/lib)
codeql/java-examples (/usr/local/codeql-home/codeql-repo/java/ql/examples)
codeql/java-queries (/usr/local/codeql-home/codeql-repo/java/ql/src)
codeql/java-tests (/usr/local/codeql-home/codeql-repo/java/ql/test)
codeql/java-upgrades (/usr/local/codeql-home/codeql-repo/java/upgrades)
codeql/javascript-all (/usr/local/codeql-home/codeql-repo/javascript/ql/lib)
codeql/javascript-examples (/usr/local/codeql-home/codeql-repo/javascript/ql/examples)
codeql/javascript-experimental-atm-lib (/usr/local/codeql-home/codeql-repo/javascript/ql/experimental/adaptivethreatmodeling/lib)
codeql/javascript-experimental-atm-queries (/usr/local/codeql-home/codeql-repo/javascript/ql/experimental/adaptivethreatmodeling/src)
codeql/javascript-queries (/usr/local/codeql-home/codeql-repo/javascript/ql/src)
codeql/javascript-tests (/usr/local/codeql-home/codeql-repo/javascript/ql/test)
codeql/javascript-upgrades (/usr/local/codeql-home/codeql-repo/javascript/upgrades)
codeql/python-all (/usr/local/codeql-home/codeql-repo/python/ql/lib)
codeql/python-examples (/usr/local/codeql-home/codeql-repo/python/ql/examples)
codeql/python-queries (/usr/local/codeql-home/codeql-repo/python/ql/src)
codeql/python-tests (/usr/local/codeql-home/codeql-repo/python/ql/test)
codeql/python-upgrades (/usr/local/codeql-home/codeql-repo/python/upgrades)
codeql/ruby-all (/usr/local/codeql-home/codeql-repo/ruby/ql/lib)
codeql/ruby-consistency-queries (/usr/local/codeql-home/codeql-repo/ruby/ql/consistency-queries)
codeql/ruby-examples (/usr/local/codeql-home/codeql-repo/ruby/ql/examples)
codeql/ruby-queries (/usr/local/codeql-home/codeql-repo/ruby/ql/src)
codeql/ruby-tests (/usr/local/codeql-home/codeql-repo/ruby/ql/test)
codeql/suite-helpers (/usr/local/codeql-home/codeql-repo/misc/suite-helpers)
legacy-libraries-cpp (/usr/local/codeql-home/codeql-repo/misc/legacy-support/cpp)
legacy-libraries-csharp (/usr/local/codeql-home/codeql-repo/misc/legacy-support/csharp)
legacy-libraries-go (/usr/local/codeql-home/codeql-go-repo/ql/config/legacy-support)
legacy-libraries-java (/usr/local/codeql-home/codeql-repo/misc/legacy-support/java)
legacy-libraries-javascript (/usr/local/codeql-home/codeql-repo/misc/legacy-support/javascript)
legacy-libraries-python (/usr/local/codeql-home/codeql-repo/misc/legacy-support/python)
legacy-upgrades (/usr/local/codeql-home/codeql/legacy-upgrades)

**Comment by MathiasVP** [comment]
Hi @jacobmsft,

Thank you for opening an issue! We're currently looking into the problem. As a workaround, can you check if it works if you add an `--additional-packs` argument like this:
```bash
/usr/local/codeql-home#> codeql query compile --threads=0 /usr/local/codeql-home/codeql-go-repo/ql/src/codeql-suites/*.qls --additional-packs .
```

**Comment by jacobmsft** [comment]
> Hi @jacobmsft,
> 
> Thank you for opening an issue! We're currently looking into the problem. As a workaround for `Ruby`, can you check if it works if you add an `--additional-packs` argument like this:
> 
> ```shell
> /usr/local/codeql-home#> codeql query compile --threads=0 /usr/local/codeql-home/codeql-go-repo/ql/src/codeql-suites/*.qls --additional-packs .
> ```
> 
> For `go`, make sure you've run the `scripts/install-deps.sh` script as specified in the [README](https://github.com/github/codeql-go#installation) of the [codeql-go](https://github.com/github/codeql-go) repository.

Yes, that worked for both Ruby and Go...Thanks!

**Comment by MathiasVP** [comment]
Great! Sounds like the issue is resolved. Closing this issue. Feel free to open another one if you hit any other issues :)

**Comment by jacobmsft** [comment]
> Great! Sounds like the issue is resolved. Closing this issue. Feel free to open another one if you hit any other issues :)

The workaround works, but its still a workaround...we shouldn't be specifying the --additional-packs for compiling.

**Comment by MathiasVP** [comment]
> The workaround works, but its still a workaround...we shouldn't be specifying the --additional-packs for compiling.

I agree. We're working on an actual solution. In fact, we have a solution, but we're still discussing which release to ship it in.

**Comment by jacobmsft** [comment]
> > The workaround works, but its still a workaround...we shouldn't be specifying the --additional-packs for compiling.
> 
> I agree. We're working on an actual solution. In fact, we _probably_ have a solution, but we're still discussing which release to ship it in.

That's great, thanks MathaisVP!

**Comment by GleasonK** [comment]
Having the same issue, workaround of adding `--additional-packs <codeql-home>` worked as well. 

Running Windows 11 using Linux on WSL if relevant.
