### ISSUE TITLE
CodeQL not detecting unsafe html constructing

### ISSUE THREAD

**Issue by Naman-ntc** [github/codeql#7205]
**Description of the issue**

For the [examples in CWE-079](https://github.com/github/codeql/tree/main/javascript/ql/src/Security/CWE-079/examples), on running the [UnsafeHtmlConstruction.ql](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-079/UnsafeHtmlConstruction.ql), codeql is not detecting any vulnerabilities.

Specifically, in the examples folder running the following commands does not return anything. 

```
codeql database create ./db --language=javascript --overwrite -j 0
codeql query run -d=db ../UnsafeHtmlConstruction.ql -j 0
```

Is this expected?

**Comment by asgerf** [comment]
Hi @Naman-ntc,

This is expected. The purpose of those files is to be included as snippets in a `qhelp` file. They sometimes lack the context to be flagged by a query on their own.

For example, the file you mention isn't flagged because there isn't a `package.json` file that would mark it as being exported from a library. If you were to add this to a `package.json` file in the folder, it would be flagged
```json
{
    "name": "testpackage",
    "main": "unsafe-html-construction.js"
}
```

**Comment by Naman-ntc** [comment]
Oh I see, that's quite very interesting! 
I just assumed codeql would only take `js, jsx, tsx, ts` files into account on specifying javascript language. Can you point out other extensions (similar to `json`) which can also be relevant. (I have been cleaning up all other file extensions in repositories so far!)

**Comment by asgerf** [comment]
There's a doc listing them [here](https://github.com/github/codeql/blob/main/docs/codeql/support/reusables/versions-compilers.rst) although for JS I can see it's slightly out of date, as `".hbs", ".ejs", ".njk"` are also supported now.

**Comment by Naman-ntc** [comment]
That seems very helpful. Why doesn't it list `ts` and `tsx`?

**Comment by asgerf** [comment]
Those are listed under TypeScript

**Comment by Naman-ntc** [comment]
Yep sorry, just saw that! Closing this. Thanks alot
