### ISSUE TITLE
Unable to create a database for a Javascript project

### ISSUE THREAD

**Issue by Shivam60** [github/codeql#7213]
**Description of the issue**

I am using codeQl CLI to create a database and analyze it
I am using codeql cli version to create a database of the extension [Links para Serviços Públicos em Portugal](https://microsoftedge.microsoft.com/addons/detail/links-para-servi%C3%A7os-p%C3%BAbli/fmndcafgeidojkdcdgkghglleppadapj). Downloads link [here](https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&os=win&arch=x64&os_arch=x86_64&nacl_arch=x86-64&prod=chromiumcrx&prodchannel=&prodversion=96.0.1054.29&lang=en-US&acceptformat=crx3&x=id%3Dfmndcafgeidojkdcdgkghglleppadapj%26installsource%3Dondemand%26uc) I extracted the link using fiddler.

I first unzip the package using 7Zip and then use codeql cli to create a database out of it.
`codeql database create %databaseOutputPath% --source-root=%sourcePath% --language=javascript --threads=0`

Each time i run i get this following error.

`
[2021-11-23 12:14:37] [build-stdout] Done extracting E:\codeql-home\codeql\javascript\tools\data\externs\web\w3c_rtc.js (291 ms)
[2021-11-23 12:14:37] [build-stdout] Done extracting E:\codeql-home\codeql\javascript\tools\data\externs\web\webgl.js (250 ms)
[2021-11-23 12:14:37] [build-stderr] Only found JavaScript or TypeScript files that were empty or contained syntax errors.
[2021-11-23 12:14:37] [ERROR] Spawned process exited abnormally (code -1; tried to run: [E:\codeql-home\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, E:\codeql-home\codeql\javascript\tools\autobuild.cmd])
A fatal error occurred: Exit status -1 from command: [E:\codeql-home\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, E:\codeql-home\codeql\javascript\tools\autobuild.cmd]
`

My codeQl CLI version is 2.6.0

`
CodeQL command-line toolchain release 2.6.0.
Copyright (C) 2019-2021 GitHub, Inc.
Unpacked in: E:\codeql-home\codeql
   Analysis results depend critically on separately distributed query and
   extractor modules. To list modules that are visible to the toolchain,
   use 'codeql resolve qlpacks' and 'codeql resolve languages'.
`

Why is CodeQl not able to create a db here and what can I do to mitigate this ?

**Comment by Shivam60** [comment]
This is what the log file is showing me in terms of exception
`
[2021-11-23 12:20:04] Exception caught at top level: Exit status -1 from command: [E:\codeql-home\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, E:\codeql-home\codeql\javascript\tools\autobuild.cmd]
                      com.semmle.cli2.database.DatabaseProcessCommandCommon.executeSubcommand(DatabaseProcessCommandCommon.java:176)
                      com.semmle.cli2.database.TraceCommandCommand.executeSubcommand(TraceCommandCommand.java:86)
                      com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:110)
                      com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:160)
                      com.semmle.cli2.database.CreateCommand.executeSubcommand(CreateCommand.java:147)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:456)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:214)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:98)
`

**Comment by Shivam60** [comment]
found the same error while using codeQl CLI 2.7.2

**Comment by mbaluda** [comment]
Hi @Shivam60 
CodeQL does not extract files with the .min.js extension as scanning minified files is not considered a normal use case for the tool. You can however rename the files and ideally run them through a code formatter.
I refer you to this issue for further clarification:
https://github.com/github/codeql-cli-binaries/issues/75

**Comment by Shivam60** [comment]
Unfortunately this did not work.

I added the variable `` as Environment variable 
![image](https://user-images.githubusercontent.com/13963817/144197101-338dc5bd-7bdd-4fc1-9bbd-0b54d2accc31.png)


I also added the yml file in source directory of the project that I am trying to convert
![image](https://user-images.githubusercontent.com/13963817/144197289-7d4ae84e-fd83-42b3-ae42-6e0a48c7a911.png)


Please let me know if i did any step incorrectly and what else I can do here onwards

**Comment by mbaluda** [comment]
Dear @Shivam60 ,
that pattern will only add sources from the current folder.
I tried with the following:
`LGTM_INDEX_FILTERS="include:**/*.min.js"`
and I managed to create a database

**Comment by FaiqueAli** [comment]
in which file should we add this variable for Makefile on windows?
I am using CodeQL CLI..
