### ISSUE TITLE
LGTM.com - false positive - undeclared functions from the Python C API

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [github/codeql#7214]
**Description of the false positive**

Some functions of the Python C API, including Unicode functions introduced by the implementation of [PEP 393](https://www.python.org/dev/peps/pep-0393) in Python 3.3, are reported to be implicitly declared, despite `#include <Python.h>`:
* [`PyUnicode_FromKindAndData`](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_FromKindAndData)
* [`PyUnicode_AsUCS4Copy`](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUCS4Copy)
* [`PyUnicode_GET_LENGTH`](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_GET_LENGTH)
* [`PyModule_Create`](https://docs.python.org/3/c-api/module.html#c.PyModule_Create)

Strangely enough, other functions of the Python C API are **not** reported undeclared, for example:
* [`PyUnicode_AsUTF8String`](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUTF8String)
* [`PyObject_CallFunction`](https://docs.python.org/3/c-api/call.html#c.PyObject_CallFunction)
* [`PyArg_ParseTupleAndKeywords`](https://docs.python.org/3/c-api/arg.html#c.PyArg_ParseTupleAndKeywords)
* [`PyErr_SetString`](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_SetString)

Most of the functions that are **not** reported undeclared are part of the [Stable ABI](https://docs.python.org/3/c-api/stable.html#stable). Those that **are** reported undeclared are not part of the [Stable ABI](https://docs.python.org/3/c-api/stable.html#stable).

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/jamesturk/jellyfish/snapshot/33c4a9bfde303b44b8b943f9919ad38b05a02d72/files/cjellyfish/jellyfishmodule.c?sort=name&dir=ASC&mode=heatmap#x8906dd19aaa8e471:1

https://lgtm.com/projects/g/jamesturk/jellyfish/snapshot/33c4a9bfde303b44b8b943f9919ad38b05a02d72/files/cjellyfish/jellyfishmodule.c?sort=name&dir=ASC&mode=heatmap#xd27fd0646bed32aa:1

https://lgtm.com/projects/g/jamesturk/jellyfish/snapshot/33c4a9bfde303b44b8b943f9919ad38b05a02d72/files/cjellyfish/jellyfishmodule.c?sort=name&dir=ASC&mode=heatmap#xb7381a65a2fbab8a:1

https://lgtm.com/projects/g/jamesturk/jellyfish/snapshot/33c4a9bfde303b44b8b943f9919ad38b05a02d72/files/cjellyfish/jellyfishmodule.c?sort=name&dir=ASC&mode=heatmap#x8f5448c81822df00:1

**Comment by MathiasVP** [comment]
Hi @DimitriPapadopoulos,

Thanks for your issue. As this isn't a security query I'm not sure when we'll have time to fix this issue.

However, I took a quick look at [the first link on LGTM](https://lgtm.com/projects/g/jamesturk/jellyfish/snapshot/33c4a9bfde303b44b8b943f9919ad38b05a02d72/files/cjellyfish/jellyfishmodule.c?sort=name&dir=ASC&mode=heatmap#x8906dd19aaa8e471:1), and I can't seem to find a declaration in `Python.h` of `PyUnicode_FromKindAndData`. Can you help me find it so I can try to diagnose what's gone wrong?

**Comment by DimitriPapadopoulos** [comment]
Mmmh... It should be part of `Python.h` according to the [Python documentation](https://docs.python.org/3/c-api/unicode.html), at least starting with Python 3.3. 

Perhaps that's a documentation issue:
* How do I find the version of Python run by the LGTM.com?
* How do I specify that version? I have read [Customizing the python_setup: step](https://lgtm.com/help/lgtm/python-extraction#customizing-python-setup). It remains unclear whether I can just specify Python 2 vs. Python 3 or specify a a more precise version. The documentation does not explicit the valid values of `version`.

**Comment by DimitriPapadopoulos** [comment]
`PyUnicode_FromKindAndData` lives in [`Include/cpython/unicodeobject.h`](https://github.com/python/cpython/blob/main/Include/cpython/unicodeobject.h):
```c
/* Create a new string from a buffer of Py_UCS1, Py_UCS2 or Py_UCS4 characters.
   Scan the string to find the maximum character. */
PyAPI_FUNC(PyObject*) PyUnicode_FromKindAndData(
    int kind,
    const void *buffer,
    Py_ssize_t size);
```
https://github.com/python/cpython/blob/2c047f6/Include/cpython/unicodeobject.h#L543-L548

which is included by [`Include/unicodeobject.h`](https://github.com/python/cpython/blob/main/Include/unicodeobject.h):
```c
#ifndef Py_LIMITED_API
#  define Py_CPYTHON_UNICODEOBJECT_H
#  include "cpython/unicodeobject.h"
#  undef Py_CPYTHON_UNICODEOBJECT_H
#endif
```
https://github.com/python/cpython/blob/2c047f6/Include/unicodeobject.h#L1044-1048

which is included by [`Include/Python.h`](https://github.com/python/cpython/blob/main/Include/Python.h):
```c
#include "unicodeobject.h"
```
https://github.com/python/cpython/blob/2c047f6/Include/Python.h#L49

**Comment by MathiasVP** [comment]
Thanks a lot for that include path! It looks like the `Python.h` header in the database on LGTM comes from a Python 2.7 include path, which explains those alerts. I'll investigate if it's possible to convince LGTM to use Python 3.3 for the project.

**Comment by MathiasVP** [comment]
The fact that Python 2.7 is being used is also very much visible from the extraction log file https://lgtm.com/projects/g/jamesturk/jellyfish/logs/languages/lang:cpp:
```
[2021-11-17 17:08:49] [build-stderr] cjellyfish/jellyfishmodule.c: In function ‘unicode_from_ucs4’:
[2021-11-17 17:08:49] [build-stderr] cjellyfish/jellyfishmodule.c:26:12: warning: implicit declaration of function ‘PyUnicode_FromKindAndData’; did you mean ‘PyUnicode_FromOrdinal’? [-Wimplicit-function-declaration]
[2021-11-17 17:08:49] [build-stderr]    26 |     return PyUnicode_FromKindAndData(PyUnicode_4BYTE_KIND, (void*)str, len);
[2021-11-17 17:08:49] [build-stderr]       |            ^~~~~~~~~~~~~~~~~~~~~~~~~
[2021-11-17 17:08:49] [build-stderr]       |            PyUnicode_FromOrdinal
...
***************************************************************************
[2021-11-17 17:08:50] [build-stdout] WARNING: C extension could not be compiled, falling back to pure Python.
[2021-11-17 17:08:50] [build-stdout] ***************************************************************************
```

**Comment by DimitriPapadopoulos** [comment]
> The fact that Python 2.7 is being used is also very much visible from the extraction log file

Indeed:
```
[2021-11-17 17:08:48] [build-stdout] x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-8kFkPd/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCJELLYFISH_PYTHON=1 -I/usr/include/python2.7 -c cjellyfish/jellyfishmodule.c -o build/temp.linux-x86_64-2.7/cjellyfish/jellyfishmodule.o
```

Yet [jellyfish](https://github.com/jamesturk/jellyfish/) explicitly depends on Python 3:
```python
        python_requires=">3.5",
```
https://github.com/jamesturk/jellyfish/blob/e1be2f9/setup.py#L113
```python
            "Programming Language :: Python :: 3.6",
            "Programming Language :: Python :: 3.7",
            "Programming Language :: Python :: 3.8",
            "Programming Language :: Python :: 3.9",
```
https://github.com/jamesturk/jellyfish/blob/e1be2f9/setup.py#L126-L130

According to [Preparing for extraction ](https://lgtm.com/help/lgtm/python-extraction#python_setup-step) LGTM is expected to select Python 3:
> By default, the python_setup step uses the following strategy:
> 1. Look for a `setup.py` file and run it to determine the dependencies and/or versions required.

**Comment by MathiasVP** [comment]
Thanks for the detailed explanation @DimitriPapadopoulos.

We have added an analysis-configuration file to the project which changes the Python version from 2.7 to 3.7. Hopefully, that means the alerts are now gone.
