### ISSUE TITLE
[Python] How to detect `write()` with __buildins__.open ?

### ISSUE THREAD

**Issue by yad1d1** [github/codeql#7278]
Using `API::builtin("open").getACall()` can quickly query the call status of the `open` method in the built-in function, but how can I query the corresponding `write` method? 🤣

For example:
```py
a=open("1.txt","w")
a.write("something")
```

**Comment by tausbn** [comment]
If you do `API::builtin("open").getReturn()`, you get an API graph node representing the _result_ of calling the `open` builtin. With this API graph node, you can continue to use all of the usual methods to access member methods, calls, etc. Thus, `API::builtin("open").getReturn().getMember("write").getACall()` will give you the call on the second line you list above.

**Comment by yad1d1** [comment]
Great, solve the problem perfectly, thanks！！
