### ISSUE TITLE
[Feature Request] Support Trusted Types in JavaScript queries

### ISSUE THREAD

**Issue by tosmolka** [github/codeql#7336]
Hello, I did not find much info about this elsewhere so asking here. 

It would be amazing if CodeQL had support for [Trusted Types](https://w3c.github.io/webappsec-trusted-types/dist/spec/) in JavaScript language and we could use CodeQL to query DOM injections sinks and catch violations early. Similar to what [tsec](https://github.com/google/tsec) is doing in their [rules](https://github.com/google/tsec/tree/main/src/rules/dom_security). 

I know many sinks (ScriptContentSink, ScriptUrlSink, EvalJavaScriptSink, DomSink, HtmlParserSink, TemplateTagInScriptSink, ...) are already covered to some extend. But it seems we might be missing some sinks (I did not check extensively, maybe SharedWorker constructor, React<iframe srcdoc>, HTMLBaseElement.href, ...). 

And I could not find anything related to trusted types (TrustedHTML, TrustedScript, TrustedScriptURL) or other relevant methods (TrustedTypePolicyFactory.createPolicy, TrustedTypePolicy.createHTML, TrustedTypePolicy.createScript, TrustedTypePolicy.createScriptURL). 

Now, without this support, it is challenging to continue scanning large and complex JavaScript applications that adopted Trusted Types. CodeQL does not understand "guard" methods and detected issues are not as precise as they could be. 

Thanks.

**Comment by RasmusWL** [comment]
Hi @tosmolka, thanks for your suggestion. I've forwarded this to the JS team :+1:

**Comment by asgerf** [comment]
Hi @tosmolka,

I've opened https://github.com/github/codeql/pull/7408 which adds sinks at the points where a value is boxed in a trusted type wrapper (i.e. the return value from the policy callback)

> CodeQL does not understand "guard" methods and detected issues are not as precise as they could be.

Without more information I can't really help with this. If you're seeing false positives due to a missed sanitizer guard, feel free to open an issue.

**Comment by asgerf** [comment]
Closing as https://github.com/github/codeql/pull/7408 has been merged
