### ISSUE TITLE
YAML support for languages other than Javascript (like Python)

### ISSUE THREAD

**Issue by kjcolley7** [github/codeql#7345]
The Javascript extractor has the ability to extract YAML documents into a CodeQL database, and the Javascript library code has QL classes for working with YAML documents. It would be really nice if this functionality were available from other languages like Python.

For some context, I have been working on static analysis for an internal project that is written in Python and makes heavy use of YAML files, even to define control flow and data flow. To get a complete picture of what the codebase does, it is not sufficient to look just at the Python code or the YAML files in isolation. Info from both must be combined to know how it works.

Because of this, I went ahead and created my own custom language for CodeQL called Python+YAML, where it uses the Python extractor and the Javascript extractor to produce trap files for a custom dbscheme. Then, the QLPack for the language is the core Python language support coupled with a modified version of YAML.qll from the Javascript libraries. This has been working perfectly for me for the past couple months.

Obviously, my solution here is very hacky, and it would be much better if there were official support in CodeQL for importing YAML documents into databases for other languages besides Javascript.

**Comment by RasmusWL** [comment]
Thanks for raising this. Sounds rather impressive to me with the scarce documentation we have of dbschemes :blush: 

We do have a shared XML library, and files can be added manually to a DB with `codeql database index-files`, so it would be possible to do something similar for YAML. I can't make any promises on when or if we're going to do this, but I'll definitely put it up for discussion :+1:

**Comment by kjcolley7** [comment]
I'm effectively using the `index-files` subcommand to run the Javascript extractor with the right arguments to only extract YAMLs. In a previous discussion with another CodeQL engineer, they mentioned they were considering "composable dbschemes", which may help with this. It would also be cool if multi-language databases allowed you to access more than one of the language "slices" of the DB in a single query. That would probably require some extra namespacinf feature for QL at least though so probably isn't the easiest solution for this issue.

**Comment by retanoj** [comment]
hello  @kjcolley7 
could you share your "Python+YAML" semmlecode.dbscheme and modified lib file content?

I just copy "YAML" segment in semmlecode.dbscheme from javascript to java, some error occues. And I did not solve it :(
