### ISSUE TITLE
LGTM.com - false positive `cpp/comparison-of-identical-expressions`

### ISSUE THREAD

**Issue by bblanchon** [github/codeql#7385]
**Description of the false positive**

I'm using a meta-programming trick that reduces the number of overloads by sorting the arguments to a function like so:

```c++
template <typename TString1, typename TString2>
typename std::enable_if<TString1::typeSortKey <= TString2::typeSortKey, int>::type
stringCompare(TString1 s1, TString2 s2) {
  // IMPLEMENTATION
}

template <typename TString1, typename TString2>
typename std::enable_if<(TString1::typeSortKey > TString2::typeSortKey), int>::type
stringCompare(TString1 s1, TString2 s2) {
  return -stringCompare(s2, s1);
}
```

As you can see, this code uses the same implementation even if the arguments  are reversed.

The alert "Self Comparison" triggers on the expression `TString1::typeSortKey <= TString2::typeSortKey`.
Indeed, it can be a self-comparison if `TString1` and `TString2` are the same type, but in the general case, it's not.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/bblanchon/ArduinoJson/snapshot/6d857fd73270f4ee1e03f5e9aa5c1e7d1ee0f179/files/src/ArduinoJson/Strings/StringAdapters.hpp?sort=name&dir=ASC&mode=heatmap#x262128796e29999c:1

**Comment by MathiasVP** [comment]
Hi @bblanchon,

Thanks for the report. Indeed, this looks like a false positive. I've opened a PR with a fix here: https://github.com/github/codeql/pull/7395.

**Comment by MathiasVP** [comment]
The PR has been merged 🎉. The fix will reach LGTM within the next couple of weeks :)

**Comment by bblanchon** [comment]
Awesome. Thank Mathias!

**Comment by MathiasVP** [comment]
This is unfortunately expected, yes. We update LGTM roughly 14 days, but the last update before Christmas had to be canceled due to technical issues. I expect the warning to disappear within the next couple of days, though.

**Comment by MathiasVP** [comment]
We've just updated LGTM and the false positive is now gone.

**Comment by bblanchon** [comment]
Awesome! ArduinoJson is now A+ 😍
