### ISSUE TITLE
General issue C/C++: help of understanding the division of a predicate

### ISSUE THREAD

**Issue by f0rm2l1n** [github/codeql#7404]
**Description of the issue**

In the implementation of Steensgaard's algorithm in the CodeQL library
(link: https://github.com/github/codeql/blob/main/cpp/ql/lib/semmle/code/cpp/pointsto/PointsTo.qll#L640)

It is quite obscure that there are divisions of the predicates
`flowEntity/2, pointerEntity/2, compoundEdgeEntity/5, locationEntity/1`

I have gone through the documentation but failed to find what does this means. Can anyone help with explaining this?
Thanks a lot

**Comment by intrigus-lgtm** [comment]
Is the higher-order `collapse` primitive documented anywhere?
I could not find any reference to this primitive and the documentation on higher-order relations is also pretty much non-existent, besides 4 mentions here:
https://codeql.github.com/docs/ql-language-reference/ql-language-specification/

**Comment by hmakholm** [comment]
Indeed `collapse` is undocumented. I believe the only reason it (and the library module that uses it) still exists after our own queries have switched to a more flexible points-to analysis written in QL itself, is that some enterprise customers from the Semmle days had some custom-developed queries that used it and we didn't want to pull the rug from under those.

It is also true that the higher-order primitives _in general_ are, let's say, less than ideally documented. We'll have to do something about that sooner or later.
