### ISSUE TITLE
Unknown kind "Table" in query meta-data 

### ISSUE THREAD

**Issue by Kadam-Tushar** [github/codeql#7453]
In [this](https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/CWE-020/ExternalAPIsUsedWithUntrustedData.ql) example query provided. 
I guess the table is `UNSUPPORTED_KIND`. 
I am not able to find any documentation related to `@kind table`.

**Comment by hmakholm** [comment]
`@kind table` is a kind of catch-all kind, where the results of the query doesn't have to follow any particular format rules. It's a way to explicitly document that the query is not _intended_ to produce results that can be expressed as, for example, alerts to be displayed in the Code Scanning UI. It is automatically excluded from the standard query suites, based on the `@kind`.

Such a query can still be run manually with `codeql query run` on the command line, or in the VS Code extension, with results displayed in a plain tabular format.

The particular query you point to is intended to be useful during a manual security audit of a codebase, even though its user interface is a bit rough.
