### ISSUE TITLE
SinkModelCsv

### ISSUE THREAD

**Issue by turn1tup** [github/codeql#7476]
**Description of the issue**
Hello! Recently, I study codeql java rule.But the offical doc is not enough.
I want to know the deatil of the class "SinkModelCsv", which's grandfather is TMkUnit.
The following example, I change the "false" to "true" and the result seems no different. Another , I notice there are odditional ";;;".
So, I want to know more deatil, Thank you !

private class MyDefaultOgnlInjectionSinkModel extends SinkModelCsv {
override predicate row(string row) {
    row =
      [  ...
        "ognl;Ognl;false;getValue;;;Argument[0];my-ognl-injection",
    ....

**Comment by turn1tup** [comment]
I knwo the answer

**Comment by Yoga7xm** [comment]
> I knwo the answer

hello! I want to know more detail of this "SinkModelCsv" too . Can you help me understand this format of ModelCsv? Thank You.

**Comment by smowton** [comment]
Firstly have a look at the comment at the top of https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll. Post back if any of that is not clear.

**Comment by turn1tup** [comment]
> > I knwo the answer
> 
> hello! I want to know more detail of this "SinkModelCsv" too . Can you help me understand this format of ModelCsv? Thank You.
As @smowton said,you can read the comment to know what the "ModelCsv" is, another,you should read the rule (for example , ognl ) and setp into each predicate or function , after that eryerything is easy.
