### ISSUE TITLE
Query improvement: Include IO.popen as a command execution sink in Ruby's standard library

### ISSUE THREAD

**Issue by bananabr** [github/codeql#7483]
The current Ruby standard queries do not consider IO.popen (https://www.rubydoc.info/stdlib/core/IO.popen) as a command execution sink.
I don't have the time to work on a PR right now, but I would really like to see this implemented.

Thank you,

**Comment by edoardopirovano** [comment]
Greetings. Many thanks for raising this with us - this seems like a sensible enhancement to our queries. I'll let @github/codeql-ruby comment further on how easy this is to do and if/when they'll be able to prioritise working on this.

**Comment by alexrford** [comment]
Sorry for the lack of updates on this - `IO.popen` was added as a command execution sink in https://github.com/github/codeql/pull/8635.
