### ISSUE TITLE
JavaScript type confusion documentation example mistake 

### ISSUE THREAD

**Issue by Naman-ntc** [github/codeql#7488]
In the [Type confusion through parameter tampering](https://codeql.github.com/codeql-query-help/javascript/js-type-confusion-through-parameter-tampering/) documentation, the fixed example seems to be wrong. 

It does a check on `typeof path !== string` which should be `typeof file !== string`. The comments in the example also do not make sense. I suppose updating [TypeConfusionThroughParameterTampering_fixed.js](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-843/examples/TypeConfusionThroughParameterTampering_fixed.js) javascript file would be sufficient (the query-tests folder doesn't have this example)?

**Comment by edoardopirovano** [comment]
Greetings, many thanks for spotting this issue! I've opened a PR that fixes that example here: https://github.com/github/codeql/pull/7489
