### ISSUE TITLE
dataflow can't flow from one project to another in java query

### ISSUE THREAD

**Issue by KiruaLawliet** [github/codeql#7492]
build two java database and run query script by [Right Click Menu] -> CodeQL: Run Query on Multiple Databases

![image](https://user-images.githubusercontent.com/16208969/147747470-ec0e123c-20e1-4266-baf1-3a460c9147a2.png)

Result shows that taint dataflow can't flow from one project to another.

**Comment by edoardopirovano** [comment]
Greetings, many thanks for reaching our for us with this question. Indeed, it is not currently possible for CodeQL queries to analyze data flow across projects. The _Run Query on Multiple Databases_ button in the VS Code extension that you point out is not intended to do this - all it does is run the query on each database individually.

**Comment by KiruaLawliet** [comment]
@edoardopirovano  ok，thanks for your reply.
