### ISSUE TITLE
Does CodeQL understand C# file-scoped namespaces?

### ISSUE THREAD

**Issue by sungam3r** [github/codeql#7544]
After migration to file-scoped namespaces I got a lot of new errors. See [CI pipeline](https://github.com/graphql-dotnet/parser/runs/4749699509?check_suite_focus=true) and [CodeQL workflow file](https://github.com/graphql-dotnet/parser/blob/master/.github/workflows/codeql-analysis.yml).

Build results:
```
 GraphQLParser -> /home/runner/work/parser/parser/src/GraphQLParser/bin/Debug/netstandard2.0/GraphQLParser.dll
 GraphQLParser -> /home/runner/work/parser/parser/src/GraphQLParser/bin/Debug/netstandard2.1/GraphQLParser.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

CodeQL results:
```
|          Diagnostic          |         Summary          |
+------------------------------+--------------------------+
| Extraction errors            | 101 results (101 errors) |
| Successfully extracted files | 2 results                |
```

Example error:
![изображение](https://user-images.githubusercontent.com/21261007/148661075-5f14c4e1-dac6-44e0-96ca-86bf4e9f5be6.png)

**Comment by tamasvajk** [comment]
Thank you for reporting this issue. File-scoped namespace declarations are not yet supported by codeql, we're working on adding C# 10 support.

**Comment by michaelnebel** [comment]
Yes, we just merged support for it today.
[File scoped namespaces](https://github.com/github/codeql/pull/7532)

**Comment by sungam3r** [comment]
Thanks! ping @Shane32

**Comment by sungam3r** [comment]
@tamasvajk @michaelnebel What do I need to configure in CI to get this feature? Bump CodeQL GitHub action version?

**Comment by tamasvajk** [comment]
I don't think there's a way to configure this in the action. You would need to wait for a new release that contains these changes. 

The [change notes](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) of the `codeql-action` shows when a new codeql version is included in the action. Also, there are more detailed release notes for the CLI [here](https://github.com/github/codeql-cli-binaries/releases).

For your particular case, the change regarding file-scoped namespace declarations was just merged, so it will take a couple of weeks to be released. There was an [earlier change](https://github.com/github/codeql/pull/6791/) to upgrade the C# compiler dependencies to the latest version, which would remove the parsing errors, and simply omit the extraction of these namespace declarations. This might be a working partial solution for your current need. The [next release] will contain this change.

**Comment by sungam3r** [comment]
OK. Then please close this issue when you publish a new release so I can get a notification.

**Comment by ga394** [comment]
> OK. Then please close this issue when you publish a new release so I can get a notification.

**Comment by DanJesensky** [comment]
Any news on this? I could be missing something, but it looks like this should've been fixed if targeting `github/codeql-action/{init,autobuild,analyze}@v1.0.30` which checks out codeql-cli v2.7.5, and I'm still getting extraction errors in every file I use file-scoped namespaces:

> Unexpected C# extractor error: Unhandled top-level syntax node
at Semmle.Extraction.CSharp.Populators.TypeContainerVisitor.DefaultVisit(SyntaxNode node) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Populators/TypeContainerVisitor.cs:line 39
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitFileScopedNamespaceDeclaration(FileScopedNamespaceDeclarationSyntax node)
at Microsoft.CodeAnalysis.CSharp.Syntax.FileScopedNamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
at Semmle.Extraction.CSharp.Populators.CompilationUnitVisitor.<>c__DisplayClass2_0.b__0() in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Populators/CompilationUnitVisitor.cs:line 28
at Semmle.Extraction.Context.Try(SyntaxNode node, ISymbol symbol, Action a) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 484
CodeQL

Am I not looking at the right release?

**Comment by michaelnebel** [comment]
Hi, the file scoped namespace functionality is not included in v.2.7.5 and it is not included in v.2.7.6 either.
We expect the PR containing the file scoped namespaces will be included in the next CLI release, which will be v.2.8.0.
One way to check, if a certain piece of functionality (or more specifically a PR) is included in a given release, is to inspect the  tags on the last commit of the PR.

Examples:
The [commit](https://github.com/github/codeql/pull/7337/commits/13347cd102751a840d294a7c2f6d434559bc1a6f) has the codeql-cli/v2.7.6, which means that this change is included in the CLI v.2.7.6.

The last [commit](https://github.com/github/codeql/pull/7532/commits/23b844434867b88394f073876bde0d184f2dd472) of the PR with the file scoped namespaces does not have any tags yet (at the time of writing).

**Comment by michaelnebel** [comment]
The C# file-scoped namespace support is included in v.2.8.0: https://github.com/github/codeql-cli-binaries/releases

**Comment by sungam3r** [comment]
Thanks

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/parser/runs/5090401946?check_suite_focus=true#step:7:52
![изображение](https://user-images.githubusercontent.com/21261007/152757770-4bec2dbf-6ae2-46b9-b1a4-aac232446504.png)

My workflow - https://github.com/graphql-dotnet/parser/blob/master/.github/workflows/codeql-analysis.yml

Should I bump action versions?

**Comment by hvitved** [comment]
2.8.0 has only just been released, and it takes a week (or so) before is reaches Code Scanning. So I'm afraid all you can do is wait.

**Comment by sungam3r** [comment]
Ah, OK.

**Comment by sungam3r** [comment]
2.8.0 arrived into our worflow!
