### ISSUE TITLE
LGTM.com - false positive `go/incorrect-integer-conversion`

### ISSUE THREAD

**Issue by Gusted** [github/codeql#7608]
**Description of the false positive**

The query warns about the usage of conversations when a higher bit size is converted to a lower bit size. However it also will error in the usage of `int64` -> `int`, which is incorrect. As this doesn't conversion doesn't cause any integer overflow. The `int` type can hold the maximum/minimum value of `int64`(as seen [here](https://go.dev/play/p/EiJyae4Dh23)) and thus cannot cause any integer overflow. Adding any checks is useless for this conversion. The same thing applies with `uint64` -> `uint` conversions and can be generalized to `intXX` -> `int` & `uintXX` -> `uint`? I've only seen this happening on the 64 bit so far.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/go-gitea/gitea/snapshot/ec86b032e3467e6e3d12292d6c17fc5ded94cf28/files/models/auth/source.go?sort=name&dir=ASC&mode=heatmap#x87edecc4d75f95b4:1

**Comment by smowton** [comment]
In general `int` and `uint` might be 32-bit depending on the architecture your program is compiled for.

**Comment by Gusted** [comment]
> In general `int` and `uint` might be 32-bit depending on the architecture your program is compiled for.

Ah yep, that's a good one. I didn't consider that, is it possible to mention that with the rule?
