### ISSUE TITLE
LGTM.com - false positive C# record classes (records) - Local scope variable shadows member

### ISSUE THREAD

**Issue by ldeluigi** [github/codeql#7609]
**Description of the false positive**
When using recors, a false positive about local variable shadowing pops up.
![image](https://user-images.githubusercontent.com/44567586/149657088-69b3a800-0e1b-4b6f-821d-ef35a8e5ea62.png)

**URL to the alert on the project page on LGTM.com**

https://github.com/e-scooter-2077/rent.manage-scooter-availability/security/code-scanning/16?query=ref%3Arefs%2Fheads%2Fmaster

**Comment by tausbn** [comment]
Thank you for your report!

I agree that this looks like a false positive. I will forward it to the CodeQL C# team.

**Comment by smowton** [comment]
Fixed in https://github.com/github/codeql/pull/7628 -- the fix will show up as of CodeQL 2.12.1, which is estimated to begin rolling out on 24th January.
