### ISSUE TITLE
java/inefficient-output-stream - false positive

### ISSUE THREAD

**Issue by pivotal-jbarrett** [github/codeql#7610]
java/inefficient-output-stream does not detect overrides with annotated parameters.

Using `@NotNull` annotation when overriding `OutputStream.write(byte[],int,int)` LGTM falsely reports the method is not overridden.

https://lgtm.com/projects/g/apache/geode/snapshot/ea9978861be8143611575cc24ca5d82e9c222879/files/geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java?sort=name&dir=ASC&mode=heatmap#L2231

**Comment by tausbn** [comment]
Thank you for your report!

I agree that this looks like a false positive. I have forwarded this report to the team in charge of the Java analysis.

**Comment by smowton** [comment]
I have a Java extractor fix for this in the pipeline.

**Comment by smowton** [comment]
Fix committed; this should work as of future CodeQL release 2.8.3.
