### ISSUE TITLE
codeql script is incompatible with gnu coreutils

### ISSUE THREAD

**Issue by CaledoniaProject** [github/codeql#7624]
I've installed coreutils with homebrew, and linked gnu xattr to $PATH. When codeql starts, it invokes `xattr -c` to remove attributes.

```
  if [ -w "${CODEQL_DIST}" -a -w "${CODEQL_DIST}/codeql" ]; then
    find "${CODEQL_DIST}" "(" -path "*/osx64/*" -o -path "*/macos/*" ")" -a \
      "(" -perm -100 -o -perm -10 -o -perm -1 -o -name "*.dll" ")" -a \
      "!" -type d -a -xattr -print0 | xargs -0 -- xattr -c
    xattr -c "${CODEQL_DIST}/codeql"
    chmod a-w "${CODEQL_DIST}/codeql"
  fi
```

However, gnu xattr does not support `-c` parameter, so please either
1.  change it to absolute path instead, e.g /usr/bin/xattr
2. temporarily disable `set` -e`

**Comment by tausbn** [comment]
Thank you for your report! I have brought it to the attention of the team responsible for the CodeQL utilities.

**Comment by edoardopirovano** [comment]
Thanks for reporting this! We've got a fix on our development branch that should make it into our 2.8.1 release (unfortunately it didn't _quite_ get done in time to get into 2.8.0 which we've just begun the testing process for).
