### ISSUE TITLE
Java: `getCommonSensitiveInfoRegex()` pattern might be incorrect

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#7636]
The pattern used by `getCommonSensitiveInfoRegex()` from module `semmle.code.java.security.SensitiveActions` might be incorrect:
https://github.com/github/codeql/blob/84097468cc8d826db03c9736c9760c1f02e5c050/java/ql/lib/semmle/code/java/security/SensitiveActions.qll#L30

`.*challenge` only allows arbitrary prefixes for `challenge`, but not for any of the other words. It looks like this was done by accident, the complete regex pattern should probably be:
<pre>
(?i).*<b>(</b>challenge|pass(wd|word|code|phrase)<b>)</b>(?!.*question).*
</pre>

Or is that intentional?

**Comment by tausbn** [comment]
Thank you for your report! 

I agree that this looks like a mistake. I will forward it to the CodeQL Java team.
