### ISSUE TITLE
"Failed with bad exit code during 'Checkout'" when not using "main" branch

### ISSUE THREAD

**Issue by WoLpH** [github/codeql#7640]
**When a new repository is pushed the automatic build fails due to missing main branch**

Apparently LGTM makes the erroneous assumption that every Git repository has a main branch: https://lgtm.com/logs/0176eefe523c586b18059cdad095d4435561d35b

**Comment by tausbn** [comment]
Thank you for your report!

LGTM.com always uses the default branch in the repository for its analysis. In this case, it looks like this may have recently been changed?

At any rate, as far as we can tell, LGTM.com has now picked up on the fact that the default branch is `master`, and so the analysis should start working again.

**Comment by WoLpH** [comment]
It's a brand new repository so as far as I know, nothing has changed.

I simply told Pycharm to publish the repository to Github and there never was a main branch as far as I know.

**Comment by tausbn** [comment]
Hmm... In that case, I'm not exactly sure what happened. I'm not familiar with how PyCharm does its publishing.

Either way, it _should_ hopefully be working now. If not, do let us know! :slightly_smiling_face:

**Comment by WoLpH** [comment]
Yes, it appears to work fine now :)
But I highly suspect this behavior is repeatable and will result in more bug reports in the future so it might be good to figure out why this is happening.

From the build logs I can see this checkout which is working fine:
```
git clone --bare -- https://github.com/WoLpH/speedups.git /work/working/private/src/.git
```
After that it tries to change the branch to `main` it seems. But why? There is no specific branch configured so there shouldn't be a need to change the branch after checkout.
