### ISSUE TITLE
[JS][question] How can I set js file as module if I don't add "import ..." line in the origin js file?

### ISSUE THREAD

**Issue by greatyy** [github/codeql#7664]
@asgerf mentioned that Flow through globals is tracked less precisely in https://github.com/github/codeql/issues/7221
![image](https://user-images.githubusercontent.com/48902334/150242919-909315ae-2cc0-41fc-971a-5ae33d000af9.png)

Is there any ways to treat all js files as module without just add "import ..." in the origin js file?

**Comment by asgerf** [comment]
Not officially supported via the `codeql` CLI, but as a workaround you can set the environment variable `LGTM_INDEX_SOURCE_TYPE` to `MODULE`. For example,
```
env LGTM_INDEX_SOURCE_TYPE=MODULE codeql database create ....
```

**Comment by greatyy** [comment]
> Not officially supported via the `codeql` CLI, but as a workaround you can set the environment variable `LGTM_INDEX_SOURCE_TYPE` to `MODULE`. For example,
> 
> ```
> env LGTM_INDEX_SOURCE_TYPE=MODULE codeql database create ....
> ```

Thanks a lot! Problem solved!
