### ISSUE TITLE
Why won't codeql compiler throw an error here?

### ISSUE THREAD

**Issue by CaledoniaProject** [github/codeql#7690]
I'm doing a simple logical expression test:

```
predicate hasCapital(string country, string capital) {
    country = "Belgium" and capital = "Brussels"
    or
    country = "Germany" and capital = "Berlin"
    or
    country = "France" and capital = "Paris"
}

from int i
where hasCapital("Belgium", "Paris") and i = 2
select i
```

In C language if I do similar things the compiler would print a warning,

```
test.c:11:60: warning: '&&' within '||' [-Wlogical-op-parentheses]
    if (a == 1 && b == 2 || a == 10 && b == 20 || a == 100 && b == 200) {puts("OK");}
```

And I expect codeql to print a warning as well, unless I use `(country = "Belgium" and capital = "Brussels")` instead.
So why won't codeql throw an error here?

**Comment by smowton** [comment]
Just convention that it is understood that `and` binds more tightly. The autoformatter helps you out here by producing the sort of formatting you show above, where the typography lines up with the binding precedence.

**Comment by CaledoniaProject** [comment]
OK, Thanks
