### ISSUE TITLE
[C/C++] How to sanitize a class object after its member function change its value?

### ISSUE THREAD

**Issue by UniverseExplorer7274** [github/codeql#7714]
**Description of the issue**

codeql binary version: 2.7.5

When query path of this code, I got some false-positive paths which I don’t know how to eliminate.
Here is my code and my QL query.
I only want to get the path from `getInput(a)` to the first `system` call.

```cpp
#include <stdio.h>
#include <stdlib.h>

void getInput(char* a) {
    scanf("%s", a);
}

class B {
    public:
    char *b;
    void assign(char *a) {
        b = a;
    }

    char* getPtr() {
        return b;
    }
};

int main() {
    char *a = (char *)malloc(0x100);
    B b; 
    char *c = "This isn't tainted.";
    getInput(a);

    b.assign(a);

    system(b.getPtr());

    b.assign(c);

    system(b.getPtr());

    return 0;
}
```

```codeql
/**
 * @kind path-problem
 */

import cpp
import semmle.code.cpp.dataflow.TaintTracking
import DataFlow::PathGraph

class MyConfig extends TaintTracking::Configuration {
    MyConfig () {
        this = "MyConfig"
    }

    override predicate isSource(DataFlow::Node node) {
        exists( FunctionCall fc | 
            node.asExpr() = fc.getAnArgument() and
            fc.getTarget().getName().matches("getInput")
        )
    }

    override predicate isSink(DataFlow::Node node) {
        exists( FunctionCall fc | 
            node.asExpr() = fc.getAnArgument() and
            fc.getTarget().getName().matches("system")
        )
    }
}

from DataFlow::PathNode src, DataFlow::PathNode sink, MyConfig conf
where 
    conf.hasFlowPath(src, sink)
select sink.getNode(), src, sink, "From $@ to $@", src, src.toString(), sink, sink.toString()
```

However, I got 2 paths.
![image](https://user-images.githubusercontent.com/98157309/150514911-124d8cfe-7063-47cd-b405-43ace36bf1b3.png)

I think I should write a sanitizer which sanitizer the call to class object member function `assign` whose argument is not tainted. But I don't know how to write it in CodeQL.

I have tried to write a sanitizer like this, but the `DataFlow::PathNode` causes Non-monotonic recursion.
```codeql
predicate sanitizerAssign(DataFlow::Node node) {
    exists( FunctionCall fc, DataFlow::PathNode node1 | 
      node.asPartialDefinition() = fc.getQualifier() and
      fc.getTarget().hasName("assign") and
      not(
        fc.getAnArgument() = node1.getNode().asExpr() 
      )
    )
}
```

The expected result is like the following:
```cpp
#include <stdio.h>
#include <stdlib.h>

int main() {
    char *a = "echo \'This is tainted.\'";
    char *b;
    char *c = "echo \'This is not tainted.\'";

    b = a;
    system(b);
    
    b = c;
    system(b);

    return 0;
}
```

```codeql
/**
 * @kind path-problem
 */

import cpp
import semmle.code.cpp.dataflow.TaintTracking
import DataFlow::PathGraph

class MyConfig extends TaintTracking::Configuration {
    MyConfig () {
        this = "MyConfig"
    }

    override predicate isSource(DataFlow::Node node) {
        exists( VariableAccess va | 
            node.asExpr() = va and
            va.getTarget().getName().matches("a")
        )
    }

    override predicate isSink(DataFlow::Node node) {
        exists( FunctionCall fc | 
            node.asExpr() = fc.getAnArgument() and
            fc.getTarget().getName().matches("system")
        )
    }
}

from DataFlow::PathNode src, DataFlow::PathNode sink, MyConfig conf
where 
    conf.hasFlowPath(src, sink)
select sink.getNode(), src, sink, "From $@ to $@", src, src.toString(), sink, sink.toString()
```

![image](https://user-images.githubusercontent.com/98157309/150714194-8582d12b-aeed-499a-a6c7-2ec571546670.png)

there is not path to the second `system` call

Any reply will be appreciated. If there is any other information needed, please let me know.

**Comment by smowton** [comment]
I'm afraid this is a known shortcoming of the C/C++ CodeQL analysis: because it's very common for C programs to have many aliases for the same memory location, it currently never notices that a particular location is certainly overwritten with clean data and therefore constitutes a barrier.

Unfortunately this can't easily be worked around using a barrier, because the dataflow step you'd need to eliminate goes straight from the write on line 26 to the read on line 32. That means your `isBarrier` implementation would need to interrupt that flow at line 32, without also identifying the true-positive flow to line 28. You would need to identify situations where a field read always comes from a field write of something clean (e.g., a constant), which is in general pretty difficult. I would suggest it's better to accept (and if necessary, dismiss) the false positive than to write that workaround.

**Comment by UniverseExplorer7274** [comment]
Thanks for your reply. I will take your suggestion.

However, I think the situation is a common in C/C++ program. And it might lead to tons of false-positive result if happened in the beginning of the program.

If it’s possible to provide an API like DataFlow::SourceNode.flowsToExpr in CodeQL for Javascript in this example. 
https://lgtm.com/query/2562618391260740405/

```codeql
class StringSanitizerGuard extends TaintTracking::SanitizerGuardNode, DataFlow::ExprNode {
  StringSanitizerGuard() {
    guardInequality(this, "string") = true or
    guardEquality(this, "string") = false
  }

  Expr getSanitizedExpr() {
    exists(TypeofExpr te, DataFlow::SourceNode sn |
      this.asExpr().(EqualityTest).hasOperands(te, _) and
      sn.flowsToExpr(te.getOperand()) and
      (
        result = sn.asExpr() or
        result = te.getOperand()
      )
    )
  }

  override predicate sanitizes(boolean outcome, Expr e) {
    (
      outcome = guardInequality(this, "string") or
      outcome = guardEquality(this, "string")
    ) and
    e = getSanitizedExpr()
  }
}
```

If it’s possible, we can use it to check if any argument of the `Format` FunctionCall is tainted in this situation.

Apologizes for any stupid word, my wish is to make CodeQL better. :)

**Comment by UniverseExplorer7274** [comment]
Thanks for your patient reply.

Shall we close this issue or leave it until the problem is fixed? @smowton
