### ISSUE TITLE
A symbol in CodeQL Query Results

### ISSUE THREAD

**Issue by KeuntaeShin** [github/codeql#7745]
With Dataflow, a symbol is appeared in several rows (and there are not paths like below). What does it mean? Is there any document that describes about the symbol?

![image](https://user-images.githubusercontent.com/1381322/151094866-b9edf6bb-5718-4189-a99a-eee8aba09a2f.png)

**Comment by smowton** [comment]
You mean rows 1 and 3? These indicate zero-length paths: the source is equal to the sink.

**Comment by KeuntaeShin** [comment]
> You mean rows 1 and 3? These indicate zero-length paths: the source is equal to the sink.

Thank you for your time!
