### ISSUE TITLE
FastAPI Request: possible false positive

### ISSUE THREAD

**Issue by prithvijitguha** [github/codeql#7786]
**Description of the issue**

Hi All, 

I have a fastapi app I'm running codeQL on. I seem to be receiving a `Reflected server-side cross-site scripting` in `python` for sanitizing a fastapi `Request`. 

```python

from fastapi import Request

@app.get("/register", response_class=HTMLResponse)
async def register_page(request: Request):
    """
    Register page
    """
    return templates.TemplateResponse("register.html", {"request": request})
```

There's no user input in this part, it's a get request? I thought it may be a false positive? 

If otherwise please let me know 😃

**Comment by aibaars** [comment]
Hi @prithvijitguha , thanks for you question. A `GET` request may contain user-provided input, for example parameters in a query string or in request headers.

It looks like the entire request is passed into `templates.TemplateResponse` so there could indeed be a risk of cross-site scripting depending on what data the template takes from the request and includes in the generated output.

**Comment by prithvijitguha** [comment]
Hi @aibaars, thank you for that answer! 

This answer helped fix a similar error I was having. I'm working on this particular one however I'm not sure which part of `Request` class needs to sanitized. 

Would you happen to have an idea on this? this is the same `Request` from `from starlette.requests import Request`?

Either case I think this question can be closed. Thank you so much!

**Comment by aibaars** [comment]
> This answer helped fix a similar error I was having. I'm working on this particular one however I'm not sure which part of `Request` class needs to sanitized.

Glad I could help! Unfortunately, I don't know how to answer your followup question. Which part of the request needs to be sanitized depends a bit on what the template is doing. Is it really necessary to pass the entire Request to the template? It might be clearer to only pass the parts that are actually used by the template to the `templates.TemplateResponse` function.

**Comment by prithvijitguha** [comment]
Hi @aibaars 

For `templates.TemplateResponse`, the complete request  must be passed. 

Here is the snippet from the documentation: 

Import Jinja2Templates.
Create a templates object that you can re-use later.
Declare a Request parameter in the path operation that will return a template.
Use the templates you created to render and return a TemplateResponse, passing the request as one of the key-value pairs in the Jinja2 "context".

Note: 

Notice that you have to pass the request as part of the key-value pairs in the context for Jinja2. So, you also have to declare it in your path operation.

``` python 
@app.get("/items/{id}", response_class=HTMLResponse)
async def read_item(request: Request, id: str):
    return templates.TemplateResponse("item.html", {"request": request, "id": id})
```

[Fastapi template response documentation](https://fastapi.tiangolo.com/advanced/templates/#using-jinja2templates)

**Comment by aibaars** [comment]
> For `templates.TemplateResponse`, the complete request must be passed.

Indeed, you're right, so my suggestion won't work .

Does `register.html` use an of the properties of the Request? It's quite likely that a registration page picks things like the host name/scheme/path from the original request to for example generate a redirect link or similar.

**Comment by prithvijitguha** [comment]
Hi @aibaars , 

`register.html` is a jinja template which extends `base.html` and comprises of mainly a form. 

Another point to mention is I have got similar errors for all `app.get()` but not for `app.post()` urls. 

It is highlighting: 
```python
request: Request
```

But there is also register post 
```python
@app.post("/register")
async def register(
    request: Request,
    username: str = Form(...),
    password: str = Form(...),
    profile_picture: UploadFile = File(None),
    email: str = Form(...),
    db: Session = Depends(get_db),
):
````
Also to note I am directly passing the request to the template in post requests.. (I am sanitizing the str: Form data).

```python
   success_context = {
        "request": request,
        "message": "Successfully registered",
        "tag": "success",
    }
    return templates.TemplateResponse("login.html", context=success_context)
```
Not sure why that is?

**Comment by RasmusWL** [comment]
Hi @prithvijitguha, thanks for reporting this :+1: I've been able to reproduce your problem with the code below, getting XXS results for both the `get` and `post` handlers

```py
# see https://fastapi.tiangolo.com/advanced/templates/

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates

app = FastAPI()


templates = Jinja2Templates(directory="templates")


@app.get("/foo", response_class=HTMLResponse)
async def foo_handler(request: Request, id: str):
    return templates.TemplateResponse("foo.html", {"request": request})


@app.post("/foo", response_class=HTMLResponse)
async def foo_post_handler(request: Request, id: str):
    return templates.TemplateResponse("foo.html", {"request": request})
```

I'll work on a fix for this, which should make its way into the CodeQL version used by Code Scanning within a few weeks.

**Comment by prithvijitguha** [comment]
Hi @RasmusWL 

Thank you so much for the support!
