### ISSUE TITLE
C++: Add `FieldAccessCall` for calls from function pointers in structs

### ISSUE THREAD

**Issue by gsingh93** [github/codeql#7822]
I have to analyze a lot of code that calls function pointers defined in struct fields. `ExprCall` is able to find these, but it's not ergonomic to use in this case, as I need to convert `this.getExpr()` to a `FieldAccess`, and I need to check the target fields name against the function I want and the declaring type of the target field against the struct type. This gets messy without a helper class, so I was hoping we could add something like `FieldAccessCall` to the standard library.

Here is how it could look:
```ql
import cpp

class FieldAccessCall extends ExprCall {
  FieldAccessCall() { this.getExpr() instanceof FieldAccess }

  Field getField() { result = this.getExpr().(FieldAccess).getTarget() }

  string getFieldName() { result = getField().getName() }

  Type getDeclaringType() { result = getField().getDeclaringType() }
}

from FieldAccessCall fac
where fac.getFieldName() = "foo" and fac.getDeclaringType().getName() = "Foo"
select fac
```
It works on this test code:
```c
struct Foo {
  void (*foo)();
  void (*bar)();
};

struct Bar {
  void (*foo)();
  void (*bar)();
};

void test(Foo &f1) {
  f1.foo(); // Alert
  f1.bar(); // No alert

  Foo f2;
  f2.foo(); // Alert
  f2.bar(); // No alert

  Foo *f3 = new Foo();
  f3->foo(); // Alert
  f3->bar(); // No alert

  Bar b;
  b.foo(); // No alert
  b.bar(); // No alert
}
```

**Comment by geoffw0** [comment]
Hi,

Thanks for your suggestion.  We don't think this class would see wide enough use to have a place in the standard libraries, but you are welcome to create a local `.qll` library for your own use!

We *do* have a `VariableCall` class extending `ExprCall` that is similar to your `FieldAccessCall` class but more general.  `VariableCall` includes calls from any `VariableAccess` expression, including but not limited to field accesses.  `VariableCall.getVariable()` returns the target, equivalent to your `getField` except that the `Variable` that is returned may or may not be a `Field`.

**Comment by gsingh93** [comment]
Thanks! I was able to rewrite my query as this and the test above passes without the need to introduce `FieldAccessCall`:
```
import cpp

from VariableCall vc
where
  vc.getVariable().getDeclaringType().getName() = "Foo" and
  vc.getVariable().getName() = "foo"
select vc
```

I'll go ahead and close this issue.
