### ISSUE TITLE
False positive in javascript type confusion vulnerability

### ISSUE THREAD

**Issue by Naman-ntc** [github/codeql#7840]
I believe the following code is safe with respect to the type confusion vulnerability however is still returned by the query.
```js
express().get('/some/path/:foo', function(req, res) {
    let p = req.query.path;
    if (typeof p !== 'string') {
        return;
    }
    while (p.indexOf("..")) p.replace("..", ""); // OK
});
```

I ran the following query which finds the node corresponding to p in the while loop condition and returns its type. I found that it returns all possible types for p, therefore, leading to false positives. 
```codeql
import javascript

from WhileStmt s, DataFlow::Node n
where n.asExpr() = s.getExpr().getAChildExpr().getAChildExpr()
select n, n.analyze().getAType()
```

I would assume this is because the type inference module does not utilize return statements to infer the exact type. Is that correct or am I missing something?

**Comment by max-schaefer** [comment]
Thanks for the report.

> I would assume this is because the type inference module does not utilize return statements to infer the exact type.

It does in principle, but apparently not in this example.

**Comment by max-schaefer** [comment]
So, I can't actually reproduce the problem. For me, the query manages to infer the correct type for `p` (namely `string`) on your example.

**Comment by Naman-ntc** [comment]
Okay, apologies, my bad. I also observe the correct behavior for the code I posted. 
I actually tried the following code and removed the first while loop (`while (p.length) { `) when reporting here (considering it innocent!). I assumed that `p=p.substr(1)` would retain type as string and not cause any issues but doesn't seem like it
```js
var express = require('express');
    path = require("path");

express().get('/some/path/:foo', function(req, res) {
    let p = req.query.path;
    if (typeof p !== 'string') {
        return;
    }
    while (p.length) { // OK
        p = p.substr(1);
    }
    p.length < 1; // OK
    while (p.indexOf("..")) p.replace("..", ""); // OK
});
```

**Comment by max-schaefer** [comment]
Ah, no, indeed, the type inference doesn't know about `substr`. It is purely local and has no knowledge of the standard library (or indeed any other libraries!), and so isn't generally very useful for writing security queries.

**Comment by Naman-ntc** [comment]
Oh, I see! Feel free to close the issue then
