### ISSUE TITLE
Unexpected C# extractor error: Unhandled top-level syntax node

### ISSUE THREAD

**Issue by jeffpriz-3c** [github/codeql#7882]
Running Scan on a new C# project using the security and quality query list.  End up with a number of Extraction errors on our C# class files

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        queries: security-and-quality

--------------
Analysis produced the following diagnostic data:

|          Diagnostic          |        Summary         |
+------------------------------+------------------------+
| Extraction errors            | 10 results (10 errors) |
| Successfully extracted files | 12 results             |
Analysis produced the following metric data:

|               Metric                | Value |
+-------------------------------------+-------+
| Total lines of code in the database |   192 |

---------------

Unexpected C# extractor error: Unhandled top-level syntax node
at Semmle.Extraction.CSharp.Populators.TypeContainerVisitor.DefaultVisit(SyntaxNode node) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Populators/TypeContainerVisitor.cs:line 39
at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitFileScopedNamespaceDeclaration(FileScopedNamespaceDeclarationSyntax node)
at Microsoft.CodeAnalysis.CSharp.Syntax.FileScopedNamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
at Semmle.Extraction.CSharp.Populators.CompilationUnitVisitor.<>c__DisplayClass2_0.b__0() in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Populators/CompilationUnitVisitor.cs:line 28
at Semmle.Extraction.Context.Try(SyntaxNode node, ISymbol symbol, Action a) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 459
CodeQL

**Comment by jeffpriz-3c** [comment]
uploading Sarif from a run here
[sarif.zip](https://github.com/github/codeql/files/8017719/sarif.zip)

**Comment by aeisenberg** [comment]
Thank you for reporting your error. I'll forward this on to the team who maintains the C# extractor.

It might be that your project is just not compatible with the codeql autobuilder. Please take a look at [the documentation](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-the-codeql-workflow-for-compiled-languages#c).

**Comment by jeffpriz-3c** [comment]
> Thank you for reporting your error. I'll forward this on to the team who maintains the C# extractor.
> 
> It might be that your project is just not compatible with the codeql autobuilder. Please take a look at [the documentation](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-the-codeql-workflow-for-compiled-languages#c).

Thanks, I will attempt to build outside of the autobuild to see if that changes any behavior, but this is pretty straight-forward and not out-of-the-ordinary build-wise.

**Comment by jeffpriz-3c** [comment]
Interestingly, swapping out the autobuild for a build that is just:

dotnet build --Configuration Release 

results in slightly different number of errors, but still the Extractor errors persist
|          Diagnostic          |       Summary        |
+------------------------------+----------------------+
| Extraction errors            | 7 results (7 errors) |
| Successfully extracted files | 9 results            |
Analysis produced the following metric data:

|               Metric                | Value |
+-------------------------------------+-------+
| Total lines of code in the database |   158 |


Overall this shows fewer errors, but also fewer successful extractions and fewer total lines of code.

**Comment by aeisenberg** [comment]
Is your repository public? If not we will need some more information in order to help. If it's private, can you share the full (with redactions) workflow and log?

**Comment by jeffpriz-3c** [comment]
It is private... here is a copy of the current code ql yaml and the latest log of that step (redacted the log)
[15.zip](https://github.com/github/codeql/files/8018321/15.zip)
[codeql-analysis.zip](https://github.com/github/codeql/files/8018324/codeql-analysis.zip)

**Comment by jeffpriz-3c** [comment]
but as an example, since this is a new project there isn't really a lot of code in place yet.  But this very simple class throws the C# Extractor error, and I just don't understand why
![image](https://user-images.githubusercontent.com/97974887/152865405-2edc85df-4ee8-4437-b631-585469027c17.png)

**Comment by jeffpriz-3c** [comment]
It Appears as though the Extractor just doesn't like the newer Namespace syntax that doesn't use braces.  
![image](https://user-images.githubusercontent.com/97974887/152870396-f8d116ad-6c86-46e9-b424-15b375c75c6c.png)

I swapped over the Namespace syntax to follow the older syntax with the braces encapsulating the class and the errors go away.   I guess can the extractor's start handling this syntax?

**Comment by aeisenberg** [comment]
Ah...yes. That makes sense. The C# extractor does not yet support C# 10. It is under active development. See https://github.com/github/codeql/issues/7086 for more details.

**Comment by aeisenberg** [comment]
I'm closing this issue since the root cause is known.

**Comment by michaelnebel** [comment]
CLI version 2.8.0 will have support for the global namespace feature for C# 10.

**Comment by jeffpriz-3c** [comment]
@michaelnebel awesome thanks for the update..  what is the expected timeframe for that release?

**Comment by michaelnebel** [comment]
@aeisenberg has brought it to my attention that it should be possible to use 2.8.0 already now in your workflow. So maybe you just need to change your workflow file to point to the newer version of the CLI?

**Comment by jeffpriz-3c** [comment]
> @aeisenberg has brought it to my attention that it should be possible to use 2.8.0 already now in your workflow. So maybe you just need to change your workflow file to point to the newer version of the CLI?

I'll review the documentation to see how to target a specific version and give it a shot

**Comment by jeffpriz-3c** [comment]
> > @aeisenberg has brought it to my attention that it should be possible to use 2.8.0 already now in your workflow. So maybe you just need to change your workflow file to point to the newer version of the CLI?
> 
> I'll review the documentation to see how to target a specific version and give it a shot

@aeisenberg @michaelnebel  I don't see anything in the documentation on the action tasks that shows how to configure the version of CodeQL CLI to use.  can you point me in the right direction?   Poking around in the logs of the latest run it appears that it is running 2.7.6 by default...?
