### ISSUE TITLE
LGTM alert beyond response limit!

### ISSUE THREAD

**Issue by Naman-ntc** [github/codeql#7889]
I was scanning alerts on lgtm.com and for a particular project the HTTP response is beyond the response limit for https://lgtm.com//api/v1.0/analyses/f92fa1b04aec4a90a66ddf98b72faaa9baf92bb3/alerts

`HTTP response was too large: 37767742. The limit is: 33554432.`

**Comment by aibaars** [comment]
The restriction on response size is a hard limit imposed by the application server. I suspect some of the results have very many/large dataflow paths. Curiously, downloading the results in SARIF format through the UI is still possible. The size is about 17MB, which is still large for such a small number of results, but at least below the limit. 

https://lgtm.com/projects/g/anylogic/alogic/analysis/f92fa1b04aec4a90a66ddf98b72faaa9baf92bb3/files

You can also try to fetch the alerts in CSV format through the API:
```
curl -H 'Accept: text/csv' https://lgtm.com//api/v1.0/analyses/f92fa1b04aec4a90a66ddf98b72faaa9baf92bb3/alerts
```

**Comment by Naman-ntc** [comment]
Hi, Yeah the CSV route works but ideally, sarif would be more helpful.
