### ISSUE TITLE
[Question] More complex scenarious for creating tests

### ISSUE THREAD

**Issue by rbut-husaim-gte** [github/codeql#7983]
Hello a CodeQL team!

First, thanks for all your effort creating such an interesting tool. Really enjoy working with it.

## Description

Now, back to the actual issue.

Environment: **dotnet**
OS: windows/linux

At the moment I'm working on codelql custom queries for csharp language. One of the steps for it - ensure that we have proper unit-tests for each query as part of our pipeline. And what I'm struggling to understand is how to setup more advanced unit-test scenarios for the queries I'm creating.

To be more precise the [documentation](https://codeql.github.com/docs/codeql-cli/testing-custom-queries/) states to put the files query will be launched against in the same folder. And it looks ok for basic tests. In our case in order to perform a test we need to specify an entire project/solution with a set of public/private packages for it.

I've tried to create a custom `sut` folder and place all test source code into it however it looks like the `codeql cli test run` command does not recognize it. Here is the tree structure I'm using:

```text
-> custom-queries
----> csharp
------> src
--------> CustomQuery.ql
--------> ...
--------> qlpack.yml
-------> test
---------> qlpack.yml
---------> CustomQuery
-----------> CustomQuery.qlref
-----------> sut
-------------> <source_code_to_launch_tests_agains>
```

Here is what I see in the logs:

```cmd
Executing 1 tests in 1 directories.
Extracting test database in C:\work\github-actions\codeql\custom-queries\csharp\test\CustomQuery.
The 'csharp' extractor found nothing to extract in C:\work\github-actions\codeql\custom-queries\csharp\test\CustomQuery.
Compiling queries in C:\work\github-actions\codeql\custom-queries\csharp\test\CustomQuery.
Executing tests in C:\work\github-actions\codeql\custom-queries\csharp\test\CustomQuery.
Cannot find CustomQuery.expected file.
Query produced no results.
[1/1 eval 1.1s] FAILED(RESULT) C:\work\github-actions\codeql\custom-queries\csharp\test\CustomQuery\CustomQuery.qlref
0 tests passed; 1 tests failed:
  FAILED: C:\work\github-actions\codeql\custom-queries\csharp\test\CustomQuery\CustomQuery.qlref
```

I've noticed that the `test run` command created the following folder - `CustomQuery.testproj`. However the attempt to place the generated database from `database create` command failed as

+ by default `run` command recreates a folder;
+ see no options to avoid database creation in the [docs](https://codeql.github.com/docs/codeql-cli/manual/test-run/).

Exactly same situation with `test extract` command. 

What I would like to understand is how to test complex scenarios whether either a database already exists or it should be generated in a more complex manner?

Thanks.

## Resources

+ https://codeql.github.com/docs/codeql-cli/manual/test-run/
+ https://codeql.github.com/docs/codeql-cli/manual/test-extract/
+ https://codeql.github.com/docs/codeql-cli/testing-custom-queries/

**Comment by aeisenberg** [comment]
Thank you for your question. 

I believe the reason why your `test run` command is failing is that the sources are in a sub-directory in the test folder. In general, these tests are meant to be unit tests. They are not expected to run against large or complex databases. Rather, they are meant to run against a small code snippet that is carefully crafted to satisfy the query.

The `test run` command will create a codeql database in `CustomQuery.testproj`. If the test is successful, then the database will be removed on exit. If there is a failure, then the database will stick around.

If you want to test more elaborate scenarios, then you may find that the codeql unit test infrastucture is no longer enough and you will need to create something bespoke. However, before you go down this route, I recommend you first focus on creating smaller test cases with small snippets to unit test your queries.

Though, now that I tried this out myself, I see that the csharp extractor is behaving differently in this scenario from the java extractor. The csharp extractor is not extracting files in sub-directories of tests, whereas the java extractor does. I am asking the csharp team for some guidance.

**Comment by rbut-husaim-gte** [comment]
Hello @aeisenberg ,

Thanks a lot for the feedback. The queries we have usually depend on a bunch of libraries so defining unit-tests require them to be present somewhere near cs files and used inside (`EntityFramewokCore`, `NHibernate`, `Autofac`, etc.) - due to `fromLibrary` calls inside the query. I'm not sure whether this is possible in general.

The approach that I wish to evaluate at the moment is to essentially:

1. Prepare a test project (SUT) to launch the analysis against.
2. Execute the analysis against this test project.
3. Compare the results produced by the analysis with the ones we expect.

Will keep you updated on the outcomes.

Thanks.

**Comment by aeisenberg** [comment]
It might be useful to look at how the csharp library itself uses ql tests. https://github.com/github/codeql/tree/main/csharp/ql/test/

**Comment by rbut-husaim-gte** [comment]
Hello everyone,
I'm going to close this one as we've built our small in-house testing approach according to the plan above.
Thanks.
