### ISSUE TITLE
What's the optimal way to query multiple projects?

### ISSUE THREAD

**Issue by erik-whiting** [github/codeql#7990]
Hi, I hope general questions are ok. 

I have a use-case where I'm cloning a project, building the CQL database, then analyzing the results. I'm doing this for hundreds of projects a day.

Each project is the same language so I'm wondering if I can save some time by only building one database inside a directory with the hundreds of projects each in their own subdirectory, and running the analysis on each subdirectory.

I'm not sure how the database is built so I don't know if this would actually save time vs building and analyzing for each individual project.

Any thoughts? Or any advice on saving time when analyzing many repositories?

**Comment by edoardopirovano** [comment]
Greetings!

Unfortunately, I don't expect you'll be able to save time by building one huge database with many distinct projects like this. If anything, doing this may result in a _slower_ analysis time, as CodeQL queries that try to (for instance) find data flow between different parts of the code will be trying (in vain) to identify calls between the distinct projects.

In terms of general advice for improving the performance of CodeQL, I would recommend passing in a `--ram` flag with most of the memory of your machine (although leaving at least 2GB for your operating system), and a `--threads` flag with the number of cores on your machine.
