### ISSUE TITLE
Non existent schema for sarif files

### ISSUE THREAD

**Issue by jacobmsft** [github/codeql#8033]
The schema definition output by codeql 2.6+ doesn't exist: https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json
Can't do schema validation without the schema.

**Comment by aeisenberg** [comment]
Hmmm...Looks like the `sarif-spec` repo went through a transition in September and removed the file. This is the commit where it was removed. https://github.com/oasis-tcs/sarif-spec/commits/c8abbbb043375b96a5c67fde642af46ad99a65d7

Thanks for raising this. The new and (hopefully) permanent [location is here](https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json).

**Comment by jacobmsft** [comment]
> Hmmm...Looks like the `sarif-spec` repo went through a transition in September and removed the file. This is the commit where it was removed. https://github.com/oasis-tcs/sarif-spec/commits/c8abbbb043375b96a5c67fde642af46ad99a65d7
> 
> Thanks for raising this. The new and (hopefully) permanent [location is here](https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json).

Sure, thanks for the quick response!

**Comment by edoardopirovano** [comment]
Thanks for noticing this! We've merged a fix in our development branch so that SARIF produced by CodeQL 2.8.2 onwards will now link to the new location of the schema.
