### ISSUE TITLE
CS8858 - false positive

### ISSUE THREAD

**Issue by sungam3r** [github/codeql#8132]
Error CS8858 The receiver type 'ErrorInfo' is not a valid record type:

https://github.com/graphql-dotnet/graphql-dotnet/security/code-scanning/661?query=ref%3Arefs%2Fheads%2Fdevelop

C# 10 allows `with` keyword for structs (only for records before).

**Comment by RasmusWL** [comment]
Hi, thanks for raising this. I've forwarded this to the C# team to take a look at :+1:

**Comment by michaelnebel** [comment]
Maybe I am not reading the the content of the link correctly, but it looks like the error was detected in December and then "disappeared" around one month ago.
This sounds plausible as it was around this time, large parts of the support for C#10 / .NET6 had been completed, which is required for using "with" expression on structs.

In any case, I tried to reproduce locally, but the query in question did not find any compile error in the following example, which looks very similar to the reported case:
```csharp
    public struct ErrorInfo
    {
        public string Message;
        public System.Collections.Generic.IDictionary<string, object?>? Extensions;
    }

    public interface IErrorInfoProvider
    {
        ErrorInfo GetInfo();
    }

    public class ErrorInfoProvider : IErrorInfoProvider
    {
        public virtual ErrorInfo GetInfo()
        {
            return new ErrorInfo() { Message = "hello" };
        }
    }

    internal class TestErrorInfoProvider : ErrorInfoProvider
    {
        public override ErrorInfo GetInfo()
        {
            return base.GetInfo() with
            {
                Extensions = new System.Collections.Generic.Dictionary<string, object>
                {
                    { "violations", new object()}
                }
            };
        }
    }
```

**Comment by sungam3r** [comment]
Thanks. If I see this error again, I will reopen that issue.
