### ISSUE TITLE
[JS] Modifying query predicates `nodes` based on sink node 

### ISSUE THREAD

**Issue by Naman-ntc** [github/codeql#8163]
I want to modify the nodes set returned by my query based on the sink nodes selected. 
For instance, say in SQL injection, corresponding to a sink node, I want to find the database library (Postgres vs MySQL vs MSSQL) that was used to instantiate the `query(...)` function where the sink node was an argument. 

------
```
const pgp = require('pg-promise')();
const db = pgp(process.env['DB_CONNECTION_STRING']);
source = req.query.taint
sink = source
db.query(sink)
```
So, in the above example, apart from the normal dataflow edges (`req.query.taint`, `source`, and `sink`), I also want to store the information that it was `pgp` or `pg-promise` library.

------
I can imagine doing this recursively in a predicate where 
* the base case of recursion calls the `cfg.hasFlowPath(...)` to find the sink and 
* then recursively finds predecessors corresponding to the sink. 

However, this seems very expensive as we redoing the `cfg.hasFlowPath(...)` computation. What would be an appropriate way to implement this?

**Comment by RasmusWL** [comment]
Hi @Naman-ntc, can you highlight what problem you are trying to solve?

We've generally not designed our libraries to make this sort of thing easy to achieve, so knowing what you will actually use this for, might help us find a better solution.

I took a stab at doing this for your example of SQL injection (although I'm not an expert on the JS libs), but that does not nessecarily translate to work on all queries. With this I was able to find 48/50 results from our tests in `javascript/ql/test/query-tests/Security/CWE-089/untyped/`.

```codeql
import javascript

DatabaseAccess getDbAccessForSqlString(SQL::SqlString sqlString) {
  result.getAQueryArgument().asExpr() = sqlString
}

query predicate sqlStringsNotCovered(SQL::SqlString sqlString) {
  not exists(getDbAccessForSqlString(sqlString))
  or
  not exists(API::Node apiNode | apiNode.getACall() = getDbAccessForSqlString(sqlString))
}

from SQL::SqlString sqlString, DatabaseAccess dbAccess, API::Node calledNode, API::Node moduleNode
where
  dbAccess = getDbAccessForSqlString(sqlString) and
  calledNode.getACall() = dbAccess and
  moduleNode = calledNode.getAPredecessor*() and
  moduleNode.getAPredecessor() = API::root()
select dbAccess, sqlString, calledNode, moduleNode
```

results looks like

![image](https://user-images.githubusercontent.com/1054041/155154156-48ef88a3-7a4a-4feb-994d-1bea8fcb35ca.png)

**Comment by RasmusWL** [comment]
I think the overall response will be the same as for https://github.com/github/codeql/discussions/7888 -- that it's not something we designed our queries for, so there is no easy way to do it.

I'll try to ping the JS team to see if I overlooked something though. (but don't get your hopes up)

**Comment by Naman-ntc** [comment]
Actually, I was trying to go over the default `PathGraph::edges` and `PathGraph::nodes` definitions (which might be specific to JS libs). It uses the `MidPathNode` and `PathSummary` classes that I believe allow it to reuse the computations performed while executing the `hasFlowPath` predicate. 
I will try to see if something can be hacked around for my case and get back here (or in a new issue!).

**Comment by Naman-ntc** [comment]
Okay, so after removing the private from `DataFlow::isSinkNode` predicate, (I believe) I was able to reuse the computation done in the main query. Specifically, I added
```codeql
query predicate nodes2(DataFlow::Node nd){
  exists(SqlInjection::Configuration cfg, DataFlow::Node sinkNode, DataFlow::CallNode call |
    DataFlow::isSinkNode(sinkNode, cfg, _) and 
    sinkNode = call.getAnArgument() and // not complete because sql query sometimes is argument inside an object
    nd = call.getReceiver() // in db.run(query) call finds `db`
  ) or
  exists(DataFlow::Node nd2 | nodes2(nd2) and nd2 = nd.getASuccessor()) // recurisively finds predecessors
}
```
However, that solution does not work correct because for instance in the following mysql example, the predecessor recursion stops at `connection` Node!
```js
pool.getConnection(function(err, connection) {
    connection.query({
        sql: 'SELECT * FROM `books` WHERE `author` = ' + temp,
    }, function(error, results, fields) {});
});
```
-----
Therefore, I used the `getDbAccessForSqlString` function you used and related it with the `sinkNode` (I am not sure if this method is better compared to what you did)
```codeql
DatabaseAccess getDbAccessForSqlString(SQL::SqlString sqlString) {
  result.getAQueryArgument().asExpr() = sqlString
}

query predicate nodes3(DataFlow::Node nd, DatabaseAccess db){
  exists(SQL::SqlString str, SqlInjection::Configuration cfg, DataFlow::Node sinkNode, DataFlow::CallNode call |
    DataFlow::isSinkNode(sinkNode, cfg, _) and 
    nd = str.flow() and
    db = getDbAccessForSqlString(str)
  ) 
}
```

Would appreciate feedback on the approach or alternative ideas to try out. 
Thanks!
