### ISSUE TITLE
[ruby] setting custom sources

### ISSUE THREAD

**Issue by Ludgershall** [github/codeql#8201]
Hello, 

I would like to create custom source types according to AST nodes in my ruby files instead of using those from the standard library (RemoteFlowSources, etc..).

I've come up with the following script but it doesn't return anything.
I'd like it to return `DataFlow::PathNode`s that correspond to, in this case, a `VariableAccess` (defined in `ruby/ast/Variable.qll`). I noticed that `VariableAccess` extended `Expr` so I assumed that comparing 2 `Expr` would yield positive results but no luck.

Any idea what I'm missing? Thank you and have a great day.

```codeql
/**
 * @name Testing.
 * @kind problem
 * @problem.severity warning
 * @id rb/variable-access
 * @precision low
 */

import ruby
import codeql.ruby.DataFlow

class VariableAccessNode extends DataFlow::PathNode {
    VariableAccessNode() {this.getNode().asExpr().getExpr() instanceof VariableAccess}
}

from VariableAccessNode source
select source, "Node is " + source.getNode()

```

**Comment by RasmusWL** [comment]
`DataFlow::PathNode` is only used together with data flow or taint-tracking configurations, and _Only those `PathNode`s that are reachable from a source are generated_.

Can you try using a `DataFlow::Node` instead?

**Comment by Ludgershall** [comment]
Oh it works, thank you very much
