### ISSUE TITLE
Ran with database overwriting enabled, but the directory does not appear to be a CodeQL database or database cluster

### ISSUE THREAD

**Issue by CaledoniaProject** [github/codeql#8413]
I'm creating a java database but maven fails:

```
codeql database create log4j-database -l=java -c="mvn clean install -file pom.xml -Dmaven.test.skip=true" --overwrite
```

When I run it again I got:

```
A fatal error occurred: Ran with database overwriting enabled, but the directory does not appear to be a CodeQL database or database cluster. Please check you do indeed wish to delete it, and do so manually.
```

When maven fails, codeql would fail to determine if it's a codeql database. That looks like a bug to me.

Here's the contents of log4j-database directory:

```
%> ls log4j-database/ -R
log4j-database/:
./  ../  log/  trap/
````

**Comment by smowton** [comment]
Can't reproduce this if I use `-c false` for a failing command. I'm using CodeQL CLI 2.8.2. What version are you using, and can you reproduce the problem using `-c false`? If not, what is the nature of the Maven failure that does reproduce this?

**Comment by hvitved** [comment]
I also tried to reproduce, and it works fine for me locally. Does the same thing happen if you first manually remove `log4j-database`, and then run the `database create` command twice?

**Comment by CaledoniaProject** [comment]
This happens every time in my environment:

1. Install jdk-17.0.2 on Mac
2. Download log4j source code: https://github.com/apache/logging-log4j2/archive/refs/tags/rel/2.11.0.zip
3. Run this command: codeql database create log4j-database -l=java -c="mvn clean install -file pom.xml -Dmaven.test.skip=true" --overwrite

And to reproduce the problem:
1. mkdir -p log4j-database/{log,trap}
2. codeql database create log4j-database -l=java -c="mvn clean install -file pom.xml -Dmaven.test.skip=true" --overwrite

**Comment by wac84s** [comment]
I am getting the same error reported above when using codeQL gitaction.  Our runners dont clean up after themself always so passed the overwrite.  Does the overwrite require a db to be there?  Some runners wont be dirty.


`Exit code was 2 and error was: A fatal error occurred: Ran with database overwriting enabled, but the directory does not appear to be a CodeQL database or database cluster. Please check you do indeed wish to delete it, and do so manually.
`
