### ISSUE TITLE
Detecting  C-style variadic function

### ISSUE THREAD

**Issue by MFaisalZaki** [github/codeql#8468]
I am trying to detect a C-style variadic function to cover SEI CERT [DCL50-CPP](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL50-CPP.+Do+not+define+a+C-style+variadic+function) rule, but it fails to detect such a pattern.

```
#include <cstdarg>
 
int add(int first, int second, ...) {
  int r = first + second; 
  va_list va;
  va_start(va, second);
  while (int v = va_arg(va, int)) {
    r += v;
  }
  va_end(va);
  return r;
}
```

**Comment by jketema** [comment]
Hi @MFaisalZaki 

Thanks for your question. I'm not completely sure what you're trying to detect. Are you trying to detect all variadic functions, like `add` in your example? If so, the CodeQL `Function` class has the `isVarargs` predicate. So to find all variadic functions, you can write a query like
```codeql
from Function f
where f.isVarargs()
select f
```
Does that help?

**Comment by MFaisalZaki** [comment]
@jketema Yes, I was trying to parse it myself. Thanks a lot for your help.
