### ISSUE TITLE
LGTM.com - false positive - [cs/comparison-of-identical-expressions]

### ISSUE THREAD

**Issue by DaveSkender** [github/codeql#8504]
**Description of the false-positive**

This one is fairly obvious in this check to avoid `div/0`.  `High` and `Low` are never assigned the same value.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/DaveSkender/Stock.Indicators/snapshot/f27f431046511d7ed60a76e79cb82d5e219a441f/files/src/a-d/Bop/Bop.cs?sort=name&dir=ASC&mode=heatmap#xc0fdb35fd14d7e8:1

```csharp
double?[] raw = quotesList
    .Select(x => (x.High != x.Low) ?
        (double?)((x.Close - x.Open) / (x.High - x.Low)) : null)
    .ToArray();
```

**Comment by hvitved** [comment]
Hi

It looks like the alert you have linked to is from an old run, if you instead look at the latest state of the file there are actually no alerts: https://lgtm.com/projects/g/DaveSkender/Stock.Indicators/latest/files/src/a-d/Bop/Bop.cs?sort=name&dir=ASC&mode=heatmap.

By the way, you may want to remove [these two lines](https://github.com/DaveSkender/Stock.Indicators/blob/main/.lgtm.yml#L7-L8), which tag all your code as (3rd party) library code, and alerts are therefore not shown by default.

**Comment by DaveSkender** [comment]
Seems odd as, as I don’t think there were meaningful changes between runs.  It’s nuclear why it initially alerted.  I’ll keep an eye on it.
