### ISSUE TITLE
CodeQL for Go language guide has broken links

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/codeql#8513]
https://codeql.github.com/docs/codeql-language-guides/modeling-data-flow-in-go-libraries/ aka https://github.com/github/codeql/blob/main/docs/codeql/codeql-language-guides/modeling-data-flow-in-go-libraries.rst has broken links such as:
- https://github.com/github/codeql-go/tree/main/ql/src/semmle/go/frameworks
- https://github.com/github/codeql-go/blob/main/ql/src/semmle/go/Concepts.qll

I don't know if there are additional broken links in the Go guide, but it is possible that there are further broken links in the Go guide **and** in other guides, because the breakage seems to have been caused by the package restructering into `ql/src` and `ql/lib`.
For Go, these links should have been broken for half a year:
https://github.com/github/codeql-go/pull/566

**Comment by smowton** [comment]
Thanks, fixed at https://github.com/github/codeql/pull/8528
