### ISSUE TITLE
Is there any way to see the data flow graph of the query results? 

### ISSUE THREAD

**Issue by ernongxizhu** [github/codeql#8527]
Is there any way to see the data flow graph of the query results? 

I want to see the calling relationship of each function.

I have defined a data flow analysis. I want to display the path information from sink to source so that I can see the calling relationship between various functions.

**Comment by fakhrinail** [comment]
Did you figure out how to do this?

**Comment by smowton** [comment]
Does using `@kind path-problem` and `import DataFlow::PathGraph` as described at https://codeql.github.com/docs/writing-codeql-queries/creating-path-queries/ provide enough insight into the shape of the dataflow graph, or are you hoping for something more detailed? If so, could you give an example of what you're hoping for?
