### ISSUE TITLE
When I execute the following query in LGTM, I will be stuck at 61%, and the execution will fail later

### ISSUE THREAD

**Issue by ernongxizhu** [github/codeql#8545]
codeql database：Uranusboy/log4j2-test
[URL：](https://lgtm.com/projects/g/Uranusboy/log4j2-test/alerts/?mode=list)

When I execute the following query in LGTM, I will be stuck at 61%, and the execution will fail later
![image](https://user-images.githubusercontent.com/73651912/159886762-5323ca9b-16fb-4897-a85a-f93ada6d0b43.png)
![image](https://user-images.githubusercontent.com/73651912/159900347-1c585101-74f2-4cd6-b613-9202a2b5ce77.png)

```
import java
import semmle.code.java.dataflow.FlowSources
import DataFlow::PathGraph
class Context extends  RefType{
    Context(){
        this.hasQualifiedName("javax.naming", "Context")
        or
        this.hasQualifiedName("javax.naming", "InitialContext")
    }
}

predicate isLookup(Expr arg) {
    exists(MethodAccess ma |
        ma.getMethod().getName() = "lookup"
        and
        ma.getMethod().getDeclaringType() instanceof Context
        and
        arg = ma.getArgument(0)
    )
}

class TainttrackLookup  extends TaintTracking::Configuration {
    TainttrackLookup() { 
        this = "TainttrackLookup" 
    }

	override predicate isSource(DataFlow::Node source) { none() }
    override predicate isSink(DataFlow::Node sink) {
        exists(Expr arg |
            isLookup(arg)
            and
            sink.asExpr() = arg
        )
    }
	override int explorationLimit() { result = 17 }
} 
from TainttrackLookup config, DataFlow::PartialPathNode sink,DataFlow::PartialPathNode node
where 
	config.hasPartialFlowRev(node,sink,17)
select sink.getNode(),node.getNode()
```

**Comment by tausbn** [comment]
Assuming this works for lower `explorationLimit`s, my best guess would be that `17` is just too high a level, and that it times out before it can calculate the entire graph. 

You may have better luck downloading the database and running it locally using either the VSCode extension (recommended) or the CodeQL CLI.

**Comment by ernongxizhu** [comment]
> Assuming this works for lower `explorationLimit`s, my best guess would be that `17` is just too high a level, and that it times out before it can calculate the entire graph.
> 
> You may have better luck downloading the database and running it locally using either the VSCode extension (recommended) or the CodeQL CLI.

But I am very slow to execute locally, and even feel stuck. Is it because my memory is too small or CPU is too small

**Comment by ernongxizhu** [comment]
> Assuming this works for lower `explorationLimit`s, my best guess would be that `17` is just too high a level, and that it times out before it can calculate the entire graph.
> 
> You may have better luck downloading the database and running it locally using either the VSCode extension (recommended) or the CodeQL CLI.

Can you run this script successfully?

**Comment by tausbn** [comment]
I tried running your query locally (on a fairly beefy machine) and I don't think there's much hope that it'll finish with an `explorationLimit` of 5 or above.

Perhaps you could limit the number of sinks you're defining? I assume you're using partial flow because you're not finding the results you're expecting for the query, and you want to figure out where the flow stops.

**Comment by ernongxizhu** [comment]
> I tried running your query locally (on a fairly beefy machine) and I don't think there's much hope that it'll finish with an `explorationLimit` of 5 or above.
> 
> Perhaps you could limit the number of sinks you're defining? I assume you're using partial flow because you're not finding the results you're expecting for the query, and you want to figure out where the flow stops.

thank you for answer

I do think so, but I don't know what to do.

**Comment by ernongxizhu** [comment]
> I tried running your query locally (on a fairly beefy machine) and I don't think there's much hope that it'll finish with an `explorationLimit` of 5 or above.
> 
> Perhaps you could limit the number of sinks you're defining? I assume you're using partial flow because you're not finding the results you're expecting for the query, and you want to figure out where the flow stops.

I think I may know why.
Codeql doesn't have multi-core optimization, so even a well configured computer can't process these data.
