### ISSUE TITLE
Java: `SwitchCase.getRuleExpression()` has no result for `switch` statements

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#8570]
CodeQL's `SwitchCase.getRuleExpression()` seems to be intended to model `switch` rules (`... -> ...`) where the right side is `Expression;` ([JLS 17 §14.11.1](https://docs.oracle.com/javase/specs/jls/se17/html/jls-14.html#jls-14.11.1)). This works correctly for `switch` expressions, but for `switch` statements this CodeQL predicate does not have a result. Instead there the right side is modelled as `ExprStmt` in this case.

Example query:
```ql
import java

from SwitchStmt s, Top e
where
    e = s.getACase().getRuleExpression()
    or e = s.getACase().getRuleStatement()
select s, e, e.getPrimaryQlClasses()
```
ℹ️ `getRuleExpression()` has no results and instead `getRuleStatement()` has `ExprStmt` entities as result.

This behavior is inconsistent and possibly also incorrect. [JLS 17 §14.11.2](https://docs.oracle.com/javase/specs/jls/se17/html/jls-14.html#jls-14.11.2) explicitly covers this case, saying:
> Every switch rule expression in the switch block is a statement expression ([§14.8](https://docs.oracle.com/javase/specs/jls/se17/html/jls-14.html#jls-14.8))

Notice that it says "statement *expression*". While this sounds similar to "expression *statement*" (as which CodeQL currently models it), they are separate concepts; a statement *expression* is contained within an expression *statement*.

If this behavior of CodeQL is considered intended, it might be good to mention this in the documentation of `getRuleExpression()` to avoid incorrect behavior when users assume `getRuleExpression()` will have results and `getRuleStatement()` will only have block statements or `throw` statements as result.

**Comment by smowton** [comment]
How about https://github.com/github/codeql/pull/8611

I think intuitively the idea that the RHS is either directly an expression or a block containing yield statements is likely to make sense to users, even if the JLS contains text about statement expressions.
