### ISSUE TITLE
Java: `any(Method m).isFinal()` returns `false` for static methods

### ISSUE THREAD

**Issue by JLLeitschuh** [github/codeql#8594]
**Description of the false positive**

The documentation for `Modifiable.isFinal()` is the following:

```
/** Holds if this element has a `final` modifier or is implicitly final. */
```

For methods, that are `static` can be considered implicitly final, IE. they can't be overridden. As such, `Method` should override `isFinal()` to check if the method is declared `final` or is `static`.

**Comment by intrigus-lgtm** [comment]
`static` methods are not implicitly `final`.

Run these two snippets in `jshell`:
```java
public class Foo {
    public static final void test() {System.out.println("Foo");}
}
```
```java
public class Bar extends Foo {
    public static void test() {System.out.prinltn("Bar");}
}
```
**You will get a compilation error:**
> |  Error:
|  test() in Bar cannot override test() in Foo
|    overridden method is static,final
|      public static void test() {System.out.println("Bar");}
|      ^----------------------------------------------------^

If you remove the `final` modifier from the `Foo.test` method, you will not get a compilation error.
Therefore, `static` methods should not be treated as implicitly `final` by CodeQL as far as I understand this.

**Comment by JLLeitschuh** [comment]
🤔  maybe a new predicate, like `isOverrideable` would be useful here then instead? Something that includes checks for `isFinal` `isStatic` and `isPrivate`. Something to convey that, the method declared will be what is executing because there's no way other logic can override it's execution.

**Comment by atorralba** [comment]
[`isOVerridable` already exists](https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/Member.qll#L448). It actually does what you want: it holds if the method is virtual (i.e. not private nor static), not final and it isn't declared in a final class.
