### ISSUE TITLE
Java: Query compilation can fail without location

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#8663]
### Version
CodeQL extension version: 1.6.1
CodeQL CLI version: 2.8.4
Platform: win32 x64

CodeQL commit https://github.com/github/codeql/commit/3119885a9b21951aafac88e01c946b3e7cfbe163

### Description
It appears certain queries can cause the compilation to fail without any location information (`Compiler Generated:-1:-1:-1:-1`). In this case the Query Console on LGTM.com says "Unable to perform linting but query can still be run", which then results in "Failed to execute". The VS Code extension shows no error at all (should I raise that as separate issue on that repo?), but executing the query fails.

Query:
```ql
import java

query predicate test(RefType t) { t.inherits(t) }
```

Fails with:
```
ERROR: Type::RefType.extends#6144c3fd incompatible with (<compiler generated node> /\ Member::Member) \/ (<compiler generated node> /\ Member::Member) (Compiler Generated:-1:-1:-1:-1)
```

Interestingly, modifying the query slightly still results in a cryptic error message, but this time includes location information:
```ql
import java

query Member test(RefType t) { t.inherits(result.(RefType)) }
```

Error message / logged error:
```
ERROR: Type::RefType.extends#6144c3fd incompatible with (<compiler generated node> /\ Member::Member) \/ (<compiler generated node> /\ Member::Member) (#REDACTED#\quick-queries\quick-query.ql:3:47:3:53)
```

**Comment by alexet** [comment]
Thanks for reporting this. 

This is a bug in codeql. I have reproduced and I have a fix.

**Comment by alexet** [comment]
The fixes are now merged. They should be released in a future version of codeql (probably 2.9.0).
