### ISSUE TITLE
Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by greenpau** [github/codeql#8712]
**Description of the issue**

The job fails with the following error:

```
Error: Cannot create a string longer than 0x1fffffe8 characters
```

Config file is vanilla: https://github.com/greenpau/go-authcrunch/blob/main/.github/workflows/codeql.yml

![image](https://user-images.githubusercontent.com/3826416/162626716-809abb5d-f3cd-40f2-b884-a3b0703197e5.png)

**Comment by greenpau** [comment]
The config was missing autobuild:

```
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
```

**Comment by greenpau** [comment]
Actually, the issue re-appeared again.

**Comment by aibaars** [comment]
Thanks for the report. The exception originates from the `github/codeql-action`. In [upload-lib.ts(line 269)](https://github.com/github/codeql-action/blob/baf90d17d2dff1411edbc33429becd4afaecd4ab/src/upload-lib.ts#L269) it attempts to read the entire contents of the SARIF file containing the analysis results. The SARIF file is somehow really larges and exceeds to limits on the size of a Javascript string.

The error message isn't very user friendly and should be improved. However, if a SARIF file has over `0x1fffffe8 characters` (512 MB) it exceeds the limits imposed by the [CodeScanning Upload API](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github). 

To further debug the issue we'd need to find out why the SARIF file is that large. You could do the following:
* set [`upload: false`]( https://github.com/github/codeql-action/blob/baf90d17d2dff1411edbc33429becd4afaecd4ab/analyze/action.yml#L12-L15) for the `codeql-action/analyze` step
* upload the SARIF file using `action/upload` instead
  ```
   - uses: actions/upload-artifact@v3
     with:
       name: go.sarif
       path: results/go.sarif"
   ```
* set [`debug: true'](https://github.com/github/codeql-action/blob/main/init/action.yml#L58-L61) for the `codeql-action/init` step

**Comment by greenpau** [comment]
> upload the SARIF file using action/upload instead

Logs attached: [logs_115.zip](https://github.com/github/codeql/files/8464203/logs_115.zip)


@aibaars , I followed your guidance. I get the following warning. (fyi, fixed typo with the single `"` quote in your example, but it did not change the warning.)

```
Run actions/upload-artifact@v3
Warning: No files were found with the provided path: results/go.sarif. No artifacts will be uploaded.
```

Prior to that I can see:

```
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "debug-artifacts-go" successfully created. Starting upload of file(s)
Uploaded /home/runner/work/go-authcrunch/results/go.sarif (67.0%) bytes 0:8388607
Uploaded /home/runner/work/go-authcrunch/results/go.sarif (100.0%) bytes 8388608:12509191
```

The is also a message about the size:

```
The raw size of all the files that were specified for upload is 22584518 bytes
The size of all the files that were uploaded is 1203645 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage

Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 
```

**Comment by greenpau** [comment]
> 1100 results should normally be smaller than 687MB though. Most likely there are a lot of dataflow paths attached to those alerts.

@aibaars , there a file where a lot of logging happens. Hence the below:

```
    529       "ruleId" : "go/clear-text-logging",
    596       "ruleId" : "go/log-injection",
```

I will try it out. Will start with `1`.

**Comment by greenpau** [comment]
@aibaars , I am running into the following error:

```
Invalid pattern '../results/go.sarif'. Relative pathing '.' and '..' is not allowed.
```

**Comment by greenpau** [comment]
> Invalid pattern '../results/go.sarif'. Relative pathing '.' and '..' is not allowed.

Here is what worked.

```
    - name: Upload CodeQL Analysis
      uses: actions/upload-artifact@v3
      with:
        name: go.sarif
        path: ${{runner.workspace}}/results/go.sarif
```

@aibaars , I do not see any updates to scan results in my repo.
