### ISSUE TITLE
License hint in README.md violates MIT license

### ISSUE THREAD

**Issue by berndschatz** [github/codeql#8716]
**Description of the issue**

With 
commit d9826c571a253015144299641aa7182e6dc37229
Date:   Thu May 13 13:17:16 2021 +0100

The license hint in the README.md was extended:

-The code in this repository is licensed under the [MIT License](LICENSE) by [GitHub](https://github.com).
+The code in this repository is licensed under the [MIT License](LICENSE) by [GitHub](https://github.com). The use of CodeQL on Open source code is licensed under specific [Terms & Conditions](https://securitylab.github.com/tools/codeql/license/) UNLESS you have a commercial license in place. If you'd like to use CodeQL with a commercial codebase, please [contact us](https://enterprise.github.com/contact) for further help.

Does this additional restriction of usage not violate the MIT license ? 
Please check and clarify or remove it again.

**Comment by aibaars** [comment]
Thanks for raising this issue. The intention of the additional sentence is to clarify that even though the QL queries and other files in this repository are open source code licensed under the MIT license, the CodeQL CLI (https://github.com/github/codeql-cli-binaries) has usage restrictions.

**Comment by berndschatz** [comment]
now it is clear, thx
