### ISSUE TITLE
Add codeql bundle in existing docker: Exception caught at top level: IOException while executing process with args

### ISSUE THREAD

**Issue by Nikoms** [github/codeql#8753]
Hello,

I'm trying to add codeql to an existing docker image that will (in summary) pull a repository every x hours and run some `.ql` queries on it to see how it evolves.

In our `Dockerfile`, there is not so much:
- We are using a simple `from node:15` 
- I added `RUN wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz`and `RUN tar -xvzf ./codeql-bundle-linux64.tar.gz`

Then in "js" I use `require('child_process').exec` to create the database with `codeql database create --language=javascript --source-root ${serverSrcDir} ${serverCodeQLDatabaseDir} --overwrite`

I end up with this error (from the logs):
```
Exception caught at top level: IOException while executing process with args: [/app/codeql/tools/linux64/scc, --format, json]
                      (eventual cause: IOException "error=0, Failed to exec spawn helper: pid: 143, exit value: 1")
                      com.semmle.util.process.AbstractProcessBuilder.execute(AbstractProcessBuilder.java:258)
                      com.semmle.util.process.AbstractProcessBuilder.execute(AbstractProcessBuilder.java:198)
                      com.semmle.cli2.database.loc.LocCounter.run(LocCounter.java:66)
                      com.semmle.cli2.database.loc.LocCounter.count(LocCounter.java:93)
                      com.semmle.cli2.database.InitCommand.executeSubcommand(InitCommand.java:185)
                      com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:110)
                      com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:162)
                      com.semmle.cli2.database.CreateCommand.executeSubcommand(CreateCommand.java:84)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:500)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:214)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:98)

                       ... caused by:

                      java.io.IOException: Cannot run program "/app/codeql/tools/linux64/scc" (in directory "/app/codeql/server/src"): error=0, Failed to exec spawn helper: pid: 143, exit value: 1
                      java.base/java.lang.ProcessBuilder.start(Unknown Source)
                      java.base/java.lang.ProcessBuilder.start(Unknown Source)
                      com.semmle.util.process.AbstractProcessBuilder.execute(AbstractProcessBuilder.java:231)
                      com.semmle.util.process.AbstractProcessBuilder.execute(AbstractProcessBuilder.java:198)
                      com.semmle.cli2.database.loc.LocCounter.run(LocCounter.java:66)
                      com.semmle.cli2.database.loc.LocCounter.count(LocCounter.java:93)
                      com.semmle.cli2.database.InitCommand.executeSubcommand(InitCommand.java:185)
                      com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:110)
                      com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:162)
                      com.semmle.cli2.database.CreateCommand.executeSubcommand(CreateCommand.java:84)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:500)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:214)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:98)

                       ... caused by:

                      java.io.IOException: error=0, Failed to exec spawn helper: pid: 143, exit value: 1
                      java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
                      java.base/java.lang.ProcessImpl.<init>(Unknown Source)
                      java.base/java.lang.ProcessImpl.start(Unknown Source)
                      java.base/java.lang.ProcessBuilder.start(Unknown Source)
                      java.base/java.lang.ProcessBuilder.start(Unknown Source)
                      com.semmle.util.process.AbstractProcessBuilder.execute(AbstractProcessBuilder.java:231)
                      com.semmle.util.process.AbstractProcessBuilder.execute(AbstractProcessBuilder.java:198)
                      com.semmle.cli2.database.loc.LocCounter.run(LocCounter.java:66)
                      com.semmle.cli2.database.loc.LocCounter.count(LocCounter.java:93)
                      com.semmle.cli2.database.InitCommand.executeSubcommand(InitCommand.java:185)
                      com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:110)
                      com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:162)
                      com.semmle.cli2.database.CreateCommand.executeSubcommand(CreateCommand.java:84)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:500)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:214)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:98)

```

Do I need to install more things in my docker image? I'm running docker on mac m1 and I added `--platform=linux/amd64` to make it "work" first.

Thank you for your help

**Comment by aibaars** [comment]
Thanks for the report. The scc binary is used for counting lines of code and is not essential. It possibly requires some shared library that is not available in the Docker image .

You could try installing the missing libraries .  There might also be a command line option to skip counting lines. Alternatively you could replace the scc binary with a script that simple returns an empty json object.

**Comment by intrigus-lgtm** [comment]
Searching for
> Failed to exec spawn helper:

yields 
https://stackoverflow.com/questions/61301818/java-failed-to-exec-spawn-helper-error-since-moving-to-java-14-on-linux so this seems to be related to your java distribution.

**Comment by aibaars** [comment]
Thanks a lot for that link @intrigus-lgtm . According to that link the problem may be due to `jspawnhelper`.
> Essentially in Java 11 Linux uses vfork to start processes but by Java 13 it now uses posix_spawn.
>
> posix_spawn actually requires a program called jspawnhelper that is located within jre/lib. In my case this exists but it does not have execute permissions, this is because I use jlink to build a jre that just has the system modules I need, but I create this on Windows (my main dev environment).

@Nikoms Could you check that `codeql/tools/linux64/java/lib/jspawnhelper` has the right permissions and works as expected in your docker image? 

You can also install a JDK in your docker image and set the environment variable `CODEQL_JAVA_HOME` to the path of that JDK. Alternatively, you can replace `codeql/tools/linux64/java` with a copy of a JDK that works for you.

**Comment by Nikoms** [comment]
Thanks for all your answers. Sorry for the later answer, I was sick last week :( 

@aibaars I've checked and `/app/codeql/tools/linux64/java/lib/jspawnhelper` has execute permission. But What is interesting is that I can run the command `/app/codeql/tools/linux64/scc ./kpi/codeql/server/src` without any problem. But when I do `/app/codeql/codeql database create --language=javascript --source-root ./kpi/codeql/server/src ./database`

I have this:
```
This command is not for general use and should only be run as the result of a call to
ProcessBuilder.start() or Runtime.exec() in a java application
A fatal error occurred: IOException while executing process with args: [/app/codeql/tools/linux64/scc, --format, json]
(eventual cause: IOException "error=0, Failed to exec spawn helper: pid: 487, exit value: 1")
```

**Comment by aibaars** [comment]
Ah that's interesting. That error message comes from the jspawnhelper. I think you get the same message if you run the jspawnhelper directly.  I wonder why it complains about not being run from ProcessBuilder.

**Comment by Nikoms** [comment]
It seems that it's a problem with M1 only (it's working on another machine). Let me close this because it's out of CodeQL scope :)

Thank you for your help @aibaars

**Comment by aibaars** [comment]
> Indeed, I have the same message. I see that it might come from M1. I tried the "fix" `JAVA_OPTS "-Djdk.lang.Process.launchMechanism=vfork"` but to luck for the moment

@Nikoms You can supply `java` arguments to `codeql` using the `-J` flag. Have you tried `codeql -J-Djdk.lang.Process.launchMechanism=vfork database create ...` ?

**Comment by Nikoms** [comment]
I didn't know about this flag 😅. I added it at the end of the command and it starts at least. But now I'm having:

```
[2022-04-26 15:45:30] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/app/codeql/javascript/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command: [/app/codeql/javascript/tools/autobuild.sh]
```

**Comment by Nikoms** [comment]
Sorry there was another error just before:

```

[2022-04-26 20:21:50] [build-stderr] Could not start Node.js. It is required for TypeScript extraction.
[2022-04-26 20:21:50] [build-stderr] Please install Node.js and ensure 'node' is on the PATH.
[2022-04-26 20:21:50] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/app/codeql/javascript/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command: [/app/codeql/javascript/tools/autobuild.sh]
```


Seems that node is not installed, but I'm in an official node docker image :D

**Comment by Nikoms** [comment]
FYI

```
# which node
/usr/local/bin/node
```

**Comment by ashkash22** [comment]
Try following this and restarting your docker instance:

docker-machine env --shell cmd default  or docker-machine env --shell=powershell | Invoke-Expression

SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\USER_NAME\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM @FOR /f "tokens=*" %i IN ('docker-machine env --shell cmd default') DO @%i

@FOR /f "tokens=*" %i IN ('docker-machine env --shell cmd default') DO @%i

'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon”
