### ISSUE TITLE
Failed to Generate Test Queries

### ISSUE THREAD

**Issue by MFaisalZaki** [github/codeql#8795]
I am trying to write test cases query, but the problem is that the extractor failed to compile the c++ because it failed to load an std include file. I have tried to add the `-stdlib=libc++` but I cannot figure out where to add it. I am attaching the complete test query along with the generated `testproj` dir.
[test-query.zip](https://github.com/github/codeql/files/8530596/test-query.zip)

**Comment by aeisenberg** [comment]
Can you show me the commands you are running to generate the database? Also, what OS are you on?

**Comment by MFaisalZaki** [comment]
I am using [vscode-codeql-starter](https://github.com/github/vscode-codeql-starter) and running it on macOS. Please note I am attaching the full folder structure just you can use it directly to regenerate the issue.

[Queries.zip](https://github.com/github/codeql/files/8532494/Queries.zip)

**Comment by aeisenberg** [comment]
It sounds like the problem is happening during extraction, which is unrelated to actually running the queries. Extraction is the process of creating a queryable database from your source code. 

In order to help you, I need to see the compile errors you are seeing, as well as the steps you are taking to create your database.

**Comment by MFaisalZaki** [comment]
I just add the `Queries` directory to `vscode` workspace then press on the Testing tab on the right then execute the `ctr/50` testcase.

**Comment by aeisenberg** [comment]
Thanks for the explanation. I'll try this out.

**Comment by aeisenberg** [comment]
Your best bet in this situation is to stub out the headers that you require. These are test cases and they are meant to be small snippets that exhibit explicit patterns in code. 

[Here is an example](https://github.com/github/codeql/blob/main/cpp/ql/test/library-tests/dataflow/taint-tests/stl.h) where we are doing the same. In this CodeQL test, the stl header is stubbed out. You can use this header in your tests and you will have to create similar stubs for other headers in your tests.
