### ISSUE TITLE
False Negatives - Prototype Pollution

### ISSUE THREAD

**Issue by dottif** [github/codeql#8846]
Hi, here are some prototype pollution false negatives.

### 1 Array / Rest parameters taint analysis
In the [extend function](https://github.com/eggjs/extend2/blob/ddefb57595a369eeec88d001786161389e1ee406/index.js#L64) from the extend2 package, if the parameters are accessed using ```arguments``` (first function) then CodeQL can detect the vulnerability. ([LGTM](https://lgtm.com/projects/g/dottif/prototype-pollution-static-analysis/snapshot/5d946562e24c36607c648e5d2e1540e08268e032/files/case_studies/extend2/index.js?sort=name&dir=ASC&mode=heatmap#x5c3dbd400bc04a82:1))
However if we implement the function using [rest parameters](https://lgtm.com/projects/g/dottif/prototype-pollution-static-analysis/latest/files/case_studies/extend2/index-rest.js?sort=name&dir=ASC&mode=heatmap#L64), or by directly passing an array (third function), the query won’t detect the vulnerability.
```javascript
function extend(){ //ok
  var target = arguments[0];
  target[name] = extend(deep, clone, copy);
}

function extend(...args){ //false negative
  var target = args[0];
  target[name] = extend(deep, clone, copy);
}

function extend(args){ //false negative
  var target = args[0];
  target[name] = extend([deep, clone, copy]);
}
```
### 2 Js-data deepFillIn
This vulnerability is not reported: [LGTM](https://lgtm.com/projects/g/dottif/prototype-pollution-static-analysis/snapshot/5d946562e24c36607c648e5d2e1540e08268e032/files/case_studies/js-data/utilsmod.js?sort=name&dir=ASC&mode=heatmap#L55)
### 3 Mutiny
Also this one is a false negative [LGTM](https://lgtm.com/projects/g/dottif/prototype-pollution-static-analysis/latest/files/case_studies/mutiny/mutiny-original.js)
###### source: https://github.com/BlackFan/client-side-prototype-pollution/blob/master/pp/mutiny.md

**Comment by kaeluka** [comment]
Thank you for that issue, @dottif! You've provided very thorough documentation.

As a first step, I have confirmed that there seems to be a bug. In the three snippets below, we catch the first one, but not the others.

```javascript
function copyUsingForInAndArguments() {
    const dst = arguments[0];
    const src = arguments[1];
    for (let key in src) {
        if (dst[key]) {
            copyUsingForInAndArguments(dst[key], src[key]);
        } else {
            dst[key] = src[key]; // NOT OK
        }
    }
}

function copyUsingForInAndRest(...args) {
    const dst = args[0];
    const src = args[1];
    for (let key in src) {
        if (dst[key]) {
            copyUsingForInAndRest(dst[key], src[key]);
        } else {
            dst[key] = src[key]; // NOT OK
        }
    }
}

function copyUsingForInAndArray(args) {
    const dst = args[0];
    const src = args[1];
    for (let key in src) {
        if (dst[key]) {
            copyUsingForInAndRest(dst[key], src[key]);
        } else {
            dst[key] = src[key]; // NOT OK
        }
    }
}
```

**Comment by kaeluka** [comment]
I've sent a PR that addresses the `...rest` parameters problem in function `copyUsingForInAndRest` (PR is linked above). The fix is deep in the flow steps implementation. The fix therefore could help with precision of other analyses. It looks like an excellent find 👍 .

I'll continue with `copyUsingForInAndArray` some other time.

**Comment by kaeluka** [comment]
Merged the first PR; I'm now trying to solve the `deepFillIn` case.
