### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by asportnoy** [github/codeql#8847]
This isn't _exactly_ a false positive, but I feel like this is the best place to report it. My JS formatter causes comments on lines that start blocks (like opening a function) to be wrapped to the next line. This is an issue as LGTM comments will only work if they are on the specific line that it wants, which in this case is at the start of a function. This could be solved by allowing the comment on the line above the error.

If this isn't the place to report this issue, please let me know where I should submit it instead.

[LGTM page](https://lgtm.com/projects/g/codeths/kitcoin/snapshot/668c5c4eb1df19f833bd2931933915853b69f1de/files/src/webserver/routes/auth.ts?sort=name&dir=ASC&mode=heatmap#x6217fb50451e9829:1)

**Comment by MathiasVP** [comment]
Thanks for the feedback. I'll bring it to the appropriate team.

As a quick workaround, could you try the following style for bypassing the formatter?
```js
async (req, res) => { /* lgtm [js/missing-rate-limiting] */
  handleLogin(req, res);
},
```

(I assume the alert appears on the `async` line?)

**Comment by asportnoy** [comment]
I tried that as well and had the same issue.

**Comment by asportnoy** [comment]
Yes, it also gets wrapped the same way.

**Comment by MathiasVP** [comment]
Hm. I guess we can get create with the placement of the comment then. Maybe:
```js
async (req, res) /* lgtm [js/missing-rate-limiting] */ => {
  handleLogin(req, res);
},
```
?
I get that this is an annoying workaround, but it might solve your issue until we have a better fix for this.

**Comment by asportnoy** [comment]
I can confirm this does not get wrapped. I can also put it at the start of the line and it will not get wrapped either. Would that still ignore the query though?

In this case I ended up just ignoring the whole query from my project in lgtm.yml since it doesn't apply to the project.

**Comment by MathiasVP** [comment]
Yes, as long as the comment is on the same line as the alert location it _should_ get suppressed.
