### ISSUE TITLE
No alerts generated

### ISSUE THREAD

**Issue by MFaisalZaki** [github/codeql#8940]
I have developed this rule: 

```

/**
 * @name cpp-ctr50.
 * @description Guarantee that container indices and iterators are within the valid range.
 * @id cpp/sei-cert/ctr/50
 * @kind problem
 * @problem.severity error
 * @precision very-high
 * @tags sei-security
 */

import cpp

predicate isAToolchainLocation(Location l) {
  l.getContainer().getParentContainer+().getBaseName().matches("Program Files (x86)")
}

predicate hasPossibleNegitiveIndexing(Element ele) {
  exists( ArrayExpr array_access | ele = array_access and 
                                   not (array_access.getArrayOffset().getType() instanceof Size_t or array_access.getArrayOffset().isConstant()) and
                                   not isAToolchainLocation(array_access.getArrayOffset().getLocation()))
  or
  exists( OverloadedArrayExpr index_operator | ele = index_operator and 
                                               not (index_operator.getArgument(0).(VariableAccess).getType() instanceof Size_t or index_operator.getArgument(0).isConstant()) and
                                               not isAToolchainLocation(index_operator.getLocation())
                                               )
}

from Element var
where hasPossibleNegitiveIndexing(var)
select var, "Their is a potential of negative value addressing invoked."

```

in order to detect those pattern:

```
void insert_in_table_ncf0(int *table, std::size_t tableSize, int pos, int value) {
  if (pos >= tableSize) {
    // Handle error
    return;
  }
  table[pos] = value;
}

void insert_in_table_ncf1(std::vector<int> &table, long long pos, int value) {
  if (pos >= table.size()) {
    // Handle error
    return;
  }
  table[pos] = value;
}
```

The problem is that the results shows correctly when the results tab is switched to the `#select` and it fails to generate alerts. The major problem is that I have integrated the mentioned rule in a suit and used it to analyze the database and yet it generates an empty `csv` file.

I tried to mix and match different metadata attributes yet with no success. 

![select-tab](https://user-images.githubusercontent.com/9129265/165743373-b38bac35-0e67-4989-b14b-cd614f8e1038.png)
![alerts-tab](https://user-images.githubusercontent.com/9129265/165743385-0c6916e0-fa48-4e9b-bcf0-b03989103b6d.png)

**Comment by MathiasVP** [comment]
Hi @MFaisalZaki,

The query results correctly show up in my `alerts` view. Do you get any error messages in the CodeQL Extension Log? You can find that by pressing the <img width="45" alt="Screenshot 2022-04-28 at 12 51 13" src="https://user-images.githubusercontent.com/4527323/165745943-b3377dba-06ea-4156-9f01-987bd4f9d847.png"> button on the lower left of your VSCode, and selecting the CodeQL Extension Log form the dropdown menu:

<img width="1413" alt="Screenshot 2022-04-28 at 12 52 38" src="https://user-images.githubusercontent.com/4527323/165746270-4f77f319-b9f4-44fa-987d-da63f6af113a.png">

**Comment by MFaisalZaki** [comment]
[log.log](https://github.com/github/codeql/files/8582467/log.log)

Here is the log file, also I cannot understand why it does not generate alerts when I execute this cli command:

```

codeql database analyze --ram=8000 --threads=4 --format="csv" --output="test.csv" samples-db-msvc-v3 CodeSecurity-Queries/cpp/ql/src/codeql-suites/sei-cert.qls --additional-packs CodeSecurity-Queries --additional-packs queries

```

**Comment by aibaars** [comment]
@MFaisalZaki Could you check the `sourceLocationPrefix:` field in ` samples-db-msvc-v3/codeql-database.yml`? If I recall correctly, the `codeql database analyze` command filters out alerts that are "outside" the source folder. Another thing to check is the ` samples-db-msvc-v3/src.zip` file which should contain copies of all the analysed source files. Alerts may also be filtered out if they were found in a file that is not in the `src.zip`.

**Comment by MFaisalZaki** [comment]
Hello @aibaars,

I am creating my database using `msvc` then I develop the queries on my mac. You are correct the `sourceLocationPrefix:` is different so what can I do to fix such an issue.

[Uploading samples-db-msvc-v3.zip…]()

**Comment by MFaisalZaki** [comment]
So can I change it by hand since the 'src' directory is different from the 'sourceLocationPrefix'? Or is there any way to do it automatically upon generating a database

**Comment by MFaisalZaki** [comment]
Sure,
[Archive.zip](https://github.com/github/codeql/files/8589545/Archive.zip)
Also, I would like to share with you the process I follow for generating the database. I generate an MSVC solution using CMake in a separate `build` directory, not within the source code/CMakeLists directory. Then I navigate to this directory `build` directory, followed by creating the database.

Sometimes I am forced to generate an MSVC solution in the same source directory to get it to work, but I don't think this is the proper way to do it.

**Comment by aibaars** [comment]
@MFaisalZaki I think the problem is that the `sourceLocationPrefix` ends with `x64-windows-dbg\\` and none of the source files are actually in that folder. Could you try removing the `x64-windows-dbg\\` part? I think this problem can be avoided by supplying the `-s, --source-root=<dir>` flag to `codeql database create`.

**Comment by MFaisalZaki** [comment]
@aibaars your suggestion worked. I will give the ‘-s’ option a try. Thanks a lot for your help.

**Comment by MFaisalZaki** [comment]
@aibaars things worked after I modified the value of `-s`. Thanks for your support.
