### ISSUE TITLE
[INVALID_RESULT_PATTERNS] for loop elements

### ISSUE THREAD

**Issue by MFaisalZaki** [github/codeql#8988]
I wrote a query that detects element `i` in the following code snippet as a possible overflow event:

```
void ncf0(const std::vector<int> &c) {
  for (auto i = c.begin(), e = i + 20; i != e; ++i) {
    std::cout << *i << std::endl;
  }
}
```

However, when running my query, it generates `[INVALID_RESULT_PATTERNS]` even though I have similar patterns, which works fine. I think the problem is that the parser cannot handle the loop's variables.

**Comment by intrigus-lgtm** [comment]
Can you post your full query or at least the `from` and `select` clause of your query?
Without either one, it will be hard to diagnose your problem.

**Comment by aibaars** [comment]
The error message means that the select clause of your query has the wrong shape with respect to the @kind specified at the top of the query

**Comment by MFaisalZaki** [comment]
Sure this is the query I am using 

```
/**
 * @name cpp-ctr55
 * @description Do not use an additive operator on an iterator if the result would overflow.
 * @id cpp/sei-cert/ctr/55
 * @kind problem
 * @problem.severity error
 * @tags sei-security
 */

import cpp

import semmle.code.cpp.dataflow.DataFlow
import semmle.code.cpp.exprs.ArithmeticOperation
import DataFlow::PathGraph

import itergator.ql.src.trailofbits.itergator.iterators

predicate isBinaryArithmeticOperator(Function fn) {
    exists( | (fn.hasName("operator+") or 
               fn.hasName("operator-") ) and 
               fn.getACallToThisFunction().getNumberOfArguments() > 0)
}


predicate hasArithmeticOperationPerformed(Variable e) {
    exists( Iterated vector_iterated_element, FunctionCall operator | 
            isBinaryArithmeticOperator(operator.getTarget()) and 
            vector_iterated_element.getTarget() = operator.getQualifier().(VariableAccess).getTarget() and 
            operator.getArgument(0) instanceof Literal and
            vector_iterated_element.getTarget() = e)
}

from Variable element
where hasArithmeticOperationPerformed(element)
select element, " has an arithmetic operation performed which may lead to out-of-bound access."
```

and here is the used [itergator](https://github.com/trailofbits/itergator/tree/978458c5c5791abac88de4b856859b77861b6ead) lib.

**Comment by aibaars** [comment]
I see  . Your select clause is fine. However you should remove the PathGraph import. That module defines some query predicates for the edges and nodes of the path graph. These query predicates are like additional select statements and these are expected for path-problem but not for  normal problem queries.

**Comment by MFaisalZaki** [comment]
You are right, I have removed the import statement and it worked fine. Do you have any kind of wiki to check for such cases?
