### ISSUE TITLE
How can I query some history version/commit of github repositories on LGTM.com?

### ISSUE THREAD

**Issue by cokeBeer** [github/codeql#9068]
I want to query history verison of openjdk, how can make this?

**Comment by smowton** [comment]
You'll need to create a database using `codeql database create -l java -c "... first build command here ..." -c "... second build command here ..."`, perhaps starting from https://github.com/openjdk/jdk checked out at the point in history you're interested in.

For example, on Ubuntu, to build JDK18 I found this worked:

1. Before building install packages `libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev libcups2-dev libasound2-dev`
2. Download JDK17 (boot JDK) and JDK18 (build JDK); set JDK17_HOME and JDK18_HOME to their respective JAVA_HOMEs
3. First build command: `bash configure --disable-javac-server --disable-generate-classlist --disable-cds-archive --disable-warnings-as-errors --with-num-cores=4 --with-boot-jdk=$JDK17_HOME --with-build-jdk=$JDK18_HOME`
4. Second build command: `make images`

**Comment by cokeBeer** [comment]
Thanks for your answer. I've already known some methods to create a database from openjdk locally. LGTM.com can really query the lastest version of openjdk/jdk directly by its own method to create database. Is it automatic or pre-created by developers? What about adding some famous version like JDK7 or JDK8 to LGTM.com 
 for security research? Querying on LGTM.com directly can be a helpful thing.
