### ISSUE TITLE
How to query types with a specific composite type in CodeQL Go?

### ISSUE THREAD

**Issue by cokeBeer** [github/codeql#9097]
I am working on defining a dataflow source for web framework Beego.
I tried this query on my project written in beego (https://github.com/cokeBeer/go-sec-code):
```ql
import go

from Type c
where  c.hasQualifiedName("go-sec-code/controllers", "CommandInjectVuln1Controller")
select c.getMethod("Get")
```
it turned out no results，but I do have a go-sec-code/controllers.CommandInjectVuln1Controller.Get Method
https://github.com/cokeBeer/go-sec-code/blob/main/controllers/commandInject.go#L23
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/70683161/167546653-40299221-7974-4ef5-977a-ca2b134d5994.png">
I think the problem may come from that Beego.Controller is a composite type which looks like:
```go
package controllers

import (
	"fmt"
	"go-sec-code/utils"
	"os/exec"

	beego "github.com/beego/beego/v2/server/web"
)

type CommandInjectVuln1Controller struct {
	beego.Controller
}
```
moreover, I've noted that there is a BeegoControllerSource in CodeQL Go standard library semmle.go.frameworks.Beego.qll.
<img width="745" alt="image" src="https://user-images.githubusercontent.com/70683161/167546986-227abf9a-d623-4d14-96bc-8f636ebc2897.png">
I tried only query the souce node with vscode's help on the same project, but it turned out not found GetString() method called
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/70683161/167547177-c644fbab-1760-4ae7-8f5a-3a750e08db46.png">

How can  I make a source defination that can find all Controllers that composite Beego.Controller?

**Comment by cokeBeer** [comment]
found that Beego's latest package name has became ""github.com/beego/beego/v2/server/web"
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/70683161/167559508-502036e4-0c19-4cae-8c16-18449b641b46.png">
After I add the package name, I can successfully query the results by BeegoControllerSource.
May I got a PR to fix it?

**Comment by smowton** [comment]
The guess there is that `Host` is often not user-controlled because the request had to somehow get routed here, whereas of course they do control other parts of the request.

Can I take it you've solved your Beego problem?

**Comment by cokeBeer** [comment]
@smowton yes,  seems I don't need to query a composite struct now. What about a PR to fix the module name "github.com/beego/beego/v2/server/web"?

**Comment by smowton** [comment]
Sure, please do submit one
