### ISSUE TITLE
LGTM.com - false positive in java/insecure-cookie rule

### ISSUE THREAD

**Issue by fabien-chebel** [github/codeql#9106]
**Description of the false positive**

The following Java code triggers the `java/insecure-cookie` CodeQL rule:

```java
public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response, Authentication authentication) throws ServletException, IOException {

        Cookie cookie = new Cookie("cookie-name", "yummy");
        cookie.setMaxAge(-1);
        cookie.setSecure(request.isSecure());
        cookie.setHttpOnly(true);
        cookie.setPath("/");
        response.addCookie(cookie);
    }
```

The alert is triggered on the following line:
```java
cookie.setSecure(request.isSecure());
```

If the request is run in a secure context (ie HTTPS), then the cookie is guaranteed to be flagged as secure.

An exception should be made in the rule to allow for a call to `javax.servlet.ServletRequest#isSecure` to be passed instead of `true`.

**URL to the alert on the project page on LGTM.com**

Not applicable, as the project is a private project running GHAS.

**Comment by smowton** [comment]
Seems like a reasonable complant; proposed fix: https://github.com/github/codeql/pull/9116

**Comment by smowton** [comment]
Fix merged; this should be fixed in the next release of CodeQL.

**Comment by fabien-chebel** [comment]
Awesome, thanks a bunch @smowton! 🙌
