### ISSUE TITLE
LGTM.com - false positive - Python - Explicit export is not defined

### ISSUE THREAD

**Issue by dlshriver** [github/codeql#9111]
**Description of the false positive**

The report says, `The name 'HpolyReductionError' is exported by __all__ but is not defined.`, pointing to line 657 of the file linked below. However the `HpolyReductionError` class is defined in the same file, beginning on line 49.

URL: https://lgtm.com/projects/g/dlshriver/dnnf/snapshot/adea1af854e38ba3a938a9093992f9d3a6ffc9ca/files/dnnf/reduction.py?sort=name&dir=ASC&mode=heatmap#xa98522da724b57b6:1

**Comment by alexet** [comment]
It seems like `HPolyReductionError` is defined but not `HpolyReductionError` which is what is exported. Note the capitalisation of the `P` differs between line 49 and `__all__`.

**Comment by dlshriver** [comment]
You are correct, thank you!
