### ISSUE TITLE
How to get the same security scans of CodeQL with Jenkins?

### ISSUE THREAD

**Issue by BOLT04** [github/codeql#9162]
**Description of the issue**
I'm investigating how to use CodeQL in a CI server outside GitHub, Jenkins. I'd like to know if we can get the same results that appear on GitHub's security tab but on Jenkins?

I looked up this [plugin for Jenkins](https://plugins.jenkins.io/codeql/) but couldn't find screenshots of the results, so I'm not sure I can get the same results as the GitHub's security tab which is already integrated with CodeQL.
I've also  seen the [docs available in here](https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/about-codeql-code-scanning-in-your-ci-system), but still would like to know if anyone has done this for Jenkins?

Any help is appreciated.
Thanks!

**Comment by hvitved** [comment]
Please be aware that if you are using CodeQL with Jenkins, that it is not in violation with the [license](https://codeql.github.com/docs/codeql-cli/getting-started-with-the-codeql-cli/). Specifically this bit:
```
CodeQL can’t be used for automated analysis, continuous integration or continuous delivery, whether as part of normal software engineering processes or otherwise, except in the express cases set forth herein.
```

**Comment by BOLT04** [comment]
hi @hvitved, just to be clear when you said "(...) that it is **not in violation** with the license", you meant that it **does violate** the license?

I hadn't checked but yeah it seems from that link it can't be used in Jenkins. Thank you for letting me know 👍
