### ISSUE TITLE
Java: Rename `FloatingPointLiteral` to `FloatLiteral`

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#9170]
Currently the CodeQL class modeling a Java `float` literal such as `0.1f` is called `FloatingPointLiteral`. This is rather confusing because "floating point" usually refers to the concept as a whole, and not to a specific data type (`double` or `float`). This is also how the [JLS uses this term](https://docs.oracle.com/javase/specs/jls/se18/html/jls-3.html#jls-3.10.2):

> A floating-point literal is of type `float` if it is suffixed with an ASCII letter `F` or `f`; otherwise its type is `double`

("floating-point literal" here covers both `float` and `double`)

Would it therefore make sense to rename `FloatingPointLiteral` to `FloatLiteral`, and to keep `FloatingPointLiteral` as deprecated alias for now?

**Comment by hvitved** [comment]
One for you @github/codeql-java .

**Comment by aschackmull** [comment]
Yes, that makes sense. PR welcome.

**Comment by Marcono1234** [comment]
Have created #9181
