### ISSUE TITLE
Is it possible to re-use databases for custom tools?

### ISSUE THREAD

**Issue by liona24** [github/codeql#9179]
Quick question: I was wondering if there is any (open-source) documentation for the databases created by `codeql database create ...` so that one might re-use it to create own analysis tools besides codeQL?

Since I find the extractor very handy, I could imagine the db being a nicer alternative to let's say a LLVM analysis pass for some high level tasks.

**Comment by hvitved** [comment]
If you are asking whether there is some documentation on the internal database format used by CodeQL, then the answer is no. The database uses proprietary technology, and should only be queried using CodeQL.

**Comment by liona24** [comment]
Thanks. I figured that this would be the case. Are there any plans to provide an API to access the internal data model?
Also: Is there any information on the user agreement of the internal database? I only seem to be able to find licensing documents regarding CodeQL?

**Comment by liona24** [comment]
Alright thanks for your answers.
