### ISSUE TITLE
Incorrect Integer Conversion Query appears to fail to capture integer parsing

### ISSUE THREAD

**Issue by tomtau** [github/codeql#9295]
Parsing signed integers consumes one bit less than their unsigned counterparts. The usage of [strconv.ParseUint](https://golang.org/pkg/strconv/#ParseUint) to parse a signed integer out of a string returns an unsigned 64-bit integer uint64. I'd expect the query to detect, for example, this uint64 if casted with the wrong constant bitsize:
```go
    u64, err := strconv.ParseUint(str, 10, 64)
    if err != nil {
        panic(err)
    }
    i64 := int64(u64)
```
which ideally should have been:
```go
    u64, err := strconv.ParseUint(str, 10, 63)
    if err != nil {
        panic(err)
    }
    i64 := int64(u64)
```

I'm not sure whether these cases are in that query's scope. If not, it may be worth adding a query that can capture these integer parsing-related conversion bug patterns.

**Comment by owen-mc** [comment]
This issue was addressed as part of [this PR](https://github.com/github/codeql/pull/13949).

**Comment by thediveo** [comment]
> It does apply in principle, though it seems a little niche given that the user could have simply used `ParseInt(...64)` there? Is this a pattern you've seen happen often?

I'm squatting that niche, too 😁
