### ISSUE TITLE
go-extractor happened `undeclared name: any` error

### ISSUE THREAD

**Issue by zchee** [github/codeql#9297]
My project update go1.18.x recently, and already set codeql scan.

But, when after the update go version to1.18, I found go-extractor has many error about `undeclared name: any` on GitHub Actions CodeQL log.

This is new type alias to `interface` type after the go1.18.
Also, I'd try to run CodeQL with debug mode, found below message. It seems to root cause is go1.15.15 haven't `any` type alias.

```
Autobuilder was built with go1.15.15, environment has go1.18.1
```

What should I do? Or, I should wait for new release about re-compile some codeql-go CLIs with latest Go version?

**Comment by smowton** [comment]
Closing as support is now rolled out.
