### ISSUE TITLE
Suppress warnings from Github

### ISSUE THREAD

**Issue by leoluz** [github/codeql#9298]
Hi!
I am trying to suppress a warning from what I understand a false positive zip-slip validation. We are using the GitHub Code Scanning job for running CodeQL. Even when I add the `// lgtm[go/zipslip]` tag in the code I still get the warning. 

Example case:
https://github.com/argoproj/argo-cd/pull/8789/checks?check_run_id=5574205353

Is `// lgtm` tags supported by Github Code Scanning jobs? If not, how could I suppress warnings in this case?

Thank you!

**Comment by smowton** [comment]
Closing as answered: no there isn't an inline comment mechanism for suppression in current code scanning, but manual dismissal via the UI can be done.

**Comment by aibaars** [comment]
You may want to use  https://github.com/advanced-security/dismiss-alerts to automate the task of dismissing alerts that have suppression markers in the code.
