### ISSUE TITLE
Newly-broken builds

### ISSUE THREAD

**Issue by smowton** [github/codeql#9304]
Likely a consequence of https://github.com/github/codeql-go/pull/554 there are two new classes of failure: segfaults and a no-source-code-found error. Lists of affected projects posted on Slack.

**Comment by owen-mc** [comment]
This issue was solved by reverting https://github.com/github/codeql-go/pull/554 in https://github.com/github/codeql-go/pull/572. There is a follow-up task to see if the problems can be fixed and this feature can be re-enabled: https://github.com/github/codeql-go-team/issues/282.
