### ISSUE TITLE
A fatal error occurred: Extractors for 'go' are found in several same-priority locations

### ISSUE THREAD

**Issue by tconnolly11** [github/codeql#9307]
I am following the directions listed [here](https://codeql.github.com/docs/codeql-cli/getting-started-with-the-codeql-cli/).

I am doing this on Mac, running 10.15.7.

These are the steps I've taken:

1. Downloaded CodeQL prebuilt binary (2.5.4) from [here](https://github.com/github/codeql-cli-binaries/releases/download/v2.5.4/codeql.zip)
2. Extracted CodeQL into ~/code-ql
3. Verified codeql  CLI is working:
`codeql % codeql version
CodeQL command-line toolchain release 2.5.4.
Copyright (C) 2019-2021 GitHub, Inc.
Unpacked in: /Users/tc/codeql
   Analysis results depend critically on separately distributed query and
   extractor modules. To list modules that are visible to the toolchain,
   use 'codeql resolve qlpacks' and 'codeql resolve languages'.`
4. Obtained local copies of both [codeql-repo](https://github.com/github/codeql) & [codeql-go](https://github.com/github/codeql-go) and installed them in ~/codeql/codeql-repo ~/codeql/codeql-go respectiveley
5. Ran `make` inside of ~/codeql-go
6. Ran `codeql resolve qlpacks` which resulted in `legacy-upgrades (/Users/tc/codeql/legacy-upgrades)`
7. Ran `codeql resolve languages` which resulted in:  
```
cpp (/Users/tc/codeql/cpp)
csharp (/Users/tc/codeql/csharp)
csv (/Users/tc/codeql/csv)
go is found in 2 same-priority locations, so attempts to resolve it will fail:
   /Users/tc/codeql/go
   /Users/tc/codeql/codeql-go
html (/Users/tc/codeql/html)
java (/Users/tc/codeql/java)
javascript (/Users/tc/codeql/javascript)
properties (/Users/tc/codeql/properties)
python (/Users/tc/codeql/python)
xml (/Users/tc/codeql/xml)

```
8. Attempted to do `codeql database create appdb --language=go` within the root directory of my Go project which resulted in:
```
Initializing database at /Users/tc/go/horizon/appdb
A fatal error occurred: Extractors for 'go' are found in several same-priority locations. It is unclear which to use:
   /Users/tc/codeql/go
   /Users/tc/codeql/codeql-go
```
Is there something I'm missing? At a minimum, I think the documentation [here](https://codeql.github.com/docs/codeql-cli/getting-started-with-the-codeql-cli/) could be updated to make it more clear. Thanks!

**Comment by adityasharad** [comment]
Closing: I believe the docs now explain the intended layout, and since we have merged `codeql-go` into `codeql` there will soon be no need to check out both repos.
