### ISSUE TITLE
usage of syscall/js causes codeql analysis to fail

### ISSUE THREAD

**Issue by adamdecaf** [github/codeql#9311]
Including `syscall/js` for cross-compiling Go code for WASM support seems to cause codeql to fail. It appears to not support that build tag.  I [have a PR which adds WASM support](https://github.com/moov-io/imagecashletter/pull/116) for a project of mine that's failing.

Here's an instance of codeql failing to analyze the file. https://github.com/moov-io/imagecashletter/runs/990572783?check_suite_focus=true

```
exit status 1: go build syscall/js: build constraints exclude all Go files in /opt/hostedtoolcache/go/1.14.7/x64/src/syscall/js
```

**Comment by smowton** [comment]
Closing as the workaround did the trick and Golang build tracing is now available for more complex cases.
