### ISSUE TITLE
LGTM.com - alert suppression at source

### ISSUE THREAD

**Issue by sergefdrv** [github/codeql#9383]
There is an alert suppression comment at the source of the alert (Step 1), LGTM.com nevertheless reports an alert.

[**URL to the alert on the project page on LGTM.com**](https://lgtm.com/projects/g/filecoin-project/mir/snapshot/bd5318f7432d45080fea97a4796b6f7f49671a69/files/pkg/crypto/ecdsa.go?sort=name&dir=ASC&mode=heatmap#x25fd22aca0e057e5:1)

How could one suppress alerts for specific paths only?

**Comment by aibaars** [comment]
The suppression comment needs to be on the line where the alert is reported. Unfortunately, you cannot suppress (parts) of a flow path.

**Comment by sergefdrv** [comment]
> cannot suppress (parts) of a flow path

Is there already such feature request?

**Comment by aibaars** [comment]
> > cannot suppress (parts) of a flow path
> 
> Is there already such feature request?

It has been requested in the past, although I'm not sure if there is an issue ticket already. That said, there is hardly any new feature development for LGTM.com as the focus is on [GitHub CodeScanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-alerts) .

**Comment by sergefdrv** [comment]
> > > cannot suppress (parts) of a flow path
> > 
> > Is there already such feature request?
> 
> It has been requested in the past, although I'm not sure if there is an issue ticket already. That said, there is hardly any new feature development for LGTM.com as the focus is on [GitHub CodeScanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-alerts) .

Is this supported in GitHub Code Scanning?

**Comment by intrigus-lgtm** [comment]
> > > cannot suppress (parts) of a flow path
> > 
> > 
> > Is there already such feature request?
> 
> It has been requested in the past, although I'm not sure if there is an issue ticket already. That said, there is hardly any new feature development for LGTM.com as the focus is on [GitHub CodeScanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-alerts) .

https://github.com/github/codeql/issues/3252 seems to be a similar feature request.
