### ISSUE TITLE
Lower and upper bounds for array offsets are not detected properly

### ISSUE THREAD

**Issue by MFaisalZaki** [github/codeql#9414]
I have written this query to detect out-of-range array indexing:
``` 

import cpp
import egcert.helpers.generichelpers
import semmle.code.cpp.rangeanalysis.SimpleRangeAnalysis

predicate isAToolchainLocation(Location l) {
    l.getContainer().getParentContainer+().getBaseName().matches("Program Files (x86)")
}

predicate hasPossibleNegitiveIndexing(Element ele) {
  exists( ArrayExpr array_access | ele = array_access and 
                                   (lowerBound(array_access.getArrayOffset()) < 0
                                    or
                                    upperBound(array_access.getArrayOffset()) > upperBound(array_access)
                                   )  and 
                                   not isAToolchainLocation(array_access.getArrayOffset().getLocation()))
  or
  exists( OverloadedArrayExpr index_operator | ele = index_operator and 
                                               (lowerBound(index_operator.getArrayOffset()) < 0
                                               or
                                                upperBound(index_operator.getArrayOffset()) > upperBound(index_operator)
                                               ) and 
                                               not isAToolchainLocation(index_operator.getLocation()))
}

from Element var
where hasPossibleNegitiveIndexing(var) 
select var, "Their is a potential of negitve value addressing invoked."


```
and it detects this code snippet even though this is a valid range for `i` (i.e. have a positive values only + loops from `[0, size(str)[` ):

``` 
                string str("AAAAABBCCCDDDD");
                int all_bucket[256];
                for (std::size_t i = 0; i < str.size(); i++) {
                    all_bucket[static_cast<unsigned char>(str[i])] += 1;
                }
```

another pattern is
```
    string my_array[5] = {"A", "B", "C", "D", "E"};
    map<int, double> my_array_attr({0, 1}, {1, 1}, {2, 1}, {3, 1}, {4, 1}); 
    size_t i = 0;
    for (auto a : my_array) {
        cout << my_array_attr[i++] << endl;
    }
```
So in this pattern is it possible to link between `i` and `a` values range since both can be computed statically?

One more pattern:
```
const string list[5] = { "A", "B", "C" , "D", "E"};

int find_index(string str) {
   int i = 0;  
   for (auto a: list ) {
      if (a == str) { return i;}
      i++;
   }
   return -1;
}

int main() {
    int i = find_index("F");
    if (i != -1) {
        cout << "found element: " << list[i] << endl;
    } else {
       cout << "not found" << endl;
    }
}
```
In this pattern it is impossible to have an invalid array access, so what has went wrong.

Another issue, is there a better way to filter out files located inside the compiler's std libraries. For me I have created the `isAToolchainLocation` predicate in order to remove compiler's C++ files.

**Comment by tausbn** [comment]
Thank you for your question!

In general, I don't think you can expect the `SimpleRangeAnalysis` to provide exact bounds, as it may apply [widening](https://codeql.github.com/codeql-standard-libraries/cpp/semmle/code/cpp/rangeanalysis/SimpleRangeAnalysis.qll/module.SimpleRangeAnalysis.html) to the bounds it infers.

There is an experimental library for range analysis that may have more accurate results. You may find it here: https://github.com/github/codeql/blob/main/cpp/ql/lib/experimental/semmle/code/cpp/rangeanalysis/RangeAnalysis.qll

(cc. @github/codeql-c-analysis in case they have more specific comments on this issue.)

**Comment by MFaisalZaki** [comment]
@tausbn great, I'll give it a try. As for compiler files how can K filter them out if possible? 

Thanks
