### ISSUE TITLE
No code found during the build for multi-module java projects

### ISSUE THREAD

**Issue by shivani-rana-gss** [github/codeql#9534]
**Description of the issue**
when configuring codeql for a multi-module java project (where source code is under example/src etc rather than src) I am getting following error **No code found during the build**. I couldn't find any documentation or examples where I can define an alternate source path to make codeql scanner aware about the correct src path

**Comment by smowton** [comment]
Are you using Code Scanning or the CLI?

If Code Scanning, try replacing the default `autobuild` step with manual steps to build your code, as per https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-the-codeql-workflow-for-compiled-languages#adding-build-steps-for-a-compiled-language

**Comment by shivani-rana-gss** [comment]
Hi @smowton yes I am using code scanner and have tried replacing the auto build with a gradle build as below, but still the issue is same:
`jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: ./gradlew --no-daemon clean
            - uses: github/codeql-action/init@v2
              with:
                  languages: 'java'
            - uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '17'
                  cache: 'gradle'
            - name: Build
              run: ./gradlew build
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v2`

**Comment by shivani-rana-gss** [comment]
hi @smowton unfortunately the repo cant be made public, but below is the screenshot from the run with more details

![image](https://user-images.githubusercontent.com/34452354/173406337-8907d145-bc36-4baa-ac63-95a07400ff22.png)

**Comment by shivani-rana-gss** [comment]
And successful run with the same config but where I have code under src instead of example/src 

![image](https://user-images.githubusercontent.com/34452354/173406798-cd48df7c-c24b-47b6-a4ab-f248e35fa351.png)

**Comment by smowton** [comment]
It's the step above I'd need to see, the one where the code gets built between the `codeql-action/init` and the `codeql-action/analyze` steps.

**Comment by shivani-rana-gss** [comment]
Thanks @smowton for pointing me to the right direction as suspected by you the issue was with build.gradle.
