### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by jlaehne** [github/codeql#9584]
**Description of the false positive**

The local variable 'integration_time' assigned here is used on line 150.

[**URL to the alert on the project page on LGTM.com**](https://lgtm.com/projects/g/LumiSpy/lumispy/snapshot/4367ba0a41f5d69a19c1892b6589859aaab09a1b/files/lumispy/signals/common_luminescence.py?sort=name&dir=ASC&mode=heatmap#x85db9c69dcb4b846:1)

**Comment by hmakholm** [comment]
But line 150 is not reachable from the assignment, due to the raise in line 129.
