### ISSUE TITLE
LGTM.com - false positive - Typescript `(infer T extends U)` pattern should be valid.

### ISSUE THREAD

**Issue by Jym77** [github/codeql#9621]
**Description of the false positive**
[This alert](https://github.com/Siteimprove/alfa/security/code-scanning/330) is flagging a missing `?` in a `(infer T extends Value)` TypeScript pattern, likely expecting the `extends` keyword to be part of a ternary `extends Value ? … : …` construction.
The `infer T extends Value` pattern is valid TypeScript that I was told to use as a workaround to a TS error, see [this TS issue](https://github.com/microsoft/TypeScript/issues/49517#issuecomment-1154234114).

So, I guess this should be considered as valid syntax.

**URL to the alert on the project page on LGTM.com**
(tried to, but the alert is currently on a branch and I couldn't find how to tell LGTM.com to hook up on a branch rather than the latest released version 😕 )

**Comment by erik-krogh** [comment]
Your example is only valid in TypeScript 4.7, and the code-scanning workflow was using TypeScript 4.6, which caused the error.  

We already have support for TypeScript 4.7, but that was only released as of 2.9.4 (released 3 hours ago).  
It will still take a while before 2.9.4 is used in your code-scanning workflows.  

The alert should fix itself once you run an analysis using the new 2.9.4 version of CodeQL.   

So thanks for the report, but it has already been fixed.
