### ISSUE TITLE
LGTM.com - false positive - Python - Sensitive data (certificate)

### ISSUE THREAD

**Issue by hillmich** [github/codeql#9632]
**Description of the false positive**
Alert 

> `Sensitive data (certificate)` is logged here.

is shown, although no certicates are handled.

I assume this flagged since there's `cert` in the variable name `num_uncertainty`.

**URL to the alert on the project page on LGTM.com**
- https://lgtm.com/projects/g/cda-tum/MQTBench/snapshot/49fad76fe6586a445c46977ec68dbcf8afff9306/files/mqt/bench/benchmark_generator.py?sort=name&dir=ASC&mode=heatmap#x6ebc1d98f30cccbd:1
- https://lgtm.com/projects/g/cda-tum/MQTBench/snapshot/49fad76fe6586a445c46977ec68dbcf8afff9306/files/mqt/bench/benchmark_generator.py?sort=name&dir=ASC&mode=heatmap#x1ef783754ffa2c2f:1

**Comment by RasmusWL** [comment]
Hi @hillmich, I agree that this looks odd. I'll take a look :+1:

**Comment by RasmusWL** [comment]
Made a fix for this in https://github.com/github/codeql/pull/9649. Once that is merged, it will take a few weeks to make it live on LGTM.com and Code Scanning.
