### ISSUE TITLE
LGTM.com - false positive C++ "Missing return statement"

### ISSUE THREAD

**Issue by thomaslepoix** [github/codeql#9721]
As in [this example](https://lgtm.com/projects/g/Open-RFlab/openemsh/snapshot/37a17c9a158ee6123b7d3312c4ec60332eb62946/files/src/domain/geometrics/relation.cpp?sort=name&dir=ASC&mode=heatmap#x1b6ff311375c593c:1), a `switch` that `return` on each possible value of an `enum class` (and thus without any `default` label) does not leave any other path for a missing return statement in the function.

**Comment by aibaars** [comment]
That looks like a false positive indeed. Thanks for reporting.

**Comment by sashabu** [comment]
This is a true positive. Scoped enumerations (`enum class`) lack the _implicit_ conversions that unscoped enumerations have, but non-enumerated values can still be valid. For example, `std::byte` is [defined](https://eel.is/c++draft/cstddef.syn) as `enum class byte : unsigned char {};` (with some operator overloads, but no enumerators).

https://eel.is/c++draft/dcl.enum#8 details the valid values of an enumeration (emphasis added):
> For an enumeration whose underlying type is fixed, the values of the enumeration are the values of the underlying type. Otherwise, the values of the enumeration are the values representable by a hypothetical integer type with minimal width M such that all enumerators can be represented. The width of the smallest bit-field large enough to hold all the values of the enumeration type is M. **It is possible to define an enumeration that has values not defined by any of its enumerators.** If the enumerator-list is empty, the values of the enumeration are as if the enumeration had a single enumerator with value 0.

https://eel.is/c++draft/expr.static.cast#10 details how to actually obtain those non-enumerated values.
> A value of integral or enumeration type can be explicitly converted to a complete enumeration type. If the enumeration type has a fixed underlying type, the value is first converted to that type by integral promotion ([conv.prom]) or integral conversion ([conv.integral]), if necessary, and then to the enumeration type. If the enumeration type does not have a fixed underlying type, the value is unchanged if the original value is within the range of the enumeration values ([dcl.enum]), and otherwise, the behavior is undefined. A value of floating-point type can also be explicitly converted to an enumeration type. The resulting value is the same as converting the original value to the underlying type of the enumeration ([conv.fpint]), and subsequently to the enumeration type.

(Note that https://eel.is/c++draft/dcl.enum#5 explains that the underlying type for a scoped enum is _always_ fixed - and defaults to `int` if not specified.)

There are two ways to avoid this alert:
1. Add a `default` label. This prevents static analysis tools from telling you whether the rest of the cases are "exhaustive" (in the domain model - as per above, they're not exhaustive in the C++ model): but this may be a good thing as it means the team responsible for maintaining the enumeration type doesn't become automatically responsible for updating all users with broken warnings-as-errors builds if they need to add an enumerator.
2. Add handling after the `switch` statement.

In either case, the "handling" can simply be an `std::abort` call if that's what makes the most sense in the given application.

**Comment by thomaslepoix** [comment]
Damn! Thank you.
