### ISSUE TITLE
Mixing taint tracking and control flow analysis

### ISSUE THREAD

**Issue by ledstobstec** [github/codeql#9752]
Hi, I'm trying to use codeql to find the following code patterns:
```
function foo() {
    $a = func1();

    // make sure there isn't a call to func2($a);

    return -1;
}
```
How is it possibile to achieve this? I tried different things, but I'm stuck at trying to mix the control flow analysis needed to find the paths from `func1()` to `return -1` and the taint tracking needed to make sure `func2($a)` is not being called with the return value of `func1()`.

For example this code should be valid as if `$x is <= 0` then `func2()` won't be called with the return argument of `func1`:
```
function foo($x) {
    $a = func1();

    if ($x > 0) {
        func2($a);
    }

    return -1;
}
```

**Comment by ledstobstec** [comment]
For example, this finds the paths from `func1()` to `return -1`
```
from FunctionCall func1, ReturnStmt ret
where
  func1.getTarget().getName() = "func1"
  and func1.getASuccessor+() = ret
  and ret.getExpr().getValue().toInt() = -1
select
  func1.getLocation(), ret.getLocation()
```

Then to account for the potential call to `func2($a)` I tried something like:
```
from FunctionCall func1, FunctionCall func2, Expr var, ReturnStmt ret
where
  func1.getTarget().getName() = "func1"
  and func2.getTarget().getName() = "func2"
  and func1.getASuccessor+() = ret
  and ret.getExpr().getValue().toInt() = -1
  and var = func2.getArgument(0)
  and not TaintTracking::localExprTaint(func1, var)
select
  func1.getLocation(), ret.getLocation()
```

Which clearly doesn't work as `not TaintTracking::localExprTaint(func1, var)` will be `false` if there is at least one flow that calls `func2`.

**Comment by ledstobstec** [comment]
Hi, thanks for the answer. To me, it looks like that query has the same problem as the one I posted in my 2nd comment.
Because I'm not looking for functions that do not have any possibile flows from `$x = func1()` to `func2($x)`, but for functions that have at least one flow from `$x = func1()` to `return -1` without hitting `func2($x)` .
For example the following code is not matched by that query, but it should, because depending on `argc` there is a possibile flow that doesn't hit `func2`:
```c
int func1() { return 1; }

void func2(int x) {}

int main(int argc, char **argv) {
  int x = func1();

  if (argc) {
    func2(x);
  }

  return -1;
}
```

> I think there are two problems with the query above. Firstly it won't report any results if there is no call to `func2` anywhere in the code base. Secondly, it will return results if there is some unrelated call to `func2` somewhere else in the code base (because there won't be any local flow).
> 
> I think you meant to write something like the following:
> 
> ```ql
> from FunctionCall func1, ReturnStmt ret
> where
>   func1.getTarget().getName() = "func1" and
>   func1.getASuccessor+() = ret and
>   ret.getExpr().getValue().toInt() = -1 and
>   not exists(FunctionCall func2 | 
>     func2.getTarget().getName() = "func2" and
>     TaintTracking::localExprTaint(func1, func2.getArgument(0)))
> select func1.getLocation(), ret.getLocation()
> ```

**Comment by aibaars** [comment]
Ah, I see what you mean. What about doing the dataflow first and using that to filter out certain nodes in the control flow? That is first compute the `func2` nodes that can be tainted, and then try to find a control flow path to a return statement that does not flow through any of the tainted `func2` nodes.

Something like this (untested) 

```ql
FunctionCall taintedFunc2(FunctionCall func1) {
 result.getTarget().getName() = "func2" and
    TaintTracking::localExprTaint(func1, result.getArgument(0))
}

ControlFlowNode successors(ControlFlowNode func1) {
    result = func1
    or
    exists(ControlFlowNode mid | mid = successors(func1) and
      result = mid.getASuccessor() and not result = taintedFunc2(func1)
    )
}

from FunctionCall func1, ReturnStmt ret
where
  func1.getTarget().getName() = "func1" and
  successors(func1) = ret and
  ret.getExpr().getValue().toInt() = -1
select func1.getLocation(), ret.getLocation()
```

**Comment by ledstobstec** [comment]
Thanks, that looks exactly what I needed :)
