### ISSUE TITLE
JavaScript: RemoteFlowSource does not seem to pick up data fetched from path

### ISSUE THREAD

**Issue by eoftedal** [github/codeql#9760]
When used with node.js and express.js, RemoteFlowSource picks up access to `req.query` and `req.params` as sources, but does seem to pick up direct access to `req.path`:
```
app.get("/docs/*", async (req, res) => {
  const u = req.path;
  ...
});
```
I would expect u to be marked as a source here:
```
from RemoteFlowSource f 
select f
```

**Comment by aibaars** [comment]
This should be fixed by https://github.com/github/codeql/pull/14643 .
