### ISSUE TITLE
C++ Call Target Predicates with Polymorphism

### ISSUE THREAD

**Issue by bdrodes** [github/codeql#9784]
I'm experimenting with getting the target function for virtual function calls in C++. The documentation for `FunctionCall` suggests that `getTarget()` should return the 'most-specific function in the override tree', but I'm not sure if that is the behavior I'm observing.

In the example below, I have three calls, where I would expect the target for `CALL1` to be a the `ChildClass` target, `CALL2` the ParentClass target, and `CALL3`to be potentially from both `ChildClass` and `ParentClass`. In all cases, however, codeql reports the target as being the `ParentClass` function. Is that the expected result to `getTarget()` for `FunctionCall`, and is there a way to get my expected result with codeql?

```
#include <iostream>
#include <cstdlib>

using namespace std;

class ParentClass
{
	public:
		virtual char* test_func()
		{
			return "PARENT: test_func";
		}

};

class ChildClass: public ParentClass
{
	public:
		virtual char* test_func()
		{
			return "CHILD: test_func";
		}

};


int main(int argc, char** argv)
{

    ParentClass *c;
    if(argc > 1)
    {
        c = new ChildClass();
       // CALL1
        c->test_func();
    }
    else
    {
        c = new ParentClass();
        // CALL2
        c->test_func();
    }

    // CALL3
    c->test_func();
}
```

**Comment by jketema** [comment]
> The documentation for `FunctionCall` suggests that `getTarget()` should return the 'most-specific function in the override tree', but I'm not sure if that is the behavior I'm observing.

This will be based on the static class type of the expression that `FunctionCall:getQualifier` yields. So, in your case this will be the base type of `c`, i.e., `ParentClass`.

> is there a way to get my expected result with codeql?

I could not find any library functionality that we have and that we expose to users that does this. Although I've overlooked things before. However, what you can do is leverage the data flow library:

```codeql
import cpp
import semmle.code.cpp.dataflow.DataFlow

class VirtualCallConfiguration extends DataFlow::Configuration {
  VirtualCallConfiguration() { this = "VirtualCallConfiguration" }

  override predicate isSource(DataFlow::Node source) { source.asExpr() instanceof NewExpr }

  override predicate isSink(DataFlow::Node sink) {
    exists(FunctionCall fc | sink.asExpr().(VariableAccess) = fc.getQualifier())
  }
}

VirtualFunction getCalledFunction(VariableAccess va) {
  exists(DataFlow::Node new, DataFlow::Node access, Configuration conf, FunctionCall fc |
    conf.hasFlow(new, access) and
    va = access.asExpr() and
    va = fc.getQualifier() and
    result = fc.getTarget().(VirtualFunction).getAnOverridingFunction*() and
    result.getDeclaringType() = new.asExpr().(NewExpr).getAllocatedType()
  )
}

from VariableAccess va, MemberFunction m
where m = getCalledFunction(va)
select va, m
```

For your example this gives me:
```
| test.cpp:30:9:30:9 | c | test.cpp:14:17:14:25 | test_func |
| test.cpp:36:9:36:9 | c | test.cpp:4:17:4:25 | test_func |
| test.cpp:40:5:40:5 | c | test.cpp:4:17:4:25 | test_func |
| test.cpp:40:5:40:5 | c | test.cpp:14:17:14:25 | test_func |
```

**Comment by jketema** [comment]
Note that I have *not* tested the above with an inheritance hierarchy in which some classes do not override a specific virtual function. The CodeQL might need some tweaking to handle that. I'm of course happy to help if necessary.
