### ISSUE TITLE
How to tainttracking Properties#getProperty(key,defaultvalue) method correctly

### ISSUE THREAD

**Issue by nbxiglk0** [github/codeql#9814]
When i use codeql to analysis a java programme, i find it can TaintTracking Properties#get(key) method
correcttly but ignore Properties#getProperty(key,defaultvalue) method in half way, it will lead to a misreport, should i add some addtionnal step to make the dataflow correcttly?   

example: TaintTracking Properties#get(key) method correcttly.
![image](https://user-images.githubusercontent.com/24366795/178644771-24bc8f0b-5429-4d88-b7c7-0cc2db02d162.png)  
but ignore Properties#getProperty(key,defaultvalue) method like this pic,it can't tracking to this location
![image](https://user-images.githubusercontent.com/24366795/178646921-190cbc43-8f63-456a-98ba-7127baf86b57.png)

**Comment by smowton** [comment]
True enough -- `get` is modelled thanks to Properties inheriting the method from `Hashtable`; here's a fix to also model those methods only defined on `Properties`: https://github.com/github/codeql/pull/9817

**Comment by smowton** [comment]
Fix committed to `github.com/github/codeql`'s `main`, and will be in the next release.
