### ISSUE TITLE
Please disable analysis of python code in project KDE/KPhotoAlbum

### ISSUE THREAD

**Issue by jzarl** [github/codeql#9861]
Hi,

We've removed all python code from our repository some time ago, but I don't see any possibility to disable the language using a lgtm.yaml file or any other way.

Can you please remove the language manually from the project?

https://lgtm.com/projects/g/KDE/kphotoalbum/

**Comment by edoardopirovano** [comment]
Greetings, thanks for getting in touch about this. I can confirm we have manually removed Python from your project. Do let us know if you need anything else!
