### ISSUE TITLE
no source code was seen when "codeql database create openssl-increment --language=cpp --command=make"

### ISSUE THREAD

**Issue by hyperlyz** [github/codeql#9882]
I firstly complied a project without codeql, and then modified a file.
But, When I executed "codeql database create increment --language=cpp --command=make", I get a error about
![image](https://user-images.githubusercontent.com/20871123/180429907-58e96040-dc34-4ebd-8b42-4e862c932df8.png)
My version is
![image](https://user-images.githubusercontent.com/20871123/180430079-e0a125c1-6f73-4842-bf76-3f6e4fe68098.png)
My log is
[log.zip](https://github.com/github/codeql/files/9167338/log.zip)

**Comment by aibaars** [comment]
CodeQL database creation is unfortunately not incremental. So if you only partially build your code you end up with a partial database. 

That said, I would not expect the "no source code seen" error message, because you changed a file and the build log suggests that one file got compiled:
```
[2022-07-22 19:26:21] [build-stdout] gcc  -I. -Iinclude ...  crypto/x509/v3_utl.c
```
Looking in the `build-tracer.log` for reasons why this file was not put in the database I see:
```
[E 19:26:21 1162019] Command: /data2/fullway/codeql/codeql/cpp/tools/linux64/extractor --mimic /usr/bin/ccache -I. -Iinclude ... crypto/x509/v3_utl.c
...
[T 19:26:21 1162020] ==== Candidate to intercept: /usr/bin/ccache (canonical: /usr/bin/ccache) ====
[T 19:26:21 1162020] === Intercepted call to /usr/bin/ccache === 
[E 19:26:21 1162025] Mimicry classification suppression detected; exiting.
[T 19:26:21 1162023] Extractor terminated with exit code 0.
Warning: /usr/bin/ccache does not look like a compiler. If it is infact a compiler, please contact GitHub.
```
It looks like your build runs `ccache` instead of `gcc` and CodeQL does not detect this as a compiler and therefore skips the file.

**Comment by hyperlyz** [comment]
> CodeQL database creation is unfortunately not incremental. So if you only partially build your code you end up with a partial database.
> 
> That said, I would not expect the "no source code seen" error message, because you changed a file and the build log suggests that one file got compiled:
> 
> ```
> [2022-07-22 19:26:21] [build-stdout] gcc  -I. -Iinclude ...  crypto/x509/v3_utl.c
> ```
> 
> Looking in the `build-tracer.log` for reasons why this file was not put in the database I see:
> 
> ```
> [E 19:26:21 1162019] Command: /data2/fullway/codeql/codeql/cpp/tools/linux64/extractor --mimic /usr/bin/ccache -I. -Iinclude ... crypto/x509/v3_utl.c
> ...
> [T 19:26:21 1162020] ==== Candidate to intercept: /usr/bin/ccache (canonical: /usr/bin/ccache) ====
> [T 19:26:21 1162020] === Intercepted call to /usr/bin/ccache === 
> [E 19:26:21 1162025] Mimicry classification suppression detected; exiting.
> [T 19:26:21 1162023] Extractor terminated with exit code 0.
> Warning: /usr/bin/ccache does not look like a compiler. If it is infact a compiler, please contact GitHub.
> ```
> 
> It looks like your build runs `ccache` instead of `gcc` and CodeQL does not detect this as a compiler and therefore skips the file.

What should I do to solve this problem?

**Comment by aibaars** [comment]
> What should I do to solve this problem?

A quick solution would be to set `CCACHE_DISABLE=true`

**Comment by hyperlyz** [comment]
> CCACHE_DISABLE=true

Thanks very much.
