### ISSUE TITLE
Barrier Guard Mechanics

### ISSUE THREAD

**Issue by bdrodes** [github/codeql#9885]
I have experimented with barrier guards in my data flow queries, but I need to clarify the semantics of the `checks` operation being overridden by my guard. 

The commented documentation says the following:
```
/** Override this predicate to hold if this guard validates `e` upon evaluating to `b`. */
  abstract predicate checks(Expr e, boolean b);
```

What I'm wondering is, must `e` be controlled by the guard or can `e` be anything? 

For example, I'd like to have my guard use the SSA definition of a variable declared/defined outside of the guard as `e`. I want dataflow to continue through control flow in which the guard check was never applied. In my experimentation so far, I am seeing mixed results, so its unclear if I'm using barrier guard correctly or not, or if the semantics of the guard allow for the kind of flow I'm trying to achieve.

**Comment by smowton** [comment]
Can you post a small example of the mixed results you mention? What are you expecting to see, and what are you actually seeing?

**Comment by bdrodes** [comment]
Sorry for the delayed response. I went back to the drawing board to check my assumptions on barrier guard mechanics. I think I largely have the wrong concept initially.

One thing that would be helpful to confirm is for the `checks` predicate, is the relationship of the checked Expr to the dataflow through SSA def/use, i.e., can I expect that expr `e` is a use of some definition where that definition is shared in some dataflow path?

**Comment by smowton** [comment]
The exact implementation seems to vary from language to language, but the short answer is probably yes, there needs to be an SSA relationship between the checked thing and the use that is sanitized. For example in Java we have

```ql
  /** Gets a node guarded by this guard. */
  final Node getAGuardedNode() {
    exists(SsaVariable v, boolean branch, RValue use |
      this.checks(v.getAUse(), branch) and
      use = v.getAUse() and
      this.controls(use.getBasicBlock(), branch) and
      result.asExpr() = use
    )
  }
```

**Comment by bdrodes** [comment]
Thanks. I think that probably addresses most of what I need for now. I'll close the issue.
