### ISSUE TITLE
LGTM.com - false positive - Dereferenced variable may be null

### ISSUE THREAD

**Issue by clesaec** [github/codeql#9901]
**Description of the false positive**
In Java Unit test (JUnit5), i have this code 
```java
    assertNotNull(error);
    assertEquals("an error", error.getMessage$());
```
if error is null, "assertNotNull" will throw an exception and second line will never be called; but CodeQL give me an alert on it.

**Comment by aschackmull** [comment]
Thank you for the report. The method `AssertNotNull` was moved to a different package name in JUnit5 relative to JUnit4, so we just need to account for that. Fix is here: https://github.com/github/codeql/pull/9902
