### ISSUE TITLE
LGTM.com - false positive top-level "for await" syntax error [JS]

### ISSUE THREAD

**Issue by leibale** [github/codeql#9957]
**Description of the false positive**

"Syntax error" for top-level "for await". "normal" top-level await works as expected.

https://lgtm.com/projects/g/redis/node-redis/snapshot/ae44ac1e1a95ebddbba290195fee840d57b04911/files/examples/set-scan.js?sort=name&dir=ASC&mode=heatmap#xf9cc4b8fc3a288c5:1

**Comment by hmakholm** [comment]
Thanks for the report. It looks like a parser bug. We'll take a look.
