### ISSUE TITLE
CPP: Taint Tracking Sources as Ref Args

### ISSUE THREAD

**Issue by bdrodes** [github/codeql#9996]
I'm trying to mark out parameters of a specific call as a source in my taint tracking query. For example, argument 2 (0-based, i.e., 'z') in the below example.
```
MyFunc(x, y, &z);
return z;
```

What I have found is I can't simply state that the source is the 2nd argument to any function call called 'MyFunc'. E.g., something like this:

```
override predicate isSource(DataFlow::Node source) 
{
    exists(Call c | c.getTarget().getName() = "MyFunc" and source.asExpr() = c.getArgument(2))
}

```

If I do, no paths are found, not even when I set the sink as the return immediately following the call. Experimenting, I found that there appears to be no 'Expr' that will trace, but there is a DataFlow::Node that does (see below). 

```
override predicate isSource(DataFlow::Node source) 
{
     // WORKS:
     // Point to the line of the call in question, and a DataFlow::Node is found that will trace
     source.getLocation().getStartLine() = 76

    // DOESN'T WORK
    // I conclude there is no expression at the call that is traceable
    // source.asExpr().getLocation().getStartLine() = 76
}

```

In my output, it says the DataFlow::Node that does trace is called `ref arg &`. The problem I'm now having is I need to associate the DataFlow::Node to an expression in my call, so I get the specific arguments to the specific functions I want, but as I have found, there seems to be no expression I can map too to complete my query. What am I doing wrong?

**Comment by MathiasVP** [comment]
Hi @bdrodes,

To mark the value of an argument after it's been updated by a function call you can use `Node.asDefiningArgument()`. Running the following example:
```ql
import cpp
import semmle.code.cpp.dataflow.DataFlow::DataFlow
import PathGraph

class Conf extends Configuration {
  Conf() { this = "Conf" }

  override predicate isSource(Node source) {
    source.asDefiningArgument() = any(Call call | call.getTarget().hasName("MyFunc")).getArgument(2)
  }

  override predicate isSink(Node sink) {
    sink.asExpr() = any(Call call | call.getTarget().hasName("sink")).getAnArgument()
  }
}

from Conf conf, PathNode source, PathNode sink
where conf.hasFlowPath(source, sink)
select sink.getNode(), source, sink, "Flow from the 2nd (3rd) argument of 'MyFunc' to 'sink'."

```
on this snippet:
```cpp
void MyFunc(int x, int y, int* z);
void sink(int);

void test() {
  int x, y, z;
  MyFunc(x, y, &z);
  sink(z);
}
```
gives:

<img width="823" alt="Screenshot 2022-08-09 at 15 27 08" src="https://user-images.githubusercontent.com/4527323/183674980-f9b48fa8-f0f7-44e3-ac29-20e540915bcb.png">

**Comment by bdrodes** [comment]
Yea no sooner than I opened this issue I had stumbled onto asDefiningArgument separately too. Thanks for your quick response, that solved my problem.
